### PR TITLE
Fix getSchema while trx on postgres

### LINKED ISSUE #8176: Not having PostGIS enabled breaks schema apply
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Using a docker compose with Directus rc.93 and vanilla Postgres. 

Applying a snapshot results with the following outputs:
```
docker-compose exec directus npx directus schema apply ./schemas/schema.yml   
22:35:59 ✨ Loaded extensions: picker, test-hook, banners
? The following changes will be applied:



Fields:
  - Delete test.new

Would you like to continue? Yes
22:36:02 🚨 error 
        SELECT c.table_name
          , c.column_name
          , c.column_default as default_value
          , c.data_type
                                        , c.character_maximum_length as max_length
          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity
          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       - current transaction is aborted, commands ignored until end of transaction block 
error: 
        SELECT c.table_name
          , c.column_name
          , c.column_default as default_value
          , c.data_type
                                        , c.character_maximum_length as max_length
          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity
          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       - current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```
In the Postgres logs I see this:
```
database    | 2021-09-20 22:35:59.327 UTC [45] ERROR:  relation "geometry_columns" does not exist at character 42
database    | 2021-09-20 22:35:59.327 UTC [45] STATEMENT:  
database    |                   WITH geometries as (
database    |                           select * from geometry_columns
database    |                           union
database    |                           select * from geography_columns
database    |                   )
database    |           SELECT f_table_name as table_name
database    |                           , f_geometry_column as column_name
database    |                           , type as data_type
database    |           FROM geometries g
database    |           JOIN information_schema.tables t
database    |                   ON g.f_table_name = t.table_name
database    |                   AND t.table_type = 'BASE TABLE'
database    |           WHERE f_table_schema in ($1)
database    |         
database    | 2021-09-20 22:35:59.529 UTC [44] ERROR:  function postgis_version() does not exist at character 8
```

### To Reproduce

1. Running Directus in Docker Compose with fresh Postgres and taking a snapshot with CLI
2. Adding a new field called "new"
3. Try to apply the previous snapshot

Note: After I tried running the same steps with a different Docker image `postgis/postgis`, it just works.

### What version of Directus are you using?

9.0.0-rc.93

### What version of Node.js are you using?

v12.20.2

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker

### LINKED ISSUE #8311: Postgres query error upon applying schema through CLI
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When trying to apply my schema I'm getting this error:

```
09:42:02 🚨 error 

        SELECT c.table_name

          , c.column_name

          , c.column_default as default_value

          , c.data_type

  , c.character_maximum_length as max_length

          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity

          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable

        FROM

          information_schema.columns c

        LEFT JOIN information_schema.tables t

          ON c.table_name = t.table_name

        WHERE

          t.table_type = 'BASE TABLE'

          AND c.table_schema IN ($1);

       - current transaction is aborted, commands ignored until end of transaction block 

error: 

        SELECT c.table_name

          , c.column_name

          , c.column_default as default_value

          , c.data_type

  , c.character_maximum_length as max_length

warning "directus > @directus/extensions-sdk > rollup-plugin-typescript2@0.30.0" has unmet peer dependency "typescript@>=2.4.0".

          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity

          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable

        FROM

          information_schema.columns c

        LEFT JOIN information_schema.tables t

          ON c.table_name = t.table_name

        WHERE

          t.table_type = 'BASE TABLE'

          AND c.table_schema IN ($1);

       - current transaction is aborted, commands ignored until end of transaction block

    at Parser.parseErrorMessage (/src/node_modules/pg-protocol/dist/parser.js:287:98)

    at Parser.handlePacket (/src/node_modules/pg-protocol/dist/parser.js:126:29)

    at Parser.parse (/src/node_modules/pg-protocol/dist/parser.js:39:38)

    at Socket.<anonymous> (/src/node_modules/pg-protocol/dist/index.js:11:42)

    at Socket.emit (events.js:400:28)

    at addChunk (internal/streams/readable.js:290:12)

    at readableAddChunk (internal/streams/readable.js:265:9)

    at Socket.Readable.push (internal/streams/readable.js:204:10)

    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

As always, happy to discuss. Can't share my schema.yaml file here, will send it privately.

### To Reproduce

snapshot gemaakt van lokale postgres omgeving, lokale db weg gehaald, snapshot applied op lege postgres database, krijg ik deze error:

1. Create a snapshot from my local postgres database
2. Delete local postgres database
3. Recreate empty local postgres database
4. Apply the schema.yaml created at step 1.

### What version of Directus are you using?

rc94

### What version of Node.js are you using?

14 lts

### What database are you using?

Postgres 12

### What browser are you using?

na

### What operating system are you using?

na

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by joselcvarela**
Fix #8311
Fix #8176

Found out that a query could not throw an error inside a transaction, otherwise transaction could not be continued.
Tried with savepoints by doing nested transactions with knex without success.

### CODE REVIEW

File: packages/schema/src/dialects/postgres.ts [hunk 1]
```diff
@@ -46,9 +62,15 @@ export default class Postgres extends KnexPostgres implements SchemaInspector {
...
 			),
-			this.knex
-				.raw(
-					`
+		]);
+
+		const columns: RawColumn[] = columnsResult.rows;
+		const primaryKeys = primaryKeysResult.rows;
+		const geometryColumns: RawGeometryColumn[] = await new Promise((resolve) => {
+			if (!columns.some((col) => col.table_name === 'geometry_columns')) return resolve([]);
```
Comment (rijkvanzanten) [inline packages/schema/src/dialects/postgres.ts:70]: "geometry_columns" is a view, not a table. I don't think it shows up under `columns` at all. We'll have to find an alternative way to find whether or not PostGIS is available

Comment (rijkvanzanten) [reply packages/schema/src/dialects/postgres.ts:70]: We might be able to rely on 

```sql
SELECT EXISTS (
	SELECT
	FROM
		pg_catalog.pg_class c
		JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
	WHERE
		n.nspname = 'public'
		AND c.relname = 'geometry_columns'
		AND c.relkind = 'v' -- only views
);
```

to check if the view exists before continuing (cc @Oreilles)

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
