### PR TITLE
Fix issue preventing click events from working when sorting items

### LINKED ISSUE #23523: Unable to edit sortable items on mobile / touchscreens
### Describe the Bug

When rows are sortable, tapping it triggers sort, so can not edit the item

### To Reproduce

Example:

- I have M2A between page and blocks
- When creating / editing page, user can select/add new blocks
- Blocks are sortable, so user can tough and drag it to sort
- On mobile/touch screens, when I tap any of the block to edit it, it will trigger sort and i am unable to edit the block

### Directus Version

v10

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

### PR DESCRIPTION
**Pull request by robluton**
## Scope

What's changed:

- in the draggable component in list items, prevented dragging on all elements except the designated drag handle.

## Potential Risks / Drawbacks

- May not be immediately obvious to those who got accustomed to sorting items by clicking on any part of the item, that they need to sort by using the drag handle.

## Review Notes / Questions
- I was only able to test using an android device, so hopefully someone with an iphone can also test this.
- Vue draggable is no longer being maintained. There is a newer wrapper that is being maintained that might be worth looking into in the future. https://github.com/Alfred-Skyblue/vue-draggable-plus

---

Fixes #23523

### CODE REVIEW

File: app/src/interfaces/list-m2a/list-m2a.vue [hunk 1]
```diff
@@ -357,6 +357,8 @@ const allowDrag = computed(() => canDrag.value && totalItemCount.value <= limitW
 				:set-data="hideDragImage"
 				:disabled="!allowDrag"
 				v-bind="{ 'force-fallback': true }"
+				:filter="'.no-drag'"
+				handle=".drag-handle"
```
Comment (formfcw) [inline app/src/interfaces/list-m2a/list-m2a.vue:360]: On my end, simply adding `handle=".drag-handle"` does the job. I’ve tested it on an iPhone and the `.no-drag` parts are not necessary here. Just wondering, if they are necessary for Android?

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you for the great improvement @robluton 🎸

**Review by formfcw — APPROVED** [review]
Great Rob 🎸 

LGTM :rocket:
