### PR TITLE
Hide item link for delete action in activity feed

### LINKED ISSUE #15127: Reopening a `delete` Activity is buggy
### Describe the Bug

Uploading Screen Recording 2022-08-17 at 1.27.41 PM.mov…

### To Reproduce

Try to open a deleted item in a collection within the activity log.

### Errors Shown

_No response_

### What version of Directus are you using?

Cloud

### What version of Node.js are you using?

Cloud

### What database are you using?

Cloud

### What browser are you using?

.... Chrome

### How are you deploying Directus?

Cloud

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #15127

https://user-images.githubusercontent.com/26413686/185236202-d3026b05-ec4a-481b-bd6c-d4b2d10f969a.mov

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: app/src/modules/activity/routes/item.vue [hunk 1]
```diff
@@ -85,7 +85,7 @@ export default defineComponent({
 		const error = ref<any>(null);
 
 		const openItemLink = computed(() => {
-			if (!item.value || item.value.collection.startsWith('directus_')) return;
+			if (!item.value || item.value.collection.startsWith('directus_') || item.value.action === 'Delete') return;
```
Comment (rijkvanzanten) [inline app/src/modules/activity/routes/item.vue:88]: Is this value capitalized? If it is, is it translated?

Comment (licitdev) [reply app/src/modules/activity/routes/item.vue]: It was indeed translated. TIL. Thanks! 💯

**Review by azrikahar — APPROVED** [review]
LGTM!
