### PR TITLE
healthcheck crashes with local file storage

### LINKED ISSUE #16904: Application stops when `/server/health`
### Describe the Bug

When we call the `/server/health` endpoint, the application stops.

With this log:

```
[18:31:36] GET /server/health 304 408ms
[18:31:36] GET /server/health 304 356ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'project-path/uploads/health-6IG4X'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'project-path/uploads/health-6IG4X'
}
```

As you see, it happens after a couple of calls.

I think it's related with the `testStorage`:

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/api/src/services/server.ts#L289-L331

Probably related:
- https://github.com/directus/directus/pull/16825

### To Reproduce

Run a Directus application an call the `/server/health` endpoint several times.

### Errors Shown

```
[18:31:36] GET /server/health 304 408ms
[18:31:36] GET /server/health 304 356ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'project-path/uploads/health-6IG4X'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'project-path/uploads/health-6IG4X'
}
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

### PR DESCRIPTION
**Pull request by freekrai**
When using healthcheck (/server/health) with `local` file storage, the healthcheck would crash the app.

This PR fixes that with a mixture of error checking along with a 500 ms sleep between write and read.

Fixes #16904

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: api/src/services/server.ts [hunk 1]
```diff
@@ -307,9 +315,16 @@ export class ServerService {
 				const startTime = performance.now();
 
 				try {
-					await disk.write(`health-${checkID}`, Readable.from(['check']));
-					await disk.read(`health-${checkID}`);
-					await disk.delete(`health-${checkID}`);
+					await disk.write(`health-${checkID}`, Readable.from(['check'])).catch((err) => {
+						throw err;
+					});
+					await sleep(500); // 500 ms wait for disk to write
```
Comment (br41nslug) [inline api/src/services/server.ts:321]: What error situation does this wait fix and could this still fail if i manage to make the write take longer than 500ms? 🤔

Comment (freekrai) [reply api/src/services/server.ts:321]: if the wait is longer than 500ms, we get into healthcheck warning thresholds about healthcheck taking too long, all the sleep is doing is giving a slight pause between the write and the read to make sure any streams are closed, etc, without it we can still get the crash if the healthchecks are called too close together

Comment (freekrai) [reply api/src/services/server.ts]: removed sleep in favor of listeners in the adapter

**Review by br41nslug — COMMENTED** [review]
It is definitely a lot more stable now but im still seeing crashes when refreshing the health endpoint couple of times when running in production 🤔 
```
[09:39:17] GET /server/health?access_token=--redacted-- 200 20ms
[09:39:24] GET /server/health?access_token=--redacted-- 200 10ms
[09:39:24] GET /server/health?access_token=--redacted-- 200 7ms
[09:39:25] GET /server/health?access_token=--redacted-- 200 6ms
[09:39:26] GET /server/health?access_token=--redacted-- 200 6ms
[09:39:27] GET /server/health?access_token=--redacted-- 200 6ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'C:\Users\Brainslug\Directus\triage-repo\api\uploads\health-1lRND'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Brainslug\\Directus\\triage-repo\\api\\uploads\\health-1lRND'
}

Node.js v18.12.1

[09:41:19] GET /server/health 304 24ms
[09:41:21] GET /server/health 304 8ms
[09:41:22] GET /server/health 304 6ms
[09:41:23] GET /server/health 304 6ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Brainslug\Directus\triage-repo\api\uploads\health-xt9AR'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Brainslug\\Directus\\triage-repo\\api\\uploads\\health-xt9AR'
}

Node.js v18.12.1
```
Same happens in dev after refreshing a couple of times:
```
[10:16:56] GET /server/health 200 26ms
[10:16:59] GET /server/health 200 10ms
[10:17:00] GET /server/health 304 6ms
[10:17:00] GET /server/health 304 6ms
Error: ENOENT: no such file or directory, open 'C:\Users\Brainslug\Directus\triage-repo\api\uploads\health-moSZh'
[ERROR] 10:17:01 Error: ENOENT: no such file or directory, open 'C:\Users\Brainslug\Directus\triage-repo\api\uploads\health-moSZh'
```

**Comment by freekrai** [comment]
Will go back to see what else we can add to it.

File: packages/storage-driver-local/src/index.ts [hunk 2]
```diff
@@ -75,10 +75,20 @@ export class DriverLocal implements Driver {
...
+		try {
+			const fullPath = this.fullPath(filepath);
+			await this.ensureDir(dirname(fullPath));
+			const writeStream = createWriteStream(fullPath);
+			content.on('close', () => {
+				writeStream.end();
+				writeStream.on('finish', () => {
+					writeStream.close();
+				});
+			});
```
Comment (paescuj) [inline packages/storage-driver-local/src/index.ts:87]: This has actually worsened things in my tests, but I assume that was only added for testing purposes and will be removed again

**Review by paescuj — COMMENTED** [review]
Hey there 👋

The problem here is that `disk.read` simply returns a readable stream which cannot be awaited - although the name of the function `disk.read` and the fact that it is async might give another impression.

Therefore, by the time the readable stream wants to open the file, changes are high that the file has already been deleted by the subsequent `disk.delete` call.

This means we need to wait for the file to be opened before deleting it. I've submitted a suggestion containing the required changes.

File: packages/storage-driver-local/src/index.ts (hunk 2 above)
Comment (freekrai) [reply packages/storage-driver-local/src/index.ts:87]: in testing with myself and @br41nslug we found having that listener had the opposite effect, but will test it with your changes above and see.

Comment (paescuj) [reply packages/storage-driver-local/src/index.ts]: Great, thanks! 👍

File: packages/storage-driver-local/src/index.ts [hunk 3]
```diff
@@ -75,10 +75,14 @@ export class DriverLocal implements Driver {
...
-		const writeStream = createWriteStream(fullPath);
-		await pipeline(content, writeStream);
+		try {
+			const fullPath = this.fullPath(filepath);
+			await this.ensureDir(dirname(fullPath));
+			const writeStream = createWriteStream(fullPath);
+			await pipeline(content, writeStream);
+		} catch (error) {
+			throw new Error(`Failed writing file "${filepath}": ${error}`);
+		}
```
Comment (paescuj) [inline packages/storage-driver-local/src/index.ts:85]: Actually, I think we should revert all changes here, seeing that none of the other storage drivers have a `try...catch` statement in the `write` method. I assume the idea is to catch the error at the places where the method is called instead.

Otherwise we should apply this to all other drivers as well.

File: api/src/services/server.ts [hunk 4]
```diff
@@ -308,8 +308,10 @@ export class ServerService {
 
 				try {
 					await disk.write(`health-${checkID}`, Readable.from(['check']));
-					await disk.read(`health-${checkID}`);
-					await disk.delete(`health-${checkID}`);
+					const fileStream = await disk.read(`health-${checkID}`);
+					fileStream.on('data', async () => {
```
Comment (rijkvanzanten) [inline api/src/services/server.ts:312]: Should this be on `finish` to be safe?

Comment (freekrai) [reply api/src/services/server.ts:312]: Just tested and both `finish` or `data` work here and don't result in crashing healthcheck. Can update it to `finish`.

The idea is that it's waiting to make sure there's a valid read happening before we attempt to delete.

Comment (paescuj) [reply api/src/services/server.ts]: We don't actually read the file, so neither `finish` nor `end` are ever getting called.
But it's fine to delete the file as soon as it has been opened (`data` signal).
I did quite a lot stress tests with the `data` signal and it has not failed once.

Comment (paescuj) [reply api/src/services/server.ts]: > Yeah the `.on` is what matters here, testing with `data`, finish`and`end` all work the same and neither trigger crashes.

The test does work but the file is not getting deleted 🙃

Comment (freekrai) [reply api/src/services/server.ts]: Didn’t see non-deleted files on local testing but can put it back to `data` for more  consistency then.

Comment (paescuj) [reply api/src/services/server.ts:312]: > Didn’t see non-deleted files on local testing but can put it back to `data` for more consistency then.

Okay, that's interesting! I don't see how the `end` event should be called since we don't read from the stream. Besides there is no `finish` event on readable streams.

Thanks for putting it back to `data`!

One additional thing we could do to make it a bit safer though, is to destroy the stream before deleting the file:
```suggestion
					fileStream.on('data', async () => {
						fileStream.destroy();
```

**Review by br41nslug — APPROVED** [review]
Tried load testing again and it works without fail now 😄
