### PR TITLE
Fix bug in the select color field

### LINKED ISSUE #25040: If "Project Color" is set to an invalid hex value (i.e. "FFFFFF" without the "#"), it becomes transparent
### Describe the Bug

As stated in the title, if "Project Color" is set to an invalid value (i.e. "FFFFFF" without the "#"), it becomes transparent, which means that the "Save" button on the Appearance page itself visually disappears when the page is reloaded/revisited, and this disappearance is also the case for the Logout button and other elements depending on the project color.

Image

Additionally, there's something going on in the Project Color field - if I try to type "#FF5566", the field will auto-complete to "#FFFF55" when I type the first "5".

### To Reproduce

Try to save Project Color as i.e. "FFFFFF".

### Directus Version

11.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 17

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- Fixed a bug in the select color field that caused invalid color values to be stored.
- Fixed type errors
- Ensured that alpha channel is only added when the opacity prop is enabled

## Potential Risks / Drawbacks

—

## Review Notes / Questions

- Test also the color interface on a collection item and test various scenarios

---

Fixes #25040

### CODE REVIEW

File: app/src/interfaces/select-color/select-color.vue [hunk 1]
```diff
@@ -237,20 +242,29 @@ function useColor() {
...
+		}
+
+		if (isCssVarUtil(input.value)) return;
+
+		try {
+			// If the input is a valid color, we set the color and emit the input as a hex value which is consistent with the dropdown selector and HTML color picker
+			const newColor = Color(input.value);
+			setColor(newColor);
+		} catch {
+			// The input is not a valid color, but we still want to let the user edit/type in the input so we emit the input
```
Comment (AlexGaillard) [inline app/src/interfaces/select-color/select-color.vue:264]:
```suggestion
			// The input is not a valid color, but we still want to let the user edit/type in the input so we emit null
```

Comment (formfcw) [reply app/src/interfaces/select-color/select-color.vue:264]: nothing that I’ve touched, but yeah, let’s do this!

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
