### PR TITLE
Fix `VERSION_SAVE` activity/revisions not respecting collection tracking settings

### LINKED ISSUE #25894: API: Content Version accountability records created even if collection is set to not track anything
### Describe the Bug

When creating/updating a version of an item we can see Activity and Revisions records being created with action `version_save`.
So far so good, but we have Accountability set to Do Not Track Anything so we would expect no records to be created for this collection, even if those are related to Content Versioning

This is the part that handles this logic, but there's no condition so it will always save:
https://github.com/directus/directus/blob/main/api/src/services/versions.ts#L223-L254

### To Reproduce

1. Create a collection
2. Enable Content Versioning on that collection
3. Set Accountability to Do Not Track Anything
4. Go to content and create a new record on this collection
5. Now create a new version and save
6. See Activity and Records being created

### Directus Version

vv11.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres

### PR DESCRIPTION
**Pull request by yogeshwaran-c**
## Scope

What's changed:

- Gate the activity and revision writes in `VersionsService.save()` on the underlying collection's accountability setting, mirroring the gate `ItemsService` already uses for regular item mutations.
- When `accountability === null` (Do Not Track Anything), no activity or revision rows are created for a content version save.
- When `accountability === 'activity'`, only the activity row is created; the revision row is skipped.
- When `accountability === 'all'`, both rows are created (existing behaviour, now explicit).
- Added `api/src/services/versions.test.ts` covering all three accountability modes and asserting the version delta is still persisted when tracking is disabled.
- Added a patch changeset for `@directus/api`.

## Potential Risks / Drawbacks

- Users who rely (intentionally or not) on version saves always producing activity/revision rows on Do-Not-Track collections will see those rows disappear. This matches the documented accountability semantics for non-version mutations, so it should be a bug fix rather than a regression.
- The fix reads `this.schema.collections[collection]?.accountability`, which is identical to the lookup performed by `ItemsService` in the same file; the optional chain defends against an unexpected missing entry and falls back to "do not track" (no rows) in that edge case.

## Tested Scenarios

- `pnpm --filter @directus/api exec vitest run src/services/versions.test.ts` — 4/4 pass (all three accountability modes + delta-still-persists).
- `pnpm --filter @directus/api exec vitest run src/services/items.test.ts` — 11/11 pass (no regressions in the sibling service).
- `pnpm exec eslint` and `pnpm exec prettier --check` on both touched files — clean.

## Review Notes / Questions

- I mirrored the existing `this.schema.collections[this.collection]!.accountability` pattern used in `items.ts` for parity, but used optional chaining here because the lookup targets the *underlying* collection (derived from the version row), not `this.collection` (which is always `directus_versions`).
- Happy to split the `trackActivity` / `trackRevisions` locals into a single `collectionAccountability` switch if that is preferred.

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #25894

### CODE REVIEW

File: api/src/services/versions.ts [hunk 1]
```diff
@@ -238,28 +238,43 @@ export class VersionsService extends ItemsService<ContentVersion> {
...
+		if (trackRevisions && activity !== null) {
+			await revisionsService.createOne({
+				activity,
+				version: key,
+				collection,
+				item,
+				data: revisionDelta,
+				delta: revisionDelta,
+			});
+		}
```
Comment (ComfortablyCoding) [inline api/src/services/versions.ts:268]: Let's simplify this and keep it inline with how we handle this in other locations (e.g. https://github.com/directus/directus/blob/main/api/src/flows.ts#L416)


```suggestion
		const helpers = getHelpers(this.knex);
		let revisionDelta = await payloadService.prepareDelta(delta);

		const accountability = this.schema.collections[collection]?.accountability;

		if (accountability !== null) {
			const activityService = new ActivityService({
				knex: this.knex,
				schema: this.schema,
			});

			const activity = await activityService.createOne({
				action: Action.VERSION_SAVE,
				user: this.accountability?.user ?? null,
				collection,
				ip: this.accountability?.ip ?? null,
				user_agent: this.accountability?.userAgent ?? null,
				origin: this.accountability?.origin ?? null,
				item,
			});

			if (accountability === 'all') {
				const revisionsService = new RevisionsService({
					knex: this.knex,
					schema: this.schema,
				});

				await revisionsService.createOne({
					activity,
					version: key,
					collection,
					item,
					data: revisionDelta,
					delta: revisionDelta,
				});
			}
		}
```

File: .changeset/respect-collection-accountability-version-save.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fixed Content Version saves creating activity and revision records even when the underlying collection's accountability was set to "Do Not Track Anything". Version saves now respect the collection's accountability configuration: no activity/revision records are written when accountability is disabled, only an activity record is written when accountability is set to "activity", and both activity and revision records are written when accountability is set to "all".
```
Comment (ComfortablyCoding) [inline .changeset/respect-collection-accountability-version-save.md]:
```suggestion
Fixed `VERSION_SAVE` activity not respecting collection tracking settings
```

File: api/src/services/versions.test.ts [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+		createTracker(db);
+	});
+
+	afterEach(() => {
+		vi.clearAllMocks();
+	});
+
+	describe('Services / Versions', () => {
+		describe('save respects collection accountability tracking', () => {
+			const buildSchema = (accountability: 'all' | 'activity' | null) =>
```
Comment (ComfortablyCoding) [inline api/src/services/versions.test.ts]: Instead of rebuilding the schema for each tests, let's create collections on a shared schema that covers each tracking case.

File: api/src/services/versions.test.ts [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+					.mockResolvedValue({ item: '1', collection: 'articles', delta: {} });
+
+				const updateOneSpy = vi.spyOn(ItemsService.prototype, 'updateOne').mockResolvedValue('1');
+
+				const activityCreateSpy = vi.spyOn(ActivityService.prototype, 'createOne').mockResolvedValue(42);
+
+				const revisionsCreateSpy = vi.spyOn(RevisionsService.prototype, 'createOne').mockResolvedValue(99);
+
+				return { readOneSpy, updateOneSpy, activityCreateSpy, revisionsCreateSpy };
+			};
```
Comment (ComfortablyCoding) [inline api/src/services/versions.test.ts]: Ideally we use our [`test-utils`](https://github.com/directus/directus/blob/main/api/src/test-utils/services/items-service.ts) mocks for these, as they all extend the items service they should all be supported

**Review by ComfortablyCoding — DISMISSED** [review]
Thanks for the PR! Please see comments below.

**Comment by yogeshwaran-c** [comment]
@ComfortablyCoding thanks for the review — I've pushed 42b0fec addressing all four points:

1. **`api/src/services/versions.ts`** — Simplified to the `flows.ts` pattern: `const accountability = this.schema.collections[collection]?.accountability;` gating a single `if (accountability !== null)` block, with `ActivityService` instantiated inside that branch and `RevisionsService` only instantiated inside the nested `accountability === 'all'` branch. Moved `getHelpers`/`prepareDelta` above the guard so the rest of `save` (timestamp stamping and the sudo `updateOne`) still runs when tracking is off.
2. **`.changeset/respect-collection-accountability-version-save.md`** — Replaced with the exact wording: `Fixed \`VERSION_SAVE\` activity not respecting collection tracking settings`.
3. **`api/src/services/versions.test.ts`** — Consolidated to a single shared `SchemaBuilder` schema with three collections (`articles_track_all`, `articles_track_activity`, `articles_track_none`) covering each tracking case; tests now just pick the collection to exercise instead of rebuilding the schema.
4. **`api/src/services/versions.test.ts`** — Swapped in the `mockItemsService()` helper from `api/src/test-utils/services/items-service.ts` via `vi.mock('./items.js', ...)`, and call through on `ItemsService.prototype` for `readOne`/`updateOne`. `ActivityService` and `RevisionsService` extend `ItemsService` so they're covered transitively; the two call-count assertions use `vi.spyOn` on their prototypes.

Verified locally with `pnpm vitest run src/services/versions.test.ts` — 4/4 passing.

File: .changeset/respect-collection-accountability-version-save.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fixed `VERSION_SAVE` activity not respecting collection tracking settings
```
Comment (ComfortablyCoding) [inline .changeset/respect-collection-accountability-version-save.md]:
```suggestion
Fixed `VERSION_SAVE` activity/revisions not respecting collection tracking settings
```

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀 , Thanks @yogeshwaran-c and congratulations on your first contribution to directus! 🥳

File: contributors.yml [hunk 6]
```diff
@@ -268,5 +268,6 @@
 - Zhey-on
 - faizkhairi
 - eric-pennecot
+- yogeshwaran-c
```
Comment (AlexGaillard) [inline contributors.yml]:
```suggestion
```

**Review by AlexGaillard — APPROVED** [review]
