### PR TITLE
(#21573) Be more relaxed with UUID validation

### LINKED ISSUE #21573: UUID validation is too strict
### Describe the Bug

The [`uuid-validate` library](https://github.com/microsoft/uuid-validate/blob/master/index.js#L62-L86) in use [here](https://github.com/directus/directus/blob/main/api/src/utils/validate-keys.ts#L22) is overly strict - I have a valid (though non-standard) UUID `dc60771a-d86d-e7a3-79b1-5277050cbc99` as a key in my table (version `e`) that is being detected as invalid and throwing.

The validation should only ensure that the value is a UUID, and not that it is a certain version. In addition, the `uuid-validate` library has been archived.

```
[13:51:48.171] DEBUG: You don't have permission to access this.
    err: {
      "type": "",
      "message": "You don't have permission to access this.",
      "stack":
          DirectusError: You don't have permission to access this.
              at validateKeys (redacted/node_modules/@directus/api/dist/utils/validate-keys.js:15:19)
              at ItemsService.readOne (redacted/node_modules/@directus/api/dist/services/items.js:367:9)
              at redacted/node_modules/@directus/api/dist/controllers/items.js:87:34
              at redacted/node_modules/@directus/api/dist/utils/async-handler.js:1:66
              at Layer.handle [as handle_request] (redacted\node_modules\express\lib\router\layer.js:95:5)
              at next (redacted\node_modules\express\lib\router\route.js:144:13)
              at redacted/node_modules/@directus/api/dist/middleware/collection-exists.js:23:12
              at redacted/node_modules/@directus/api/dist/utils/async-handler.js:1:66
              at Layer.handle [as handle_request] (redacted\node_modules\express\lib\router\layer.js:95:5)
              at next (redacted\node_modules\express\lib\router\route.js:144:13)
      "name": "DirectusError",
      "code": "FORBIDDEN",
      "status": 403
    }
```

### To Reproduce

Create a table with some data:
```sql
create table uuid_test
(
  id uuid not null primary key
);
insert into uuid_test (id) values ('dc60771a-d86d-e7a3-79b1-5277050cbc99');
```

Create the collection in Directus, and attempt to access the entry in the Content viewer; the above error will happen if you have DEBUG logging enabled.

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by kashike**
## Scope

What's changed:

- Instead of using the `uuid-validate` library, which has a strict definition of what is considered to be a "valid" UUID, we manually implement our own validation method using a more relaxed validation pattern.

## Potential Risks / Drawbacks

- There shouldn't really be any drawbacks here, as the new validation pattern does ensure that the UUID is still valid, it just does not do any version restricting.

## Review Notes / Questions

- I attempted to add a small test - not sure if there are any additional steps required?

---

Fixes #21573

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]
LGTM! ..though I'm also jetlagged and very tired after a long conference day (it's 10:20pm here), so I'll leave it up to @br41nslug to give it a once over before merging 🚀

File: api/src/utils/validate-uuid.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// This expression is a bit more relaxed than libraries like uuid and uuid-validate - see: https://github.com/directus/directus/issues/21573
+const REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
```
Comment (paescuj) [inline api/src/utils/validate-uuid.ts:2]: Instead of the current comment, I'd like to have an explanation of the pattern and why that is valid/works for our use-case? So the main difference is obviously that we allow any version. Is there another thing which is more relaxed?

Do you have a source for that RegEx pattern - just to make it easier for us to validate?

**Review by paescuj — CHANGES_REQUESTED** [review]

File: api/src/utils/validate-uuid.ts (hunk 1 above)
Comment (kashike) [reply api/src/utils/validate-uuid.ts:16]: > Instead of the current comment, I'd like to have an explanation of the pattern and why that is valid/works for our use-case. So the main difference is obviously that we allow any version. Is there another thing which is more relaxed?
> 
> Do you have a source for that RegEx pattern - just to make it easier for us to validate?
> 

I've included a more detailed comment on the pattern, including reference sources.

> Bonus: I know this works with PostgreSQL, but I couldn't find an official statement about non-standard versions (cannot see anything here [1](#user-content-fn-1-e6889ca2085226678b7bd91f114ce744)) - do you happen to have anything to hand?

As far as I am aware there is no official statement, however there is no validation performed (see [here](https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/uuid.c)) and there are extensions (such as [pg_uuidv7](https://pgxn.org/dist/pg_uuidv7/)) that introduce methods to generate version 7 UUIDs.

File: api/src/utils/validate-uuid.test.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+	});
+
+	test('v7', () => {
+		expect(validateUuid('018df14d-1309-7226-9ed7-ffbfecad6b5f')).toBe(true);
+	});
+
+	// https://github.com/directus/directus/issues/21573
+	test('example from issue 21573', () => {
+		expect(validateUuid('dc60771a-d86d-e7a3-79b1-5277050cbc99')).toBe(true);
+	});
```
[the remark this answers is not in the document]
Comment (kashike) [reply api/src/utils/validate-uuid.test.ts]: https://github.com/directus/directus/pull/21613/commits/a61680cc5fa8b7b1ae2cd7b316995760cc12ed44

File: .changeset/rotten-sloths-dress.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Be more relaxed with UUID validation
```
[the remark this answers is not in the document]
Comment (kashike) [reply .changeset/rotten-sloths-dress.md]: https://github.com/directus/directus/pull/21613/commits/a61680cc5fa8b7b1ae2cd7b316995760cc12ed44

File: .changeset/rotten-sloths-dress.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Be more relaxed with UUID validation, permitting values with non-standard versions
```
Comment (paescuj) [inline .changeset/rotten-sloths-dress.md:5]:
```suggestion
Adjusted UUID validation of keys to be more relaxed, permitting values with non-standard versions
```

**Review by paescuj — APPROVED** [review]

**Comment by paescuj** [comment]
Thanks @kashike!

As a matter of facts, this might also address #15535.
