### PR TITLE
Fix nested queries with unlimited default limit

### LINKED ISSUE #22038: QUERY_LIMIT_DEFAULT breaks Flows
### Describe the Bug

When setting the environment variable QUERY_LIMIT_DEFAULT to -1 the flows screen breaks: The operations array is empty, so the flow doesn't have a starting operation. This results in the screen (and also the processing of the flow) to stop after the initial trigger, because there are no operations in the operations array.

### To Reproduce

```
  directustest:
    image: directus/directus:10.10.4
    environment:
      KEY: "key"
      SECRET: "secret_key"
      DB_CLIENT: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: directus_test
      DB_USER: root
      DB_PASSWORD: password
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'
      FLOWS_RUN_SCRIPT_TIMEOUT: 30000
      QUERY_LIMIT_DEFAULT: -1
      PUBLIC_URL: "http://api.directus.test"
    depends_on:
      - mysql
      - traefik
    networks:
      - traefik-proxy
```

1. Set up a docker container similar to the one above
2. Try to set up an example flow (e.g. CRON -> Log to Console)
3. Save
4. See the "Log to Console"-Operation vanish
5. Remove the  QUERY_LIMIT_DEFAULT: -1
6. Try steps 1-3 again and see it work

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

Fix an issue where nested items would not be returned with default query limit of unlimited (`QUERY_LIMIT_DEFAULT=-1`).

## Potential Risks / Drawbacks

None

## Review Notes / Questions

`if` statement for slicing wasn't accounting for the value of `QUERY_LIMIT_DEFAULT` of `-1`

---

Fixes #22038

### CODE REVIEW

File: api/src/database/run-ast.ts [hunk 1]
```diff
@@ -476,21 +476,18 @@ function mergeWithParentItems(
 
 			parentItem[nestedNode.fieldKey].push(...itemChildren);
 
+			const limit = nestedNode.query.limit ?? Number(env['QUERY_LIMIT_DEFAULT']);
```
Comment (br41nslug) [inline api/src/database/run-ast.ts:479]: Do we need to account for `QUERY_LIMIT_MAX` here or is that handled by the `nestedNode.query.limit` upstream? Dont see it in the old implementation either so probably the latter 🤔

Comment (paescuj) [reply api/src/database/run-ast.ts:479]: > Dont see it in the old implementation either so probably the latter

Yeah, should be checked/applied at higher level 👍 This change only ensures the check before slicing also accounts for the the fallback (default) value.

**Review by br41nslug — APPROVED** [review]
