### PR TITLE
Fixes: No notification being created when sendmail fails.

### LINKED ISSUE #13974: When sending a notification, create record first then email, else no notification record is created if email sending fails
### Describe the Bug

Currently, if sending the email notification fails, no notification record is created. The record should be created first in case email sending fails for whatever reason.

Maybe if it does fail, that could be another notification record to the admin with a high alert level?

### To Reproduce

As above.

### Errors Shown

_No response_

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

12.22.5

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

local

### PR DESCRIPTION
**Pull request by jamescammarano**
## Description

Previously: When a notification was made if the sendmail failed the notification would not be created.

With this change: A notification is created and the sendmail error is logged to console.
Fixes #13974

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: api/src/services/notifications.ts [hunk 1]
```diff
@@ -16,13 +17,22 @@ export class NotificationsService extends ItemsService {
 	}
 
 	async createOne(data: Partial<Notification>, opts?: MutationOptions): Promise<PrimaryKey> {
-		await this.sendEmail(data);
+		try {
+			await this.sendEmail(data);
+		} catch (error: any) {
+			logger.error(error.message);
+		}
```
Comment (rijkvanzanten) [inline api/src/services/notifications.ts:24]: We should swap this with the `super.createOne(data, opts)` call to solve for item 3 from https://github.com/directus/directus/issues/14100#issue-1284309285

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/services/notifications.ts (hunk 1 above)
Comment (jaycammarano) [reply api/src/services/notifications.ts:24]: So put the `super.createOne(data, opts)` into the try/catch?

Comment (rijkvanzanten) [reply api/src/services/notifications.ts:24]: The super call should happen before the try catch block altogether. Also, the try/catch of the send mail bit should happen in sendMail itself, otherwise the same problem will happen everywhere else we send an email 👍🏻

File: api/src/services/notifications.ts [hunk 2]
```diff
@@ -16,33 +17,41 @@ export class NotificationsService extends ItemsService {
 	}
 
 	async createOne(data: Partial<Notification>, opts?: MutationOptions): Promise<PrimaryKey> {
+		const response = super.createOne(data, opts);
```
Comment (rijkvanzanten) [inline api/src/services/notifications.ts:20]: These need to be awaited

```suggestion
		const response = await super.createOne(data, opts);
```

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
