### PR TITLE
Fix default values

### LINKED ISSUE #15569: Unable to add child item with default values from drawer
### Describe the Bug

Unable to add child item without saving a different value, and updating it back to the original value.

https://user-images.githubusercontent.com/26413686/190131798-87a7d939-5afd-4d2e-a52b-d6cc85122088.mov

### To Reproduce

Create an O2M relationship, with the child collection having a boolean field defaulting as `false`.

### Errors Shown

_No response_

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

v16

### What database are you using?

PG

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by Nitwel**
## Description

There where 2 Problems.

1. We would do an `if(schema.default_value)` which would fail when you want to set the default value to false.
2. The drawer item was ignoring the default values when saving.

Fixes #15569, fixes ENG-189

### CODE REVIEW

File: app/src/views/private/components/drawer-item.vue [hunk 1]
```diff
@@ -410,7 +410,11 @@ function useActions() {
 			internalEdits.value[primaryKeyField.value.field] = props.primaryKey;
 		}
 
-		emit('input', internalEdits.value);
+		const noNullDefaultValues = Object.fromEntries(
+			Object.entries(defaultValues.value).filter(([_, value]) => value !== null)
+		);
+
+		emit('input', merge({}, noNullDefaultValues, internalEdits.value));
```
Comment (rijkvanzanten) [inline app/src/views/private/components/drawer-item.vue:417]: Should this be an `assign` instead of a `merge`? Otherwise you can erroneously end up merging into a object/array default value

Comment (br41nslug) [reply app/src/views/private/components/drawer-item.vue:418]: I couldn't find a way to get an `array` or `object` in the default values to break the `merge` but i do think that these could exist in the future with JSON fields for instance. Using `assign` seems more future proof to me 😄

File: app/src/views/private/components/drawer-item.vue [hunk 2]
```diff
@@ -411,7 +411,11 @@ function useActions() {
 			internalEdits.value[primaryKeyField.value.field] = props.primaryKey;
 		}
 
-		emit('input', internalEdits.value);
+		const noNullDefaultValues = Object.fromEntries(
+			Object.entries(defaultValues.value).filter(([_, value]) => value !== null)
+		);
+
+		emit('input', assign({}, noNullDefaultValues, internalEdits.value));
```
Comment (azrikahar) [inline app/src/views/private/components/drawer-item.vue:418]: This fix perfectly resolves default value of `false` and make sure they are being emitted! 👍 however I believe we need to additionally check the Create permission and filter out `defaultValues.value` from having any fields that a user does not have permission to create.

## Example setup

1. Create collection `a` and collection `b`
2. In collection `b`, create input/string field `name` with default value `Default Name B`
3. In collection `b`, create toggle/boolean field `enabled` with default value `false`
4. In collection `a`, create O2M field to collection `b`
5. Create a new role, grant the role the following permissions:
    - Collection `a`: full Create + Read + Update permissions
    - Collection `b`
        - Create permissions on all fields _except_ `name`
        - Read permissions on all fields
        - Update permissions on all fields _except_ `name`
6. Use the new role to create a new item in collection `a` and use the O2M field
        
    Example screenshot:
    

## Screen Capture

The B item is created, but it is sending `{ name: "Default Name B", enabled: false }`, whereas the current user should only send `{ enabled: false }` because they do not have create permission on `name`.

https://user-images.githubusercontent.com/42867097/224366154-8317819a-9d4e-4ed6-8a4a-ecd19c1c4500.mp4

Comment (Nitwel) [reply app/src/views/private/components/drawer-item.vue]: Good catch, we should probably handle it the same way as the v-form does by only sending over values that are not the default, meaning, we shouldn't inject default vaules into the relational edits.

And then by not checking if edits are empty, we can also send over an empty object in the case of only having defaults.

Comment (azrikahar) [reply app/src/views/private/components/drawer-item.vue]: Makes perfect sense 👍 however it seems like sending an empty object for relationships with junction table is only creating the junction entry, not the related collection entry:

https://user-images.githubusercontent.com/42867097/226595694-3616b9e8-4596-4cfb-a504-e2885b575bae.mp4

<br />

I tried editing the raw value and change `{}` to `{"b_id": {}}` which seems to work as expected to create a new B item with default values. I assume that means we need to make it add the related collection junction field like I tested, if I'm not mistaken.

File: app/src/views/private/components/drawer-item.vue [hunk 3]
```diff
@@ -403,6 +403,10 @@ function useActions() {
 			validationErrors.value = [];
 		}
 
+		if (props.junctionField && Object.values(defaultValues.value).find((value) => value !== null)) {
```
Comment (azrikahar) [inline app/src/views/private/components/drawer-item.vue:406]:
```suggestion
		if (props.junctionField && Object.values(defaultValues.value).some((value) => value !== null)) {
```

I believe we need to use `.some` here because `.find` is returning the value.

Especially when the default value is `0` or `false`, it will then become `if (props.junctionField && 0)` or `if (props.junctionField && false)`, which are both still falsy. Please do let me know if `.some` is still not accurate 👌

**Review by azrikahar — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]
