### PR TITLE
Fix "Auto Refresh" for Kanban and Calendar layouts

### LINKED ISSUE #22274: Kanban and Calendar layouts don't (auto) refresh
### Describe the Bug

Both the Calendar and Kanban layout don't respect the `refreshInterval` setting

### To Reproduce

- Set the layout to Kanban or Calendar
- Set Refresh Interval to 10 seconds
- Observe that no refresh is happing

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

The `refresh` handler were not implemented for the two layouts

What's changed:

- Added a simple `refresh` and `resetPresetAndRefresh` (that is used in case of a misconfiguration) to calendar layout
- Add `refresh` and `resetPresetAndRefresh` to kanban layout that reloads items and group items.

## Potential Risks / Drawbacks

- Performance implications of allowing the user to reload the calendar view every 10s with a default limit of 10k.

## Review Notes / Questions

---

Fixes #22274

### CODE REVIEW

**Comment by hanneskuettner** [comment]
After talking to Pascal I moved the error notice duplicated among some layouts into the common `collection.vue` component and simply inject them at the correct locations with a slot that presence is still controlled in the layouts themselves, deduplicating the layout and copy of the error.

Additionally added the error notices to the calendar and kanban layout which were previously missing.

File: app/src/layouts/kanban/index.ts [hunk 1]
```diff
@@ -306,6 +312,16 @@ export default defineLayout<LayoutOptions, LayoutQuery>({
...
 		}
 
+		async function resetPresetAndRefresh() {
+			await props?.resetPreset?.();
+			refresh();
+		}
+
+		function refresh() {
+			getItems();
+			if (isRelational.value) getGroups();
```
Comment (paescuj) [inline app/src/layouts/kanban/index.ts:322]: Can we add a quick comment here why this is necessary?

**Review by paescuj — APPROVED** [review]
