### PR TITLE
Change csv db type to text

### LINKED ISSUE #19903: CSV field falls back to 255 characters in length
### Describe the Bug

Follow-up to a short Discord discussion, any input field with type `CSV` wont let you edit the length (much like `JSON` as expected), but once created they have their length locked to 255 characters.

The workaround is to create it as a `JSON` type, but then we'll go against other issues like #7277 till #15889 is implemented.

Database is Postgis13 and Redis6

### To Reproduce

1. In the advanced page for Tags Field or Standard Field change to type CSV
  image
2. Create the field and go back to its settings and as you can see it reports a 255 limit
  image
3. When testing if that limit is respected or not we do see it active
  image

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by DanielBiegler**
## Scope

What's changed:

- Changed the database type of our CSV field from string to text so that its not capped to 255 characters

## Potential Risks / Drawbacks

- This'll only affect created columns in the future so we should be good there.
- Should in general fine as its still a string but just persisted differently I think. There are differences as to how database vendors store text but since we use knex it should just work out. We just see a string, so all other operations we do on said string dont change.

## Review Questions

- I included the change for the db seed and did do some global searches to find every mention of CSV to not miss further checks. Seems there are only these two.

## Example

Now you can have huge CSVs, see:

image

And it gets persisted properly in raw:

```json
[
    "asdaadssad",
    "asdaadssadasdaadssadasdaadssad",
    "asdaadssadasdaadssad",
    "asdaadssadasdaadssadasdaadssadasdaadssad",
...
```

And displays work too:

image

---

Fixes #19903

### CODE REVIEW

**Review by rijkvanzanten — DISMISSED** [review]
I think we should add a migration to change existing CSVs to TEXT as well.. ?

**Comment by paescuj** [comment]
> I think we should add a migration to change existing CSVs to TEXT as well.. ?

I think so too, eliminating the risk of conflicts in the future

File: api/src/database/migrations/20231009A-update-csv-fields-to-text.ts
[the remark this answers is not in the document]
Comment (DanielBiegler) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:1]: Good points, thank you so much. Mh. Currently unsure if theres an optimal solution here.

[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:1]: > * in the `up()` function do we want to check if the field is actually a `string` type first? I suspect a non-zero amount of people may have manually changed the type to `text` already and am unsure if that would error.

Doesn't error on SQLite & PostgreSQL but not sure about other DBs so I guess a check doesn't harm 😃👍 Added in https://github.com/directus/directus/pull/19953/commits/84d0d08e274418b4e1380bb6cfaca8241f3d391f. 

>     * in the `down()` function do we want to change the type back to `string` at all? as this will be a destructive operation possibly deleting data.

I rather tend to offer (a potentially destructive) rollback than none at all. I think normally a rollback is only done when something has gone wrong, and at this point the value maxes at 255 chars anyway.
A backup should be made in any case [^1].

[^1]: https://docs.directus.io/self-hosted/upgrades-migrations.html#backing-up-a-project

**Review by paescuj — APPROVED** [review]

File: api/src/database/migrations/20231009A-update-csv-fields-to-text.ts
[the remark this answers is not in the document]
Comment (DanielBiegler) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:1]: Love the new bundling of promises into `Promise.all`, that's waaay better than my first try at this. Thanks!

[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:1]: Well, you did the heavy work, so thanks back ❤️ Just a little optimization 😃🚀

File: api/src/database/migrations/20231009A-update-csv-fields-to-text.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+	const inspector = createInspector(knex);
+	const helper = getHelpers(knex).schema;
+	const csvFields = await knex.select('collection', 'field').from('directus_fields').where('special', '=', 'cast-csv');
+
+	const updates: Promise<void>[] = [];
+
+	for (const { collection, field } of csvFields) {
+		updates.push(
+			inspector.columnInfo(collection, field).then((column) => {
+				if (column.data_type === 'text') return;
```
Comment (br41nslug) [inline api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:15]: Would it be possible to check for `!== 'string'` instead here? 🤔

File: api/src/database/migrations/20231009A-update-csv-fields-to-text.ts [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+				return helper.changeToType(collection, field, 'text', {
+					default: column.default_value,
+					nullable: column.is_nullable,
+				});
+			})
+		);
+	}
+
+	return Promise.all(updates);
```
Comment (br41nslug) [inline api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:25]: Do we really need the `Promise.all()` here over awaiting the promise directly in the inside the loop? Since `Promise.all()` will exit on the first promise rejection, which may be halfway the update if you have a large data-model, do we want/need to run this in a transaction? 🤔 Or perhaps use `Promise.allSettled()` instead to ignore failing updates

File: api/src/database/migrations/20231009A-update-csv-fields-to-text.ts (hunk 1 above)
Comment (paescuj) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:15]: Data type for "string" differs depending on the DB (`string`, `varchar`, ...) so `=== 'text'` is the easier way

Comment (br41nslug) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:15]: Yeah thats what i was afraid of

File: api/src/database/migrations/20231009A-update-csv-fields-to-text.ts (hunk 2 above)
Comment (br41nslug) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:25]: > I don't see a difference here between awaiting in loop and using Promise.all(), in both cases the update might fail at any point.

Indeed they both behave the same in that respect, the point was more that if we directly await the promise you can skip the whole array building part and it would behave the same.

The failing part was more intended to apply to the transaction part.

In any case none of this is blocking.

Comment (paescuj) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:25]: > Indeed they both behave the same in that respect, the point was more that if we directly await the promise you can skip the whole array building part and it would behave the same.

Yeah, they behave almost the same in terms of error, but the `Promise.all()` way leverages full async.

> The failing part was more intended to apply to the transaction part, which they apparently are already by default 😄

I'm afraid migrations aren't executed in transactions, as we aren't relying on `knex.migrate` (was just a ref), so I fully agree with you that this is something we should look into but out of scope of this PR in my opinion.

Comment (br41nslug) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:25]: Considering that they arent run in a transaction would it be wise to us `allSettled` instead so that the migration will try to update all possible csv fields even if on fail for unexplainable reasons along the way? 🤔

Comment (paescuj) [reply api/src/database/migrations/20231009A-update-csv-fields-to-text.ts:25]: Works for me, feel free to update the PR 👍 
Keep in mind that `allSettled` never rejects, so you need to check each promise result and throw yourself.
