### PR TITLE
Fix sort icons

### LINKED ISSUE #17974: Incorrect icon and label for sort removal in m2m table layout
### Describe the Bug

The label shown when hovered describes the sort action. 
However, the "Sort Ascending" label was used instead of a "clear sort" or "remove sort" label.
The displayed icon is also incorrect.

https://user-images.githubusercontent.com/26413686/228245328-3892e993-469d-49fc-a6a2-d1fcb065c83b.mov

### To Reproduce

Create an M2M relation. Set up the interface with M2M table layout.

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by Nitwel**
Fixes #17974

### CODE REVIEW

File: app/src/components/v-table/table-header.vue [hunk 1]
```diff
@@ -180,7 +180,8 @@ function getClassesForHeader(header: Header) {
 }
 
 function getTooltipForSortIcon(header: Header) {
-	return props.sort.by === header.value && props.sort.desc === false ? 'sort_desc' : 'sort_asc';
+	if (props.sort.by === null) return 'sort_asc';
+	return props.sort.by === header.value && props.sort.desc === false ? 'sort_desc' : 'disable_sort';
```
Comment (paescuj) [inline app/src/components/v-table/table-header.vue:184]: Should be something like this as otherwise the unsorted header shows "Disable Sort" instead of "Sort Ascending":
```suggestion
	if (props.sort.by === null || props.sort.by !== header.value) return 'sort_asc';
	return props.sort.desc === false ? 'sort_desc' : 'disable_sort';
```

**Review by paescuj — CHANGES_REQUESTED** [review]

**Review by paescuj — APPROVED** [review]

**Review by br41nslug — APPROVED** [review]
Works as expected


https://user-images.githubusercontent.com/9389634/230901124-53140a21-2daf-4cdd-89f1-edf8b62084c7.mp4
