### PR TITLE
Fix manual flow triggers not working in drawer

### LINKED ISSUE #26541: Button fields with Action Type to set to Flow do not work when the item is being viewed in pop-out right-hand pane, and a confirmation dialog for the flow is configured.
### Describe the Bug

The new ability to have a Button field trigger a Flow (as opposed to opening a url) is AWESOME and really useful. 

However, if your Flow has a confirmation box configured, and you are viewing the item in the popout right-hand pane (which appears when you click on an item in a O2M list from a parent item), the flow button doesn't work, the confirmation doesn't appear, and it just fails silently.

### To Reproduce

**In the Data Model:**
Create a collection called "Countries", with a field of "country_name".
Create a collection called "Cities" with a field of city_name.
Create a new Flow which can be manually triggered on the Cities collection. In the trigger setup, enable Confirmation Dialog. Add a "Log to console" node and write some message in there. Ensure logging is enabled for the flow.
Create a new field in the Cities Collection of type Button, set Action Type to Flow, and have it trigger the flow you just created.
In the Countries collection, create a O2M field called "cities", and set the Related Collection to Cities, with a Foreign Key of "country". 

**Then in the Content explorer:**
Create a City and name it "Paris". While still viewing the Paris item, click the flow button (on the main page... not the one in the right hand sidebar). The confirmation box will appear, and you can check the logs for the flow and confirm it ran correctly.
Create a Country and name it "France". Then in the O2M "cities" field, click Add Existing, and add the previously created Paris item. Save it.
Now, while viewing the France country item, click on the Paris city. It should open in the Paris item in the right hand pop-out panel.
Click the Flow button. Notice that no confirmation dialog box appears, and nothing happens.
Check the logs for the Flow, and notice that there are no new logs.

### Directus Version

v11.14.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by HZooly**
## Scope

What's changed:

- Fix manual flow triggers silently failing when item is opened in a drawer
- Root cause: `overlay-item.vue` called `useFlows()` but never rendered `FlowDialogs`, so confirmation dialogs had no UI and flows aborted silently
- Fix notification toasts appearing behind the drawer by switching to `position: fixed; z-index: 700` when a drawer is open

## Tested Scenarios

- Open an item that has a manual flow trigger button
- Verify flow triggers correctly from the normal item view
- Open the same item via a relational field (in a drawer) and trigger the flow — should work now
- Verify the success notification toast appears above the drawer
- Verify notifications on normal pages (no drawer) still appear correctly

## Checklist

- [ ] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26541

### CODE REVIEW

File: app/src/views/private/components/notifications-group.vue [hunk 1]
```diff
@@ -65,3 +65,11 @@ const queue = toRefs(notificationsStore).queue;
...
 }
 </style>
+
+<style lang="scss">
+// relocate to fixed position when dialog is open to prevent it from being covered by the dialog
+body:has(#dialog-outlet > .container.right) .notifications-group {
+	position: fixed;
+	z-index: 700;
+}
+</style>
```
Comment (rijkvanzanten) [inline app/src/views/private/components/notifications-group.vue]: Let's avoid using global styles within components, they're really hard to debug. The better solution here is to use a flag in the notification store to indicate that a dialogue is currently present, and then make it fixed, or just make it fixed all the time if that would work.

**Review by rijkvanzanten — DISMISSED** [review]

File: app/src/views/private/components/notifications-group.vue (hunk 1 above)
Comment (HZooly) [reply app/src/views/private/components/notifications-group.vue]: We cannot have it `fixed` all the time. Without overlay, `absolute` positions the toast relative to the content panel.

**Review by AlexGaillard — APPROVED** [review]
🆒🫘

**Comment by MarkBurvs** [comment]
Thank you 🙏
