### PR TITLE
Fix edits not being found in o2m

### LINKED ISSUE #4331: O2M interface doesn't show edits on second click
When editing a related item using the O2M interface, the edits are registered but are cleared when opening the drawer for the second time, so to the user it looks like their edits were gone.

To reproduce this issue:
1. Create a O2M field and add the default interface.
2. Visit the collections module page to render an item's form that includes the O2M interface
3. Add a new O2M item using "Create new" button in the O2M interface
4. After saving, open the item again and try editing the O2M item previously created
5. Click the top right check box in the drawer to save some edits
6. Click the O2M item again and your edits will appear to be gone in the drawer

Details:
Directus Version: 9.0.0-rc.44
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

### PR DESCRIPTION
**Pull request by Nitwel**
closes #4331

### CODE REVIEW

File: app/src/interfaces/one-to-many/one-to-many.vue [hunk 1]
```diff
@@ -363,7 +363,12 @@ export default defineComponent({
 				const pkField = relatedPrimaryKeyField.value.field;
 				const hasPrimaryKey = pkField in item;
 
-				const edits = (props.value || []).find((edit: any) => edit === item);
+				const edits = (props.value || []).find(
+					(edit: any) =>
+						typeof edit === 'object' &&
+						edit[relatedPrimaryKeyField.value.field] === item[relatedPrimaryKeyField.value.field]
+				);
+				console.log(JSON.stringify(props.value, null, 4), JSON.stringify(item, null, 4), edits);
```
Comment (rijkvanzanten) [inline app/src/interfaces/one-to-many/one-to-many.vue:371]:
```suggestion
```

**Review by rijkvanzanten — APPROVED** [review]
