### PR TITLE
SDK Improve global type compatibility

### LINKED ISSUE #19747: getting type errors when trying to use `ofetch`/`$fetch` with the SDK@12.0.0
### Describe the Bug

I'm having trouble getting `ofetch`/`$fetch` to work with the new SDK in a Nuxt project.

I already described some of this in the discord channel, but basically I'm getting 1/2 type errors related to the `extract-data` util (depending on the browser is either `TypeError: e.headers is undefined` or `TypeError: Cannot read properties of undefined (reading 'get')`. But printing the response logs I see that the correct data is returned.

Screenshot 2023-09-20 003920

One thing I've noticed is that the `ofetch`/`$fetch` types don't exactly match with the directus `fetch` type, but then looking at the first two I also see `type FetchRequest = RequestInfo;`, so I imagine that this should just work.

### To Reproduce

```vue
<template>
  <div>
    <div>
      <button @click="signIn('admin@example.com', 'Passw0rd!')">
        Sign in
      </button>
      <button @click="signOut">
        Sign out
      </button>
      <button @click="refreshTokens">
        Refresh Tokens
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { createDirectus, authentication } from '@directus/sdk'

const client = createDirectus(
  'http://localhost:8055', {
    globals: {
      // @ts-expect-error
      fetch: $fetch.create({
        onResponse({ request, options, response }) {
          console.log('Request:', request)
          console.log('Options:',options)
          console.log('Response:',response)
        }
      }),
    }
  }).with(authentication({ autoRefresh: true, credetials: 'include'}))

async function signIn(email: string, password: string) {
  const loginData = await client.login(email, password).catch(console.error)
  console.log(loginData)
} 
async function signOut() {
  const loginData = await client.logout().catch(console.error)
  console.log(loginData)
} 
async function refreshTokens() {
  const loginData = await client.refresh().catch(console.error)
  console.log(loginData)
} 
</script>
```

### Directus Version

sdk v12.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #19747 

By providing our own custom types for `fetch` and `WebSocket` type errors (or casting as `any`) can be avoided when overwriting client globals.

### Before
image
image

### After
image

## Scope

What's changed:

- Replaced the old `typeof globalThis.fetch` and `typeof globalThis.WebSocket` globals types with custom types that allow more flexibility
- Added extra type guards for fetch output

## Potential Risks / Drawbacks

- Unexpected type issues as always

## Review Questions

- Please test websocket and fetch alternative libraries

---

### CODE REVIEW

File: sdk/src/utils/request.ts [hunk 1]
```diff
@@ -20,10 +21,8 @@ export const request = async <Output = any>(
 
 	const response = await fetcher(url, options);
 
-	const data = await extractData(response).catch((reason) => {
+	return await extractData(response).catch((reason) => {
```
Comment (paescuj) [inline sdk/src/utils/request.ts:24]: I think we can omit the `await` now
```suggestion
	return extractData(response).catch((reason) => {
```

File: sdk/src/types/globals.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
+// had to take the "| any" way out because supporting each and every "fetch" alternative type
+// is not feasable because all have different custom properties we cannot account for and the
+// "unknown" return type is checked at runtime by the extractData function
```
Comment (paescuj) [inline sdk/src/types/globals.ts:3]: Can we make this comment sound a bit more neutral? E.g. instead of `had to take the "| any" way out ...` something like `using "| any" to ensure ...`

Also might look a bit cleaner using `/* ... */` instead of `//`?

File: sdk/src/types/client.ts [hunk 3]
```diff
@@ -11,9 +13,9 @@ export interface DirectusClient<Schema extends object> {
  * All used globals for the client
  */
 export interface ClientGlobals {
```
Comment (DanielBiegler) [inline sdk/src/types/client.ts:15]: I'd make this a type instead of an interface but technically it doesnt really matter

File: sdk/src/types/globals.ts [hunk 4]
```diff
@@ -0,0 +1,18 @@
+// using "| any" to ensure compatibility with various "Fetch" alternative function signatures
+export type FetchInterface = (input: string | any, init?: RequestInit | any) => Promise<unknown>;
+
+export type UrlInterface = typeof URL;
+
+export type WebSocketConstructor = {
+	new (url: URL, protocols?: string | string[]): WebSocketInterface;
+};
+
+export interface WebSocketInterface {
```
Comment (DanielBiegler) [inline sdk/src/types/globals.ts:10]: `FetchInterface` and `UrlInterface` seem to be `type`s whereas only `WebSocketInterface` is an `interface` - We might wanna stick to one thing for consistency? ( super nitpicky I know :pray: )

File: sdk/src/utils/is-response.ts [hunk 5]
```diff
@@ -0,0 +1,15 @@
+/**
+ * Custom type guard to check if an object is likely a Fetch Response
+ */
+export function isFetchResponse(result: unknown): boolean {
```
Comment (paescuj) [inline sdk/src/utils/is-response.ts:4]:
```suggestion
export function isFetchResponse(result: unknown): result is Response {
```

With this, we could omit https://github.com/directus/directus/pull/19898/files#diff-3d8c3738e2feee86a090991f222b35ff4f8e7b6f3d110e0f33d7aa15b82701f7R10

**Review by paescuj — APPROVED** [review]
Looks & works great!
