### PR TITLE
fix(env): trim environment syntax prefix before casting

### LINKED ISSUE #20577: CORS issues due to missing headers in preflight response
### Describe the Bug

I discovered this while vetting the Directus Community example of the Agency-OS stack for production. The preflight requests to Directus do not return the proper header `Access-Control-Allow-Origin`, which is required by most secure browsers to evaluate 
CORS policy from the server side. We currently get CORS errors if a browser client talks directly to Directus.

Example Error Response from browser:
```bash
Access to fetch at 'https://cms.{{REDACTED}}.com/auth/login' from origin 'http://{{REDACTED}}.test:3000' has been blocked by
CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present
on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with
CORS disabled.
```

***What is expected to happen?***
With CORS_ENABLED set to `true`, if CORS_ORIGIN is also set, the server should respond to requests with a header named `Access-Control-Allow-Origin` and its value should be as it was configured on the instance by the user in CORS_ORIGIN env var (or other equivalent config methods) or if CORS_ORIGIN is simply `true` it should return the exact origin as the initiating request. It's equivalent as saying `Access-Control-Allow-Origin: '*'` The latter being less secure but still valid CORS policy.

### To Reproduce

Start a fresh instance of Directus. Using any browser-based client and the Directus sdk, attempt to login with a valid user and see that the browser will complain about CORS on that request. You can also inspect the headers (or lack of) using cURL or Postman.

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by mahendraHegde**
## Scope

What's changed:

- when `Environment Syntax Prefix` was used in env config, make sure to cast after removing the type prefix, currently it doesnt work.
- when the type is array cast each array elements as well
   - this was needed so that we can specify `CORS_ORIGIN=array:string:http://example1.com, regex:example2\.com$`

## Potential Risks / Drawbacks

- NA

## Review Notes / Questions

- NA

---

Fixes #20577

### CODE REVIEW

File: packages/env/src/lib/cast.ts [hunk 1]
```diff
@@ -5,9 +5,13 @@ import { guessType } from '../utils/guess-type.js';
 import { getCastFlag } from '../utils/has-cast-prefix.js';
 import { tryJson } from '../utils/try-json.js';
 
-export const cast = (key: string, value: unknown) => {
+export const cast = (key: string, value: unknown): unknown => {
 	const type = getCastFlag(value) ?? getTypeFromMap(key) ?? guessType(value);
 
+	if (getCastFlag(value)) {
+		value = (value as string).split(':').slice(1).join(':');
+	}
```
Comment (mahendraHegde) [inline packages/env/src/lib/cast.ts:13]: when the prefix contains a  type, remove the first prefix only so that arrays can have inner prefix for each items.
i.e : `array:regex:example\.com$,example2.com` becomes `regex:example\.com$,example2.com`, so that in the array item level cast each element can be casted as well.

**Comment by rijkvanzanten** [comment]
This is technically a duplicate of https://github.com/directus/directus/pull/21096, but this one correctly accounts for Array use so we'll supersede the other one with this 🙂

**Review by rijkvanzanten — APPROVED** [review]
