### PR TITLE
Fix #1886 – Map interface not filling other columns

### LINKED ISSUE #1886: Map interface not filling other columns
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: Apache on MAMP Pro
  - OS name and version: macOS High Sierra 10.13.1 Beta (17B25c)
  - Browser: Safari 11.0.1

## Expected Behavior
The map sets the value of another interface on select / change of the location on the map

## Actual Behavior
It doesn't

## Steps to Reproduce
 1. Add a map interface to a table
 2. Set up the map interface to fill a column with the respective item

## Schema Dump, Logs, or Screenshots
No console errors or anything

### PR DESCRIPTION
**Pull request by nstcactus**

### CODE REVIEW

File: app/core/interfaces/map/interface.js [hunk 1]
```diff
@@ -176,7 +177,7 @@ define([
       // Include the Google JSAPI for using Maps
       require(['https://www.google.com/jsapi'], function () {
         // Load Maps API using provided key, and call initializeMap() when API is loaded
-        google.load('maps', '3', {other_params: 'sensor=false&libraries=places&key=' + that.getApiKey(), callback: function () {
```
Comment (WellingGuzman) [inline app/core/interfaces/map/interface.js]: Reason for removing `sensor` Reference: https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

**Comment by WellingGuzman** [comment]
Thanks @nstCactus
