### PR TITLE
Show fields inside groups correctly in display templates for relational interfaces

### LINKED ISSUE #13111: Cant add a field that belongs to a group to display template
### Describe the Bug

Can't add a field that belongs to a group to display template

### To Reproduce

1. Create collection A
2. Create field a1, a2 and put them in a group (eg. detail group)
3. Create collection B
4. Create field b1 that have relationship to collection A (M2O/O2M/...)
5. Edit field b1, in Display section, add field a1, a2 to Display Template and click Save

### Errors Shown

no error shows, but after refreshing a1, a2 are not in Display Template >  it's actually not saved to Display Template

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

10.4.22-MariaDB-1:10.4.22+maria~focal

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by br41nslug**
fixes #13111

### CODE REVIEW

File: app/src/composables/use-field-tree.ts [hunk 1]
```diff
@@ -174,4 +175,20 @@ export function useFieldTree(
...
+						return flattenGroups(item.children);
+					} else {
+						item.children = flattenGroups(item.children);
+					}
+				}
+				return item;
+			});
+		}
+		return flattenGroups(tree);
+	}
```
Comment (rijkvanzanten) [inline app/src/composables/use-field-tree.ts:193]: This doesn't seem directly tied to the composable `use-field-tree`. Should we move this to `utils` (and add a unit test in the process)?

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/composables/use-field-tree.ts (hunk 1 above)
Comment (br41nslug) [reply app/src/composables/use-field-tree.ts:193]: I was on the fence where this logic should end up. Originally I had this generating the flattened tree and returning it together with the regular field tree here. Since it's a decently abstract function and indeed not directly tied to the `use-field-tree` composable anymore `utils` sounds like the better place for this.

**Comment by br41nslug** [comment]
# The problem
When fields are inside a group on the collection they will not be rendered inside display templates.
It does work when initially saving the fields but won't be rendered when re-opening the display template.

# The cause
The field is correctly being saved as `{{test_3}}` but is unabled to match that field_name against a nested tree like this because it only scans the root level.
```
[
  {
    "name": "ID",
    "field": "id",
    "collection": "test_13111",
    "key": "id",
    "path": "id",
    "type": "integer"
  },
  {
    "name": "Test 1",
    "field": "test_1",
    "collection": "test_13111",
    "key": "test_1",
    "path": "test_1",
    "type": "string"
  },
  {
    "name": "Group",
    "field": "group",
    "collection": "test_13111",
    "key": "",
    "path": "group",
    "group": true,
    "type": "alias",
    "children": [
      {
        "name": "Test 2",
        "field": "test_2",
        "collection": "test_13111",
        "key": "test_2",
        "path": "group.test_2",
        "type": "string"
      },
      {
        "name": "Test 3",
        "field": "test_3",
        "collection": "test_13111",
        "key": "test_3",
        "path": "group.test_3",
        "type": "string"
      }
    ]
  }
]
```

# The solution
Added a seperate filtered tree specifically for rendering the display template which does not contain the group nesting.
The filtered tree looks like:
```
[
  {
    "name": "ID",
    "field": "id",
    "collection": "test_13111",
    "key": "id",
    "path": "id",
    "type": "integer"
  },
  {
    "name": "Test 1",
    "field": "test_1",
    "collection": "test_13111",
    "key": "test_1",
    "path": "test_1",
    "type": "string"
  },
  {
    "name": "Test 2",
    "field": "test_2",
    "collection": "test_13111",
    "key": "test_2",
    "path": "group.test_2",
    "type": "string"
  },
  {
    "name": "Test 3",
    "field": "test_3",
    "collection": "test_13111",
    "key": "test_3",
    "path": "group.test_3",
    "type": "string"
  }
]
```
Providing this tree to the original `findTree` method instead of the `treeList` makes sure it can match its fields when rendering the template.

**Review by azrikahar — APPROVED** [review]

File: app/src/components/v-field-template/v-field-template.vue [hunk 2]
```diff
@@ -78,6 +79,10 @@ export default defineComponent({
 
 		watch(() => props.modelValue, setContent, { immediate: true });
 
+		const grouplessTree = computed(() => {
+			return flattenFieldGroups(treeList.value);
+		});
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply app/src/components/v-field-template/v-field-template.vue:84]: >  I'm assuming that that composable already starts of with a flat list before grouping it, so that would allow us to prevent having to ungroup the grouped list

I've wondered the same thing initially, but I assume we ultimately still need to use the current approach since the "flat list" doesn't contain related collections' fields? At least that's what I understood from useFieldTree, but I could be mistaken. 🤔

or maybe it'll require not using `topLevelFields` (since this is filtered without group), and a variation of `makeNode` that doesn't "transform" groups like it currently does (so that we'll still retain nested relational fields.

https://github.com/directus/directus/blob/4bab1946dcb366e28882b9d22ca42108eb0b66c4/app/src/composables/use-field-tree.ts#L69

**Review by rijkvanzanten — APPROVED** [review]
