### PR TITLE
Return 401 status code for expired tokens

### LINKED ISSUE #12275: Why am I getting a Token Expired error?
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am using the following versions of Directus:

client: "@directus/sdk": "^9.5.1",
server: "directus": "^9.6.0"

I have a website that check the JS SDK's /me method on the first page-load. If it returns "invalid user credentials" I don't log in, but I create a public "anonymous" user. There is also a sign-up/login button on my website. When clicked it will go through the login flow UI, and call /users/invite etc. and eventually create a user. When the user logs in with his credentials, the login works. BUT after the expiration time of the access_token, (when closing and reopening the website). The /me method returns a "token expired" error, and consequetly all the public methods of the SDK are not working anymore (as it is trying to refresh the expired token, or something?).

my access_token_TTL is 2 mins and refresh_token_TTL is 7 days in my .env config.

### To Reproduce

- login with JS SDK auth login method. 
- reload page
- /me method called in beginning correctly returns the logged in user object.
- wait till access_token_TTL has expired.
- reload page
- /me method greeted with a 'Token expired' error

expectation: 
- after access_token_TTL reached the refresh_token should refresh the access_token behind the scenes and the /me method should return the logged in user (after refreshing the token behind the scenes)
- when not logging in for a time-period longer than the refresh_token_TTL, the /me method should return a simple "invalid user credentials" and an anonymous user would be created (my personal implementation).

### Errors Shown

a4618ee.js:2 GET https://subneu.live/api/users/me 403 (Forbidden)
bc75317.js:1 Error: Token expired.

### What version of Directus are you using?

client: "@directus/sdk": "^9.5.1", server: "directus": "^9.6.0"

### What version of Node.js are you using?

v15.5.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

nginx on ubuntu

### LINKED ISSUE #12318: Invalid status code on INVALID_TOKEN
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Even though reading from the docs the Authentication Error Codes when auth token is not valid (ie expired) should be 401 

image

I'm getting 403.

image

It should probably be 401 Unauthorized.

The error could simply be a mismatch between code and documentation. 

In the  invalid-token.ts file (https://github.com/directus/directus/blob/66d63e7acf89e0a09d5b92bd976f87aaa67c788d/api/src/exceptions/invalid-token.ts) it says 403 while in the documentation 401.

### To Reproduce

1. login
2. let expire the **access_token**
3. make a request to **/items/:collectionName**

### Errors Shown

image

```
{
    "errors": [
        {
            "message": "Token expired.",
            "extensions": {
                "code": "INVALID_TOKEN",
                "stack": "Error: Token expired.\n    at verifyAccessJWT (/path/to/datahub/node_modules/directus/dist/utils/jwt.js:34:19)\n    at handler (/path/to/node_modules/directus/dist/middleware/authenticate.js:43:55)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

mysql

### What browser are you using?

API Call

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally, Docker

### PR DESCRIPTION
**Pull request by azrikahar**
Closes #12318

Currently expired token will receive status code `403`, but it should be `401` instead.

### CODE REVIEW

**Comment by azrikahar** [comment]
@aidenfoxx would you mind vetting the changes in auth drivers when you have the chance? 🙏

File: packages/sdk/src/base/auth.ts [hunk 1]
```diff
@@ -72,7 +74,10 @@ export class Auth extends IAuth {
 
 		if (this.timer) clearTimeout(this.timer);
 
-		const msWaitUntilRefresh = this._storage.auth_expires - this.msRefreshBeforeExpires;
+		const msWaitUntilRefresh = Math.max(
+			this._storage.auth_expires - this.msRefreshBeforeExpires,
+			this.msRefreshBeforeExpires
+		);
```
Comment (azrikahar) [inline packages/sdk/src/base/auth.ts:80]: @rijkvanzanten is this still prone to issues? Basically when we set `ACCESS_TOKEN_TTL` to `10s` for example, but `msRefreshBeforeExpires` is higher (defaults to `30000ms`/`30s`), doing simple subtraction ended up making it negative thus causes infinite loop of refreshes. This is why the use of Math.max here, but not sure if it's too rudimentary or not taking edge cases into account, if any. Or perhaps it should be "use storage auth expires ONLY without subtracting when it's already lower than msRefreshBeforeExpires".

File: api/src/auth/drivers/oauth2.ts [hunk 2]
```diff
@@ -281,7 +282,7 @@ export function createOAuth2AuthRouter(providerName: string): Router {
 				});
 			} catch (error: any) {
 				// Prompt user for a new refresh_token if invalidated
-				if (error instanceof InvalidTokenException && !prompt) {
+				if ((error instanceof TokenExpiredException || error instanceof InvalidTokenException) && !prompt) {
```
Comment (aidenfoxx) [inline api/src/auth/drivers/oauth2.ts:285]: This shouldn't be required for Directus token handling. This code is specific to when the OAuth "refresh_token" expires, and in that instance we need to trigger a special authorization from the user to get a new one.

Comment (azrikahar) [reply api/src/auth/drivers/oauth2.ts:285]: You're right, I was too fixated on the exception itself rather than the context of when it actually happens 🤦‍♂️

File: api/src/auth/drivers/oauth2.ts [hunk 3]
```diff
@@ -292,6 +293,8 @@ export function createOAuth2AuthRouter(providerName: string): Router {
 						reason = 'SERVICE_UNAVAILABLE';
 					} else if (error instanceof InvalidCredentialsException) {
 						reason = 'INVALID_USER';
+					} else if (error instanceof TokenExpiredException) {
+						reason = 'TOKEN_EXPIRED';
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/auth/drivers/oauth2.ts]: (ditto response in review above) 😅

**Comment by krazyjakee** [comment]
@azrikahar are we trying to solve the same issue? https://github.com/directus/directus/pull/12399

If so, would you mind taking a look at my PR? I feel the datetime check solution is preferable to the timer solution.

**Comment by azrikahar** [comment]
@krazyjakee yes the refresh token portion of this PR is trying to reach the same goal. A review on your PR was actually already requested, but it's just that I didn't have the bandwidth to look into it clearly. 

With that said, I do very much concur with the datetime check solution though, as I also share the same sentiment on the current timer solution! Will check out the PR when I have the chance 👍

**Comment by rijkvanzanten** [comment]
@azrikahar Lemmeknow if this is still relevant now that the other PR has been merged and released 🙂

File: packages/sdk/src/base/auth.ts (hunk 1 above)
Comment (azrikahar) [reply packages/sdk/src/base/auth.ts:80]: This is now obsolete after #12399 was merged 😀

**Comment by azrikahar** [comment]
> @azrikahar Lemmeknow if this is still relevant now that the other PR has been merged and released 🙂

The sdk+refresh portion are definitely not relevant anymore and has been removed 👍 Updated this PR to focus solely on the token expiry status code issue instead.

**Review by rijkvanzanten — APPROVED** [review]
