### PR TITLE
Fix field update for data types with length or boolean as default value

### LINKED ISSUE #6130: Problems with fields default values
Hello,
If field's default value is null (I leave field empty). All ok.
But if I need select default value (example for dropdown), I get similar error every time.
image

Basically everywhere where i need set default value like true or false for status.

Where I get error:
Every time I use standard field.

---
### Using with Boolean:
Shema:
image

Error:
image

---
### Using Input:
Shema:
image

Error:
image

---
### Using Input as Dropdown:
Shema:
image

Interface:
image

Error:
image

---

### Project details
Directus Version: 9.0.0-rc.74 and v9.0.0-rc.73
Environment: production
OS: Linux 4.19.0
Node: 14.17.0
Database: MariaDB
Database version: 10.5 (1:10.5.10+maria~focal)

Host:
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Version: 10.9
Architecture: amd64

Docker:
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #6130 

Tested with most field types in MySQL, PostgreSQL and SQLite.
I had to exclude `longtext` (used for JSON in MySQL) from this new behavior as it doesn't support the length property but Directus has it stored in the field schema.

### CODE REVIEW

File: api/src/services/fields.ts [hunk 1]
```diff
@@ -418,7 +418,12 @@ export class FieldsService {
 		if (field.schema?.has_auto_increment) {
 			column = table.increments(field.field);
 		} else if (field.schema?.data_type) {
-			column = table.specificType(field.field, field.schema.data_type);
+			// Append length to data type if it's stored in schema
+			const data_type =
+				field.schema?.max_length && field.schema.data_type !== 'longtext'
```
Comment (rijkvanzanten) [inline api/src/services/fields.ts:423]: Instead of hardcoding `longtext` here, lets figure out why it returns the length in the first place and fix it there 🙂

File: api/src/services/fields.ts [hunk 2]
```diff
@@ -418,7 +418,12 @@ export class FieldsService {
...
+					? `${field.schema.data_type}(${field.schema.max_length})`
```
Comment (rijkvanzanten) [inline api/src/services/fields.ts:424]: Is this the correct syntax cross-database?

File: api/src/services/fields.ts [hunk 3]
```diff
@@ -440,6 +445,10 @@ export class FieldsService {
 				['"null"', 'null'].includes(field.schema.default_value.toLowerCase())
 			) {
 				column.defaultTo(null);
+			} else if (typeof field.schema.default_value === 'boolean') {
+				// Convert boolean values to number (required for MySQL)
+				const default_value = field.schema.default_value === true ? 1 : 0;
```
Comment (rijkvanzanten) [inline api/src/services/fields.ts:450]: Does this work for Postgres? IIRC their true false is "TRUE" instead of 1

Comment (paescuj) [reply api/src/services/fields.ts:450]: Yes, it does - see https://www.postgresql.org/docs/9.1/datatype-boolean.html
Also tested with SQLite

File: api/src/services/fields.ts (hunk 1 above)
Comment (paescuj) [reply api/src/services/fields.ts:423]: Would prefer that too! 😄 
But I don't have any clue where to look at for this...

Comment (rijkvanzanten) [reply api/src/services/fields.ts:423]: Riiiiiiiiight here:

https://github.com/knex/knex-schema-inspector/blob/49f1e107bf7402fbe4516f1b976de56f6ba39e88/lib/dialects/mysql.ts#L58

File: api/src/services/fields.ts (hunk 2 above)
Comment (paescuj) [reply api/src/services/fields.ts:424]: Yup 👍 It's always like this `datatype(length)`, although there are some types which doesn't accept the length property (as we have seen with `longtext`)
Also I tested it with MySQL, PostgreSQL and SQLite (as mentioned above)

File: api/src/services/fields.ts (hunk 1 above)
Comment (paescuj) [reply api/src/services/fields.ts:423]: Niiiice, thanks 😄

File: api/src/services/fields.ts (hunk 2 above)
Comment (rijkvanzanten) [reply api/src/services/fields.ts:424]: We should ideally rely on Knex to do that properly (eg `knex.text('field', maxLength)`) instead of re-adding that through here 🤔 

I believe I added that "specific data type" option at the top just to make sure `m2o` fields would use the exact same type as the primary key, in order to resolve some issues around `integer` vs `integer unsigned`, but the API handles that correctly now when setting up a relation, so we might be able to save the headache here by getting rid of this whole if statement 🤔

Comment (paescuj) [reply api/src/services/fields.ts:424]: Not sure if I can follow you, I mean we would still need to distinct between using `knex.text`, `knex.decimal`, ..., right?

Comment (paescuj) [reply api/src/services/fields.ts:424]: Which lines do you mean exactly with the "whole if statement"?

Comment (rijkvanzanten) [reply api/src/services/fields.ts:424]: Oh sorry for the ambiguity..

This specific type support:

https://github.com/directus/directus/blob/b5abb0fb20f1f8984ce506ea45727ddd8e5621e3/api/src/services/fields.ts#L420-L421

was added just as an escape hatch for the MySQL/MariaDB situation where "integer unsigned" is a dedicated type that doesn't exist elsewhere, but we might not need that anymore now that the relational setup is no longer used. Removing this if-statement completely should also solve the issue you are now trying to workaround 🙂

Comment (paescuj) [reply api/src/services/fields.ts:424]: Ah, I see! Thanks 😸 I can look at this tomorrow - it's getting late here 😴

File: api/src/services/fields.ts (hunk 1 above)
Comment (rijkvanzanten) [reply api/src/services/fields.ts]: This is no longer an issue, as max_length isn't used for `text` types 💪🏻

**Review by rijkvanzanten — APPROVED** [review]

File: api/src/services/fields.ts (hunk 1 above)
Comment (paescuj) [reply api/src/services/fields.ts]: Nice 💪🏻
