### PR TITLE
Fix field/collection translated name not resetting after being removed

### LINKED ISSUE #16128: Translating the field not reverting without refreshing the app
### Describe the Bug

If you translate the field name, after removing the translation, it is not possible to return to the original name, the translation remains.

### To Reproduce

In the video below:

https://user-images.githubusercontent.com/90528895/197409274-27024a07-84ed-495b-ba78-b6ff3868b841.mp4

### Errors Shown

_No response_

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #16128

### Changes
- Fix field translation not being reset when the translation(s) gets removed

    https://user-images.githubusercontent.com/42867097/197431262-adfc2760-cdb4-4150-8de0-72790d526238.mp4

- Applied same fix for collections

   https://user-images.githubusercontent.com/42867097/197431118-5ffa1e18-6d6e-4ae5-abb3-f4d9b7a40339.mp4

- Removed unused translations in `settings.yaml`

    `translations` needs to be an array and the nested keys should be `language + translation`, not `language + translations` (plural). Hence these translations are never used, and it seems like they are outdated.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: app/src/stores/fields.ts [hunk 1]
```diff
@@ -72,6 +72,20 @@ export const useFieldsStore = defineStore({
 		parseField(field: FieldRaw): Field {
 			let name = formatTitle(field.field);
 
+			const localesToReset = !isNil(field.meta?.translations)
```
Comment (licitdev) [inline app/src/stores/fields.ts:75]: image

Adding a check for `field.meta!.translations?.length > 0` similar to the block after seems to fix the crashing bug. It seems that the typing is incorrect as the `field.meta.translations` could have a non-array value. 🤔 

image

Comment (azrikahar) [reply app/src/stores/fields.ts:75]: Have you restarted the API? This seems like the issue with `api/src/database/system-data/fields/settings.yaml` not using array syntax (and seems very outdated), which was also fixed in this PR.

Technically the length check does also fix this, but I'm also not sure should we presume that it can _not_ be an array, aside from this outdated directus_settings file 🤔

Comment (licitdev) [reply app/src/stores/fields.ts:75]: Ooo yes, restarting resolves the issue. 👍 I think it should be fine then, since the cause of this typing issue is due to the obsolete yaml config. Thanks!

Comment (azrikahar) [reply app/src/stores/fields.ts:75]: Just to add on a bit, partially didn't added the length check as sort of an attempt to "make them more similar" since collections doesn't have it:

https://github.com/directus/directus/blob/e4364df25bb793a1c0c77a852d6354b9eb090a1d/app/src/stores/collections.ts#L56

but in hindsight, maybe lodash `isEmpty` is more concise for null and empty array 🧐 or perhaps an additional `Array.isArray()` is ultimately much safer since technically a user should still be able to manually (mistakenly) set `translations` as an object since it is just a json column 👍

Comment (licitdev) [reply app/src/stores/fields.ts:75]: Good one, the check for array would definitely be useful in preventing app crashes like above on invalid values. 👍

**Comment by rijkvanzanten** [comment]
Can we sneak in a unit test or two for those stores? 🙂

**Comment by azrikahar** [comment]
> Can we sneak in a unit test or two for those stores? 🙂

Added!

**Review by rijkvanzanten — APPROVED** [review]
