### PR TITLE
Clear collection cache & schema cache on update

### LINKED ISSUE #7990: Switching collection from "Single Object" to normal breaks the collection display
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Switching a collection from single object to normal collection breaks the API.

### To Reproduce

1. Create a new collection
2. Set "Use as a single object" to true
3. Add some data
4. Change the "Use as single object" to false

Here is a video with repro as well https://youtu.be/1LTC2vPtrdw

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

v12.20.2

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Kubernetes

### PR DESCRIPTION
**Pull request by azrikahar**
fixes #7990

## Bug

Collections' cache and schema cache are cleared for Create and Delete operations, but not for Update operations.

## Solution

Add the same cache clearing logic to Update operations.

## Pending change

~Check comments below~ Resolved

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]
LGTM. ~~What comments?~~ didn't show in the GitHub app 🥲

File: api/src/services/collections.ts [hunk 1]
```diff
@@ -353,6 +361,14 @@ export class CollectionsService {
 			}
 		});
 
+		if (this.cache && env.CACHE_AUTO_PURGE) {
```
Comment (azrikahar) [inline api/src/services/collections.ts:364]: here UpdateMany() does not have the optional 3rd argument `opts?: MutationOptions`, hence I couldn't do `opts?.autoPurgeCache !== false` for the if statement here. Is this ok or the UpdateMany() should've had this optional argument as well?

Comment (rijkvanzanten) [reply api/src/services/collections.ts:364]: Let's add the same opts object parameter and check here as well 👍🏻
