### PR TITLE
Fix O2M/M2O node merging with parent

### LINKED ISSUE #24257: [INTERNAL_SERVER_ERROR] parentsByForeignKey.get is not a function or its return value is not iterable
### Describe the Bug

Having issues with saving anything that references any o2m table or a separate table: I have uploaded screenshots

image
image

These used to properly work on the 17th of december

### To Reproduce

Any one to many dashboard seems to generate this issue for us

### Directus Version

v11.3.5

### Hosting Strategy

Directus Cloud

### Database

_No response_

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

The following fixes have been applied for the respective node types:
- M2O
    - nested PK field is null due to permissions
    - The nested item id is valid but not linked to this item  
- O2M
  - The PK and FK have mismatched types
  - parent PK or FK in nested item are null due to permissions

## Potential Risks / Drawbacks

- Should be none as the behaviour is the same as before the performance improvement

## Review Notes / Questions

- N/A

## TODO
- [x] M2O
- [x] O2M
- [x] tests

#### nested PK field is null due to permissions
  - Create a policy that allows access to a field in the collection but not the `id` field
Screenshot 2025-01-06 at 5 58 30 PM
 
 - Create another policy that does NOT allow access to the `id` field under certain conditions
Screenshot 2025-01-06 at 5 58 49 PM
Screenshot 2025-01-06 at 5 59 02 PM

#### The nested item id is valid but not linked to this item
- Create an M2O field on the data model
- Create 2 entries in the M2O data collection
- Add one as an entry to the M2O field
- Attempt to filter the record by the M2O `id` field using the second non-linked M2O items id

#### The PK and FK have mismatched types
- Create collection `b` and add an input  field `aid` of type big integer
- Create collection `a` 
   - Create an O2M field to `b` and reference `aid` as the foreign key
   - Screenshot 2025-01-13 at 7 26 18 PM

- Create a record in collection `a`  with at least one referencing record to `b`
- Attempt to navigate to new record and observe the error

#### parent PK or FK in nested item are null
- Basically the same as `nested PK field is null due to permissions` but for the parent PK.

https://github.com/user-attachments/assets/a8a6d04b-1280-43e1-b0a1-f2ba35e0c791

---

Fixes #24257

### CODE REVIEW

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 1]
```diff
@@ -63,7 +63,14 @@ export function mergeWithParentItems(
 				parentItem[parentRelationField] = [];
 			}
 
-			const parentPrimaryKey = parentItem[parentPrimaryKeyField];
+			let parentPrimaryKey: string | number | null = parentItem[parentPrimaryKeyField];
```
Comment (hanneskuettner) [inline api/src/database/run-ast/utils/merge-with-parent-items.ts:66]: Let's use `PrimaryKey | null`

Comment (ComfortablyCoding) [reply api/src/database/run-ast/utils/merge-with-parent-items.ts]: Agreed! Resolved via be268ee18fd300b47b750780ac0153af7d9a8d06.

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 2]
```diff
@@ -86,15 +93,17 @@ export function mergeWithParentItems(
 				continue; // Avoids adding the nestedItem twice
 			}
 
-			const parentPrimaryKey =
+			const parentPrimaryKey: string | number | null =
```
[the remark this answers is not in the document]
Comment (ComfortablyCoding) [reply api/src/database/run-ast/utils/merge-with-parent-items.ts]: be268ee18fd300b47b750780ac0153af7d9a8d06

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 3]
```diff
@@ -46,10 +58,20 @@ export function mergeWithParentItems(
...
+
+			let parentPrimaryKey: PrimaryKey | null = parentItem[parentPrimaryKeyField];
 
-			const parentPrimaryKey = parentItem[parentPrimaryKeyField];
+			// null if the user has no access to parent PK
+			if (parentPrimaryKey === null) {
+				continue;
+			} else {
+				// ensure key access is type agnostic
+				parentPrimaryKey = parentPrimaryKey.toString();
```
Comment (hanneskuettner) [inline api/src/database/run-ast/utils/merge-with-parent-items.ts:73]: Did you observe any specific bug that warrants this conversion?

We are not doing it in the M2O case above either and I would expect the fields to have the correct type when coming back from the DB?

Comment (ComfortablyCoding) [reply api/src/database/run-ast/utils/merge-with-parent-items.ts:73]: Yes this was the cause of the `O2M` error reported in the #24257

Comment (licitdev) [reply api/src/database/run-ast/utils/merge-with-parent-items.ts:73]: Can confirm that this fixes the mismatched types when a BigInt field is used to store the Int PK and vice versa as the BigInt is stringified.

**Review by licitdev — APPROVED** [review]
