### PR TITLE
fix nested array updates for relational interfaces

### LINKED ISSUE #13551: Deleting repeater items in translations interface is not working
### Describe the Bug

When trying to delete a single repeater field item with more than 1 items, the item does not delete. Instead it just renames the item using the name of the next item.

### To Reproduce

Added a json field with repeater interface on a translation model with a single option
image
image2

If I save and come back then exactly one item is deleted and I have to repeat the process for all items.

Here is a screen recording of my issue:

[Deleting repeater items bug](https://b2.apptime.gr/file/apptime/bug.mov)

### Errors Shown

No visible errors

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #13551

## Problem

Repeaters in Translations are not "displaying" properly on edits, although the raw values are correctly saved:

https://user-images.githubusercontent.com/42867097/170494106-8cd6a268-7567-4a9b-9e05-4cbb28a28db7.mp4

For the `displayItems`, as seen here:

https://github.com/directus/directus/blob/44df77a3a040ad6bce1099244dc196d7a446ecc0/app/src/composables/use-relation/use-relation-multiple.ts#L88-L108

It is using the lodash `merge` function for edits/updates:

https://github.com/directus/directus/blob/44df77a3a040ad6bce1099244dc196d7a446ecc0/app/src/composables/use-relation/use-relation-multiple.ts#L97-L101

This in turn causes merging of arrays to behave unlike as expected, since it's doing:

```
[{"value":"DE 1"},{"value":"DE 2"},{"value":"DE 3"}] 
```

+  

```
[{"value":"DE 1"},{"value":"DE 3"}]
```

Result = `[{"value":"DE 1"},{"value":"DE 3"},{"value":"DE 3"}]`

But the expected result is `[{"value":"DE 1"},{"value":"DE 3"}]` instead.

## Solution

Replace the `merge` function with `mergeWith` function so that we can ensure arrays in particular are always replace by the source(s).

https://user-images.githubusercontent.com/42867097/170494077-1a7c0750-f31b-4a51-bdec-dac761296c76.mp4

### CODE REVIEW

File: app/src/composables/use-relation/use-relation-multiple.ts [hunk 1]
```diff
@@ -94,10 +94,15 @@ export function useRelationMultiple(
...
 
 			if (editsIndex !== -1) {
-				merge(
+				mergeWith(
 					updatedItem,
 					{ $type: 'updated', $index: editsIndex, $edits: editsIndex },
-					_value.value.update[editsIndex]
+					_value.value.update[editsIndex],
+					(obj, src) => {
+						if (Array.isArray(obj) && Array.isArray(src)) {
```
Comment (rijkvanzanten) [inline app/src/composables/use-relation/use-relation-multiple.ts:102]: How does it handle JSON fields? Same problem?

Comment (azrikahar) [reply app/src/composables/use-relation/use-relation-multiple.ts:102]: Tested on a JSON field:

## Before

https://user-images.githubusercontent.com/42867097/170508019-bba4154a-1b5c-419b-9d20-10b3b1b9854d.mp4

## After

https://user-images.githubusercontent.com/42867097/170508003-4847cd68-721b-41b1-a3ab-a6b76f20be5d.mp4

Comment (rijkvanzanten) [reply app/src/composables/use-relation/use-relation-multiple.ts:102]: @azrikahar What if the value goes from 

```json
{
  "value": {
    "a": "x"
  }
}
```

to

```json
{
  "value": {
    "b": "y" 
  }
}
```

do you end up with 

```json
{
  "value": {
    "b": "y" 
  }
}
```

or 

```json
{
  "value": {
    "a": "x",
    "b": "y" 
  }
}
```

?

Comment (azrikahar) [reply app/src/composables/use-relation/use-relation-multiple.ts]: It was 100% turning into the latter as you suspected (rightfully so as it's also an expected behavior of `merge`):

https://user-images.githubusercontent.com/42867097/170643829-0712a974-06a1-4f4c-8473-b1a05430c717.mp4

That being said, I've updated the PR to treat edits as the single source of truth instead, and it does work for all the cases (including arrays) we've discussed:

https://user-images.githubusercontent.com/42867097/170643907-0e4da514-18dc-40fe-aecb-f9f2d245a070.mp4

Could there be any other edge cases not accounted for here? 🤔 Though once again this is technically the "display" being incorrect, but the actual update has been correct even prior to this PR:

https://user-images.githubusercontent.com/42867097/170644554-c8a58cde-f0ff-4c0a-9afc-14d15591bbc8.mp4

Comment (rijkvanzanten) [reply app/src/composables/use-relation/use-relation-multiple.ts]: Alternatively, relying on `assign` rather than `merge` might also do the trick. I think we'd only want to merge on the top-level properties here anyways right?

**Review by rijkvanzanten — APPROVED** [review]
