### PR TITLE
Fix large integer string used in filters

### LINKED ISSUE #8147: Filters do not work for specific strings
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Filters work differently based on the field value.

Ex1. For a string field with the value "107748382524547168598", the following does not work:
Equals <exact string>
Contains <exact string>
Starts/ends with <exact string>

However, if I just remove a few characters, the following _does_ work:
Contains 10774838252454716 (removed 4 characters from the end)
Starts with 10774838252454716 (removed 4 characters from the end)
Ends with 8382524547168598 (removed 5 characters from the beginning)
Specifically, Contains and Starts With can only check for a string with 17 characters **for this particular string**, and ends with can only check for 16 characters.

Ex2.
However, if I change the value to "000000000000000001234", it works just fine--all of the filters mentioned above can correctly check the entire value.

Ex3. Using "123456789012345678901":
Equals does not work.
Contains only starts working when I remove enough characters to make "1234567890123456" (eg. 16 characters).
Starts with only works under "12345678901" (eg. 11 characters).
Ends with only works under "6789012345678901" (eg. 16 characters).

### To Reproduce

1. Create a new collection with default settings
2. Add a single string field to it (input, raw value, default settings otherwise)
3. Add an item with the following value: 107748382524547168598
4. Test filters as described above
5. Change the value to "000000000000000001234" and test again--everything should work fine
6. Change the value to "123456789012345678901" and test again--results should match the described limitations

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying Directus?

Azure

### PR DESCRIPTION
**Pull request by licitdev**
Fixes #8147. Edit: Updated fix no longer has inaccuracy. Thank you @joselcvarela!

### CODE REVIEW

**Comment by joselcvarela** [comment]
What you are mentioning can be related, but also the problem is the field is a string and not a number like the author of the issue said:
> ### To Reproduce
>...
> 2. **Add a single string field to it (input, raw value, default settings otherwise)**
>...

**Comment by licitdev** [comment]
@joselcvarela The filter side will cast all "numbers" in strings to number type when the JSON.parse is called in the below code  https://github.com/directus/directus/blob/4bf55e50f6d6b65a98709c846d3495900d60fe4c/api/src/utils/sanitize-query.ts#L104

So it does not matter if it is a string field or integer field. The fix applies to all.

**Comment by joselcvarela** [comment]
Yeah, filters do not know about schema on that stage. I wonder if we should check them against the schema before the query.
Anyway, I have checked why is this `deepMap` was inserted and found this:
https://github.com/Oreilles/directus/commit/62725b2cbd5c9267bc604fe0886bc16a40a95809

I am only afraid if `val` is a JSON string, it couldn't be parsed if is greater than 15 characters

**Comment by licitdev** [comment]
> Yeah, filters do not know about schema on that stage. I wonder if we should check them against the schema before the query.
I would think that there is no need for that as it's `JSON.parse()` and not a custom parser. JSON defines seven value types: string, number, object, array, true, false, and null. Hence the issue here is that a super long string that only contains numbers, which the fix is to let it remain as a string, instead of converting to an incorrect number.

> I am only afraid if `val` is a JSON string, it couldn't be parsed if is greater than 15 characters
Ah yes, that is definitely an issue. Will add a check to see if the parsed output is of number type. Thank you!

File: api/src/utils/sanitize-query.ts [hunk 1]
```diff
@@ -98,7 +98,12 @@ function sanitizeFilter(rawFilter: any, accountability: Accountability | null) {
 
 	filters = deepMap(filters, (val) => {
 		try {
-			return JSON.parse(val);
+			const parsedObject = JSON.parse(val);
+			if (parsedObject == 'number' && typeof val == 'string' && val.length > 15) {
```
Comment (joselcvarela) [inline api/src/utils/sanitize-query.ts:102]: You are comparing the returned value with string `number`.

Why not to use `Number.isSafeInteger` ?

Comment (licitdev) [reply api/src/utils/sanitize-query.ts:102]: Oh dear, it's supposed to be `typeof parsedObject`. ><

Comment (joselcvarela) [reply api/src/utils/sanitize-query.ts]: Don't you want to try with `Number.isSafeInteger`? It is more clean and explicit.

Comment (licitdev) [reply api/src/utils/sanitize-query.ts]: Wow, I didn't know that `Number.isSafeInteger` exists. 👍🏻 Pushing a new fix now~

Comment (licitdev) [reply api/src/utils/sanitize-query.ts]: Pushed. Thank you @joselcvarela~

**Review by joselcvarela — APPROVED** [review]

File: api/src/utils/sanitize-query.ts (hunk 1 above)
Comment (rijkvanzanten) [reply api/src/utils/sanitize-query.ts]: > Wow, I didn't know that Number.isSafeInteger exists. 👍🏻 Pushing a new fix now~

TIL! Didn't know that was a thing either 🙂

**Review by rijkvanzanten — APPROVED** [review]
