### PR TITLE
Api / Cloudinary: Use version to prevent cached assets

### LINKED ISSUE #24111: Api / Cloudinary: Sometimes modified assets are not available
### Describe the Bug

When we upload a file and then we modify it, for example using Crop, the new version of the asset sometimes is not available.
Here's an example:

https://github.com/user-attachments/assets/7f7fe5ef-ee50-474f-9724-de265278b2f2

I have tried to understand when "sometimes" happens but couldn't figure it out.
I believe that's related with Cloudinary cache and asset size.

### To Reproduce

Setup your project with Cloudinary with your configs:
```
STORAGE_LOCATIONS: "XXX",
STORAGE_CLOUDINARY_DRIVER: "XXX",
STORAGE_CLOUDINARY_CLOUD_NAME: "XXX",
STORAGE_CLOUDINARY_ACCESS_MODE: "XXX",
STORAGE_CLOUDINARY_API_KEY: "XXX",
STORAGE_CLOUDINARY_API_SECRET: "XXX",
```

Upload an asset and see thumbnails are getting generated
Edit file, Crop asset and Save
If thumbnails get generated as expected, try again. You should see thumbnails failing around 1 in 5 attempts.

### Directus Version

11.2.2 (main)

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope
There's times that when an asset is edited, the respective thumbnails are not regenerated.
It seems to be related with cache, so we just ask fresh assets from Cloudinary by passing `version` with the last modified date.
This ensures fresh assets are always requested.

Here's an example:

https://github.com/user-attachments/assets/8b9182d3-4056-4ce4-9d27-4396f5b119aa

What's changed:

- Fixed thumbnails not being generated after edit for Cloudinary storage

## Potential Risks / Drawbacks

- None 🤔

## Review Notes / Questions

- At the moment `version` is only being passed to Cloudinary driver

---

Fixes #24111

### CODE REVIEW

File: api/src/services/assets.ts [hunk 1]
```diff
@@ -122,6 +122,9 @@ export class AssetsService {
 		const type = file.type;
 		const transforms = transformation ? TransformationUtils.resolvePreset(transformation, file) : [];
 
+		const modified_on = file.modified_on ? new Date(file.modified_on) : undefined;
+		const version = modified_on ? (modified_on.getTime() / 1000).toFixed() : undefined;
```
Comment (licitdev) [inline api/src/services/assets.ts:126]: Let's use camelCase instead and we'll need a changeset too.

```suggestion
		const modifiedOn = file.modified_on ? new Date(file.modified_on) : undefined;
		const version = modifiedOn ? (modifiedOn.getTime() / 1000).toFixed() : undefined;
```

**Review by licitdev — APPROVED** [review]
@joselcvarela Thank you! 🚀
