### PR TITLE
throw an error on invalid file upload

### LINKED ISSUE #17999: File upload from compresed folder
### Description
When you try to upload a file from a compressed folder like zip, rar etc.. directly on directus drag and drop file input,
the application crashes. I did not try with third-party inputs like a form on my own project, but I assumed that the same thing could happen. But the real problem is, after restarting the app, some of the files are corrupted and the directus cant recognizes them.

### Error
```terminal
ERROR: The "path" argument must be of type string. Received null
directus-directus-1    |     err: {
directus-directus-1    |       "type": "TypeError",
directus-directus-1    |       "message": "The \"path\" argument must be of type string. Received null",
directus-directus-1    |       "stack":
directus-directus-1    |           TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
directus-directus-1    |               at new NodeError (node:internal/errors:400:5)
directus-directus-1    |               at validateString (node:internal/validators:163:11)
directus-directus-1    |               at join (node:path:1172:7)
directus-directus-1    |               at DriverLocal.fullPath (file:///directus/node_modules/@directus/storage-driver-local/dist/index.js:11:32)
directus-directus-1    |               at DriverLocal.exists (file:///directus/node_modules/@directus/storage-driver-local/dist/index.js:40:28)
directus-directus-1    |               at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:75:61)
directus-directus-1    |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus-directus-1    |               at async /directus/node_modules/directus/dist/controllers/assets.js:125:36
directus-directus-1    |       "code": "ERR_INVALID_ARG_TYPE"
```

The big problem with that is, if an employee wants to upload, let's say 100 pdf or images and they got it in compressed format when they try to upload from there they can accidentally crash the app.

### To Reproduce

Docker image: directus/directus:9.22.4
db: mssql
host: aws s3

1. Create a collection with a file or input.
2. compress the file into rar or zip format.
3. open the compressed folder, grab the file, and drop it into created collection file input field.

Same could be true for directus folders.

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Added a missing integrity check for whether there are actual files to be uploaded. It does not fix the linked issue but does throw an error now instead of saving an invalid 0byte file to the Directus library.

Note: This change makes the assumption that a 0 byte file is an error!

### Before

https://user-images.githubusercontent.com/9389634/229523407-42a453d2-6d7a-4d2a-a89e-2d7ada16bd65.mp4

https://user-images.githubusercontent.com/9389634/229523518-2371419f-8e78-425d-8d98-d2724c15382c.mp4

### After

https://user-images.githubusercontent.com/9389634/229523544-264c6876-d528-4143-9a5a-57ba5e604b20.mp4

https://user-images.githubusercontent.com/9389634/229523557-dc45c776-24b4-41e2-b8e5-c4e83a71e4d4.mp4

Fixes #17999 

## Type of Change

- [x] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: app/src/components/v-upload.vue [hunk 1]
```diff
@@ -146,10 +154,12 @@ function useUpload() {
 		if (props.folder) {
 			folderPreset.folder = props.folder;
 		}
-
 		try {
-			numberOfFiles.value = files.length;
+			if (!validFiles(files)) {
+				throw new Error('An error has occurred while uploading the files.');
```
Comment (azrikahar) [inline app/src/components/v-upload.vue:159]: Do we want to be slightly more explicit here? Just in case any users might keep retrying but not sure what happened.

**Review by azrikahar — COMMENTED** [review]
> This change makes the assumption that a 0 byte file is an error!

This can somewhat be a very good question, but I personally am not aware of any valid use case of "legitimate 0 byte file" at the moment so I can only agree with this assumption. Hopefully others can shed more light on this, if any 👍

File: app/src/components/v-upload.vue [hunk 2]
```diff
@@ -129,6 +129,14 @@ const filterByFolder = computed(() => {
 	return { folder: { id: { _eq: props.folder } } } as Filter;
 });
 
+function validFiles(files: FileList) {
+	if (files.length === 0) return false;
+	for (const file of files) {
+		if (file.size === 0) return false;
+	}
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply app/src/components/v-upload.vue:136]: I do like the use of `.some` but lets return that instead of inlining it in a conditional 😄

File: app/src/components/v-upload.vue (hunk 1 above)
Comment (br41nslug) [reply app/src/components/v-upload.vue:159]: Was considering the same but im afraid this may not be the only situation that could trigger these conditions (even though im not explicitly aware of any) 🤔 So for now i chose the generic message but happy to hear any alternatives

File: app/src/components/v-upload.vue (hunk 2 above)
[the remark this answers is not in the document]
Comment (br41nslug) [reply app/src/components/v-upload.vue:136]: I was wrong for us to be able to use `.some` here it needs to be an array and a `FileList` is technically not one so we'd have to use `Array.from(files).some((file) => file.size === 0);` which i find less readable in the end than the for loop 😄

File: app/src/components/v-upload.vue (hunk 1 above)
Comment (br41nslug) [reply app/src/components/v-upload.vue:159]: There aren't really more errors to throw i think 🤔 I currently see it as either abstract "an error in uploading has occured" or specificly the issue we're covering "No data to upload. If you're directly uploading archived files then unpack them first". The check itself is not so specific though and possibly could trigger on more upload error situations like file read errors etc.

**Review by azrikahar — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]
