### PR TITLE
SDK Embed WebSocket constants

### LINKED ISSUE #19801: SDK relies on global `WebSocket` for state checks
### Describe the Bug

I am trying to create subscription to my custom collection in the directus database:

```ts
   import * as WebSocket from 'isomorphic-ws';
   Object.assign(global, { WebSocket });

   const client = createDirectus(configService.get<string>('directus.url'), {
          globals: { WebSocket: WebSocket as any },
        })
          .with(rest())
          .with(staticToken(configService.get<string>('directus.token')))
          .with(
            realtime({
              authMode: 'handshake',
            }),
          );

   await client.connect();
   client.onWebSocket('message', console.info);
   const { subscription } = await this.client.subscribe('art_assets' as never, {
      event: 'update',
    });

    for await (const data of subscription) {
        console.info('data', data);
    }
```

I've received only one message from directus: `{ type: 'auth', status: 'ok' }`

After this, subscription iterator is not producing any events. I am sure that collection name is correct.

Also, I don't like that I have to add WebSocket to global to make it work. It seems that typings should be changed for to support node.js server env.

### To Reproduce

To reproduce you can try my code from the bug description. Don't forget to do `npm i ws isomorphic-ws`.

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #19801 

# Scope

What's changed:

- Shipping the WebSocket Connection State constants with the SDK instead of relying they exist on the global object

## Before
image

## After
No error

### CODE REVIEW

File: sdk/src/realtime/composable.ts [hunk 1]
```diff
@@ -26,6 +26,9 @@ const defaultRealTimeConfig: WebSocketConfig = {
 	},
 };
 
+const WS_OPEN = 1;
+const WS_CLOSED = 3;
```
Comment (rijkvanzanten) [inline sdk/src/realtime/composable.ts:30]: Shall we use a TS enum for this?

```ts
enum WebSocketState {
  Open = 1,
  Closed = 3
}

ws.readyState !== WebSocketState.Open
```

Comment (br41nslug) [reply sdk/src/realtime/composable.ts:30]: I am not a huge fan of `enum`s as they walk the line between Type and Value resulting in some rough edges in their usage. I'd prefer a constant here since we don't need the Types side of the data.

```ts
const WebSocketState = {
  OPEN: 1,
  CLOSED: 3
} as const;
```

Comment (paescuj) [reply sdk/src/realtime/composable.ts:30]: I agree!

**Review by paescuj — APPROVED** [review]

File: sdk/src/realtime/composable.ts (hunk 1 above)
Comment (rijkvanzanten) [reply sdk/src/realtime/composable.ts]: Oki!

**Review by rijkvanzanten — APPROVED** [review]
