### PR TITLE
Fix sdk auth

### LINKED ISSUE #3313: Non persistent user session after logging in
The JavaScript SDK doesn't seem to store cookies to make the current user logged in after calling the `directus.auth.login()` method.
I'm able to successfully log in, but after a page refresh I get a 401 error when trying to fetch the current user.

Here's my setup:
```
const directus = new DirectusSDK("http://localhost:8055", {
  auth: {
    mode: "cookie",
    autoRefresh: true,
  },
})
```

I also get a 400 error right after logging in. The error seems to belong to the `/auth/refresh` endpoint.

### LINKED ISSUE #3574: SDK token can't be set to `null` in Node server
When trying to use sdk in Express, and set token to null, Express throws error when sending request.
Error: `TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"`.
It looks like token setter must remove Auth header, because Express can't parse `undefined`. In browser it works, but header is not removed, it's value is simply `undefined`. 
This is a common use case for people who use Next, Nuxt or any other SSR.

Sample code, created with `express-generator`, nothing except this file is changed:
```js
var express = require('express');
var DirectusSDK = require('@directus/sdk-js');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  const sdk = new DirectusSDK('http://localhost:8055', {auth: {authRefresh: false}});
  sdk.auth.token = null;
  sdk.items('reviews').read().then(console.log).then(() => {
    res.render('index', { title: 'Express' });
  }).catch(console.log);

});

module.exports = router;


```

Directus rc28, pg,

### LINKED ISSUE #3641: [sdk-js] auth.logout() does not include refresh_token required by /auth/logout API
https://github.com/directus/directus/blob/d9dc466f9acdb5f53ecec3773ca01e40e6294bdc/packages/sdk-js/src/handlers/auth.ts#L93

### LINKED ISSUE #3785: SDK makes undesired/unhandled refresh request
When auth's autoRefresh is enabled, the Auth's constructor will make a refresh request that will always fail if there's no (valid) token information. This will always throw an unhandled rejection.

This is a problem for scenarios like inside Gatsby that they monitor all unhandled exceptions/rejections and will stop the whole process.

```js
// Node.js
const Directus = require("@directus/sdk-js");

class MemoryStore {
  constructor() {
    this.values = {};
  }
  getItem(key) {
    return this.values[key];
  }
  setItem(key, value) {
    return this.values[key] = value;
  }
}

async function main() {
  const directus = new Directus('https://domain.com', {
    auth: {
      mode: 'json',
      autoRefresh: true,
      storage: new MemoryStore(),
    },
  });

  await directus.auth.login({
    email: 'admin@example.com',
    password: 'password',
  });
}

main().catch(err => {
  console.log("Oops: " + err.message)
});

```

This will solve the issue:

```js
// Node.js
const Directus = require("@directus/sdk-js");

class MemoryStore {
  constructor() {
    this.values = {};
  }
  getItem(key) {
    return this.values[key];
  }
  setItem(key, value) {
    return this.values[key] = value;
  }
}

async function main() {
  const directus = new Directus('https://domain.com', {
    auth: {
      mode: 'json',
      // autoRefresh: true, // disable auto refresh
      storage: new MemoryStore(),
    },
  });

  directus.auth; // let the constructor run
  directus.auth.autoRefresh = true; // enable autoRefresh again

  await directus.auth.login({
    email: 'admin@example.com',
    password: 'password',
  });
}

main().catch(err => {
  console.log("Oops: " + err.message)
});

```

### PR DESCRIPTION
**Pull request by apstanisic**
Fixes https://github.com/directus/directus/issues/3313
Fixes https://github.com/directus/directus/issues/3785
Fixes https://github.com/directus/directus/issues/3641
Fixes https://github.com/directus/directus/issues/3574

### CODE REVIEW

**Comment by apstanisic** [comment]
I still have to add and remove some tests, but it should all work.
Manually tested this and works:
```ts
// Page 1
sdk.auth
     .login({ email: "test@example.com", password: "password" })
     .then(console.log)
     .then(() => sdk.auth.refresh())
     .then(console.log);
// Page 2 (refreshed)
new Directus(url).auth.refresh().then(console.log)
// Page 3 (refreshed)
new Directus(url).items('test').read().then(console.log)

**Comment by apstanisic** [comment]
Everything should work, I'm not proudest of tests, but they work.

File: packages/sdk-js/src/handlers/auth.ts [hunk 1]
```diff
@@ -18,13 +18,19 @@ export class AuthHandler {
 	private storage: AuthStorage;
 	private mode: 'cookie' | 'json';
 	private autoRefresh: boolean;
+	private autoRefreshTimeout?: any;
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:21]: Lets make this type of Timeout/number

File: packages/sdk-js/src/handlers/auth.ts [hunk 2]
```diff
@@ -18,13 +18,19 @@ export class AuthHandler {
...
+	/** Used for tracking if accessToken is restored from store to config */
+	private accessTokenInitialized: boolean = false;
 
 	constructor(axios: AxiosInstance, options: AuthOptions) {
 		this.axios = axios;
 		this.storage = options.storage;
 		this.mode = options.mode;
 		this.autoRefresh = options.autoRefresh;
 
+		this.axios.interceptors.request.use((config) => this.initializeAccessToken(config));
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:32]: Instead of doing this every request, would it be possible to do this only when the SDK is initialized the first time?

File: packages/sdk-js/src/handlers/auth.ts [hunk 3]
```diff
@@ -42,45 +48,74 @@ export class AuthHandler {
...
+	 * Refresh access token 10 seconds before expiration
+	 */
 	async refresh() {
+		clearTimeout(this.autoRefreshTimeout);
+
+		this.expiresAt = await this.storage.getItem('directus_access_token_expires');
+		if (!this.expiresAt) return;
+
+		if (Date.now() + 10000 < this.expiresAt) {
+			this.autoRefreshTimeout = setTimeout(
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:81]: It's possible that the user calls `refresh()` manually with `autoRefresh` disabled. In that case we shouldn't create the timeout

File: packages/sdk-js/src/handlers/auth.ts [hunk 4]
```diff
@@ -42,45 +48,74 @@ export class AuthHandler {
...
 			payload['refresh_token'] = refreshToken;
 		}
 
-		const response = await this.axios.post('/auth/refresh', payload);
+		const response = await this.axios.post('/auth/refresh', payload, {
+			// If access_token is expired, it will throw 401, so we remove it from headers
+			transformRequest: (data, headers) => {
+				delete headers.Authorization;
+				return data;
+			},
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:100]: We should remove it from the axios headers by setting `this.token` to null. That should set the default header in axios

File: packages/sdk-js/src/handlers/auth.ts [hunk 5]
```diff
@@ -94,4 +129,26 @@ export class AuthHandler {
...
+	 * There is no prettier way to do this. We need to set access token before first request.
+	 * This way we intercept axios request and only first time request token from store,
+	 * and allows us to do new Directus(url).items(col).read() without having to handle
+	 * access_token restoration in methods
+	 */
+	private async initializeAccessToken(config: AxiosRequestConfig) {
+		if (!this.accessTokenInitialized) {
+			this.accessTokenInitialized = true;
+			const token = await this.storage.getItem('directus_access_token');
+			console.log(11);
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:143]:
```suggestion
```

File: packages/sdk-js/src/handlers/auth.ts [hunk 6]
```diff
@@ -94,4 +129,26 @@ export class AuthHandler {
...
+
+			if (token) {
+				console.log(21);
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:146]:
```suggestion
```

File: packages/sdk-js/src/handlers/auth.ts [hunk 7]
```diff
@@ -94,4 +129,26 @@ export class AuthHandler {
...
+				this.token = token;
+				config.headers.Authorization = `Bearer ${token}`;
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/handlers/auth.ts:148]: This isn't needed. The setter for token initializes the header in axios

File: packages/sdk-js/src/index.ts [hunk 8]
```diff
@@ -27,15 +27,18 @@ class DirectusSDK {
...
 		});
 
 		this.authOptions = {
 			storage:
-				options?.auth?.storage !== undefined ? options.auth.storage : new MemoryStore(),
-			mode: options?.auth?.mode !== undefined ? options.auth.mode : 'cookie',
-			autoRefresh:
-				options?.auth?.autoRefresh !== undefined ? options.auth.autoRefresh : false,
+				options?.auth?.storage ??
+				(typeof window === 'undefined' ? new MemoryStore() : new BrowserStore()),
```
Comment (rijkvanzanten) [inline packages/sdk-js/src/index.ts:36]: Nice 👍 smart addition to add a localStorage store as default for browser use

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: packages/sdk-js/src/handlers/auth.ts (hunk 7 above)
Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts:147]: It's not the same. Changing this.token in `this.axios.interceptors.request.use` does not changes token for current request.
So if user starts app with `new SDK(...).items('posts').read()` setting `this.token` would not set access token for existing request

Here is the code with console.log added
Screenshot from 2020-12-16 22-40-34
Here is console
Screenshot from 2020-12-16 22-41-42

Comment (rijkvanzanten) [reply packages/sdk-js/src/handlers/auth.ts:147]: Ah right, that ties back into my other comment then 🙂  https://github.com/directus/directus/pull/3337#discussion_r544592396

File: packages/sdk-js/src/handlers/auth.ts (hunk 4 above)
Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts:100]: Should we remove it?
If this happens:
sdk sends auto refresh request without awaiting and deletes this.token
user sends request
sdk finishes auto refresh request
user will send request without access token and will get 401, without knowing the reason.

This way we:
sdk sends auto refresh without awaiting, and leaves access token
user sends request with valid access token
sdk finishes auto refresh request
user receives data as normal

Comment (rijkvanzanten) [reply packages/sdk-js/src/handlers/auth.ts:105]: I meant that we should try to keep all axios headers defaulting within that `token` getter/setter instead of deleting those elsewhere, otherwise it'll get a little difficult to track where what is happening with that token later on 🙂

File: packages/sdk-js/src/handlers/auth.ts (hunk 2 above)
Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts]: Added `this.axios.interceptors.request.eject` in `initializeAccessToken`

File: packages/sdk-js/src/handlers/auth.ts (hunk 3 above)
Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts:86]: added check

Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts:86]: Should he be able to call `refresh` if he/she is not logged in at all? `if (!this.expiresAt) return;` server as check if user is logged in

File: packages/sdk-js/src/handlers/auth.ts (hunk 7 above)
Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts:151]: Yeah, added `eject` in `initializeAccessToken`

File: packages/sdk-js/src/handlers/auth.ts (hunk 4 above)
Comment (apstanisic) [reply packages/sdk-js/src/handlers/auth.ts:105]: Something like this? This will delete access token if there is less then 1s remaining. 🙂
```ts
if (this.expiresAt < Date.now() + 1000) {
	this.token = null;
}
const response = await this.axios.post('/auth/refresh', payload);


```

**Review by rijkvanzanten — APPROVED** [review]

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
ehh misclicked whoops, haven't gotten around to fully review this yet 😬

**Comment by apstanisic** [comment]
There are also same tests that are failing after last commit, and some merge conflicts. I'll fix it over the weekend. 🙂

**Comment by rijkvanzanten** [comment]
Yeah we'll do a nice little push on the SDK. Excited to clean up the methods a bit too like we discussed ✨

**Comment by apstanisic** [comment]
I've added additional commit that fixes #3574

File: packages/sdk-js/src/handlers/auth.ts (hunk 3 above)
Comment (rijkvanzanten) [reply packages/sdk-js/src/handlers/auth.ts]: No that's OK 👍🏻

File: packages/sdk-js/src/handlers/auth.ts (hunk 4 above)
Comment (rijkvanzanten) [reply packages/sdk-js/src/handlers/auth.ts]: lgtm

**Review by rijkvanzanten — APPROVED** [review]
