### PR TITLE
Fix translations setting primary key and request spamming

### LINKED ISSUE #17762: Translations Interface: Permissions error (parent-id m2o interface)
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When displaying the parent id as a m2o interface inside a translation group and create a new item, the app tries to requests the id from `/items/<collection>/+ `. This trows an error "[FORBIDDEN] You don't have permission to access this."

Not sure if this will already be resolved by https://github.com/directus/directus/pull/16373

### To Reproduce

- Create a collection `parent`
- Add a translation field
-  Go to the translations table
  - Add a text field (or whatever)
  - Select the parent ID and use the many to one interface
- Go to the parent items collection and try to create a new item. Once you start writing in the translations text field the app runs the invalid request

https://user-images.githubusercontent.com/46492597/224321116-6adf5345-a71a-4fae-8d8d-955b72c28e84.mov

If you deselect the many to one interface it works.

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Nitwel**
## Description

This PR solves 2 Problems. The first being that the primary key gets inserted, even when creating a new item. The second bein that we would reload all selected preview data even though the selected items didn't actually change.

Fixes #17762

### CODE REVIEW

**Review by paescuj — APPROVED** [review]
Nice work 👍

File: app/src/composables/use-relation-multiple.ts [hunk 1]
```diff
@@ -440,13 +440,29 @@ export function useRelationMultiple(
...
-				if (!isEqual(newVal, oldVal)) loadSelectedDisplay();
+				if (newVal.length !== oldVal?.length || !isEqual(newVal.map(getRelatedIDs), (oldVal ?? []).map(getRelatedIDs)))
+					loadSelectedDisplay();
 			},
 			{ immediate: true }
 		);
 
 		return { fetchedSelectItems, selected, isItemSelected, selectedOnPage };
 
+		function getRelatedIDs(item: DisplayItem) {
```
Comment (jaads) [inline app/src/composables/use-relation-multiple.ts:451]: should we add the return type to this function? so it would be 
```javascript
function getRelatedIDs(item: DisplayItem) : string | undefined { 
     ...
 }
```
this would make it more clear on how to use the function and it might prevent future bugs

**Review by jaads — CHANGES_REQUESTED** [review]

**Review by jaads — APPROVED** [review]
code looks good and fixes the issue 👍
