### PR TITLE
Fix not ignoring $thumbnail

### LINKED ISSUE #17541: Thumbnails not rendering in collection table
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Moving from discussion: https://github.com/directus/directus/discussions/17494

My collection has a 1:1 relationship to an image, when I add the image thumbnail to the table view of the collection, the image is not shown, and the requests loading the image are missing the asset ID:
image

When switching to card view the image render correctly, which makes me think that this must be a bug in the table view renderer.

Running directus v9.22.3 in a self-hosted node18 environment.

### To Reproduce

1. Create a collection with a 1:1 relationship to an image. 
2. Switch to the Collection view table
3. Add a column for the thumbnail of the image to the table
4. Observe the thumbnail not rendering and failing network requests in the browser's network inspector
5. Switch to card view and observe the images rendering correctly.

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Nitwel**
fixes #17541

grafik

### CODE REVIEW

**Review by paescuj — APPROVED** [review]
LGTM

File: app/src/composables/use-alias-fields.ts [hunk 1]
```diff
@@ -111,6 +111,9 @@ export function useAliasFields(
 	function getFromAliasedItem<K, T extends Record<string, K>>(item: T, key: string): K | undefined {
 		const aliasInfo = Object.values(aliasedFields.value).find((field) => field.key === key);
 
+		// Skip any thumbnail keys as they don't actually exist
+		key = key.replace('.$thumbnail', '');
```
Comment (rijkvanzanten) [inline app/src/composables/use-alias-fields.ts:115]: Can we do it for any key starting with `$` instead? `$thumbnail` is the only one currently, but i'd like it to be as generic as possible

**Review by rijkvanzanten — DISMISSED** [review]

File: app/src/composables/use-alias-fields.ts [hunk 2]
```diff
@@ -111,6 +111,9 @@ export function useAliasFields(
 	function getFromAliasedItem<K, T extends Record<string, K>>(item: T, key: string): K | undefined {
 		const aliasInfo = Object.values(aliasedFields.value).find((field) => field.key === key);
 
+		// Skip any thumbnail keys as they don't actually exist
```
Comment (paescuj) [inline app/src/composables/use-alias-fields.ts:114]: Comment should be updated as well 👍

**Review by DanielBiegler — APPROVED** [review]
