### PR TITLE
Fix comma decimal separator handling for decimal inputs

### LINKED ISSUE #25727: Numeric Input does not accept comma (,) as decimal separator anymore
### Describe the Bug

In previous versions of Directus (or with previous configuration), entering a decimal number using a comma (e.g. 99,99) into a numeric field was automatically converted to 99.99 and stored correctly in Postgres.
Currently, this no longer works — Directus forwards the value "99,99" directly to Postgres, which throws an error:

```bash
update "location_offers" set "price_euro_total" = $1 ...
invalid input syntax for type numeric: "99,99"
```

### To Reproduce

1. Create a collection with a numeric field (type decimal/numeric in Postgres).
2. In the Admin App, enter a decimal value using a comma, e.g. 99,99.
3. Save the record.
4. Error occurs: invalid input syntax for type numeric.

### Directus Version

11.10.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL 15

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Corrected decimal inputs to correctly replace `,` with `.` to ensure it can be saved to the db

## Potential Risks / Drawbacks

- As the change is fairly localized to decimal inputs risk should be minimal

## Tested Scenarios

- Non decimal inputs do not enter the relevant code section
- decimal inputs marked as text replace `,` with `.`

## Review Notes / Questions

- Added an additional test that will fail if we ever add thousandth separator support to our inputs. This should hopefully reduce possibility of a regression.

## Checklist

- [x] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25727

### CODE REVIEW

File: app/src/components/v-input.vue [hunk 1]
```diff
@@ -235,6 +235,15 @@ function emitValue(event: InputEvent) {
 			emit('update:modelValue', parsedNumber);
 		}
 	} else {
+		// decimal input
+		if (props.float === true) {
+			/**
+			 * Normalize decimal separator to '.'
```
Comment (ComfortablyCoding) [inline app/src/components/v-input.vue]:
```suggestion
			 * Normalize decimal separator from ',' to '.'
```

File: app/src/components/v-input.vue [hunk 2]
```diff
@@ -235,6 +235,15 @@ function emitValue(event: InputEvent) {
 			emit('update:modelValue', parsedNumber);
 		}
 	} else {
+		// decimal input
```
Comment (ComfortablyCoding) [inline app/src/components/v-input.vue]:
```suggestion
		// decimal input marked as text
```

**Review by formfcw — APPROVED** [review]
Thank you @ComfortablyCoding 🎉 

LGTM :rocket:
