### PR TITLE
Deprecate utils/package.js in favor of directus/version

### LINKED ISSUE #18795: Versions mix
Not quite fixed. 

On a clean install of `10.2.1`  
- correctly no request for update after `npx directus start`

but
- `10.2.0` is incorrectly shown in the UI
- `npx directus -v` still gives `11.0.1` _(at least on my development computer and on the server)_.

despite `node_modules/directus/package.json` contains
```
{
  "name": "directus",
  "version": "10.2.1",
  ...
  "dependencies": {
    "@directus/api": "11.0.1",
    "@directus/update-check": "11.0.0"
  },
  ...

```
This makes it difficult to automate updates on purpose.

BTW, why `npx directus -v` takes so much time ~10s.?
Wouldn't be much faster (and more accurate) to read the version from `node_modules/directus/package.json`?

_Originally posted by @Pachat in https://github.com/directus/directus/issues/18782#issuecomment-1571599180_

### PR DESCRIPTION
**Pull request by rijkvanzanten**
## Scope

What's changed:

- Resolves a startup error on certain containerized environments
- Resolves version mis-matches in various places (like `npx directus -v` and schema snapshots)

## Potential Risks / Drawbacks

- It's theoretically an `npm` circular dependency, but the way it's exported and imported _shouldn't_ cause any issues[^1]

## Review Notes / Questions

- Needs to be checked in prod builds!

---

Fixes https://github.com/directus/directus/issues/18795

[^1]: famous last words

### CODE REVIEW

File: directus/version.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import { readFileSync } from 'node:fs';
+import { dirname, resolve } from 'node:path';
+import { fileURLToPath } from 'node:url';
+
+const __dirname = dirname(fileURLToPath(import.meta.url));
+
+const pkg = JSON.parse(readFileSync(resolve(__dirname, 'package.json'), 'utf8'));
```
Comment (paescuj) [inline directus/version.js:7]: While we're at it, can we make it async? 🙏
Also no need for `resolve` since `__dirname` is already absolute.

```suggestion
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const pkg = JSON.parse(await readFile(join(__dirname, 'package.json'), 'utf8'));
```

**Review by paescuj — APPROVED** [review]
👍

**Review by nickrum — APPROVED** [review]
