### PR TITLE
App: Fix try load image before it's completely uploaded

### LINKED ISSUE #24086: App: After uploading multiple images, some don't show thumbnail
### Describe the Bug

After uploading multiple images, some do not show thumbnail.
In order for them to appear, either need to navigate to other route and get back or reload the browser.
This happens because the refresh of the layout is being called as soon as some upload completes.
Although at that time, some uploads are still in progress so it's not possible to have the thumbnail.
This is happening at least with Cloudinary storage. Since it envolves network request, uploads are slower than local storage.

Example:

https://github.com/user-attachments/assets/26d654ef-c945-4832-9efb-d953fd8bb63c

### To Reproduce

Set Cloudinary as asset storage
Upload multiple (more than 8) files (more than 800KB)
See some files not having thumbnail

### Directus Version

11.2.2 (main)

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope
When uploading multiple files, thumbnail of some files may not be available.
It looks like this happens because every image upload emits the event "upload" when it completes
The layout refreshes every time it receives this type of event, which means it will try to refresh multiple times.

In order to fix this, we just send the event "upload" once either if is a single file or if is multiple files.

Example
<video src="https://github.com/user-attachments/assets/3034f88f-df7e-42fd-92d5-f01e64dddd46"></video>

What's changed:

- Fix load thumbnails after upload multiple files

## Potential Risks / Drawbacks

- Not sure 🤔

## Review Notes / Questions

- We may want to move more logic into `useFiles` but for now it will be used just for `uploading` flag

---

Fixes #24086

### CODE REVIEW

File: app/src/stores/files.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { defineStore } from 'pinia';
+import { ref } from 'vue';
+
+export const useFilesStore = defineStore('filesStore', () => {
+	const uploading = ref(false);
```
Comment (rijkvanzanten) [inline app/src/stores/files.ts:5]: When we're relying on a global true/false state, it'll mean that different consumers of this store can set it to false even though other processes are still uploading.

Instead, the internal state of the files store should be an array of upload IDs. We can export a `startUpload` function that itself returns the corresponding stop function. That way the upload component(s) can consume it as:

```js
const filesStore = useFilesStore();

const done = filesStore.startUpload();

// Do some async work to upload the file(s)

done();
```

Internally, this store could look something like (pseudo code):

```js
const active = ref([]);
const uploading = computed(() => active.value.length > 0);

const start = () => {
  const id = genId();
  active.value.push(id);

  return () => {
    active.value = active.value.filter((act) => act !== id));
  }
}

return { uploading, start };
```

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Comment by joselcvarela** [comment]
I have updated the logic so each upload has it's own state while the store holds the state of all uploads.
This way the `uploading` flag is now based on the amount of active uploads instead of flag that could be overwritten.

File: app/src/components/v-upload.vue [hunk 2]
```diff
@@ -102,7 +105,7 @@ function useUpload() {
 
 				const uploadedFiles = await uploadFiles(Array.from(files), {
 					onProgressChange: (percentages) => {
-						progress.value = Math.round(
+						newUpload.progress.value = Math.round(
```
Comment (rijkvanzanten) [inline app/src/components/v-upload.vue:108]: Should the progress of the current upload component be shared to the store, or is that something we can just keep locally? 🤔

Comment (joselcvarela) [reply app/src/components/v-upload.vue:108]: On Google Drive, when you upload files, there's a small popup on right bottom corner that shows the status of the upload while you navigate through the app.

While we do not have this yet, I was thinking that all the upload logic could be moved into it's own logic so we can easily access the state for future improvements. Also this should be more consistent and clean.

I also understand that this will store a new number value on memory for each upload (single or multiple files) and I am ok with putting it as before, but in my perspective the memory used this way vs. the legibility and flexibility this gives to us should worth it. 🧐

**Review by connorwinston — APPROVED** [review]
This LGTM! Works as expected and resolves all the extraneus refreshes and cancelled requests.

**Review by rijkvanzanten — APPROVED** [review]
