### PR TITLE
Set system field lengths based on database max limits for columns and tables

### LINKED ISSUE #18530: Field lengths in db too short (64 chars)
### Describe the Bug

Certain fields used by Directus' internal collections are limited to 64 chars, which collides with certain project requirements of ours. Is there a reason for limiting field length?

Whenever we attach a MSSQL database with longer field names to Directus, we receive this error when working with the collection and changes are not saved reliably after that.

image

### To Reproduce

The following fields show the length restriction of 64 characters:
- `directus_fields.collection`
- `directus_fields.field`
- `directus_fields.special`
- `directus_fields.interface`
- `directus_fields.display`
- `directus_fields.group` 

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- Don't hardcode string length for fields referencing columns and table names

## Potential Risks / Drawbacks

- I could have missed some spots that then would fail some time after importing the collection.

## Review Notes / Questions

- This will not fix the issue right away but only for projects bootstrapped after the fix. It would have been possible to write a migration for this as well but due to this being a very edge case scenario, I didn't bother. Instead, the problematic fields size can be updated manually via some DB inspector.

---

Fixes #18530

### CODE REVIEW

File: api/src/database/helpers/schema/dialects/mssql.ts [hunk 1]
```diff
@@ -70,4 +70,12 @@ export class SchemaHelperMSSQL extends SchemaHelper {
 			groupByFields.push(...sortRecords.map(({ column }) => column));
 		}
 	}
+
+	override getColumnMaxLength(): number {
```
Comment (ComfortablyCoding) [inline api/src/database/helpers/schema/dialects/mssql.ts:74]:
```suggestion
	override getColumnNameMaxLength(): number {
```

File: api/src/database/helpers/schema/types.ts [hunk 2]
```diff
@@ -188,4 +188,12 @@ export abstract class SchemaHelper extends DatabaseHelper {
 	): void {
 		// no-op by default
 	}
+
+	getColumnMaxLength() {
+		return 64;
```
[the remark this answers is not in the document]
Comment (ComfortablyCoding) [reply api/src/database/helpers/schema/types.ts:193]: We are restricting in the sense that if for example `postgres` supports `128` we are still limiting it to `64` for no apparent reason. Ideally we set the max length to what is supported by the respective db

[the remark this answers is not in the document]
Comment (Nitwel) [reply api/src/database/helpers/schema/types.ts:193]: So for PG and Cockroach there is a defined limit of 63 if I remember, mysql and oracle have a limit of 128 like defined. The odd one out is SQLite which doesn't really have any limits at all so I'd say we default to 64 to keep it inline which what it was before.

File: api/src/database/migrations/20210510A-restructure-relations.ts [hunk 3]
```diff
@@ -12,7 +12,7 @@ export async function up(knex: Knex): Promise<void> {
 	await knex('directus_relations').update({ one_deselect_action: 'nullify' });
 
 	await helper.changeToType('directus_relations', 'sort_field', 'string', {
-		length: 64,
+		length: helper.getColumnNameMaxLength(),
```
Comment (ComfortablyCoding) [inline api/src/database/migrations/20210510A-restructure-relations.ts:15]: In the name of consistency should we use `helper.schema. getColumnNameMaxLength` and update usage accordingly?

File: .changeset/gentle-horses-add.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fixed string length too short to store db column/table names
```
Comment (ComfortablyCoding) [inline .changeset/gentle-horses-add.md:5]: What do we think of the following? 
```suggestion
Fixed issue where column/table names didn't follow the database's maximum allowed length limit, applied to new projects only
```

Comment (licitdev) [reply .changeset/gentle-horses-add.md:5]: Another suggestion:
```suggestion
Set system field lengths based on database max limits for columns and tables (new installs only)
```

File: api/src/database/migrations/20210510A-restructure-relations.ts (hunk 3 above)
Comment (ComfortablyCoding) [reply api/src/database/migrations/20210510A-restructure-relations.ts]: Resolved in 3c90df309ef0013c85375db421230ad84187be09

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀 

#### Tests
- [x] Expect bootstrap to complete successfully on all supported db ([with exception of crdb v25](https://github.com/directus/directus/issues/25001))
- [x] Expect imported dbs within the db allowed limit to now be imported/configurable
- [x] Expect the changes not to effect old projects
