### PR TITLE
Pause "Auto Refresh" when page is idle

### LINKED ISSUE #17083: Token expire when using "Auto Refresh"-Feature in a background tab [ /auth/refresh is missing]
### Describe the Bug

I updated directus from v9.11.1 to v9.22.1. Then I noticed a bunch of "Token Expired" sometimes in my console. 

After reading https://github.com/directus/directus/issues/16188 and some testing I realized it only happens when an "Auto Refresh" from the sidebar is running in a background tab. In that case there won't be triggered an "/auth/refresh".

When the browser tab with directus is open/active it works as expected.

### To Reproduce

1. Set your ACCESS_TOKEN_TTL to "1m" (for faster reproduction)
2. Set your LOG_LEVEL to "debug"
3. Choose a Collection
4. Set up "Auto Refresh" in the sidebar for 30sec
5. Switch to a new Browser Tab (directus in background tab)

The first refresh after 30sec should work. All other refreshes after 1m should fail and show a "Token expired.".

6. Switch to the directus browser tab again

An /auth/refresh will be triggered and all "Auto Refreshes" will work again

### Errors Shown

_Disclaimer: I cleaned the file paths to only show the part after node_modules folder._

**DEBUG: Token expired.**
```
    err: {
      "type": "TokenExpiredException",
      "message": "Token expired.",
      "stack":
          Error: Token expired.
              at verifyAccessJWT (CLEANED\directus\dist\utils\jwt.js:38:19)
              at handler CLEANED\directus\dist\middleware\authenticate.js:44:55)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 401,
      "code": "TOKEN_EXPIRED",
      "extensions": {}
    }
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 13

### What browser are you using?

Vivaldi (Chromium)

### How are you deploying Directus?

locally, render.com

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

Pause the "Auto Refresh" functionality if the page is idle (not focused / no interaction for 5min), to avoid unnecessary requests as well a requests with expired token.

## Potential Risks / Drawbacks

None

## Review Notes / Questions

- Relevant commits by @br41nslug extracted from #17341
- Thanks to @jay-p-b-7span for initial work in #17341

---

Fixes #17083

### CODE REVIEW

File: app/src/views/private/components/refresh-sidebar-detail.vue [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
-import { computed, ref, watch } from 'vue';
 
 const props = defineProps<{
 	modelValue: number | null;
 }>();
 
 const emit = defineEmits<{
-	(e: 'update:modelValue', value: number | null): void;
-	(e: 'refresh'): void;
+	'update:modelValue': [value: number | null];
```
Comment (rijkvanzanten) [inline app/src/views/private/components/refresh-sidebar-detail.vue:11]: If we wanna make this even nicer, we could use a

```ts
const value = defineModel();
```

and use that instead of the modelValue prop w/ emit 🙂

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/views/private/components/refresh-sidebar-detail.vue (hunk 1 above)
Comment (paescuj) [reply app/src/views/private/components/refresh-sidebar-detail.vue]: Good idea 🚀
