### PR TITLE
Allow to pass type to `useItem` & fix `User` type

### LINKED ISSUE #19303: When a user is not assigned any roles, the backend will display a blank page.
### Describe the Bug

When the user has no role assigned, selecting to open that user's page in the backend will result in a blank screen.

image
image

### To Reproduce

To reproduce the issue, you can create a new user in the backend without assigning any role. 

### Directus Version

10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
- More accurate types would have prevented this regression introduced in #19257 in the first place, therefore this PR intends to improve accuracy by enabling to pass types to `useItem`
- Type of `User` was pretty outdated

Account for users with no role associated, fixes #19303

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/composables/use-item.ts [hunk 1]
```diff
@@ -37,11 +37,11 @@ type UsableItem = {
...
 
-export function useItem(
+export function useItem<T extends Record<string, any>>(
 	collection: Ref<string>,
 	primaryKey: Ref<string | number | null>,
 	query: Ref<Query> | Query = {}
-): UsableItem {
+): UsableItem<T> {
 	const { info: collectionInfo, primaryKeyField } = useCollection(collection);
 	const item = ref<Record<string, any> | null>(null);
```
Comment (br41nslug) [inline app/src/composables/use-item.ts:46]: To fix the issue marked todo
> // TODO Find way to fix warning:
> // 'T' could be instantiated with a different subtype of constraint 'Record<string, any>'

```suggestion
	const item: Ref<T | null> = ref(null);
```

Comment (paescuj) [reply app/src/composables/use-item.ts]: Thanks! I think I've tried this as well but noticed that it moves the issue further down:


I've now added an assertion which should be fine in this case 👍 
https://github.com/directus/directus/blob/ed859ef8e8529bd7b0c56cf2deaf9f741332b538/app/src/composables/use-item.ts#L400

**Review by br41nslug — APPROVED** [review]
