### PR TITLE
Fix O2M edits on unsaved items

### LINKED ISSUE #13537: When updating an entry in O2M, the original value doesn't get edited before saving
### Describe the Bug

We have a O2M relationship, displaying multiple answers in a given collection.
When we edit an answer, the entity doesn't get updated and stays the same, even after re-opening it.
This only gets fixed once everything is saved.

https://user-images.githubusercontent.com/9347206/170220959-3aaac913-d557-4263-9282-3c489ba60b13.mov

 I created a reproducible sample:
[data.db.zip](https://github.com/directus/directus/files/8769415/data.db.zip)
admin@example.com / password

I think it might be related to this issue: https://github.com/directus/directus/issues/13456#issuecomment-1135544593

### To Reproduce

1. Create a O2M relation
2. Edit a field on the many-side
3. The field doesn't get updated on the O-side, only once saved

### Errors Shown

_No response_

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2 / SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### LINKED ISSUE #15120: When updating an entry in O2M, only the modified values are shown before saving
### Describe the Bug

In an item with an O2M field, we normally see the related items with the chosen fields.
If we modify one (or more) fields of the related item and click on Save, before saving the parent item,
among the chosen fields. we only see the modified fields.

_May have some connections with #13537 which is different_

### To Reproduce

1. Parent collection with O2M to Child collection with 2 or more fields.
2. Choose 2 or more fields of the Child collection that are to be seen on the Parent item
3. Add some Child items to the Parent item. Save the Parent item.
4. Open the Parent item, click on one of the Child item
5. Modify one or more, but not all the fields that are going to be seen on the Parent item. Save the Child item<br/><br/> => **Only the modified fields are visible** <=<br/><br/>
7. Save the Parent item
8. Reopen; the modifications of the Child item appear now as expected within all the fields that  are seen on the Parent item

### Errors Shown

At stage 5, not all the expected fields that are to be seen on the Parent item do appear: only the modified one(s)

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

### LINKED ISSUE #15198: M2O field looses all field values before save
### Describe the Bug

I have a contacts and an addresses collections. Addresses has a M2O relationship with contacts and its M2O field is contact. I added the O2M field to contacts as addresses.
when we create a contact we can create or add an existing address to it. when you tap create, and you fill in the field values and you press the blue checkmark, the popup dialog fades out  and a record sits in the M2O interface. when you click it again to check the field values before saving, every field is empty again!

I have this issue on a docker instance as well as a local test installation on macOS

**Preview**:
https://user-images.githubusercontent.com/55084508/185806565-4f2ccdc6-7859-45ec-b7f5-b3461bc05ec9.mp4

### To Reproduce

i've attached the sql dump of my mysql database.
[wpcore9_16_1bugs.sql.zip](https://github.com/directus/directus/files/9389768/wpcore9_16_1bugs.sql.zip)

- create a contacts collection with all sort, created etc fields
- create a second addresses collection
- from the addresses collection add an M2O field, call it contact and check add an O2M field to contacts as addresses.

### Errors Shown

_No response_

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

v16.15.1

### What database are you using?

mysql

### What browser are you using?

Server version: 10.3.32-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04

### How are you deploying Directus?

locally on macOS

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

For issue #15198, it is an unintended regression by #13998 as it is causing unsaved-edited-items to be "cleared", since the PR was removing any other fields except the primary key. Quote from said PR:

> In fact, we just need to pass the key value of this item as the editsAtStart as when the drawer pops up, the value will be fetched from backend. So the fix is also simple, just remove all unrelated fields from the displayItem except the key field.

With the assumption of value being fetched from backend, it is not accounting for unsaved-items that will not trigger the fetch (as it's not created yet).

This PR reverts #13998 changes in `editItem()`, and implements a replacement fix by doing it in `stageEdits()` instead, so the removal of fields without edit permissions happens _after_ closing the drawer, not when opening it.

However if we are just fixing #15198, we will see values used in the interface's display (`description` in the following video) gets removed after getting updated:

https://user-images.githubusercontent.com/42867097/186159566-3b067cc2-6081-404f-bc11-a9506515df6d.mp4

This turns out to be an oversight in #13574, as it is not accounting for additional values used for interface display, not just for the item itself.

This PR reverts #13574, but replaces it with `mergeWith()` instead and uses the customizer to ignore `typeof 'object'`, which includes objects ([to prevent this object merging issue](https://github.com/directus/directus/pull/13574#discussion_r882965813)) and arrays (repeaters, json field, or nested relational interfaces).

Fixes #15198
Fixes #15120
Fixes #13537

### Result

https://user-images.githubusercontent.com/42867097/186160763-1373d891-b069-4bc2-acf8-b9356badec52.mp4

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: app/src/interfaces/list-o2m/list-o2m.vue [hunk 1]
```diff
@@ -423,7 +423,13 @@ function stageEdits(item: Record<string, any>) {
 	if (newItem) {
 		create(item);
 	} else {
-		update(item);
+		const updatePermission = permissionsStore.getPermissionsForUser(relatedCollection.value, 'update');
+		// prevent update payload containing fields that are included for displays, but without edit permission
+		const itemToUpdate =
+			updatePermission?.fields && !updatePermission.fields.includes('*')
+				? pick(item, [...updatePermission.fields, '$index', '$type', '$edits'])
```
Comment (azrikahar) [inline app/src/interfaces/list-o2m/list-o2m.vue:430]: Not sure if there's a better way of handling this, or maybe something like a reduce and check for keys starting with `$`.

File: app/src/composables/use-relation-multiple.ts [hunk 2]
```diff
@@ -102,16 +102,18 @@ export function useRelationMultiple(
...
 			if (editsIndex !== -1) {
-				merge(
+				mergeWith(
 					updatedItem,
 					{ $type: 'updated', $index: editsIndex, $edits: editsIndex },
-					_value.value.update[editsIndex]
+					_value.value.update[editsIndex],
+					(_objValue, srcValue) => {
+						// skip the default merge behavior for objects/arrays
+						if (typeof srcValue === 'object') return srcValue;
```
Comment (azrikahar) [inline app/src/composables/use-relation-multiple.ts:114]: Perhaps this should be something like lodash's `isObjectLike` to safer and avoid false positives on null values?

**Comment by u12206050** [comment]
Hei @azrikahar I made a PR yesterday that I believe fixes this issue as well.
#15245

**Comment by azrikahar** [comment]
> Hei @azrikahar I made a PR yesterday that I believe fixes this issue as well. #15245

I'm seeing your PR fixing list-m2m, but this should be for list-o2m right? 🤔 On a related note, I believe your PR may also need to align with the changes from #15220.

**Comment by u12206050** [comment]
Ah you are right, I almost forgot that there were two different interfaces. I can point out though, that what you found is also what I found, in terms of the editsAtStart needing to contain the id of the object, although what i also found is that as soon as the drawer is closed, the changes are immediately staged for saving, making it hard to get a hold of. I will at 15220

File: app/src/composables/use-relation-multiple.ts (hunk 2 above)
Comment (rijkvanzanten) [reply app/src/composables/use-relation-multiple.ts:114]: Yeah good one. Effectively everything in JavaScript is an "object", so you might get a lot of false positives with a `typeof` check 

CleanShot 2022-08-30 at 14 45 20@2x

File: app/src/interfaces/list-o2m/list-o2m.vue (hunk 1 above)
Comment (rijkvanzanten) [reply app/src/interfaces/list-o2m/list-o2m.vue:467]: Good idea. Lets make this a hair more generic by checking for all keys starting with `$` rather than an arbitrary hardcoded list 👍🏻

File: app/src/composables/use-relation-multiple.ts (hunk 2 above)
Comment (azrikahar) [reply app/src/composables/use-relation-multiple.ts:114]: Although I believe the listed "false positives" will still pass `isObjectLike` (since the goal was to deny `null` from passing):

> Checks if value is object-like. A value is object-like if it's not null and has a typeof result of "object"

I think these "false positive" should technically still be correct since Date/Map/Set etc wouldn't do the magical object-append/array-concat, or even if they do, we'd want them to override as well right?

**Comment by azrikahar** [comment]
opted to remove the list-o2m change in favor of #15336 which resolves the "passing all values including displayValues as edits" behavior in all relational interfaces 👍

So this PR will only focus on the lodash merge behavior causing unintended side effects to edits on unsaved items.

**Comment by Nitwel** [comment]
> opted to remove the list-o2m change in favor of #15336 which resolves the "passing all values including displayValues as edits" behavior in all relational interfaces 👍
> 
> So this PR will only focus on the lodash merge behavior causing unintended side effects to edits on unsaved items.

Damn, crazy how fast you figured out that my PR already fixed that by mistake!❤️

File: app/src/composables/use-relation-multiple.ts [hunk 3]
```diff
@@ -102,17 +102,18 @@ export function useRelationMultiple(
...
-				merge(
+				mergeWith(
 					updatedItem,
-					cloneDeep(item),
 					{ $type: 'updated', $index: editsIndex, $edits: editsIndex },
-					_value.value.update[editsIndex]
+					_value.value.update[editsIndex],
+					(_objValue, srcValue) => {
+						// skip the default merge behavior for objects/arrays
+						if (isObjectLike(srcValue)) return srcValue;
```
Comment (Nitwel) [inline app/src/composables/use-relation-multiple.ts:114]:
```suggestion
						if (Array.isArray(srcValue)) return srcValue;
```
If we don't merge objects the "lodash" way, we run into the issue that when you edit a field in a m2m and then revert the changes, the display value will disappear as it wont be merged.

https://user-images.githubusercontent.com/22577866/187885683-044ce707-45e0-424c-b977-4a60451c4685.mp4

**Review by Nitwel — CHANGES_REQUESTED** [review]

File: app/src/composables/use-relation-multiple.ts (hunk 3 above)
Comment (azrikahar) [reply app/src/composables/use-relation-multiple.ts:114]: Ah... that is very true. This does feels like a catch-22 now, as the reasoning to not merge objects the "lodash" way was to fix cases such as this where it'll visually appear the "lodash" way, but the raw value isn't:

https://user-images.githubusercontent.com/42867097/187914816-82ceef6b-e29f-45ba-92b1-cb4b7383cf01.mp4

However I do agree that this is probably the edge case between the two, so perhaps we can move forward with only skipping arrays for now and try to find a fix for this elsewhere?

Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts:114]: Hmm, didn't think of that one. I guess the right fix would be to lodash merge the top level and the field with nested object values inside it and the rest should be just replaced. 🤔

Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts:114]: Something like this could maybe fix both situations.
```js
updatedItem = {...cloneDeep(item), $type: 'updated', $index: editsIndex, $edits: editsIndex, ..._value.value.update[editsIndex]}

if(isM2M || isM2A) {
  updatedItem = {...updatedItem, [junctionField]: {...updatedItem, ..._value.value.update[editsIndex][junctionField] }}
}
```

Comment (azrikahar) [reply app/src/composables/use-relation-multiple.ts:114]: I tried giving a stab at that, but it seems like arrays are still not playing nicely 🤔 but it could be an issue with my implementation. Here's what I attempted based on your suggestion:

```js
			let updatedItem: Record<string, any> = cloneDeep(item);

			if (editsIndex !== -1) {
				updatedItem = {
					...updatedItem,
					$type: 'updated',
					$index: editsIndex,
					$edits: editsIndex,
					..._value.value.update[editsIndex],
				};

				if (relation.value?.type === 'm2m' || relation.value?.type === 'm2a') {
					updatedItem = {
						...updatedItem,
						[relation.value.junctionField.field]: {
							..._value.value.update[editsIndex][relation.value.junctionField.field],
						},
					};
				}
			}
```

Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts]: I played a bit around with it and I think I have both problems solved though I don't know why the code you wrote doesn't work and mine which is really similar does. Feel free to play around with my solution as im not 100% confident at the moment that I fixed everything and will test that tomorrow a bit more.

Comment (azrikahar) [reply app/src/composables/use-relation-multiple.ts]: Thanks! Interestingly I also can't see a big difference aside from the update within isM2M and isM2A, but your current solution definitely works to resolve all the cases now ❤

Tested M2M display (as you pointed out in this comment thread), json editing and repeater deletions (which was pointed out in the comment thread here: https://github.com/directus/directus/pull/13574#discussion_r882708057):

https://user-images.githubusercontent.com/42867097/188048726-f0a8e496-5dd2-475c-8e24-65894a71e419.mp4

**Comment by appilux** [comment]
any idea when this PR is going to be merged to the main branch?

**Review by Nitwel — APPROVED** [review]

**Review by br41nslug — APPROVED** [review]
looks good to me 😄
