### PR TITLE
Optimize extension auto-reloading

### LINKED ISSUE #20380: Extension auto-reload not work for new way of creating extensions
### Describe the Bug

> the old way:
./extensions/\<extension-type>/\<extension-name>/index.js
or the new way
./extensions/directus-extension-\<extension-name>/package.json

Setting `EXTENSIONS_AUTO_RELOAD: true`  works for the old way of creating extension, but not work for the new way. See Reproduce Steps.

### To Reproduce

```yml
version: "3"
services:
  directus:
    image: directus/directus:10.7.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      EXTENSIONS_AUTO_RELOAD: true
```
```bash
docker compose up
# error for permission reasons. folders auto created.
sudo chown -R marv:marv database extensions uploads
cd extensions 
npx create-directus-extension@latest
cd directus-extension-test
npm run dev

# open another terminal
docker compose up
# change extension code and save, no effect in the console

# open another terminal
mkdir extensions/hooks/test1
vi extensions/hooks/test1/index.js
# save. then in directus log shows 'Reloading extensions'. both two hooks' changes are shown
```

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #20440: Multiple "Reloading extensions" get executed in sequence
### Describe the Bug

While directus server is running, whenever we do a batch `pnpm -r build` of our extensions, we notice in the console that Directus is "Reloading extensions" again and again and again * 22, which is one per extension is seems.

It does this in sequence and the server doesn't work correctly until it is finished.

Looking at the code in `api/src/extensions.ts` I notice in the `reload()` function that it is simply being enqueued onto a job stack.

## Solution

Debounce the reloading of extensions. The `chokidar.watch` being used seems to trigger the reload function multiple times per second as the files in `extensions` folder is being updated. So debounce and only execute a reload once every 1s, once in the start of the second and once in the end (if another reload has been called)

### To Reproduce

Build a lot of custom extensions in parallel whilst auto reload extensions is true.

### Directus Version

10.6

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

What's changed:

- Watch local package extensions (#20380)

- Debounce watcher events
  - Prevents consecutive reloads when rebuilding bundle or hybrid extensions, which results in two `change` events about the same time (for `api.js` and `app.js` files)
  - Prevents consecutive reloads when building a bundle or hybrid extensions for the first time (`add` event)
  - Reduces consecutive reloads when rebuilding multiple extensions at the same time, like in #20440
  - Prevents error message about missing `dist` files during removal of an extension (thus the `2s` delay for `delete` events)
  - The `750ms` delay for `change` seems good enough to catch most cases and at the same time still lead to what feels like an almost instant reload

     https://github.com/directus/directus/assets/5363448/f48a7dc3-3127-4dfe-a73d-74378e41db3b
  - See also https://github.com/directus/directus/pull/20849#issuecomment-1895636360 for additional insights
- Respect the `PACKAGE_FILE_LOCATION` config option for watching the root `package.json` file
- Introduced fixes for `chokidar` watching unwanted files

## Potential Risks / Drawbacks

Tiny delays, but this should be made up for by the prevented reloads

## Review Notes / Questions

Tested with extension installed as dependency as well as direct and linked (`npm run link`) package extensions in `extensions` folder on
✅ macOS
✅ Linux (Ubuntu)
✅ Windows
✅ Docker (macOS)

- You may want to log `this.watcher.getWatched()` after updates to see the list of currently watched files
- You may want to log `this.reloadQueue.size` to see if and when it takes effect
- Over the long-term, I'd like to move away from `chokidar` to get rid of the applied workarounds. Vite and others are considering migration to [parcel/watcher](https://github.com/parcel-bundler/watcher), but it's currently lacking a few features... 

---

Fixes #20380
Fixes #20440
In addition to #20849

### CODE REVIEW

File: api/src/extensions/manager.ts [hunk 1]
```diff
@@ -307,10 +308,10 @@ export class ExtensionManager {
 
 		logger.info('Watching extensions for changes...');
 
-		const extensionDirUrl = pathToRelativeUrl(getExtensionsPath());
+		const extensionsDir = path.posix.resolve(getExtensionsPath());
```
Comment (br41nslug) [inline api/src/extensions/manager.ts:311]: Do we need `path.posix.resolve` here? This function is known to have some footguns resulting in non-posix compliant paths on Windows in certain situations (for example `path.posix.resolve(process.cwd(), 'foo') -> '/Users/Brainslug/C:\\Users\\Brainslug/foo'`)

File: api/src/extensions/manager.ts [hunk 2]
```diff
@@ -307,10 +308,10 @@ export class ExtensionManager {
...
 
-		const localExtensionUrls = NESTED_EXTENSION_TYPES.flatMap((type) => {
-			const typeDir = path.posix.join(extensionDirUrl, pluralize(type));
+		const nestedExtensions = NESTED_EXTENSION_TYPES.flatMap((type) => {
+			const typeDir = path.posix.join(extensionsDir, pluralize(type));
```
Comment (br41nslug) [inline api/src/extensions/manager.ts:314]: This line is creating invalid paths resulting in legacy extension folders not being watched consistently on Windows.

image

**Review by br41nslug — COMMENTED** [review]
Loving the fixes 🚀😄 However the Windows path issues do worry me 😬

**Comment by br41nslug** [comment]
I know we are not currently doing this anyway but should we include the 2 forgotten children of extensions in the auto-reloading? Migrations and Email Templates, specifically the email templates could be very valuable to have auto reloaded while working on them.

File: api/src/extensions/manager.ts (hunk 2 above)
Comment (paescuj) [reply api/src/extensions/manager.ts:314]: <sub>Also in response to https://github.com/directus/directus/pull/21111/files#r1455398161</sub>

I've tested it on all platforms, including Windows.
It works on my end, the legacy extensions are watched too.
The paths are passed to `chokidar` in which they are correctly interpreted.

I went with `path.posix` on line 311 to be in accordance with `path.posix` on line 313 which was already there before. 
I'm not sure about the original reason for using `path.posix`, an assumption could be that there were concerns about globs with Windows-path-style.
I didn't want to change that as part of this PR, because as mentioned I don't know about the reason and it worked fine in my tests.

However, happy to update this if we can get some more clarity 👍

File: api/src/extensions/manager.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply api/src/extensions/manager.ts:311]: The usage of posix (213 and 236) could be causing the issue in https://github.com/directus/directus/issues/18721. We should check if this is resolved once paths are made OS agnostic.

File: api/src/extensions/manager.ts [hunk 3]
```diff
@@ -322,17 +323,30 @@ export class ExtensionManager {
...
+				debounce(() => this.reload(), 500),
+			)
+			.on(
+				'change',
+				debounce(() => this.reload(), 650),
+			)
+			.on(
+				'unlink',
+				debounce(() => this.reload(), 2000),
+			);
```
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/extensions/manager.ts:349]: I'd rather not make this configurable. I don't see a real reason for this.
The debouncing is intended as an optimization, with values that will cover most cases.
However, we can never cover all cases (for example edge-cases like in #20440).
Even if we make it configurable, it doesn't really make sense to set the values higher, because then it takes too long for single file changes.
On the other side, IMO the values are small enough not to impair everyday use.

File: api/src/extensions/manager.ts (hunk 1 above)
Comment (paescuj) [reply api/src/extensions/manager.ts:311]: Nope, that's https://github.com/paulmillr/chokidar/issues/1051

Comment (ComfortablyCoding) [reply api/src/extensions/manager.ts:311]: It might not be as that one reports it as a macOS issue while #18721 reports that it works on macOS/linux but not windows.

Comment (paescuj) [reply api/src/extensions/manager.ts:311]: Hmm, I cannot imagine how that could affect the Docker container, as the OS will always be Linux.

But as outlined in https://github.com/directus/directus/pull/21111#discussion_r1455898895, happy to switch to OS agnostic `path.resolve`.
@nickrum Do you remember the reason for using `path.posix`?

File: api/src/extensions/manager.ts (hunk 2 above)
Comment (nickrum) [reply api/src/extensions/manager.ts:314]: The chokidar docs specifically mention that "globs must not contain windows separators (\), because that's how they work by the standard". That's why on line 311 `pathToRelativeUrl` was used, which converts any path to a relative URL (making it a relative path first ensures that we do not have to deal with windows vs posix root specifiers). So, even if it might works, maybe we should keep it that way to adhere to the standard 🤔

File: api/src/extensions/manager.ts (hunk 1 above)
Comment (nickrum) [reply api/src/extensions/manager.ts:311]: Yup, I just answered [here](https://github.com/directus/directus/pull/21111#discussion_r1456064371) before I saw your comment 😅

File: api/src/extensions/manager.ts (hunk 2 above)
Comment (paescuj) [reply api/src/extensions/manager.ts:314]: Thank you @nickrum ❤️ 🙏 

The thing is that I need the absolute path to be able to apply https://github.com/directus/directus/pull/21111/files#diff-09fef1df59269b49b62b7e749e695089e0e51baa3f666521c50a48a58a7820f6R332

So in that case, could we use the following?
```js
const extensionsDir = pathToRelativeUrl(path.resolve(getExtensionsPath()));
```

Comment (paescuj) [reply api/src/extensions/manager.ts]: Alright! `pathToRelativeUrl` obviously won't work for absolute paths, so I gave it a try and removed all usages of `posix`. Turns out that works perfectly fine 👍🥳 
I think that is either because Node.js' `path` API already escapes the paths correctly or because `chokidar`'s statement is simply outdated.

The generated paths:

 
Excerpt of chokidar's watched paths:


Thanks @br41nslug thanks for checking on that, and thanks again @nickrum for the info! 🚀

Comment (nickrum) [reply api/src/extensions/manager.ts]: > The thing is that I need the absolute path to be able to apply https://github.com/directus/directus/pull/21111/files#diff-09fef1df59269b49b62b7e749e695089e0e51baa3f666521c50a48a58a7820f6R332

Do we actually need absolute paths for this to work, though? Couldn't this also be converted to a relative URL? Wouldn't that make sense given it is a glob pattern as well? I'm a little bit worried using something which is explicitly advised against. It might only work by chance and could break in a future minor/patch update 🤔

Comment (paescuj) [reply api/src/extensions/manager.ts]: Two things before I spend more time on this:
1. `chokidar` is more or less in unmaintained state, so I doubt there will be updates which break that behavior (or updates at all)
2. Over the long-term, I'd like to move away from `chokidar` anyway (see OP) because of 1) and the quirks it comes with

Comment (nickrum) [reply api/src/extensions/manager.ts]: Ah, I didn't even know that. Are there any good alternatives?

I really don't want to make your live any harder 🫣 So, if it works and as long as we keep in mind that this could break once we move away from chokidar, I'd be fine with it.

Comment (paescuj) [reply api/src/extensions/manager.ts]: > Ah, I didn't even know that. Are there any good alternatives?

Unfortunately, not really as of now 😢 There's [`parcel/watcher`](https://github.com/parcel-bundler/watcher) which looks promising but it's missing a high-level API, similar to `fs.watch`. I think https://github.com/vitejs/vite/issues/13593#issuecomment-1776906216 sums it up pretty well, for our needs too.

> I really don't want to make your live any harder 🫣

All good! ❤️ I just wanted to have that mentioned as basis for further discussion. I didn't mean to say that we can't make any further adjustments.

> So, if it works and as long as we keep in mind that this could break once we move away from chokidar, I'd be fine with it.

Yeah, that's what I'm also leaning towards at the moment.

File: .changeset/witty-cobras-add.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Optimized extension auto-reload behaviour and added auto-reload support for local package extensions
```
Comment (ComfortablyCoding) [inline .changeset/witty-cobras-add.md:5]:
```suggestion
Optimized extension auto-reload behaviour and fixed auto-reload for local package extensions
```

**Review by ComfortablyCoding — COMMENTED** [review]
LGTM!

Waiting on confirmation from @br41nslug that all is well on a windows native machine before approving.

**Comment by ComfortablyCoding** [comment]
Two DX non blocking notes
- We should add some sort of log for the code change case. ATM it shows "Reloading extensions" with nothing to indicate that the reload was completed. Video attached
- When testing it was strange when I did not see the reload message after a change was made. It made me think the watcher was not working. Potentially adding the message mentioned above might resolve this. 

https://github.com/directus/directus/assets/44623501/56b342e4-7e24-474e-a19c-34400979fc86

File: api/src/extensions/manager.ts (hunk 2 above)
Comment (br41nslug) [reply api/src/extensions/manager.ts]: Seems to work fine, in my tests today 🤔 not sure if due to the changes or due to flawed testing in my original review.

**Review by br41nslug — APPROVED** [review]
While theoretically possible to lose the last extension update done (if done within the 500ms debounce of the last update) that is quite fast and definitely an edge case 😄
