### PR TITLE
Ensure that M2M fields in the directus_files collection use the correct interface

### LINKED ISSUE #25462: Interface "list-m2m" not found.
### Describe the Bug

When I add a new many-to-many property and set the interface to "Select Many to Many", I can no longer modify it afterward. Even if I just created it, when I go back into the field configuration, the following error appears:

> Interface "list-m2m" not found.

Additionally, if I click the "Reset" button, it restores the interface to "File Upload" instead of reverting to the correct "Select Many to Many" interface.

I found this open issue https://github.com/directus/directus/issues/25438, could be related?

## Selection
Image

## Error when re-open the field configuration
Image

## After reset interface
Image

### To Reproduce

- settings
- data model
- choose any model and create a many to many field in advanced mode
- set a relationship
- set the interface "Many to Many"
- save
- open the field configuration again
- go to the interface panel
- the error will appear

### Directus Version

11.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by robluton**
## Scope

What's changed:
Changed condition in get-local-types to ensure files interface is used for relationships pointing at the directus_files collection.

## Potential Risks / Drawbacks

- None that I can think of

## Tested Scenarios

- Verified m2m and files interfaces work correctly with the directus_files collection.

## Checklist

- [x ] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25462

### CODE REVIEW

File: app/src/utils/get-local-type.ts [hunk 1]
```diff
@@ -46,12 +46,7 @@ export function getLocalTypeForField(collection: string, field: string): LocalTy
 			return 'm2o';
 		}
 
-		if (
-			relations[0]!.related_collection === 'directus_files' ||
-			relations[1]!.related_collection === 'directus_files'
-		) {
-			return 'files';
-		} else {
+		if ((fieldInfo.meta?.special || []).includes('m2m')) {
```
Comment (formfcw) [inline app/src/utils/get-local-type.ts]: We can fix this issue without removing the existing behavior by checking if the root collection is `directus_files` in the condition.

```suggestion
		const directusFilesRelationsCount = relations.filter((relation) => relation.related_collection === 'directus_files').length;

		const isRelationToDirectusFiles = collection !== 'directus_files' && directusFilesRelationsCount === 1;
		const isSelfRelationToDirectusFiles = directusFilesRelationsCount === 2;

		if (isRelationToDirectusFiles || isSelfRelationToDirectusFiles) {
			return 'files';
		} else {
			return 'm2m';
		}
```

Note that I have not tested the example above. Explanation:
We have 2 related collections.
If both related collections are `directus_files`, then we want to return `files` (`isSelfRelationToDirectusFiles`).
If only one related collection is `directus_files`, then we only want to return `files` if the root collection is not `directus_files` (`isRelationToDirectusFiles`).

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you @robluton!

Let’s take a different approach that won't remove existing behavior — see the code comment.

File: .changeset/purple-animals-grab.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/app': patch
+---
+
+Removed condition forcing m2m fields related to directus_files to use files interface
```
Comment (formfcw) [inline .changeset/purple-animals-grab.md]: Let’s update the changeset, since we didn’t remove this functionality.

```suggestion
Ensured that M2M fields in the directus_files collection use the correct interface
```

**Review by formfcw — CHANGES_REQUESTED** [review]
Please update the changeset and the PR description for future reference to something like … Ensured that M2M fields in the directus_files collection use the M2M instead of the Files interface when relating to a collection other than directus_files

**Review by formfcw — APPROVED** [review]
Thank you @robluton :heart:
LGTM :rocket:
