### PR TITLE
Fix stacked drawers layering

### LINKED ISSUE #10892: Drawers open behind modals
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Items drawer appears behind the v-modal in upload dialog.

### To Reproduce

Create text field with markdown interface, allow image tool. With the new field add image and pick "Choose from library"

https://user-images.githubusercontent.com/1009639/148432167-c1ba97b2-6f8f-4cd1-98cb-86b6a94b2993.mov

### Errors Shown

_No response_

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16

### What database are you using?

mysql5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS Big sur

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by licitdev**
Closes #10892.

https://user-images.githubusercontent.com/26413686/154048780-6f3d9e3c-7b4b-418c-8c07-e0215c6d916d.mov

Implements the use of a different tag for dialogs and drawers as suggested in https://github.com/directus/directus/issues/10892#issuecomment-1011163395.

Note: `<span>` is used for dialogs as it breaks layering in `v-menu` if used for drawers.

### CODE REVIEW

File: app/src/components/v-dialog/v-dialog.vue [hunk 1]
```diff
@@ -2,21 +2,17 @@
 	<div class="v-dialog">
 		<slot name="activator" v-bind="{ on: () => (internalActive = true) }" />
 
-		<teleport v-if="placement === 'right'" to="#drawer-outlet">
+		<teleport to="#dialog-outlet">
 			<transition-dialog @after-leave="leave">
-				<div v-if="internalActive" class="container" :class="[className, placement]">
+				<component
+					:is="placement === 'right' ? 'div' : 'span'"
```
Comment (rijkvanzanten) [inline app/src/components/v-dialog/v-dialog.vue:8]: Smart! Using a different tag so that the `:nth-of-type` trick in CSS still works ❤️

**Review by rijkvanzanten — APPROVED** [review]
