### PR TITLE
Change notifications timestamp to nullable & default to now

### LINKED ISSUE #14100: Notifications GraphQL requires `timestamp` field is non-nullable
### Describe the Bug

**TL;DR**
1. Notifications GraphQL API expects wrong types and doesn't work at all
2. Notifications REST API requires EMAIL to be set-up? Not mentioned in the docs + why so? Notifications should be able to be just in-application without an email tied to it.
3. Notifications REST API can be abused even without ANY auth header
4. Notifications REST API: the Notification created will link to an invalid url in the app (`/admin/content/null/null`)
---

I tried following the [docs for the notifications API](https://docs.directus.io/reference/system/notifications/#notifications) to post a message to a user.

According to that doc's example, all that is needed to POST a notification are the `recipient` and `subject`.

First I tried it using GraphQL with the following query:
```ts
const systemMutation = gql`
  mutation createNotification(
    $USER: ID!
    $MESSAGE: String!
  ) {
    create_notifications_item(
      data: {
        recipient: $USER
        subject: $MESSAGE
      }
    ) {
      id
    }
  }
`;
const sysemMutationResult: {
  create_notifications_item: {
    data: {
      id: string;
    };
  };
} = await graphQLSystemClient.request(systemMutation, {
  USER: notification.user,
  MESSAGE: notification.message,
});

```

And I received the first odd error:
> `timestamp` (type `String!`) is supposedly required

I thought that's weird, but I guess I'll just generate one myself and add it to the `data`.

After adding `timestamp` to the `data` object, I received the next odd error:
> `$USER` is supposed to be of type `create_directus_users_input!` and not `ID!`

That did not make any sense to me. I tried playing around with data for that type, but `create_directus_users_input` seems to expect a full user object, not just the primary id (which makes no sense, of course, I don't want to create a new user)

So I gave up on using the GraphQL endpoint and thought, that maybe the REST API will work.

```ts
const response = await fetch(`${process.env.DIRECTUS_REST_ENDPOINT}/notifications`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Authorization: "Bearer XXXXX",
    Accept: "application/json", // required
  },
  body: JSON.stringify({
    recipient: "xxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
    subject: ":)))",
  }),
});
```
The REST API actually kinda worked but still had some weird quirks:
1. The EMAIL needed to be setup, otherwise there was an error 500 (`Error: Sendmail exited with code 1`)
2. Even if **no** `Authorization` header was provided **a Mail was still sent out** (after configuring mail)
   - > Seems like quite the security issue, but I think it's not THAT big of a deal, because someone trying to abuse this would still need to know userIDs first I think
3. The Notification created will link to an invalid url in the app (`/admin/content/null/null`)

> I used the endpoints `http://localhost:8055/graphql/system` and `http://localhost:8055/notifications`
> The Bearer token used had admin privileges

### To Reproduce

Run similar queries to the ones mentioned above

docker-compose.yml used locally:
```yml
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:latest
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'

  cache:
    container_name: cache
    image: redis:latest
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: 'xxx'
      SECRET: 'xxxx'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'xxx@example.ch'
      ADMIN_PASSWORD: 'xxx'

      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: 'mail.example.ch'
      EMAIL_SMTP_PORT: '999'
      EMAIL_SMTP_USER: 'acc@example.ch'
      EMAIL_SMTP_PASSWORD: 'xxx'

      EXTENSIONS_AUTO_RELOAD: 'true'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:

```

### Errors Shown

GraphQL error when trying to create a notifications item without a timestamp in the `data`
```
Field "create_directus_notifications_input.timestamp" of required type "Date!" was not provided.
```
GraphQL error when trying to create a notifications item with the recipient being type `ID!`
```
Variable "$USER" of type "ID!" used in position expecting type "create_directus_users_input"
```
GraphQL error that illustrates that the expected recipient is a full object and not just the primary key
```
Expected type "create_directus_users_input" to be an object.
```
Console error when REST API is called without email being set-up
```
Error: Sendmail exited with code 1
```

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

v16.14.0

### What database are you using?

Postgres 14.3

### What browser are you using?

Chrome

### How are you deploying Directus?

docker-compose locally

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Closes #14100 

(There are other bugs reported in the issue, however each of them are being tracked in separate issues now, as described in https://github.com/directus/directus/issues/14100#issuecomment-1178534044)

### Problem

When creating a notification via GraphQL, it is requiring `timestamp` even though that field should default to the timestamp on creation:

Error message: `"Field \"create_directus_notifications_input.timestamp\" of required type \"Date!\" was not provided."`

chrome_hEoZ2gfzMo

GraphQL is making this field required as it is indeed set as notNullable:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/api/src/database/migrations/20211118A-add-notifications.ts#L6

However it already has the special flag `date-created`, which is why it has worked via REST:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/api/src/database/system-data/fields/notifications.yaml#L5-L8

### Solution

Added a migration and follow the same solution for `date_created` fields in other system tables such as dashboards & flows:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/api/src/database/migrations/20210525A-add-insights.ts#L9

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/api/src/database/migrations/20220429A-add-flows.ts#L17

Result:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/api/src/database/system-data/fields/notifications.yaml#L5-L8

Note that although it still shows an error, it is because it is trying to create a user instead of associating the user to the notification. However this issue is tracked in #7237 separately hence not a part of the goal of this PR.

chrome_GsHj5C7uZ5

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
@azrikahar I think the real fix here should be that the API validation considers the special flags that set data as valid default values as well. Right now you will have the same problem with any other collection that has a timestamp with no sql default value but with the "on create" / "on update" flags associated 🤔 

I believe that the validation error here is thrown from GraphQL directly, rather than the Directus services, which means that the schema building logic only checks for the nullable state when setting `GraphQLNotNull()`, so we should include a check for the `special` flag on the field as well (and reference it against a new const array of flags that generate data)

**Comment by azrikahar** [comment]
@rijkvanzanten good point! When looking into the "check for special flag", just realized this was technically also being done here (assuming I understood it correctly, but it's the inverse/nullable):

https://github.com/directus/directus/blob/06a618c758d0a7f45536b2c5e8eb9d27ccd6426b/api/src/services/authorization.ts#L499-L503

Pushed a commit, that should reflect the same idea right? Also didn't include the "on update" flags since there's an existing logic preventing this from happening to GraphQL updates:

https://github.com/directus/directus/blob/06a618c758d0a7f45536b2c5e8eb9d27ccd6426b/api/src/services/graphql/index.ts#L404-L409

Btw just to be sure, do we still want to keep the migration? I assume it's redundant now? (or maybe it's still preferred to make default-to-now-fields more "uniform")

**Comment by rijkvanzanten** [comment]
We can leave the migration 👍🏻 Kinda nice in case you go straight to DB, and keeps it consistent with the others

File: api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+export async function up(knex: Knex): Promise<void> {
+	await knex.schema.alterTable('directus_notifications', (table) => {
+		table.timestamp('timestamp').defaultTo(knex.fn.now()).alter();
+	});
+}
+
+export async function down(knex: Knex): Promise<void> {
+	await knex.schema.alterTable('directus_notifications', (table) => {
+		table.timestamp('timestamp').notNullable().alter();
```
Comment (rijkvanzanten) [inline api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts:11]: Should this remove the default value again?

Comment (rijkvanzanten) [reply api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts:11]: Also we should use the helper like in other migrations. I'm pretty sure this breaks in oracle

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts (hunk 1 above)
Comment (azrikahar) [reply api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts:11]: > Should this remove the default value again?

I believe not adding `defaultTo` in an alter statement means there won't be default value anymore 🤔 at least that's the case when I tested on Postgres, and I think this is also the same logic in the helper as well:

https://github.com/directus/directus/blob/06a618c758d0a7f45536b2c5e8eb9d27ccd6426b/api/src/database/helpers/schema/types.ts#L22-L44

> Also we should use the helper like in other migrations. I'm pretty sure this breaks in oracle

Actually I tried to find it before the current migration, but I'm not sure if there's one that's applicable for timestamp? (other than `changeToText`, `changeToInteger` and `changeToString`. It also seems like `changeNullable` isn't really used anywhere except in the protected `changeToTypeByCopy`)

Comment (rijkvanzanten) [reply api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts:11]: > Actually I tried to find it before the current migration, but I'm not sure if there's one that's applicable for timestamp? (other than changeToText, changeToInteger and changeToString

Hmm, we should just make a `updateType` helper with a string for the type input.

Comment (azrikahar) [reply api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts]: added the `updateType` helper, but not sure am I misinterpreting the expected usage 🤔

but assuming it fits, this would mean `changeToText` and `changeToInteger` will technically be redundant right? as we can use `updateType(table, column, 'integer', options)` to replace `changeToInteger(table, column, options)` for example.

**Review by rijkvanzanten — APPROVED** [review]

File: api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts (hunk 1 above)
Comment (rijkvanzanten) [reply api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts]: > but assuming it fits, this would mean changeToText and changeToInteger will technically be redundant right? 

That's correct. I'd rather have one "changeType" utility that takes the types as parameters, than individual methods for each type 👍🏻

Comment (azrikahar) [reply api/src/database/migrations/20220708A-update-notifications-timestamp-column.ts]: Thanks for clearing it up 👍 replaced all the individual methods now.

File: api/src/database/helpers/schema/dialects/cockroachdb.ts [hunk 2]
```diff
@@ -11,14 +11,6 @@ export class SchemaHelperCockroachDb extends SchemaHelper {
...
 
-	async changeToText(
-		table: string,
-		column: string,
-		options: { nullable?: boolean; default?: any } = {}
-	): Promise<void> {
-		await this.changeToTypeByCopy(table, column, options, (builder, column) => builder.text(column));
-	}
-
 	async changeToString(
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts]: Didn't replace it initially because it's slightly different in that it'll use the `length` in options, but I've replace them now and modified the `changeToType` to use length when it's string 👍

File: api/src/database/helpers/schema/types.ts [hunk 3]
```diff
@@ -19,37 +21,14 @@ export abstract class SchemaHelper extends DatabaseHelper {
 		});
 	}
 
-	async changeToText(
-		table: string,
-		column: string,
-		options: { nullable?: boolean; default?: any } = {}
-	): Promise<void> {
-		await this.knex.schema.alterTable(table, (builder) => {
-			const b = builder.string(column);
```
Comment (licitdev) [inline api/src/database/helpers/schema/types.ts:28]: The `changeToText` uses `.string()` for all vendors except for `oracle` and `crdb`. It was necessary in order to support these two vendors. Ref: https://github.com/directus/directus/pull/5462 & https://github.com/directus/directus/pull/10113.

After this PR, existing fields such as `url` and `collections` in `directus_webhooks` will be set to `text` type. Whereas the existing installations would still have them as `string` type.

@rijkvanzanten How should we approach this issue?
- Should we add database specific migrations so we will be able to run `changeToType(...'string')` for all vendors except for `oracle` and `crdb` which will run `changeToType(...'text')` to maintain the existing behaviour?
- Or should we standardise it where we add a migration so that all databases will have the same `text` type from now onwards? 

The latter option would definitely be less efficient, database wise.

Comment (rijkvanzanten) [reply api/src/database/helpers/schema/types.ts:28]: > Or should we standardise it where we add a migration so that all databases will have the same text type from now onwards?

Even though it's less efficient on most databases, I'm worried about having databases in different system states based on their vendor. 🤔 For example if we rely on the database for max length, it's gonna work differently based on what vendor you're using

Comment (licitdev) [reply api/src/database/helpers/schema/types.ts:28]: @rijkvanzanten The fields are of type `string` with a length of `255`, which is the default value when length is not provided.  
An example is the `collections` field in `directus_webhooks`. https://github.com/directus/directus/blob/71e23a024eeefd4ebd691ae6a2a2c255f84f98e6/api/src/database/seeds/14-webhooks.yaml#L32-L35
How should we proceed?

Comment (rijkvanzanten) [reply api/src/database/helpers/schema/types.ts:28]: Difficult difficult question. Before we set that limit to 64 as that was the table length limit on Postgres, but that was changed to 255 to account for sqlite names if I recall correctly 🤔 Making those text doesn't make too much sense as we know they're smaller values. That being said, is it that noticeable of a performance difference nowadays? There's whole ORM abstractions that rely exclusively on storing everything unstructured

Comment (azrikahar) [reply api/src/database/helpers/schema/types.ts:28]: I believe the main concern is the slight difference of field type across different Directus instances depending on their installation "period". Hopefully this table helps to summarize it:

|                                   | CockroachDB | Oracle | Other DBs |
| --------------------------------- | ----------- | ------ | --------- |
| New installations in the past     | -           | CLOB   | text      |
| New installations after PR #10113 | text        | text   | string    |
| New installations after this PR   | text        | text   | text      |

As there's that slight difference, there'll be a form of "desync" between several instances. Another potential issue could be with schema migrations (as the schema file will indicate them differently) across Directus instances that were initialized with "different" webhooks migrations. 🤔

With all that being said, I do also want to acknowledge that as `changeToText` helper was exclusively used in `directus_webhooks` migrations only, and since webhooks will be deprecated in favor of Flows in the future, this whole concern will technically be obsolete when that happens 😅

Comment (azrikahar) [reply api/src/database/helpers/schema/types.ts:28]: We can also make use of the `isOneOfClients` helper:

https://github.com/directus/directus/blob/52598538f047e093e6629cfe3680eddbbd7f5f19/api/src/database/migrations/20210626A-change-filesize-bigint.ts#L7-L9

and wrap it as an IF-ELSE for `changeToType` in webhook migrations to keep the existing "text for crdb and oracle, string for others" behavior 👍

**Review by licitdev — APPROVED** [review]
