### PR TITLE
Fix spacings and icons on presentation link buttons

### LINKED ISSUE #6358: Bad spacing in Button Links from Alias and Presentation Field (or am i using it wrong?)
1) The issue and what you expected to happen
    when adding multiple buttons they overlap

2) Exact steps to reproduce this issue
    Add a presentation and alias field--->In interface tab select button links---->Add some buttons with a large title and select a icon for every button--->Go to collection's view and look the result.

3) Your environment:
    What version of Directus you are using: 9.0.0-rc.76
    Which DBMS are you using: Postgres 12.7
    Which deployment are you using: npx (ubuntu server 20.04)
    What browser are you using: MS Edge, Chrome, Firefox, Opera, latest versions

4) Any other relevant information we might need to reproduce this issue
    NodeJS 14.17.0

image

### PR DESCRIPTION
**Pull request by HitomiTenshi**
Fixes #6358

For an explanation of my changes see https://github.com/directus/directus/issues/6358#issuecomment-863580437

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/interfaces/presentation-links/presentation-links.vue [hunk 1]
```diff
@@ -59,16 +59,10 @@ export default defineComponent({
 .presentation-links {
 	display: flex;
 	flex-wrap: wrap;
-	margin: -4px;
+	gap: 8px;
```
Comment (HitomiTenshi) [inline app/src/interfaces/presentation-links/presentation-links.vue:62]: @rijkvanzanten Oh I didn't know about `gap`, good to know! Thanks! 😄
