### PR TITLE
Fix SDK policy type and updateRole function

### LINKED ISSUE #23313: SDK does not allow to query nested field of core collection
### Describe the Improvement

I am not able to query a nested field of a core collection in a type safe way. It seems to work for custom collections and fields. Here is a code example that can be used to reproduce the "problem":

```ts
import { createDirectus, readUsers, rest } from '@directus/sdk';

interface Collections {
	a_collection: { id: string };
}

const client = createDirectus<Collections>('URL').with(rest());

const users = await client.request(
  readUsers({ fields: ['id', { role: ['id', 'name'] }] }) // <- TS error here
);

const firstRoleName = users[0]?.role.name; // <- TS error here
```

### LINKED ISSUE #24206: [SDK] Roles -> policies type is incorrect
### Describe the Bug

Follows up on https://github.com/directus/directus/issues/24168#issuecomment-2528087907

393867185-52b019f3-86fc-4ed6-90d4-4f7bff0a8e76

### To Reproduce

The following snippet throws a type error as shown in the screenshot above
```js
await client.request(updateRole(roleId, {
    policies: [{ policy: policy.id }],
}))
```

### Directus Version

11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

-

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #24206
Fixes #23313

## Scope

There are 2 underlying issues addressed here:
1. The new `directus_access` schema was missing for relating to policies
2. The `updateUser*` were not using `NestedPartial` for input types and `NestedPartial` failed to loop through unions like `string[] | DirectusRole<Schema>[]`

What's changed:

- Added missing `directus_access` schema
- Updated `directus_role` type
- Updated `NestedPartial` type to support unions
- Added `NestedPartial` to `updateRole*` functions

## Potential Risks / Drawbacks

- Type issues

## Review Notes / Questions

- The `ToTuple` helper type allows us to split up union types and treat each part individually. Example usage:
```ts
type T = ToTuple<'a' | 'b' | 1>;
//   ^? ['a', 'b', 1]
```
---

### CODE REVIEW

File: sdk/src/schema/access.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+import type { DirectusUser } from './user.js';
+
+export type DirectusAccess<Schema = any> = MergeCoreCollection<
+	Schema,
+	'directus_access',
+	{
+		id: string; // uuid
+		role: string | DirectusRole<Schema>;
+		user: string | DirectusUser<Schema>;
+		policy: string | DirectusRole<Schema>;
```
Comment (ComfortablyCoding) [inline sdk/src/schema/access.ts:12]: Should this not be DirectusPolicy?

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
