### PR TITLE
Prevent null being converted to empty object in deepMap utility function

### LINKED ISSUE #8096: INVALID_QUERY when browsing collections using archive field
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When opening a collection, an unexpected error occurs.
image

This issue only surfaces for **existing** collections using a `Status` or `Archive` field.
image

### To Reproduce

Browse a collection. 

Not sure where the issue is but the url that causes this error is `.../items/something?limit=25&fields[]=id&fields[]=name&sort=id&page=1&filter=%7B"status":%7B"_neq":null%7D%7D`.

Upon clicking the reset page preferences button, the request url becomes `/items/something?limit=25&fields[]=id&fields[]=name&fields[]=status&sort=id&page=1&filter=%7B%7D` and loads fine.

However, when browsing to another collection and back, the same error occurs.

### Tested workarounds
- If the archive field is deselected for **some** collections, the error vanishes.
- The error can also be removed temporarily by setting an advanced filter then removing it.
  - A preset is automatically saved. However, when the preset is deleted, the error comes back.
  - Remember to refresh the entire webpage after deleting the preset, to see error resurface.

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

### PR DESCRIPTION
**Pull request by azrikahar**
Closes #8096

## Reported Bug

When we leave Archive Value as null for a particular collection:

chrome_8M4QxA2wT3

We will face error when viewing that collection:

ws1wHjdxQA

The underlying API call for it does have the filter `filter: {"status":{"_neq":null}}`. However I believe `_neq=null` is an acceptable filter for string so it should qualify as a bug, and it must be a recent change/regression as the issue owner mentioned that it used to work in the past.

## Investigation

If we check the `validateFilterPrimitive` function, it does return true if the value is null. Only if it's not, then it will return the error shown above:

https://github.com/directus/directus/blob/9967274ab276a4adfe4a76b775b614cf940dcb27/api/src/utils/validate-query.ts#L94-L102

Since the API call does request for `_neq: null`, what gives? As we can see here, the resulting query filter actually shows that it is an empty object, not `null`:

Code_jAePeYEBKH

Seems like in the SanitizeFilter, which happens before validateQuery, the deepmap function is responsible for turning `null` into an empty object:

  - Before processed by deepmap, it's `null`: 
      Code_J0RzRhYdxT
        
  - After processed by deepmap, it's `{}`:
      Code_vlcjHVKcLl

Finally looks like `typeof null === 'object'` DOES equals to true, that's why it's turned into `{}`:

nITT5mKkf4 

Note: this deepmap function was added in SanitizeFilter from the recent Geometry/Map feature, so once again that explains why the issue owner faced this error only after they update their Directus recently: https://github.com/directus/directus/pull/5684/files#diff-5b6b8ed21158e5378ab1be3561ca320371c142c323f7af9c4c7adbf27265115b

## Solution

Added `object !== null` to ensure it's not turned into an empty object.

## Uncertainty

Is the empty object by any chance an intended feature? Also not sure if this will break anything where they intentionally wants empty object instead of null.

I'm also unsure whether we need to add the `object !== null` check here:

https://github.com/directus/directus/blob/9967274ab276a4adfe4a76b775b614cf940dcb27/packages/shared/src/utils/deep-map.ts#L9

### CODE REVIEW

File: packages/shared/src/utils/deep-map.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ export function deepMap(
 		return object.map(function (val, key) {
 			return typeof val === 'object' ? deepMap(val, iterator, context) : iterator.call(context, val, key);
 		});
-	} else if (typeof object === 'object') {
+	} else if (object !== null && typeof object === 'object') {
```
Comment (rijkvanzanten) [inline packages/shared/src/utils/deep-map.ts:11]: I think a more known solution here is to replace the `typeof object === 'object'` with Lodash' `isObjectLike`

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
