### PR TITLE
Fix user-popover location when hovered in revisions

### LINKED ISSUE #7926: User Tooltips not correctly positioned
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The user tooltips are showing in the top-left corner of the App... instead of directly next to the user name. Also, ideally, I would like to make it so the username is NOT clickable, but instead, clicking the **tooltip** itself takes you to the user's detail page. This might require some fanciness to allow the cursor to move onto the tooltip.

Screen Shot 2021-09-08 at 12 41 06 PM

### To Reproduce

Hover over a user name in the revisions sidebar.

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #7926

## Bug reported in the issue

The user tooltip **for revisions** are wrongly shown on the top left corner:

orZOLhGpxp

There is an emphasis on "for revisions" because if we observe the same user tooltip in the table view, it is working as expected:

QjWgVVtdK9

## Investigation

If we look at the `v-menu` component which is used for this user tooltip `user-popover`, we can see there are `activator` and `reference` to target HTML element, with `virtualReference` technically a point in the top left corner because of everything is 0 as observed here:

https://github.com/directus/directus/blob/640368a21b4743689c1df5568eb20ddd564ec8c0/app/src/components/v-menu/v-menu.vue#L103-L117

Then when we look at the watcher for `isActive`, which dictates whether the tooltip appears or not, we can see the logic for `reference` being either the first child of the `activator` (i.e. the first child of the element we hover at) or just the virtual reference which is the top left corner:

https://github.com/directus/directus/blob/640368a21b4743689c1df5568eb20ddd564ec8c0/app/src/components/v-menu/v-menu.vue#L140-L148

This is why the tooltip works in table view because there's a div (with class `user both`) inside the activator element (the one with class `v-menu-activator`) as shown here:

vivaldi_vm88o8xK4v

Whereas the user-popover in revisions directly inserts the user email without any wrapping element as the child:

https://github.com/directus/directus/blob/640368a21b4743689c1df5568eb20ddd564ec8c0/app/src/views/private/components/revisions-drawer-detail/revision-item.vue#L10-L12

vivaldi_jxFiD10QZV

## Solution

Add a wrapping element, specifically `<span>` tag on the user email, then it'll work as expected:

OaG0lbvGA3

S5StsW3inG

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you so much, @azrikahar!! I think you have some of the best written PRs I've ever seen. 😍

File: app/src/views/private/components/revisions-drawer-detail/revision-item.vue [hunk 1]
```diff
@@ -163,6 +163,11 @@ export default defineComponent({
 	}
 
 	.user {
+		span {
+			margin: -6px;
+			padding: 6px;
+		}
```
Comment (rijkvanzanten) [inline app/src/views/private/components/revisions-drawer-detail/revision-item.vue:169]: Good call to increase the hitbox for this a notch too 👍🏻

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/views/private/components/revisions-drawer-detail/revision-item.vue (hunk 1 above)
Comment (azrikahar) [reply app/src/views/private/components/revisions-drawer-detail/revision-item.vue:169]: Thanks :) when I look/think back at it, the thought of making the hitbox larger suddenly popped up 😄 used to do the same thing for buttons-look-like-links in past projects
