### PR TITLE
Fix errors thrown for starts_with and ends_with variations

### LINKED ISSUE #18992: validationError.undefined for validations with startsWith
### Describe the Bug

It seems that [translation](https://github.com/directus/directus/blob/94bfecf72e0802d03d5e85363d85d4e7d6da08bb/app/src/lang/translations/en-US.yaml#L133C2-L133C2) for startsWith validation is missing

### To Reproduce

Create field with validation that uses startsWith

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by br41nslug**
All the variations of `starts_with` and `ends_with` use a regex match in Joi which was not being caught in the error transformation done by `joiValidationErrorItemToErrorExtensions()`.
Also added the missing translations for these filters.

Fixes #18992

### CODE REVIEW

**Comment by paescuj** [comment]
> TODO find a better way of passing the expected value down to the client.

Could we just pass `compareValue` to the `validationErrorItem` context?

**Comment by br41nslug** [comment]
> > TODO find a better way of passing the expected value down to the client.
> 
> Could we just pass `compareValue` to the `validationErrorItem` context?

Didnt find a way to do so yet (without dumping significantly more time in this issue than i already have 😬)

**Review by paescuj — APPROVED** [review]
LGTM!

Would you mind adding the TODO as a comment to the code?

File: packages/validation/src/utils/joi-to-error-extensions.ts [hunk 1]
```diff
@@ -94,6 +94,27 @@ export const joiValidationErrorItemToErrorExtensions = (
 		extensions.invalid = validationErrorItem.context?.value;
 	}
 
+	// TODO Find a better way of passing the expected value down to the client
+	if (joiType.endsWith('.pattern.name')) {
```
Comment (azrikahar) [inline packages/validation/src/utils/joi-to-error-extensions.ts:98]:
```suggestion
	if (joiType.endsWith('.pattern.name') || joiType.endsWith('.pattern.invert.name') {
```

this is due to when the `invert` option is set to true:

https://github.com/directus/directus/blob/b211a3b68d4af52237decc68fc556941fb5935ec/packages/utils/shared/generate-joi.ts#L193-L196

the name ends up having `.invert` in between, as seen in https://joi.dev/api/?v=17.9.1#stringpatterninvertname.

File: packages/validation/src/utils/joi-to-error-extensions.ts [hunk 2]
```diff
@@ -94,6 +94,27 @@ export const joiValidationErrorItemToErrorExtensions = (
 		extensions.invalid = validationErrorItem.context?.value;
 	}
 
+	// TODO Find a better way of passing the expected value down to the client
```
Comment (azrikahar) [inline packages/validation/src/utils/joi-to-error-extensions.ts:97]: regarding this, I wonder whether it is possible to do something similar to the existing `contains` and `ncontains` which are an extension of the Joi instance:

https://github.com/directus/directus/blob/b211a3b68d4af52237decc68fc556941fb5935ec/packages/utils/shared/generate-joi.ts#L18-L59

which may make it possible to attach the "substring" even for all variations of starts_with/ends_with without having to extract it from `validationErrorItem.context?.['regex']`. I'm still not 100% sure why/how `contains` and `ncontains` returns "substring" in the context (unless "substring" being in `args` is the factor here)

however that can/should be a separate PR, so this particular review comment shouldn't block this particular PR.

Comment (paescuj) [reply packages/validation/src/utils/joi-to-error-extensions.ts:99]: Took a quick look at this. Could work, but the extension would need to be named differently (cannot override `pattern`). Then we would have to replace usages of `pattern` with this extension. Hopefully we could just reuse `pattern` in this extension instead of re-implementing the whole logic.
In summary, a bit much effort just to get the value easier.

**Review by azrikahar — APPROVED** [review]
