### PR TITLE
Replace mapValuesDeep with deepMap

### LINKED ISSUE #25209: Combine API's `mapValuesDeep` and Util's `deepMap` into a single function
### Describe the Bug

They're more or less doing the same thing, it's confusing which you should pick then so we should combine them to only have a single function.

### To Reproduce

...

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- We had to relative similar functions which are now reduced into one.

## Potential Risks / Drawbacks

- I made sure that the function kept the same name, properties and behavior but still cleaned it up slightly, as both implementations where a little bit messy.

## Review Notes / Questions

- Should be merged after #25207 is merged

---

Fixes #25209

### CODE REVIEW

File: packages/utils/shared/deep-map.ts [hunk 1]
```diff
@@ -1,25 +1,25 @@
...
-
-			if (isObjectLike(val)) {
-				res[key] = deepMap(val, iterator, context);
-			} else {
-				res[key] = iterator.call(context, val, key);
-			}
+	function recurse(value: any, key?: string | number): any {
+		if (Array.isArray(value)) {
+			return value.map(recurse);
+		} else if (isObjectLike(value) && isPlainObject(value)) {
```
Comment (ComfortablyCoding) [inline packages/utils/shared/deep-map.ts:16]: Are we able to use `isObject` here instead?

Comment (Nitwel) [reply packages/utils/shared/deep-map.ts:16]: Because `isObject(new Date()) === true` which we don't want here.

File: .changeset/fine-boats-brush.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+'@directus/utils': patch
+'@directus/api': patch
+---
+
+Combined mapValuesDeep into deepMap and cleaned function up.
```
Comment (ComfortablyCoding) [inline .changeset/fine-boats-brush.md]:
```suggestion
Replaced mapValuesDeep with deepMap.
```

**Review by ComfortablyCoding — APPROVED** [review]
LGTM
