### PR TITLE
Deep merge relational fields in content versions

### LINKED ISSUE #20429: Content versions do not seem to work with relationships
### Describe the Bug

When trying out content versioning on basic fields (text for example), it works great and is an awesome feature, yet when trying it out on relationships, the behaviour is very strange.

I have a model called a **page** which is basically a wrapper for references to other pieces of content. Initially I was hoping content versions of those pieces of content would propagate when querying the **page**. It seems this does not work. The content version is only applied to the item you are querying and not any related content.

I decided to work around this by creating a content version of the **page** and changing one of the references to something new. Although this works, the functionality is limited. Querying via _graphql_ throws an error when trying to get the `id` of the related item. And querying via REST will only ever respond with the `id` of the related item (no matter how many levels of `fields=*.*.*` you add).

This highly limits this awesome feature and how it is just me doing something wrong :) 

### To Reproduce

- Create a collection called **pages**
- Create a collection called **blocks**
- For **pages**, add a many-to-one relationship with **blocks**
- For **blocks** add a text field called `name`
- Populate some content in each collection
- Create a content version of one of the referenced blocks called `experiment-ref`

#### Graphql
- Query pages via Graphql with `?version=experiment-ref`
- Add `id` to block fields in query results in `Cannot return null for non-nullable field`
- Any other field is the original value (not the content version)

##### REST
- Query pages via REST with `?version=experiment-ref`
- Reference value is always the id even when adding `fields=*.*.*`

---

- Create a content version of one of the pages called `experiment-page`

#### Graphql
- Query page via Graphql with `?version=experiment-page`
- Reference fields are `null`

#### REST
- Query page via Graphql with `?version=experiment-page`
- Reference value is always the id even when adding `fields=*.*.*`

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #20890: Content Versioning - deep merge content version changes in response
### Describe the Improvement

The current content versioning response where lists of related records are found returns in a **changeset** object in its place with `create`, `update` and `delete` properties, each with an array of values to perform said operations against the `main` version records.

The lack of a versioned response that is on par with the non-versioned response, limits the ability of content previewing to more simple data model projects without list relation fields.

I am proposing that the a new query parameter is introduced, to be used in conjunction with `version` to specify whether the changes come back as the **changeset** object for those related records (as it is now with the create, update, delete object) or to come back with the changes merged into the resulting query data. Default would be the current mode, which returns with the **changeset** object at the list relation field.

Longer term, my thought is that the default should be a merged result with the version changes, and a diff parameter to enabled the **changeset** response instead (which is used in the data studio app, so that would need updating as well).

I've taken a first pass as attempting to see how this would work and have come up with a relatively workable solution and would like to see what direction/advice might be had on this matter.

https://github.com/isaiahgrey93/directus/tree/isaiahgrey93/content-versioning-merged-diff-response

### PR DESCRIPTION
**Pull request by azrikahar**
## Scope

What's changed:

- Currently the `create/update/delete` structure for relational fields are still returned as-is when fetching a particular content version of an item. This PR attempts to "merge" the content version saves as a mock for the returned data when it gets merged in the future.
- Re-introduced the `version` argument for `<collection>_by_id` graphql queries. The existing `<collection>_by_version` will keep returning the `versionRaw` content as it does now and the `<collection>_by_id(id: '', version: '')` will return the newly merged content.

## Potential Risks / Drawbacks

- technically a breaking change, with a new query param `versionRaw` to get the unaltered original structure (the app uses this)

## Review Notes / Questions

---

Fixes #20890
Fixes #20429

### CODE REVIEW

File: api/src/utils/merge-version-saves.ts [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+
+			for (const relation of relations) {
+				const currentPrimaryKeyField = schema.collections[relation.related_collection!]!.primary;
+				const relatedPrimaryKeyField = schema.collections[relation.collection]!.primary;
+
+				payload[key] = [
+					...value
+						.filter((item) => {
+							if (item?.[currentPrimaryKeyField]) return !alterations.delete.includes(item[currentPrimaryKeyField]);
+							return !alterations.delete.includes(item);
```
Comment (br41nslug) [inline api/src/utils/merge-version-saves.ts:50]: We should probably check both `alternations !== falsy` and wether the `delete` property exists. I accidentally stored a alteration with just the `create` property which broke the API response for this entire item.

```suggestion
							return !alterations.delete?.includes(item);
```

**Review by br41nslug — COMMENTED** [review]
The merging itself is working fine on the first level but fails for nested relations. So far this is purely visual, so you still cannot query into the relational fields it will just look like the related object with the updated values (independent of filter/field settings on the query)

The big question I have here is: Is querying relational version fields part of the MVP?
- If yes then there is still a lot to do and unanswered questions
- If no then lets be very clear about in the documentation because it is really easy to assume it would work!

File: api/src/middleware/merge-content-versions.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
+import type { RequestHandler } from 'express';
+import { VersionsService } from '../services/versions.js';
+import asyncHandler from '../utils/async-handler.js';
+import { mergeVersionsRaw, mergeVersionSaves } from '../utils/merge-version-saves.js';
+
+/**
+ * Checks and merges
+ */
+export const mergeContentVersions: RequestHandler = asyncHandler(async (req, res, next) => {
```
Comment (DanielBiegler) [inline api/src/middleware/merge-content-versions.ts:9]: I know its still WIP, just want to leave this comment as reminder for later to update/finish this comment

**Review by DanielBiegler — CHANGES_REQUESTED** [review]
I ran into the following error right now when querying with the new merging:

```json
{
  "errors": [
    {
      "message": "Cannot use 'in' operator to search for 'id' in null",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stack": "TypeError: Cannot use 'in' operator to search for 'id' in null\n    at mergeVersionSaves (/home/dan/Projects/directus-src/api/src/utils/merge-version-saves.ts:48:8)\n    at <anonymous> (/home/dan/Projects/directus-src/api/src/middleware/merge-content-versions.ts:31:33)"
      }
    }
  ]
}
```

1. Create an item with a M2O and select an item
2. Create a new version of this item
3. Query this item with the new merging, it works for me:
4. ```... "m2o": "2aae8be7-ea90-4cbb-99ef-d39119256b23", ...```
5. Clear this field
6. Refetch now with the new merging
7. Now I get this error:

```json
{
  "errors": [
    {
      "message": "Cannot use 'in' operator to search for 'translations' in null",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stack": "TypeError: Cannot use 'in' operator to search for 'translations' in null\n    at <anonymous> (/home/dan/Projects/directus-src/api/src/utils/merge-version-saves.ts:31:96)\n    at Array.reduce (<anonymous>)\n    at mergeVersionSaves (/home/dan/Projects/directus-src/api/src/utils/merge-version-saves.ts:29:37)\n    at mergeVersionSaves (/home/dan/Projects/directus-src/api/src/utils/merge-version-saves.ts:60:20)\n    at <anonymous> (/home/dan/Projects/directus-src/api/src/middleware/merge-content-versions.ts:31:33)"
      }
    }
  ]
}
```

Which interestingly enough is slightly different than the initial one but the same problem.

**Review by DanielBiegler — COMMENTED** [review]
It'd be also nice if we could merge https://github.com/directus/directus/pull/21509 so that we can test relational stuff easier for this PR

**Review by DanielBiegler — DISMISSED** [review]
The merging doesnt seem to work for my O2M relation for some reason :thinking: 

I have the following item and field in my main version:

```json
    "o2m": [
      "2aae8be7-ea90-4cbb-99ef-d39119256b23",
      "3a51d23a-a61e-4e19-be07-207aaffd0373"
    ]
```

Now in my draft version:

- I delete one item
- Add an existing item

image

which correctly generates the following raw response:

```json
    "o2m": {
      "create": [],
      "update": [
        {
          "m2a": "2",
          "id": "9d12e0ec-539e-4412-beb4-d7a87e80f973"
        }
      ],
      "delete": [
        "3a51d23a-a61e-4e19-be07-207aaffd0373"
      ]
    }
``` 

but now switching to the merged version shows only one item remaining:

```json
    "o2m": [
      "2aae8be7-ea90-4cbb-99ef-d39119256b23"
    ]
```

But whats interesting is that it seems to work for M2A:

image

```json
    "m2a": [
      4,
      {
        "test_content_version_m2m_id": "2",
        "collection": "example",
        "item": {
          "id": "9d12e0ec-539e-4412-beb4-d7a87e80f973"
        }
      }
    ],
```

**Comment by rijkvanzanten** [comment]
I'll handle the breaking change note 👍🏻

File: api/src/middleware/merge-content-versions.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+			req.sanitizedQuery.version,
+			req.collection,
+			req.params['pk'],
+		);
+
+		if (!versionData) return next();
+
+		const originalData = res.locals['payload'].data;
+
+		if ((originalData && typeof originalData !== 'object') || versionData.length === 0) {
```
Comment (ComfortablyCoding) [inline api/src/middleware/merge-content-versions.ts:25]: We can move the `originalData` check to before L13 or as an additional check in the `if`  to reduce work needed for the false case.

I believe we can also reduce the check from `originalData && typeof originalData !== 'object'` to `typeof originalData !== 'object'`? I believe they are equivalent.

Comment (ComfortablyCoding) [reply api/src/middleware/merge-content-versions.ts:25]: Right, always with the gotchas. I was thinking more undefined than null, I have not checked the response types yet. I guess we will need to stick with it for now in that case.

Comment (paescuj) [reply api/src/middleware/merge-content-versions.ts:25]: I feel like this line could need a comment - what the check is supposed to do

File: api/src/utils/merge-version-data.ts [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+	create: Joi.array().items(Joi.object().unknown()),
+	update: Joi.array().items(Joi.object().unknown()),
+	delete: Joi.array().items(Joi.string(), Joi.number()),
+});
+
+export function mergeVersionsRaw(item: Item, versionData: Partial<Item>[]) {
+	const result = { ...item };
+
+	for (const versionRecord of versionData) {
+		for (const key in versionRecord) {
```
Comment (ComfortablyCoding) [inline api/src/utils/merge-version-data.ts:15]: As this is using `in` should we be checking `Object.prototype.hasOwnProperty.call(versionRecord, key)`?

File: api/src/utils/merge-version-data.ts [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+		for (const key in data) {
+			if (!versionRecord || key in versionRecord === false) {
+				continue;
+			}
+
+			const currentValue: unknown = data[key];
+			const newValue: unknown = versionRecord[key];
+
+			if (typeof newValue !== 'object' || newValue === null) {
+				// primitive type substitution
```
Comment (ComfortablyCoding) [inline api/src/utils/merge-version-data.ts:53]:
```suggestion
				// primitive type substitution
				// json and non relational array values are handled in the next check
```

File: api/src/utils/merge-version-data.ts (hunk 4 above)
Comment (paescuj) [reply api/src/utils/merge-version-data.ts:15]: Yes, but preferably via `for (const [key, value] of Object.entries(versionData))`.
Also this applies to other similar usages in the file as well.

File: api/src/utils/merge-version-data.ts [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+				result[key] = newValue;
+				continue;
+			}
+
+			if (key in relations === false) {
+				// check for m2a exception
+				if (isManyToAnyCollection(collection, schema) && key === 'item') {
+					const item = addMissingKeys(currentValue && typeof currentValue === 'object' ? currentValue : {}, newValue);
```
Comment (ComfortablyCoding) [inline api/src/utils/merge-version-data.ts:61]:
```suggestion
					const item = addMissingKeys(isObject(currentValue) ? currentValue : {}, newValue);
```

If accepted an import from utils is required for this to work.

File: api/src/utils/merge-version-data.ts [hunk 7]
```diff
@@ -0,0 +1,186 @@
...
+	versionData: Partial<Item>[],
+	collection: string,
+	schema: SchemaOverview,
+): unknown {
+	const result = { ...data };
+	const relations = getRelations(collection, schema);
+
+	for (const versionRecord of versionData) {
+		for (const key in data) {
+			if (!versionRecord || key in versionRecord === false) {
```
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/utils/merge-version-data.ts:45]: Theoretically, I'm afraid this could be possible - at least I think I've seen a `null` entry out in the wild (will see if I'm able to reproduce...).
But if we account for that, we should adjust the type 👍 Also shouldn't it be placed like
```js
	for (const versionRecord of versionData) {
		if (!versionRecord) continue;
		// ...
```
?

[the remark this answers is not in the document]
Comment (ComfortablyCoding) [reply api/src/utils/merge-version-data.ts:45]: Agreed, it should be shifted higher!

File: api/src/utils/merge-version-data.ts [hunk 8]
```diff
@@ -0,0 +1,186 @@
...
+import { isObject } from '@directus/utils';
+
+const alterationSchema = Joi.object({
+	create: Joi.array().items(Joi.object().unknown()),
+	update: Joi.array().items(Joi.object().unknown()),
+	delete: Joi.array().items(Joi.string(), Joi.number()),
+});
+
+export function mergeVersionsRaw(item: Item, versionData: Partial<Item>[]) {
+	const result = { ...item };
```
Comment (rijkvanzanten) [inline api/src/utils/merge-version-data.ts:13]: I believe this is intended to be a clone, but be aware that a top level `...` doesn't clone the whole nested structure. Any arrays or objects that are root properties are still by references instead of copied. We should probably use lodash' `cloneDeep` here to be safe.

File: api/src/utils/merge-version-data.ts [hunk 9]
```diff
@@ -0,0 +1,186 @@
...
+	collection: string,
+	schema: SchemaOverview,
+): Item {
+	if (versionData.length === 0) return item;
+
+	return recursiveMerging(item, versionData, collection, schema) as Item;
+}
+
+function recursiveMerging(data: Item, versionData: unknown[], collection: string, schema: SchemaOverview): unknown {
+	const result = { ...data };
```
Comment (rijkvanzanten) [inline api/src/utils/merge-version-data.ts:36]: Same clone thing here

File: api/src/utils/merge-version-data.ts [hunk 10]
```diff
@@ -0,0 +1,186 @@
...
+				if (typeof newValue === 'object' && key in relations) {
+					const newItem = !currentValue || typeof currentValue !== 'object' ? newValue : currentValue;
+					result[key] = recursiveMerging(newItem, [newValue], relations[key]!, schema);
+				}
+
+				continue;
+			}
+
+			const alterations = newValue as Alterations;
+			const related_collection = relations[key]!;
```
Comment (rijkvanzanten) [inline api/src/utils/merge-version-data.ts:83]: Lets stick to camelCase

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Code generally LGTM!

**Review by rijkvanzanten — APPROVED** [review]
🐿️ shipit
