### PR TITLE
Fix logic to update parent bundles enabled status

### LINKED ISSUE #22569: Bundle extension labels as enabled when all nested packages are disabled
### Describe the Improvement

Bundle extensions label as `enabled` when all their nested packages are disabled.

image

However, when a nested package is enabled, it's labelled as `partially enabled`.

image

Perhaps the parent bundle extension's enabled status should be updated when a nested package is enabled and disabled. 🤔

### PR DESCRIPTION
**Pull request by licitdev**
## Scope

What's changed:

- Renamed `bundleId` to `extensionId` for increased clarity between extension IDs.
- Fixed logic to update parent bundles enabled status

https://github.com/directus/directus/assets/26413686/43fa3dac-59c4-4ebe-b2cd-877dfe243d33

## Potential Risks / Drawbacks

- None that I am aware of

## Review Notes / Questions

- Nil

---

Fixes #22569

### CODE REVIEW

File: api/src/services/extensions.ts [hunk 1]
```diff
@@ -245,18 +245,19 @@ export class ExtensionsService {
...
-				.where({ bundle: bundleId })
-				.orWhere({ id: bundleId });
+				.where({ bundle: extensionId })
+				.orWhere({ id: extensionId });
 
 			return;
 		}
 
-		const parent = await this.readOne(bundleId);
+		const parentId = extension.bundle ?? extensionId;
```
Comment (paescuj) [inline api/src/services/extensions.ts:259]: What is this fallback to `extensionId` for?

Comment (licitdev) [reply api/src/services/extensions.ts]: Ah yes, it should be `extension.meta.bundle`. 🙈 
Added the fallback just in case. 

Further processing will be skipped if `parentId` is `null`. 
It's patched via https://github.com/directus/directus/pull/22587/commits/5fd3a5b19cd9ed71db0fb3321aa134122a9ce5b2.

Comment (paescuj) [reply api/src/services/extensions.ts]: Perfect 🚀❤️

**Review by paescuj — APPROVED** [review]
