### PR TITLE
Fix the system theme overrides interface color rules to refresh on external changes

### LINKED ISSUE #20126: Colors in system theme overrides interface not refreshed with external settings changes
### Describe the Bug

The colours in system theme overrides interface is not refreshed when project color / custom CSS in project settings is updated.

https://github.com/directus/directus/assets/26413686/2827b3e3-d0ba-4ace-83d3-5010bc8e9848

### To Reproduce

Change the project color / custom CSS, notice the colors not updated in the system theme overrides interface.

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Fixed colors in the system theme overrides interface not refreshing on external changes.
  - We now directly render var (that has a color rule) and color-mix instead of just the result.
- Rules that have color-mix now render a swatch properly.

https://github.com/directus/directus/assets/44623501/f2d3f61f-bfb1-4701-91e0-a64fb3c10a3e

## Potential Risks / Drawbacks

- None, this is the only location where this interface is used.

## Review Notes / Questions

- This seemed the optimal solution here, open to any suggestions. 
   - The issue here is that the value for the var function never changed although the result does. The cssVar function is not reactive from a vue perspective and therefor does not trigger a re-compute.
   - Rendering the functions directly seem to be an easy and ideal solution.

---

Fixes #20126

### CODE REVIEW

File: app/src/interfaces/_system/system-theme-overrides/system-theme-overrides-rule.vue [hunk 1]
```diff
@@ -33,6 +38,15 @@ const showSwatch = computed(() => {
 	if (!swatchValue.value) return false;
 
 	try {
+		if (swatchValue.value.startsWith('var(--') || swatchValue.value.startsWith('color-mix(')) {
+			/**
```
Comment (paescuj) [inline app/src/interfaces/_system/system-theme-overrides/system-theme-overrides-rule.vue:42]:
```suggestion
			/*
```

**Review by paescuj — APPROVED** [review]
