### PR TITLE
Fix md editor being empty when editing existing value

### LINKED ISSUE #6730: Field is always deleted automatically
### Describe the Bug

Hello, I have had the bug for a long time (in version RC.81) that when I go to an item that has several "text" fields, the lower one is always deleted. Has the problem been solved in the newer versions? Is that a bug? And when it is solved in the newer versions, I also asked a question how I can update the whole thing: https://github.com/directus/directus/discussions/6728

I hope someone can help me because it's a very annoying bug and I also have newbies who can't handle it.

### To Reproduce

I'm sorry, I don't know exactly how to explain this in writing, but I just made a video that should explain everything:
https://vimeo.com/572959730

### What version of Directus are you using?

v9.0.0-RC.81

### What version of Node.js are you using?

10.24.0

### What database are you using?

Postgres 13.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by nickrum**
This is the same fix I applied a while ago to the code interface.

Fixes #6730

### CODE REVIEW

File: app/src/interfaces/input-rich-text-md/input-rich-text-md.vue [hunk 1]
```diff
@@ -206,12 +206,12 @@ export default defineComponent({
...
-				codemirror.on('change', (cm) => {
+				codemirror.on('change', (cm, { origin }) => {
+					if (origin === 'setValue') return;
+
 					const content = cm.getValue();
 
-					if (content !== props.value && (props.value === null && content === '') === false) {
-						emit('input', content);
-					}
+					emit('input', content);
```
Comment (rijkvanzanten) [inline app/src/interfaces/input-rich-text-md/input-rich-text-md.vue:214]: We'll have to double check what happens when `content == ''` and `props.value == null`. That cumbersome check was to make sure that the interface wouldn't stage an empty change on first load 🤔

Comment (nickrum) [reply app/src/interfaces/input-rich-text-md/input-rich-text-md.vue:214]: Shouldn't that only happen if codemirrors value is set manually by using 'setValue()'?

Comment (rijkvanzanten) [reply app/src/interfaces/input-rich-text-md/input-rich-text-md.vue:214]: Yeah! Just my PTSD from TinyMCE / codemirror kicking in

**Review by rijkvanzanten — APPROVED** [review]
