### PR TITLE
Default values ignored for validations affected by conditions

### LINKED ISSUE #13649: Conditions on fields ignore default values on targeted field
### Describe the Bug

Conditions on fields are not working properly when the field specified in the rule field has a default value.

I configured a Radio field with two possible values and a default one
Then configure two additional **required** fields with a condition that set one of the two fields as non required based on the value of the radio field.
Even if the radio has a default value, the conditions are never met as if the radio field value was null.
Only after changing the value of the radio field the conditions start working as expected.

### To Reproduce

1. Create a new collection
2. Create a Radio field named "condition" with choices:
    *   value1
    *   value2
3. Set default value to value1
    
image

4. Create two input fields and set them as required
image
5. Go to input1 field and add a new Condition that set the field as Hidden and Non required when the field condition is Equals to value2
image
6. Go to input2 field and add a new Condition that set the field as Hidden and Non required when the field condition is Equals to value1
image
7. Save and create a new item (condition should be set to value1 by default)
8. Leave input1 empty and click on save -> WRONG both input1 and input2 are marked as required
image
9. Select condition = value2
10. Leave input2 empty and click on save -> only input2 is marked as required (as expected)
image

### Errors Shown

_No response_

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

12.20.0

### What database are you using?

SQLite, Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

locally, Docker

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

When validating content on save only the internal `item` (which is always empty for new items) and `edits` (which is also empty if nothing has been edited yet) are used to validate the item resulting in validation errors when saving an unedited new item.
The chosen solution is to add the default values logic used in `v-form` to the validation of items on save.

Fixes #13649

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [X] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by azrikahar — CHANGES_REQUESTED** [review]
Works great! 

Coincidentally the `validateItem()` change reminded me of #15245 as I thought that PR also touched the same piece of code, but turns out it isn't as that's `drawer-item`, not `use-item`. 

However that does unintentionally bring up that we will need to add this fix to the `validateItem()` in drawer-item as well, since the reported issue still happens in drawer-item:

https://user-images.githubusercontent.com/42867097/187389989-595a5cc3-80db-40d9-8bd2-bf2e2d87fff7.mp4

File: app/src/utils/get-default-values-from-fields.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+			if (
+				field.schema?.default_value !== undefined &&
+				// Ignore autoincremented integer PK field
+				!(
+					field.schema.is_primary_key &&
+					field.schema.data_type === 'integer' &&
+					typeof field.schema.default_value === 'string'
+				)
+			) {
+				acc[field.field] = field.schema.default_value;
```
Comment (azrikahar) [inline app/src/utils/get-default-values-from-fields.ts:16]: wondered about the original redundant optional chaining of `field.schema?.default_value` in v-form when looking at it again, but you're already one step ahead 😆

**Review by azrikahar — APPROVED** [review]
LGTM!
