### PR TITLE
Fix token manipulation on alignment change in images

### LINKED ISSUE #10145: wysiwyg alignment changes access_token
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using the 'align left' 'align right' 'align center' 'align justify' formatting options on an image inside a wysiwyg field - setting anything other than what it was originally imported into the field as causes the default access_token (which has been set in the interface) to become an automatically generated token.

**1. Importing an image / publishing etc:**

 
**2. Leaving the import alone - notice the access_token is what I've set it to be in the interface "web-app-public-token":**

**3. Centering the image and then publishing etc:**

**4. Notice how the centered image uses a completely random token.** 

**5. If you move the image back to the alignment option it had when it was first imported, it starts using the token set in the interface again.** 

### To Reproduce

1. Create a brand new database and directus instance.
2. Create a collection with a wysiwyg field.
3. Take steps listed above - set the innerHtml somewhere in a client or use postman etc to see it.

### Errors Shown

After some time (15 mins?) 'unauthorised' when trying to render the wysiwyg content if it does not have the access_token set to what has been set in the interface. 

### What version of Directus are you using?

Latest / 9.1.2 / Docker (9.0.1?)

### What version of Node.js are you using?

LTS & latest

### What database are you using?

Postgres & MySQL

### What browser are you using?

Chrome, Firefox, Brave (completely stock - incognito - no extensions etc)

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Locally & Docker (not at the same time)

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Fixes #10145

### CODE REVIEW

File: app/src/interfaces/input-rich-text-html/input-rich-text-html.vue [hunk 1]
```diff
@@ -271,7 +271,7 @@ export default defineComponent({
 		const replaceTokens = (value: string, token: string | null) => {
 			const url = getPublicURL();
 			const regex = new RegExp(
-				`(<[^=]+=")(${escapeRegExp(
+				`(<[^.]+=")(${escapeRegExp(
```
Comment (nickrum) [inline app/src/interfaces/input-rich-text-html/input-rich-text-html.vue:274]:
```suggestion
				`(<[^]*?=")(${escapeRegExp(
```

**Review by nickrum — CHANGES_REQUESTED** [review]

**Review by nickrum — APPROVED** [review]
