### PR TITLE
Fix Color Select Interface

### LINKED ISSUE #21409: Dropdown: Status, Default Configuration Error
### Describe the Bug

With Color Match theme, Have not tested with others yet.
`Background Color` has an unexpected value on the display configuration
image

### To Reproduce

1. Create a new Collection
2. Select the default Field "status"
3. Configure the display

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #23441: V-Color select interface doesn't support CSS-Variables
### Describe the Bug

When trying to setting a css-variable in the color-interface it shows an error in the interface:
 
Bildschirmfoto 2024-08-21 um 17 53 44

### To Reproduce

1. Click: edit raw value
2. Insert a css variable, e.g `var(--v-list-item-color-active)`
3. Save

**Result:** 
The css variable is used, but the interface is broken. 

**Possible solution:**
Add a third mode: 'css variable' to the interface, which is stored as string. This would also allow to insert the variable through the nterface (instead going through the `Edit raw`-approach)

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by connorwinston**
## Scope

For the purposes of this PR description "input"/"input value" refers to the color interface's text input field and "raw value" refers to the actual string value saved to the database or entered via the raw value modal.

What's changed:

- Typing/Pasting into the input a [valid color string](https://github.com/Qix-/color-string) will now parse the string to a HEX as the raw value.
- Typing/Pasting into the input a CSS Variable will now save the CSS Variable and save the CSS Variable as the raw value. The CSS Variable will show in the input now, not a HEX like the previous behavior. If the CSS Variable is not able to be parsed to a Javascript color, the input value will still be saved to the raw value AND it will still show the color in the swatch, however, the internal color will be null which means the dropdown color selector and HTML color picker will show the color black instead of being preloaded with the color of a CSS Variable it CAN parse. A CSS Variable that has valid syntax BUT is not defined in the styles available to the interface will show an _empty_ swatch.
- Typing/Pasting into the input a _invalid_ [color string](https://github.com/Qix-/color-string) or _invalid_ CSS Variable will emit the invalid value to the raw value, however, a "?" icon will now show in the swatch. Previous behavior was that you just couldn't type and it would silently delete anything you type that was invalid.
- Setting/Loading the raw value as a [valid color string](https://github.com/Qix-/color-string) will show this color string raw value as the input value. However, making a change to this in the input OR dropdown OR HTML Color Pick will convert it to a HEX value
- Fixed visual artifacts for transparent colors.

_Note the picture below shows how different raw values are presented, NOT input values as described above._
Frame 2

---

Fixes #23441 , Fixes #21409 , Closes #23452

### CODE REVIEW

File: app/src/interfaces/select-color/select-color.vue [hunk 1]
```diff
@@ -64,9 +64,19 @@ const props = withDefaults(defineProps<Props>(), {
 
 const emit = defineEmits(['input']);
 
+const validateVarSyntax = (input: string): boolean =>
```
Comment (rijkvanzanten) [inline app/src/interfaces/select-color/select-color.vue:67]: Can we move this to a separate util function file and add a unit test?

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
