### PR TITLE
Sort is set to NULL for new items

### LINKED ISSUE #11430: Sort is set to NULL for new items. Hence the manual order is not kept.
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After creating a new item, the Sort field is Null.
Therefore, after moving the item to another line, the order is not registered.

### To Reproduce

1. In a Collection with Sort field, add 3 items and set the order to Manual
2. Create a new item and save it.
3. Move that item to another row.
4. Go to another collection and come back to the sorted collection
5. BUG: The item you created is not at the right place

### Errors Shown

The item you created is not at the right place.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

A combination of  PR's #14689 and #12506 in an attempt to solve this problem both in the App making sure the sort value is sent in the same way it's represented in the app and on the API as fallback in case the sort field is required or non-nullable but not directly provided (only covers the creation of a new item with sort not updating).

Closes #11430

There have been other reports of the same issue (https://github.com/directus/directus/issues/4280 for M2A, https://github.com/directus/directus/issues/10657 for O2M, https://github.com/directus/directus/issues/6111 for M2M) which have been addressed in individual PRs addressing a specific relationship type (https://github.com/directus/directus/pull/4294 M2A, https://github.com/directus/directus/pull/10703 for M2M). Since then the issue reappeared and more fixes were suggested (https://github.com/directus/directus/pull/9832, and recently https://github.com/directus/directus/pull/12506).

**Most credit still goes to the original authors:**
@andrenarchy
@scolastico

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: app/src/composables/use-relation-multiple.ts [hunk 1]
```diff
@@ -196,8 +218,19 @@ export function useRelationMultiple(
 		return { create, update, remove, select, clear };
 
 		function create(...items: Record<string, any>[]) {
+			const sortField = relation.value?.sortField;
+
 			for (const item of items) {
-				target.value.create.push(cleanItem(item));
+				target.value.create.push(
+					cleanItem(
+						sortField && (item[sortField] === undefined || item[sortField] === null)
```
Comment (Nitwel) [inline app/src/composables/use-relation-multiple.ts:226]: `isNil` from lodash does the same as `item[sortField] === undefined || item[sortField] === null`  and is a bit cleaner.

**Review by Nitwel — CHANGES_REQUESTED** [review]
I'm wondering if it would make more sense to have this fix implemented on the api side only?

**Comment by br41nslug** [comment]
> I'm wondering if it would make more sense to have this fix implemented on the api side only?

We did consider that but with the create/update/delete format we weren't sure we could always tell what order it had in the App when reaching the API 😬 for instance consider this m2m payload:
```
{
  "create": [
    { related: { text: "abc" } },
    { related: { text: "123" } },
  ],
  "update": [
    { id: 11, related: { text: "def" } },
    { id: 11, related: { text: "456" } },
  ],
  "delete": [
     42
  ]
}
```

**Comment by Nitwel** [comment]
Pretty simple I would say as:

1. Newly created items go on the end of the array if they have no sort value set.
2. Updated items either already have a sort value or are also inserted at the end in case that they are newly selected.
3. We don't need to care about sort values of deleted items.

Then we just have to make sure that the interfaces asways display created items either before of after the updated ones. But that should be fairly easy if we are not doing this already.

File: app/src/composables/use-relation-multiple.ts [hunk 2]
```diff
@@ -30,6 +30,14 @@ export type ChangesItem = {
 	delete: (string | number)[];
 };
 
+function getSortMax(...values: (number | null)[]) {
+	return values.reduce<null | number>((max, v) => {
+		if (max === null) return v;
+		if (v === null) return max;
+		return Math.max(max, v);
+	}, null);
+}
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply app/src/composables/use-relation-multiple.ts:39]: Does the lodash max function do anything better than the `Math.max` one? I can't imagine there is much improvement to be gotten in the comparison of 2 values unless im missing something 🤔 For arrays of unknown lengths i suppose lodash would be more efficient

**Comment by br41nslug** [comment]
> Newly created items go on the end of the array if they have no sort value set.
Thats what they do by default but you can still sort it on the frontend before saving so adding the App logic to insert that the sort field/value is not something we can avoid i think.

File: app/src/composables/use-relation-multiple.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts:39]: Even better, we wan just use `Math.max` as it also supports an array of elements: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Math/max

[the remark this answers is not in the document]
Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts:39]: And it's not about speed but code redundancy and readability. 😄

**Comment by Nitwel** [comment]
In the case of someone sorting newly created items, we automatically set the sort value, see here: https://github.com/directus/directus/blob/5e8137367b7f28eac90c4d493049845497c0bf41/app/src/interfaces/list-m2m/list-m2m.vue#L430-L439

**Comment by br41nslug** [comment]
True the sorting was fixed for several relational interfaces separately in various PRs. Solving this at the `useRelationMultiple` level to catch all relational interfaces with multiple items does have my preference. I'll do some new testing to see if this same problem was also fixed for the O2M and M2A (i thought one was still problematic but not 💯% sure there) if so then this solution can indeed just be on the API side and we can leave the `useRelationMultiple` logic as an improvement/refactor for later.

**Comment by azrikahar** [comment]
> In the case of someone sorting newly created items, we automatically set the sort value, see here:
> 
> https://github.com/directus/directus/blob/5e8137367b7f28eac90c4d493049845497c0bf41/app/src/interfaces/list-m2m/list-m2m.vue#L430-L439

Just noticed this does mean the sort number will start with 0 upon reordering. Do we want, or should we, make it start with 1 instead? 🤔 Feels like an inane question but just curious.

**Comment by scolastico** [comment]
Big thank you from me for taking this! <3

**Comment by Nitwel** [comment]
I don't think it matters if we start at 0 or 1 but feel free to prove me wrong. The only reason I could think of is for consistency if other parts of directus also let sort start at 1.

**Comment by br41nslug** [comment]
Historically i would choose for sorting to start at 1 because of the old javascript double not construction `if ( !! sortValue) // do some sorting` but that's not really a good argument anymore in modern typescript 🤔

**Comment by azrikahar** [comment]
Currently it seems to start with 1 when creating new items, then after reordering it becomes starting with 0, so I do think we may need to make it consistent at least:

https://user-images.githubusercontent.com/42867097/187187817-81a45ddf-78b6-4db0-a238-01d43146405c.mp4

---

I've also just realized the app side sort is not accounting for bulk add existings, and turn all of them with the same sort number:

https://user-images.githubusercontent.com/42867097/187188191-82bc1acd-6efb-45f4-af77-242b819cbb89.mp4

**Comment by azrikahar** [comment]
> Currently it seems to start with 1 when creating new items, then after reordering it becomes starting with 0

> I've also just realized the app side sort is not accounting for bulk add existings, and turn all of them with the same sort number

Both of these should be resolved now 👍 (opted to unify the sort number to start at 1 after reordering)

**Review by licitdev — APPROVED** [review]
Works well to resolve the issue! 👍 

Here are two observations that may be addressed in the future PR.

1. The sort value when adding existing values may result in duplicated sort values. Also, the "newly" added existing items may be distributed within the list. 
    1. I feel that all newly added items to the list should be added to the bottom for consistency with the new item UX.

2. After sorting, the entire list is being sent for update even when the sort value remains the same. This issue exists on the main branch. 
    1. I believe o2m items that do not have an updated sort value should not be included within the update request.

**Comment by rijkvanzanten** [comment]
@Nitwel Mind reviewing this?

**Review by azrikahar — APPROVED** [review]
Apart from the points above, I do still also wonder can/should we optimize the `highestOrderNumber` in the API, as that query is currently running for each created items instead of once in the beginning. Made an attempt at that in https://github.com/directus/directus/pull/15241/commits/b37ed207f30be065cbbb9e92e6bd841a7fc86769 previously, but it was incomplete and a faulty abstraction thus it was reverted. 

With that said, this PR should achieve the primary goal of sorting newly created items (excluding adding existing ones as mentioned). 👍

File: api/src/services/payload.ts [hunk 3]
```diff
@@ -670,17 +670,38 @@ export class PayloadService {
...
+
+						// add sort field value if it is not supplied in the item
+						if (sortField !== null && parent !== null && record[sortField] === undefined) {
+							const highestOrderNumber: Record<string, any> | undefined = await this.knex
+								.select(sortField)
+								.from(relation.collection)
+								.where({ [relation.field]: parent })
+								.whereNotNull(sortField)
+								.orderBy(sortField, 'desc')
+								.first();
```
Comment (rijkvanzanten) [inline api/src/services/payload.ts:686]: This does a new SQL query for every item in the create array, that's a pretty large amount of overhead. We should instead fetch the current highest value from the DB once, and keep incrementing in JS when looping over instead.

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/services/payload.ts [hunk 4]
```diff
@@ -672,31 +672,39 @@ export class PayloadService {
...
+					let createPayload: Alterations['create'];
+
+					if (sortField !== null) {
+						const highestOrderNumber: Record<string, any> | undefined = await this.knex
+							.select(sortField)
+							.from(relation.collection)
+							.where({ [relation.field]: parent })
+							.whereNotNull(sortField)
+							.orderBy(sortField, 'desc')
+							.first();
```
Comment (rijkvanzanten) [inline api/src/services/payload.ts:684]: Lets use `.max()` instead of order by + limit 1 (first). Even though the difference is tiny, it is technically faster 🙂 (and imo also a little easier to read, as it's more explicit)

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/services/payload.ts (hunk 3 above)
Comment (azrikahar) [reply api/src/services/payload.ts]: implemented 👍

File: api/src/services/payload.ts (hunk 4 above)
Comment (azrikahar) [reply api/src/services/payload.ts]: Using `.max()` now 👍

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@Nitwel You happy with the current state of this PR? 🚀

**Comment by younky-yang** [comment]
Hi, Just encounter an issue with this change, with the M2M relation, if the sort field type is not a number, for example in my case it is a uuid, the line in /api/src/services/payload.ts below will through an error. 
``` typescript
const highestOrderNumber: Record<'max', number | null> | undefined = await this.knex
	.from(relation.collection)
	.where({ [relation.field]: parent })
	.whereNotNull(sortField)
	.max(sortField, { as: 'max' })
	.first();						
```
So to solve this, we can't assume that user always use number as the sort field, especially if they didn't specify the sort field, but their pk of collection is uuid.  I assume the change can be solved with below changes, 
``` typescript
const highestOrderNumber: Record<'max', number | string | null> | undefined = await this.knex
	.from(relation.collection)
	.where({ [relation.field]: parent })
	.whereNotNull(sortField)
	.select(`${sortField} as max`)
	.orderBy(sortField, 'desc')
	.first();

createPayload = alterations.create.map((item, index) => {
	const record = cloneDeep(item);

	// add sort field value if it is not supplied in the item
	if (parent !== null && record[sortField] === undefined) {
		if (typeof highestOrderNumber?.max === 'string') {
			record[sortField] = uuid();
		} else {
			record[sortField] = highestOrderNumber?.max ? highestOrderNumber.max + index + 0 : index + 1;
		}
	}
```

I just did  a very simple test with my own case, and looks it works, but need further investigation on this one. Please share your thoughts.

**Comment by rijkvanzanten** [comment]
@younky-yang The `sort` field is required to be a numeric type. The app shouldn't allow you to select a non-numeric value either.
