### PR TITLE
Replace `node-schedule` with `cron`

### LINKED ISSUE #25855: API: Schedule Flow not being triggered after some time running
### Describe the Bug

We have a Flow set to run every day at 23h (0 23 * * *) and for the last X days this Flow is being running as intended.
Although now it stopped and we cannot see it running anymore.
We haven't change anything so not sure what happened.
After restarting the project the Flow started running as intended again.

This seems to be a an issue with long running Scheduled Flows.
More specifically, it looks like `node-schedule`  may stop working when running for long time:
https://github.com/node-schedule/node-schedule/issues/494
https://github.com/node-schedule/node-schedule/issues/614

I have tried to create a Flow running every second (`* * * * *`) for about 40minutes and it ran as expected.
This seems to be tied for how long it is running. Maybe a tiny shift that is only noticeable after some days running.
Some people mentioned about 25 days:
https://github.com/node-schedule/node-schedule/issues/516

Also the project `node-schedule` seems to be abandoned, so maybe we could use `node-cron` 🤔

### To Reproduce

- Create a Schedule Flow to run daily
- Wait around 25 days
- Verify Flow does not run anymore

### Directus Version

v11.11.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres

### PR DESCRIPTION
**Pull request by gaetansenn**
## Scope

What's changed:
- Replaced `node-schedule` with `node-cron` (cron package) library to fix the 25-day execution bug in scheduled flows
- Updated scheduling utilities to use native validateCronExpression from the cron package
- Improved timezone handling by leveraging the cron package's built-in support for TZ environment variable
- Updated test mocks to properly handle the new cron package API
- Cleaned up dependencies by removing node-schedule and @types/node-schedule from package catalogs

## Potential Risks / Drawbacks
- Dependency change introduces a new external library, though it's widely used and actively maintained
- Runtime behavior changes in edge cases due to different internal implementations between libraries
- Potential timing differences in cron execution, though this should be minimal and within acceptable ranges

## Tested Scenarios
- Existing scheduled flows continue to work with the same cron expressions (`0 23 * * *`, etc.)
- Multi-instance coordination still functions correctly via SynchronizedClock mechanism
- Timezone handling respects system TZ environment variable as expected
- Cron validation properly rejects invalid expressions and accepts valid ones
- Metrics scheduling continues to work with the updated implementation

## Review Notes / Questions
- Long-term reliability: The cron package is actively maintained and has no known long-running issues
- Performance impact: Should be minimal as both libraries have similar overhead
- Migration strategy: No data migration needed as this only affects in-memory scheduling
- Backward compatibility: All existing cron expressions remain valid and functional

## Checklist

- [X] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25855
Docs PR: https://github.com/directus/docs/pull/486

### CODE REVIEW

**Comment by ComfortablyCoding** [comment]
> Replaced node-schedule with node-cron (cron package) library to fix the 25-day execution bug in scheduled flows

Has this been confirmed or documented as fixed in `node-cron`?

**Comment by gaetansenn** [comment]
> > Replaced node-schedule with node-cron (cron package) library to fix the 25-day execution bug in scheduled flows
> 
> Has this been confirmed or documented as fixed in `node-cron`?

No, there isn't explicit documentation confirming that the 25-day bug has been tested and fixed in the cron package (`kelektiv/node-cron`). However, the migration is justified by several technical and maintenance factors:
- Different timer architecture: The cron package uses `Luxon DateTime` for time calculations instead of internal Node.js timers, which should be more robust for long-running schedules
- No similar issues reported: I couldn't find any GitHub issues in the `kelektiv/node-cron` repository reporting long-running job failures or memory leaks

**Comment by br41nslug** [comment]
How can we test this fix without waiting 25days to verify this new package actually resolves the issue?

**Comment by gaetansenn** [comment]
> How can we test this fix without waiting 25days to verify this new package actually resolves the issue?

Unfortunately, as the bug was present in the `node-schedule` and was probably because of the node internal timer, as the `node-cron` is now using Luxon for the timing schedule job, the only way to test it is to wait for 25 days or maybe just re-open / create an issue if the problem persists

**Comment by ComfortablyCoding** [comment]
> Unfortunately, as the bug was present in the node-schedule and was probably because of the node internal timer, as the node-cron is now using Luxon for the timing schedule job, the only way to test it is to wait for 25 days or maybe just re-open / create an issue if the problem persists

Although it uses `luxon` to determine the execution date/time, it still appears to rely on `setTimeout` for scheduling same as node-schedule. Since the problem wasn’t with execution accuracy but rather the execution stopping, I suspect the same issue could occur here as well. However, without a way to test it we cannot confirm it is fixed.

**Comment by AlexGaillard** [comment]
@gaetansenn to attempt to write a test that fails on the old implementation

**Comment by AlexGaillard** [comment]
@gaetansenn [docs page for cron](https://directus.io/docs/guides/automate/triggers#schedule-cron) points to node-schedule. Will need to open a PR to adjust that link to point at the [node-cron equivalent](https://github.com/kelektiv/node-cron?tab=readme-ov-file#-cron-patterns).

Line in question can be found [here](https://github.com/directus/docs/blob/f8a179f49c62bface397a2468d4a1eb14e0d3895/content/guides/06.automate/3.triggers.md?plain=1#L98).

File: api/src/schedules/metrics.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export default async function schedule(): Promise<boolean> {
 		return false;
 	}
 
-	scheduleJob('metrics', String(env['METRICS_SCHEDULE']), handleMetricsJob);
+	new CronJob(String(env['METRICS_SCHEDULE']), handleMetricsJob, null, true);
```
Comment (AlexGaillard) [inline api/src/schedules/metrics.ts]: Can we make it explicit as to what the `null` `true` params are?

According to the docs they're `onComplete` callback and `start`.

We should prob save them as const's to be more specific or doc what they are.

File: api/src/utils/schedule.test.ts
Comment (AlexGaillard) [inline api/src/utils/schedule.test.ts:1]: I know you've mocked out CronJob here, but can we add a test with mock timers and an unmocked function to ensure that this actually runs after a set time, something like:

```
	test('cron job fires at scheduled time', async () => {
		vi.useFakeTimers();

		const mockCallback = vi.fn();

		new CronJob('0 0 * * *', mockCallback, null, true);

		await vi.advanceTimersByTimeAsync(24 * 60 * 60 * 1000);

		expect(mockCallback).toHaveBeenCalledTimes(1);

		vi.useRealTimers();
	});
```

File: api/src/utils/schedule.ts [hunk 2]
```diff
@@ -23,21 +18,25 @@ export function scheduleSynchronizedJob(
...
 
-	const job = schedule.scheduleJob(rule, async (fireDate) => {
-		const nextInvocation = job.nextInvocation();
-		if (!nextInvocation) return;
+	const job = new CronJob(
+		rule,
+		async (fireDate: Date) => {
+			// Get next execution time for synchronization
+			const nextDate = job.nextDate();
+			const nextTimestamp = nextDate.toMillis();
```
Comment (AlexGaillard) [inline api/src/utils/schedule.ts:24]: FWIW I tested this against `node-schedule`'s `.getTime()` with the rule '0 0 * * *' and both return the same value `1760760000000` 👍

File: api/src/utils/schedule.ts [hunk 3]
```diff
@@ -23,21 +18,25 @@ export function scheduleSynchronizedJob(
...
-
-		if (wasSet) {
-			await cb(fireDate);
-		}
-	});
+			if (wasSet) {
+				await cb(fireDate);
+			}
+		},
+		null,
```
Comment (AlexGaillard) [inline api/src/utils/schedule.ts]: Same comment regarding `null` and `true` applies here

**Review by AlexGaillard — DISMISSED** [review]
Nice work @gaetansenn. Just some small suggestions here. Functionally this seems to work the same.

File: api/src/schedules/metrics.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply api/src/schedules/metrics.ts]: On that note, it might be worth to use the equivalent `CronJob.from` method which accepts an object with optional params

File: api/src/utils/schedule.ts (hunk 3 above)
Comment (ComfortablyCoding) [reply api/src/utils/schedule.ts]: See https://github.com/directus/directus/pull/25874#discussion_r2437424392

**Comment by gaetansenn** [comment]
I’ve created a pull request for the document update: https://github.com/directus/docs/pull/486

File: .changeset/replace-node-schedule-with-cron.md [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+Addresses an issue where scheduled flows would stop executing after approximately 25 days due to a known bug in the node-schedule library. The replacement uses the actively maintained 'cron' package from kelektiv/node-cron which provides better long-term reliability, active maintenance, and improved timezone handling.
+
+**Key improvements:**
+- Addresses the 25-day execution bug reported in node-schedule
+- Better timezone support (respects TZ environment variable)
+- Uses native validation functions from the cron package
+- Maintains existing SynchronizedClock mechanism for multi-instance coordination
+- Preserves all existing cron expression formats and functionality
+
+**Breaking changes:** None - this is a drop-in replacement that maintains full backward compatibility.
```
Comment (ComfortablyCoding) [inline .changeset/replace-node-schedule-with-cron.md]:
```suggestion
Replaced `node-schedule` with `cron`
```

Comment (AlexGaillard) [reply .changeset/replace-node-schedule-with-cron.md]: Yeah seconded here, these can be simpler to fit into a big list with the other changesets in the release notes :)

File: api/src/utils/schedule.ts [hunk 5]
```diff
@@ -1,19 +1,14 @@
...
 export function validateCron(rule: string): boolean {
-	try {
-		cron.parseExpression(rule);
-	} catch {
-		return false;
-	}
+	const validation = validateCronExpression(rule);
 
-	return true;
+	return validation.valid;
```
Comment (ComfortablyCoding) [inline api/src/utils/schedule.ts]: As we are not doing any additional checks we should be able to simplify this to the following
```suggestion
	return validateCronExpression(rule).valid;
```

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀

**Comment by AlexGaillard** [comment]
Seems we maybe have a broken test? 🤔
