### PR TITLE
[SDK] Added "_icontains" string operator

### LINKED ISSUE #22249: SDK - Missing _icontains operator in types
### Describe the Bug

Hi, I'm trying to use the **_icontains** operator, but it returns a typscript error because it doesn't exist.
However, you can send the request ignoring the typescript error and it works correctly.

image

### To Reproduce

```ts
 const data = await client.request(
    aggregate("cars_inventory", {
      query: {
        filter: {
          _and: matches.map((match) => ({
            excerpt: {
              _icontains: match,
            },
          })),
        },
        limit: 5,
      },
      aggregate: { count: "*" },
      groupBy: ["maker", "model", "trim", "year"],
    }),
  );
```

### Directus Version

^15.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #22249 

## Scope

What's changed:

- Added the `_icontains` string operator

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- I would like to lorem ipsum

### CODE REVIEW

File: sdk/src/types/filters.ts [hunk 1]
```diff
@@ -58,6 +58,7 @@ export type FilterOperators<
 	_nbetween: IsDateTime<FieldType, [T, T], IsNumber<T, [T, T], never>>;
 	_contains: IsDateTime<FieldType, never, IsString<T, string, never>>;
 	_ncontains: IsDateTime<FieldType, never, IsString<T, string, never>>;
+	_icontains: IsDateTime<FieldType, never, IsString<T, string, never>>;
```
Comment (licitdev) [inline sdk/src/types/filters.ts:61]: Should we add the `_nicontains` operator?

```suggestion
	_icontains: IsDateTime<FieldType, never, IsString<T, string, never>>;
	_nicontains: IsDateTime<FieldType, never, IsString<T, string, never>>;
```

Comment (br41nslug) [reply sdk/src/types/filters.ts:61]: Currently `_nicontains` does not pass the filter validation this does not work on the API.
image

But good point lets pick that up in a separate issue.

Comment (paescuj) [reply sdk/src/types/filters.ts:61]: Was wondering the same 🤔 Though this one is not documented, right? So probably better to addressed that separately, including docs and potentially other implications.

**Review by paescuj — APPROVED** [review]

File: .changeset/rude-cougars-suffer.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@directus/sdk": patch
+---
+
+Added "_icontains" string operator to the SDK
```
Comment (hanneskuettner) [inline .changeset/rude-cougars-suffer.md:5]:
```suggestion
Added "_icontains" string operator to the SDK types
```

**Review by hanneskuettner — APPROVED** [review]

**Review by licitdev — APPROVED** [review]
🚀
