### PR TITLE
Ensure primary key field is auto-injected when absent from the fields array

### LINKED ISSUE #24956: Failure to add fields when POSTING field property within the collections endpoint
### Describe the Bug

When I POST the following payload to the collections endpoint I can see the Products collection has been created but it has no fields (not even id which I believe is created by default if no fields are provided):

```
{
  collection: 'Products',
  meta: { note: 'A collection of products' },
  schema: { schema: 'public', name: 'Products', comment: 'The product schema' },
  fields: [
    {
      collection: 'Products',
      field: 'code',
      type: 'string',
      meta: { interface: 'input', note: 'Product code' }
    },
    {
      collection: 'Products',
      field: 'name',
      type: 'string',
      meta: { interface: 'input', note: 'Product name' }
    },
    {
      collection: 'Products',
      field: 'description',
      type: 'string',
      meta: { interface: 'input', note: 'Product description' }
    }
  ]
}
```

I do not receive any error.  The status is 'OK'

### To Reproduce

    const productCollectionResponse = await fetch('http://localhost:8055/collections', {
        method: "POST",
        headers: {
            Authorization: "Bearer ****************************",
            "Content-Type": 'application/json',
        },
        body: JSON.stringify(productCollection),
    });

### Directus Version

v11.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- The primary key is now auto injected if a fields array is provided that does not contain the `set_primary_key:true` property

## Potential Risks / Drawbacks

- Should be none 🤔 

## Review Notes / Questions

- N/A

---

Fixes #24956

--- 

### Tested
- [x] Expect a primary key field to be automatically injected when creating a collection, if the `fields` array does not include `is_primary_key: true`
- [x] Expect a primary key field to NOT be automatically injected when creating a collection, if the `fields` array includes a field with `is_primary_key: true` 
- [x] Expect creating an empty collection (i.e. folder) should work as previous
- [x] Expect Bring Your Own Database (BYOD) table configuration to work as previous
- [x] Expect a primary key field to be automatically injected when creating a collection, if the `fields` array is empty or not present

### CODE REVIEW

File: api/src/services/collections.ts [hunk 1]
```diff
@@ -94,25 +94,30 @@ export class CollectionsService {
...
-									readonly: true,
-								},
-								schema: {
-									is_primary_key: true,
-									has_auto_increment: true,
-								},
-							},
-						];
+						payload.fields = [injectedPrimaryKeyField];
+					} else if (payload.fields.some((f) => f.schema?.is_primary_key === true) === false) {
```
Comment (licitdev) [inline api/src/services/collections.ts:119]:
```suggestion
					} else if (!payload.fields.some((f) => f.schema?.is_primary_key === true)) {
```

File: tests/blackbox/tests/db/routes/collections/crud.test.ts [hunk 2]
```diff
@@ -199,6 +199,171 @@ describe.each(PRIMARY_KEY_TYPES)('/collections', (pkType) => {
 				});
 			});
 
+			describe('Creates a new collection without any field', () => {
```
Comment (ComfortablyCoding) [inline tests/blackbox/tests/db/routes/collections/crud.test.ts:202]:
```suggestion
			describe('Creates a new collection with auto created primary key when empty schema is present', () => {
```

File: tests/blackbox/tests/db/routes/collections/crud.test.ts [hunk 3]
```diff
@@ -199,6 +199,171 @@ describe.each(PRIMARY_KEY_TYPES)('/collections', (pkType) => {
...
+								expect(await db.schema.hasColumn(TEST_COLLECTION_NAME, 'id')).toBe(true);
+							} else {
+								expect(response.statusCode).toBe(403);
+							}
+						});
+					});
+				});
+			});
+
+			describe('Creates a new collection auto creates primary key', () => {
```
Comment (ComfortablyCoding) [inline tests/blackbox/tests/db/routes/collections/crud.test.ts:240]:
```suggestion
			describe('Creates a new collection with auto created primary key when no primary key is in the fields array', () => {
```

File: tests/blackbox/tests/db/routes/collections/crud.test.ts [hunk 4]
```diff
@@ -199,6 +199,171 @@ describe.each(PRIMARY_KEY_TYPES)('/collections', (pkType) => {
...
+								expect(await db.schema.hasColumn(TEST_COLLECTION_NAME, 'id')).toBe(true);
+							} else {
+								expect(response.statusCode).toBe(403);
+							}
+						});
+					});
+				});
+			});
+
+			describe('Creates a new collection with fields including primary key', () => {
```
Comment (ComfortablyCoding) [inline tests/blackbox/tests/db/routes/collections/crud.test.ts:288]:
```suggestion
			describe('Creates a new collection with specified primary key in fields array', () => {
```

File: .changeset/famous-turtles-bow.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fixed primary key field was not auto injected when not present in fields array
```
Comment (licitdev) [inline .changeset/famous-turtles-bow.md:5]:
```suggestion
Ensured primary key field is auto-injected when absent from the fields array
```

**Review by licitdev — APPROVED** [review]
