### PR TITLE
Fix sorting of aggregated result

### LINKED ISSUE #23189: Sorting of aggregated result returns server error
### Describe the Bug

Sorting of aggregated queries was added in https://github.com/directus/directus/pull/19568 but it currently returns a server error. 

The aggregation works only if the sort query is removed.

`"You don't have permission to access field \"sum\" in collection \"v11_agg\" or it does not exist. Queried in root."`

`GET /items/v11_agg?aggregate[sum]=value&groupBy=type&sort[]=sum.value`

There's a pending documentation PR https://github.com/directus/directus/issues/21014 for this functionality.

### To Reproduce

Create a collection named `v11_agg` with a type (string) and value (integer) field.
Populate some records.
Perform a `GET /items/v11_agg?aggregate[sum]=value&groupBy=type&sort[]=sum.value`

### Directus Version

v11.rc3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

pg

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

The sorting based on aggregated fields needs to be handled in a special way.

When constructing the field map for permission checking we need to ignore all sort fields that are located in the scope of the aggregation, e.g. everything starting with `sum.` if there is a aggregate `sum` operation. 
The correct fields still show up in the field map because they are extracted from the aggregate query. 

What's changed:

- Ignore aggregated fields showing up in sort when constructing field map

## Potential Risks / Drawbacks

- N/A

## Review Notes / Questions

- N/A
---

Fixes #23189

### CODE REVIEW

File: api/src/permissions/modules/process-ast/utils/extract-paths-from-query.ts [hunk 1]
```diff
@@ -29,7 +29,16 @@ export function extractPathsFromQuery(query: Query) {
 		for (const field of query.sort) {
 			// Sort can have dot notation fields for sorting on m2o values Sort fields can start with
 			// `-` to indicate descending order, which should be dropped for permissions checks
-			readOnlyPaths.push(field.split('.').map((field) => (field.startsWith('-') ? field.substring(1) : field)));
+
+			const parts = field.split('.').map((field) => (field.startsWith('-') ? field.substring(1) : field));
+
+			if (query.aggregate && parts.length > 0 && parts[0]! in query.aggregate) {
+				// If query is an aggregate query and the first part is a requested aggregate operation ignore the whole field
```
Comment (paescuj) [inline api/src/permissions/modules/process-ast/utils/extract-paths-from-query.ts:36]:
```suggestion
				// If query is an aggregate query and the first part is a requested aggregate operation, ignore the whole field.
```

File: api/src/permissions/modules/process-ast/utils/extract-paths-from-query.ts [hunk 2]
```diff
@@ -29,7 +29,16 @@ export function extractPathsFromQuery(query: Query) {
...
+				// The correct field is extracted into the field map when procession the `query.aggregate` fields.
```
Comment (paescuj) [inline api/src/permissions/modules/process-ast/utils/extract-paths-from-query.ts:37]:
```suggestion
				// If query is an aggregate query and the first part is a requested aggregate operation, ignore the whole field.
				// The correct field is extracted into the field map when processing the `query.aggregate` fields.
```

**Review by paescuj — APPROVED** [review]
LGTM 🎸 The permission check still takes place via aggregation ✅
