### PR TITLE
Fix accounts with minimum access permissions unable to add 2fa

### LINKED ISSUE #25948: Unable to add 2FA to an account
### Describe the Bug

I am unable to add 2FA to a user but the 2FA implementation on my admin account from a while back works fine. I can login to it and it even asks for the verification code which is expected. When I try to add it to the new account it fails with the following error: `Invalid Payload. 'password' is required`. This is on the Directus Admin Panel

### To Reproduce

1. Create a non-admin account
2. Login to the account and try to enable 2FA.
3. It will log you out and ask you to login again
4. You'll get to the page asking if you want to enable 2FA.
5. Click yes, it shows the error "Invalid Payload. 'password' is required".
6. Go to the network tab and click on next again, you'll see a generate request being sent without any data in the request payload.

### Directus Version

v11.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

 pg16-v0.2.0

### PR DESCRIPTION
**Pull request by br41nslug**
## Scope

What's changed:

- Added `directus_users.provider` to the minimal app permissions

## Potential Risks / Drawbacks

- A migration against potentially a lot of policies

## Tested Scenarios

- [x] Expect user with minimum app access permissions to be able to enable 2fa
- [x] Expect provider is now auto merged and allowed for all users with minimum app access

## Review Notes / Questions

- I would like to lorem ipsum
- Special attention should be paid to dolor sit amet

----

Fixes #25948

### CODE REVIEW

**Review by ComfortablyCoding — COMMENTED** [review]
Should we accompany this with a migration? Existing policies will not be fixed by this change as they are persisted to the db.

File: api/src/database/migrations/20251105A-add-provider-access.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+			.select('directus_permissions.id', 'directus_permissions.fields')
+			.join('directus_policies', 'directus_policies.id', 'directus_permissions.policy')
+			.where('directus_policies.app_access', '=', 1)
+			.andWhere('directus_permissions.collection', '=', 'directus_users')
+			.andWhere('directus_permissions.action', '=', 'read')
+			.andWhereNot('directus_permissions.fields', 'LIKE', '*')
+			.limit(rowsLimit)
+			.offset(rowsOffset);
+
+		if (policies.length === 0) {
```
Comment (ComfortablyCoding) [inline api/src/database/migrations/20251105A-add-provider-access.ts]: We can further improve this by adding `|| policies.length < rowsLimit` and moving it under the for loop. This will reduce the loop by one ensuring we do query an extra time when we know we have reached the end of the line.

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
Upon re-review I do not believe a migration is necessary. We auto merge the app min permissions[^1][^2][^3] irrespective of whatever other rules are defined in the db.

[^1]:https://github.com/directus/directus/blob/d0800c54ef50fdf45ffc4d20a2d4a4e3b7b19803/api/src/permissions/lib/with-app-minimal-permissions.ts#L6
[^2]:https://github.com/directus/directus/blob/d0800c54ef50fdf45ffc4d20a2d4a4e3b7b19803/api/src/services/permissions.ts#L34
[^3]:https://github.com/directus/directus/blob/d0800c54ef50fdf45ffc4d20a2d4a4e3b7b19803/api/src/permissions/utils/fetch-raw-permissions.ts#L53

File: .changeset/empty-berries-behave.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/system-data': patch
+---
+
+Added directus_users provider field to minimum app permissions
```
Comment (ComfortablyCoding) [inline .changeset/empty-berries-behave.md]:
```suggestion
Fixed accounts with minimum access permissions unable to add 2fa
```

**Review by ComfortablyCoding — APPROVED** [review]
