### PR TITLE
Use correct status code (204) when no content is sent

### LINKED ISSUE #10558: Responses with not content are wrongly set to status Code 200
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

i stumpled upon this while using the okhttp library on android. it tries to parse the response body as json, which is not set. this is due to directus setting the http code to 200 even if no content is provided

### To Reproduce

i tried this with DELETE operation on REST for an item endpoint. it returns no content and thus should have status code 204 instead of 200.

### Errors Shown

_No response_

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.6.1

### What database are you using?

SQLITE

### What browser are you using?

FF

### What operating system are you using?

win64

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by eikaramba**
this is currently wrong for the DELETE Http Method in directus, which sends 200 status code although no content is served

Fixes https://github.com/directus/directus/issues/10558

### CODE REVIEW

File: api/src/middleware/respond.ts [hunk 1]
```diff
@@ -80,8 +80,10 @@ export const respond: RequestHandler = asyncHandler(async (req, res) => {
 
 	if (Buffer.isBuffer(res.locals.payload)) {
 		return res.end(res.locals.payload);
-	} else {
+	}else if(res.locals.payload){
```
Comment (rijkvanzanten) [inline api/src/middleware/respond.ts:83]:
```suggestion
	} else if (res.locals.payload) {
```

Comment (rijkvanzanten) [reply api/src/middleware/respond.ts:83]: I'm sure the linter will cry otherwise

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
