### PR TITLE
Fix formatted Kanban card text including HTML tags

### LINKED ISSUE #19065: Kanban layout cards only show raw values in the 'Card Text' field
### Describe the Bug

When using a WYSIWYG text field for the Kanban layout's 'Card Text', the card previews do not use the Display Formatted Value that is normally used in e.g. the Table layout. This results in the card text including HTML tags. If the field is a Markdown field instead, the text will include MD syntax etc. I have tried all kinds of different options for formatting the display value.

In a perfect world the value would be rendered as text with the applied formatting, but just making it readable (as the current Table view does) would be a fix to this problem.

An example of how the card text is displayed with a WYSIWYG field in the Kanban layout:
image

An example of how the same text is displayed in the Table layout:
image

The Display settings for the field:
image

You're doing a great job with Directus!

### To Reproduce

1. Create an empty Directus project
2. Create a collection (e.g. Tasks)
3. Set a WYSIWYG text field for the collection with a Display option of 'Formatted Value'
4. Go to the Tasks content page of directus, create an entry with some formatting in the WYSIWYG field
5. See the column in the Table layout and then switch to the Kanban layout and set the WYSIWYG field as the 'Card Text' to see the HTML tags in the card preview.

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by magnus-bb**
Fixes HTML tags rendering in Kanban card text of WYSIWYG fields described in #19065.

When setting a formatted display value for WYSIWYG fields...:
image
... the value should now be prettier on the Kanban card:
image

However, the HTML is not rendered on the card. The `<render-display>` component simply displays the raw values without any HTML tags.

Fixes #19065

### CODE REVIEW

File: app/src/layouts/kanban/kanban.vue [hunk 1]
```diff
@@ -53,7 +53,16 @@
...
+								<render-display
+									v-if="element.text && textFieldConfiguration"
+									:collection="collection"
+									:value="element.text"
+									:type="textFieldConfiguration.type"
+									:field="layoutOptions.textField"
+									:display="textFieldConfiguration.meta?.display"
+									:options="textFieldConfiguration.meta?.options"
+									:interface="textFieldConfiguration.meta?.interface"
+								/>
```
Comment (magnus-bb) [inline app/src/layouts/kanban/kanban.vue:65]: As per Rijk's suggestion on #19065, I used the `<render-display>` component in order to format the raw HTML string of WYSIWYG fields.

As far as I can tell, this was the most fitting component to use, but it does not seem to work for all types of text / string fields (e.g. markdown).

The `textFieldConfiguration` is explained below.

File: app/src/layouts/kanban/kanban.vue [hunk 2]
```diff
@@ -111,16 +120,17 @@ export default {
...
-import type { ChangeEvent, Group, Item } from './types';
+import type { ChangeEvent, Group, Item, LayoutOptions } from './types';
+import type { Field } from '@directus/types';
 
 const props = withDefaults(
 	defineProps<{
 		collection?: string | null;
 		groupCollection?: string | null;
-		fieldsInCollection?: Record<string, any>[];
+		fieldsInCollection?: Field[];
```
Comment (magnus-bb) [inline app/src/layouts/kanban/kanban.vue:133]: It seems that when `fieldsInCollection` is passed to the Kanban layout, it is a `Field[]`. I updated the type here to reflect the actual objects passed to the layout.

File: app/src/layouts/kanban/kanban.vue [hunk 3]
```diff
@@ -134,6 +144,7 @@ const props = withDefaults(
 		sortField?: string | null;
 		userField?: string | null;
 		groupsSortField?: string | null;
+		layoutOptions: LayoutOptions;
```
Comment (magnus-bb) [inline app/src/layouts/kanban/kanban.vue:147]: `layoutOptions` were not "caught" as a prop in the Kanban layout, but it is already passed to the layout. Technically it might be possible to access the data through `$attrs` instead, but since I use the data, I figured this was best.

File: app/src/layouts/kanban/kanban.vue [hunk 4]
```diff
@@ -185,6 +196,13 @@ function saveChanges() {
 	editDialogOpen.value = null;
 	editTitle.value = '';
 }
+
+// Used to find relevant information to display cards' formatted text with <render-display>
+const textFieldConfiguration = computed<Field | undefined>(() => {
+	/* Extra information is stored in fieldsInCollection,
+	but we need to find the config for the field used as the card's text field */
+	return props.fieldsInCollection.find((field) => field.field === props.layoutOptions.textField);
+});
```
Comment (magnus-bb) [inline app/src/layouts/kanban/kanban.vue:205]: I contrast to the Tabular layout, I could not find a pretty declaration of the settings / configurations for the fields that are used for the kanban card's title, text, tags etc.

By settings / configuration I mean the definition of the item's display configuration, type of field (e.g. text / string) and so on.

Instead, I am getting the configuration for the field that is selected to be the kanban card's text by looking for the field that is selected to be the card's text in the given collection's array of field configurations. In cases where no field has been selected for the card's text, this will return `undefined` and the `<render-display>` will not render on the card, just like before.

Let me know if you know of an easier / better way of getting these data without having to look them up manually. This way seems robust enough and the computational overhead is extremely small, even if this method is applied to other card fields in the future where the configuration is also needed (such as the card labels etc), since it will only ever need compute this once for every field on the collection (not every item being displayed).

File: app/src/layouts/kanban/kanban.vue (hunk 1 above)
Comment (rijkvanzanten) [reply app/src/layouts/kanban/kanban.vue:65]: > As far as I can tell, this was the most fitting component to use, but it does not seem to work for all types of text / string fields (e.g. markdown).

The render-display component will simply render whatever display is configured for that particular field, so depending on the configured display, it should work for all field types 👍🏻

File: .changeset/plenty-dragons-drop.md [hunk 5]
```diff
@@ -0,0 +1,6 @@
+---
+'@directus/app': patch
+---
+
+The Card Text of the Kanban board layout items have been changed to use the given field's formatted value when the Card
+Text field is a WYSIWYG
```
Comment (paescuj) [inline .changeset/plenty-dragons-drop.md:6]:
```suggestion
Fixed displaying of formatted values in Kanban cards
```

File: app/src/layouts/kanban/kanban.vue (hunk 4 above)
Comment (rijkvanzanten) [reply app/src/layouts/kanban/kanban.vue:205]: This looks good to me! The layoutOptions do in fact just store the string field name, so you will have to lookup the field information from there.

**Review by rijkvanzanten — APPROVED** [review]
LGTM!

File: .changeset/plenty-dragons-drop.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/app': patch
+---
+
+Fixed displaying of formatted values in Kanban cards
```
Comment (paescuj) [inline .changeset/plenty-dragons-drop.md:5]:
```suggestion
Fixed displaying of formatted values used as card text in Kanban layout
```

File: .changeset/plenty-dragons-drop.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/app': patch
+---
+
+Fixed displaying of formatted values used as card text in Kanban layout
```
Comment (paescuj) [inline .changeset/plenty-dragons-drop.md:5]:
```suggestion
Fixed display of formatted values used as card text in Kanban layout
```

File: app/src/layouts/kanban/kanban.vue (hunk 4 above)
Comment (paescuj) [inline app/src/layouts/kanban/kanban.vue:205]: Code is self-explanatory, comments not necessary 👍 

```suggestion
const textFieldConfiguration = computed<Field | undefined>(() => {
	return props.fieldsInCollection.find((field) => field.field === props.layoutOptions.textField);
});
```

**Review by paescuj — APPROVED** [review]
Looks great, thanks! 🚀
