### PR TITLE
Fix layout display dependant on item count request

### LINKED ISSUE #25984: Missing data if the distinct count is failing
### Describe the Bug

The collection page will not show any data if the distinct count (its result shown at the top right corner of the page) is not loaded in. If the distinct count fails, it won't show the data at all.

Image

I would consider the `x-y of z` visual a _nice to have_, but not critical for it to block the data visualisation all together.  For larger datasets, this feature keeps most collections empty for longer than needed, given that the actual query for the data itself is faster than the distinct count.

### To Reproduce

Create a large table if 1M entries. Open the collection through the CMS and observe the load times.

To 'break' the distinct count query can be a bit harder. Either reduce the performance of the database, or increase the number of entries.

### Directus Version

v11.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15.13

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Layout item display for `tabular` and `cards` are no longer dependant on the item count request completing before display
  - The pagination now shows a loader when items have been loaded but the count has not
- Added circular loader display when card items are loading

#### BEFORE
https://github.com/user-attachments/assets/a3b7f752-dc04-4bca-b17a-1891c7590bae
#### AFTER
https://github.com/user-attachments/assets/4dca6231-5ace-4ff5-b72f-ea9a218ab76f

## Potential Risks / Drawbacks

- If the count request errors no error is displayed leading to an empty pagination location

## Tested Scenarios

- [x] Expect layout item display to no longer block item count completing
- [x] Expect pagination location displays a loader when items have loaded but item count has not
- [x] Expect pagination to display once count and items have been loaded

## Review Notes / Questions

- Any alternative or UX improvement suggestions are welcome
- Specifically limited the progress loader to only do so if the items have NOT loaded to prevent multiple loaders to displays while the items are being loaded in

## Checklist

- [ ] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25984

### CODE REVIEW

File: app/src/layouts/cards/cards.vue [hunk 1]
```diff
@@ -86,7 +87,7 @@ watch(innerWidth, (value) => {
 
 <template>
 	<div ref="layoutElement" class="layout-cards" :style="{ '--size': size * 40 + 'px' }">
-		<template v-if="loading || ((itemCount ?? 0) > 0 && !error)">
+		<template v-if="loading || ((items.length ?? 0) > 0 && !error)">
```
Comment (AlexGaillard) [inline app/src/layouts/cards/cards.vue]:
```suggestion
		<template v-if="loading || (items.length > 0 && !error)">
```

This assertion reads a bit strangely. Any reason you didn't just go with `items.length > 0`. It's a required prop, so it should always at least be an empty array I think.

File: app/src/layouts/tabular/tabular.vue [hunk 2]
```diff
@@ -112,7 +113,7 @@ function removeField(fieldKey: string) {
 <template>
 	<div class="layout-tabular">
 		<v-table
-			v-if="loading || (itemCount && itemCount > 0 && !error)"
+			v-if="loading || ((items.length ?? 0) > 0 && !error)"
```
Comment (AlexGaillard) [inline app/src/layouts/tabular/tabular.vue]: Same note about assertion

```suggestion
			v-if="loading || (items.length > 0 && !error)"
```

**Review by AlexGaillard — COMMENTED** [review]
Functionally this looks good. Though I wonder if we should go with a linear progress indicator rather than the circular.

### Linear
Screenshot 2025-11-03 at 13 28 13

### Circular
Screenshot 2025-11-03 at 13 28 34

WDYT @formfcw?

**Comment by formfcw** [comment]
> Functionally this looks good. Though I wonder if we should go with a linear progress indicator rather than the circular.
> WDYT @formfcw?

Neither one nor the other. I suggest showing either the pagination disabled (like `<v-pagination disabled />`) or a skeleton while loading.

**Comment by AlexGaillard** [comment]
> or a skeleton while loading

Not sure we have a skeleton. I guess it should just be disabled then. Adding skeleton functionality feels out of scope.

**Comment by AlexGaillard** [comment]
Florian has just schooled me that we do in fact have `v-skeleton`, so perhaps that is the better way to go

**Comment by ComfortablyCoding** [comment]
> Florian has just schooled me that we do in fact have `v-skeleton`, so perhaps that is the better way to go

I would agree skeleton is the way to go, this is usually indicative of something loading while disabled does not and may lead to some confusion. I'll have a look at adding it in

**Comment by ComfortablyCoding** [comment]
Loader has been added


https://github.com/user-attachments/assets/d08f5bf4-d38d-424c-8738-e1b8f7f80c15

**Review by AlexGaillard — APPROVED** [review]
TY for updating tests
