### PR TITLE
Fix not being able to close groups

### LINKED ISSUE #11060: Tree-view interface search doesn't find top-level items
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you use the tree-view interface's search box, it only searches through the recursive items starting at level 2. All top level parent items aren't searched through / highlighted.

### To Reproduce

Setup a tree-view interface, search for something

### Errors Shown

_No response_

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13

### What database are you using?

PG 13

### What browser are you using?

Safari 15.2

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

locally

### LINKED ISSUE #11061: Tree-view expand/collapse doesn't work when search is active
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When you've searched for a value, you can no longer collapse any sections that have search results

### To Reproduce

Search for something, try to collapse the top level section

### Errors Shown

n/a

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

Node 16.13

### What database are you using?

Postgres 13

### What browser are you using?

Safari 15.2

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by Nitwel**
closes #11060
closes #11061
The problem was by setting the `open` prop to true, we enforce the group to always be open.
This was fixed by not using the `open` prop, but to add the searched items to the selected group list.

### CODE REVIEW

File: app/src/components/v-checkbox-tree/v-checkbox-tree-checkbox.vue [hunk 1]
```diff
@@ -165,7 +165,7 @@ export default defineComponent({
 				return visibleChildrenValues.value.length > 0;
 			}
 
-			return typeof props.search === 'string' && props.search.length > 0;
+			return undefined;
```
Comment (rijkvanzanten) [inline app/src/components/v-checkbox-tree/v-checkbox-tree-checkbox.vue:168]:
```suggestion
			return false;
```

**Review by rijkvanzanten — APPROVED** [review]

**Comment by bcartier** [comment]
This is still an issue when using the "Show Selected" option - you can't expand/collapse groups.
