### PR TITLE
DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake

### LINKED ISSUE #24835: DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake
### Describe the Bug

After upgrade to 11.5.1, we see the deprecation warning below.

`(node:29) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.`

Image

### To Reproduce

1. create Dockerfile
```
FROM directus/directus:11.5.1

USER root
RUN npm i -g corepack@latest
RUN corepack enable
USER node

RUN pnpm install \
  directus-extension-field-actions@1.9.0 \
  directus-extension-generate-types@0.6.1 \
  directus-extension-sync@3.0.3
```

2. run docker build and run then check the logs 

### Directus Version

11.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL

### PR DESCRIPTION
**Pull request by br41nslug**
## Scope

What's changed:

Since the node 22 update node has started throwing deprecation warnings for `promisify(Promise)`.
> (node:81820) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.

image

Since knex is internally relying on `await promisify(poolConfig.afterCreate)` we have 3 options to get rid of this warning:
1. wait for an update to knex that avoids using promisify (unlikely as there hasnt been a knex release in over a year, and doing this change ourself would be quite a breaking change for knex users)
2. Disable the throwing of this error in nodejs (`export NODE_OPTIONS=--disable-warning=DEP0174`)
3. Make sure our `afterCreate` functions are not `async` (as I've done in this PR)

- refactored `poolConfig.afterCreate` to be synchronous instead of async

[MySQL 5.7 has been out of support for over a year](https://endoflife.date/mysql)
- Dropped mysql 5.7 specific exception and `getDatabaseVersion()` function
- Removed no longer used abstraction of `SchemaHelper.applyMultiRelationalSort()`

## Potential Risks / Drawbacks

- Unexpected database issues

## Review Notes / Questions

- Do we consider the dropping of MySQL 5.7 specific logic a breaking change?
- Why were these `afterCreate` functions made async anyway? Feels like we were unnecessarily creating wrapping promises here considering all the code in them was awaited in a synchronous fashion anyway.

---

Fixes #24835

### CODE REVIEW

**Comment by ComfortablyCoding** [comment]
### Testing
- [x] sqlite 
- [x] mssql - no `afterCreate`
- [ ] mysql
- [ ] postgres
- [ ] cockroachdb
- [ ] oracle
- [ ] maria

File: api/src/database/index.ts [hunk 1]
```diff
@@ -165,14 +162,14 @@ export function getDatabase(): Knex {
...
 		Object.assign(knexConfig, { client: 'mysql2' });
 
-		poolConfig.afterCreate = async (conn: any, callback: any) => {
+		poolConfig.afterCreate = (conn: any, callback: any) => {
 			logger.trace('Retrieving database version');
-			const run = promisify(conn.query.bind(conn));
 
-			const version = await run('SELECT @@version;');
-			databaseVersion = version[0]['@@version'];
+			conn.query('SELECT @@version;', (_err: any, rows: any[], _fields: any) => {
```
Comment (ComfortablyCoding) [inline api/src/database/index.ts:168]: As [MYSQL 5.7 is EOL](https://endoflife.date/mysql) we can probably remove this query for `databaseVersion` and its relevant usage. This is only used for checking `mysql 5.7` when we generate relational sort queries

File: api/src/database/helpers/schema/dialects/mysql.ts [hunk 2]
```diff
@@ -15,32 +14,6 @@ export class SchemaHelperMySQL extends SchemaHelper {
 		return getDefaultIndexName(type, collection, fields, { maxLength: 64 });
 	}
 
-	override applyMultiRelationalSort(
```
Comment (ComfortablyCoding) [inline api/src/database/helpers/schema/dialects/mysql.ts:18]: As we are no longer using `applyMultiRelationalSort` for mysql it looks like we can remove it completely from https://github.com/directus/directus/blob/main/api/src/database/helpers/schema/types.ts#L149 ? It does not seem to be a necessary abstraction anymore.

Comment (br41nslug) [reply api/src/database/helpers/schema/dialects/mysql.ts:18]: Sure thing

File: .changeset/green-places-throw.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': major
```
Comment (licitdev) [inline .changeset/green-places-throw.md:2]: Let's bump this to a minor release

```suggestion
---
'directus': minor
'@directus/api': major
```

**Review by licitdev — DISMISSED** [review]

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
