### PR TITLE
header bar icon color: var(--primary)

### LINKED ISSUE #13669: Settings Header Icon Color Incorrect
While the upcoming Data Flows is correct, all left heading icons should be `primary` within the Settings Module:

Screen Shot 2022-06-01 at 12 49 09 PM

You can see that this is currently "foreground-normal" on purple... which is incorrect.

I'm on 9.11.1 Cloud.

### PR DESCRIPTION
**Pull request by jamescammarano**
## Description

Added a css rule to header-bar.vue to change the icon color to be primary.
171458370-a280b524-6297-43e6-9b95-51bd37d5b6a2
Screen Shot 2022-06-06 at 2 14 04 PM

Fixes #13669

## Type of Change

- [x] Bugfix
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: app/src/views/private/components/header-bar/header-bar.vue [hunk 1]
```diff
@@ -112,6 +112,10 @@ export default defineComponent({
 	.title-outer-prepend {
 		display: none;
 
+		:deep(.button) {
+			color: var(--primary);
+		}
```
Comment (rijkvanzanten) [inline app/src/views/private/components/header-bar/header-bar.vue:117]: This would change the icon color _everywhere_, rather than just in the couple of pages in settings where it's applicable. The user is normally able to configure the color, so this isn't quite the right solution. As per the original issue, Flows already has the correct icon styling applied, so lets copy over the styling logic used in there to the other pages in settings where it's missing 🙂 

https://github.com/directus/directus/blob/ae6182215965f99f30c1d5b1eeb1a708466e76a4/app/src/modules/settings/routes/flows/flow.vue#L689-L694

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/views/private/components/header-bar/header-bar.vue (hunk 1 above)
Comment (jaycammarano) [reply app/src/views/private/components/header-bar/header-bar.vue:117]: I tried this and didn't see any change in the applied styling. I also don't see any change on hove with the flows icon either.

Comment (rijkvanzanten) [reply app/src/views/private/components/header-bar/header-bar.vue:117]: Looks like there's a small difference in how the buttons are rendered between flows and the other pages. Flows uses:

```html
<v-button class="header-icon" rounded disabled icon>
	<v-icon name="bolt" />
</v-button>
```

whereas the other pages seem to use:

```html
<v-button class="header-icon" rounded disabled icon secondary>
	<v-icon name="list_alt" />
</v-button>
```

the `secondary` prop sets the foreground color to the gray, and has a higher specificity in the context of the page than the custom override. Removing those `secondary` props makes things look like it should 👍🏻

**Review by rijkvanzanten — APPROVED** [review]
