### PR TITLE
Only treat `tinyint(1)` and `tinyint(0)` as booleans

### LINKED ISSUE #6665: Don't treat TINYINT as Boolean
### sql
image

### directus
image

### tinyint
https://docs.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-2016

### To Reproduce

create a tinyint field in sql

### What version of Directus are you using?

v9.0.0-rc.82

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

### PR DESCRIPTION
**Pull request by jamescammarano**
Fixes #6665 
Added an if check for tinyint(1) and tinyint(0) which will be treated like a boolean.

### CODE REVIEW

File: api/src/utils/get-local-type.ts [hunk 1]
```diff
@@ -128,6 +127,11 @@ export default function getLocalType(
 		return 'text';
 	}
 
+	/** Handle Boolean as TINYINT*/
+	if (column.data_type === 'tinyint(1)' || column.data_type === 'tinyint(0)') {
```
Comment (rijkvanzanten) [inline api/src/utils/get-local-type.ts:131]: Lets add in a `toLowerCase()` here just in case some database wants to throw you a curveball with `TINYINT` instead of `tinyint`

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
