### PR TITLE
Fix a few dev mode warnings

### LINKED ISSUE #18248: `dev` mode warnings in app
### Describe the Bug

When running the app in dev mode there are a few warnings that drown the console.

In `/admin/settings/data-model/whatever`
- v-text-overflow
```
[Vue warn]: Invalid prop: type check failed for prop "text". Expected String | Number | Boolean | Object | Array, got Undefined  
  at <VTextOverflow text=undefined > 
```
- fields (caused in use-item)
```
[Vue warn]: Invalid watch source:  {} A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. 
  at <Fields collection="block_editor" field=undefined type=undefined  ... > 
 ```

When adding a new field to a datamodel
- field-detail-simple
```
[Vue warn]: Invalid prop: type check failed for prop "search". Expected String with value "null", got Null  
  at <FieldDetailSimple key=0 collection= {collection: 'block_editor', meta: {…}, schema: {…}, name: 'Block Editor', type: 'table', …} search=null  ... > 
 ```
 
In `settings/webhooks` 
- v-button
```
[Vue warn]: Invalid prop: type check failed for prop "to". Expected String | Null, got Object  
  at <VButton to= {path: '/settings/webhooks/+'} > 
```

Any item with a default O2M List
```
[Vue warn]: Missing required prop: "layout" 
  at <ListO2m autofocus=false disabled=false loading=false  ... > 
 ```

### To Reproduce

See above

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by hanneskuettner**
Fixes #18248

### CODE REVIEW

File: app/src/components/v-text-overflow.vue [hunk 1]
```diff
@@ -11,14 +11,15 @@ import { useElementSize } from '@directus/composables';
...
-	text: string | number | boolean | Record<string, any> | Array<any>;
+	text?: string | number | boolean | Record<string, any> | Array<any>;
 	/** What parts of the text should be highlighted */
 	highlight?: string;
 	/** The placement of the tooltip */
 	placement?: 'top' | 'bottom' | 'left' | 'right' | 'start' | 'end';
 }
 
 withDefaults(defineProps<Props>(), {
+	text: '',
```
Comment (paescuj) [inline app/src/components/v-text-overflow.vue:22]: The warning you're currently seeing in `/admin/settings/data-model/whatever` actually seems to be more of an indication that the components are being rendered even though the data is not yet loaded... In principle, however, it's okay for me to accept an undefined value here. Should we default to `undefined` instead of `''`though?

File: app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue [hunk 2]
```diff
@@ -57,7 +57,7 @@ export default defineComponent({
 		},
 		search: {
 			type: String,
-			required: true,
+			default: null,
```
Comment (paescuj) [inline app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue:60]: Wondering what's the cleaner solution to get rid of the current type mismatch in `app/src/modules/settings/routes/data-model/field-detail/field-detail.vue` 😄 

- Changing it to 
  ```suggestion
				type: String as () => string | null,
				required: true,
  ```
- or adjusting the line here https://github.com/directus/directus/blob/678c5f57af547f567b8c12f0c67e471f82d70710/app/src/modules/settings/routes/data-model/field-detail/field-detail.vue#L78 to 
  ```js
 		const search = ref<string | undefined>(undefined); 
  ```

Comment (hanneskuettner) [reply app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue:60]: I've never seen the `String as () => string | null` syntax before. It doesn't seem to work when trying it out locally. And as far as I can see it's not supported by Vue? https://github.com/vuejs/vue/issues/1961

I know it works for sure when using a `<script setup>` block and `search: string | null`. So not really sure what to do here.

Comment (paescuj) [reply app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue:60]: Oh, right this just makes TypeScript happy but not Vue 😅 

An ugly workaround for this would be https://github.com/vuejs/core/issues/3948#issuecomment-860466204.

Would you mind adjusting `field-detail.vue` as suggested above in that case? Thx!

Comment (rijkvanzanten) [reply app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue:60]: hey psst would it be fixed if we rework it to a `<script setup>` with `defineProps`? I wanna move everything over regardless, so this could be a good excuse

Comment (hanneskuettner) [reply app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue]: Agreed. I'll use that excuse

Comment (hanneskuettner) [reply app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue]: That's one ugly diff. Looks wait better with "Hide Whitespace"

Comment (paescuj) [reply app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue]: Awesome 🚀

**Review by paescuj — APPROVED** [review]
Nice 💯

**Review by rijkvanzanten — APPROVED** [review]
