### PR TITLE
Translate system fields when creating new collections

### LINKED ISSUE #8323: Status field options not translated
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I didn't know what to title this bug. Anyway, I bootstrapped an ENV file to quickly set up Directus, then I created a collection and check some default fields like "Status". Going to edit the status field I found this.

Screen Shot 2021-09-25 at 10 53 57 PM

I am guessing there is an error somewhere. Might be a small issue. Just thought to mention

### To Reproduce

As above

### What version of Directus are you using?

RC.94

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by azrikahar**
fixes #8323 

## Bug

The choices for Status are not translated:

chrome_lzzdnr8UYT

## Investigation

These translations were introduced in #7925, but they were never actually parsed/translated (`$t:`) before being used to create new collections, as seen at the end of `getSystemFields()` function:

https://github.com/directus/directus/blob/9967274ab276a4adfe4a76b775b614cf940dcb27/app/src/modules/settings/routes/data-model/new-collection.vue#L454

## Solution

Ensure `getSystemFields()` returns translated fields by wrapping `translate()` around the returned `fields` array.

## After fix

chrome_POi0nUOnxq

### CODE REVIEW

**Comment by licitdev** [comment]
@azrikahar I saw that when configuring the status fields and I thought that was a feature hmm. It allows the person configuring to know that the text will be localised. 

I wonder if the UI could have a label or tag that says `i18n` etc, alongside the translated text.

**Comment by azrikahar** [comment]
@licitdev that's understandable. However there are quite a lot of localised text on the UI in general, so not sure if we can go with the label/tag approach. Though I do recall there was a similar question over here #5079 (check the comments where they discussed about it), so maybe the "localised text" indicator would be more appropriate within such feature.

**Comment by benhaynes** [comment]
On the user side of the app I agree all of this should be transparent. Perhaps on the admin side, we could have some sort of indicator that shows this is an actively translated value.

We could either go with a tooltip, to keep the UI cleaned, or a subtle indicator, such as:

`$t:Published` where "Published" (the actual translated string in the user's language, not the key) is the standard text coloring, and the rest uses the subdued coloring.

`Published*` where the asterisk is subdued or primary color, and simply hints that there is a tool tip. This specifically might be confusing with "required".

Thoughts?

**Comment by rijkvanzanten** [comment]
Ohh this is reaching a very interesting rabbit hole.. We want to support that `$t:` syntax in various places, to allow for translatable option values (like this status thing). However, when it comes to showing that raw value, like in the repeater rows, we reach a weird in-between. Should we always try converting any raw value to make sure we handle the translations? Is it just in the repeater rows seeing we expect the raw value there to have a $t:? 🤔

**Comment by azrikahar** [comment]
Just to clarify the end goal for `$t:` here, does it mean the plan is to allow adding `$t:` translation key values (directly in the app), or just confined to the translations available in the existing translation files?

**Comment by rijkvanzanten** [comment]
> does it mean the plan is to allow adding $t: translation key values (directly in the app)

That's correct! The user will be able to add their custom translation values, so we can allow for custom translations in all sorts of other places, like interface options

File: app/src/modules/settings/routes/data-model/new-collection.vue [hunk 1]
```diff
@@ -451,7 +452,7 @@ export default defineComponent({
 				});
 			}
 
-			return fields;
+			return translate(fields);
```
Comment (rijkvanzanten) [inline app/src/modules/settings/routes/data-model/new-collection.vue:455]: We can't translate it in this step, if we'd do that it would save it translated to the database, instead of as the translatable string 🤔

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/modules/settings/routes/data-model/new-collection.vue (hunk 1 above)
Comment (azrikahar) [reply app/src/modules/settings/routes/data-model/new-collection.vue:455]: Oh didn't realize that. This means we'll need to translate it on the interface?

Comment (rijkvanzanten) [reply app/src/modules/settings/routes/data-model/new-collection.vue:455]: Yeah! That being said, we can only translate where the value is displayed, otherwise we'll have the same problem where the value is overwritten with the translated value 😩

**Comment by joselcvarela** [comment]
@azrikahar @rijkvanzanten 
I have updated this in order to only translate on display 👍

**Comment by rijkvanzanten** [comment]
Smart solution @joselcvarela! It will technically also translate user content in those repeater rows, but I think the `$t:` syntax is proprietary enough that we shouldn't expect too many conflicts. If somebody shows up complaining about it, we can add an advanced interface option to disable it 👍🏻

**Review by rijkvanzanten — APPROVED** [review]

**Comment by azrikahar** [comment]
@joselcvarela this is great! Thanks for picking this up 🤝
