### PR TITLE
Fix Flow Error Handling

### LINKED ISSUE #14415: Flows: Operation "request" does not pass error information/data
### Describe the Bug

I stumbled across this behavior trying to pass additional information along with an error and could not retrieve it. 

In case of an error the flow's logs show an (axios) error but the payload (incl. headers, message etc.) consists of the original request's data, not the error's response.

File: `directus/api/src/operations/request/index.ts` :

Perhaps - unfortunately I can't test it myself right now :/ - this is (simply) due to a missing try/catch block.

A request is made without catching possible errors, thus loosing all additional error information/data from the server the request went to:

```typescript
...
  handler: async ({ url, method, body, headers }) => {
    const customHeaders = headers?.reduce((acc, { header, value }) => {
      acc[header] = value;
      return acc;
    }, {} as Record<string, string>);

    const result = await axios({ url, method, data: body, headers: customHeaders });

    return { status: result.status, statusText: result.statusText, headers: result.headers, data: result.data };
  },
...
```

If so, it could be solved by adding the try/catch block and passing the error's information/data: 

```typescript
...
  handler: async ({ url, method, body, headers }) => {
    const customHeaders = headers?.reduce((acc, { header, value }) => {
      acc[header] = value;
      return acc;
    }, {} as Record<string, string>);

    try{
      const result = await axios({ url, method, data: body, headers: customHeaders });
      return { status: result.status, statusText: result.statusText, headers: result.headers, data: result.data };
    } catch(error) {
      return { status: error.response.status, statusText: error.result.statusText, headers: error.response.headers, data: error.response.data };
    }
  },
...
``` 

This would be analog to the [Axios Docs (Error Handling)](https://axios-http.com/docs/handling_errors)

And last but not least: Thank you so much for your great work, Directus really is an amazing project! 

### To Reproduce

Add a 'request' operation to a flow, that makes a request to a script and within that script (in my case a custom endpoint extension) return an error with additional data.

For example (within a custom endpoint extension), something like the following (js):

```js
  export default (router, context) => {
    return router.get('/', (req, res) => {
      return res.status(400).send('A custom error message');
    }
  }
```

Even if you add additional custom headers, json etc. to the response, the problem remains the same: The flow's logs will only show the original requests data in the payload. The additional data (in this case the message 'A custom error message') is nowhere to be found. 

### Errors Shown

_No response_

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

v17.8.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### LINKED ISSUE #15291: Run Script return value with circular reference throws error
### Describe the Bug

Error is thrown while saving revision if Run Script returns value with circular reference.

https://github.com/directus/directus/blob/a98a83b5da0677c45cce0e9dc23204438ee32cc8/api/src/flows.ts#L343-L351

Leading to an error being thrown in the payload service.

https://github.com/directus/directus/blob/a98a83b5da0677c45cce0e9dc23204438ee32cc8/api/src/services/payload.ts#L179-L180

### To Reproduce

Create a new flow with `Activity & Logs Tracking` set as `Track Activity & Logs`.
Create a Run Script operation in Flows with the following example.

```js
module.exports = async function(data) {
	const obj = {a: 1};
	obj.b = obj;
	return obj;
}
```

### Errors Shown

```
00:28:25 🚨 Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'b' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'b' closes the circle
    at JSON.stringify (<anonymous>)
    at /Users/ian/Projects/directus/api/src/services/payload.ts:179:27
    at Array.forEach (<anonymous>)
    at PayloadService.processValues (/Users/ian/Projects/directus/api/src/services/payload.ts:175:21)
    at /Users/ian/Projects/directus/api/src/services/items.ts:135:35
```

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by connorwinston**
## Description
Fixes #15291, Fixes #14415, Closes #16166

This validates that the result of an operation is valid serializable JSON, fixes errors being swallowed because they are enumerable,  fixes the request operations error being inconclusive, and adds the ability for operations to throw JSON string errors and them to be parsed before being pushed as an error.

## Type of Change

- [X] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: api/src/flows.ts [hunk 1]
```diff
@@ -413,7 +416,21 @@ class FlowManager {
...
 	}
 }
+
+function isJSON(value: any): boolean {
+	try {
+		parseJSON(value);
+		return true;
+	} catch {
+		return false;
+	}
```
Comment (br41nslug) [inline api/src/flows.ts:435]: Can we extract this to a utility function so it can be re-used? We're using at least one exact copy of this function elsewhere https://github.com/directus/directus/blob/main/api/src/operations/request/index.ts#L36

**Review by br41nslug — CHANGES_REQUESTED** [review]

File: api/src/flows.ts (hunk 1 above)
Comment (ConnorSimply) [reply api/src/flows.ts:435]: I was wanting to, but this function was inconsistently used in the code base like the following as an almost similar name but slightly different function. One returns the JSON one and one returns true.
https://github.com/directus/directus/blob/e3c755dcf000aafc6535cc271093242da5e5dbc9/api/src/env.ts#L508

What do you think the best way to name/differentiate the two is?

Comment (br41nslug) [reply api/src/flows.ts:435]: As for your and the linked function i'd personally think `isValidJSON` is a proper name implying that it's a boolean value by with the word `Valid` while `tryJSON` seems to be a very basic wrapper for `parseJSON` sepcifically made for `env.ts` because it is used a couple times. No need to abstract the latter.

Comment (br41nslug) [reply api/src/flows.ts]: The test looks good to me 😄 not sure what else you could test on this util

**Review by br41nslug — COMMENTED** [review]
Works like a charm! But from a security standpoint I am wondering about whether we should dump the entire error stack here 🤔 Perhaps we should only persist the error message itself.
image

**Comment by ConnorSimply** [comment]
> Works like a charm! But from a security standpoint I am wondering about whether we should dump the entire error stack here 🤔 Perhaps we should only persist the error message itself. 

I was curious about that too, but thought that was the intended behavior since the error was just dumped into it before...it just couldn't stringify it because it was enumerable. Which resulted in inconsistent errors because Axios errors some keys are enumerable and some are not. Etc. @rijkvanzanten do you want the full errors returned?

**Comment by paescuj** [comment]
> Works like a charm! But from a security standpoint I am wondering about whether we should dump the entire error stack here 🤔 Perhaps we should only persist the error message itself. image

Are you worried about the paths? In this case we could use https://github.com/sindresorhus/clean-stack to clean up the stack.

**Comment by br41nslug** [comment]
@paescuj The path i would consider unintended information disclosure yeah but it is also not very readable in this format when all you really need is `TypeError: Converting circular structure to JSON`

**Comment by paescuj** [comment]
> @paescuj The path i would consider unintended information disclosure yeah but it is also not very readable in this format when all you really need is `TypeError: Converting circular structure to JSON`

Agree very much! I'm going to create a separate issue for this 👍

**Comment by ConnorSimply** [comment]
@br41nslug Not every Operation throws an instance of error, though when it errors. For example, the webhook/request operation. This PR also fixed returning the request instead of the result. The only way to do that with Axios was to make some custom error throwing and catching as a string and then parsing it. Your change breaks the changes made to that. Additionally, in almost every other place, we return errors as JSON objects; however, your change returns a string which may confuse people using flows?

**Comment by br41nslug** [comment]
Thanks @ConnorSimply I may have been a little overzealous on the friday fix there. Have updated it to only apply in the case of an actual Error and use the existing logic otherwise

**Comment by ConnorSimply** [comment]
@br41nslug Are we good then to merge now? Tested your changes and they LGTM!

**Comment by br41nslug** [comment]
@ConnorSimply Yep I think so

**Review by br41nslug — APPROVED** [review]

**Comment by paescuj** [comment]
> @br41nslug @paescuj Are we good then to merge now? Tested your changes and they LGTM!

Going to add my review in a few minutes 👍

File: api/src/flows.ts [hunk 2]
```diff
@@ -416,10 +416,20 @@ class FlowManager {
...
+				errorMessage = isValidJSON(String(error))
+					? parseJSON(String(error))
+					: JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
+			}
+
 			return {
 				successor: operation.reject,
 				status: 'reject',
-				data: error instanceof Error ? error.message : null,
+				data: errorMessage ?? null,
```
Comment (paescuj) [inline api/src/flows.ts:432]: I feel like things are now a bit mixed-up...

```JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));``` is intended for `Error` but this is now already caught above, right?

**Review by paescuj — CHANGES_REQUESTED** [review]

File: api/src/operations/request/index.ts [hunk 3]
```diff
@@ -19,27 +19,28 @@ export default defineOperationApi<Options>({
 				return acc;
 			}, {} as Record<string, string>) ?? {};
 
-		if (!customHeaders['Content-Type'] && isValidJSON(body)) {
+		if (!customHeaders['Content-Type'] && isValidJSON(String(body))) {
```
[the remark this answers is not in the document]
Comment (ConnorSimply) [reply api/src/operations/request/index.ts:22]: I did not change this behavior it just got moved into shared utils. I believe the body always comes in as a string because before `isValidJSON(value: any)` tests by using `parseJSON(input: string)` which just uses JSON.parse().

Will the operation ever get passed an object or will it always get passed stringified JSON?

File: api/src/flows.ts [hunk 4]
```diff
@@ -413,7 +416,22 @@ class FlowManager {
...
 			return { successor: operation.resolve, status: 'resolve', data: result ?? null, options };
 		} catch (error: unknown) {
-			return { successor: operation.reject, status: 'reject', data: error ?? null, options };
+			let errorMessage: Record<string, any>;
+			if (error instanceof Error) {
+				errorMessage = { message: error.message };
+			} else {
+				// Is the error a JSON string? If so, parse it and use that as the error
+				errorMessage = isValidJSON(String(error))
+					? parseJSON(String(error))
```
[the remark this answers is not in the document]
Comment (ConnorSimply) [reply api/src/flows.ts:425]: Great catch seeing that this got overwritten from when I had this in before.

File: api/src/flows.ts (hunk 2 above)
Comment (ConnorSimply) [reply api/src/flows.ts]: I believe you are right on this, I am getting mixed up too.

File: api/src/flows.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (br41nslug) [reply api/src/flows.ts]: Something has gone wrong in accepting this suggestion 😬 Half of the ternary operation was replaced leaving an invalid statement.

File: api/src/flows.ts [hunk 5]
```diff
@@ -413,7 +416,23 @@ class FlowManager {
...
-			return { successor: operation.reject, status: 'reject', data: error ?? null, options };
+			let errorMessage: Record<string, any>;
+			if (error instanceof Error) {
+				errorMessage = { message: error.message };
+			} else {
+				// Is the error a JSON string? If so, parse it and use that as the error
+				errorMessage = isValidJSON(String(error))
+					: // Explicit specification of the error properties since those aren't enumerable
+					  JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
+					: JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
```
Comment (paescuj) [inline api/src/flows.ts:427]:
```suggestion
					? parseJSON(String(error))
					: // Explicit specification of the error properties since those aren't enumerable
					  JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error)));
```

File: api/src/flows.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/flows.ts:425]: Probably my bad 😅 Sorry about that! Fixed now 👍

**Comment by ConnorSimply** [comment]
@paescuj Is this clear to be merged now?

File: api/src/flows.ts [hunk 6]
```diff
@@ -415,22 +415,21 @@ class FlowManager {
...
+		} catch (error) {
+			const data =
+				error instanceof Error
+					? // If the error is instance of Error, use the message of it as the error data
+					  { message: error.message }
+					: isValidJSON(String(error))
+					? // If the error is a JSON string, parse it and use that as the error data
+					  parseJSON(String(error))
+					: // If error is plain string, use this as the error data and otherwise fallback to null
+					  error ?? null;
```
Comment (br41nslug) [inline api/src/flows.ts:427]: I am personally not a huge fan of nesting ternary conditional operations for readability/maintainability 😬

Comment (paescuj) [reply api/src/flows.ts:427]: You'd prefer this?
```js
			let data;

			if (error instanceof Error) {
				// If the error is instance of Error, use the message of it as the error data
				data = { message: error.message };
			} else if (isValidJSON(String(error))) {
				// If the error is a JSON string, parse it and use that as the error data
				data = parseJSON(String(error));
			} else {
				// If error is plain string, use this as the error data and otherwise fallback to null
				data = error ?? null;
			}
```

File: api/src/flows.ts (hunk 2 above)
Comment (paescuj) [reply api/src/flows.ts]: Tried to clean it up 😃 Please check if it makes sense like this!

**Comment by paescuj** [comment]
> @paescuj Is this clear to be merged now?

Looks good from my side now 👍 Glad if you could take a final look at it again! 😃

**Review by paescuj — APPROVED** [review]

**Review by connorwinston — COMMENTED** [review]
LGTM!
