### PR TITLE
Fix retention time based query not being database agnostic

### LINKED ISSUE #24176: FLOW_LOGS_RETENTION failed to delete data
### Describe the Bug

I've enabled the new data-retention config to delete flow-logs. However this throws an error:

```
[13:30:00.063] ERROR: Retention failed for Collection directus_activity
directus-1  |     err: {
directus-1  |       "type": "DatabaseError",
directus-1  |       "message": "delete from \"directus_activity\" where \"id\" in (select \"directus_activity\".\"id\" from \"directus_activity\" where \"timestamp\" < $1 and \"action\" = $2 limit $3) - date/time field value out of range: \"1731159000036\"",
directus-1  |       "stack":
directus-1  |           error: delete from "directus_activity" where "id" in (select "directus_activity"."id" from "directus_activity" where "timestamp" < $1 and "action" = $2 limit $3) - date/time field value out of range: "1731159000036"
directus-1  |               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:283:98)
directus-1  |               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:122:29)
directus-1  |               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:35:38)
directus-1  |               at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/index.js:11:42)
directus-1  |               at Socket.emit (node:events:517:28)
directus-1  |               at Socket.emit (node:domain:489:12)
directus-1  |               at addChunk (node:internal/streams/readable:368:12)
directus-1  |               at readableAddChunk (node:internal/streams/readable:341:9)
directus-1  |               at Readable.push (node:internal/streams/readable:278:10)
directus-1  |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus-1  |       "length": 205,
directus-1  |       "name": "error",
directus-1  |       "severity": "ERROR",
directus-1  |       "code": "22008",
directus-1  |       "hint": "Perhaps you need a different \"datestyle\" setting.",
directus-1  |       "where": "unnamed portal parameter $1 = '...'",
directus-1  |       "file": "datetime.c",
directus-1  |       "line": "3985",
directus-1  |       "routine": "DateTimeParseError"
directus-1  |     }
```

Configuration:

```
####################################################################################################
### Data Retention
RETENTION_ENABLED=true
RETENTION_SCHEDULE="30 * * * *"
ACTIVITY_RETENTION=false
REVISIONS_RETENTION=false
FLOW_LOGS_RETENTION=30d
```

### To Reproduce

Use the given config and wait until the cronjob starts

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PG 16.2

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- We now utilize the db helpers to generate a db specific timestamp for the retention query
- The subquery is executed outside the delete to adhere to the `mysql`/`maria` restriction of no `LIMIT` within a subquery
- Fixed `oracledb` to properly query date fields

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- Any suggested alternative solutions are welcome

## Testing
- DB
   - [x] sqlite
   - [x] pg
   - [x] cockroach
   - [x] mysql
   - [x] maria
   - [x] mssql
   - [x] oracle
- General Checks (done with PG)
  - While the query is being processed for large batches there was no visible degradation observed
     - Degradation observed with sqlite even at 250 for frequent runs (every second), I assume due to no pool?
  - The job lock preventing subsequent jobs seems to work as expected when queries take more time than expected
- Performance
      - Batch of 10k:  ~`140000ms - 180000ms `
      - Batch of 1k: ~`15000ms - 15600ms`
      - Batch of 500: ~`7400ms - 7900ms`
      - Batch of 250: ~`3800ms - 4000ms`

P.S. Performance testing was done with a sample size of `1000000` records in PG and may vary depending on setup

---

Fixes #24176

### CODE REVIEW

File: api/src/database/index.ts [hunk 1]
```diff
@@ -143,6 +143,19 @@ export function getDatabase(): Knex {
 		};
 	}
 
+	if (client === 'oracledb') {
+		poolConfig.afterCreate = async (conn: any, callback: any) => {
+			logger.trace('Setting OracleDB NLS_DATE_FORMAT and NLS_TIMESTAMP_FORMAT');
+
+			// enforce proper ISO standard date as default
+			await conn.executeAsync('ALTER SESSION SET NLS_TIMESTAMP_FORMAT = \'YY-MM-DD"T"HH24:MI:SS\'');
```
Comment (licitdev) [inline api/src/database/index.ts:151]: Should it be `YYYY` instead of `YY` for both formats? 

How about the `NLS_TIMESTAMP_TZ_FORMAT`?

Comment (ComfortablyCoding) [reply api/src/database/index.ts]: > Should it be YYYY instead of YY for both formats?

Either seem to work but in the interest of non ambiguiigty updating it 👍 

> How about the NLS_TIMESTAMP_TZ_FORMAT?

This does not seem to be necessary as `NLS_TIMESTAMP_FORMAT` [^1] covers both `TIMESTAMP` and `TIMESTAMP WITH LOCAL TIME ZONE` which are the only 2 we seem to user

---
[^1] : https://docs.oracle.com/en/database/oracle/oracle-database/19/nlspg/datetime-data-types-and-time-zone-support.html#GUID-3A1B7AC6-2EDB-4DDC-9C9D-223D4C72AC74

File: api/src/schedules/retention.ts [hunk 2]
```diff
@@ -77,7 +79,21 @@ export async function handleRetentionJob() {
...
+
+				if (records.length !== 0) {
+					count = await database(task.collection)
+						.where(
+							'id',
+							'in',
+							records.map((r) => r.id),
+						)
+						.delete();
+				}
```
Comment (licitdev) [inline api/src/schedules/retention.ts:96]: Could we extract this as a generic helper (if possible) so that most vendors run the efficient single query delete?

There's also the `whereIn` function that we could use.

Comment (ComfortablyCoding) [reply api/src/schedules/retention.ts]: > Could we extract this as a generic helper (if possible) so that most vendors run the efficient single query delete?

Updated in bdcbef4315063de36beeb6b4aec1097c0057497e
> There's also the whereIn function that we could use.

Updated in aa279d299b474b3521e4ade47c32130cc73fb52c

**Review by licitdev — APPROVED** [review]
