### PR TITLE
Only trigger edits guard if there are edits

### LINKED ISSUE #11088: New Item has changes even without any modifications
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I am trying to leave the New Item view without any changes the confirmation modal appears.
Also, when I click `Discard Changes` it shows the confirmation modal again and this process repeats and I am not able to quit this view.

### To Reproduce

I am not sure why this started happened now, but this is easy reproducible:

1. Create a collection
2. Open the New Item view on this collection
3. Try to leave. Confirm leave modal must appear.

### Errors Shown

See this screenshot
Screenshot 2022-01-17 at 06 46 25

Those are the edits, but I didn't make any change 🤔
The `nextval` thing comes from the default value from PostgreSQL

### What version of Directus are you using?

9.4.3 (e258f3d28 - main)

### What version of Node.js are you using?

v16.13.0

### What database are you using?

postgis/postgis:13-3.1-alpine

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by nickrum**
We should only show a warning if the user actually made changes to the item.

Fixes #11088

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/modules/content/routes/item.vue [hunk 1]
```diff
@@ -302,7 +302,7 @@ export default defineComponent({
 			return hasEdits.value;
 		});
 
-		const { confirmLeave, leaveTo } = useEditsGuard(isSavable);
+		const { confirmLeave, leaveTo } = useEditsGuard(hasEdits);
```
Comment (joselcvarela) [inline app/src/modules/content/routes/item.vue:305]: @nickrum please explain me 🥲
Why do we need theses lines, do you know?
```js
			if (isNew.value === true) {
				return Object.keys(defaults.value).length > 0 || hasEdits.value;
			}
```

Comment (rijkvanzanten) [reply app/src/modules/content/routes/item.vue:305]: > Also, can't we just rely on hasEdits or isSavable, why do we need both? 

It's for the navigation guard. We only want to show the _Are you sure you want to leave?_ when you've made edits. However, an item can be Savable without having Edits 👍🏻

Comment (joselcvarela) [reply app/src/modules/content/routes/item.vue:305]: Ohhh makes sense now, because it may be automatically populated or a clone of other item.
Thank you for the explanation ❤️
