### PR TITLE
fix: extension auto-load crashes directus if local extension is removed

### LINKED ISSUE #19755: Removing Local Extension crash directus with EXTENSIONS_AUTO_RELOAD
### Describe the Bug

When removing [Local Extension](https://docs.directus.io/extensions/creating-extensions.html#local-extension) from the disk with `EXTENSIONS_AUTO_RELOAD=true` directus crashes.

### To Reproduce

- Enable `EXTENSIONS_AUTO_RELOAD` in config
- Create a directory ouside of the project named `foo` with inside a file `index.js` with following content :
```javascript
import { defineHook } from '@directus/extensions-sdk'
export default defineHook(({ filter, action }) => {
  console.log('I\'m a hook!')
  filter('items.create', () => {
    console.log('Creating Item!')
  })

  action('items.create', () => {
    console.log('Item created!')
  })
})
```
- Start directus with `npx directus start`
- Move the `foo` directory to `extensions/hooks/`
- Notice in the console that the `foo` extension was loaded : `[22:20:29.737] INFO: Added extensions: foo`
- Delete the `foo` directory
- Save a file to trigger the file watcher
- Crash directus with following error message :
```javascript
[22:20:29.691] INFO: Reloading extensions
[22:20:29.737] INFO: Added extensions: foo
[22:20:56.851] INFO: Reloading extensions
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module '/workspaces/ddf-tools/packages/ddf-bundle-store/extensions/hooks/foo/index.js'
Require stack:
- /workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at ExtensionManager.unregisterApiExtensions (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:483:42)
    at ExtensionManager.unload (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:190:20)
    at file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:94:28
    at JobQueue.run (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/utils/job-queue.js:18:19)
    at JobQueue.enqueue (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/utils/job-queue.js:11:18)
    at ExtensionManager.reload (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:90:26)
    at FSWatcher.<anonymous> (file:///workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js:218:38)
    at FSWatcher.emit (node:events:513:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/ddf-tools/node_modules/.pnpm/@directus+api@13.1.0_@types+node@20.6.2/node_modules/@directus/api/dist/extensions.js'
  ]
}

```

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:
- Updated the `deleteFromRequireCache` function to use a `try/catch` for the module resolve and cache removal. If it throws an error it will now notify the user that the modules cache was not deleted instead of crashing directus.

## Potential Risks / Drawbacks
- None

## Review Notes / Questions
- I tested adding an extension (as suggested in the issue) as well. No error or issue was observed for this functionality.
- I did notice that adding and removing more than once seems to work sometimes but not others, the same behaviour is on main without my changes.

---

Fixes #19755

### CODE REVIEW

File: api/src/utils/delete-from-require-cache.ts [hunk 1]
```diff
@@ -1,7 +1,13 @@
...
 const require = createRequire(import.meta.url);
 
 export function deleteFromRequireCache(modulePath: string): void {
-	delete require.cache[require.resolve(modulePath)];
+	try {
+		const moduleCachePath = require.resolve(modulePath);
+		delete require.cache[moduleCachePath];
+	} catch (error) {
+		logger.warn(`Module cache not found for ${modulePath}, skipped cache delete.`);
+	}
```
Comment (paescuj) [inline api/src/utils/delete-from-require-cache.ts:12]: Couldn't this be just a simple `if` (if `require.cache[moduleCachePath]` exists)?
Also I don't think it's necessary to log this, or at least the level should be changed from `warn` to `trace`.

Comment (ComfortablyCoding) [reply api/src/utils/delete-from-require-cache.ts:12]: The `require.resolve` is what throws the `MODILE_NOT_FOUND` error so doing that would not resolve this issue.

I can update the warn to a trace if you believe that to be more appropriate. Logging it as a warn was mentioned in the issue so that is what I used.

Comment (paescuj) [reply api/src/utils/delete-from-require-cache.ts:12]: Ah I see, thanks 😄👍

I don't think that's really relevant to log, and might be more confusing than helping (since you cannot do anything against it anyway). Therefore I'd go with the trace level.

Comment (ComfortablyCoding) [reply api/src/utils/delete-from-require-cache.ts:12]: Alright, sounds good. Will update it tonight.

**Review by rijkvanzanten — APPROVED** [review]

**Review by paescuj — APPROVED** [review]
Thanks!
