### PR TITLE
Fix/issue 16692 and issue 16437

### LINKED ISSUE #16437: O2M unable to select existing M2O field
### Describe the Bug

Using cockroachDB it is not possible to create the reverse relation to a M2O after the fact.

https://user-images.githubusercontent.com/26413686/200910989-2b02f801-5eaf-408e-b206-866659a56bed.mov

As it's not a problem when selecting the reverse relation on creation this must be on the frontend "disable field" side.

### To Reproduce

- Create 2 collections (collection A, collection B)
- Create a M2O relation from collection A to collection B
- Try to create the reverse O2M relation

### Errors Shown

Existing field is not selectable.

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.x

### What database are you using?

CockroachDB

### What browser are you using?

firefox/chrome

### How are you deploying Directus?

docker

### LINKED ISSUE #16692: When creating O2M the foreign key selector field options are greyed out
### Describe the Bug

Today I created some other fields to my database through the cloud UI. I created a singleton collection (call it collection ,,A") with a few String type fields. 

After this I created another (not singleton) collection (call it collection ,,B" )with some fields and a field for the foreign key, as I did before. (I always created a plus field in the collection for the O2M model I choosed integer field type, entered a starting value (always 1 ) and clicked to the hidden on details button)

When I did this I wanted to add an O2M field to collection A but when I selected collection B in the related collection field option, I cannot choose any foreign key from collection B, all of the options greyed out.

I attached a Picture:

image

Interesting thing is that the same issue appear when I delete and recreate a some data structure, Same issue happening when I downloaded the latest update I tryed to create what I mentioned above, result: not working.

I don't know what is the solution. I kindly ask you for your help!

Thank you! 

### To Reproduce

Please follow the Describe the bug session!

### Errors Shown

No error just greyed out foreign key selector field. 

### What version of Directus are you using?

9.21.2.

### What version of Node.js are you using?

8.15.0.

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally, trying from the cloud version

### PR DESCRIPTION
**Pull request by jay-p-b-7span**
## Description

Fixes #16437 and fixes #16692 

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

image
image
image
image
image
image

### CODE REVIEW

File: app/src/modules/settings/routes/data-model/field-detail/shared/related-field-select.vue [hunk 1]
```diff
@@ -94,7 +94,7 @@ export default defineComponent({
 					!!field.schema?.is_primary_key ||
 					props.disabledFields.includes(field.field) ||
 					props.typeDenyList.includes(field.type) ||
-					!props.typeAllowList.includes(field.type),
+					(props.typeAllowList.length ? !props.typeAllowList.includes(field.type) : false),
```
Comment (rijkvanzanten) [inline app/src/modules/settings/routes/data-model/field-detail/shared/related-field-select.vue:97]: `typeAllowList` should default to an empty array when it's not provided in props. When is it not an array?

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/modules/settings/routes/data-model/field-detail/shared/related-field-select.vue (hunk 1 above)
Comment (jay-p-b-7span) [reply app/src/modules/settings/routes/data-model/field-detail/shared/related-field-select.vue:97]: I agree that `typeAllowList` should default to an empty array when it's not provided in props. To solve this issue, I think we have to pass `typeAllowList` prop with values. Let me know about it. I have attached a screenshot for `type-allow-list` prop passed in various routes. 

image

**Review by rijkvanzanten — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by Nitwel** [comment]
@jay-p-b-7span Thanks for the PR ❤️! Awesome fix for the mistake I made when implementing typeAllowList.
