### PR TITLE
Skip checking of virtual alias fields

### LINKED ISSUE #16315: "[INVALID_PAYLOAD] Alias type cannot be changed" when adding conditions to a divider
### Describe the Bug

Add a divider to one of your content models. Edit the field and go to conditions. Create any new condition and click save. You will get error: [INVALID_PAYLOAD] Alias type cannot be changed.

Screenshot 2022-11-04 at 08 37 13
Screenshot 2022-11-04 at 08 39 51

### To Reproduce

see bug

### Errors Shown

[INVALID_PAYLOAD] Alias type cannot be changed

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v16.18.0

### What database are you using?

Postgres 15

### What browser are you using?

Chrome mac os x

### How are you deploying Directus?

locally npx

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #16315. Default missing field in schema as `alias` if field doesn't exist in the schema.

`alias` type fields with the `no-data` flag are removed from the schema, hence the defaulting to `alias` type.

https://github.com/directus/directus/blob/4b5c0e1022d5fd342ce660a5cb7dd0354acc4512/api/src/utils/get-schema.ts#L130

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by joaopaulomoraes** [comment]
Some update here?

File: api/src/services/fields.ts [hunk 1]
```diff
@@ -362,10 +362,10 @@ export class FieldsService {
 				: null;
 
 			if (
-				(hookAdjustedField.type === 'alias' ||
+				((hookAdjustedField.type === 'alias' && this.schema.collections[collection].fields[field.field]) ||
 					this.schema.collections[collection].fields[field.field]?.type === 'alias') &&
 				hookAdjustedField.type &&
-				hookAdjustedField.type !== this.schema.collections[collection].fields[field.field]?.type
+				hookAdjustedField.type !== this.schema.collections[collection].fields[field.field].type
```
Comment (joselcvarela) [inline api/src/services/fields.ts:368]: It seems that we are adding too many exceptions for this use case.
Do you know why do we need this if condition?
If this is related to the M2O↔️O2M recursive bug, maybe we can be explicit to it like check the relationship.
Also the error message is misleading since Dividers are Alias and can be changed 🤔

Comment (licitdev) [reply api/src/services/fields.ts:368]: Additionally, A possible separate issue causing this is due to the app sending the `type` field even though it's an unchanged field. 🤔

Comment (licitdev) [reply api/src/services/fields.ts:368]: To address the checking of relationship, that's another way to go around the issue but I feel that it would be better to be broader like current, by prevent type changes from / to alias types. The only addition now is to confirm if they exist in the schema. Similar to adding a TS optional chaining. 🤔 

Please make any changes accordingly, would love get this fix merged sooner. 👍 
Thanks for the review!

**Review by joselcvarela — APPROVED** [review]
Looks to be working as expected 👍
Tested with Groups, Dividers and M2O↔️O2M

**Review by rijkvanzanten — APPROVED** [review]

**Comment by joaopaulomoraes** [comment]
When will it be available on cloud?

**Comment by rijkvanzanten** [comment]
> When will it be available on cloud?

Within the coming days

**Comment by andrii-bodnar** [comment]
Faced the same issue, looking forward to the new release 🙂

**Comment by andrii-bodnar** [comment]
Hi @rijkvanzanten!

How about a new version release of Directus? Is it on your roadmap in the nearest future?

**Comment by azrikahar** [comment]
> How about a new version release of Directus? Is it on your roadmap in the nearest future?

Released in the latest [`v9.21.0`](https://github.com/directus/directus/releases/tag/v9.21.0) 👍

**Comment by joaopaulomoraes** [comment]
Cloud?

**Comment by azrikahar** [comment]
@joaopaulomoraes we're looking to resolve #16503 and release a follow up patch which will be pushed to cloud altogether 👍

**Comment by joaopaulomoraes** [comment]
Amazing! Thanks, @azrikahar ❤️
