### PR TITLE
Fix `DB_CLIENT` expected before project initialized

### LINKED ISSUE #23255: ERROR: "DB_CLIENT" Environment Variable is missing during project init
### Describe the Bug

Initializing a project via `npm init directus-project@latest <project-name>` errors with `ERROR: "DB_CLIENT" Environment Variable` after database is selected and credentials provided. Upon investigation this seems to occur on during the `runMigrations` stage.

Based on the investigation this is caused by the recent addition of `getSchemaInspector` to the `Permission Policies` migration in https://github.com/directus/directus/pull/23253. When `getSchemaInspector` is called for the first time it will trigger a `getDatabase` which requires a `.env` file to be present. As the `.env` file has not been generated yet the error is thrown.

### To Reproduce

1. npm init directus-project@latest tester
2. Select sqlite (applies to any db)
3. Select file location
4. Observe error 

Screenshot 2024-08-08 at 4 12 45 PM

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

_No response_

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Updated `getSchemaInspector` to accept passing in the database to bypass `getDatabase` being called

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- None

---

Fixes #23255

### CODE REVIEW

File: api/src/database/index.ts [hunk 1]
```diff
@@ -191,12 +191,12 @@ export function getDatabase(): Knex {
...
 }
 
-export function getSchemaInspector(): SchemaInspector {
+export function getSchemaInspector(database?: Knex): SchemaInspector {
 	if (inspector) {
 		return inspector;
 	}
 
-	const database = getDatabase();
+	database = database ?? getDatabase();
```
Comment (hanneskuettner) [inline api/src/database/index.ts:199]: Short and sweet

```suggestion
	database ??= getDatabase();
```

**Review by hanneskuettner — APPROVED** [review]
Good find, great fix! 🎸
