### PR TITLE
Correct field editability for conditional update policies and version items

### LINKED ISSUE #26721: Permission conditions are checked against the main object instead of the versioned object being edited
### Describe the Bug

We are trying to upgrade from 11.14.0 to 11.15.4 and we are running into some permissions issues.

It looks like now the permission check has changed for versioned objects:
- In 11.14.0 it would only check your permissions on `directus_versions` to see if you can create and update version objects
- In 11.15.4 it seems to also check your permissions on the collection itself (which is fine)

The problem is that the permission check on the collection itself only checks the conditions against the main object and not the version you are editing.

### To Reproduce

- Create a collection with a field of `status` (which defaults to `Draft`) and other fields to edit (such as title)
- Create a policy where the user has permission to:
  - Create and update versions
  - Update the collection you created only if status is not `Active`
- With an admin create an item in that collection and set the status to `Active`
- Assign the policy you created to a user and login as that user
- As that user
  - you should not be able to edit the main object with status set to `Active`
  - you should be able to create a version of that object
  - The versioned object should have a status of `Draft`
  - The user should be able to edit that versioned object with status of `Draft` (this is not the case)

### Directus Version

v11.15.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

### PR DESCRIPTION
**Pull request by HZooly**
## Scope

What's changed:

- Fix version item editing to bypass the collection's write permissions. Fields were incorrectly locked when the main item failed a permission condition, even though version editing should only be gated by `directus_versions` permissions
- Fix fields being incorrectly locked when a partial-access permission has no `fields` restriction (`fields: undefined` was treated as "no fields allowed" instead of "all fields allowed")
- Introduce `isVersion` flag to `useItem`, `usePermissions`, `useItemPermissions`, `getFields` to identify when a version is being edited

## Potential Risks / Drawbacks

- Version items now show all fields as editable regardless of the main item's condition result or field-level policy. Backend enforces field restrictions at promote time
- The `fields: undefined` fix changes behavior for partial-access policies with no field restriction: previously all fields were locked even when the item passed the condition; now they are all editable

## Tested Scenarios

- Version of a `draft` item (fails condition) shows all fields as editable, including fields excluded from the update field permission
- Main item with `status = draft` (fails condition) correctly shows all fields as read-only
- Main item with `status = published` (passes condition) shows allowed fields as editable and excluded fields as read-only
- Partial-access permission with no `fields` restriction no longer locks all fields when the item passes the condition
- New item creation uses the `create` permission directly, unaffected by this change

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26721

### CODE REVIEW

**Comment by AlexGaillard** [comment]
I wonder if we're actually achieving the behavior the OP is asking for. 🤔 With this approach when a version has `status === published` you can still edit it.

Technically, what they're asking for is that a version be non-editable when `status === published`. It's arguable as to whether that makes sense, but you could currently have a version with `status === published` and a main with `status === draft`.

It's almost like the conditions need to be merged like:

- Can edit versions
- Can't edit when version `status === published`

Not sure how feasible this, or necessary. Seeing as this involves versioning, I'll defer to Florian on this one as this will affect the work he is currently doing.

If this behavior is what we want, then I think this approach is fine, though it might affect people's existing policies.

File: app/src/composables/use-permissions/item/lib/get-fields.ts [hunk 1]
```diff
@@ -7,7 +7,12 @@ import type { FormField } from '@/components/v-form/types';
 import { usePermissionsStore } from '@/stores/permissions';
 import { useUserStore } from '@/stores/user';
 
-export function getFields(collection: Collection, isNew: IsNew, fetchedItemPermissions: Ref<ItemPermissions>) {
+export function getFields(
+	collection: Collection,
+	isNew: IsNew,
+	fetchedItemPermissions: Ref<ItemPermissions>,
+	isVersion: IsNew = false,
```
Comment (alvarosabu) [inline app/src/composables/use-permissions/item/lib/get-fields.ts]: `MaybeRef<boolean>` would be clearer.

File: app/src/composables/use-permissions/item/use-item-permissions.ts [hunk 2]
```diff
@@ -21,6 +21,7 @@ export function useItemPermissions(
 	collection: Collection,
 	primaryKey: PrimaryKey,
 	isNew: IsNew,
+	isVersion: IsNew = false,
```
Comment (alvarosabu) [inline app/src/composables/use-permissions/item/use-item-permissions.ts]: Question:

Since we now have this guard for versions, shouldn't be also used for `fetchItemPermissions` or the `isAllowed`?

**Review by alvarosabu — CHANGES_REQUESTED** [review]

File: app/src/composables/use-permissions/item/use-item-permissions.ts (hunk 2 above)
Comment (HZooly) [reply app/src/composables/use-permissions/item/use-item-permissions.ts]: Yes I think it makes sense!

**Review by alvarosabu — APPROVED** [review]
LGTM

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
