### PR TITLE
Sso login issue 4570

### LINKED ISSUE #4570: Signing in with SSO without an account
And the last one :)

1) The issue and what you expected to happen
    The _ _ does _ _ when _ _ while it should _ _
    When signing in with SSO without an account in Directus does one just get redirected to a page with a json error. 

image

I haven't researched this too in depth, but i think it is an uncaught exception from this function: https://github.com/directus/directus/blob/76b31eda78d53f7866040f897376fa514e7b1202/api/src/controllers/auth.ts#L261-L263

I would expect to be redirected back and perhaps see something like "Login failed" or "The user does not exist" error on the login page.

image

2) Exact steps to reproduce this issue
    Set up a SSO provider
    Try to sign into a user that doesn't exist in the Directus users table. (I just changed the email of my user to test this :) )
    Sign out and Sign in with the SSO provider
    You should see this error on the callback

3) Your environment:
Directus 9.0.0 rc 45
MySQL 8
Docker
Chrome 89

4) Any other relevant information we might need to reproduce this issue
The SSO provider is Google with OAuth 2.0 :)

### PR DESCRIPTION
**Pull request by workatease**
FIxes #4570 
we need to make code changes in APP to handle the exception in UI

### CODE REVIEW

File: api/src/controllers/auth.ts [hunk 1]
```diff
@@ -253,14 +254,31 @@ router.get(
...
-		const email = getEmailFromProfile(req.params.provider, req.session.grant.response?.profile);
+			req.session?.destroy(() => {});
 
-		req.session?.destroy(() => {});
+			authResponse = await authenticationService.authenticate({
+				email,
+			});
+		} catch (error) {
+			if (redirect) {
+				let reason = 'UNKNOWN_EXCEPTION';
```
Comment (workatease) [inline api/src/controllers/auth.ts:268]: @rijkvanzanten Do you think this flow is good.

**Comment by workatease** [comment]
is the error handling good @rijkvanzanten  should I work on any thing more to merge this.

**Comment by rijkvanzanten** [comment]
Haven't had the time to look at it yet :C I'll let you know here!

**Review by rijkvanzanten — APPROVED** [review]
