### PR TITLE
Fix display template not appearing for relations inside translations on new items

### LINKED ISSUE #26051: App: M2A Display template is not shown when translation is created
### Describe the Bug

When having a M2A field in a translations field (table), the first time records are added to the M2A field in a new selected language, Display template of those records does not appear on the list.
The Display template only appears when the item is saved.
See the following video for a better comprehension.

https://github.com/user-attachments/assets/79bd86e8-995f-4393-b9a2-490a8707a926

### To Reproduce

Download the following database and reproduce the steps on the video.

Database:
[m2a-translations-issue.sql.zip](https://github.com/user-attachments/files/23157841/m2a-translations-issue.sql.zip)

Credentials:
admin@directus.io
password

### Directus Version

v11.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres

### PR DESCRIPTION
**Pull request by gaetansenn**
## Scope

What's changed:

- Fixed `translation-form.vue` to pass `'+'` as primaryKey for new translation items instead of `null`

## Potential Risks / Drawbacks

- None identified. Existing tests pass and new tests added.

## Tested Scenarios

- Add Existing item to M2A/M2M field in new parent, display template now shows correctly
- Add multiple items from same/different collections, all display correctly
- Create New item, continues working 
- Pagination, existing behavior preserved

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26051

### CODE REVIEW

**Review by robluton — APPROVED** [review]
LGTM! 🎸

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you @gaetansenn :heart:
Unfortunately, this is not the ideal approach, because the underlying problem is different.

- [x] Let’s revert the changes and ensure the foreign key of the m2a junction collection is included in the edits object, as demonstrated in the video below. It appears that the property is missing when using in the translation form and the m2a interface, which may be due to incorrect handling of the key.

- [x] Let’s also address this issue in the M2M field, where it occurs in exactly the same way.

https://github.com/user-attachments/assets/5525511a-dac7-448a-8beb-396da811e2e7

File: app/src/interfaces/translations/translation-form.vue [hunk 1]
```diff
@@ -182,7 +182,9 @@ function onToggleDelete(item: DisplayItem, itemInitial?: DisplayItem) {
 			v-if="selectedLanguage"
 			:key="selectedLanguage.value"
 			:primary-key="
-				relationInfo?.junctionPrimaryKeyField.field ? itemInitial?.[relationInfo?.junctionPrimaryKeyField.field] : null
+				relationInfo?.junctionPrimaryKeyField.field
+					? (itemInitial?.[relationInfo?.junctionPrimaryKeyField.field] ?? '+')
+					: null
 			"
```
Comment (formfcw) [inline app/src/interfaces/translations/translation-form.vue]: Let’s simplify this condition for better readability.

```suggestion
			:primary-key="itemPrimaryKey ?? '+'"
```

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you @gaetansenn :heart:

- [x] Let’s add a test for this case.

File: app/src/interfaces/translations/translation-form.vue (hunk 1 above)
Comment (gaetansenn) [reply app/src/interfaces/translations/translation-form.vue]: Good point

**Review by formfcw — APPROVED** [review]
Thank you @gaetansenn :heart:

LGTM 🎉

**Review by AlexGaillard — APPROVED** [review]
TY for the 🧪
