### PR TITLE
Log out user when deleting own account

### LINKED ISSUE #24258: Users are not automatically logged out after deleting their own account
### Describe the Bug

When a user with enough privileges deletes their own account, they are not automatically logged out of the platform. This can lead to runtime errors and unexpected behavior since the system continues to operate as if the user still exists. For a better UX/UI experience and to prevent potential issues, the system should automatically log out the user immediately after they delete their own account.

### To Reproduce

1- Log in to a Directus instance as an admin user.
2- Navigate to the user management section.
3- Attempt to delete your own account.
4- Observe that the account is deleted, but the session remains active, and the user is not logged out.
5- Perform any actions in the UI which trigger a database call for the deleted user and note potential runtime errors or unexpected behavior.

### Directus Version

v11.3.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

### PR DESCRIPTION
**Pull request by robluton**
## Scope

What's changed:

- Fixed type error in batch delete functionality where selection was incorrectly typed as Item[] instead of string[]
- Added logout flow when current user is deleted
- Ensured consistent behavior between single user deletion (item view) and batch deletion (collection view)

## Potential Risks / Drawbacks

N/A

## Review Notes / Questions

1. Logging Out When Deleting Yourself from Profile
Steps:
- Create a user with admin rights 
- login with the user just created and navigate to the profile page
- Click on the trash icon at the top of the profile to delete
Expected Result:
Your account is deleted
You are logged out and redirected to the login page
You should not be able to log back in since your account was removed

2. Logging Out When Deleting Yourself from Profile
Steps:
- Create two users (at least one should have admin rights) 
- log in using the user with admin rights and navigate to the users page.
- select the user you logged in with in addition to the other user you created.
- click the delete button.
Expected Result:
Both accounts are deleted
You are logged out and redirected to the login page
You should not be able to log back in with either account that you removed.
---

Fixes  #24258

### CODE REVIEW

File: app/src/modules/users/routes/collection.vue [hunk 1]
```diff
@@ -16,6 +16,8 @@ import { useI18n } from 'vue-i18n';
 import { onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router';
 import UsersNavigation from '../components/navigation.vue';
 import useNavigation from '../composables/use-navigation';
+import { logout } from '@/auth';
+import { useUserStore } from '@/stores/user';
 
 type Item = {
```
Comment (AlexGaillard) [inline app/src/modules/users/routes/collection.vue]: This is unused now

image

**Review by AlexGaillard — CHANGES_REQUESTED** [review]
Just the one change above but otherwise good catch on the type info 😄

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
