### PR TITLE
fix: update permissions in item.vue

### LINKED ISSUE #23622: Move folder and edit controls appear on files even when edit permissions are restricted
### Describe the Bug

Certain file controls should be hidden if user does not have edit access. The file fields are correctly displayed as they remain greyed out.

Screenshot 2024-09-10 at 15 45 36
Screenshot 2024-09-10 at 15 50 03

### To Reproduce

1. Remove access to edit directus files via directus_files permission filter. 
2. Options to edit file and move to folder remain available. Changing this leads to a permission error.
Screenshot 2024-09-10 at 15 48 32

### Directus Version

v10.13.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Mysql 8

### PR DESCRIPTION
**Pull request by amosmurmu**
## Scope

What's changed:

- used updateAllowed property to fix issues

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

 How do you find Will Smith in the snow?
 You look for the fresh prints.

---

Fixes #23622

### CODE REVIEW

File: app/src/modules/files/routes/item.vue [hunk 1]
```diff
@@ -281,7 +281,7 @@ function useMovetoFolder() {
 						<v-button secondary @click="moveToDialogActive = false">
 							{{ t('cancel') }}
 						</v-button>
-						<v-button :loading="moving" @click="moveToFolder">
+						<v-button :loading="moving" :disabled="!updateAllowed" @click="moveToFolder">
```
Comment (formfcw) [inline app/src/modules/files/routes/item.vue:284]: Instead of adding the condition to the button in the modal, add it to the button in the `activator` slot above, to ensure we are not able to open the modal. Also add the `'not_allowed'` label.

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you @amosmurmu :heart: for your first contribution :tada:

Great improvement! 🚀 
However, a few things — see the code comments.

Would be great, if you could also implement the same logic to the listing view, where these buttons appear as soon as you (batch) select some files/images: https://github.com/amosmurmu/directus/blob/dec21113a4f458fe5ebab9c6315589d42236b9a8/app/src/modules/files/routes/collection.vue#L400-L403

Also, please make sure to fulfill the requirements for accepting a PR — CLA and Changeset: https://directus.io/docs/community/contribution/pull-requests

File: app/src/modules/files/routes/item.vue (hunk 1 above)
Comment (amosmurmu) [reply app/src/modules/files/routes/item.vue:284]: ohh okay

File: app/src/modules/files/routes/collection.vue [hunk 2]
```diff
@@ -413,7 +421,7 @@ function useFileUpload() {
 							<v-button secondary @click="moveToDialogActive = false">
 								{{ t('cancel') }}
 							</v-button>
-							<v-button :loading="moving" @click="moveToFolder">
+							<v-button :loading="moving" :disabled="!batchEditAllowed" @click="moveToFolder">
```
Comment (formfcw) [inline app/src/modules/files/routes/collection.vue:424]: Let’s remove the redundancy here, as well as in the item.vue component.

```suggestion
							<v-button :loading="moving" @click="moveToFolder">
```

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you for your changes! Just one thing …

**Review by formfcw — APPROVED** [review]
Thank you @amosmurmu :heart:
LGTM :rocket:

@AlexGaillard CLA is included in the [other PR](https://github.com/directus/directus/pull/25181).
