### PR TITLE
Storage / S3: Only pass `key` and `secret` if defined

### LINKED ISSUE #16985: Directus 9.22.1 Amazon S3 403 assets
### Describe the Bug

After upgrading from 9.21 assets are showing a 403 error. I can successfully add new images and view them, but all images that have been uploaded before the update, are not shown. Accessing them gives the following error (from the browser's network inspection tab):

```json
[
    {
        "message": "You don't have permission to access this.",
        "extensions": {
            "code": "FORBIDDEN"
        }
    }
]
```

I believe this is similar to https://github.com/directus/directus/issues/16876 however I am on 9.22.1 and the issue persists.

Storage config

```
STORAGE_LOCATIONS=s3
STORAGE_S3_BUCKET=OMITTED
STORAGE_S3_DRIVER=s3
STORAGE_S3_KEY=OMITTED
STORAGE_S3_REGION=eu-central-1
STORAGE_S3_ROOT=/
STORAGE_S3_SECRET=OMITTED
```

### To Reproduce

Not sure.

1. You would need to use an old version of the Directus docker image with the above s3 configuration (with your own set of credentials). I am using Elastic Beanstalk
2. Then upload some files
3. Upgrade docker image to current version

### Errors Shown

_No response_

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18

### What database are you using?

Cockroach DB Serverless

### What browser are you using?

Chrome

### How are you deploying Directus?

Elastic Beanstalk (Docker Image)

### PR DESCRIPTION
**Pull request by joselcvarela**
With [File Storage 2.0](https://github.com/directus/directus/pull/16825), `key` and `secret` are now required to instantiate S3 driver.
Although, AWS SDK can read machine configuration like `~/.aws`:
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html

On versions before that PR, this was working, so let's put it back to 👍

Closes https://github.com/directus/directus/issues/16985
Closes ENG-356
Closes ENG-374

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by licitdev — APPROVED** [review]
LGTM. Tested working as intended. 👍

File: packages/storage-driver-s3/src/index.ts [hunk 1]
```diff
@@ -39,12 +39,16 @@ export class DriverS3 implements Driver {
 	private serverSideEncryption: string | undefined;
 
 	constructor(config: DriverS3Config) {
-		const s3ClientConfig: S3ClientConfig = {
-			credentials: {
+		const s3ClientConfig: S3ClientConfig = {};
+
+		if (config.key || config.secret) {
+			if (!(config.key && config.secret)) throw new Error('Both `key` and `secret` are required when defined');
```
Comment (br41nslug) [inline packages/storage-driver-s3/src/index.ts:45]:
```suggestion
		if (isEmpty(config.key) || isEmpty(config.secret)) {
                    throw new Error('Both `key` and `secret` are required when defined');
                } else {
```
If i got my boolean comparisons right this would be a more readable option in my opinion.

**Review by br41nslug — COMMENTED** [review]
Looks good and works as expected when tested on Windows 😄

File: packages/storage-driver-s3/src/index.ts (hunk 1 above)
Comment (br41nslug) [reply packages/storage-driver-s3/src/index.ts:45]: Actually i made a mistake with the usage of isEmpty here.

**Review by br41nslug — APPROVED** [review]

File: packages/storage-driver-s3/src/index.ts [hunk 2]
```diff
@@ -39,12 +39,16 @@ export class DriverS3 implements Driver {
 	private serverSideEncryption: string | undefined;
 
 	constructor(config: DriverS3Config) {
-		const s3ClientConfig: S3ClientConfig = {
-			credentials: {
+		const s3ClientConfig: S3ClientConfig = {};
+
+		if ((config.key && !config.secret) || (config.secret && !config.key)) {
```
Comment (licitdev) [inline packages/storage-driver-s3/src/index.ts:44]: Thoughts on simplifying with `XOR` operator?

```suggestion
		if (config.key ^ config.secret) {
```

Comment (joselcvarela) [reply packages/storage-driver-s3/src/index.ts:44]: I think bitwise operators are harder to read but defer to other reviewers to tell their opinion 😅

Comment (br41nslug) [reply packages/storage-driver-s3/src/index.ts:44]: I do like this approach but i have my doubts on the maintainability as the bitwise XOR operator is not very commonly used and may be tricky for new members jumping into the codebase.

Comment (paescuj) [reply packages/storage-driver-s3/src/index.ts:44]: > Thoughts on simplifying with `XOR` operator?

Looks cleaner IMO 😄👍 Personally, I'd go with this while adding a comment to explain it.

Comment (rijkvanzanten) [reply packages/storage-driver-s3/src/index.ts:44]: > Looks cleaner IMO 😄👍 Personally, I'd go with this while adding a short comment to explain it.

Hard disagree! If it needs a comment explaining what it's supposed to do, you're probably better off making it slightly more verbose and maintainable in the process 🙂

Comment (paescuj) [reply packages/storage-driver-s3/src/index.ts:44]: > Hard disagree! If it needs a comment explaining what it's supposed to do, you're probably better off making it slightly more verbose and maintainable in the process 🙂

Honestly, the more verbose option here isn't much more readable, so I'd have thought to add a comment in both cases anyway... But after looking at the code again, I realize that it's actually pretty obvious what the `if` statement does because of the verbose `error` statement one line below.

> [...] If it needs a comment explaining what it's supposed to do, you're probably better off making it slightly more verbose and maintainable in the process 🙂

I totally agree with you in principle (big fan of clean code), but I do think it doesn't harm do add a comment from time to time. Especially because the code only tells you what it does and not why it is done that way.

Comment (rijkvanzanten) [reply packages/storage-driver-s3/src/index.ts:44]: > I totally agree with you in principle (big fan of clean code), but I do think it doesn't harm to add a comment from time to time. Especially because the code only tells you what it does and not why it is done that way.

I'm not against comments in general! I do have a problem when a comment is needed to explain _what_ a line of JS is supposed to do though. If that's the case, I'd rather rework the JS itself to make it more human readable 🙂 

Comments explaining _why_ something is required or needed are very valuable (as long as they're maintained)

File: packages/storage-driver-s3/src/index.ts [hunk 3]
```diff
@@ -39,12 +39,16 @@ export class DriverS3 implements Driver {
...
+			throw new Error('Both `key` and `secret` are required when defined');
```
Comment (rijkvanzanten) [inline packages/storage-driver-s3/src/index.ts:45]: Any reason we have to error out when only key or secret is configured through config? I could imagine a scenario where somebody might rely on AWS's default injection for SECRET, but keep the KEY in the config 🤔

Comment (rijkvanzanten) [reply packages/storage-driver-s3/src/index.ts:45]: The TypeScript signature for `credentials` answers this:

```
Type '{ accessKeyId: string; }' is not assignable to type 'AwsCredentialIdentity | Provider<AwsCredentialIdentity>'.
  Property 'secretAccessKey' is missing in type '{ accessKeyId: string; }' but required in type 
```

**Review by rijkvanzanten — APPROVED** [review]

File: packages/storage-driver-s3/src/index.ts (hunk 2 above)
Comment (paescuj) [reply packages/storage-driver-s3/src/index.ts:44]: I am very happy to hear that! 😃 You summarized it very well and I can say that I completely agree with you!

**Comment by paescuj** [comment]
Great work! 😃 

I'd like to raise the following points that have come to my attention:
- The error is only thrown as soon as the first interaction with files takes place. The reason is that the `storage` is currently "lazy-loaded". I wonder if this was done on purpose and if something speaks against initializing this at server startup? For example, somewhere around here:
  https://github.com/directus/directus/blob/6c2df2dca39bdc542e549b4e3f9add3b7b31e626/api/src/app.ts#L73 Since it's clearly a configuration error (and not a runtime error - at least in this case), we could point out the problem to the administrator right from the beginning, which would give the chance to eliminate the problem right away.
- The current error message does not indicate where the problem originates from:
  
  I think this is especially confusing for end users, but a clearer message would also be helpful for administrators.
  In this case it is even more confusing because the same keys also exist as global configurations.
  We should be able to catch issues when initializing the driver and rethrow it with the associated info (location name, ...):
  https://github.com/directus/directus/blob/6c2df2dca39bdc542e549b4e3f9add3b7b31e626/packages/storage/src/index.ts#L20  For example:
  ```console
  Failed to register storage location "s3": Both `key` and `secret` are required when defined
  ```

I look forward to your thoughts on this!
