### PR TITLE
Assign admin policy to a new role created via command line when needed

### LINKED ISSUE #24021: Command line admin role creation not working
### Describe the Bug

To create a new admin role via command line user needs to run the command from docs:

`npx directus roles create --role <role-name> --admin true`

The `admin` flag is not working and doesn't actually create an admin role. It creates a role without any policies.

### To Reproduce

1. Run Directus 11.2.1 and PostgreSQL 12 using docker compose
2. Open container shell which is running directus 
3. Run the command `npx directus roles create --role <role-name> --admin true`
4. Check the role in the Settings -> User Roles 

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 12

### PR DESCRIPTION
**Pull request by NickSettler**
## Scope

Creating a new role via command line with admin access doesn't work. It happens, because this CLI command still relies on the old database schema, which had `admin_access` property as a part of `Role` type. 

Addition of policies changed this concept and migrated `admin_access` field to a policy database table.

The command for creating an admin role via the command line remained unchanged since that time.

What's changed:

- Admin role creation via CLI adds a corresponding row in the directus_access table
- In case there is no admin policy, the logger outputs an error

## Potential Risks / Drawbacks

- I dont see any. Admin role creation is not working now. Default role creation remains unchanged

## Review Notes / Questions

- ...

---

Fixes #24021

### CODE REVIEW

File: api/src/cli/commands/roles/create.ts [hunk 1]
```diff
@@ -14,10 +16,32 @@ export default async function rolesCreate({ role: name, admin }: { role: string;
...
 	try {
 		const schema = await getSchema();
-		const service = new RolesService({ schema: schema, knex: database });
+		const rolesService = new RolesService({ schema: schema, knex: database });
+		const policiesService = new PoliciesService({ schema: schema, knex: database });
+		const accessService = new AccessService({ schema: schema, knex: database });
 
-		const id = await service.createOne(admin ? { name, admin_access: admin } : { name });
-		process.stdout.write(`${String(id)}\n`);
+		const adminPolicyId = await policiesService.knex
```
Comment (rijkvanzanten) [inline api/src/cli/commands/roles/create.ts:23]: We should use `readOne` from the service here, as there might be differences in how databases store the values under the hood (f.e. in SQLite a boolean is `0` / `1` and will fail with a "where `true`"). The Directus methods will type cast these differences away.

That being said, seeing you're trying to create a whole new role, should we instead opt to just create a new admin policy that's just for this role? 🤔 Might be less confusing than reusing one that might be named for a certain use case or group.

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Comment by rijkvanzanten** [comment]
Thanks @NickSettler! And welcome to the repo 🙂 Little usage question up above, but otherwise LGTM 🚀

**Comment by NickSettler** [comment]
> Thanks @NickSettler! And welcome to the repo 🙂 Little usage question up above, but otherwise LGTM 🚀

Thank you! 🙂

**Review by rijkvanzanten — APPROVED** [review]
