### PR TITLE
Fix Visual Editor stripping trailing slashes from URLs

### LINKED ISSUE #26750: Visual Editor: normalizeUrl strips trailing slashes, breaking frameworks with trailingSlash config
### Describe the Bug

The Visual Editor module's normalizeUrl function in app/src/modules/visual/index.ts explicitly strips trailing slashes from all URLs:

```js
function normalizeUrl(url: string) {
  try {
    return new URL(url).href.replace(/\/$/, '');
  } catch {
    return '';
  }
}
```

This causes a 404 when reloading or clicking the URL dropdown in the Visual Editor, for any framework configured to require trailing slashes (e.g. Astro with trailingSlash: 'always', Next.js with trailingSlash: true, Nuxt, etc.).

### To Reproduce

1. Configure your frontend with trailing slashes (e.g. Astro: `trailingSlash: 'always'`)
2. Set up Visual Editor with a preview URL
3. Navigate to a page in the Visual Editor — works fine, URL shows correctly in address bar (e.g. `/admin/visual/https://preview.example.com/de/`)
4. Notice the URL dropdown displays the URL without trailing slash (https://preview.example.com/de)
5. Click the URL in the dropdown or reload the page → 404

## Expected Behavior

The trailing slash should be preserved. `/de/` and `/de` are different resources per HTTP specification. The Visual Editor should not normalize URLs in a way that alters their path semantics.

## Actual Behavior

`normalizeUrl` strips the trailing slash via `.replace(/\/$/, '')`. This normalized URL is:

- Shown in the URL dropdown (via dynamicUrl prop)
- Used for router.replace() when navigating
- Becomes the iframe src on reload

## Root Cause

In `app/src/modules/visual/index.ts`:

```js
// normalizeUrl
return new URL(url).href.replace(/\/$/, '');

// route props
dynamicUrl: normalizeUrl(`${route.params.url}...`),

// getSettingsUrls
return settingsUrls.map(normalizeUrl).filter(Boolean);
```

## Suggested Fix

Remove the trailing slash stripping:

```js
function normalizeUrl(url: string) {
  try {
    return new URL(url).href;
  } catch {
    return '';
  }
}
```

If the intent was to normalize only origin-level URLs from settings (e.g. https://example.com/ → https://example.com), then the stripping should only apply where the path is exactly /, not to all URLs including those with actual paths.

### Directus Version

v11.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- Removed `normalizeUrl` utility that stripped trailing slashes via `.replace(/\/$/, '')` from all Visual Editor URLs
- URLs now preserve trailing slashes through navigation, iframe src, route params, and version replacement
- Moved slash-stripping normalization into `live-preview.vue` scoped only to URL _comparison_ (dropdown active state), where it doesn't affect actual navigation

## Potential Risks / Drawbacks

- URLs resolved from origin-only settings (e.g. `https://example.com`) now include the trailing slash added by the URL API (`https://example.com/`). This is the correct canonical form per RFC 3986 and
  shouldn't cause issues, but is a behavioral change.

## Tested Scenarios

- URLs with trailing slashes (`/de/`) are preserved through `replaceVersion` for all placement types (path, query, subdomain, hash)
- `resolveUrls` preserves trailing slashes for both plain URLs and version-templated URLs
- URL dropdown active state still matches correctly regardless of trailing slash differences

## Review Notes / Questions

- The root cause was `normalizeUrl` applying `.replace(/\/$/, '')` globally — this stripped trailing slashes from iframe src, route navigation, and the URL dropdown, causing 404s for frameworks with
  `trailingSlash: 'always'` (Astro, Next.js, Nuxt)
- The local `normalizeUrl` kept in `live-preview.vue` still strips trailing slashes but is only used for comparison (`dynamicUrlIncluded`, `matchesDynamicUrl`), never for navigation or iframe loading

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26750

### CODE REVIEW

File: app/src/views/private/components/live-preview.vue [hunk 1]
```diff
@@ -255,9 +259,22 @@ function useUrls() {
...
+		if (!dynamicUrl) return false;
+		return normalizeUrl(url) === normalizeUrl(dynamicUrl);
+	}
+
+	function normalizeUrl(url: string): string {
+		const parsed = parseUrl(url);
+		if (!parsed) return '';
+
+		return parsed.href.replace(/\/$/, '');
+	}
```
Comment (hanneskuettner) [inline app/src/views/private/components/live-preview.vue:276]: Does it make sense to use [`ufo`](https://github.com/unjs/ufo) here so we don't have to do this ourselves?

Comment (formfcw) [reply app/src/views/private/components/live-preview.vue:276]: `parseUrl` is just a thin wrapper around the native `new URL()` API. Since removing the trailing slash is just a single line, using `ufo` here would probably be a bit overkill.

Comment (hanneskuettner) [reply app/src/views/private/components/live-preview.vue:276]: Not saying we should not do it ourselves, but just poking holes in this: If somebody enters `https://example.com/something//` (double `/`) this fails to reliably remove all trailing slashes. Haven't traced the code to see if that actually might happen, but worth considering

Comment (formfcw) [reply app/src/views/private/components/live-preview.vue:276]: The `normalizeUrl` function here is used only for comparison. `https://example.com/something` and `https://example.com/something/` should match and be treated as the same. However, if someone enters `https://example.com/something//` it is not considered the same URL as `https://example.com/something` or `https://example.com/something/`. If a website decides to remove multiple trailing slashes from a URL, that behavior is up to the site itself. This does not affect the visual editor, and it will not cause any failures.

**Review by AlexGaillard — APPROVED** [review]
Image

SHIP-SHIP-SHIP-ADELPHIA

How could we forget RFC-3986! 🤓
