### PR TITLE
Prevent creation of relationships on primary keys

### LINKED ISSUE #11357: Don't allow PKs to be used as FKs
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Right now, you can technically provide `id` as the _foreign_ key of a one to many relationship. This is not something that Directus supports, and should be prevented.

### To Reproduce

Create a one-to-many field to the current collection, add `id` as the foreign key field

### Errors Shown

_No response_

### What version of Directus are you using?

9.5

### What version of Node.js are you using?

16

### What database are you using?

PG 13

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Locally

### PR DESCRIPTION
**Pull request by licitdev**
Closes #11357.

Was thinking if the same change should be added to relation's `updateOne()`. Currently not added as I think it may lead to issues surfacing from users with existing relations on primary keys.

### CODE REVIEW

File: api/src/services/relations.ts [hunk 1]
```diff
@@ -143,6 +143,15 @@ export class RelationsService {
 			);
 		}
 
+		const columnInfo = await this.schemaInspector.columnInfo(relation.collection, relation.field);
```
Comment (rijkvanzanten) [inline api/src/services/relations.ts:146]: Lets pull this from `this.schema` instead, to prevent the performance overhead of reading this info fresh from the database.

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/services/relations.ts (hunk 1 above)
Comment (licitdev) [reply api/src/services/relations.ts]: Yes that's an unnecessary overhead. Thank you!

**Review by rijkvanzanten — APPROVED** [review]
