### PR TITLE
Fix empty string not checked against `_regex` validation

### LINKED ISSUE #21489: Field Validation doesn't seem to respect detecting a null or an empty string as part of a regexp.
### Describe the Bug

I’m trying to add basic validation to an input field where I want the user to enter either a valid email address, or nothing at all. 

I’m using regex and in theory this should work: `(^$|^.@...*$)`, (it works as expected on https://regex101.com), only it doesn’t allow the user to delete an email that was previously entered:

Screenshot 2024-02-20 at 14 57 07

After deleting a previously saved value:
Screenshot 2024-02-20 at 15 41 08

The only way I can get the desired behaviour is by creating an “Or” group, but that gives a double error message when the user enters anything wrong which is ugly and confusing:
Screenshot 2024-02-20 at 15 22 18
Screenshot 2024-02-20 at 12 45 36

Had a short discussion on the Discord about this:
https://discord.com/channels/725371605378924594/1151320093565927504/1209480440944005130

### To Reproduce

Create a text input field called "email" within a collection.
Ensure the field allows a NULL value.
Add the following regexp validation rule to detect a correctly formatted email OR an empty string: (^$|^.*@.*\..*$)
Go to the Content section, create an item and enter a valid email into the "email" field.
Save. 
Value should be saved correctly.
Clear the email field again so it is empty. 
Save again.
Validation will fail. Expected result is that it should accept an empty field

Note:
You can test any of the following Regexp alternatives on https://regex101.com and observe that they do correctly match against an empty string as well as an email address, but try them in Directus, and they will fail when the field is empty:
`(^$|^.*@.*\..*$)`
`^(.*@.*)?$`
`(^NULL$|^.*@.*\..*$)`

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #22394: `_regex` filter matching empty string fails in `joiValidationErrorItemToErrorExtensions`
### Describe the Bug

When using a `_regex` filter that is valid in case of an empty string `^$`, the conversion from Joi to Directus error fails, as strings are not allowed to be empty in Joi by default[^1], which generates the error `type` `'string.empty'` which is not accounted for in the conversion. We would have to explicitly allow empty strings in the default string schema in case of matching a regex, e.g. `.allow('')`.

I'd like to discuss if it makes sense to allow matching empty strings in the `_regexp` filter or if this can result in breaking changes.

[^1]: https://github.com/hapijs/joi/blob/master/API.md#string

### To Reproduce

- Create a string field with `Save as empty string`
- Set validation to `Matches RegExp` with the RegExp `^$|foo`
- Create a new item with value `foo` and save the value
- Edit the item, remove the value and save
- See error message

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- We now allow empty string to be checked against the `_regex` validation filter, it is left up to the users regex to account for this.

## Potential Risks / Drawbacks

- As we are opting in for regex only this should not have any effect as it will validate against any existing regex which would not match against an empty string unless explicitly set

## Review Notes / Questions

- `joi` by default adds [a non empty constraint for string strings](https://joi.dev/api/?v=17.13.3#string)
- Using `allow('')` as recommended in the docs results in any subsequent constraints not being applied
   - https://joi.dev/api/?v=17.13.3#anyvalidvalues---aliases-equal
Screenshot 2025-03-28 at 5 19 17 PM
- `min(0)` is used here as it looks to be a special bypass
   -  https://github.com/hapijs/joi/blob/5685db766f6a2261c3c1839a56c3b879c3cf5a0a/lib/types/string.js#L137
   - https://github.com/hapijs/joi/issues/2687

---

Fixes #22394
Fixes: #21489

### CODE REVIEW

**Review by Nitwel — APPROVED** [review]

File: packages/utils/shared/generate-joi.ts [hunk 1]
```diff
@@ -367,7 +367,9 @@ export function generateJoi(filter: FieldFilter | null, options?: JoiOptions): A
 				const wrapped =
 					typeof compareValue === 'string' ? compareValue.startsWith('/') && compareValue.endsWith('/') : false;
 
-				schema[key] = getStringSchema().regex(new RegExp(wrapped ? (compareValue as any).slice(1, -1) : compareValue));
+				schema[key] = getStringSchema()
+					.min(0)
+					.regex(new RegExp(wrapped ? (compareValue as any).slice(1, -1) : compareValue), {});
```
Comment (licitdev) [inline packages/utils/shared/generate-joi.ts:372]:
```suggestion
					.regex(new RegExp(wrapped ? (compareValue as any).slice(1, -1) : compareValue));
```

Comment (ComfortablyCoding) [reply packages/utils/shared/generate-joi.ts:372]: Not sure how that got there? 🤔

**Review by licitdev — APPROVED** [review]
