### PR TITLE
Fix caching for dynamic variables

### LINKED ISSUE #23319: Dynamic variables in permissions get cached
### Describe the Bug

The dynamic variable insertion takes place before the permission are stored in the cache. As such the cached permissions contain fixed values where there should be dynamic placeholders.

### To Reproduce

- Create a permission with `$NOW` or `$CURRENT_USER.some_field` and see that the permissions are not updated when the field changes.

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

Due to an oversight in the new policies implementation the permissions were cached after the replacement of the dynamic variables happened, so for example `$NOW` got turned into the current timestamp at the time of the first function call and then it was cached like that until the cache eviction happened.

What's changed:

- Independently cache the raw permissions and the dynamic filter context and always join them in every call of `fetchPermissions`
- The filter context is cached in the normal cache, if available, and is affected by `CACHE_AUTO_PURGE`, similar to the request level cache
- Updated function that use `fetchPermissions` to not be cached themselves, since that would result in the same problem, higher up in the call stack

## Potential Risks / Drawbacks

- Now more queries hit the database for retrieving the dynamic variable context. This should be offset somewhat by the usage of the independent global cache used for caching each set of context variables.  
- More work is being performed. We might want to revisit this at a later point in time to introduce split caching for permissions that have dynamic variables and for those that don't.

## Review Notes / Questions

- I would like to lorem ipsum
- This PR does not solve https://github.com/directus/directus/issues/22492 which is an existing bug in v10

---

Fixes #23319

### CODE REVIEW

File: api/src/permissions/utils/fetch-dynamic-variable-context.ts [hunk 1]
```diff
@@ -33,36 +24,93 @@ export async function _fetchDynamicVariableContext(options: FetchDynamicVariable
...
+	key: keyof RequiredPermissionContext,
+	permissionContext: RequiredPermissionContext,
+	cacheContext: Record<string, any>,
+	fetch: (fields: string[]) => Promise<Record<string, any>>,
+) {
+	const { cache } = getCache();
+	const env = useEnv();
+
+	const fields = Array.from(permissionContext[key]!);
+	const cacheKey = cache ? `filter-context-${key.slice(1)}-${getSimpleHash(JSON.stringify(cacheContext))}` : '';
```
Comment (hanneskuettner) [inline api/src/permissions/utils/fetch-dynamic-variable-context.ts:99]: Removing the `$` here, since I don't know if there might be any kv store where a `$` has a special meaning

**Review by ComfortablyCoding — COMMENTED** [review]
This does not seem to work in the data studio with the following setup.

### Settings
```
CACHE_ENABLED=true
CACHE_STORE="redis"
CACHE_PERMISSIONS=true
CACHE_AUTO_PURGE=true
CACHE_SCHEMA=true
CACHE_TTL=30m
```

### Data Model
```
id
published (datetime)
```

### Access Rule
```
{
    "_and": [
        {
            "published": {
                "_lte": "$NOW"
            }
        }
    ]
}
```

If I create 1 article before `$NOW` and 1 article after `$NOW` once the `published` time meets the condition for that missing record it will still not show in the data studio. Only once an auto purge is triggered does it then show.

https://github.com/user-attachments/assets/6ad33bba-2761-4944-9ad1-91915fc407d0

File: api/src/permissions/utils/fetch-dynamic-variable-context.ts (hunk 1 above)
Comment (licitdev) [inline api/src/permissions/utils/fetch-dynamic-variable-context.ts:99]: This cache key is simple and has a high chance of collision. Including the `fields` in the cacheKey should be better but more testing is needed to confirm. 🤔 

On a side note, this `cache` would not be purged if `CACHE_AUTO_PURGE=false`.

Comment (hanneskuettner) [reply api/src/permissions/utils/fetch-dynamic-variable-context.ts:99]: Oh! The fields were meant to be included! Good catch!

Comment (hanneskuettner) [reply api/src/permissions/utils/fetch-dynamic-variable-context.ts]: And yes, that cache would not be cleared, but then also the request level cache (which is the same for that matter) would not be cleared either. So you already have stale data.

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
