### PR TITLE
Optimise data model sorting

### LINKED ISSUE #14774: Data Model: Folders - system completely crashes when put collection in a folder
### Describe the Bug

I created a new Folder in the Data Model. I then tried to drag an existing collection under that Folder.
Every time I tried this the system went slow, became unresponsive - and then when came back online the collection had not been moved. One time the system completely stopped.

I would expect to be able to put collections under the folder.

### To Reproduce

See above

### Errors Shown

System completely stopped one time

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

n/a

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #14774. Updates the sorting of collections in data model to a single request, preventing the system cache from being cleared multiple times. 
Increase `MAX_PAYLOAD_SIZE` to `1mb`.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: api/src/services/collections.ts [hunk 1]
```diff
@@ -345,8 +348,50 @@ export class CollectionsService {
...
+				await clearSystemCache();
+			}
+		}
+	}
+
+	/**
+	 * Update multiple collections in a single transaction
+	 */
+	async updateBatch(data: Partial<Collection>[], opts?: MutationOptions): Promise<string[]> {
+		if ((this.accountability && this.accountability.admin !== true) || !Array.isArray(data)) {
```
Comment (br41nslug) [inline api/src/services/collections.ts:361]: `|| !Array.isArray(data)` Do we want to throw a Forbidden error for this? I think an `InvalidPayload` may be more appropriate 🤔

File: app/src/modules/settings/routes/data-model/collections/collections.vue [hunk 2]
```diff
@@ -197,12 +197,14 @@ export default defineComponent({
...
+				api.patch(
+					`/collections`,
+					updatesWithSortValue.map((collection) => {
+						return {
+							collection: collection.collection,
 							meta: { sort: collection.meta.sort, group: collection.meta.group },
-						})
-					)
+						};
+					})
```
Comment (br41nslug) [inline app/src/modules/settings/routes/data-model/collections/collections.vue:207]: This may be a little premature optimization but theoretically this approach could end up at "max_payload_size". Perhaps we should consider sending this in batches of a set size.

File: api/src/services/collections.ts (hunk 1 above)
Comment (licitdev) [reply api/src/services/collections.ts]: Yup, refactored. Thanks! 👍

**Review by rijkvanzanten — APPROVED** [review]
