### PR TITLE
Fix revision drawer for create events

### LINKED ISSUE #7933: Show "changes" for the create revision
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

As of now, we are not showing any updates for item creation revisions (see below). It's just a header and blank drawer. We need to show all the _initial_ values set. Ideally, we also highlight that this is a "Create" as opposed to an "Update"... perhaps in the drawer header title?

`Item Revision` -> `Item Creation` (only for create event)

Screen Shot 2021-09-08 at 4 43 22 PM

### To Reproduce

Open an item's create revision (the first) and see it empty.

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

Node: 16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DO

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #7933

## Reported bug

Two parts of the issue are:

- The UI still shows `Item Revision` title for creation events.

    chrome_2EXlOCZMEC

- The `Updates Made` tab for creation event is empty.

    chrome_D4ijjccuZ4

## Proposed changes

- Added computed value for `title` to show `Item Creation` for revision wih create action.
- Regarding item creation revision not showing any update, I opted to just hide the `Updates Made` tab since there is indeed no changes to be shown, plus `Creation Preview` already shows the initial value set (which was the enhancement wanted in the issue).
- Added necessary translation keys.

## After fix

chrome_kvTcVTjG1H

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/views/private/components/revisions-drawer-detail/revisions-drawer.vue [hunk 1]
```diff
@@ -86,18 +90,29 @@ export default defineComponent({
...
+							value: 'updates_made',
+						},
+						{
+							text: t('revision_preview'),
+							value: 'revision_preview',
+						},
+				  ];
+		});
+
+		watchEffect(() => (currentTab.value = [tabs.value[0].value]));
```
Comment (rijkvanzanten) [inline app/src/views/private/components/revisions-drawer-detail/revisions-drawer.vue:113]: Clever use of watchEffect here 👍🏻
