### PR TITLE
Ensure that flows open in a new tab by pressing Ctrl/Cmd+click or the middle mouse button

### LINKED ISSUE #26103: Flows Page: Cannot Open Flows in a New tab
### Describe the Bug

On the Flows settings page, when viewing the list of flows, it is not possible to open a flow in a new browser tab using standard shortcuts (Ctrl+Click on Windows, Cmd+Click on Mac, or middle mouse button).  
Currently, clicking a flow always navigates to its details within the same tab. This differs from the data model (collections) page, where items can be opened in a new tab using these shortcuts, which is especially helpful for multitasking or comparing multiple flows/items side by side.

### To Reproduce

1. Go to "Settings" → "Flows" in the Directus Admin.
2. Hold Ctrl (Windows) or Cmd (Mac) and click the name of any flow—or try middle mouse button.
3. Observe that the flow only opens in the same tab.
4. Compare this behavior with the Collections or Table layout, where items can be opened in a new tab.

### Expected Behavior:
Ctrl/Cmd+Click or middle mouse button should open the flow details in a new tab, just as it works for collection items in list view for example or data model collection.

### Actual Behavior:
Flows only open in the current tab, preventing multiple flows from being viewed or compared simultaneously.

### Suggested Fix:
Please update the Flows listing so flow links behave consistently with collections and support standard browser mechanisms for opening in new tabs.

### Directus Version

v11.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by dstockton**
## Scope

What's changed:

- Updated navigateToFlow function to accept event parameter
- Added support for Ctrl+Click, Cmd+Click, and middle mouse button
- Opens flows in new tab using window.open() when modifier keys are pressed
- Added comprehensive tests for all click scenarios
- Maintains backward compatibility with normal clicks

## Tested Scenarios

- Added test coverage for:
  - normal mouse click
  - ctrl + mouse click
  - cmd + mouse click
  - middle mouse click

## Review Notes / Questions

- Is the test code structure matching maintainer expectations?

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26103

### CODE REVIEW

File: app/src/modules/settings/routes/flows/overview.vue [hunk 1]
```diff
@@ -85,8 +85,15 @@ function updateSort(sort: Sort | null) {
...
+function navigateToFlow({ item: flow, event }: { item: FlowRaw; event: MouseEvent }) {
+	const route = `/settings/flows/${flow.id}`;
+
+	if (event.ctrlKey || event.metaKey || event.button === 1) {
+		event.preventDefault();
+		window.open(router.resolve(route).href, '_blank');
+	} else {
+		router.push(route);
+	}
 }
```
Comment (formfcw) [inline app/src/modules/settings/routes/flows/overview.vue:96]: Let’s revert this change since Copilot was wrong 🙈

```suggestion
function navigateToFlow({ item: flow, event }: { item: FlowRaw; event: MouseEvent }) {
	const route = `/settings/flows/${flow.id}`;

	if (event.ctrlKey || event.metaKey || event.button === 1) {
		window.open(router.resolve(route).href, '_blank');
	} else {
		router.push(route);
	}
}
```

**Review by formfcw — CHANGES_REQUESTED** [review]
Hey @dstockton :wave:, you beat me to it. The copilot suggestion doesn’t make sense …

**Comment by dstockton** [comment]
> Hey @dstockton 👋, you beat me to it. The copilot suggestion doesn’t make sense …

Thanks for the message & manual review :)

**Review by formfcw — APPROVED** [review]
Thank you so much @dstockton :heart: for your first contribution :rocket:
Perfect, thank you for adding a test.
Nice improvement!

LGTM :tada:

**Comment by dstockton** [comment]
> * codecov/project#### [codecov/project](/directus/directus/pull/26181/checks?check_run_id=55935478053)Failing after 1s — 59.49% (-0.09%) compared to 15276cd

@formfcw - thanks - even though I've added a test, codecov isn't happy about the "reduced" coverage level. Is that something I need to solve (by adding even more tests) before this is mergeable? Or would you just merge anyway?

**Comment by formfcw** [comment]
It’s fine in this case!

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
