### PR TITLE
treat empty array as null on relational field

### LINKED ISSUE #15504: Files interface: [] is not considered the same as null for mandatory field, and cannot sidestep with validation
### Describe the Bug

I have a form with a Files interface. By default it is a mandatory field on creation, but this can be sidestepped by toggling a checkbox triggering a condition making it temporarily non mandatory. Once the item is created, the checkbox is automatically removed via flow so that the next open will force the user to upload.

The Files interface changes null to [] on creation. This means if you update the form without uploading a file, it incorrectly passes validation and proceeds to commit the update. The form does think it is a mandatory field as the blue asterisks appears, it just doesn't behave as such.

I can validate this is definitely the problem because if you edit raw value, change it to null, then try to submit, it spits out the expected cannot be null error.

I tried two field validation methods to sidestep this, and neither worked:
Field is not empty: still saved
Regex not match "[]": still saved

I also tried manually pushing a null back to the item via API, but the change wouldn't stick and keeps going back to []

As an aside, if i try to filter the collection using Files is empty, all items appear. If i use is not empty, all items still appear. If i do Count Files = 0 and >= 1, it behaves as expected. So a potential workaround to this would be the count function being available in the field validation. 

### To Reproduce

1. Create Files interface, mandatory
2. Create checkbox with condition that makes Files non-mandatory when set
3. Save item
4. Edit item and remove the checkbox value. The blue mandatory asterisks appears
5. Submit the form, the update commits without spitting out a field error for your blank mandatory field. 

### Errors Shown

_No response_

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

cloud

### PR DESCRIPTION
**Pull request by Nitwel**
The problem is that relational fields are `[]` when empty and not `null` so we have to accommodate for that.
Fixes #15504

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/utils/validate-item.ts [hunk 1]
```diff
@@ -22,6 +25,13 @@ export function validateItem(item: Record<string, any>, fields: Field[], isNew:
 			});
 		}
 
+		const relation = relationsStore.getRelationsForField(field.collection, field.field);
+
+		// Check if we are dealing with a relational field that has an empty array as its value
+		if (relation.length > 0 && Array.isArray(item[field.field]) && isEmpty(item[field.field])) {
+			item[field.field] = null;
```
Comment (rijkvanzanten) [inline app/src/utils/validate-item.ts:32]: Does this alter the originally passed in `item`? That might cause issues elsewhere. I think we might have to do a `cloneDeep` at the top of this function before this runs to make sure we don't alter the passed in object.

Also, mind adding some unit tests while we're at it? 🙂

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/utils/validate-item.ts (hunk 1 above)
Comment (Nitwel) [reply app/src/utils/validate-item.ts]: Improved and added a test to it.

**Review by rijkvanzanten — APPROVED** [review]
