### PR TITLE
Collection export limit 0 leads to 500 error

### LINKED ISSUE #16719: Collection export limit 0 leads to request that throws 500 Internal Server Error
### Describe the Bug

Exporting `0` items throws 500 Internal server error.

image

### To Reproduce

1. Go to any collection
2. Set `0` as limit and leave other stuff with default values
3. See error 500 in logs

### Errors Shown

```json
{
  "level":50,
  "time":1670247237915,
  "pid":18,
  "hostname":"8d68feca5546",
  "err":{
    "type":"Error",
    "message":"Data should not be empty or the \"fields\" option should be included",
    "stack":"Error: Data should not be empty or the \"fields\" option should be included\n    at JSON2CSVParser.preprocessData (/directus/node_modules/json2csv/lib/JSON2CSVParser.js:57:13)\n    at JSON2CSVParser.parse (/directus/node_modules/json2csv/lib/JSON2CSVParser.js:20:32)\n    at ExportService.transform (/directus/node_modules/directus/dist/services/import-export.js:272:33)\n    at /directus/node_modules/directus/dist/middleware/respond.js:72:55\n    at /directus/node_modules/directus/dist/utils/async-handler.js:3:66\n    at Layer.handle [as handle_request] (/directus/node_modules/express/lib/router/layer.js:95:5)\n    at next (/directus/node_modules/express/lib/router/route.js:144:13)\n    at /directus/node_modules/directus/dist/controllers/items.js:77:12\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
  },
  "msg":"Data should not be empty or the \"fields\" option should be included"
}
```

```json
{
  "level": 30,
  "time": 1670247237916,
  "pid": 18,
  "hostname": "8d68feca5546",
  "req": {
    "id": 72,
    "method": "GET",
    "url": "/items/leads?access_token=--redacted--&export=csv&sort=id&fields%5B%5D=date_created&fields%5B%5D=date_updated&fields%5B%5D=type&fields%5B%5D=payload&limit=0",
    "query": {
      "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0M2E4ODI2LWEwNWQtNDljMi1hOWZlLTg4ZGM3YjEwNDI2ZiIsInJvbGUiOiIyYzFhYmYyYy04OGUxLTQxZTMtYTAwMS00ZDVkZjY0NzM3Y2EiLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOnRydWUsImlhdCI6MTY3MDI0NjQyMiwiZXhwIjoxNjcwMjQ3MzIyLCJpc3MiOiJkaXJlY3R1cyJ9.XCJ4v1nkeJKDrQ_YH-qjhOwCClWJbquN-BzuzAawouo",
      "export": "csv",
      "sort": "id",
      "fields": ["date_created", "date_updated", "type", "payload"],
      "limit": "0"
    },
    "params": {},
    "headers": {
      // redacted
    }
  },
  "res": {
    "statusCode": 500,
    "headers": {
      "content-security-policy": "script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
      "x-powered-by": "Directus",
      "vary": "Origin, Cache-Control",
      "access-control-allow-credentials": "true",
      "access-control-expose-headers": "Content-Range",
      "cache-control": "no-cache",
      "content-type": "text/csv; charset=utf-8",
      "content-disposition": "attachment; filename=\"leads 20221205-133357.csv\"",
      "content-length": "141",
      "etag": "W/\"8d-UpJRA3haAhWTgYTyBPu8RHaaAVs\""
    }
  },
  "err": {
    "type": "Error",
    "message": "failed with status code 500",
    "stack": "Error: failed with status code 500\n    at ServerResponse.onResFinished (/directus/node_modules/pino-http/logger.js:113:40)\n    at ServerResponse.emit (node:events:525:35)\n    at onFinish (node:_http_outgoing:950:10)\n    at callback (node:internal/streams/writable:554:21)\n    at afterWrite (node:internal/streams/writable:499:5)\n    at afterWriteTick (node:internal/streams/writable:486:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"
  },
  "responseTime": 61,
  "msg": "request errored"
}
```

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

N/A

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

By explicitly checking for `limit=0` and providing an empty fields array to the CSVParser if true this prevents the API from returning a 500 error and returns an empty result as expected instead.

Fixes #16719 
Fixes ENG-118

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: api/src/services/import-export.ts [hunk 1]
```diff
@@ -341,6 +341,7 @@ export class ExportService {
 			const parser = new CSVParser({
 				transforms: [CSVTransforms.flatten({ separator: '.' })],
 				header: options?.includeHeader !== false,
+				...(input.length > 0 ? {} : { fields: [] }), // prevent CSVParser from erroring (issue #16719)
```
Comment (rijkvanzanten) [inline api/src/services/import-export.ts:344]: Should we just short-circuit the export before even creating the parser object?

Comment (br41nslug) [reply api/src/services/import-export.ts:344]: my first thought was that optimally CSV with limit=0 should return the header without data but couldnt get that done in a time-boxed fashion.
Do you mean not giving a download when limit is set to `0` for any data type? I stuck with this way for consistency as the CSV is the only one erroring, JSON and XML already returned an empty file without erroring

**Review by licitdev — CHANGES_REQUESTED** [review]
Noticed that the comment for `limit = -1` is incorrect. We should add a similar limit condition check for `exporting_all_items_in_collection` when `exportSettings.limit === -1`.

image

Additionally, should we prevent invalid negative limits such as `-2`?

image

**Comment by br41nslug** [comment]
Good points @licitdev there is no functionality with `limit < -1` or non-integers for that matter. So i've set `min=-1` and `step=1` on the limit interface 😄

**Review by freekrai — APPROVED** [review]
Tested with a few exports and no server errors thrown.

**Review by licitdev — APPROVED** [review]

**Review by licitdev — CHANGES_REQUESTED** [review]
I ran into errors with negative limits (except `-1`) on Postgres, but there was no error on SQLite.
@br41nslug Can we clear the invalid negative values when users key them?

**Comment by br41nslug** [comment]
Sure thing, lets add some backend validation for that 👌

File: api/src/utils/sanitize-query.ts [hunk 2]
```diff
@@ -128,7 +128,9 @@ function sanitizeFilter(rawFilter: any, accountability: Accountability | null) {
 
 function sanitizeLimit(rawLimit: any) {
 	if (rawLimit === undefined || rawLimit === null) return null;
-	return Number(rawLimit);
+	const limit = Number(rawLimit);
+	if (limit < -1) return null; // don't accept below -1
```
Comment (licitdev) [inline api/src/utils/sanitize-query.ts:132]: I think we should also add a check for `NaN`.

```suggestion
	if (isNaN(limit) || limit < -1) return null; // don't accept NaN or below -1
```

Comment (br41nslug) [reply api/src/utils/sanitize-query.ts:132]: good suggestion, i was even thinking of adding a `Math.floor` to the result as decimals have no meaning for a `limit`.

Comment (licitdev) [reply api/src/utils/sanitize-query.ts:132]: I would suggest adding a check using `Number.isInteger()` instead.

Comment (br41nslug) [reply api/src/utils/sanitize-query.ts:132]: Even better

Comment (licitdev) [reply api/src/utils/sanitize-query.ts:132]: Edited! 😄

Comment (azrikahar) [reply api/src/utils/sanitize-query.ts:132]: Although slightly-unintuitively, should we intentionally not return null for NaN instead? Seems like `validateQuery` does return error when we're using `limit=a` for example:

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/api/src/middleware/sanitize-query.ts#L14-L24

chrome_l6mgOJabCj

but returning `null` would ignore it silently. 

That being said, this does depend on what should be the expected outcome. If we want to go with "return null when NaN" for `limit`, we might have to do the same thing for `offset` and `page` to make the expected outcome of NaN values consistent across the query parameters.

Comment (licitdev) [reply api/src/utils/sanitize-query.ts:132]: Nice catch with the tests! 💯 
Should this fix be shifted into `validateQuery()` instead? 🤔

Comment (azrikahar) [reply api/src/utils/sanitize-query.ts:132]: FWIW I do feel the lines are abit blurry, especially with this piece of logic technically also drops NaN values:

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/api/src/utils/sanitize-query.ts#L11-L15

but yeah let's shift to `validateQuery()` for this fix, for now. 

Looks like using `Joi.number().integer().min(-1)` to replace the following line does the integer and above -1 check we wanted, if I'm not mistaken:

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/api/src/utils/validate-query.ts#L14

Comment (azrikahar) [reply api/src/utils/sanitize-query.ts]: @br41nslug I believe https://github.com/directus/directus/pull/16722/commits/71fba5de69c6b7c8d0fe9a1dacd31db0f2a0f31e should be reverted in favor of the Joi change in `validate-query.ts` as discussed above. Apologies if it ended up being long winded and not really clear that we decided not to go with [this suggestion](https://github.com/directus/directus/pull/16722#discussion_r1058492239) 😄

Comment (br41nslug) [reply api/src/utils/sanitize-query.ts]: But `joi` is on the validation side right? is will only error when invalid not sanitize? Or is the idea moving away from sanitization in favor of validation 🤔Sanitization has a better user experience imo but validation is more explicit so something to be said for both approaches however it is a bit confusing that we're mixing both here

Comment (azrikahar) [reply api/src/utils/sanitize-query.ts]: > Sanitization has a better user experience imo but validation is more explicit so something to be said for both approaches 

I do agree that sanitization can be a better UX! Just not sure which approach should we opt for as some other query params technically aren't "sanitized" the same way (eg. `offset` and `page` aren't null-ed when we use alphabets, `export` doesn't get null-ed when it isn't one of the accepted format), at least from my current understanding.

> however it is a bit confusing that we're mixing both here

Yeah my main concern is more to do with inconsistency. If `limit` is null-ed/ignored when it is not an integer, then we may need to do the same across the query params or else they will behave slightly differently. It does feel like the existing logic (not this PR) is already somewhat blurry, so it might require a separate discussion to align the expectation here 🤔

File: api/src/controllers/utils.ts [hunk 3]
```diff
@@ -154,8 +155,10 @@ router.post(
 			schema: req.schema,
 		});
 
+		const sanitizedQuery = sanitizeQuery(req.body.query, req.accountability ?? null);
```
Comment (azrikahar) [inline api/src/controllers/utils.ts:158]: Great idea to use sanitizeQuery here compared to the previous `if` condition check!

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@licitdev Looking good?

**Review by licitdev — APPROVED** [review]
LGTM. Nice use of validation. 👍
