### PR TITLE
Insights 2.0

### LINKED ISSUE #13341: Time Series Insight GUID issue
### Describe the Bug

Imported activity data from another source using GUID and the time series graph is quite entertaining. Looking at the api query, there is no sort option. I think its worth including the sort parameter using the chosen time column.

image

### To Reproduce

Create a table with a guid primary key and a date field then create a time series chart.

### Errors Shown

N/A

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MS SQL

### What browser are you using?

Chrome and MS Edge

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by rijkvanzanten**
## Description

Continuation of https://github.com/directus/directus/pull/12960

- Move Flows variables parsing to `@directus/shared`
- Allow updating multiple items to multiple values in API
  - Add `updateBatch` to services
  - Add's `update_<collection>_batch` mutation in gql
- Refactor GraphQL service partially
- Add StringOrFloat GQL Scalar for filter inputs
- Add paths to graphql validation errors
- Update app tests to accept `@/` aliases
- Rework insights data handling to load everything through the store
  - Fetches all panel data in a single request
  - Caches last 3 open dashboards between navigations
- Adds auto-refresh sidebar detail to insights
- Adds run-time global variables for use in panel configuration
- Fix time-series bug rendering chart. Fixes #13341

## Type of Change

- [x] Bugfix
- [x] Improvement
- [x] New Feature
- [x] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [x] Documentation was added/updated

## Marketing

Just some beauty shots to get the excitement juices flowing:

https://user-images.githubusercontent.com/9141017/175697114-baae2d52-dbbb-4f29-ab81-556977aacc7d.mov

https://user-images.githubusercontent.com/9141017/175697115-946af5ba-990a-49ab-bab8-add0e5d6f45f.mov

https://user-images.githubusercontent.com/9141017/175697116-9a1a7683-fc9b-4365-9360-97de3bbee5f9.mov

https://user-images.githubusercontent.com/9141017/175697118-260cbdc2-6886-47ab-a0bc-71122faf88b4.mov

### CODE REVIEW

File: api/src/services/items.ts [hunk 1]
```diff
@@ -371,7 +371,31 @@ export class ItemsService<Item extends AnyItem = AnyItem> implements AbstractSer
...
+		await this.knex.transaction(async (trx) => {
+			const service = new ItemsService(this.collection, {
+				accountability: this.accountability,
+				knex: trx,
+				schema: this.schema,
+			});
+
+			for (const item of data) {
+				if (!item[primaryKeyField]) throw new InvalidPayloadException(`Item in update misses primary key.`);
+				keys.push(await service.updateOne(item[primaryKeyField]!, item, opts));
```
Comment (licitdev) [inline api/src/services/items.ts:390]: I think the `primaryKeyField` within `item` should be omitted when passed to the `updateOne()`. 
Users without update permission for the `primaryKeyField` will result in an error.

File: app/src/modules/settings/routes/flows/flow.vue [hunk 2]
```diff
@@ -76,17 +76,17 @@
 				:hovered-panel="hoveredPanelID"
 				:subdued="flow.status === 'inactive'"
 			/>
-			<v-workspace :panels="panels" :edit-mode="editMode">
-				<template #panel="{ panel }">
+			<v-workspace :tiles="panels" :edit-mode="editMode">
+				<template #tile="{ tile }">
 					<operation
 						v-if="flow"
```
Comment (licitdev) [inline app/src/modules/settings/routes/flows/flow.vue:82]: Is there a need to propagate the rename of panels into tiles for flows?
The `panels` is passed in as `tiles`. 🤔 Does `panel == tile`?

**Comment by licitdev** [comment]
Noticed that the background of `.edit-actions` covers the input within global variable panel in insights.

Screenshot 2022-06-27 at 1 09 49 AM

## Idea 1: Remove the background
As there's a background in `.v-workspace-tile`, this background should be unnecessary.

https://github.com/directus/directus/blob/59ab26b8ee448e1318950b9ba90e45b38058d98b/app/src/components/v-workspace-tile.vue#L445

https://user-images.githubusercontent.com/26413686/175825773-51b58de3-afa4-4936-9289-7ad5e4106dd1.mov

## Idea 2: Increase the `padding-top` to > 6px or remove it
https://github.com/directus/directus/blob/7050fa236b7446e917748f3f08271d00a85bf676/app/src/panels/variable/panel-variable.vue#L48

https://user-images.githubusercontent.com/26413686/175825911-34e70de0-dd64-4618-8fe7-a016a7e5a2b2.mov

File: app/src/modules/settings/routes/flows/flow.vue (hunk 2 above)
Comment (azrikahar) [reply app/src/modules/settings/routes/flows/flow.vue:82]: Ref https://github.com/directus/directus/pull/12522#discussion_r881584338 (and the relevant commit https://github.com/directus/directus/pull/12522/commits/a73f8a7fdeefa0e0f60e5a93e26cba7bc25e5ef9)

Good question. Though I assume from the initial point sparking this change (assuming from extensions perspective), maybe there isn't a need to rename as developers will refer them as Flow operations  instead of panels. 🤔

**Review by azrikahar — COMMENTED** [review]
Tested with demo data and it's really sweet! 😄

https://user-images.githubusercontent.com/42867097/175899752-819146c5-d4c3-4ae2-a36c-94cef13821f5.mp4

Just listing some minor oddities here:

- List panel showing undefined (@licitdev is already on it!)

   chrome_YCHnNs5voX
   
- Panel doesn't reload when we discard changes

   https://user-images.githubusercontent.com/42867097/175901702-d2825a7f-9a17-468a-b852-9acc435367dc.mp4

File: app/src/modules/settings/routes/flows/flow.vue (hunk 2 above)
Comment (rijkvanzanten) [reply app/src/modules/settings/routes/flows/flow.vue:82]: > Is there a need to propagate the rename of panels into tiles for flows?

There's not really a need, though it would be a little cleaner. The "workspace" renders "tiles". In the case of Insights, each "Panel" gets converted to a tile and then rendered. In Flows, each "Operation" gets rendered as a "Tile". The name "Panel" is technically used for what we consider the graph/metric/widget/thing in a dashboard

**Comment by abdonrd** [comment]
Ops! After updating to the v9.13.0 we have this error:
Screen Shot 2022-06-29 at 09 56 43
Screen Shot 2022-06-29 at 09 56 25

**Comment by abdonrd** [comment]
Fixed if we change this:
Screen Shot 2022-06-29 at 12 26 03

To this:
Screen Shot 2022-06-29 at 12 26 14

Note the Field as ID.
