### PR TITLE
Fix too many SQL Variables

### LINKED ISSUE #17982: I can't delete a collection
### Describe the Bug

[INTERNAL_SERVER_ERROR] update `directus_revisions` set `parent` = NULL where `parent` in (3303, 3304, 3313, 3316, 3319, 3337, 3338, 3339, 3340, 3341

### To Reproduce

1) Create a collection: number: string, price: integer, provider: string, state: string
2) Upload a .csv file with these fields: number, price, provider, state
3) After all when i want to delete collection i have this error: [INTERNAL_SERVER_ERROR] update `directus_revisions` set `parent` = NULL where `parent` in (3303, 3304, 3313, 3316, 3319, 3337, 3338, 3339, 3340, 3341

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by Nitwel**
The problem was that when setting the parents to null, we didn't batch the ids, meaning that when you would update more than 32766 items in one statement using SQLite, it would hit a max limit.

Fixes #17982

### CODE REVIEW

**Review by jaads — APPROVED** [review]

File: api/src/services/collections.ts [hunk 1]
```diff
@@ -579,8 +579,10 @@ export class CollectionsService {
 
 					if (revisionsToDelete.length > 0) {
 						const keys = revisionsToDelete.map((record) => record.id);
-						for(let i = 0; i < keys.length; i += 10_000) {
-							await trx('directus_revisions').update({ parent: null }).whereIn('parent', keys.slice(i, i + 10_000));
+						for (let i = 0; i < keys.length; i += 10_000) {
```
Comment (rijkvanzanten) [inline api/src/services/collections.ts:582]: 10000 feels like an arbitrary number that we might want to make configurable. I'm also curious how this interplays with other transaction insertions; should we do the same batched insert everywhere?

Comment (Nitwel) [reply api/src/services/collections.ts:582]: 10.000 was choosen because the limit in SQLite is 32766 and the charakter limit is 1.000.000 so to be extra sure we don't hit those limits I divided 1.000.000 / 60 charakters which is about 16.000 and to be extra sure again I went down to 10.000. But I agree that this is completely arbitrary though I'm not sure where else we do something similar / how that configuration variable would be named?

**Review by rijkvanzanten — APPROVED** [review]
