### PR TITLE
Fix calendar picker crash when using dynamic variables

### LINKED ISSUE #26828: Calendar picker crashes with focus-trap error when value is a dynamic variable
### Describe the Bug

Opening the calendar picker in the field validation when the value is set to a dynamic variable (e.g. `$NOW`) throws an uncaught error and breaks the UI:

```
Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    at updateTabbableNodes2 (index.js:409:13)
    at Object.activate (index.js:940:9)
    at activate (useFocusTrap-lXZ_YG-8.js:17:42)
    at ComputedRefImpl.set [as setter] (v-menu.vue:176:5)
```

**Root cause**: `v-date-picker` watches its `modelValue` prop and tries to parse it using `@internationalized/date` functions. When the value is `$NOW`, parsing throws an exception, crashing the component.

### To Reproduce

- Open any collection's field configuration (e.g. a dateTime field)
- Go to the **Validation** tab
- Add a filter rule on the date field, e.g. Date Equals `$NOW`
- Click the calendar icon next to the `$NOW` value

### Directus Version

v11.16.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by costajohnt**
## Summary

- Fix v-date-picker crash (focus-trap error) when `modelValue` is a dynamic variable like `$NOW`
- Guard the `modelValue` watcher with `isDynamicVariable` before passing values to `@internationalized/date` parsers
- `$NOW` (and variants like `$NOW(-7 days)`) resolves to current date/time so the picker renders correctly
- Non-date dynamic variables (`$CURRENT_USER`, `$CURRENT_ROLE`, etc.) leave the picker in an empty state

Closes #26828

## Test plan

- [x] Unit tests: 60/60 passing — covers all 4 picker types, `$NOW` resolution, adjustment syntax, prop transitions, and non-date variable empty state
- [x] ESLint: no errors
- [x] Manual testing: opened calendar picker with `$NOW` validation filter — renders at today's date instead of crashing

### CODE REVIEW

**Comment by costajohnt** [comment]
Screenshot 2026-03-23 at 6 26 40 PM

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
Thanks for the PR!

It looks like `$NOW` is handled, but `$NOW(-7 days)` doesn’t seem to be. As it stands, we always resolve to the current date regardless of any adjustment, which is incorrect. Could you confirm if this is intentional?

We should simplify the resolution logic by using our existing `parseDynamicVariable`. Additionally, if a date is returned, could we convert it to the expected string format and let it pass through, reducing the need for additional processing?

**Comment by costajohnt** [comment]
Screenshot 2026-03-24 at 10 26 21 AM

File: app/src/components/v-date-picker/v-date-picker.vue [hunk 1]
```diff
@@ -132,26 +134,66 @@ watch(
...
+			}
+
+			// Resolve $NOW with optional adjustment (e.g. "$NOW(-7 days)") to a date
+			// string so it can be parsed by the type-based logic below.
+			let resolved = new Date();
+			const adjustment = newValue.match(REGEX_BETWEEN_PARENS)?.[1];
+
+			if (adjustment) {
+				resolved = adjustDate(new Date(), adjustment) ?? resolved;
+			}
```
Comment (ComfortablyCoding) [inline app/src/components/v-date-picker/v-date-picker.vue]: Any context for why `parseDynamicVariable` was not used here as mentioned in my initial comment?

File: app/src/components/v-date-picker/v-date-picker.vue [hunk 2]
```diff
@@ -132,26 +134,66 @@ watch(
...
+				case 'dateTime':
+					parseable = `${date}T${time}`;
+					break;
+				case 'timestamp':
+					parseable = resolved.toISOString();
+					break;
+				default:
+					parseable = date;
+					break;
+			}
```
Comment (ComfortablyCoding) [inline app/src/components/v-date-picker/v-date-picker.vue]: Ideally we use something less custom, our `parseDate` util looks to be possibly applicable here

**Review by ComfortablyCoding — DISMISSED** [review]

File: app/src/components/v-date-picker/v-date-picker.vue (hunk 1 above)
Comment (costajohnt) [reply app/src/components/v-date-picker/v-date-picker.vue]: `parseDynamicVariable` is a private function inside `parse-filter.ts` so it can't be imported directly. The public APIs that use it (`parseFilter`/`parsePreset`) operate on filter objects rather than resolving a single value for display. For `parseDate`, the component imports that from `@internationalized/date` (returns `CalendarDate` for reka-ui), not from `@/utils/parse-date` (returns `Date` via date-fns).

The current approach resolves `$NOW` to a type-formatted string and falls through into the same parsing switch that handles regular values, keeping one code path. That said, I hear you on reducing custom code. We could skip the string round-trip and construct the types directly from the resolved `Date`:

```ts
const resolved = adjustDate(new Date(), adjustment) ?? new Date();
calendarValue.value = new CalendarDate(resolved.getFullYear(), resolved.getMonth() + 1, resolved.getDate());
internalTimeValue.value = new Time(resolved.getHours(), resolved.getMinutes(), resolved.getSeconds());
```

The tradeoff is that the current approach keeps one unified path for both dynamic and regular values but with more formatting glue, while direct construction eliminates the round-trip but adds a second path for setting `calendarValue`/`internalTimeValue`. Let me know if I'm weighing that correctly or if there's another angle I'm missing. Happy to go either direction.

Comment (ComfortablyCoding) [reply app/src/components/v-date-picker/v-date-picker.vue]: > parseDynamicVariable is a private function inside parse-filter.ts so it can't be imported directly. The public APIs that use it (parseFilter/parsePreset) operate on filter objects rather than resolving a single value for display. 

We can make it public if it’s now needed, many of these functions were originally private since they weren’t used elsewhere. In this case, let’s keep that function as is and add a new `parseNow` export in the utils package to handle the `$NOW` logic, then update the relevant areas to avoid duplicating the implementation.

> For parseDate, the component imports that from @internationalized/date (returns CalendarDate for reka-ui), not from @/utils/parse-date (returns Date via date-fns).

I’m not sure I follow, could you clarify? I was suggesting we use `@/utils/parse-date`, which we can import if needed. I do see that it expects a string rather than a `Date`, which would make things messy. I’d prefer not to reimplement existing logic, what do you think about using `formatDatePickerModelValue` instead?

**Comment by costajohnt** [comment]
Pulled the `$NOW` resolution into a new `parseNow` export in `packages/utils/shared/` and updated `parse-filter.ts` to use it, so the logic is not duplicated.

On `formatDatePickerModelValue`, that function goes from calendar values to strings for emitting model values, so it does not help in the input direction here. Instead of formatting a string for the downstream switch to re-parse, I construct `CalendarDate` and `Time` directly from the resolved `Date`. This eliminates the custom `pad` and `switch` block entirely and avoids the string round-trip.

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀 , thanks for sticking with @costajohnt

**Review by AlexGaillard — APPROVED** [review]
Nice 👍 TY @costajohnt really knocking them out
