### PR TITLE
Fix decompression in file import endpoint

### LINKED ISSUE #19492: Import .svg image from a url gives error
### Describe the Bug

Import .svg image from a URL gives this error

### To Reproduce

upload any media file, choose from URL, insert this URL https://www.uspolo.org/uspolo/safari-pinned-tab.svg

### Directus Version

v10.5.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #19492

There seems to be an issue in `axios`' built-in decompression, where the stream would be finished before the file is written down in the storage driver.
Resolved by using own implementation, gratefully borrowed from https://github.com/sindresorhus/decompress-response.

### CODE REVIEW

File: api/src/services/files.ts [hunk 1]
```diff
@@ -343,3 +347,66 @@ export class FilesService extends ItemsService {
...
+	}
+
+	let isEmpty = true;
+
+	function handleContentEncoding(data: any) {
+		const decompressStream =
+			// eslint-disable-next-line no-nested-ternary
+			contentEncoding === 'br'
+				? zlib.createBrotliDecompress()
+				: contentEncoding === 'deflate' && data.length > 0 && (data[0] & 0x08) === 0
```
Comment (br41nslug) [inline api/src/services/files.ts:365]: What exactly is the purpose of `0x08` here? Can we move this magic value to a constant for some added context? And should we use just plain `8` instead of the hex notation ```8 === 0x08```

**Review by br41nslug — COMMENTED** [review]
Can confirm this fixes the linked issue 🚀

File: api/src/services/files.ts (hunk 1 above)
Comment (paescuj) [reply api/src/services/files.ts]: It's the header indicating compression with `deflate` algorithm. I've cleaned up the code 👍 

I prefer `0x08` in this case, because I feel like it's more obvious we're doing bitwise operation that way.

Comment (br41nslug) [reply api/src/services/files.ts]: beautiful, love the abstraction to its own function :) a whole lot clearer what the if statement does now

**Review by br41nslug — APPROVED** [review]

**Review by azrikahar — APPROVED** [review]
