### PR TITLE
Fix "Claude Code AI Assistant Field Update payload #26790"

### LINKED ISSUE #26790: Claude Code AI Assistant Field Update payload
### Describe the Bug

When trying to update a field, Claude just sends an incorrect payload causing these tool to malfunction 

Input

{
  "action": "update",
  "collection": "firmwares",
  "field": "main_firmware",
  "data": [
    {
      "type": "alias",
      "name": "main_firmware",
      "meta": {
        "translations": [
          {
            "language": "en-US",
            "translation": "Included as component in"
          }
        ]
      }
    }

### To Reproduce

Image

### Directus Version

11.15.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by powerseed**
To fix https://github.com/directus/directus/issues/26790.

### Bug Reason:
In `api/src/ai/tools/fields/index.ts`, `FieldsInputSchema` is inconsistent with `FieldsValidateSchema`.

The former tells AI providers that 

1. `field` is optional.
2. `data.field` is optional.
3. `data.type` is optional.

```
export const FieldsInputSchema = z.object({
        ...
	field: z.string().optional(),
	data: z
		.array(
			FieldItemInputSchema.extend({
				children: RawFieldItemInputSchema.shape.children,
			}).partial(),
		)
		.optional(),
});
```
But when updating fields, the latter requires

1. `field` is not present.
2. `data.field` is present.
3. `data.type` is present.

```
export const FieldsValidateSchema = z.discriminatedUnion('action', [
        ...
	FieldsBaseValidateSchema.extend({
		action: z.literal('update'),
		data: z.array(RawFieldItemValidateSchema),
	}),
        ...
]);

export const FieldsBaseValidateSchema = z.strictObject({
	collection: z.string(),
});

export const RawFieldItemInputSchema = z.object({
	field: z.string(),
        type: z.string(),
        ...
});
```
### Fix:
Modify the former to make it aligned with the latter.

### Test results:
Test updating a field's interface:
image

Test updating a field's default value:
image

Test creating a new field:
image

### CODE REVIEW

**Review by AlexGaillard — COMMENTED** [review]
Hi @powerseed upon testing this fix in the studio, it does not fix the stated problem. 

Did you run and test this code before opening this PR?

**Comment by powerseed** [comment]
> Hi @powerseed upon testing this fix in the studio, it does not fix the stated problem.
> 
> Did you run and test this code before opening this PR?

Yes I did and it worked fine, but let me test it again.

**Comment by powerseed** [comment]
> Hi @powerseed upon testing this fix in the studio, it does not fix the stated problem.
> 
> Did you run and test this code before opening this PR?

Please take a look again. 
It turned out that `data.type` is required by the validate schema when updating a field, which is incorrect because requests like changing the "default value" of a field doesn't involve its "type". Therefore, I assume the error you saw is `expected string, received undefined at "data[0].type".`

I have made it optional, and added screenshots of test result in this PR.

Regarding why it worked when I tested it, I don't clearly remember.
My guess is that I tested it by updating a field's type, so somehow AI included the `type` field in `data`, so there were no problems; but I didn't test other types of update operations, my apologies.

File: api/src/ai/tools/fields/index.ts [hunk 1]
```diff
@@ -53,13 +53,19 @@ export const FieldsValidateSchema = z.discriminatedUnion('action', [
...
+		.describe(
+			'The name of the field. Required for delete. Optional for read (omit to read all fields). Do not use for create or update.',
+		)
+		.optional(),
 	data: z
 		.array(
 			FieldItemInputSchema.extend({
 				children: RawFieldItemInputSchema.shape.children,
-			}).partial(),
+			}).partial({ type: true, name: true, collection: true, schema: true, meta: true, children: true }),
```
Comment (bryantgillespie) [inline api/src/ai/tools/fields/index.ts]: This works but it's fragile. Let's use something like `.partial().required({field:true})` instead.

File: api/src/ai/tools/fields/index.test.ts [hunk 2]
```diff
@@ -245,6 +245,38 @@ describe('fields tool', () => {
 		});
 	});
 
+	describe('validate schema', () => {
```
Comment (bryantgillespie) [inline api/src/ai/tools/fields/index.test.ts:248]: Could you also add a test for FieldsInputSchema? That's the one the LLMs are sending data against so probably more important to cover that one.

```
test('should accept update input payload without type', () => {
    const result = FieldsInputSchema.safeParse({
      action: 'update',
      collection: 'authors',
      data: [{ field: 'optional', schema: { default_value:'value100' } }],
    });
    expect(result.success).toBe(true);
  });
```

File: .changeset/gentle-dots-ask.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fix "Claude Code AI Assistant Field Update payload #26790"
```
Comment (bryantgillespie) [inline .changeset/gentle-dots-ask.md]: Changeset text should be past tense and should describe the actual change instead of the issue title. 

Along the lines of 

```
Fixed AI assistant field tool call
```

**Review by bryantgillespie — CHANGES_REQUESTED** [review]
The fix works. But a few little things to fix before we merge.

File: .changeset/gentle-dots-ask.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fixed the inconsistency between `FieldsInputSchema` and `FieldsValidateSchema` in `api/src/ai/tools/fields/index.ts`. Therefore, resolved the issues with updating fields via AI.
```
Comment (bryantgillespie) [inline .changeset/gentle-dots-ask.md]:
```suggestion
Fixed AI assistant Fields tool call inconsistency
```

**Review by bryantgillespie — APPROVED** [review]
In pretty good shape. Send it.

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
