### PR TITLE
Remove auto-increment primary key when saving as copy

### LINKED ISSUE #15771: Save as copy not working - Field has to be unique
### Describe the Bug

Save as copy has stopped working. It seems that it fails when creating the new record because Directus is trying to use the existing ID.

### To Reproduce

- Create collection A with some field in it
- Create some item for collection A
- Enter the previously created item details page and try to "Save as copy" it

### Errors Shown

```json
{
  "errors": [
    {
      "message": "Field has to be unique.",
      "extensions": {
        "code": "RECORD_NOT_UNIQUE",
        "collection": "PRIMARY",
        "field": null,
        "invalid": "2226"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

When saving as copy the code was looking for the `is_generated` flag in schema which can be false for primary keys. I've updated this check to look for the `has_auto_increment` flag instead which should always be true for auto-increment IDs.

Fixes #15771
Fixes ENG-179

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by br41nslug** [comment]
I've manually tested this on postgres and mysql against auto-increment IDs, manmually entered IDs and Generated UUIDs. Would love to have some unit tests for this too but have not been able to manage that so far.

https://github.com/directus/directus/issues/15033 is still occurring on mysql.

File: app/src/composables/use-item.ts [hunk 1]
```diff
@@ -172,9 +172,15 @@ export function useItem(
...
 		};
 
-		// Make sure to delete the primary key if it's generated
-		if (primaryKeyField.value && primaryKeyField.value.schema?.is_generated && primaryKeyField.value.field in newItem) {
-			delete newItem[primaryKeyField.value.field];
+		// Make sure to delete the primary key if it's has auto increment enabled
+		if (primaryKeyField.value && primaryKeyField.value.field in newItem) {
+			if (
+				primaryKeyField.value.schema?.has_auto_increment ||
+				primaryKeyField.value?.schema?.is_generated ||
```
Comment (azrikahar) [inline app/src/composables/use-item.ts:179]:
```suggestion
				primaryKeyField.value.schema?.is_generated ||
```

**Review by azrikahar — COMMENTED** [review]
> I've manually tested this on postgres and mysql against auto-increment IDs, manually entered IDs and Generated UUIDs. 

Nice catch to cover uuid special flag as well! 👍

> Would love to have some unit tests for this too but have not been able to manage that so far.

Added an attempt for it in a follow up commit. Do feel free to vet the tests as it feels like the structure can still be improved, but it should help catch these scenarios for now. 🤞

File: app/src/composables/use-item.ts (hunk 1 above)
Comment (br41nslug) [reply app/src/composables/use-item.ts:179]: @azrikahar Im starting to doubt the function of `is_generated` 🤔 in my tests none of the 3 primary key types get the `is_generated` flag set to true. Am i missing a usecase?

Comment (azrikahar) [reply app/src/composables/use-item.ts]: That is a very good question 🤔 It seems like it was added in #14947, do you recall the context of it? I'm also not sure the usage of `is_generated` in that PR, or maybe the fix actually required a different approach.

Comment (br41nslug) [reply app/src/composables/use-item.ts]: This was probably a mistaken assumption on my part on what `is_generated` was intended for 😬 It doesn't look to be a flag related to primary keys 🤦

Comment (azrikahar) [reply app/src/composables/use-item.ts]: Honestly I've also never 100% grasped it's purpose until now. Seems like it is indeed meant for generated columns rather than primary keys specifically.

Seems like the original `primaryKeyField.value && primaryKeyField.value.field in newItem` would still be the correct logic, but now we need to prevent this primary key deletion for manually entered primary keys.

What if we first delete the primary key from the fetched data first (or somehow _not_ fetch primary key), then merge `edits.value` into it? Not sure if there's other edge cases not covered by this though.

Comment (br41nslug) [reply app/src/composables/use-item.ts]: I think this check should cover it https://github.com/directus/directus/pull/16966/files#diff-4ca9afb518ec3f7957e6a2723f01f557c177987383e93bda1ce02918b73b27fcR177
As manually entered IDs neither have `is_auto_increment` set not have the `uuid` special.

Comment (br41nslug) [reply app/src/composables/use-item.ts]: Looked into it a little and the ID is either needed for the update request or it needs to be there as value on the edits (like manually entered ids).

File: app/src/components/v-form/v-form.vue [hunk 2]
```diff
@@ -296,8 +296,8 @@ function useForm() {
 
 	function setPrimaryKeyReadonly(field: Field) {
 		if (
-			field.schema?.is_generated === true &&
-			(field.schema?.has_auto_increment === true || (field.schema?.is_primary_key === true && props.primaryKey !== '+'))
+			field.schema?.is_primary_key === true &&
+			(field.schema?.has_auto_increment === true || props.primaryKey !== '+')
```
Comment (azrikahar) [inline app/src/components/v-form/v-form.vue:300]: Although this does "revert" #14947, but I believe we will still need to fix the original "not able to edit manual primary key" issue that #14947 aimed to fix 👍 

Example test case:

https://user-images.githubusercontent.com/42867097/210757331-99887f9e-8d74-45d8-9bea-d8707db188b9.mp4

**Review by azrikahar — CHANGES_REQUESTED** [review]

File: app/src/components/v-form/v-form.vue (hunk 2 above)
Comment (br41nslug) [reply app/src/components/v-form/v-form.vue]: You're very right as usual 😄 I have updated the readonly check to only target uuid and auto increment IDs in line with the changes done for deleting the id

Comment (azrikahar) [reply app/src/components/v-form/v-form.vue]: Making the check inline with the changes in use-items makes perfect sense! 👍

**Review by azrikahar — APPROVED** [review]
