### PR TITLE
Fix module bar relative links from opening externally

### LINKED ISSUE #8123: Module bar - relative links opens in new tab/window
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

With the new module bar settings you can add custom links, but those links always opens in a new tab/window. If the URL is relative (like `/collections`) it should be open in the same tab/window, right? 

### To Reproduce

Add a new link with relative URL to the Module Bar in the project settings.

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

v15.14.0

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally / NPM

### PR DESCRIPTION
**Pull request by licitdev**
Fixes #8123. Links starting with a "/" will not open externally. This fix also allows links such as `mailto:`, `tel:`, or other deep linking custom schemes to still work.

### CODE REVIEW

**Comment by joselcvarela** [comment]
Internal URLs could be tricky.

I've just tested your changes:

https://user-images.githubusercontent.com/14039341/133894496-65d1e602-9db6-4216-b745-7185d518b5bd.mp4

So I had put `/admin/collections/category` on link and that led me to `/admin/admin/collections/category`.

I think you could check if it starts with `/admin` and remove it, what do you think?

File: app/src/views/private/components/module-bar.vue [hunk 1]
```diff
@@ -9,8 +9,8 @@
 				v-tooltip.right="modulePart.name"
 				icon
 				x-large
-				:to="modulePart.to"
-				:href="modulePart.url"
+				:to="modulePart.to || (modulePart.url && modulePart.url.startsWith('/') ? modulePart.url : undefined)"
```
Comment (joselcvarela) [inline app/src/views/private/components/module-bar.vue:12]: Internal URLs could be tricky.

I've just tested your changes:

https://user-images.githubusercontent.com/14039341/133894496-65d1e602-9db6-4216-b745-7185d518b5bd.mp4

So I had put `/admin/collections/category` on link and that led me to `/admin/admin/collections/category`.

I think you could check if it starts with `/admin` and remove it, what do you think?

**Review by joselcvarela — CHANGES_REQUESTED** [review]

File: app/src/views/private/components/module-bar.vue (hunk 1 above)
Comment (licitdev) [reply app/src/views/private/components/module-bar.vue:12]: Thank you @joselcvarela for helping to test the PR.

If it is a relative (internal as you call it) URL, users can just use `/collections/category`.
I personally think that doing a check for `/admin` and removing it would result in a messier codebase.
All the routes from modules are without the `/admin` as they are all definitely under the admin folder.

In addition, I would believe that for most people upon seeing their link not working and the URL having `/admin/admin`, they would remove it (as they added in the first place).

On a possibly relevant note, there is a question in the Discord SaaS channel asking about changing the `/admin` folder to just `/`. I am not sure if that is possible or not, but should it be possible, I suppose we should not be hardcoding the detection of `/admin`.

Would a note stating that relative URLs should exclude `/admin` suffice in your opinion?

Comment (joselcvarela) [reply app/src/views/private/components/module-bar.vue:12]: From a developer perspective, you are right, we should avoid hardcoded strings
But from an end user perspective, I also expect that a relative link is always relative to the domain, and not to a nested path.

So I don't know if a note is a little bit "hacky" or if we should create an interface for that like this:
image

What are your thoughts @rijkvanzanten @benhaynes ?

Comment (licitdev) [reply app/src/views/private/components/module-bar.vue:12]: > But from an end user perspective, I also expect that a relative link is always relative to the domain, and not to a nested path.

Completely agree with this.

Refer the below screenshot from your video, the links for the modules do not include `/admin`.
image

Perhaps it is just due to the term relative URLs. 
Would it still be an issue if it is termed as internal URLs.

Your interface idea looks good but it may be limiting as there are `mailto:`, `tel:`, or other deep linking custom schemes that work on both desktop and mobile.

Comment (benhaynes) [reply app/src/views/private/components/module-bar.vue:12]: I like that approach, @joselcvarela !! And a good thing to keep in mind, while it's not on our immediate roadmap, would be if `/admin` ever changed or became configurable. In that case we want to avoid that being in these module strings. I love the idea of the drop-down prefix interface! Seems like a nice option to have regardless. 🙌

**Comment by licitdev** [comment]
@joselcvarela I wonder if this pull request should be tagged `Bug` instead of the `Improvement` as it was meant to fix #8123. 
Improvements to the interface should be in a separate pull request, as that may take much longer before the fix is merged.

**Comment by joselcvarela** [comment]
Thank you @licitdev, you're right.
Maybe we could merge this and open another issue about the interface changes

File: app/src/views/private/components/module-bar.vue [hunk 2]
```diff
@@ -9,8 +9,8 @@
...
+				:href="modulePart.url && modulePart.url.startsWith('/') ? undefined : modulePart.url"
```
Comment (rijkvanzanten) [inline app/src/views/private/components/module-bar.vue:13]: I think we can simplify the inline template logic quite a bit by moving this magic down to line 86, where we're creating the "to" field in the first place. By omitting "url" and "to" from the original object, and only adding it when it matches the condition, we can clean this up nicely 🙂

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/views/private/components/module-bar.vue (hunk 2 above)
Comment (licitdev) [reply app/src/views/private/components/module-bar.vue:13]: Hmm, I did it in this manner as there was a need to modify `SettingsModuleBarLink` typings. Somehow I was wondering where's the typing for `modulePart.color`.

https://github.com/directus/directus/blob/f5550af862641ba81b3d8b96fe8210e30a59bd5c/app/src/views/private/components/module-bar.vue#L15-L20

Comment (licitdev) [reply app/src/views/private/components/module-bar.vue:13]: And updating the typings to include `to` also meant that there was a need to update `system-modules.vue` as the modulePart now will not have a `url` if it is changed to a `to`.

Comment (licitdev) [reply app/src/views/private/components/module-bar.vue]: Hmm, I was thinking whether to have separate typings for internal and external links. 

But when I do this, vetur will throw error on either `module-bar` or `system-module` depending on which variable is set to null. Just random thoughts on whether typings should be changed, so that people developing modules will be prompted to set either `url` or `to`...

@rijkvanzanten Anyways, I've just patched the PR, shifting logic out of the vue template. 

```js
export type SettingsModuleBarLinkBase = {
	type: 'link';
	id: string;
	icon: string;
	name: string;
	enabled: boolean;
	locked?: boolean;
};

export type SettingsModuleBarInternalLink = SettingsModuleBarLinkBase & {
	to: string;
	url?: string;
}

export type SettingsModuleBarExternalLink = SettingsModuleBarLinkBase & {
	url: string;
}

export type SettingsModuleBarLink = SettingsModuleBarInternalLink | SettingsModuleBarExternalLink;
```

Comment (licitdev) [reply app/src/views/private/components/module-bar.vue]: > That `href` vs `to question is only relevant at render time in that `module-bar.vue`component. We don't differentiate in the field itself in project-settings, so it's stored under the same`url` name regardless of how it has to be used in the end

Somehow when `module-bar` edits the `url` to `to`, it affects `system-module` which is using the data from props. But it's should be working now. 🤓

**Review by rijkvanzanten — APPROVED** [review]

**Comment by licitdev** [comment]
@rijkvanzanten Wow nice, your cleanup is really 👍🏻. Thank you! Omit is now added to my dictionary. 🤓
But may I ask what is the reason behind the change to the conditional check?

https://github.com/licitdev/directus/blob/c8bde307372f52955e8ceee320fdc6ece89bb54a/app/src/views/private/components/module-bar.vue#L63-L67

I've used `modulePart.url.startsWith('/')` to allow for deep linking or other URL schemes such as `mail-to:` and `tel:` to still work within the app.

PS: please ignore the above revert, accidentally clicked it.

**Comment by joselcvarela** [comment]
Yeah @licitdev has a point. I can think on a letter icon to open mail app to ask help for example.
Maybe on another PR?

**Comment by rijkvanzanten** [comment]
> I've used modulePart.url.startsWith('/') to allow for deep linking or other URL schemes such as mail-to: and tel: to still work within the app.

Fair! I was thinking about the opposite side, where a link that omitted the leading `/` wouldn't load relatively in the app 🙂
