### PR TITLE
Fixed Incorrect docstring for `readGraphqlSdl`

### LINKED ISSUE #21688: Incorrect docstring for `readGraphqlSdl`
### Page

https://docs.directus.io/packages/@directus/sdk/rest/functions/readGraphqlSdl.html

### Describe the Inaccuracy

`sdk/src/rest/commands/server/graphql.ts`

Contains docstring for OpenAPI spec. Seems like a copy paste that was not altered to match its new location.

### PR DESCRIPTION
**Pull request by br41nslug**
## Scope

What's changed:

- Fixed `readGraphqlSdl` doc block description

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- I would like to lorem ipsum

---

Fixes #21688

### CODE REVIEW

File: sdk/src/rest/commands/server/graphql.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import type { RestCommand } from '../../types.js';
 
 /**
- * Retrieve the OpenAPI spec for the current project.
- * @returns Object conforming to the OpenAPI Specification
+ * Retrieve the GraphQL SDL for the current project.
+ * @returns GraphQL SDL file.
```
Comment (paescuj) [inline sdk/src/rest/commands/server/graphql.ts:5]:
```suggestion
 * @returns GraphQL SDL.
```

**Review by paescuj — APPROVED** [review]
