### PR TITLE
Fix filter column aliasing

### LINKED ISSUE #14209: Unknown column 'NaN' in 'where clause' in nested permissions
### Describe the Bug

After upgrading to 9.13 I got this error calling REST APIs.
Response is a generic "Unauthorized" message, log shows the attached exception.
This was working in 9.12.2 (and it works again after downgrading)
 

### To Reproduce

- upgrade to 9.13

### Errors Shown

error

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

14.19.3

### What database are you using?

MariaDB 10.5.15

### What browser are you using?

Chrome

### How are you deploying Directus?

manually

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #14209. Returns the target collection name when generating the aliased column path.
Follow up of #13575. 

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: api/src/utils/get-column-path.ts [hunk 1]
```diff
@@ -54,11 +55,13 @@ export function getColumnPath({ path, collection, aliasMap, relations }: ColPath
...
 		if (remainingParts.length === 1) {
-			return `${alias || parent}.${remainingParts[0]}`;
+			return { columnPath: `${alias || parent}.${remainingParts[0]}`, targetCollection: parent };
 		}
 
 		if (remainingParts.length) {
 			return followRelation(remainingParts, parent, alias);
 		}
+
+		return { columnPath: '', targetCollection: '' };
```
Comment (azrikahar) [inline api/src/utils/get-column-path.ts:65]: Would returning `columnPath: ''` as default make the `if (!columnPath) continue;` in apply-query.ts line 358 not work as intended?

Comment (licitdev) [reply api/src/utils/get-column-path.ts:65]: It was previously undefined (void type), so I supposed the change into '' should be ok.

**Review by rijkvanzanten — APPROVED** [review]
