### PR TITLE
Fix tabular not properly dealiasing items

### LINKED ISSUE #18181: Tabular view translations only showing when primary "Translations" is added
### Describe the Bug

After #17716 the translations columns show correctly in the tabular view, but the data only shows when the primary "translations" field is added.

### To Reproduce

Create collection with translations field. eg Title.
open tabular view of the collection.
Add Translations > Title as a column in the view.
Notice that the column does not display any data.
Add Translations as a column in the view
Notice that the Title column now shows data correctly.

There is some correlation between the Display value for the translations field too.

https://user-images.githubusercontent.com/21194068/232001422-4ea1ca11-e120-48f5-923f-965f897698e3.mov

https://user-images.githubusercontent.com/21194068/232001443-8906d4ba-1e60-4e61-9391-89a75be0ffa0.mov

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Nitwel**
The problem was that when merging the item returned from the api to replace alaised fields with their original names, I didn't take into account that the field without an alias could override the dealiased field, thus resulting in the wrong item.

closes #18181

### CODE REVIEW

File: app/src/layouts/tabular/index.ts [hunk 1]
```diff
@@ -234,7 +236,7 @@ export default defineLayout<LayoutOptions, LayoutQuery>({
 							const arrayField = fieldsStore.getField(collection.value!, fieldParts.slice(0, -1).join('.'));
 
 							// Special case for translations to render the nested data in the translations display instead of the default display
-							if (types.at(-1) === 'o2m' && arrayField?.meta?.special?.includes('translations')) {
+							if (types.at(-1) === 'o2m' && arrayField?.meta?.display === 'translations') {
```
Comment (rijkvanzanten) [inline app/src/layouts/tabular/index.ts:239]: We can't rely on the name of an extension for logic. Displays are extension types so the name could be anything

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Comment by Nitwel** [comment]
@rijkvanzanten Going back to the discussion we had on Discord, your idea of being able to apply the translations display to any field wouldn't work at the moment as the display needs to configure which fields it should load, but the problem here is that you can only specify fields relative to your field so you can't load fields on the same level meaning, the display wouldn't be able to access the `languages_code.code` field.

What I did now is to remove the hacky logic so we can fix this for now and figure out a proper way to support translations display on none translations fields, meaning that for now we will only show it as an array like so:
grafik

**Review by rijkvanzanten — APPROVED** [review]
