### PR TITLE
Fix strange behavior of the sticky header bar

### LINKED ISSUE #24357: Strange behavior of the (sticky) header bar
### Describe the Bug

When the header gets stuck at the top, sometimes the collection name is missing, sometimes the shadow is missing, sometimes the margins don't make sense — especially after a validation error.

https://github.com/user-attachments/assets/1aa981e3-1a8a-411d-afcf-515f6b1d530a

### To Reproduce

Add a collection with a required field and other fields to make the page scrollable. Then scroll up and down to see the behavior of the header bar.

on Firefox 134 (macos)

### Directus Version

v11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

any

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- Fixed a bug where the header would not collapse under certain circumstances and would unexpectedly move up when
scrolling elements in the view

Shifting bug:

https://github.com/user-attachments/assets/764506f5-a21f-470a-8b3a-4c02751f6f04

## Potential Risks / Drawbacks

- …

## Review Notes / Questions

- small one

---

Fixes #24357

### CODE REVIEW

**Comment by hanneskuettner** [comment]
CleanShot 2025-01-23 at 17 24 06@2x

Do we also want to fix the 4px gap at the bottom while we're at it? Looks like the height of the module bar is determined by `calc(100% - 64px)` while the project header is only `60px`. Doesn't seem intentional?

**Comment by formfcw** [comment]
> Do we also want to fix the 4px gap at the bottom while we're at it? Looks like the height of the module bar is determined by `calc(100% - 64px)` while the project header is only `60px`. Doesn't seem intentional?

Good catch! Thank you @hanneskuettner ! I added a commit for this!

**Review by hanneskuettner — APPROVED** [review]
Great find, great fix! 🎸

File: app/src/views/private/private-view.vue [hunk 1]
```diff
@@ -421,7 +421,7 @@ function getWidth(input: unknown, fallback: number): number {
 				--v-divider-color: var(--theme--navigation--list--divider--border-color);
 				--v-divider-thickness: var(--theme--navigation--list--divider--border-width);
 
-				height: calc(100% - 64px);
+				height: calc(100% - 60px);
```
Comment (paescuj) [inline app/src/views/private/private-view.vue:424]: Just a small suggestion:

For such cases I like using vars as a way to describe values. A comment would also do it. This helps to understand the value if we'd come across or have to touch it again in the future.

```suggestion
				--project-header-height: 60px;

				height: calc(100% - var(--project-header-height));
```

Comment (formfcw) [reply app/src/views/private/private-view.vue]: added a commit

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
