### PR TITLE
Fix error when functions are passed to the `run-script` operation

### LINKED ISSUE #25090: Flows Run Script breaks on event hook server.start
### Describe the Bug

When a flow is triggered via event hook with action scope = `server.start`, any sort of Run Script operation breaks and throws errors like:
`{
  "name": "TypeError",
  "message": "function(req, res, next) {\n    app.handle(req, res, next);\n  } could not be cloned."
}`

Observations:
- Delaying the first call of Run Script with a Sleep Operation (10000 ms) in front does not help
- Triggering another flow (from `server.start` triggered flow) -> Run Script also breaks in that second flow

- (!) Firing a Webhook request (from `server.start` triggered flow) to call another flow on the same/self instance (Webhook trigger) -> Run Script works (as workaround)

### To Reproduce

- Create a flow triggered by event hook - type: action and scope = `server.start`
- Add plain/empty Run Script `module.exports = async function(data) {
	// Do something...
	return {};
}`
- Restart directus
- `{
  "name": "TypeError",
  "message": "`undefined` requires parameter 1 to be a string"
}`

Another variant:
`module.exports = async function(data) {
	return data.$last;
}`
Causes:
`{
  "name": "TypeError",
  "message": "function(req, res, next) {\n    app.handle(req, res, next);\n  } could not be cloned."
}`

### Directus Version

v11.4.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres 14

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- Made sure that no functions are passed into isolate-vm

## Potential Risks / Drawbacks

- Shouldn't have any as before, passing in functions would have failed

## Review Notes / Questions

---

Fixes #25090

### CODE REVIEW

File: api/src/controllers/items.ts [hunk 1]
```diff
@@ -74,12 +74,16 @@ const readHandler = asyncHandler(async (req, res, next) => {
...
+	try {
+		if (req.singleton) {
+			result = await service.readSingleton(req.sanitizedQuery);
+		} else if (req.body.keys) {
+			result = await service.readMany(req.body.keys, req.sanitizedQuery);
+		} else {
+			result = await service.readByQuery(req.sanitizedQuery);
+		}
+	} catch (e) {
+		result = new Error('Test');
```
Comment (licitdev) [inline api/src/controllers/items.ts:86]: 👀

File: api/src/operations/exec/index.ts [hunk 2]
```diff
@@ -46,6 +47,8 @@ export default defineOperationApi<Options>({
 		// Run the operation once to define the module.exports function
 		await context.eval(code, { timeout: scriptTimeoutMs });
 
+		data = sieveFunctions(data) as any;
+
 		const inputData = new ivm.ExternalCopy({ data });
```
Comment (ComfortablyCoding) [inline api/src/operations/exec/index.ts:52]:
```suggestion
		const inputData = new ivm.ExternalCopy({ sieveFunctions(data) });
```

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
