### PR TITLE
Preserve M2A type info when using named GraphQL fragments

### LINKED ISSUE #14276: Filter on translations is not working in graphql interface
### Describe the Bug

When filtering by languages code inside a Graphql fragment, filtering doesn't work, and I get a response with every translation inserted. 

Let's say I have an entity `ComponentText` with 2 fields: id, translations.
`translations` is an auto-created o2m translations table via the helper.
And then I have another entity `Page` which contains a M2A relationship called `contents` of `ComponentText` and other components.

I may fetch a particular locale with this query:
```js
const query = gql`
  query getPage {
    Page {
      contents {
        item {
          ...on ComponentText {
            id
            translations(filter: { languages_code: { code: { _eq: "en-EN" } } }) {
                id
            }
        }
      }
    }
  }
`
```

This query works. But when I extract component text into a fragment, like so:
```js
const query = gql`
  query getPage {
    Page {
      contents {
        item {
          ...ComponentText
        }
      }
    }
  }
  
  fragment ComponentText on ComponentText {
      id
      translations(filter: { languages_code: { code: { _eq: "en-EN" } } }) {
          id
      }
  }
`
```

it returns every translation without filtering correctly.

Why is that so?

### To Reproduce

See bug description

### Errors Shown

_No response_

### What version of Directus are you using?

Directus cloud

### What version of Node.js are you using?

16

### What database are you using?

Directus cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS (Directus cloud)

### PR DESCRIPTION
**Pull request by gaetansenn**
## Scope

What's changed:

- named fragments (FragmentSpread) are now wrapped in InlineFragment instead of being flattened to bare fields, preserving the typeCondition
- `parseFields` function uses schema relations to distinguish M2A `InlineFragment` from regular ones

## Potential Risks / Drawbacks

- parseFields now does relation lookups per field (via getRelation/getRelationType from @directus/utils), adds minor overhead per GraphQL query
- Subscriptions don't call replaceFragmentsInSelections at all, so they have the same pre-existing bug (separate fix needed)

## Tested Scenarios

- Inline fragment with translation filter returns only filtered locale (still works)
- Named fragment with same filter now returns only filtered locale (was returning all locales)
- Non-M2A fragments at root level (...PageFragment on Page) inline correctly without :Type prefix
- Non-M2A fragments on O2M fields (author { ...AuthorFrag }) inline as dot-notation paths

## Review Notes / Questions

- I would like to lorem ipsum
- Special attention should be paid to dolor sit amet

## Checklist

- [X] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required
- [ ] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #14276

### CODE REVIEW

File: api/src/services/graphql/schema/parse-query.ts [hunk 1]
```diff
@@ -45,12 +58,28 @@ export async function getQuery(
...
 			let current: string;
 			let currentAlias: string | null = null;
+			let childCollection: string | undefined = currentCollection;
 
-			// Union type (Many-to-Any)
 			if (selection.kind === 'InlineFragment') {
 				if (selection.typeCondition!.name.value.startsWith('__')) continue;
 
-				current = `${parent}:${selection.typeCondition!.name.value}`;
+				const isM2A = parentFieldName && currentCollection ? isM2AField(parentFieldName, currentCollection) : false;
```
Comment (Nitwel) [inline api/src/services/graphql/schema/parse-query.ts]: Already have a function for that.
```suggestion
				const isM2A = getRelationInfo(schema.relations, currentCollection, parentFieldName).relationType === 'a2o'
```

File: api/src/services/graphql/schema/parse-query.ts [hunk 2]
```diff
@@ -83,6 +112,25 @@ export async function getQuery(
...
+							collection: currentCollection,
+							field: fieldName,
+							useA2O: true,
+						});
+
+						if (relType === 'o2m') childCollection = relation.collection;
+						else if (relType === 'm2o') childCollection = relation.related_collection ?? undefined;
+						else if (relType === 'a2o') childCollection = relation.collection;
+					}
+				}
```
Comment (Nitwel) [inline api/src/services/graphql/schema/parse-query.ts:116]: can be simplified with `getRelatedCollection()`

File: api/src/services/graphql/schema/parse-query.ts [hunk 3]
```diff
@@ -83,6 +112,25 @@ export async function getQuery(
...
+						const relType = getRelationType({
+							relation,
+							collection: currentCollection,
+							field: fieldName,
+							useA2O: true,
+						});
+
+						if (relType === 'o2m') childCollection = relation.collection;
+						else if (relType === 'm2o') childCollection = relation.related_collection ?? undefined;
+						else if (relType === 'a2o') childCollection = relation.collection;
```
Comment (Nitwel) [inline api/src/services/graphql/schema/parse-query.ts]: Not sure if the `a2o` case makes sense here?

**Review by Nitwel — CHANGES_REQUESTED** [review]
Tested the changes and seems to be working great. Small code cleanup and this looks good to go.

File: api/src/services/graphql/schema/parse-query.ts (hunk 2 above)
Comment (gaetansenn) [reply api/src/services/graphql/schema/parse-query.ts:116]: Good point ! Refactoring done [here](https://github.com/directus/directus/pull/26920/changes/20ef4490ee836cccd61109dc54797f65542e94b1)

File: api/src/services/graphql/schema/parse-query.ts (hunk 3 above)
Comment (gaetansenn) [reply api/src/services/graphql/schema/parse-query.ts]: This block is gone now, replaced with `getRelatedCollection()` as you suggested above. For A2O it returns null so the fallback ?? currentCollection keeps us on the junction

File: api/src/services/graphql/schema/parse-query.ts (hunk 1 above)
Comment (gaetansenn) [reply api/src/services/graphql/schema/parse-query.ts]: Good point fixed [here](https://github.com/directus/directus/pull/26920/changes/7e1c92c0eace1f431bb24d4bf15de0b0dfc66320)

File: api/src/services/graphql/schema/parse-query.ts (hunk 2 above)
Comment (Nitwel) [reply api/src/services/graphql/schema/parse-query.ts:116]: After thinking about this a bit more, I think `getRelatedCollection` doesn't handle a2o relations so for these we need to get the related collection from the gql schema request.
Also what's the reason of defaulting to `currentCollection here`?

File: api/src/services/graphql/schema/parse-query.ts [hunk 4]
```diff
@@ -45,12 +52,31 @@ export async function getQuery(
...
 			if (selection.kind === 'InlineFragment') {
 				if (selection.typeCondition!.name.value.startsWith('__')) continue;
 
-				current = `${parent}:${selection.typeCondition!.name.value}`;
+				const isM2A =
+					parentFieldName && currentCollection
+						? getRelationInfo(schema.relations, currentCollection, parentFieldName).relationType === 'a2o'
+						: false;
+
+				if (isM2A) {
```
Comment (Nitwel) [inline api/src/services/graphql/schema/parse-query.ts]: don't need to check for `parentFieldName && currentCollection` as the function itself handles that and returns undefined for that case. E.g. something like

```suggestion
				const relationType = getRelationInfo(schema.relations, currentCollection, parentFieldName).relationType;

				if (relationType === 'a2o') {
```

**Review by Nitwel — CHANGES_REQUESTED** [review]

File: api/src/services/graphql/schema/parse-query.ts (hunk 2 above)
Comment (gaetansenn) [reply api/src/services/graphql/schema/parse-query.ts:116]: Yes, that's exactly why we fallback to currentCollection here. 
For A2O, getRelatedCollection returns null, so we keep the junction from the previous recursion. This way isM2AField at the next level can detect A2O on the junction. Once confirmed, this [line](https://github.com/directus/directus/blob/97e6f6ada8e34e9f004ed46ae3de75f4b5fa6ce1/api/src/services/graphql/schema/parse-query.ts#L67) sets the actual target collection from the InlineFragment typeCondition.

File: api/src/services/graphql/schema/parse-query.ts (hunk 4 above)
Comment (gaetansenn) [reply api/src/services/graphql/schema/parse-query.ts]: Good point fixed [here](https://github.com/directus/directus/pull/26920/changes/d391eb348ace08aca54d6a482c9e74a829aeee65)

Comment (Nitwel) [reply api/src/services/graphql/schema/parse-query.ts]: I'd say let's do `currentCollection!` or update `getRelationInfo` to also allow undefined as the implementation itself accounts for that.

File: api/src/services/graphql/schema/parse-query.ts (hunk 2 above)
Comment (Nitwel) [reply api/src/services/graphql/schema/parse-query.ts:116]: Got it, mind adding that as a comment in there as that's not so obvious from just looking at it. 👍

**Review by Nitwel — CHANGES_REQUESTED** [review]

**Review by Nitwel — APPROVED** [review]
LGTM!

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
