### PR TITLE
Set new content version to active version

### LINKED ISSUE #24554: When new revision is created it's not activated
### Describe the Bug

Maybe this is intentional, but we found it quite confusing that after creating a new revision inside a collection item, the revision is not automatically activated.

We often forget to switch to the new revision and end up modifying existing production data. Is this a known bug, or is there an option to change this behavior?

Thanks!

### To Reproduce

create revision and check currently set revision

### Directus Version

11.4.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

### PR DESCRIPTION
**Pull request by robluton**
## Scope

What's changed:

- Sets the query version after adding a new content version, allowing it to become the current version being edited.
- Changes default action to saveAndStay, so, after saving an existing version, you remain on that version instead of being redirected to the main version.

## Potential Risks / Drawbacks

- Those accustomed to the old behavior may still expect the active version to be set to "main" after adding a new version.

---

Fixes #24554

### CODE REVIEW

**Comment by robluton** [comment]
This addresses what happens when creating a new version, but I wonder what is the most intuitive path to take after updating a version. Currently, if a version is modified and then saved, the user is redirected back to the main version. Should the user remain on the same version they just updated instead, and have to manually select the main version?

File: app/src/modules/content/routes/item.vue [hunk 1]
```diff
@@ -360,17 +360,6 @@ async function saveVersionAction(action: 'main' | 'stay' | 'quit') {
...
-	if (isSavable.value === false) return;
-
-	try {
-		await save();
-		if (props.singleton === false) router.push(getCollectionRoute(props.collection));
-	} catch {
-		// Save shows unexpected error dialog
-	}
-}
-
```
Comment (AlexGaillard) [inline app/src/modules/content/routes/item.vue:373]: Screenshot 2025-02-27 at 11 35 17 AM

I think because "Save and stay" is now the default, we no longer need it under the options menu.

Furthermore, I think we should maybe add "Save and return to main" as an option to replace "Save and stay"

**Review by AlexGaillard — CHANGES_REQUESTED** [review]

File: app/src/modules/content/routes/item.vue (hunk 1 above)
Comment (robluton) [reply app/src/modules/content/routes/item.vue:373]: image

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
