### PR TITLE
Fix compatibility with Postgres <= 10

### LINKED ISSUE #10136: Directus 9.1 breaks support for PostgreSQL 10.
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Switching to version 9.1 the support for postgreSQL-databases of version 10 is broken. We're running directus in dockerized mode, when starting up the container the error-message (see below) appears because there is no field "indnkeyatts" in the table "pg_index". This field was first introduced in postgres version 11 (search for "indnkeyatts"):

Version 10: https://www.postgresql.org/docs/10/catalog-pg-index.html
Version 11: https://www.postgresql.org/docs/11/catalog-pg-index.html

We are currently using AWS Aurora Serverless because of its big advantage in scaling up and down automatically but Serverless is only supported for postgreSQL 10 (at least for now). 

The incompatibility was introduced because of the changes in the knex-schema-inspector, see the following issue and the according commit:

https://github.com/directus/directus/issues/9217
https://github.com/knex/knex-schema-inspector/commit/3b40c2c2348518caac0b65978161d0e9e876e07a

### To Reproduce

Run directus in version >= 9.1. against a PostgreSQL-Database in version 10.

### Errors Shown

> error:
        SELECT relname as table_name
          , pg_attribute.attname as column_name
        FROM pg_index
          , pg_class
          , pg_attribute
          , pg_namespace
        WHERE
          indrelid = pg_class.oid
          AND nspname IN ($1)
          AND pg_class.relnamespace = pg_namespace.oid
          AND pg_attribute.attrelid = pg_class.oid
          AND pg_attribute.attnum = ANY (pg_index.indkey)
          AND indisprimary
          AND indnkeyatts = 1
       - column "indnkeyatts" does not exist
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 176,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "pg_index.indnatts".',
  position: '463',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3293',
  routine: 'errorMissingColumn'
}

### What version of Directus are you using?

9.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 10.14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by oreilles**
Fixes https://github.com/directus/directus/issues/10136
Comes with https://github.com/knex/knex-schema-inspector/pull/89

### CODE REVIEW

File: packages/schema/src/dialects/postgres.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export default class Postgres extends KnexPostgres implements SchemaInspector {
           AND pg_attribute.attrelid = pg_class.oid
           AND pg_attribute.attnum = ANY (pg_index.indkey)
           AND indisprimary
-          AND indnkeyatts = 1
+          AND indnatts = 1
```
Comment (cah4a) [inline packages/schema/src/dialects/postgres.ts:64]: Looks like it will not work if the index contains non-key columns.
Consider `array_length(pg_index.indclass, 1) = 1` or `array_length(pg_index.indcollation, 1)`

File: packages/schema/src/dialects/postgres.ts [hunk 2]
```diff
@@ -61,7 +61,7 @@ export default class Postgres extends KnexPostgres implements SchemaInspector {
           AND pg_attribute.attrelid = pg_class.oid
           AND pg_attribute.attnum = ANY (pg_index.indkey)
```
Comment (cah4a) [inline packages/schema/src/dialects/postgres.ts:62]: `pg_index.indkey` could contain non-key column

File: packages/schema/src/dialects/postgres.ts (hunk 1 above)
Comment (Oreilles) [reply packages/schema/src/dialects/postgres.ts:64]: I don't believe a primary key index can include non-key columns, so is that really an issue ?

File: packages/schema/src/dialects/postgres.ts [hunk 3]
```diff
@@ -61,7 +61,7 @@ export default class Postgres extends KnexPostgres implements SchemaInspector {
...
           AND indisprimary
```
[the remark this answers is not in the document]
Comment (Oreilles) [reply packages/schema/src/dialects/postgres.ts:63]: These lines are 13 month old, was this comment targeted to another section of the code ?

**Comment by rijkvanzanten** [comment]
@cah4a This PR fixes the OP in the referenced ticket, so I'll merge it for now. Mind opening a new Issue / PR with any comments / concerns you have on that [dialects/postgres](https://github.com/directus/directus/blob/main/packages/schema/src/dialects/postgres.ts) file? 🙂 [As @Oreilles mentioned](https://github.com/directus/directus/pull/10139#discussion_r759513010), it seems like some of your comments aren't related to anything that changed in this PR in particular, so are better suited for a follow up sprint 👍🏻

**Review by rijkvanzanten — APPROVED** [review]

**Comment by cah4a** [comment]
@rijkvanzanten just took my eye.
If nobody is concerned, then let it be.

**Comment by rijkvanzanten** [comment]
@cah4a What do you mean? I'm very interested to hear more about the points you've found! Just saying that a separate issue w/ pull request review cycle is a better place to discuss optimizations to code that already existed before the changes in this PR.
