### PR TITLE
Fix conversion of `fields` from object notation to dot syntax in SDK subscription queries

### LINKED ISSUE #26396: SDK: Realtime subscription does not parse nested `fields` the same way as REST requests
### Describe the Bug

When using the Directus SDK, nested `fields` definitions are correctly parsed when making REST requests, but the same structure fails when used inside a Realtime subscription.

In REST requests, the SDK correctly converts nested `fields` objects into the expected dot-notation format (e.g. `*.members.*`). However, when using the same `fields` configuration inside a Realtime `subscribe` call, the parsing does not occur and the API returns an error.

This creates an inconsistency between REST and Realtime behavior, even though both accept a `fields` option.

### To Reproduce

1. Perform a REST request with nested fields:

```ts
await client.request(
  readItems('departments', {
    fields: ['*', { members: ['*'] }]
  })
);
````

2. Observe that the SDK correctly parses the fields into the expected format (e.g. `*.members.*`) and the request works as expected.

3. Perform a Realtime subscription using the same fields configuration:

```ts
await client.subscribe('departments', {
  query: {
    fields: ['*', { members: ['*'] }]
  }
});
```

4. Observe that:

   * The `fields` option is **not parsed** into dot-notation
   * The API logs show an error: WebSocket unhandled exception

### Directus Version

v11.14.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

docker image pgvector/pgvector:pg17

### PR DESCRIPTION
**Pull request by bruno-costa**
This PR fixes an inconsistency between REST requests and realtime subscriptions when handling complex query parameters, such as nested `fields`.

In REST requests, query parameters are properly parsed before being sent to the API. However, realtime subscriptions were forwarding the query object as-is, causing invalid queries and API errors when using structured fields.

To address this, a shared `parseQueryParams` utility was introduced and applied to realtime subscription options, ensuring consistent behavior across both transports.

## Scope

What's changed:

- Added a reusable `parseQueryParams` utility
- Applied query parsing to realtime subscription options
- Ensured nested `fields` and other complex query parameters are correctly serialized

## Potential Risks / Drawbacks

- Low risk: logic already exists and is used by REST requests
- No breaking changes to the public SDK API

## Tested Scenarios

- Realtime subscriptions using nested `fields` (e.g. `['*', { members: ['*'] }]`)
- Realtime subscriptions without query options
- REST and realtime requests using equivalent query structures

## Review Notes / Questions

- This change aligns realtime query handling with existing REST behavior
- Prevents API errors caused by unparsed query parameters

## Checklist

- [x] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required
- [ ] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required
---

Fixes #26396

### CODE REVIEW

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
Thanks for the PR! 🙌

Let’s move `queryToParams` into the shared `src/utils` folder so it can be utilized by both implementations. The surrounding try/catch in the proposed new function shouldn’t be necessary, since invalid data should already be safely skipped. We should therefor be able to directly call it.

File: sdk/src/realtime/utils/parse-query-params.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import { queryToParams } from '../../utils/query-to-params.js';
```
Comment (ComfortablyCoding) [inline sdk/src/realtime/utils/parse-query-params.ts]: Let's remove this utility and use `queryToParams` directly in the composable. As noted in the original review this utility should be unnecessary given we have `queryToParams` which is not expected to error for invalid input

File: sdk/src/realtime/composable.ts [hunk 2]
```diff
@@ -371,6 +372,11 @@ export function realtime(config: WebSocketConfig = {}) {
 				options = {} as Options,
 			) {
 				if ('uid' in options === false) options.uid = uid.next().value;
+
+				if ('query' in options && options.query) {
+					options.query = parseQueryParams(options.query);
+				}
```
Comment (ComfortablyCoding) [inline sdk/src/realtime/composable.ts]: Let's simplify this to 
```suggestion
				if (options.query) {
					options.query = queryToParams({ ...options.query });
				}
```

File: sdk/src/rest/helpers/with-search.ts [hunk 3]
```diff
@@ -1,4 +1,4 @@
-import { formatFields } from '../index.js';
+import { formatFields } from '../../utils/query-to-params.js';
```
Comment (ComfortablyCoding) [inline sdk/src/rest/helpers/with-search.ts]: As we are already touching `queryToParams` lets move `formatFields` to its own util file with tests backing it.

File: .changeset/blue-moose-reply.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+---
+'@directus/sdk': minor
+---
+
+Add `parseQueryParams` utility and apply it to realtime subscriptions to properly parse complex query parameters (e.g.
+`fields` with nested relations), aligning realtime behavior with REST requests.
```
Comment (ComfortablyCoding) [inline .changeset/blue-moose-reply.md]: As [this is a fix and not feature](https://directus.io/docs/community/contribution/pull-requests#changeset-bump-definitions) lets mark this as a patch, changesets should also be [past tense](https://directus.io/docs/community/contribution/pull-requests#changesets).
```suggestion
'@directus/sdk': patch
---

Fixed conversion of `fields` from object notation to dot syntax missing in realtime subscription queries.
```

File: sdk/src/utils/query-to-params.test.ts
Comment (ComfortablyCoding) [inline sdk/src/utils/query-to-params.test.ts:1]: If we can add some tests ensuring this also supports dot notation for backwards compatibility that would be great.

**Review by ComfortablyCoding — DISMISSED** [review]
Thanks for the updates! I have left a few more comments

File: .changeset/blue-moose-reply.md (hunk 4 above)
Comment (bruno-costa) [reply .changeset/blue-moose-reply.md]: Done bro

File: sdk/src/realtime/composable.ts (hunk 2 above)
Comment (bruno-costa) [reply sdk/src/realtime/composable.ts]: This works better this way

File: sdk/src/realtime/utils/parse-query-params.ts (hunk 1 above)
Comment (bruno-costa) [reply sdk/src/realtime/utils/parse-query-params.ts]: Removed!

File: sdk/src/rest/helpers/with-search.ts (hunk 3 above)
Comment (bruno-costa) [reply sdk/src/rest/helpers/with-search.ts]: moved

**Review by ComfortablyCoding — APPROVED** [review]
LGTM! Thanks @bruno-costa and congratulations on your first contribution to directus! 🥳

**Review by licitdev — APPROVED** [review]
