### PR TITLE
Fix `requireSelection` check for manual trigger flows

### LINKED ISSUE #25385: 403 Forbidden error on manual flows that do not require selection
### Describe the Bug

When attempting to run any manual flow that *does not* require selection on Directus 11.9.0+, a "You don't have permission to access this" error occurs. 

The logs indicate this is because the `keys` property is missing (which should be expected).

I believe the error is caused by lines 273-276 in `api/src/flows.ts` failing to check `requireSelection`: https://github.com/directus/directus/blob/main/api/src/flows.ts#L273-L276

Introduced by this commit: https://github.com/directus/directus/commit/22be460c76957708d67fdd52846a9ad1cbb083fb 

### To Reproduce

1. Create a manual flow that does not require selection on any collection.
2. Attempt to run it.
3. Observe "[FORBIDDEN] You don't have permission to access this" error.

### Directus Version

11.9.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

_No response_

### PR DESCRIPTION
**Pull request by JoshTheDerf**
## Scope

What's changed:

- Adds a missing `requireSelection` check before enforcing keys are defined
- Adds a missing `targetKeys` check before checking key permissions

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- N/A

---

Fixes #25385

### CODE REVIEW

File: api/src/flows.ts [hunk 1]
```diff
@@ -270,7 +270,7 @@ class FlowManager {
 						throw new ForbiddenError();
 					}
 
-					if (!targetKeys || !Array.isArray(targetKeys)) {
+					if (requireSelection && (!targetKeys || !Array.isArray(targetKeys))) {
```
Comment (licitdev) [inline api/src/flows.ts:281]: 🤔 
```suggestion
					if (requireSelection && !targetKeys || !Array.isArray(targetKeys)) {
```

**Review by ComfortablyCoding — DISMISSED** [review]
Thanks for the PR!

I believe we need to wrap https://github.com/directus/directus/blob/main/api/src/flows.ts#L311-L328 in a `requireSelection` check as well.

**Comment by JoshTheDerf** [comment]
Good catch, I didn't read that far. 👀

File: api/src/flows.ts (hunk 1 above)
Comment (JoshTheDerf) [reply api/src/flows.ts:281]: I just like being explicit with logical operators. 😆

**Review by ComfortablyCoding — APPROVED** [review]
LGTM, thanks again!

**Review by br41nslug — APPROVED** [review]
