### PR TITLE
Fix collection sorting for grouped collections

### LINKED ISSUE #21658: Order of related items is random, on 10.9.3
### Describe the Bug

Since the latest update, related items are shown in a seemingly random order.
This is true for relation dropdowns, access control, …

Screenshot_2024-02-15_at_20 33 12

Screenshot_2024-02-15_at_20 23 34

### To Reproduce

Open a Directus instance, look at a field that has many relations, for example M2A (Blocks) or the access control page in settings

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

When displaying collections (in selects, lists, `system-collection` and `system-collections`) they were only sorted by `meta.sort` (and the collection name for ties). When grouping selections the sort index starts at `1` again, so the collections appeared out of order with how you would expect it based on the data-model manual sorting.

What's changed:

- Introduced `flattenGroupedCollections` (not sure about the name, any suggestions?) to recursively flatten a list of collections that might be (deeply) grouped with the `meta.group` prop.
- After talking with @paescuj I moved the sorting to a single source of truth, the `collections` store
  - Introduced a new `sortedCollections` getter in addition to the original `collections` state, that is now used instead of `collections` whenever a sorted list of collections is needed. As such the `collections` is not modified and can be used in a backward compatible manner (also it is assigned to outside of the store, introducing the need for either a `replaceCollections` or the sorted getter)
- Added more getters in the collection store to ease repetitive filtering, and to use as intermediate lists in the store itself.

## Potential Risks / Drawbacks

None 

## Review Notes / Questions

- Did I miss any access to `.collections` that would result in inconsistent sorting behavior?
- Is the sorting actually less confusing? Sometimes I still struggle with finding the collection easily.

---

Fixes #21658

### CODE REVIEW

File: app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue [hunk 1]
```diff
@@ -18,14 +17,8 @@ const collectionExists = computed(() => {
...
-const availableCollections = computed(() => {
-	return orderBy(
-		collectionsStore.databaseCollections.filter((collection) => collection.meta),
-		['meta.sort', 'collection'],
-	);
-});
-
-const systemCollections = collectionsStore.crudSafeSystemCollections;
+const availableCollections = computed(() => collectionsStore.configuredCollections);
+const systemCollections = computed(() => collectionsStore.crudSafeSystemCollections);
```
Comment (hanneskuettner) [inline app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue:21]: Do you know if these `computed(() => ...)` are needed? They are getters in a pinia store, and I'm not really sure about their reactiveness. So I opted to wrap them in computed, but we had it as non-computed value before.

Comment (paescuj) [reply app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue:21]: Not required, as long as it is not destructured [^1] 👌 

[^1]: https://pinia.vuejs.org/core-concepts/#Using-the-store

File: app/src/modules/settings/routes/roles/item/components/permissions-overview.vue
Comment (rijkvanzanten) [inline app/src/modules/settings/routes/roles/item/components/permissions-overview.vue:1]: Empty new file

File: app/src/modules/settings/routes/data-model/collections/collections.vue [hunk 2]
```diff
@@ -99,28 +93,13 @@ const visibilityTree = computed(() => {
...
-			collectionsStore.collections.filter(
-				(collection) =>
-					isSystemCollection(collection.collection) === false && !!collection.meta === false && collection.schema,
-			),
-			['meta.sort', 'collection'],
-		),
-	);
-});
+const tableCollections = computed(() =>
+	translate(collectionsStore.databaseCollections.filter((collection) => !collection.meta)),
```
Comment (rijkvanzanten) [inline app/src/modules/settings/routes/data-model/collections/collections.vue:97]: I'm wondering if there's any better names for these different subsets. `configuredCollections` and `databaseCollections` were a little hard to grok out of the collections store file.

**Review by rijkvanzanten — DISMISSED** [review]

**Comment by rijkvanzanten** [comment]
@hanneskuettner It seems like non-table Groups are also present in the list when selecting a relational field, so somewhere we're not filtering those out as we should

> Is the sorting actually less confusing? Sometimes I still struggle with finding the collection easily.

Good question.. I'm a little conflicted. Is it better to show them in the dropdown as actual groups you have to click through to open them? Alternatively, maybe we want to prefix nested ones with a space or two and an icon? F.e. 

```
collection_a
group_a
  → collection_b
  → collection_c
  → nested_group
    → collection_d
```

although that'll quickly grow wider than the dropdown box 🤔

**Comment by AlexGaillard** [comment]
> Is it better to show them in the dropdown as actual groups you have to click through to open them

I think this makes the most sense to me as it keeps it much neater. 

image

You do run the risk of getting lost in the nest however. Though you could maybe have a little breadcrumb trail along the top?

> maybe we want to prefix nested ones with a space or two and an icon

You could also perhaps split the difference where you can dropdown to expand for one level, and then going one level deeper sort of slides everything along, so you can only ever see two levels at a time. 🤔 If that makes sense.

File: app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue [hunk 3]
```diff
@@ -18,13 +17,7 @@ const collectionExists = computed(() => {
...
 });
 
-const availableCollections = computed(() => {
-	return orderBy(
-		collectionsStore.databaseCollections.filter((collection) => collection.meta),
-		['meta.sort', 'collection'],
-	);
-});
-
+const availableCollections = collectionsStore.configuredCollections;
```
Comment (AlexGaillard) [inline app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue:20]: >It seems like non-table Groups are also present in the list when selecting a relational field, so somewhere we're not filtering those out as we should

It's here. I think this should be databaseCollections, no?

File: app/src/modules/settings/routes/data-model/collections/collections.vue (hunk 2 above)
Comment (hanneskuettner) [reply app/src/modules/settings/routes/data-model/collections/collections.vue:97]: The problem is that `databaseCollections` has been there before and is effectively public API at this point because it is part of the exposed API of the `CollectionsStore`

File: app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue (hunk 3 above)
Comment (hanneskuettner) [reply app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue:20]: Oh it looks like I messed up the definition for `configuredCollections`. It should be a filter on `databaseCollections` and not on `allCollections`.

Comment (AlexGaillard) [reply app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue:20]: Well that fixes the non-table groups not filtering out out of the relational field selector, but then anything nested under a non-table group is filtered out of  the `/data-model` route 😅 

Before:
Screenshot 2024-09-16 at 4 33 23 PM

After:
Screenshot 2024-09-16 at 4 29 32 PM

Comment (AlexGaillard) [reply app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue:20]: This is the culprit here:

https://github.com/directus/directus/blob/c216136deadc9f800cda0f37f4b613e3a91ae1a7/app/src/modules/settings/routes/data-model/collections/collections.vue#L34-L36

May want to update it to:

```
const rootCollections = computed(() => {
	return collectionsStore.allCollections.filter((collection) => !collection.meta?.group);
});
```

Or possibly define `rootCollections` in the collections store?

**Review by AlexGaillard — APPROVED** [review]
I think this LGTM.

We never addressed the idea of redesigning the UI: https://github.com/directus/directus/pull/22392#issuecomment-2348962114

However, I think that would likely balloon in scope so probably best to leave it as is.

**Comment by AlexGaillard** [comment]
@rijkvanzanten Your requested changes are blocking this merge?

Are they still relevant?
