### PR TITLE
fix(app): deduplicate aggregate count requests on content navigation

### LINKED ISSUE #25194: APP: Inconsistent and Extra API calls when initializing, navigating route /content/:collection and navigating Bookmarks
### Describe the Bug

In the UI, we only need to display information derived from the filtered total count (pagination, total items). However, during page initialization, navigation, and bookmark switching, multiple redundant and inconsistent API requests are made for the total (filtered or not). 

**Expected Behavior**:

- Only one request to get the filtered total count.
- One request for the filtered rows.

**Actual Behavior**:

- Multiple (up to 3 requests), inconsistent API requests are sent for the total count, affecting performance, especially on high-volume tables.

### To Reproduce

**Refresh page /admin/content/:collection (3 requests related to the collection)**
```
GET https://api.mimelis.ch/items/:collection?aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?limit=25&fields[]=description&fields[]=name&fields[]=id&sort[]=id&page=1
```
-> 2 times the same requests to get the total

**Navigate to /admin/content/:collection (4 requests related to the collection)**
```
GET https://api.mimelis.ch/items/:collection?aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?filter[]&aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?filter[]&aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?limit=25&fields[]=description&fields[]=name&fields[]=id&sort[]=id&page=1
```
-> 3 requests to get the total (2 filtered, 1without filter)

**Navigate to /admin/content/:collection?bookmark=xxx (3 requests related to the collection)**
```
GET https://api.mimelis.ch/items/:collection?aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?filter[]&aggregate[countDistinct]=id
GET https://api.mimelis.ch/items/:collection?limit=25&fields[]=description&fields[]=name&fields[]&filter[]
```
-> 2 requests to get the total (1 filtered, 1 without filter)

### Directus Version

v11.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by okxint**
## Scope

What's changed:

- Merged the two separate `watch` blocks in the `useItems` composable into a single coordinated watcher that includes `filterSystem` in its dependency array
- Added a `loadingTotalCount` indicator so `getItemCount` can wait for an in-flight `getTotalCount` request instead of making a duplicate API call
- When no user filter/search is active (or the user filter matches the system filter), `getItemCount` reuses the `totalCount` result — eliminating redundant aggregate requests
- Added 3 new tests covering the deduplication behavior

## Potential Risks / Drawbacks

- The abort behavior in `getTotalCount` is preserved, so collection changes still correctly cancel stale requests and fetch fresh data
- When filters/search ARE active, `getItemCount` still makes its own separate request with the appropriate parameters, so filtered counts remain accurate
- The `loadingTotalCount` watch-based waiting approach correctly handles the race condition where `getTotalCount` is in-flight when `getItemCount` needs the result

## Tested Scenarios

- Initial page load `/content/:collection`: 2 requests (down from 3) — `getItems` + `getTotalCount`, `getItemCount` reuses `totalCount`
- Navigation to `/content/:collection`: 2 requests (down from 4) — same deduplication
- Navigation with `?bookmark=xxx`: 2 requests (down from 3) — same deduplication
- Active search/filter: 3 requests (unchanged) — `getItems` + `getTotalCount` + `getItemCount` (separate, as expected)
- Filter matching system filter: 2 requests — `getItemCount` correctly reuses `totalCount`
- All 10 tests pass (7 updated existing + 3 new)

## Review Notes / Questions

- Previous PRs (#26530, #26825) attempted to fix this but were closed. This implementation addresses the maintainer feedback from @ComfortablyCoding:
  - Keeps the abort behavior in `getTotalCount` to handle collection changes correctly
  - Uses a `loadingTotalCount` indicator so `getItemCount` can wait for in-flight requests rather than triggering new ones
  - Checks if user filter matches `systemFilter` (not just empty filters) per the suggestion
  - Merges the two watchers into one coordinated flow to prevent race conditions

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #25194

### CODE REVIEW

File: packages/composables/src/use-items.ts [hunk 1]
```diff
@@ -277,12 +284,50 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery):
...
+				if (loadingTotalCount.value) {
+					// A getTotalCount request is already in flight — wait for it to complete
+					await new Promise<void>((resolve) => {
+						const unwatch = watch(loadingTotalCount, (loading) => {
+							if (!loading) {
+								unwatch();
+								resolve();
+							}
+						});
+					});
```
Comment (Nitwel) [inline packages/composables/src/use-items.ts]: This can be simplified with `https://vueuse.org/shared/until/#until`

File: packages/composables/src/use-items.ts [hunk 2]
```diff
@@ -277,12 +284,50 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery):
...
+
+		const isFilterEmpty = !filterVal || Object.keys(filterVal).length === 0;
+		const isSearchEmpty = !searchVal || searchVal.length === 0;
+
+		// When there's no user filter/search active (or the user filter matches the system filter),
+		// the item count equals the total count — reuse it instead of making a duplicate request.
+		if (isSearchEmpty && (isFilterEmpty || isEqual(filterVal, filterSystemVal))) {
+			loadingItemCount.value = true;
+
+			try {
```
Comment (Nitwel) [inline packages/composables/src/use-items.ts]: Why do we need a try catch here around this whole statement?

File: packages/composables/src/use-items.ts [hunk 3]
```diff
@@ -106,17 +118,10 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery):
...
 
-			fetchItems(shouldUpdateCount);
-		},
-		{ deep: true, immediate: true },
-	);
-
-	watch(
-		[collection, toRef(filterSystem)],
-		async (after, before) => {
-			if (isEqual(after, before)) return;
```
Comment (Nitwel) [inline packages/composables/src/use-items.ts:117]: what's the benefit/reason behind combining these two watchers?

File: packages/composables/src/use-items.ts [hunk 4]
```diff
@@ -73,17 +74,28 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery):
...
-		[collection, limit, sort, search, filter, fields, page, toRef(alias), toRef(deep)],
+		[collection, limit, sort, search, filter, fields, page, toRef(alias), toRef(deep), toRef(filterSystem)],
 		async (after, before) => {
 			if (isEqual(after, before)) return;
 
-			const [newCollection, newLimit, newSort, newSearch, newFilter] = after;
-			const [oldCollection, oldLimit, oldSort, oldSearch, oldFilter] = before;
+			const [newCollection, newLimit, newSort, newSearch, newFilter, , , , , newFilterSystem] = after;
+
+			const [oldCollection, oldLimit, oldSort, oldSearch, oldFilter, , , , , oldFilterSystem] = before;
```
Comment (Nitwel) [inline packages/composables/src/use-items.ts]: Not a big fan of that spread syntax, please move `filterSystem` so that we don't have all these empty spreads.

**Review by Nitwel — CHANGES_REQUESTED** [review]

**Comment by okxint** [comment]
Thanks for the review @Nitwel! Addressed all 4 comments:

1. **Simplified with `until`** — replaced the manual `watch`/`Promise` pattern with `until(loadingTotalCount).toBe(false)` from `@vueuse/core`
2. **Removed the try-catch** — it was unnecessary since we're just reading reactive values and awaiting, no error to catch there
3. **Kept watchers separate** — reverted the merge, the two watchers serve different purposes and are cleaner apart
4. **Removed spread syntax** — `filterSystem` is no longer in the first watcher's dependency array, so no empty slots needed

File: packages/composables/src/use-items.ts [hunk 5]
```diff
@@ -277,12 +281,40 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery):
...
+		if (isSearchEmpty && (isFilterEmpty || isEqual(filterVal, filterSystemVal))) {
+			loadingItemCount.value = true;
+
+			if (loadingTotalCount.value) {
+				// A getTotalCount request is already in flight — wait for it to complete
+				await until(loadingTotalCount).toBe(false);
+			} else if (totalCount.value === null) {
+				// No request in flight and no cached value — trigger one
+				await getTotalCount();
+			}
```
Comment (Nitwel) [inline packages/composables/src/use-items.ts]: Tests currently fail because getTotalCount will be run twice with the same arguments. By using `useMemoize()` from vueuse, we can prevent that and also simplify the code here to just call `getTotalCount()` as `useMemoize()` will reuse currently active promises.

**Review by Nitwel — CHANGES_REQUESTED** [review]

**Comment by okxint** [comment]
Refactored to use `useMemoize()` as suggested — the memoized `fetchAggregate` wrapper now deduplicates concurrent calls with the same arguments automatically, so `getItemCount` reuses the in-flight `getTotalCount` promise when no user filters are active. Removed the `loadingTotalCount` ref and `until()` waiting logic since memoization handles it naturally. Tests updated and passing.

**Review by Nitwel — APPROVED** [review]
Cleaned up unnecessary code. LGTM!
@okxint mind signing the CLA so we can merge this?

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:

**Review by ComfortablyCoding — DISMISSED** [review]
The CLA needs to be signed. 

P.S. AbortController was removed for total count, I believe this introduces a race condition where request 1 resolves after request 2 setting the wrong count?

**Comment by okxint** [comment]
CLA signed! Added my username to contributors.yml. Thanks for the cleanup commit and the approvals @Nitwel @AlexGaillard — ready to merge whenever you are.

**Comment by okxint** [comment]
@ComfortablyCoding Good catch on the race condition — you're right that without protection, a slow response from a previous collection/filter could overwrite a fresh result.

I've added generation counters to both `getTotalCount` and `getItemCount` (a9ac323). Each call increments a counter and captures the current value; when the response arrives, it checks whether a newer request has been initiated and discards stale results if so. This works cleanly with the existing `useMemoize` layer (which deduplicates concurrent calls with identical arguments) since the generation guard handles the cross-argument staleness case.

Re CLA: it's been signed (contributors.yml was updated in 5a04a51).

**Comment by okxint** [comment]
Good catch on the race condition concern @ComfortablyCoding — the AbortController was replaced with a generation counter pattern (`totalCountGeneration` at L282/L289). Each call to `getTotalCount()` increments the counter, and when the response arrives, it checks if a newer request was initiated in the meantime. If so, the stale result is discarded. This handles the same out-of-order response scenario without needing an AbortController.

CLA is signed and all 77 checks are green. Ready for another look when you get a chance!

**Comment by okxint** [comment]
@ComfortablyCoding Hey — I addressed the race condition concern about the AbortController pattern in my last comment. The generation counter approach ensures only the latest request's result is used, regardless of completion order. All 77 CI checks are green and I've got 2 approvals from @Nitwel and @AlexGaillard. Would you mind taking another look when you get a chance? Happy to make further changes if needed.

**Comment by ComfortablyCoding** [comment]
Thanks for the heads-up. One of us will circle back and review the changes as time allows.

**Review by Nitwel — APPROVED** [review]
LGTM!
