### PR TITLE
Fix arrow misalignment in M2A relation settings

### LINKED ISSUE #22348: [App] Many to any relationship arrow misalligned
### Describe the Bug

When selecting 5 or more related collections for a many-to-any relation the UI arrows will no longer line up.
image

### To Reproduce

- add a many to any field
- add 5 or more related collections to the relation
- look at the relationship tab

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

What's changed:

- Use a few wrappers to push the fields up or down
- Actually position the arrows with the fields they are pointing to / from to not rely on fixed positions

|Before|After few|After many|
|-|-|-|
| Screenshot 2024-04-30 at 19 48 05 | Screenshot 2024-04-30 at 19 40 43 | Screenshot 2024-04-30 at 19 40 54 |

## Potential Risks / Drawbacks

None

## Review Notes / Questions

None

---

Fixes #22348

### CODE REVIEW

File: app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2a.vue [hunk 1]
```diff
@@ -229,27 +239,30 @@ const unsortableJunctionFields = computed(() => {
...
+			--v-icon-color: var(--theme--primary);
+			position: absolute;
+			pointer-events: none;
 
-		&:first-of-type {
-			top: 117px;
-			left: 32.5%;
+			top: 50%;
+			transform: translateY(-50%);
+			right: -26px;
```
Comment (paescuj) [inline app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2a.vue:254]: Could you add a comment on what the value is based on?

**Review by paescuj — APPROVED** [review]
Funny issue, nice fix 😄
