### PR TITLE
Fix unexpected camera update and unavailable clustering option in map

### LINKED ISSUE #9543: Maps Slightly Zooming Out on All Interactions
Not sure what's going on here, but on 9.0.0, every time I do anything in the Map Layout (zoom, pan, etc) the map spins (thinking) and then automatically zooms out a bit. Slowly working back to the global view. Weird!

https://user-images.githubusercontent.com/522079/140576336-cf876d34-7858-4c06-bb9e-0c4c1878f65d.mp4

Maybe this is related to clustering? Not sure why but my clustering is on but the checkbox is disabled (so I can't turn it off to try it without). I'd like to know why this is disabled and make sure we add a tooltip explaining why it can't be turned off.

CC @Oreilles

### PR DESCRIPTION
**Pull request by oreilles**
Fixes https://github.com/directus/directus/issues/9543

### CODE REVIEW

File: app/src/layouts/tabular/index.ts [hunk 1]
```diff
@@ -142,9 +142,8 @@ export default defineLayout<LayoutOptions, LayoutQuery>({
 		function useItemOptions() {
 			const page = syncRefProperty(layoutQuery, 'page', 1);
 			const limit = syncRefProperty(layoutQuery, 'limit', 25);
-			const sort = syncRefProperty(layoutQuery, 'sort', () =>
-				primaryKeyField.value ? [primaryKeyField.value?.field] : []
-			);
+			const defaultSort = computed(() => (primaryKeyField.value ? [primaryKeyField.value?.field] : []));
+			const sort = syncRefProperty(layoutQuery, 'sort', defaultSort.value);
```
Comment (rijkvanzanten) [inline app/src/layouts/tabular/index.ts:146]: This is no longer reactive if my understanding of `.value` is correct. The `.value` here is the static value, while the `defaultSort` is the reactive object reference. Seeing you're using `unref` in the `syncRefProperty` util, I believe you can safely omit the `.value` from the usage here, and keep it reactive (eg make sure the default value updates when the `primaryKeyFIeld.value` updates)

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/layouts/tabular/index.ts (hunk 1 above)
Comment (Oreilles) [reply app/src/layouts/tabular/index.ts]: You're right, that was my intent! I hadn't push that change yet 😁
