### PR TITLE
Fix MySQL wkt conversion and fix SRID for Postgres geometry columns

### LINKED ISSUE #9614: Geometry field types are formatted incorrectly for MySQL schemas
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Looks like lat and long need to be reversed just for MySQL 8... I bet this never came up in testing since no one from down under tried to insert this data 😛

https://dba.stackexchange.com/questions/242001/mysql-8-st-geomfromtext-giving-error-latitude-out-of-range-in-function-st-geomfr

```
{
  "message": "
    insert into `areas` (`id`, `location`, `name`) 
    values ('c38f629f-a69d-4e64-a3a9-e70a1cbfe1e4', 
      st_geomfromtext('MULTIPOLYGON (((148.19430559458425 -25.359817002954728, 150.07262775362693 -26.12884590315783, 148.19430559458425 -27.953799657646407, 148.19430559458425 -25.359817002954728)))', 4326), 
    'Test 2') 
    - UNKNOWN_CODE_PLEASE_REPORT: Latitude 148.194306 is out of range in function st_geomfromtext. It must be within [-90.000000, 90.000000].",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

Slightly formatted error message for easier reading

### To Reproduce

Configure a collection interface for MultiPolygon and draw a shape over... Australia for instance.

### Errors Shown

_No response_

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.17.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

Docker

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by oreilles**
Don't set SRID in mysql st_geomfromtext because it then invert longitude and latitude.
Add explicit SRID when creating Postgis geometry columns.
Fixes https://github.com/directus/directus/issues/9614

### CODE REVIEW

File: api/src/database/helpers/geometry.ts [hunk 1]
```diff
@@ -87,14 +87,15 @@ class KnexSpatial_SQLite extends KnexSpatial {
...
+
 class KnexSpatial_PG extends KnexSpatial {
 	async supported() {
 		const res = await this.knex.select('oid').from('pg_proc').where({ proname: 'postgis_version' });
 		return res.length > 0;
 	}
 	createColumn(table: Knex.CreateTableBuilder, field: RawField | Field) {
 		const type = field.type.split('.')[1] ?? 'geometry';
-		return table.specificType(field.field, `geometry(${type})`);
+		return table.specificType(field.field, `geometry(${type}, 4326)`);
```
Comment (joselcvarela) [inline api/src/database/helpers/geometry.ts:98]: Hey @Oreilles 
This PR is supposed to fix on MySQL but you are modifying the Postgres side.
Is this supposed to be like this?

Comment (Oreilles) [reply api/src/database/helpers/geometry.ts:98]: Yes, I forgot to mention this in the PR. PostGIS supports explicictly naming the SRID in the type definition, guarantying that no other projection can be inserted - Since we will only ever send WGS84 data ( as per the GeoJSON spec ) it doesn't change anything to our flow, just a safety for use outside Directus!

**Review by rijkvanzanten — APPROVED** [review]

File: api/src/database/helpers/geometry.ts (hunk 1 above)
Comment (joselcvarela) [reply api/src/database/helpers/geometry.ts:98]: Thank for the clear explanation 🙏
