### PR TITLE
Fix drawer not scrolling to top when validation errors occur

### LINKED ISSUE #26735: Validation error in drawer does not scroll drawer to top
### Describe the Bug

When a validation error occurs inside a drawer, the drawer does not automatically scroll to the top. If the user has scrolled down, any validation messages are displayed at the top and will remain out of view. 

The item view behaves correctly and scrolls to the top (or directly to the invalid field) when a validation error is triggered.

### To Reproduce

1. Create two collections: `parent` and `child`, each with a required `title` field.
       - Add several additional fields to both collections so the form requires scrolling.
3. Add an O2M relationship field from `parent` → `child`.
4. In the `parent` item view, attempt to create a new parent item without filling in the required `title` field (ensure the `title` field is out of view by scrolling down).
5. Observe that the view correctly scrolls to the top (or to the invalid field).
6. Within the parent item view, open the O2M child drawer.
7. Repeat `#3` again inside the child drawer (submit without the required `title` field, ensuring it is out of view).
8. Observe that no scrolling occurs and there is no visible indication of the validation error unless manually scrolled to the top of the drawer.

[snapshot.json](https://github.com/user-attachments/files/25525453/snapshot.json)

https://github.com/user-attachments/assets/6a3cb73e-cf80-4d73-9733-005b2483110d

### Directus Version

v11.15.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by robluton**
## Scope                                                                                       
                                                                                      
  What's changed:                                                                                
                                                                                                 
  - When validation errors appear in
   a drawer, automatically scroll the drawer to the top so the errors are visible                
                                                            
  ## Potential Risks / Drawbacks

  - None that I can think of

  ## Tested Scenarios

  - Opened a O2M drawer with multiple fields (enough to require scrolling)
  - Scrolled down and submitted without filling in a required field
  - Verified the drawer scrolls to the top and the validation error banner is visible

  ## Review Notes / Questions

  - The fix mirrors the existing pattern in `v-form.vue`, which watches
  `validationErrors` and scrolls the form into view.

  ## Checklist

  - [ ] Added or updated tests ( don't think this is necessary for this small improvement )
  - [ ] Documentation PR created [here](https://github.com/directus/docs) or not required
  - [ ] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

  ---

  Fixes #26735

### CODE REVIEW

**Review by alvarosabu — APPROVED** [review]
LGTM

File: app/src/views/private/components/overlay-item-content.vue [hunk 1]
```diff
@@ -95,6 +96,15 @@ function useFile() {
 function useValidationScrollToField() {
 	const mainFormEl = useTemplateRef<any>('mainForm');
 	const junctionFormEl = useTemplateRef<any>('junctionForm');
+	const mainDrawerElement = inject<Ref<HTMLElement | null>>('main-element');
```
Comment (formfcw) [inline app/src/views/private/components/overlay-item-content.vue]: Using the mainDrawerElement here assumes that overlay-item-content only renders inside the drawer, but it can also render inside a modal or popover. Instead let’s put a templateRef on the ValidationErrors element and use scrollIntoView() to scroll it into the view.

File: app/src/views/private/components/overlay-item-content.vue [hunk 2]
```diff
@@ -95,6 +96,15 @@ function useFile() {
...
+
+	watch(
+		() => validationErrors,
+		(newVal, oldVal) => {
+			if (isEqual(newVal, oldVal)) return;
+			if (newVal?.length > 0) mainDrawerElement?.value?.scrollTo({ top: 0, behavior: 'smooth' });
+		},
+	);
```
Comment (formfcw) [inline app/src/views/private/components/overlay-item-content.vue]: The watcher here lives inside `useValidationScrollToField` which addresses a different concern. The logic here ensures that when we click on a field in the ValidationErrors, that the field is scrolled into the view. However, scrolling to the ValidationErrors when they are not in the view is a different concern. Therefore, either place the watcher outside the composable or consider renaming it so it to address both concerns.

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you @robluton :heart:

I’ve just noticed something here.

File: app/src/views/private/components/overlay-item-content.vue (hunk 1 above)
Comment (robluton) [reply app/src/views/private/components/overlay-item-content.vue]: Makes sense. I made the change.

File: app/src/views/private/components/overlay-item-content.vue (hunk 2 above)
Comment (robluton) [reply app/src/views/private/components/overlay-item-content.vue]: This should be addressed now. Thanks @formfcw!

File: app/src/views/private/components/overlay-item-content.vue [hunk 3]
```diff
@@ -44,6 +44,20 @@ const { mainInitialValues, junctionInitialValues } = useInitialValues();
 const { file } = useFile();
 const { scrollToField } = useValidationScrollToField();
 
+const validationErrorsEl = useTemplateRef<any>('validationErrors');
```
Comment (alvarosabu) [inline app/src/views/private/components/overlay-item-content.vue]: @robluton lets avoid typing as any.

```ts
const validationErrorsEl = useTemplateRef<typeof ValidationErrors>('validationErrors');
```

or just simply remove the type generic, it should be infered

```ts
const validationErrorsEl = useTemplateRef('validationErrors');
```

**Review by alvarosabu — DISMISSED** [review]

**Review by formfcw — APPROVED** [review]
Code review: LGTM :tada:

**Review by AlexGaillard — APPROVED** [review]
