### PR TITLE
Export Collection button now shows collection name not table name

### LINKED ISSUE #7361: Missing Translation for directus_webhooks
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Screen Shot 2021-08-11 at 9 34 30 AM

### To Reproduce

See button text above

### What version of Directus are you using?

INTERNAL

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

### PR DESCRIPTION
**Pull request by jamescammarano**
Changed export collection button to use collection.name instead of collection.collection.
Fixes #7361

### CODE REVIEW

File: app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue [hunk 1]
```diff
@@ -25,7 +25,7 @@
 
 			<div class="field full">
 				<v-button full-width @click="exportData">
-					{{ t('export_collection', { collection }) }}
+					{{ t('Export ' + collectionName) }}
```
Comment (rijkvanzanten) [inline app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue:28]: This won't work. The string value in the `t()` function matches the translation key under `lang/en-us.yaml`.

```suggestion
					{{ t('export_collection', { collection: collectionName }) }}
```

File: app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue [hunk 2]
```diff
@@ -65,13 +66,21 @@ export default defineComponent({
...
 
 		const format = ref('csv');
 		const useFilters = ref(true);
+		const collections = useCollectionsStore();
+		let collectionName;
+		collections.visibleCollections.forEach((collection) => {
+			if (collection.collection === props.collection) {
+				collectionName = collection.name;
+			}
+		});
```
Comment (rijkvanzanten) [inline app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue:81]: Use `collectionsStore.getCollection()` instead https://github.com/directus/directus/blob/af4dbad27d6f96a592959325dadc2f06946fdbd6/app/src/stores/collections.ts#L110-L112

(ps, instead of forEach with an if-statement, it's easier to use a `.find()` 🙂

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue [hunk 3]
```diff
@@ -65,13 +66,16 @@ export default defineComponent({
...
 	setup(props) {
 		const { t } = useI18n();
 
 		const format = ref('csv');
 		const useFilters = ref(true);
+		const collectionsStore = useCollectionsStore();
+		let collectionName = collectionsStore.getCollection(props.collection).name;
 
-		return { t, format, useFilters, exportData };
+		return { t, format, useFilters, exportData, collectionName };
```
Comment (rijkvanzanten) [inline app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue:78]: One last thing: We should make this a `computed` value so it updates once the `collection` prop changes, otherwise it only fetches it once on setup, and doesn't update when the collection prop changes 🙂

Comment (rijkvanzanten) [reply app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue:78]:
```
const collectionName = computed(() => collectionsStore.getCollection(props.collection).name);
```

**Review by rijkvanzanten — APPROVED** [review]
