### PR TITLE
Only emit value if updated for wysiwyg interface

### LINKED ISSUE #14215: Duplicate entries when pasting into WYSIWYG nested in translations
### Describe the Bug

When pasting values into the WYSIWYG interface that is nested in translations, duplicate entries are created.

Issue reported by @joselcvarela [here](https://github.com/directus/directus/pull/13802/files/bfd2727789e9cfee13869211389fa0852a6d53c0#r910659562) 

### To Reproduce

https://user-images.githubusercontent.com/26413686/176675704-3a784108-1841-4fbc-b745-41c8c3734938.mov

### Errors Shown

_No response_

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #14215.

https://user-images.githubusercontent.com/26413686/176678384-04c8ad21-a989-4a42-a541-3ec6a3c3c55b.mov

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: app/src/interfaces/input-rich-text-html/input-rich-text-html.vue [hunk 1]
```diff
@@ -427,7 +428,11 @@ export default defineComponent({
 
 			if (!observer) return;
 
-			emit('input', editorRef.value.getContent() ? editorRef.value.getContent() : null);
+			const newValue = editorRef.value.getContent() ? editorRef.value.getContent() : null;
+
+			if (newValue === emittedValue) return;
+
+			emit('input', (emittedValue = newValue));
```
Comment (rijkvanzanten) [inline app/src/interfaces/input-rich-text-html/input-rich-text-html.vue:435]:
```suggestion
			emittedValue = newValue;
			emit('input', newValue);
```

**Review by rijkvanzanten — APPROVED** [review]
