### PR TITLE
Fix `withToken` precedence if a token is already saved in SDK client

### LINKED ISSUE #23176: Javascript SDK: make withToken usable for other clients
### Describe the Bug

When using `withToken(...)` on a client that uses static tokens, the call will fail, e.g. `withToken` seems to be ignored. In order not to create an additional client, it would be handy if `withToken` is always evaluated first, regardless of the other auth composables applied.

### To Reproduce

```
    // static token client
    this.tokenClient = createDirectus(url).with(rest()).with(staticToken(my_static_token));
    // fails
    await tokenClient.request(withToken(token, readItem('my_collection', id)));
    
    // restClient
    this.restClient = createDirectus(url).with(rest());
    // succeeds
    await restClient.request(withToken(token, readItem('my_collection', id)));    
```

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgrSQL

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

Previously, if a `token` was saved in the SDK client (and retrievable with `getToken`) it would override any already set authorization headers. This would result in the reported behavior of not being able to override the saved token using the `withToken` utility, which would be the more desirable behavior.

## Review Notes / Questions

- Is this technically a breaking change? I can't really imagine a situation where one would expect the `withToken` util to not override a saved token.

---

Fixes #23176

### CODE REVIEW

File: sdk/src/rest/composable.ts [hunk 1]
```diff
@@ -31,11 +31,10 @@ export const rest = (config: Partial<RestConfig> = {}) => {
 				}
 
 				// we need to use THIS here instead of client to access overridden functions
-				if ('getToken' in this) {
+				if ('getToken' in this && 'Authorization' in options.headers === false) {
```
Comment (br41nslug) [inline sdk/src/rest/composable.ts:34]: This line will error if `options.headers` is `undefined`
image

```suggestion
				if ('getToken' in this && (!options.headers || 'Authorization' in options.headers === false)) {
```

Comment (hanneskuettner) [reply sdk/src/rest/composable.ts:34]: We force `options.headers` to always be defined a couple of lines above it tho

https://github.com/directus/directus/blob/5e9e4b79dff85fc9e76d0305b6f3c11b1f5f7635/sdk/src/rest/composable.ts#L22-L24

Comment (br41nslug) [reply sdk/src/rest/composable.ts:34]: fair point did not see that in the PR diff 😄

**Review by br41nslug — APPROVED** [review]
🚀
