### PR TITLE
Fix Save As Copy when duplicating M2M/O2M fields

### LINKED ISSUE #21895: Save As Copy does not work when having O2M/M2M relationships
### Describe the Bug

When trying to Save As Copy an item, the save icon keeps looping forever and a 400 error appears on Network.
This happens because there's a M2M relationship selected on Item Duplication Fields, but App it's not recognizing it properly.

The error that appears is:
```
{
    "errors": [
        {
            "message": "Invalid query. \"fields[1]\" is not allowed to be empty.",
            "extensions": {
                "code": "INVALID_QUERY",
                "reason": "\"fields[1]\" is not allowed to be empty",
                "stack": "DirectusError: Invalid query. \"fields[1]\" is not allowed to be empty.\n    at validateQuery (/directus/directus/api/src/utils/validate-query.ts:49:9)\n    at sanitizeQueryMiddleware (/directus/directus/api/src/middleware/sanitize-query.ts:24:2)\n    at Layer.handle [as handle_request] (/directus/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/directus/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:328:13)\n    at /directus/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/directus/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:346:12)\n    at next (/directus/directus/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:280:10)\n    at <anonymous> (/directus/directus/api/src/middleware/check-ip.ts:24:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
            }
        }
    ]
}
```

### To Reproduce

Here's a how to reproduce the issue:
- Create collection A
- Create collection B with M2M field called X pointing to A
- On Item Duplication Fields within collection B, select all root fields, including X field
- Create items in A
- Create items on B with relationship to A items
- Edit one item on B and save as copy

https://github.com/directus/directus/assets/14039341/4005eda5-1fb2-4c27-9f79-92f32f2027ec

### Directus Version

main(10.10.4)

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope
This PR fixes an issue when duplicating an item which has relationships but only the root level field is selected on Item Duplication fields within collection. More can be seen on the linked issue below

What's changed:

- Fetch all root fields from related collection when saving item as copy

## Potential Risks / Drawbacks

- None as I can think of as current behaviour is currently not working as expected

## Review Notes / Questions

- I was thinking if we could optimize by selecting only the fields we want  instead of selecting all of them with `*` but, since the root field is selected in Item Duplication Fields, I expect that all related fields should be fetched

---

Fixes #21895

### CODE REVIEW

File: app/src/composables/use-item.ts [hunk 1]
```diff
@@ -210,7 +210,7 @@ export function useItem<T extends Record<string, any>>(
 			if (relation.meta?.one_field && relation.meta.one_field in newItem) {
 				const fieldsToFetch = fields
 					.filter((field) => field.startsWith(relation.meta!.one_field!))
```
Comment (licitdev) [inline app/src/composables/use-item.ts:212]: I've not found any issue with this fix, but noticed an oddity with the use of `field.startsWith()` for filtering. 
Eg: `m2m` and `m2m_other` both start with `m2m`, resulting in duplicate fields requested. 

It might need to be updated to be more specific or it could be an issue with my local schema. 🤔 
Will have to investigate further, but it's probably out of the PR's scope.

Comment (paescuj) [reply app/src/composables/use-item.ts]: Fixed in 80c9893c6e5ce684747c10ac5cc85c50638eb368

**Review by paescuj — APPROVED** [review]
Tested with all relationships -> LGTM 🚀
