### PR TITLE
Fix skipping marketplace for local extensions

### LINKED ISSUE #25322: Fix fetching extension id from extension registry if extension is local
### Describe the Bug

#25304 included 2 oversights which I didn't catch at first.
1. We're using the search parameter which can get the wrong extension id in certain scenarios.
2. We're searching the registry for local extensions which are never in the registry

### To Reproduce

...

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- Small fix to @joselcvarela 's recent PR.

~~The 2nd fix which is coming later would be to implement a proper way to fetch the ID by name. The search parameter can yield results even if there is no 1 to 1 match in the extension name.~~ Resolved by using find and matching on name as a temp fix

---

Builds upon #25304
Fixes #25322

### CODE REVIEW

File: api/src/extensions/lib/get-extensions-settings.ts [hunk 1]
```diff
@@ -72,8 +72,14 @@ export const getExtensionsSettings = async ({
 		extension: Extension,
 		source: 'local' | 'registry' | 'module',
 	) => {
-		const marketplace = await list({ search: extension.name });
-		const id = marketplace.data[0]?.id || randomUUID();
+		let marketplaceId;
+
+		if (!extension.local) {
```
Comment (ComfortablyCoding) [inline api/src/extensions/lib/get-extensions-settings.ts]: Per discussion this should be checking `source`, not `local`. `local` is used to indicate if it is an extension that is stored on disk which both local and registry are (via `.registry`)[^1][^2]
```suggestion
		if (source === 'registry') {
```

---
[^1]: https://github.com/directus/directus/blob/main/api/src/extensions/lib/get-extensions.ts
[^2]: https://github.com/directus/directus/blob/bd064fe1d2f7eeb7294e0786f8550816e09b6e82/packages/extensions/src/node/utils/get-extensions.ts#L104

**Comment by ComfortablyCoding** [comment]
### Tests
- [x] Expect local extension with conflicting registry extension name should generate its own uuid
- [x] Expect search to match extension name exactly - checked with `directus-extension-flexible-editor` which returns multiple results
- [x] Expect request to only be sent for registry extensions

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
