### PR TITLE
Overflow in manual flow's confirmation dialog

### LINKED ISSUE #18306: Overflow in manual flow's confirmation dialog is broken
### Describe the Bug

When using WYSIWYG editor inside confirmation dialog and paste pretty large text you will see this

image

Look at the buttons, they outside modal, if text will be even bigger, it will be impossible to click on this buttons

P.S. It works fine with textarea, because textarea have scrollbar by itself

### To Reproduce

Create manual flow with confirmation dialog, add WYSIWYG field and paste some text

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #18306 

Adds scrollbars when needed in the flow confirmation dialog.

firefox_g2PrBvnGCr

### CODE REVIEW

File: app/src/views/private/components/flow-sidebar-detail.vue [hunk 1]
```diff
@@ -247,4 +247,14 @@ const runManualFlow = async (flowId: string) => {
 		font-size: 1rem;
 	}
 }
+
+.card {
```
Comment (rijkvanzanten) [inline app/src/views/private/components/flow-sidebar-detail.vue:251]: Feels like this should be part of `v-card` rather than a one-off override 🤔

File: app/src/interfaces/input-rich-text-html/input-rich-text-html.vue [hunk 2]
```diff
@@ -23,7 +23,7 @@
 			</span>
 		</template>
 		<v-dialog v-model="linkDrawerOpen">
-			<v-card class="card">
+			<v-card>
 				<v-card-title class="card-title">{{ t('wysiwyg_options.link') }}</v-card-title>
```
Comment (paescuj) [inline app/src/interfaces/input-rich-text-html/input-rich-text-html.vue:27]:
```suggestion
				<v-card-title>{{ t('wysiwyg_options.link') }}</v-card-title>
```

**Review by paescuj — APPROVED** [review]
❤️

File: .changeset/chatty-clocks-kick.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@directus/app": patch
+---
+
+Added overflow scrollbars in manual flow's confirmation dialog
```
Comment (azrikahar) [inline .changeset/chatty-clocks-kick.md:5]:
```suggestion
Added overflow scrollbars in v-card component
```

As we moved the fix to v-card, I believe this change should describe the current PR clearer 👍 (of course we can update this afterwards if there's a better way to describe it 😄)

**Review by azrikahar — APPROVED** [review]
