### PR TITLE
Only show message on just request/exec flow operations

### LINKED ISSUE #18161: No error code is returned when the Update Item Operation fails
### Describe the Bug

I recently updated my self-hosted directus instance to the latest release and found that the "update item operation" only returns "message" but no "Error Code" when it fails. This caused some of Flows that relied on Error Codes to no longer work properly.
The change seems to be from the PR #17519 .

### To Reproduce

Create a flow that raises a "not unique error".
There is no Error Code "RECORD_NOT_UNIQUE" in the log.

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by connorwinston**
This fixes #18161 which was caused by errors being swallowed by #17519.

We had changed the flows to only return `error.message` to prevent sensitive information being released from Run Scripts, however, it was not limited to run scripts which resulted in other operations also being stripped of information.

@br41nslug Can you confirm that this is acceptable from a security stand point? Should any other operations also return only `error.message`?

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/flows.ts [hunk 1]
```diff
@@ -421,8 +421,12 @@ class FlowManager {
...
 
 			if (error instanceof Error) {
-				// If the error is instance of Error, use the message of it as the error data
-				data = { message: error.message };
+				// If the error is from a request or exec operation, use the message of it as the error data
+				if (operation.type == 'request' || operation.type == 'exec') {
+					data = { message: error.message };
+				} else {
+					data = error;
+				}
```
Comment (br41nslug) [inline api/src/flows.ts:429]: As the original issue is that the code is not passed on, should we not add that instead. The point of the mentioned PR was to not expose the stack trace but we can add the code where applicable 😄 
```suggestion
if (error instanceof BaseException) {
	// "code" is part of our BaseException
	data = { message: error.message, code: error.code, extensions: error.extensions };
} else if (error instanceof Error) {
	// and does not exist in the native Error
	data = { message: error.message };
```

**Review by br41nslug — CHANGES_REQUESTED** [review]

File: api/src/flows.ts (hunk 1 above)
Comment (rijkvanzanten) [reply api/src/flows.ts:429]: @br41nslug That looks great to me @br41nslug!

**Review by rijkvanzanten — APPROVED** [review]

**Review by br41nslug — DISMISSED** [review]
Works as i'd expect now 😄 ~~as a final thought: should we include `status` too for BaseExceptions? 🤔 noticed it was there just now but no clue what data is in that specific field~~

A regular error:
firefox_Y3Non0XU3J

A BaseException:
firefox_ZSW1FN2e3A

**Review by br41nslug — APPROVED** [review]
Noticed error can be an array or errors aswell but lets address that in a new PR
