### PR TITLE
Fix MySQL migration compatibility with sql_require_primary_key

### LINKED ISSUE #26324: Migrations failing for mysql 8
### Describe the Bug

Hey,
i tried installing directus today via coolify (they use the `directus/directus:11` image inside a docker compose template). in my setup im using a hosted mysql cluster and therefore `sql_require_primary_key = ON` is set for good reasons. 

currently the migration `/api/src/database/migrations/20240204A-marketplace.ts` is failing during initial setup, as it leaves the `directus_extensions` table without a primary key for a moment as the following error messages suggests:
```
sqlMessage: "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.",
```

as far is i researched inside this repo the following issue: https://github.com/directus/directus/issues/21828 and this PR: https://github.com/directus/directus/pull/22019 are likely involved.

If its a intended requirement to disable that rule within the database i would expect that its somehow explicitly mentioned in the docs. 
My guess is that this would make directus likely unusable with replicated sql databases? As its unsafe to turn that check off especially in such scenarios?

### To Reproduce

Set up a new project with Directus 11.xx.xx and some mysql database with `sql_require_primary_key = ON`

### Directus Version

v11.xx.xx;  Dockerimage: directus/directus:11

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql 8 (provisioned by digitalocean)

### PR DESCRIPTION
**Pull request by gaetansenn**
## Scope

What's changed:

- Use atomic `ALTER TABLE` statement for MySQL when changing primary keys in migration `20240204A-marketplace.ts`

## Tested Scenarios

- Fresh install on MySQL 8 with `sql_require_primary_key=ON` (blackbox `mysql-strict`)
- Migration `up` and `down` functions work correctly

## Review Notes / Questions

- Same pattern already used in other migrations

## Checklist

- [ ] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required
- [ ] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26324

### CODE REVIEW

**Review by ComfortablyCoding — DISMISSED** [review]
This should be added as a schema helper so it can be reused in other migrations/locations.

Sample: https://github.com/directus/directus/pull/25280

**Comment by gaetansenn** [comment]
> This should be added as a schema helper so it can be reused in other migrations/locations.
> 
> Sample: #25280

Moved into the schema helper from this [commit](https://github.com/directus/directus/pull/26374/changes/84fb40773803ae4738f6314f3d61558c9ebfe45b)

File: api/src/database/helpers/schema/types.ts [hunk 1]
```diff
@@ -67,6 +67,15 @@ export abstract class SchemaHelper extends DatabaseHelper {
 		});
 	}
 
+	async changePrimaryKey(table: string, columns: string | string[]): Promise<void> {
+		const primaryColumns = Array.isArray(columns) ? columns : [columns];
```
Comment (ComfortablyCoding) [inline api/src/database/helpers/schema/types.ts]: Let's use our toArray util here

File: api/src/database/helpers/schema/dialects/mysql.ts [hunk 2]
```diff
@@ -14,6 +14,13 @@ export class SchemaHelperMySQL extends SchemaHelper {
 		return getDefaultIndexName(type, collection, fields, { maxLength: 64 });
 	}
 
+	override async changePrimaryKey(table: string, columns: string | string[]): Promise<void> {
+		const primaryColumns = Array.isArray(columns) ? columns : [columns];
```
Comment (ComfortablyCoding) [inline api/src/database/helpers/schema/dialects/mysql.ts]: Same as https://github.com/directus/directus/pull/26374#discussion_r2631272085

Comment (gaetansenn) [reply api/src/database/helpers/schema/dialects/mysql.ts]: Good point ! Made the changes

**Review by ComfortablyCoding — APPROVED** [review]

**Review by AlexGaillard — APPROVED** [review]
