### PR TITLE
do not remove custom devDependencies on bundle add

### LINKED ISSUE #20394: `directus-extension add` rewrites package.json
### Describe the Bug

If custom `devDependencies` have been added during a development of a bundle-type extension, running `directus-extension add` deletes them.

Additional, lesser parts of the problem also are:

- other entries in the `package.json`, albeit preserved, are moved around and changed places, which introduces unnecessary VCS changes
- CLI has no option to skip actual invocation of `npm install`, like Composer does e.g. with `composer update --no-install`, to only update the `.json` file and be able to review changes before time-consuming installation process is initiated

### To Reproduce

1. Generate an initial extension structure with `npx create-directus-extension`, provide extension type "bundle"
2. Run `directus-extension add` to add e.g. a hook
3. Add some dev dependencies by running `npm install <SOME_DEP> --save-dev`
4. Run `directus-extension add` to scaffold another part of your bundle, e.g. an interface
5. Your `devDependencies` are now reverted to initial state, your custom ones are uninstalled, those that Directus itself adds are reverted to earlier versions

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- we no longer remove custom devDependencies from the package.json when a new extension is added to the bundle.

## Potential Risks / Drawbacks

- N/A

## Review Notes / Questions

- ~Special attention should be paid to the naming of the option `base` as the current defined devDeps, base seemed to be somewhat appropriate.~ This is no longer relevant.

---

Fixes #20394

### CODE REVIEW

File: packages/extensions-sdk/src/cli/commands/add.ts [hunk 1]
```diff
@@ -133,6 +133,7 @@ export default async function add(): Promise<void> {
 			devDependencies: await getExtensionDevDeps(
 				newEntries.map((entry) => entry.type),
 				getLanguageFromEntries(newEntries),
+				{ base: extensionManifest.devDependencies },
 			),
```
Comment (paescuj) [inline packages/extensions-sdk/src/cli/commands/add.ts:137]: Honstely, I'd choose this route. Makes it easier to see what's happening to the existing deps.

```suggestion
			devDependencies: {
				...extensionManifest.devDependencies,
				...(await getExtensionDevDeps(
					newEntries.map((entry) => entry.type),
					getLanguageFromEntries(newEntries),
				)),
			},
```

Comment (paescuj) [reply packages/extensions-sdk/src/cli/commands/add.ts:137]: ... and we don't have to care about the parameter / option name 😃

Comment (ComfortablyCoding) [reply packages/extensions-sdk/src/cli/commands/add.ts:137]: I was originally going to go this way but decided to use the options route for the following reasons:
- slightly more performant as we are just adding keys, no double spread.
- allows us to re-use this logic without needing to spread every time we want to keep the base deps.

I do agree it might not be as clear as a spread but I was hoping the reasons above outweighed that.

Comment (paescuj) [reply packages/extensions-sdk/src/cli/commands/add.ts:137]: > - slightly more performant as we are just adding keys, no double spread.

In my opinion, this can be neglected in this case. If, for example, we were dealing with an operation in the API, then yes, absolutely! 🚀🙏 But for this one-off command, it has no noticeable effect.

> - allows us to re-use this logic without needing to spread every time we want to keep the base deps.

I think the function `getExtensionDevDeps` currently does exactly what it should: returning the dev dependencies that are specific to the extension.
To me it feels a bit strange to pass the existing dependencies to this function and expect it to merge them. Which is why I would prefer to do it outside of the function. 

But that probably goes in the direction of personal preference, so you have my approval and I'll leave it up to you to make the final decision.

**Review by paescuj — APPROVED** [review]

File: packages/extensions-sdk/src/cli/commands/add.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply packages/extensions-sdk/src/cli/commands/add.ts]: Fair point, I have updated the code accordingly.
