### PR TITLE
KanBan Avatar fix Fallback Icon and SVG Logic

### LINKED ISSUE #18900: User avatars are not loading in Kanban layout
### Describe the Bug

image
image

It is not loading, because there is no src in image tag, not sure why

### To Reproduce

Create Kanban layout, create user, add avatar (in my case I using Azure storage), avatar will not load in Kanban layout, even on admin account with all privileges

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by connorwinston**
Fixes the logic for falling back to an icon and fixes the SVG logic.

Fixes #18900

### CODE REVIEW

File: app/src/layouts/kanban/kanban.vue [hunk 1]
```diff
@@ -165,7 +165,7 @@ function openEditGroup(group: Group) {
 function parseAvatar(file: Record<string, any>) {
 	if (!file || !file.type) return;
 	if (file.type.startsWith('image') === false) return;
-	if (file.type.includes('svg')) return;
+	if (!file.type.includes('svg')) return;
```
Comment (rijkvanzanten) [inline app/src/layouts/kanban/kanban.vue:168]: I'm gonna assume there was a good reason previously to don't render SVGs in here 🤔

File: app/src/layouts/kanban/kanban.vue [hunk 2]
```diff
@@ -165,7 +165,7 @@ function openEditGroup(group: Group) {
...
 
 	const url = getRootPath() + `assets/${file.id}?modified=${file.modified_on}&width=48&height=48`;
```
Comment (rijkvanzanten) [inline app/src/layouts/kanban/kanban.vue:170]: While we're in here.. Mind updating this to use `key=` with one of the system ones? Direct width/height usage might be disabled

File: app/src/layouts/kanban/kanban.vue (hunk 1 above)
Comment (ConnorSimply) [reply app/src/layouts/kanban/kanban.vue:168]: I believe it was just an oversight. Looking through the commits this code was added in the initial refactor commit by Azri. But if you can confirm @azrikahar that would be great. The Cards layout loads SVGs so I don't know this wouldn't.

Comment (rijkvanzanten) [reply app/src/layouts/kanban/kanban.vue:168]: @ConnorSimply Can we try using a `v-image` for this rather than the ``? This might be one of the reasons of the potential of the app hitting the rate limiter (cc @joselcvarela )

File: app/src/layouts/kanban/kanban.vue (hunk 2 above)
Comment (ConnorSimply) [reply app/src/layouts/kanban/kanban.vue:170]: Done :)

**Review by rijkvanzanten — APPROVED** [review]
