### PR TITLE
Refresh datetime display value every minute for relative format

### LINKED ISSUE #12859: AutoRefresh does not refresh the relative timestamp column value
### Describe the Bug

A timestamp column's Relative Time does not update when using Auto Refresh.

Although it makes sense *why* it isn't updating (because technically the table's underlying data is not actually changing).

In the UI, it should update whether the page is reloaded, or Auto Refresh is used.

A table's column "Updated"::timestamp set to "SaveCurrentDateTime" on create/update.  
Display set to "Show Relative Time".
In user mode, the "Auto Refresh" is set to 10sec.
The relative value of "a few minutes ago" never changes unless page is reloaded manually or navigated away and back to.   Despite the refresh triggering every X seconds.

Note, I have all caching disabled.

### To Reproduce

create timestamp column and set to  "Save Current Date Time" on update.
in Display, set it to "Show Relative Time"
In user mode, the "Auto Refresh" is set to 10sec.
Value doesn't change

### Errors Shown

_No response_

### What version of Directus are you using?

9.9

### What version of Node.js are you using?

16.14.2

### What database are you using?

postgres 14

### What browser are you using?

chrome

### How are you deploying Directus?

CLI npm package

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #12859

Set to 1 minute interval when relative prop is true, as lower interval wouldn't be useful to change `1 minute ago` to `2 minutes ago` for example.

## After change

https://user-images.githubusercontent.com/42867097/164191218-2f930127-f316-4d15-a027-980b2f4addd5.mp4

### CODE REVIEW

File: app/src/displays/datetime/datetime.vue [hunk 1]
```diff
@@ -2,88 +2,93 @@
...
-		);
-
-		return { displayValue };
+			displayValue.value = await localizedFormat(newValue, format);
+		}
 	},
+	{ immediate: true }
+);
+
+const refreshInterval = ref<number | null>(null);
```
Comment (nickrum) [inline app/src/displays/datetime/datetime.vue:79]: Not that it would make much of a difference performance-wise, but `refreshInterval` can just be a regular value instead of a reactive one.

**Review by nickrum — CHANGES_REQUESTED** [review]

File: app/src/displays/datetime/datetime.vue (hunk 1 above)
Comment (azrikahar) [reply app/src/displays/datetime/datetime.vue]: good point! Was actually just using it out of habit 😄

Comment (nickrum) [reply app/src/displays/datetime/datetime.vue]: I know how that goes 😁 You get used to writing `ref`s everywhere pretty quickly!

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/displays/datetime/datetime.vue [hunk 2]
```diff
@@ -2,88 +2,93 @@
...
+interface Props {
+	value: string;
+	type: 'dateTime' | 'date' | 'time' | 'timestamp';
+	format?: string;
+	relative?: boolean;
+}
+
+const props = withDefaults(defineProps<Props>(), {
+	format: 'long',
+	relative: true,
```
Comment (nickrum) [inline app/src/displays/datetime/datetime.vue:21]: Changing the default of the `relative` prop to `true` causes the datetime display to always be relative because the prop default and the display option default aren't the same. When the display option for _relative_ is turned of, it will simply use the component's default value (which is `true`) and when it is turned on, it will also be `true`.

Comment (azrikahar) [reply app/src/displays/datetime/datetime.vue:21]: Ah nice catch. Thought it was a 1-to-1 change, but it's definitely always true now.. Removing it should be the way to go right? Tested that and it seems to work.

Comment (rijkvanzanten) [reply app/src/displays/datetime/datetime.vue:21]: Ref 1486d37eb

Comment (azrikahar) [reply app/src/displays/datetime/datetime.vue:21]: scratch that... for some reason the default is `true` in my head, even when it was `false` all along 🤦‍♂️
