### PR TITLE
Do not throw unhandled error on passing a null query

### LINKED ISSUE #24147: Websocket Query does not error when null provided
### Describe the Bug

When subscribing:
- omitting query works fine
- sending "query":null breaks (no init message) without an error response
- sending "query":{} works fine

There is probably some kind of missing null coalesce. 
I was trying this with directus_collections and directus_fields which do not support the query parameter. I didn't have time to verify if the issue occurs for user created collections.

### To Reproduce

Establish an authenticated websocket connection.
Send the following:
`{"type":"subscribe","uid":"s:test","collection":"directus_fields","query":null}`

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- We now throw an `INVALID_PAYLOAD` error for invalid query types (i.e. anything aside from `undefined` or a `query` object)
Screenshot 2025-03-05 at 2 50 26 PM

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- N/A

---

Fixes #24147

### CODE REVIEW

File: api/src/websocket/handlers/subscribe.ts [hunk 1]
```diff
@@ -162,8 +162,12 @@ export class SubscribeHandler {
 					subscription.event = message.event as SubscriptionEvent;
 				}
 
-				if ('query' in message) {
-					subscription.query = sanitizeQuery(message.query!, accountability);
+				if (message.query) {
+					if (typeof message.query === 'object' && !Array.isArray(message.query)) {
```
Comment (br41nslug) [inline api/src/websocket/handlers/subscribe.ts:166]: If im reading this right the WebSocket error gets thrown when the `query` is an object and not is an array. This should be the other way around:
```suggestion
					if (typeof message.query !== 'object' || Array.isArray(message.query)) {
```

**Review by br41nslug — CHANGES_REQUESTED** [review]

File: api/src/websocket/handlers/subscribe.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply api/src/websocket/handlers/subscribe.ts:166]: That is correct 😅 , looks like i got them mixed up with the passing condition

**Review by br41nslug — DISMISSED** [review]

**Review by br41nslug — APPROVED** [review]
Nice fix! 🧹
