### PR TITLE
Fix unique name check for extension locations and extensions within bundles

### LINKED ISSUE #20412: Bundle entries unique name check
### Describe the Bug

When creating a bundle type extension, all names across all bundle types still need to be unique. https://github.com/directus/directus/pull/20221 purported to fix this issue.
Having inspected the code, the fix in that Pull Request that adds the extension type to the unique check for extension names only seems to address certain extension types.
When running the Directus instance the following error gets generated:
```logs
[16:00:24.796] WARN: Couldn't load extensions
[16:00:24.797] WARN: insert into `directus_extensions` (`enabled`, `name`) select true as `enabled`, 
'directus-extension-bug-repro' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` - SQLITE_CONSTRAINT: UNIQUE constraint failed: directus_extensions.name
err: {
  "type": "Error",
  "message": "insert into `directus_extensions` (`enabled`, `name`) select true as `enabled`, 'directus-extension-bug-repro' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` - SQLITE_CONSTRAINT: UNIQUE constraint failed: directus_extensions.name",
  "stack":
      Error: insert into `directus_extensions` (`enabled`, `name`) select true as `enabled`, 'directus-extension-bug-repro' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` - SQLITE_CONSTRAINT: UNIQUE constraint failed: directus_extensions.name
  "errno": 19,
  "code": "SQLITE_CONSTRAINT"
}
```
This seems to generate a warning on sqlite but generates an error on Postgres, for example.

### To Reproduce

1. In a blank folder create a Docker Compose file as outlined in https://docs.directus.io/self-hosted/quickstart.html#create-a-docker-compose-file
2. Create a new bundle extension type as outlined in https://docs.directus.io/extensions/bundles.html
3. Run npm add twice, for two different extension types (interface, display for example) **but** give these extensions the exact same name.
4. Jimmy the package.json `directus:extension.entries` to point to different files/folders.
5. Build the extension using `npm run build` and copy the contents to the `extensions` folder with correct folder naming conventions as outlined in https://docs.directus.io/extensions/installing-extensions.html#installing-through-the-extensions-folder
6. Run command `docker compose up` and see error output:
```logs
[16:00:24.796] WARN: Couldn't load extensions
[16:00:24.797] WARN: insert into `directus_extensions` (`enabled`, `name`) select true as `enabled`, 
'directus-extension-bug-repro' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` - SQLITE_CONSTRAINT: UNIQUE constraint failed: directus_extensions.name
err: {
  "type": "Error",
  "message": "insert into `directus_extensions` (`enabled`, `name`) select true as `enabled`, 'directus-extension-bug-repro' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` - SQLITE_CONSTRAINT: UNIQUE constraint failed: directus_extensions.name",
  "stack":
      Error: insert into `directus_extensions` (`enabled`, `name`) select true as `enabled`, 'directus-extension-bug-repro' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` union all select true as `enabled`, 'directus-extension-bug-repro/currency' as `name` - SQLITE_CONSTRAINT: UNIQUE constraint failed: directus_extensions.name
  "errno": 19,
  "code": "SQLITE_CONSTRAINT"
}
```

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Duplicate extension names within a bundle are now properly filtered out.
   -  `./extensions/directus-extension-my-bundle`
       - `my-interface`
       - `my-display`
       - `my-interface`
- Attempting to add an extension with a duplicate name to a bundle via the cli will now error.
- Duplicate extension names within an extension location (local, npm etc) will now properly filter out.
  - `./extensions/directus-extension-my-bundle`
     - `name: "my-bundle"`
  - `./extensions/directus-extension-my-bundle1`
     - `name: "my-bundle"`

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- Added a log message for when an extension (whether in a bundle or not) is filtered out.
- The entire bundle is disabled if there are duplicate entries. Reasoning here is usually bundle entries are dependant upon one another.
- Should we start using the folder names as the extension names? These are guaranteed to be unique.

---

Fixes #20412

### CODE REVIEW

File: packages/extensions-sdk/src/cli/commands/add.ts
Comment (br41nslug) [inline packages/extensions-sdk/src/cli/commands/add.ts:1]: I think it would be good to add this uniqueness check to the `build` command too 😄

File: api/src/extensions/lib/get-extensions.ts [hunk 1]
```diff
@@ -8,7 +8,15 @@ export const getExtensions = async () => {
...
+
+		if (isUnique) {
+			loadedNames.push(name);
+		}
+
+		return isUnique;
+	};
 
 	const localPackageExtensions = (await resolvePackageExtensions(getExtensionsPath())).filter((extension) =>
 		filterDuplicates(extension),
```
Comment (paescuj) [inline api/src/extensions/lib/get-extensions.ts:22]: I don't like `.filter` being used with side effects, I'd prefer a `for` loop here which pushes to `localPackageExtensions`, in combination with a `Set` (`loadedNames.has`) for unique checks.

File: packages/extensions-sdk/src/cli/commands/add.ts [hunk 2]
```diff
@@ -101,6 +101,11 @@ export default async function add(options: AddOptions): Promise<void> {
 			},
 		]);
 
+		if (extensionOptions.entries.map((entry) => entry.name).includes(name)) {
```
Comment (paescuj) [inline packages/extensions-sdk/src/cli/commands/add.ts:104]: Moving the map outside of the `if` condition should make it a bit clearer. We could use a `Set` here too.

```suggestion
		const exitingNames = new Set(extensionOptions.entries.map((entry) => entry.name));

		if (exitingNames.has(name)) {
```

File: packages/extensions/src/node/utils/get-extensions.ts [hunk 3]
```diff
@@ -51,7 +53,17 @@ export async function resolvePackageExtensions(root: string, extensionNames?: st
...
+					.filter((entry) => {
+						const isUnique = loadedEntryNames.includes(entry.name) === false;
+
+						if (isUnique) {
+							loadedEntryNames.push(entry.name);
+						}
+
+						return isUnique;
+					})
+					.map((entry) => pick(entry, 'name', 'type')),
```
Comment (paescuj) [inline packages/extensions/src/node/utils/get-extensions.ts:66]: Similar to my first comment: Let's move `entries` out of this `push` and use a for loop.

**Review by paescuj — CHANGES_REQUESTED** [review]

File: api/src/extensions/lib/get-extensions.ts (hunk 1 above)
Comment (br41nslug) [reply api/src/extensions/lib/get-extensions.ts:22]: Absolutely agree `filter`/`map`/`sort` should never have side effects.

File: packages/extensions-sdk/src/cli/commands/add.ts
Comment (ComfortablyCoding) [reply packages/extensions-sdk/src/cli/commands/add.ts:1]: Uniqueness check added to the build command.

**Review by paescuj — APPROVED** [review]
