### PR TITLE
fix M2O field deletion

### LINKED ISSUE #11473: Image Field added to translations collection cannot be deleted
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have created a collection that has a translations field added to it.
In the translations collection, I have added some text fields as well as a couple of image fields as I would like to have distinct images associated with the localized text fields.
However, I wanted to delete one of the image fields as it was not needed.  When I selected "delete item" from the menu and confirming, I received an error popup.

After the error, the image field I tried to delete from the translations collection still remained in the collection.  When I go to edit the content for the "Lessons" collection, the translations section is still showing the image field I tried to delete, however it seems like it is now just a plain text field and is no longer an image picker. 

### To Reproduce

* Add translations field to collection data model
* Edit collection_translations collection data model and add an image field
* Attempt to delete the added image field from the collection_translations collection data model

### Errors Shown

Popup error message:
`
{
  "errors": [
    {
      "message": "alter table \"Lessons_translations\" drop constraint \"lessons_translations_banner_image_foreign\" - constraint \"lessons_translations_banner_image_foreign\" of relation \"Lessons_translations\" does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
`

I am running this in a docker so I was also able to get the stack trace from the directus app container:

`
directus  | 09:02:42 🚨 error alter table "Lessons_translations" drop constraint "lessons_translations_banner_image_foreign" - constraint "lessons_translations_banner_image_foreign" of relation "Lessons_translations" does not exist 
directus  | error: alter table "Lessons_translations" drop constraint "lessons_translations_banner_image_foreign" - constraint "lessons_translations_banner_image_foreign" of relation "Lessons_translations" does not exist
directus  |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
directus  |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus  |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus  |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
directus  |     at Socket.emit (node:events:390:28)
directus  |     at addChunk (node:internal/streams/readable:315:12)
directus  |     at readableAddChunk (node:internal/streams/readable:289:9)
directus  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
directus  |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
directus  | 09:02:42 ✨ request errored DELETE 500 /fields/Lessons_translations/banner_image 19ms
`

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres 14.1

### What browser are you using?

Chrome

### What operating system are you using?

MacOSX Big Sur

### How are you deploying Directus?

Local Docker using the Directus Docker image

### LINKED ISSUE #11510: M2O Relations can not be deleted
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

You can't delete the M2O relation field of a model anymore.

### To Reproduce

Create a M2O relation field in your model and delete it after creation. 

### Errors Shown

This shows an example from my directus instance. In this case the relation "black_list" can not be deleted from the "players" model.
image

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

PaaS

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #11510, fixes #11473

Note: tested on PostgreSQL, CockroachDB, and MySQL.

## Reported Bug

When we are deleting a M2O field, an error regarding the "constraint doesn't exist" pops up and prevent us from deleting the field:

https://user-images.githubusercontent.com/42867097/153170870-faed557f-7461-4d9b-a610-c14daf00c817.mp4

## Investigation

Seems like the issue stems from #11279 moving up the deletion (drop) of column in the transaction for field deletion here:

https://github.com/directus/directus/blob/c0c412d30b116bd38a2690b62463f775d37db79c/api/src/services/fields.ts#L406-L415

This is because when isM2O case attempts to delete the relationship (constraint) over here:

https://github.com/directus/directus/blob/c0c412d30b116bd38a2690b62463f775d37db79c/api/src/services/fields.ts#L439-L441

The column has been dropped, which includes the constraint/relationship as well. So when relationsService tries to `dropForeign` here:

(it still attempts to drop it because the schema, `existingRelation`, still has the removed relation)

https://github.com/directus/directus/blob/934225a26a9fc05f11e7cdaef91004e34d930843/api/src/services/relations.ts#L294-L307

the error of foreign constraint pops up and prevents the M2O field from being deleted.

## Solution

~~Removed the "relation deletion" logic since it has been deleted when the column gets dropped at the start of the transaction.~~

Previous solution ended up not working for MySQL & MariaDB as they do not auto drop foreign keys & prevent the column deletion.

Opted to move the drop column back down to where it was before #11279.

### CODE REVIEW

**Comment by azrikahar** [comment]
@rijkvanzanten in light of https://github.com/directus/directus/issues/11473#issuecomment-1033989522, when we moved up the column drop _before_ the relationship was removed, it does not work well with MySQL's [`foreign_key_check`](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_foreign_key_checks) which prevents column with existing constraint from being dropped. Both the linked issues were using PostgreSQL so this didn't end up surfacing earlier. 

Would reverting the previous "remove relationship first before removing column" order _but_ making sure it's not nested transactions be possible in regards to #11279's concern?

File: api/src/services/fields.ts [hunk 1]
```diff
@@ -488,6 +478,16 @@ export class FieldsService {
...
+
+			if (
+				this.schema.collections[collection] &&
+				field in this.schema.collections[collection].fields &&
+				this.schema.collections[collection].fields[field].alias === false
+			) {
+				await trx.schema.table(collection, (table) => {
+					table.dropColumn(field);
+				});
+			}
```
Comment (rijkvanzanten) [inline api/src/services/fields.ts:490]: This shouldn't work on CockroachDB. You can't do any DDL operations after a regular SQL query 🤔

Comment (azrikahar) [reply api/src/services/fields.ts:490]: Ah bummer. Somehow it doesn't show any error for me when I tested it on the CockroachDB docker image, but the scenario I tested was probably too rudimentary. Honestly not sure what would the fix be now 🤔

Comment (rijkvanzanten) [reply api/src/services/fields.ts:490]: Maybe adding a manual `dropForeign` before the `dropColumn` to force delete the constraint no matter what before dropping the column? 🤔

**Comment by RayFinney** [comment]
Can someone solve this, we cant use the CMS at all because we cant remove relations on v9.6.0 with Postgres v14.
Constraint gets auto droped and directus tries to drop again which triggers the tx rollback....

**Comment by kosicielPL** [comment]
As @RayFinney said - I also cannot move on with custom extensions and infrastructure development without this issue being merged.

**Review by rijkvanzanten — APPROVED** [review]

File: api/src/services/fields.ts (hunk 1 above)
Comment (rijkvanzanten) [reply api/src/services/fields.ts]: The problem here was that the database constraint was being deleted by dropColumn (but not in every DB), which caused the following `dropForeign` call to fail (which happens in the `relationsService.deleteOne()` call. My fix is to explicitly check if the constraint still exists before attempting to delete it in the relations service, as trying to delete a non-existing key causes a database error 👍🏻

**Comment by skopz356** [comment]
@rijkvanzanten Hi, was this tested against mariadb? I have the newest version (9.7) of directus and the error is still there. 

image

**Comment by liho00** [comment]
> @rijkvanzanten Hi, was this tested against mariadb? I have the newest version (9.7) of directus and the error is still there. Mariadb: latest, Testing with M2O
> 
> image

me too, but im using posgresql...

**Comment by colorao** [comment]
Similar problem here:
Directus 9.6.0 on Docker + MariaDB on Docker
Captura de pantalla 2022-04-27 a las 23 51 26
.

**Comment by rijkvanzanten** [comment]
@colorao Try updating to a later version 👍🏻 This bug was fixed and marked as released under v9.7.0

**Comment by colorao** [comment]
I'll update Docker Image ASAP
Thanks for your fast reply !!
