### PR TITLE
Gatsby: Fix auth email and password

### LINKED ISSUE #10602: gatsby-source-directus fails when authenticating with email & password rather than token
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

`gatsby-source-directus` returns the error:

`gatsby-source-directus : ("auth.email" and "auth.password") must be defined if "auth.token" is not set`

when authenticating with an email and password. The problem lies with line 144 of `gatsby-node.js`: 

```if (hasAuth && !hasToken) error('("auth.email" and "auth.password") must be defined if "auth.token" is not set');```, 

which will always fail without a token. Even if I disable that line, there's an additional failure at line 172: 

```await this.directus.auth.login({ email: this.options?.auth?.email, password: this.options?.auth?.password });```,

as `this.options` isn't yet defined. Changing the line to:

```await this.directus.auth.login({ email: auth?.email, password: auth?.password });```

fixes the issue.

### To Reproduce

Set up a gatsby project using `gatsby-source-directus`. Log in with an email and password rather than a token. Be disappointed.

### Errors Shown

gatsby-source-directus : ("auth.email" and "auth.password") must be defined if "auth.token" is not set

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL

### What browser are you using?

Any

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by joselcvarela**
Fixes #10602

### CODE REVIEW

File: packages/gatsby-source-directus/gatsby-node.js [hunk 1]
```diff
@@ -125,28 +125,28 @@ class Plugin {
...
-
-		if (hasAuth && !hasToken) error('("auth.email" and "auth.password") must be defined if "auth.token" is not set');
+		if (hasAuth) {
+			if (!hasToken && !hasCredentials) error('"auth.token" or ("auth.email" and "auth.password") must be defined');
 
-		if (hasToken && hasCredentials)
-			warning('"auth.token", "auth.email" and "auth.password" are all set, but only "auth.token" will be used');
-
-		if (!hasAuth) warning('no "auth" option were defined. Resources will be fetched with public role');
+			if (!hasToken && (!hasEmail || !hasPassword))
```
Comment (azrikahar) [inline packages/gatsby-source-directus/gatsby-node.js:147]: Not sure am I seeing this correctly, but I believe technically `(!hasEmail || !hasPassword)` is the same as `!(hasEmail && hasPassword)` which ended up being `!hasCredentials`, so now it's the same condition as line 145 and feel slightly odd 🤔

On a side note, this "either token or credentials" case was also one of the things I had to think of when I was doing the 3rd party integrations so it'll definitely be helpful 😄

Comment (joselcvarela) [reply packages/gatsby-source-directus/gatsby-node.js]: Yeah, it makes total sense.
I have removed the second condition.
Although, in Gatsby v4 we have `pluginOptionsSchema` which allows to pass a Joi schema. Then the options will be tested against that schema, so I believe this conditions are not required at all. But just to be sure and since it makes the code more readable I think we should preserve them. 👍
