### PR TITLE
Fix sorting for nested queries with permissions / filters

### LINKED ISSUE #23517: MSSQL Policy that allows non-admin users to assign policies
### Describe the Bug

Want to allow some of our non-admin users to assign certain policies to other users. Setting up full read permissions on the policy works, but as soon as custom item filters are applied to the `directus_policies` READ permissions, the Data Studio throws a 500 error and no polices are shown in the drawer, though it shows the correct number of items in the upper right corner.

### To Reproduce

Create a policy named “App Access”. This policy only has the “Recommended Defaults” permissions:
image

Create a policy named “User Assign Policy”. This policy has the following permissions:
- directus_access: CREATE, READ, UPDATE, DELETE
- directus_policies: READ (with filter {"_and":[{"admin_access":{"_neq":true}}]})
- directus_users: READ, UPDATE
image

These custom permissions didn’t work as intended, the policy drawer shows a count of 16, but no items in the list:
image

get a 500 from [https://<PROJECT_URL>/policies?limit=25&fields[]=icon&fields[]=name&fields[]=app_access&fields[]=admin_access&fields[]=description&fields[]=id&sort[]=name&page=1&filter[_and][0][$FOLLOW(directus_access,policy)][_none][user][_eq]=<TEST_USER_UUID>](https://<PROJECT_URL>/policies?limit=25&fields%5b%5d=icon&fields%5b%5d=name&fields%5b%5d=app_access&fields%5b%5d=admin_access&fields%5b%5d=description&fields%5b%5d=id&sort%5b%5d=name&page=1&filter%5b_and%5d%5b0%5d%5b$FOLLOW(directus_access,policy)%5d%5b_none%5d%5buser%5d%5b_eq%5d=<TEST_USER_UUID>)

Here’s what we have in our logs:

```
2024-08-29T14:26:26.977535488Z [14:26:26] GET /policies?limit=25&fields[]=icon&fields[]=name&fields[]=app_access&fields[]=admin_access&fields[]=description&fields[]=id&sort[]=name&page=1&filter[_and][0][$FOLLOW(directus_access,policy)][_none][user][_eq]=<TEST_USER_UUID> 500 19ms
2024-08-29T14:26:27.345139376Z [14:26:26.687] ERROR: select CASE WHEN [inner].[iolkn_icon] > 0 THEN [directus_policies].[icon] END as [icon], CASE WHEN [inner].[iolkn_name] > 0 THEN [directus_policies].[name] END as [name], CASE WHEN [inner].[iolkn_app_access] > 0 THEN [directus_policies].[app_access] END as [app_access], CASE WHEN [inner].[iolkn_admin_access] > 0 THEN [directus_policies].[admin_access] END as [admin_access], CASE WHEN [inner].[iolkn_description] > 0 THEN [directus_policies].[description] END as [description], CASE WHEN [inner].[iolkn_id] > 0 THEN [directus_policies].[id] END as [id] from [directus_policies] inner join (select top (@p0) [directus_policies].[id], [directus_policies].[name] as [sort_pesvj], COUNT((CASE WHEN ((not [directus_policies].[admin_access] = @p1)) THEN 1 END)) AS [iolkn_icon], COUNT((CASE WHEN ((not [directus_policies].[admin_access] = @p2)) THEN 1 END)) AS [iolkn_name], COUNT((CASE WHEN ((not [directus_policies].[admin_access] = @p3)) THEN 1 END)) AS [iolkn_app_access], COUNT((CASE WHEN ((not [directus_policies].[admin_access] = @p4)) THEN 1 END)) AS [iolkn_admin_access], COUNT((CASE WHEN ((not [directus_policies].[admin_access] = @p5)) THEN 1 END)) AS [iolkn_description], COUNT((CASE WHEN ((not [directus_policies].[admin_access] = @p6)) THEN 1 END)) AS [iolkn_id] from [directus_policies] left join [directus_access] as [sbgff] on [directus_policies].[id] = [sbgff].[policy] where (([directus_policies].[id] not in (select [directus_access].[policy] as [policy] from [directus_access] where [directus_access].[policy] is not null and ([directus_access].[user] = @p7))) and ((not [directus_policies].[admin_access] = @p8))) group by [directus_policies].[id] order by [directus_policies].[name] asc) as [inner] on [directus_policies].[id] = [inner].[id] order by [inner].[sort_pesvj] asc - Column 'directus_[policies.name](http://policies.name/)' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause
```
### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MSSQL

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

Previously we already included the sort records in the `GROUP BY` clause if the sort was multi relation. This worked well on Postgres, since otherwise (without multi relational sort) the sort columns that were selected in the inner query were always directly related (in the same table & row) to the primary key, which is unique, so exactly one row would always be returned from the grouped select, and Postgres is smart enough to identify that. 

However, MSSQL does complain if not all selected columns are part of the `GROUP BY` clause or aggregated over, no matter if they are directly related to the already grouped by unique primary key. So instead of only including the inner sort columns when we have a multi relational sort they always need to be included if present.

Additionally the `GROUP BY` clause can not use aliases established in the `SELECT` clause in some DBs [^1], Postgres just happened to be one where it worked. So instead of relying on the aliases we need to reuse the actual column.

What's changed:

- Always include all `innerSortRecords` in the `GROUP BY` clause
- Use actual column instead of alias in `GROUP BY`

## Potential Risks / Drawbacks

- ?

## Review Notes / Questions

- This initial problem can be reproduced on MSSQL by setting up the following read permission for `directus_policies`

```json
{
    "_and": [
        {
            "admin_access": {
                "_eq": false
            }
        }
    ]
}
```

and then assigning the policy to a test user and query 
`/policies?sort=name&filter[_and][0][$FOLLOW(directus_access,policy)][_none][user][_eq]=$CURRENT_USER`

[^1]: https://stackoverflow.com/a/3841804

---

Fixed #23517

### CODE REVIEW

**Review by licitdev — DISMISSED** [review]
Nice investigation and patch! 🫡 

A potential drawback could be additional overhead on the databases that don't require these columns in the groupBy. A future optimisation perhaps. 🤔

**Comment by hanneskuettner** [comment]
> A potential drawback could be additional overhead on the databases that don't require these columns in the groupBy. A future optimisation perhaps. 🤔

Very true! It is something that could potentially moved into a dialect helper, tho this feels very specific. `addGroupByFieldForSort`? 😄

**Comment by hanneskuettner** [comment]
Let's turn this into a DB specific helper. Than we can reuse aliases where needed and only include the sort fields that need including for the vendors that need it 👍

File: api/src/database/helpers/schema/types.ts [hunk 1]
```diff
@@ -155,4 +160,12 @@ export abstract class SchemaHelper extends DatabaseHelper {
 	preprocessBindings(queryParams: Sql): Sql {
 		return queryParams;
 	}
+
+	addInnerSortFieldsToGroupBy(
+		_groupByFields: (string | Knex.Raw)[],
```
Comment (hanneskuettner) [inline api/src/database/helpers/schema/types.ts:165]: I did not want to put the underscore there, just because then it shows up in the method usage descriptions. Fine to keep it like this, tho

Comment (licitdev) [reply api/src/database/helpers/schema/types.ts:165]: Updated it for consistency with similar cases and also to satisfy the linter. Would you prefer the parameters wrapped in an `options` field instead?

Comment (hanneskuettner) [reply api/src/database/helpers/schema/types.ts:165]: Don't have a preference. If you think `options` is more appropriate, let's go for options

Comment (licitdev) [reply api/src/database/helpers/schema/types.ts:165]: As discussed over chat, I'm resolving this conversation for consistency with other similar occurrences.

**Review by licitdev — APPROVED** [review]
LGTM~ Loved the details on the db specifics. Thanks @hanneskuettner
