### PR TITLE
Fix handling of nested arrays in snapshot diffing

### LINKED ISSUE #10167: Updating M2A relationship through snapshot not working
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When applying a snapshot that contains an update on the field one_allowed_collections in a M2A relationship, the update doesn't persist, although Directus detect some kind of update.

directus_update

Expected behavior:

`update.yaml` is adding `entity_3` and `entity_4` as part of the `one_allowed_collections` in a M2A relationship for `entity_1_translations`.

If I go to the CMS UI after applying the snapshot, the entities `entity_3` and `entity_4` should be part of the relationship.
expected

Current behavior:
`update.yaml` is not adding `entity_3` and `entity_4` as part of the `one_allowed_collections` in a M2A relationship for `entity_1_translations`.

If I go to the CMS UI after applying the snapshot, the entities `entity_3` and `entity_4` are not part of the relationship.
wrong

Snapshots:
[snapshots.zip](https://github.com/directus/directus/files/7627508/snapshots.zip)

### To Reproduce

1. Apply snapshot create.yaml
2. Apply snapshot update.yaml

### Errors Shown

_No response_

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

v16.13.9

### What database are you using?

Postgres 13-alpine

### What browser are you using?

Chrome

### What operating system are you using?

Directus is running on linux (docker image). Browser is running over macOS.

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Fixes #10167

### CODE REVIEW

File: api/src/cli/commands/schema/apply.ts [hunk 1]
```diff
@@ -109,9 +113,18 @@ export async function apply(snapshotPath: string, options?: { yes: boolean }): P
...
+						message += `\n  - ${chalk.green('Create')} ${collection}.${field}`;
+					} else if (diff[0]?.kind === 'A') {
+						message += `\n  - ${chalk.blue('Update')} ${collection}.${field}`;
+					} else {
+						continue;
+					}
+
+					// Related collection doesn't exist for m2a relationship types
+					if (related_collection) {
+						message += `-> ${related_collection}`;
```
Comment (nickrum) [inline api/src/cli/commands/schema/apply.ts:127]: @rijkvanzanten Small nitpick: I think you're missing a space here right before the arrow.
