### PR TITLE
Fix cache skipping for getSchema

### LINKED ISSUE #24961: Snapshot apply failure on production
### Describe the Bug

Hey!

Using D `11.5.1` Im trying to apply a snapshot on self-hosted production with quite a few changes:
```
Collections:
  - Update alert_service_request
    - Set sort to 10
  - Delete business_locations
  - Update directus_sync_id_map
    - Set sort to 16
  - Update helpdesk_request
    - Set sort to 9
  - Update invoices
    - Set sort to 11
  - Update junction_directus_users_directus_files
    - Set sort to 15
  - Update logs
    - Set sort to 12
  - Update orders
    - Set sort to 6
  - Update promotion_links
    - Set sort to 8
  - Update settings
    - Set sort to 13
  - Update settings_invoice
    - Set sort to 14
  - Update settings_pages
    - Set sort to 17
  - Update tickets
    - Set sort to 7
  - Update user_registration_data
    - Set sort to 18
  - Create business_addresses

Fields:
  - Update businesses.status
    - Set default_value to active
  - Delete businesses.street_name
  - Delete businesses.street_number
  - Delete businesses.city
  - Delete businesses.zip_code
? The following changes will be applied:

Collections:
  - Update alert_service_request
    - Set sort to 10
  - Delete business_locations
  - Update directus_sync_id_map
    - Set sort to 16
  - Update helpdesk_request
    - Set sort to 9
  - Update invoices
    - Set sort to 11
  - Update junction_directus_users_directus_files
    - Set sort to 15
  - Update logs
    - Set sort to 12
  - Update orders
    - Set sort to 6
  - Update promotion_links
    - Set sort to 8
  - Update settings
    - Set sort to 13
  - Update settings_invoice
    - Set sort to 14
  - Update settings_pages
    - Set sort to 17
  - Update tickets
    - Set sort to 7
  - Update user_registration_data
    - Set sort to 18
  - Create business_addresses

Fields:
  - Update businesses.status
    - Set default_value to active
  - Delete businesses.street_name
  - Delete businesses.street_number
  - Delete businesses.city
  - Delete businesses.zip_code
✔ The following changes will be applied:

Collections:
  - Update alert_service_request
    - Set sort to 10
  - Delete business_locations
  - Update directus_sync_id_map
    - Set sort to 16
  - Update helpdesk_request
    - Set sort to 9
  - Update invoices
    - Set sort to 11
  - Update junction_directus_users_directus_files
    - Set sort to 15
  - Update logs
    - Set sort to 12
  - Update orders
    - Set sort to 6
  - Update promotion_links
    - Set sort to 8
  - Update settings
    - Set sort to 13
  - Update settings_invoice
    - Set sort to 14
  - Update settings_pages
    - Set sort to 17
  - Update tickets
    - Set sort to 7
  - Update user_registration_data
    - Set sort to 18
  - Create business_addresses

Fields:
  - Update businesses.status
    - Set default_value to active
  - Delete businesses.street_name
  - Delete businesses.street_number
  - Delete businesses.city
  - Delete businesses.zip_code
  - Delete businesses.phone
  - Delete businesses.email
  - Delete businesses.locations
  - Update directus_users.promotion_link
    - Add options.enableLink and set it to true
  - Update directus_users.business
    - Set options to [object Object]
  - Update orders.helpdesk_request
    - Set sort to 10
  - Update orders.stripe_payment_intent
    - Set sort to 12
  - Update orders.stripe_payment_method
    - Set sort to 13
  - Update orders.user
    - Set sort to 14
  - Update orders.alert_service_request
    - Set sort to 11
  - Delete tickets.business_location
  - Update user_registration_data.user
    - Set options to [object Object]
  - Create business_addresses.id
  - Create business_addresses.status
  - Create business_addresses.sort
  - Create business_addresses.user_created
  - Create business_addresses.date_created
  - Create business_addresses.user_updated
  - Create business_addresses.date_updated
  - Create business_addresses.street_name
  - Create business_addresses.street_number
  - Create business_addresses.zip_code
  - Create business_addresses.city
  - Create business_addresses.country_code
  - Create business_addresses.phone
  - Create business_addresses.email
  - Create business_addresses.business
  - Create business_addresses.address_type
  - Create business_addresses.archived_at
  - Create businesses.addresses
  - Create orders.user_json
  - Create tickets.business_address
  - Create user_registration_data.business_name

Relations:
  - Delete tickets.business_location → business_locations
  - Create business_addresses.user_updated → directus_users
  - Create business_addresses.user_created → directus_users
  - Create business_addresses.business → businesses
  - Create tickets.business_address → business_addresses
```

I then press `y` and I get the following error:
```
Would you like to continue? Yes
[12:27:01.296] ERROR: Failed to delete field "tickets.business_location"
[12:27:01.297] ERROR: alter table "tickets" drop constraint "tickets_business_location_foreign" - constraint "tickets_business_location_foreign" of relation "tickets" does not exist
    err: {
      "type": "DatabaseError",
      "message": "alter table \"tickets\" drop constraint \"tickets_business_location_foreign\" - constraint \"tickets_business_location_foreign\" of relation \"tickets\" does not exist",
      "stack":
          error: alter table "tickets" drop constraint "tickets_business_location_foreign" - constraint "tickets_business_location_foreign" of relation "tickets" does not exist
              at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:283:98)
              at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:122:29)
              at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:35:38)
              at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:518:28)
              at addChunk (node:internal/streams/readable:561:12)
              at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
              at Readable.push (node:internal/streams/readable:392:5)
              at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
              at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
      "length": 153,
      "name": "error",
      "severity": "ERROR",
      "code": "42704",
      "file": "tablecmds.c",
      "line": "12235",
      "routine": "ATExecDropConstraint"
    }
exit status 1
```
On the tickets table I see the constraint though!:
Image

Now my production deployment it broken, how can I fix this!?

### To Reproduce

See comment

### Directus Version

v11.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgreSQL 16.8

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- Now skips all caches when `bypassCache` is enabled for getSchema()

## Potential Risks / Drawbacks

- none

## Review Notes / Questions

- Thanks to @joselcvarela for putting so much research into this already, making it quite easy to resolve. ❤️ 

---

Fixes #24961, Closes NOW-839

### CODE REVIEW

File: api/src/services/relations.ts [hunk 1]
```diff
@@ -112,7 +112,7 @@ export class RelationsService {
 			return metaRow.many_collection === collection;
 		});
 
-		const schemaRows = await this.foreignKeys(collection);
+		const schemaRows = bypassCache ? await this.schemaInspector.foreignKeys() : await this.foreignKeys(collection);
```
Comment (Nitwel) [inline api/src/services/relations.ts:115]:
```suggestion
		const schemaRows = bypassCache ? await this.schemaInspector.foreignKeys().filter((row) => row.table === collection) : await this.foreignKeys(collection);
```

**Review by Nitwel — COMMENTED** [review]
LGTM, feel free to merge!

File: api/src/services/relations.ts (hunk 1 above)
Comment (licitdev) [reply api/src/services/relations.ts:115]: This would also be inaccurate, as there should be no filtering if `collection` is not defined. Here's [the PR](https://github.com/directus/directus/pull/19391) which changed this behaviour.

**Review by licitdev — APPROVED** [review]
