### PR TITLE
Fix `applyOptionsData` errors not appearing in the flow log

### LINKED ISSUE #22191: Flows failing
### Describe the Bug

I upgraded recently and the webhooks where converted to flows. However you can now use templates in the headers and it didn't escape the values which caused it to fail. The major problem I have is not this not the escaping, but the failing as it isn't logged in the interface. I had to go to logs where Detritus was running.

### To Reproduce

Add incomplete value to a header like `...{{...` in a webhook and then trigger it. No logs are generated in the ui, but the it fails in the background.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Any errors thrown by `applyOptionsData` during the flow process are now shown in the flow logs

## Potential Risks / Drawbacks

- Should be none

## Review Notes / Questions

-N/A

---

Fixes #22191

### CODE REVIEW

File: api/src/flows.ts [hunk 1]
```diff
@@ -421,9 +421,11 @@ class FlowManager {
 
 		const handler = this.operations.get(operation.type)!;
 
-		const options = applyOptionsData(operation.options, keyedData);
+		let options = null;
```
Comment (ComfortablyCoding) [inline api/src/flows.ts:424]: Any opinion on if we should default to `null` or `operation.options`? I can see arguments for both.

Comment (licitdev) [inline api/src/flows.ts:424]: Defaulting to the options value would be helpful for debugging via logs.

```suggestion
		let options = operation.options;
```

File: api/src/flows.ts [hunk 2]
```diff
@@ -421,9 +421,11 @@ class FlowManager {
...
 
 		try {
+			options = applyOptionsData(operation.options, keyedData);
```
Comment (licitdev) [inline api/src/flows.ts:427]: If we proceed with the defaulting to options, this change could be added to batch.
```suggestion
			options = applyOptionsData(options, keyedData);
```

**Review by licitdev — APPROVED** [review]

File: api/src/flows.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply api/src/flows.ts:424]: Agreed and good enough for me
