### PR TITLE
fix(api): dont allow setting nullable for primary key while updating a field

### LINKED ISSUE #20361: Setting `Allow NULL value` on primary key, drops auto increment (default value)
### Describe the Bug

When you edit the id field on a datamodel and select the nullable value and save it would prompt you with an error. 
```json
{
  "errors": [
    {
      "message": "alter table \"newpagecategories\" alter column \"id\" drop not null - column \"id\" is in a primary key",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stack": "error: alter table \"newpagecategories\" alter column \"id\" drop not null - column \"id\" is in a primary key\n    at Parser.parseErrorMessage (/Users/~/projects/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/Users/~/projects/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/Users/~/projects/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/Users/~/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:335:12)\n    at readableAddChunk (node:internal/streams/readable:308:9)\n    at Readable.push (node:internal/streams/readable:245:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
      }
    }
  ]
}
```
But after creating a new item for that collection it would say `ID: Value is required`. The default value already has been deleted so the auto increment doesn't work anymore on the ID.

### To Reproduce

1. Have a model in my case I use something simple with just one input.
2. Create a few items normally.
3. Then go to the model and edit field on the id.
image
4. check nullable, save and you will get this error.
image
4a. You can check again and see that nullable is unchecked now.
5. Go to your collection. 
6. Create a new item and it will prompt you the error `ID: Value is required`. 
image

You will see that the default is now removed from the schema.

https://github.com/directus/directus/assets/14160793/8714ae60-27c7-404d-a8ca-0567d8f242b2

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by mahendraHegde**
## Scope

What's changed:

- Validate `is_nullable` and throw invalid payload error when the column is PK
- Use transaction to update a field
- Disable allow nullable in UI for PK

## Potential Risks / Drawbacks
NA

## Review Notes / Questions

- Using transaction for item update is optional, but i feel we should to avoid these kind of inconsistencies, in this specific case, knex was generating a series of queries and it was failing while setting nullable to PK, but before that default(auto increment) was removed, since it was not a transaction, statements(remove default in this case) was not rolled back.

---

Fixes #20361

### CODE REVIEW

File: api/src/services/fields.ts [hunk 1]
```diff
@@ -412,15 +412,21 @@ export class FieldsService {
...
 				if (!isEqual(columnToCompare, hookAdjustedField.schema)) {
 					try {
-						await this.knex.schema.alterTable(collection, (table) => {
-							if (!hookAdjustedField.schema) return;
-							this.addColumnToTable(table, field, existingColumn);
+						await this.knex.transaction(async (trx) => {
+							await trx.schema.alterTable(collection, async (table) => {
+								if (!hookAdjustedField.schema) return;
+								this.addColumnToTable(table, field, existingColumn);
+							});
```
Comment (mahendraHegde) [inline api/src/services/fields.ts:429]: Using transaction for item update is optional, but i feel we should to avoid these kind of inconsistencies, in this specific case, knex was generating a series of DDL queries and it was failing while setting nullable to PK, but before that default(auto increment) was removed, since it was not a transaction, statements(remove default in this case) was not rolled back.

**Review by mahendraHegde — COMMENTED** [review]
@br41nslug  this is ready to be reviewed.

File: .changeset/metal-walls-accept.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+'@directus/api': patch
+'@directus/app': patch
+---
+
+Dont allow setting nullable for primary key
```
Comment (paescuj) [inline .changeset/metal-walls-accept.md:6]:
```suggestion
Prevented changing primary keys to nullable
```

**Review by paescuj — APPROVED** [review]
Thank you @mahendraHegde ❤️
