### PR TITLE
Keep SidebarOpen state in local storage

### LINKED ISSUE #15860: Sidebar does not keep the state after refreshing the page
### Describe the Bug

Sidebar does not keep the state after refreshing the page.

Maybe it's not a bug, but could be improved :)

#### For `window.width` >= 1430 (sidebar is open by default)
1. Open the page
2. Close the sidebar
3. Refresh the page

Current behavior: Sidebar is open.
Expected behavior: Sidebar is closed.

#### For `window.width` < 1430 (sidebar is closed by default)
1. Open the page
2. Open the sidebar
3. Refresh the page

Current behavior: Sidebar is closed.
Expected behavior: Sidebar is open.

### Errors Shown

_No response_

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by goth-pl**
## Description

`sidebarOpen` state is now being saved in local storage, so sidebar keeps the state (opened / closed) after refreshing the page.

Added tests for `useLocalStorage`.

Fixes #15860.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [x] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

### CODE REVIEW

**Review by molszanski — APPROVED** [review]
🔥

**Review by patrycjabrzeskot — APPROVED** [review]
:clap:

**Comment by benhaynes** [comment]
Yaasss... big one, thank you! 🙌

File: app/src/stores/app.ts [hunk 1]
```diff
@@ -13,4 +16,9 @@ export const useAppStore = defineStore({
 		accessTokenExpiry: 0,
 		basemap: 'OpenStreetMap',
 	}),
+	actions: {
+		setSidebarOpen(isOpen: boolean) {
+			this.sidebarOpen = sidebarOpenObject.setValue(isOpen);
+		},
+	},
```
Comment (nickrum) [inline app/src/stores/app.ts:23]: This might be a potential footgun as `sidebarOpen` would still be modifiable through `useAppStore().sidebarOpen`.

File: app/src/views/private/components/sidebar-detail.vue [hunk 2]
```diff
@@ -59,6 +59,11 @@ export default defineComponent({
 		const { sidebarOpen } = toRefs(appStore);
 		return { active, toggle, sidebarOpen };
 	},
+	methods: {
+		closeSidebar() {
+			useAppStore().setSidebarOpen(false);
+		},
+	},
```
Comment (nickrum) [inline app/src/views/private/components/sidebar-detail.vue:66]: We shouldn't mix Vue Composition API and Options API.

**Review by nickrum — CHANGES_REQUESTED** [review]
I'm wondering if we should rather convert `appStore` to pinia's Composition API and use `useLocalStorage` directly inside the store.

File: app/src/stores/app.ts (hunk 1 above)
Comment (molszanski) [reply app/src/stores/app.ts:23]: How to avoid it?

Comment (nickrum) [reply app/src/stores/app.ts:23]: One option would be to convert `appStore` to a [setup store](https://pinia.vuejs.org/cookbook/composables.html#setup-stores) as mentioned above.

Comment (goth-pl) [reply app/src/stores/app.ts]: Thanks for the tip 🙌 I've made some changes to avoid this problem.

File: app/src/views/private/components/sidebar-detail.vue (hunk 2 above)
Comment (goth-pl) [reply app/src/views/private/components/sidebar-detail.vue]: Good point! Anyway, the method has been removed as it's not needed anymore :)

**Review by molszanski — APPROVED** [review]

**Review by nickrum — CHANGES_REQUESTED** [review]
Do we still need the `LocalStorageObject` now that it is only used inside `useLocalStorage`?

**Comment by goth-pl** [comment]
@nickrum I've moved logic back to `useLocalStorage` and removed `LocalStorageObject`.

**Review by molszanski — APPROVED** [review]

**Review by nickrum — APPROVED** [review]

**Comment by molszanski** [comment]
🔥

File: app/src/composables/use-local-storage.ts [hunk 3]
```diff
@@ -1,38 +1,42 @@
...
+		if (!rawExistingValue) return defaultValue;
 
-	function getExistingValue() {
-		let rawExistingValue;
 		try {
-			rawExistingValue = localStorage.getItem(internalKey);
-		} catch (err: any) {
-			//
-		}
+			return JSON.parse(rawExistingValue);
```
Comment (br41nslug) [inline app/src/composables/use-local-storage.ts:15]: A small change but i'd prefer we use our `parseJSON` utility function here.

**Review by br41nslug — CHANGES_REQUESTED** [review]
Looking good, if you could make that small requested change it'll be ready to be merged 😄

**Review by br41nslug — APPROVED** [review]

File: app/src/composables/use-local-storage.ts [hunk 4]
```diff
@@ -1,38 +1,43 @@
...
-		try {
-			if (data.value == null) {
-				localStorage.removeItem(internalKey);
-			} else {
-				localStorage.setItem(internalKey, JSON.stringify(data.value));
-			}
-		} catch (err: any) {
-			//
+		if (data.value == null) {
+			localStorageObject.clear();
```
Comment (paescuj) [inline app/src/composables/use-local-storage.ts:38]: Hey @goth-pl, thanks for this pull request!

Sorry to bother you, but just stumbled upon this while working on other stuff...
Shouldn't this be `localStorage.removeItem(internalKey)` as it used to be before? Am I missing something here?
Probably, the test needs to be updated as well.

Thanks again!

Comment (azrikahar) [reply app/src/composables/use-local-storage.ts:38]: Looks like @paescuj is right on the money here, as this line currently errors out due to `localStorageObject` not being declared anywhere.

I believe it was missed during the removal of `localStorageObject` in this commit: https://github.com/directus/directus/pull/15861/commits/d7715afabe1d3adbf8361114f770737044fecd56.

> Shouldn't this be `localStorage.removeItem(internalKey)` as it used to be before?

Seems like originally `localStorageObject` has a method called `clear()` which then actually calls `localStorage.removeItem()` so it was technically still correct: 
https://github.com/directus/directus/blob/5c8ba4b8eb7506ba6d714912834008304ad0124d/app/src/utils/local-storage-object.ts#L40-L42

Definitely confused me as well 😄 

@goth-pl Let's make sure to use `localStorage.removeItem(internalKey)` for the follow up fix 👍 (or do feel free to let us know if you don't currently have the bandwidth for this)

Comment (azrikahar) [reply app/src/composables/use-local-storage.ts:38]: Just recalled about this earlier, so I've followed this up with a PR in #16581 👍

Comment (paescuj) [reply app/src/composables/use-local-storage.ts:38]: > Just recalled about this earlier, so I've followed this up with a PR in #16581 👍

Nice! Exactly what I was thinking of 🥇

Comment (goth-pl) [reply app/src/composables/use-local-storage.ts:38]: @paescuj @azrikahar OMG! You're right! I must have missed it while cleaning up. Sorry, thanks for catching and fixing it ❤️
