### PR TITLE
Fix `countAll` generating an incorrect query

### LINKED ISSUE #26768: [API] GraphQL `_aggregate` `countAll` not working/applied
### Describe the Bug

When using the GraphQL API to retrieve the total count aka `countAll` of a collection, the query leads to the database statement `SELECT * FROM "<table>" LIMIT $1` where $1 equals `100` by default, instead of `SELECT COUNT(*) FROM "<table>"`.

The `countAll` operation is described [here](https://directus.io/docs/guides/connect/query-parameters#aggregate).

I think the actual error happens at this point: https://github.com/directus/directus/blob/282a6de31f5d3ea5f20fe2519ee747d21e05dfb5/api/src/database/run-ast/lib/apply-query/aggregate.ts#L4-L17

The function `applyAggregate` is called with the parameter `aggregate` with the value `{countAll: []}`.

The iteration at beginning at https://github.com/directus/directus/blob/282a6de31f5d3ea5f20fe2519ee747d21e05dfb5/api/src/database/run-ast/lib/apply-query/aggregate.ts#L11 assignes `countAll` to the variable `operation` and `[]` to the variable `fields`.

Since `fields` is an empty array the loop at https://github.com/directus/directus/blob/282a6de31f5d3ea5f20fe2519ee747d21e05dfb5/api/src/database/run-ast/lib/apply-query/aggregate.ts#L14 does not perform a single iteration and the condition at https://github.com/directus/directus/blob/282a6de31f5d3ea5f20fe2519ee747d21e05dfb5/api/src/database/run-ast/lib/apply-query/aggregate.ts#L15 will never be met.

The issue does not appear in the tests because the test case is executed with a dataset that cannot be constructed using the GraphQL API: https://github.com/directus/directus/blob/282a6de31f5d3ea5f20fe2519ee747d21e05dfb5/api/src/database/run-ast/lib/apply-query/aggregate.test.ts#L109-127

My expectation is that the operation `countAll` is checked before the `fields` are iterated on.

If I am not wrong, should this patch fix the issue: [aggregate.patch](https://github.com/user-attachments/files/25607033/aggregate.patch)

### To Reproduce

1. Configure Directus to log any database query, for example using the environment `LOG_LEVEL=trace` or the Database, PostgreSQL in this example, using the option `-c log_statement=all`
2. Create a collection called `posts`
3. Create at least two items in the created collection
4. Perform the query `query { posts_aggregated { countAll } }`
5. Query Log will show `select * from "posts" limit $1`

The response will look like:
```json
{
  "data": {
    "posts_aggregated": [
      {
        "countAll": null
      },
      {
        "countAll": null
      }
    ]
  }
}
```
instead of
```json
{
  "data": {
    "posts_aggregated": [
      {
        "countAll": 2
      }
    ]
  }
}
```

### Directus Version

v11.15.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres

### PR DESCRIPTION
**Pull request by tysoncung**
## Description

Fixes #26768

When `countAll` is invoked via the GraphQL API (e.g. `{ posts_aggregated { countAll } }`), the aggregate parameter is `{ countAll: [] }` — an empty fields array. The current code checks for `countAll` inside the `for (const field of fields)` loop, which never executes when fields is empty. This causes the query to fall through to `SELECT * FROM table LIMIT 100` instead of generating `SELECT COUNT(*) AS countAll`.

## Changes

- Moved the `countAll` check **before** the fields iteration so it executes regardless of whether fields are provided
- Added a test case for `countAll` with an empty fields array (the GraphQL case)

## How it works

Before:
```
for (const [operation, fields] of Object.entries(aggregate)) {
    for (const field of fields) {     // fields = [] → never executes
        if (operation === 'countAll')  // never reached
```

After:
```
for (const [operation, fields] of Object.entries(aggregate)) {
    if (operation === 'countAll') {    // checked before field iteration
        dbQuery.count('*', { as: 'countAll' });
        continue;
    }
    for (const field of fields) {      // only iterates for other operations
```

### CODE REVIEW

File: api/src/database/run-ast/lib/apply-query/aggregate.ts [hunk 1]
```diff
@@ -11,12 +11,12 @@ export function applyAggregate(
...
 
-		for (const field of fields) {
-			if (operation === 'countAll') {
-				dbQuery.count('*', { as: 'countAll' });
-				continue;
-			}
+		if (operation === 'countAll') {
+			dbQuery.count('*', { as: 'countAll' });
+			continue;
+		}
```
Comment (MaSpeng) [inline api/src/database/run-ast/lib/apply-query/aggregate.ts:17]: @tysoncung how about moving this section before line 12 to avoid the bug reocurring when fields might not be an array?

**Comment by MaSpeng** [comment]
Attention this PR is a duplicate or is duplicated by https://github.com/directus/directus/pull/26781 and https://github.com/directus/directus/pull/26778.

**Comment by tysoncung** [comment]
Good call @MaSpeng - moved the countAll check before the fields guard so it handles null/undefined fields too. Thanks for the review!

**Comment by tysoncung** [comment]
CI needs the 'No Changeset' label - this is a small bug fix with no public API changes. Could a maintainer add it? Thanks!

**Comment by tysoncung** [comment]
Good point @MaSpeng — moved the guard before the countAll check so it catches missing fields early. Thanks for the suggestion!

**Comment by MaSpeng** [comment]
@tysoncung I fear this pull request is not looked at because its pipeline is failing. Could you please add the missing changeset file?

Also it seems that it must be rebased as well.

File: api/src/database/run-ast/lib/apply-query/aggregate.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply api/src/database/run-ast/lib/apply-query/aggregate.ts:17]: It should be fine to leave it here. Per to the type definitions, it should be an array. If it isn’t, then something is wrong and we shouldn’t process it.

File: api/src/database/run-ast/lib/apply-query/aggregate.ts [hunk 2]
```diff
@@ -9,14 +9,14 @@ export function applyAggregate(
 	hasJoins: boolean,
 ): void {
 	for (const [operation, fields] of Object.entries(aggregate)) {
-		if (!fields) continue;
+		if (!fields && operation !== 'countAll') continue;
```
Comment (ComfortablyCoding) [inline api/src/database/run-ast/lib/apply-query/aggregate.ts]: Let's remove this change, as mentioned in https://github.com/directus/directus/pull/26774/changes#r2890191775 we should not process it if it is not defined
 ```suggestion
		if (!fields) continue;
```

**Comment by ComfortablyCoding** [comment]
> @tysoncung I fear this pull request is not looked at because its pipeline is failing. Could you please add the missing changeset file?
> 
> Also it seems that it must be rebased as well.

In this case the pipeline was erroring on a missing changeset, not a blocker for review. I have since added one so we are good on that front. I have resolved any conflicts as well 👍 

Review was pending some other priorities.

**Comment by ComfortablyCoding** [comment]
> CI needs the 'No Changeset' label - this is a small bug fix with no public API changes. Could a maintainer add it? Thanks!

Although it is not a Public API interface change, it is a change in functionality which requires a changeset. I have added one.

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀 , thanks @tysoncung and congratulations on your first contribution to directus! 🥳

**Review by AlexGaillard — APPROVED** [review]

**Comment by AlexGaillard** [comment]
TY @tysoncung and congrats 🎉
