### PR TITLE
Translation string performance

### LINKED ISSUE #15501: Translation string performance
### Describe the Bug

In projects with many translation strings, there's a UI blocking delay every time the Directus app loads in the browser (logging in, opening a Collection Item in a new tab, etc. The delay is caused when parsing the strings, not the network API request to retrieve the translation string values. 

I think the translation strings should be aggressively cached, and not re-requested or parsed every time Directus is opened a tab/window. 

 

### To Reproduce

1. Create many translation strings (like localized values for a large checkbox tree, for example)
2. Observe the impact on performance waterfall in browser dev tools

### Errors Shown

None

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17

### What database are you using?

MySQL

### What browser are you using?

Chrome, Safari on macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by br41nslug**
Rework of https://github.com/directus/directus/pull/17094

This PR adds the following:
- A migration to update the current `translation_strings` content to a new core table.
- Replaced the hydration of translation strings to only fetch the current language.
- Updated the translation strings setting page to use the new structure.

### Todo

- [x] Docs

Fixes https://github.com/directus/directus/issues/15501
Fixes ENG-193

### CODE REVIEW

**Review by nickrum — COMMENTED** [review]
Since all of our other internal collections and services are named using a single word, do we also want to call this `directus_translations`/`TranslationService` or is that too vague?

File: api/src/controllers/translations.ts [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+	const result = await service.readByQuery(req.sanitizedQuery);
+
+	res.locals['payload'] = {
+		data: result,
+	};
+
+	return next();
+});
+
+router.search('/', validateBatch('read'), readHandler, respond);
```
Comment (paescuj) [inline api/src/controllers/translations.ts:26]: Do we need this?

**Review by paescuj — APPROVED** [review]
Great work!

File: api/src/database/migrations/20230524A-migrate-translation-strings.ts [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+		const parsedTranslationStrings =
+			typeof data.translation_strings === 'string' ? JSON.parse(data.translation_strings) : data.translation_strings;
+
+		const newTranslationStrings = transformStringsNewFormat(parsedTranslationStrings);
+
+		for (const item of newTranslationStrings) {
+			await knex('directus_translations').insert(item);
+		}
+	}
+}
```
Comment (licitdev) [inline api/src/database/migrations/20230524A-migrate-translation-strings.ts:57]:
```suggestion
	}

	await knex.schema.alterTable('directus_settings', (table) => {
		table.dropColumn('translation_strings');
	});
}
```

File: api/src/database/migrations/20230524A-migrate-translation-strings.ts [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+export async function down(knex: Knex): Promise<void> {
+	const data = await knex.select('language', 'key', 'value').from('directus_translations');
+	const settingsId = await knex.select('id').from('directus_settings').first();
+
```
Comment (licitdev) [inline api/src/database/migrations/20230524A-migrate-translation-strings.ts:62]:
```suggestion

	await knex.schema.alterTable('directus_settings', (table) => {
		table.json('translation_strings');
	});

```

**Review by licitdev — COMMENTED** [review]
Should we drop the `translation_strings` column in `directus_settings` within this migration or will it be done in a future release?

**Comment by paescuj** [comment]
> Should we drop the `translation_strings` column in `directus_settings` within this migration or will it be done in a future release?

Yes 👍 Admins are supposed to create a backup before the upgrade. Maybe we can add a notice in the release notes.

File: api/src/controllers/translations.ts (hunk 1 above)
Comment (paescuj) [reply api/src/controllers/translations.ts:26]: I kind of thought that we've removed that method from all controllers. But that's not the case, so we might as well keep it here 👍

**Review by nickrum — CHANGES_REQUESTED** [review]
Other than a few little nitpicks, this works like a charm 👍

File: api/src/controllers/translations.ts [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+		}
+
+		throw error;
+	}
+
+	return next();
+});
+
+router.post('/:key', upsertHandler, respond);
+router.patch('/:key', upsertHandler, respond);
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply api/src/controllers/translations.ts:72]: I like that idea 🤔 However i dont think we are using PUT yet right? perhaps we should introduce that with a broader upsert for items collections feature like https://github.com/directus/directus/discussions/5706 🤔

[the remark this answers is not in the document]
Comment (nickrum) [reply api/src/controllers/translations.ts:72]: Not as far as I know, no! Adding upsertion to the API in general is definitely a bigger task that needs a lot more planning (as @rijkvanzanten mentioned in the discussion you linked, it is not as easy as always using `PUT` for upserts because it indicates _replace_ instead of _update_). I'm just a little worried that the translations controller will be the only outlier that works differently once we add upsertion to all the other controllers.

[the remark this answers is not in the document]
Comment (licitdev) [reply api/src/controllers/translations.ts:72]: translations is already an outlier as the `key` here isn't the primary key. 👀

File: app/src/utils/get-current-language.ts
Comment (azrikahar) [inline app/src/utils/get-current-language.ts:1]: Should we make this account for project default language as well? As it coincidentally reminded me of this piece of code:

https://github.com/directus/directus/blob/e5bf8a76f8368157bd10d609ab0b4417016ece2a/app/src/hydrate.ts#L72-L74

in which case this function can replace also these 3 lines of code if I'm interpreting it correctly.

File: api/src/controllers/translations.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (rijkvanzanten) [reply api/src/controllers/translations.ts:72]: `/translations` should be the same as any other endpoint 👍🏻

File: app/src/stores/settings.ts [hunk 5]
```diff
@@ -17,7 +17,33 @@ export const useSettingsStore = defineStore({
...
+						'storage_asset_presets',
+						'custom_css',
+						'storage_default_folder',
+						'basemaps',
+						'mapbox_key',
+						'module_bar',
+						'project_descriptor',
+						'default_language',
+						'custom_aspect_ratios',
+						'image_editor',
```
Comment (azrikahar) [inline app/src/stores/settings.ts:42]:
```suggestion
```

I believe this is only an alias field and doesn't need to be fetched 👍

https://github.com/directus/directus/blob/e5bf8a76f8368157bd10d609ab0b4417016ece2a/api/src/database/system-data/fields/settings.yaml#L383-L391

File: app/src/modules/settings/routes/translation-strings/translation-strings-drawer.vue [hunk 6]
```diff
@@ -146,9 +145,8 @@ const fields = computed<DeepPartial<Field>[]>(() => {
 							name: '$t:translation',
 							type: 'string',
 							meta: {
-								interface: 'input-multiline',
-								width: 'full',
-								required: true,
+								interface: 'input',
+								width: 'half',
```
Comment (azrikahar) [inline app/src/modules/settings/routes/translation-strings/translation-strings-drawer.vue:149]: I believe this might be from an accidental merge conflict, but we need to revert `interface` and `width` changes here back to `input-multiline` and `full` respectively as they were a change by #18135 in https://github.com/directus/directus/pull/18135/files#diff-77e105fb6f04788401f31f2f7475400fee26bc7ed62e8e7b40e762af5613faf0R149-R150.

File: app/src/modules/settings/routes/translation-strings/collection.vue [hunk 7]
```diff
@@ -29,83 +37,168 @@
...
+									show-first-last
+									:model-value="page"
+									@update:model-value="toPage"
+								/>
+							</div>
+							<div v-if="loading === false" class="per-page">
+								<span>{{ t('per_page') }}</span>
+								<v-select
+									:model-value="`${limit}`"
+									:items="['25', '50', '100', '250', '500', ' 1000']"
```
Comment (azrikahar) [inline app/src/modules/settings/routes/translation-strings/collection.vue:78]: I believe we need to update this to use the recent `usePageSize`, similar to this changes in Cards layout: https://github.com/directus/directus/pull/17309/files#diff-9940b7966742cae75070d5f1c877859e6712805136610a866f8db5f61fd4aacf

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Should be the same as `/translations`

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Should be the same as `/translations`

File: api/src/controllers/translations.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (nickrum) [reply api/src/controllers/translations.ts:72]: > translations is already an outlier as the `key` here isn't the primary key. 👀

You're not wrong! We do have controllers that use different routes than the items controller , though, but they at least all flow the same rules for `POST`/`PATCH`/etc.

Making `/translations` act the same as `/items` would indeed be best 👍

File: docs/reference/system/translations.md
Comment (br41nslug) [inline docs/reference/system/translations.md:1]: This docs file will also need to be updated to reflect the new API controller 😄

File: api/src/controllers/translations.ts
[the remark this answers is not in the document]
Comment (br41nslug) [reply api/src/controllers/translations.ts:1]: Performance for these endpoints have taken a fair hit compared to before. I am seeing up to 4 seconds load time on my tiny test database with 28 translations.

File: app/src/lang/refresh-current-language.ts [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+	const { currentUser } = useUserStore();
+	const translationsStore = useTranslationsStore();
+
+	let lang = fallback;
+
+	if (serverStore.info?.project?.default_language) lang = serverStore.info.project.default_language;
+
+	if (currentUser && 'language' in currentUser && currentUser.language) {
+		lang = currentUser.language;
+	}
```
Comment (nickrum) [inline app/src/lang/refresh-current-language.ts:18]: Do we want to use `getCurrentLanguage()` here as well?

**Review by nickrum — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by licitdev — APPROVED** [review]

File: api/src/services/translations.ts [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+	constructor(options: AbstractServiceOptions) {
+		super('directus_translations', options);
+
+		this.knex = options.knex || getDatabase();
+		this.accountability = options.accountability || null;
+		this.schema = options.schema;
+	}
+
+	private async translationKeyExists(key: string, language: string) {
+		const result = await this.knex.select('').from(this.collection).where({ key, language });
```
Comment (rijkvanzanten) [inline api/src/services/translations.ts:18]: Lets play it safe here:

```suggestion
		const result = await this.knex.select('id').from(this.collection).where({ key, language });
```

Gut feeling says there's _probably_ an edge case bug waiting to happen where one of the DBs doesn't support fetching nothing

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Review by nickrum — APPROVED** [review]
