### PR TITLE
fix(graphql):handle nested originalError inside the GraphQLError.originalError in processError method

### LINKED ISSUE #20442: GraphQL API doesn't report the correct extension code
### Describe the Bug

Hi there,

In a custom hook extension, given a filter hook in which I throw an error with a specific extension code, the GraphQL API always responds with the extension code of INTERNAL_SERVER_ERROR. This makes it difficult to distinguish between unexpected server errors and validation errors.

### To Reproduce

Given the hook,

```
const InvalidPayloadError = createError('INVALID_PAYLOAD_ERROR', 'Something went wrong...', 500);

filter("My_Collection.items.create", async (payload) => {
      throw new InvalidPayloadError();
});
```

The GraphQL API responds with the following when performing a mutation,

```
{
    "data": {
        "create_My_Collection_item": null
    },
    "errors": [
        {
            "message": "Something went wrong...",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 1
                }
            ],
            "path": [
                "create_My_Collection_item"
            ]
        }
    ]
}
```

The expected response is,
```
{
    "data": {
        "create_My_Collection_item": null
    },
    "errors": [
        {
            "message": "Something went wrong...",
            "extensions": {
                "code": "INVALID_PAYLOAD_ERROR"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 1
                }
            ],
            "path": [
                "create_My_Collection_item"
            ]
        }
    ]
}
```

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by mahendraHegde**
## Scope

What's changed:

- `processError` method to process the graphQL error was having wrong type for originalError
- GraphQLError.originalError was in fact of type GraphQLError, so "original error" is accessed by error.originalError.originalError`
Screenshot 2023-12-25 at 2 18 09 PM

## Potential Risks / Drawbacks

NA

#### Error Response after fix

```
{
    "data": {
        "update_table_a_item": null
    },
    "errors": [
        {
            "message": "Something went wrong...",
            "extensions": {
                "code": "INVALID_PAYLOAD_ERROR"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "update_table_a_item"
            ]
        }
    ]
}
```

#### Sample Validation error response after fix
```
{
    "data": {
        "update_table_a_item": null
    },
    "errors": [
        {
            "message": "Validation failed for field \"status\". Value can't be null.",
            "extensions": {
                "code": "FAILED_VALIDATION",
                "field": "status",
                "type": "nnull"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "update_table_a_item"
            ]
        }
    ]
}
```
---

Fixes #20442

### CODE REVIEW

File: api/src/services/graphql/utils/process-error.ts [hunk 1]
```diff
@@ -1,12 +1,19 @@
...
+	error: Readonly<GraphQLError & { originalError: GraphQLError | DirectusError | Error | undefined }>,
+): GraphQLFormattedError => {
 	logger.error(error);
 
-	const { originalError } = error;
+	let originalError = error.originalError;
+
+	if (originalError && 'originalError' in originalError) {
+		originalError = originalError.originalError;
+	}
```
Comment (mahendraHegde) [inline api/src/services/graphql/utils/process-error.ts:16]: even though `originalError` is always nested inside `error.originalError`
I have added this logic to make sure to keep it backward compatible or inline with the `GraphQLError` type definition.

File: api/src/services/graphql/utils/process-error.ts [hunk 2]
```diff
@@ -15,6 +22,8 @@ const processError = (accountability: Accountability | null, error: Readonly<Gra
 				code: originalError.code,
 				...(originalError.extensions ?? {}),
 			},
+			...(error.locations && { locations: error.locations }),
+			...(error.path && { path: error.path }),
```
Comment (mahendraHegde) [inline api/src/services/graphql/utils/process-error.ts:26]: added these to keep it consistent with else section.

File: api/src/services/graphql/utils/process-error.ts [hunk 3]
```diff
@@ -1,12 +1,19 @@
-import { isDirectusError } from '@directus/errors';
+import { isDirectusError, type DirectusError } from '@directus/errors';
 import type { Accountability } from '@directus/types';
 import type { GraphQLError, GraphQLFormattedError } from 'graphql';
 import logger from '../../../logger.js';
 
-const processError = (accountability: Accountability | null, error: Readonly<GraphQLError>): GraphQLFormattedError => {
+const processError = (
+	accountability: Accountability | null,
+	error: Readonly<GraphQLError & { originalError: GraphQLError | DirectusError | Error | undefined }>,
```
Comment (mahendraHegde) [inline api/src/services/graphql/utils/process-error.ts:8]: `error.originalError` is an instance of `GraphQLError` in all the cases i tried. however i have kept the `originalError` type as union to keep it consistent/backward compatible with type `GraphQLError`

**Review by mahendraHegde — COMMENTED** [review]
@br41nslug  this is ready to be reviewed.

**Review by paescuj — APPROVED** [review]
Thanks @mahendraHegde, LGTM 🚀
