### PR TITLE
Ensure the created revision uses the correct label

### LINKED ISSUE #26273: Created revision record not showing in UI
### Describe the Bug

Before 11.13.0 the created record of an item was shown in the right "Revisions" section.
Now only updates are shown:

Image

Even though the create record does exist.

Image

### To Reproduce

Create an item in Directus
View the item in collections and check its revisions.
It should show when and by whom it was created.

### Directus Version

11.13.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySql

### PR DESCRIPTION
**Pull request by vizzv**
## Scope

What's changed:

- Corrected the revision sidebar label for **create** revision entries.
- Replaced the incorrect `revision_delta_updated` translation key with `revision_delta_created`.
- Ensures newly created items display **“Created”** instead of **“Updated”** in the Revisions panel across all supported databases.

## Potential Risks / Drawbacks

- Very low risk: this change only updates the translation key used at runtime and does not modify revision logic or database behavior.

## Tested Scenarios

- Created new items in **SQLite**.
- Verified the revision sidebar now correctly displays **"Created"** for creation events.

## Review Notes / Questions

- Although the translation key `revision_delta_created` currently resolves to `"Created"` and does not include a `{count}` placeholder, I kept the existing pattern:

```js
  t('revision_delta_created', revisionCount.value);
```

This preserves consistency with other revision actions and ensures future compatibility with:

- locales that may use {count}
- potential pluralization changes
- consistent function signatures across all actions

Fixes #26273

If there's anything you'd like adjusted or improved, feel free to let me know!

### CODE REVIEW

File: app/src/views/private/components/revision-item.vue [hunk 1]
```diff
@@ -30,7 +30,7 @@ const revisionCount = computed(() => {
 const headerMessage = computed(() => {
 	switch (props.revision.activity.action.toLowerCase()) {
 		case 'create':
-			return t('revision_delta_updated', revisionCount.value);
+			return t('revision_delta_created', revisionCount.value);
```
Comment (formfcw) [inline app/src/views/private/components/revision-item.vue]: Let’s remove the parameter here since there is none for the `revision_delta_created` message.

```suggestion
			return t('revision_delta_created');
```

File: .changeset/orange-rats-burn.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/app': major
```
Comment (formfcw) [inline .changeset/orange-rats-burn.md]: Let’s use "patch" since this is a fix.

```suggestion
'@directus/app': patch
```

File: .changeset/orange-rats-burn.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+---
+
+fix(revisions): use correct label for create revision
```
Comment (formfcw) [inline .changeset/orange-rats-burn.md]: Let’s use a changeset in past tense per our [contribution guidelines](https://directus.io/docs/community/contribution/pull-requests#changesets).

```suggestion
Ensured the created revision uses the correct label
```

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you @vizzv for your first contribution :tada:

Just a few minor things.

**Comment by vizzv** [comment]
Thank you! All changes have been applied.

**Review by formfcw — APPROVED** [review]
Thank you @vizzv :heart:

LGTM 🎉

**Review by AlexGaillard — APPROVED** [review]
