### PR TITLE
Fix rotating called twice

### LINKED ISSUE #15490: Rotations that are multiples of 90 degrees do not work in transforms parameter (assets endpoint)
### Describe the Bug

I need to use the `/assets` endpoint to rotate the image by multiples of 90 degrees. However, it does not work now - the API returns the unchanged image. However, using other values (91, 53, -273, etc.) rotates the image as expected.

### To Reproduce

1. Create a new image
2. Use the /assets endpoint and `transforms=[["rotate", 90]]` on any image to reproduce the problem

### Errors Shown

None

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by Nitwel**
## Description

It seems that `sharp` doesn't like to have `rotate` called multiple times.

Fixes #15490

### CODE REVIEW

File: api/src/services/assets.ts [hunk 1]
```diff
@@ -151,7 +151,10 @@ export class AssetsService {
 				const transformer = sharp({
 					limitInputPixels: Math.pow(env.ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION, 2),
 					sequentialRead: true,
-				}).rotate();
+				});
+
+				if(transforms.find((transform) => transform[0] === 'rotate') === undefined)
```
Comment (licitdev) [inline api/src/services/assets.ts:156]: I think this line isn't necessary. Just the removal of `rotate()` seems to do the trick as the rotation is applied in the following line. 🤔

Comment (Nitwel) [reply api/src/services/assets.ts:156]: `rotate` by default aligns the image with it's metadata orientation so we still want to correctly rotate the image when the metadata exists.

Comment (licitdev) [reply api/src/services/assets.ts:156]: Got it. Thanks for the clarification! 👍

**Review by licitdev — APPROVED** [review]
