### PR TITLE
Fix sorting in m2m table

### LINKED ISSUE #17474: Sorting a column in a Many to Many table returns error
### Describe the Bug

Hi, I hope I can describe this issue clear enough.

In my data model, I have a collection `project`. 
Within this collection there is a Many to Many field called `poster_layers`.

<details>
<summary>Show Data Model</summary>

image

</details>

<details>
<summary>Show Many to Many field config</summary>

image
image
image
image
image

</details>

image

When I click on a column header to sort, e.g. `Z Index` in the screenshot above, I get the following error:

image

---

Also, what is very weird (but maybe unrelated), is that sometimes when I click on an item in this table I get the following error:

image

Clicking on Dismiss just closes the popup and everything works as you'd expect: it opens the item and I can edit it. 

### To Reproduce

I'm not sure how to reproduce this, but the Poster Layers collection looks like this:

<details>
<summary>Show Poster Layers collection fields</summary>

image

</details>

<details>
<summary>Show Project Poster Layers junction table</summary>

image
image

</details>

### Errors Shown

I see a 400 Bad Request network error in the console:

`/items/project_poster_layers?fields[]=poster_layers_id.image.id&fields[]=poster_layers_id.image.type&fields[]=poster_layers_id.image.title&fields[]=poster_layers_id.zIndex&fields[]=poster_layers_id.id&fields[]=poster_layers_id.scale&fields[]=poster_layers_id.blendMode&fields[]=id&filter[_and][0][project_slug]=gnomes&page=1&limit=15&sort[]=poster_layers_id.poster_layers_id.zIndex`

I think the error is in the last `sort[]` parameter. If I replace that value with `poster_layers_id.zIndex` the request returns with 200 OK and the table sorts properly.

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

-

### What database are you using?

Postgres

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker image 9

### PR DESCRIPTION
**Pull request by Nitwel**
The problem was that the junction field got applied twice.

Fixes #17474, fixes ENG-679

### CODE REVIEW

**Review by azrikahar — APPROVED** [review]
PR LGTM!

---

Very random tangent here, I was just checking list O2M interface since the query is now identical, but I noticed the watcher has `limit` in O2M, but not M2M:

- O2M
    https://github.com/directus/directus/blob/01cf6ee73d4d34fd0ab44e73dba6d5f37f3bb937/app/src/interfaces/list-o2m/list-o2m.vue#L316-L318

- M2M
    https://github.com/directus/directus/blob/01cf6ee73d4d34fd0ab44e73dba6d5f37f3bb937/app/src/interfaces/list-m2m/list-m2m.vue#L341-L343

It seems like the `limit` in O2M was added in #16412, should we add it to M2M as well?

**Review by licitdev — COMMENTED** [review]
The current fix removes the error message. However, two other issues surfaced when testing the sorting within an M2M table interface.

1. The sort button is not hidden when sort is changed from descending to "no sort".
2. The received values from the API are sorted but the sorting isn't displayed.

https://user-images.githubusercontent.com/26413686/225365932-4754cb6a-3485-4ac2-9c07-981d763b2573.mov

File: app/src/composables/use-relation-multiple.ts [hunk 1]
```diff
@@ -178,12 +178,15 @@ export function useRelationMultiple(
...
+		const sortField = (previewQuery.value.sort ?? toArray(relation.value.sortField))[0];
 
 		if ((previewQuery.value.limit > 0 && totalItemCount.value > previewQuery.value.limit) || !sortField) return items;
 
 		return items.sort((a, b) => {
-			return a[sortField] - b[sortField];
+			const field = sortField.replace('-', '');
+
+			if (sortField.startsWith('-')) return get(b, field) - get(a, field);
+			else return get(a, field) - get(b, field);
```
Comment (azrikahar) [inline app/src/composables/use-relation-multiple.ts:189]: Although `replace('-', '')` does technically works, it might be better to follow our existing convention of `substring(1)` 👍 such as:

- https://github.com/directus/directus/blob/9526b4e5b222acc8f58aa3ad61fb15393dca74e8/api/src/database/run-ast.ts#L490-L493

- https://github.com/directus/directus/blob/9526b4e5b222acc8f58aa3ad61fb15393dca74e8/api/src/utils/apply-query.ts#L262-L264

perhaps especially for edge cases where a setup may (somehow) have fields with hyphens (eg. `my-new-field`), even if such cases aren't truly officially supported per se.

**Review by azrikahar — CHANGES_REQUESTED** [review]

File: app/src/composables/use-relation-multiple.ts (hunk 1 above)
Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts:189]:
```suggestion
			const field = sortField.substring(1);

			if (sortField.startsWith('-')) return get(b, field) - get(a, field);
			else return get(a, field) - get(b, field);
```

Comment (Nitwel) [reply app/src/composables/use-relation-multiple.ts]: Updated it

**Review by azrikahar — APPROVED** [review]
LGTM!

**Review by freekrai — APPROVED** [review]
👍🏻

**Review by licitdev — APPROVED** [review]
Fixes the sorting issue within the table. 👍
