### PR TITLE
Fix permission generation for Shares 📰

### LINKED ISSUE #23017: Share permissions are not handled at all in V11
### Describe the Bug

The old implementation of share permissions are not directly transferable to the new policies implementation. 

Instead of selecting a role that the permissions are based on, we will simplify this to selecting fields that a share should be able to access. Additionally the transitive permissions that are require to view all relations of the shared item will be injected like before.

### To Reproduce

- Try to create a share

### Directus Version

v11.0.0-rc.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### LINKED ISSUE #23930: Shares are not shown to users with Public permissions.
### Describe the Bug

Shares with no role (which [according to docs, should default to Public permissions](https://docs.directus.io/user-guide/content-module/content/shares.html#:~:text=If%20no%20Role%20is%20selected%2C%20it%20defaults%20to%20Public%20permissions)) are not displaying shared item.

Instead, message "Empty Form, This form has no visible fields." is shown.

### To Reproduce

1. Define a collection, with some visible fields.
2. Set Full Read Access for this collection for the Public policy.
3. Create item within that collection.
4. Create a share for that item, without a role or password.
5. Copy link to this share
6. In another browser or incognito window, open this share.

https://github.com/user-attachments/assets/01065e9f-ab16-4267-834b-735d2be3b1aa

Expected:
Shared item is displayed.

Result:
Shared item is not shown.

### Directus Version

v11.1.1

### Hosting Strategy

Directus Cloud

### Database

_No response_

### PR DESCRIPTION
**Pull request by Nitwel**
Bring back the ability to share items while also making sure [this](https://github.com/directus/directus/security/advisories/GHSA-pmf4-v838-29hg) is covered.

## Scope

What's changed:

- Properly give out read permissions on access through a share
- Scope the permissions to only what the user who created it has access to instead of selecting a role
- Fix app hydration on shares

## Potential Risks / Drawbacks

- As permissions are critical to work properly, there is always a high risk attached to these changes.
- The risk in this PR should be scoped to only `read` actions with a share as any other action will not be handled by the introduced code.

---

Fixes #23017, Fixes #23930
Closes SER-19

### CODE REVIEW

**Comment by Nitwel** [comment]
>I don't think this is the optimal approach, as this severely limits the capabilities of shares to only show specific fields. Previously that was possible. Now, every admin who creates a share will now share all the fields instead of a limited number of fields.

For context of the discussion, Hannes and I chatted on if we want to support a fields array option to whitelist all fields, that should be included in the share. I decided to leave out such feature out of this PR for the following reasons:

- The implementation details for the fields option should be discussed first in detail, as it is unclear if a whitelist or blacklist makes more sense and if wildcards should be allowed in that list.
- Shares are currently completely broken and going with fields would significantly increase the time until shares work at all again.
- As this is touching permission logic, I wanted to keep this PR as simple and minimalistic as possible to make sure we can catch all hidden gotchas before merging and that it is not a mess to review.

In short, I'm not against adding the fields option in another PR, but I would prefer to keep that feature out of this one. For an intermediate solution, we could also leave the option in to select a role for a share. That way you can again scope the fields to only what a certain role has access to. That way, we can leave out the migration.

> The migration also just suddenly gives more access to fields that previously where not visible in existing shares.

Could you elaborate as that sounds like my PR is leaking information and that would have to be fixed before we can merge this.

**Comment by Nitwel** [comment]
@licitdev feel free to review this now as I've added back in support for the role option.

File: api/src/permissions/utils/get-permissions-for-share.ts [hunk 1]
```diff
@@ -0,0 +1,278 @@
...
+		presets: null,
+		fields: null,
+	};
+
+	const { collection, item, role, user_created } = await fetchShareInfo(accountability.share!, context);
+
+	const userAccountability: Accountability = {
+		user: user_created.id,
+		role: user_created.role,
+		roles: await fetchRolesTree(user_created.role, context.knex),
```
Comment (licitdev) [inline api/src/permissions/utils/get-permissions-for-share.ts:34]: Wondering if the fetching of `role` from `user_created` could be a risk as the user's role may be updated, potentially elevating permissions after the share's creation. 🤔

Comment (Nitwel) [reply api/src/permissions/utils/get-permissions-for-share.ts:34]: That would be fine as the main scoping method for shares is the role option and the user_created is then merged with the assigned role.

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
### Shows admin after share
- Go to a share link
- Open a new tab and navigate to http://localhost:8055/admin/users 
- Observe it shows the admin instead of redirecting to login

https://github.com/user-attachments/assets/bdba8090-e7f4-4e01-b78d-b610150639e4

### O2M displays internal error
- Create a share that contains an o2m within the collections data model
- Observe display of `An unexpected error occurred` error message with the following error in the console
```sql
select (CASE WHEN  THEN `directus_collections`.`collection` END) AS `collection`, (CASE WHEN  THEN `directus_collections`.`icon` END) AS `icon`, (CASE WHEN  THEN `directus_collections`.`note` END) AS `note`, (CASE WHEN  THEN `directus_collections`.`display_template` END) AS `display_template`, (CASE WHEN  THEN `directus_collections`.`hidden` END) AS `hidden`, (CASE WHEN  THEN `directus_collections`.`singleton` END) AS `singleton`, (CASE WHEN  THEN `directus_collections`.`translations` END) AS `translations`, (CASE WHEN  THEN `directus_collections`.`archive_field` END) AS `archive_field`, (CASE WHEN  THEN `directus_collections`.`archive_app_filter` END) AS `archive_app_filter`, (CASE WHEN  THEN `directus_collections`.`archive_value` END) AS `archive_value`, (CASE WHEN  THEN `directus_collections`.`unarchive_value` END) AS `unarchive_value`, (CASE WHEN  THEN `directus_collections`.`sort_field` END) AS `sort_field`, (CASE WHEN  THEN `directus_collections`.`accountability` END) AS `accountability`, (CASE WHEN  THEN `directus_collections`.`color` END) AS `color`, (CASE WHEN  THEN `directus_collections`.`item_duplication_fields` END) AS `item_duplication_fields`, (CASE WHEN  THEN `directus_collections`.`sort` END) AS `sort`, (CASE WHEN  THEN `directus_collections`.`group` END) AS `group`, (CASE WHEN  THEN `directus_collections`.`collapse` END) AS `collapse`, (CASE WHEN  THEN `directus_collections`.`preview_url` END) AS `preview_url`, (CASE WHEN  THEN `directus_collections`.`versioning` END) AS `versioning` from `directus_collections` order by `directus_collections`.`collection` asc - SQLITE_ERROR: near "THEN": syntax error
```

https://github.com/user-attachments/assets/3fa14473-e312-4737-b419-9afb76b753bb



### Default Role selected
It is not intuitive or indicated anywhere that the role of the one who created the share will be used by default for permissions. We should have the users role selected with no selection option unless they are admin (an additional note under the dropdown might be helpful as well). We should not allow for deselection in any case.

File: api/src/permissions/utils/get-permissions-for-share.ts [hunk 2]
```diff
@@ -0,0 +1,278 @@
...
+		admin: false,
+		app: false,
+		ip: accountability.ip,
+	};
+
+	// Fallback to user accountability so merging later on has no issues
```
Comment (licitdev) [inline api/src/permissions/utils/get-permissions-for-share.ts:40]: Should the fallback be updated to the public role instead of the creator's role. 🤔  This PR could resolve #23930.

I think we should retain the pre-existing behaviour in utilizing the public role so that existing shares without a role will not result in privilege escalation.

Comment (ComfortablyCoding) [reply api/src/permissions/utils/get-permissions-for-share.ts:40]: Agreed

**Comment by Nitwel** [comment]
@ComfortablyCoding Hannes fixed your bugged case and @licitdev, we now fall back to the public role, if no role is selected.

File: api/src/permissions/utils/get-permissions-for-share.ts [hunk 3]
```diff
@@ -0,0 +1,275 @@
...
+	const shareAccountability: Accountability = {
+		user: null,
+		role: role,
+		roles: await fetchRolesTree(role, context.knex),
+		admin: false,
+		app: false,
+		ip: accountability.ip,
+	};
+
+	const { admin: shareIsAdmin } = await fetchGlobalAccess(shareAccountability, context.knex);
```
Comment (ComfortablyCoding) [inline api/src/permissions/utils/get-permissions-for-share.ts:50]: We can potentially speed this up by requesting `fetchGlobalAccess`,`getPermissionsForAccountability` and `fetchAllowedFieldMap` in parallel via `Promise.all` as they are independent queries.

File: api/src/permissions/utils/get-permissions-for-share.ts [hunk 4]
```diff
@@ -0,0 +1,275 @@
...
+import type { Context } from '../types.js';
+import { fetchShareInfo } from './fetch-share-info.js';
+import { mergePermissions } from './merge-permissions.js';
+import { fetchPermissions } from '../lib/fetch-permissions.js';
+import { fetchPolicies } from '../lib/fetch-policies.js';
+import { fetchRolesTree } from '../lib/fetch-roles-tree.js';
+import { reduceSchema } from '../../utils/reduce-schema.js';
+import { fetchGlobalAccess } from '../modules/fetch-global-access/fetch-global-access.js';
+
+export async function getPermissionsForShare(
```
Comment (ComfortablyCoding) [inline api/src/permissions/utils/get-permissions-for-share.ts:14]: IMO we should add tests for this function

File: api/src/services/authentication.ts [hunk 5]
```diff
@@ -294,7 +294,6 @@ export class AuthenticationService {
 				user_role: 'u.role',
 				share_id: 'd.id',
 				share_item: 'd.item',
```
Comment (ComfortablyCoding) [inline api/src/services/authentication.ts:296]: `share_item`,`share_collection`,share_times_used` and `share_max_users` do not seem to be used anymore either?

File: api/src/types/auth.ts [hunk 6]
```diff
@@ -36,15 +36,10 @@ export type DirectusTokenPayload = {
...
-		collection: string;
-		item: string;
-	};
 };
 
 export type ShareData = {
 	share_id: string;
-	share_role: string;
 	share_item: string;
 	share_collection: string;
```
Comment (ComfortablyCoding) [inline api/src/types/auth.ts:44]: `share_collection` and `share_item` do not seem to be relevant anymore as well

**Comment by ComfortablyCoding** [comment]
- If a user has read to the field but not the junction table for M2M and M2M we show incorrect configuration, IMO it should display insufficient permissions or the like in this case
Screenshot 2024-10-31 at 2 54 46 PM

**Comment by Nitwel** [comment]
I agree on the frontend should show better error cases but I'm fairly confident that this is outside the scope of what this PR is trying to achieve.

**Comment by Nitwel** [comment]
@ComfortablyCoding added tests for function.

**Review by ComfortablyCoding — APPROVED** [review]
