### PR TITLE
Fix parsing of Error objects when redacting

### LINKED ISSUE #18751: Crash flow when calling throw Error
### Describe the Bug

```
WARN: Error could not be cloned.
    err: {
      "type": "DOMException",
      "message": "Error could not be cloned.",
      "stack":
          DataCloneError: Error could not be cloned.
              at new DOMException (node:internal/per_context/domexception:53:5)
              at structuredClone (node:internal/structured_clone:23:17)
              at redact (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/utils/redact.js:11:19)
              at FlowManager.executeFlow (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/flows.js:281:31)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Promise.all (index 0)
      "name": "DataCloneError",
      "code": 25,
      "INDEX_SIZE_ERR": 1,
      "DOMSTRING_SIZE_ERR": 2,
      "HIERARCHY_REQUEST_ERR": 3,
      "WRONG_DOCUMENT_ERR": 4,
      "INVALID_CHARACTER_ERR": 5,
      "NO_DATA_ALLOWED_ERR": 6,
      "NO_MODIFICATION_ALLOWED_ERR": 7,
      "NOT_FOUND_ERR": 8,
      "NOT_SUPPORTED_ERR": 9,
      "INUSE_ATTRIBUTE_ERR": 10,
      "INVALID_STATE_ERR": 11,
      "SYNTAX_ERR": 12,
      "INVALID_MODIFICATION_ERR": 13,
      "NAMESPACE_ERR": 14,
      "INVALID_ACCESS_ERR": 15,
      "VALIDATION_ERR": 16,
      "TYPE_MISMATCH_ERR": 17,
      "SECURITY_ERR": 18,
      "NETWORK_ERR": 19,
      "ABORT_ERR": 20,
      "URL_MISMATCH_ERR": 21,
      "QUOTA_EXCEEDED_ERR": 22,
      "TIMEOUT_ERR": 23,
      "INVALID_NODE_TYPE_ERR": 24,
      "DATA_CLONE_ERR": 25
    }
```

### To Reproduce

call throw new Error() in flows (blocking operation)

### Directus Version

V10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by licitdev**
`structuredClone()` throws a `DataCloneError` when redacting logs that contain unserializable values.

Fixes #18751.

### CODE REVIEW

File: api/src/utils/error-replacer.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+/**
+ * Extract values from Error objects for use with JSON.stringify()
+ */
+export function errorReplacer(_key: string, value: any) {
```
Comment (rijkvanzanten) [inline api/src/utils/error-replacer.ts:4]: Can we come up with a bit better name for this? Looks like it's trying to standardize the stringified output of an Error object? The name `errorReplacer` isn't descriptive enough 🙂

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/utils/error-replacer.ts (hunk 1 above)
Comment (licitdev) [reply api/src/utils/error-replacer.ts:4]: How does `jsonStringifyErrorReplacer` sound? 👀 
It's used as `JSON.stringify()`'s second arg.

Comment (rijkvanzanten) [reply api/src/utils/error-replacer.ts:4]: It looks to me like it basically transforms an error object into a typed object, so maybe we call it something like `errorToSanitizedObject` or something? 🤔

Comment (licitdev) [reply api/src/utils/error-replacer.ts:4]: The choice of name was because it's known as `replacer function` and it is supposed to be used alongside `JSON.stringify()` only. Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

> maybe we call it something like `errorToSanitizedObject` or something

The function isn't sanitizing as the result of error object after `JSON.stringify()` is `{}` due to it's `enumerable` flag being `false`. Hmm, or should the `errorReplacer()` be exported from the redact util since it's only used there right now?

Comment (licitdev) [reply api/src/utils/error-replacer.ts]: 👍 Moved it in https://github.com/directus/directus/pull/18777/commits/275ed152df4ccfe559dd574578c096a6b153df02

File: api/src/utils/redact.ts [hunk 2]
```diff
@@ -86,3 +86,19 @@ export function redact(input: UnknownObject, paths: Paths, replacement: string):
 		}
 	}
 }
+
+/**
+ * Extract values from Error objects for use with JSON.stringify()
+ */
+export function errorReplacer(_key: string, value: any) {
```
Comment (paescuj) [inline api/src/utils/redact.ts:93]: Can we use `unknown` here?
```suggestion
export function errorReplacer(_key: string, value: unknown) {
```

Comment (licitdev) [reply api/src/utils/redact.ts:93]: Yes we should. Thanks!

**Review by rijkvanzanten — APPROVED** [review]
