### PR TITLE
Optimization: make readByQuery able to handle thousands of nested items

### LINKED ISSUE #23906: ItemsService.readByQuery() is not optimized for a lot of nested items
### Describe the Bug

ItemsService.readByQuery() takes 90 seconds to return items having thousands of m2m nested items 

Here is the profile
[read_grouped_notifications-no_optim.cpuprofile](https://github.com/user-attachments/files/17495939/read_grouped_notifications-no_optim.cpuprofile)

### To Reproduce

Given:
- I have 20 000 users 
- I created a `grouped_notification` collection related to them as `recipients` with a m2m relationship. 
- I create some grouped_notifications with all of them as recipients (this is also very slow but may be addressed in another PR later)
When:
- I display the list of grouped_notification in the admin panel
Then:
- It takes 90 seconds to get the list

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL 15

### PR DESCRIPTION
**Pull request by jclaveau**
## Scope

What's changed:

- ItemsService.readByQuery can now display a list of items having 20 000 nested items in 5 seconds instead of 90

## Potential Risks / Drawbacks

- There is no api change

## Review Notes / Questions

- I don't know your convention for naming errors
- I didn't understand the case where `Array.isArray(nestedItem[nestedParentKeyField])`. Some explanation would be nice 

---

Profiles
- Before [read_grouped_notifications-no_optim.cpuprofile](https://github.com/user-attachments/files/17495981/read_grouped_notifications-no_optim.cpuprofile)
- After with objects as hashmaps [read_grouped_notifications-object_optims.cpuprofile](https://github.com/user-attachments/files/17496002/read_grouped_notifications-object_optims.cpuprofile)
- After with Maps as hashmaps [read_grouped_notifications-map_optims.cpuprofile](https://github.com/user-attachments/files/17496011/read_grouped_notifications-map_optims.cpuprofile)

Fixes #23906

### CODE REVIEW

File: api/src/services/payload.ts [hunk 1]
```diff
@@ -190,16 +190,12 @@ export class PayloadService {
...
-					}),
-				);
-			}),
-		);
+		for (const record of processedPayload) {
+			for (const [name, field] of specialFields) {
+				const newValue = await this.processField(field, record, action, this.accountability);
+				if (newValue !== undefined) record[name] = newValue;
+			}
+		}
```
Comment (rijkvanzanten) [inline api/src/services/payload.ts:198]: This now runs sequential rather than parallel. Did that help the performance increase? I take it that at the tens of thousands of items range the number of async handles becomes a new bottleneck?

**Review by rijkvanzanten — COMMENTED** [review]
Haven't tested a running copy yet, but code review lgtm!

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 2]
```diff
@@ -16,39 +16,81 @@ export function mergeWithParentItems(
...
 
 	if (nestedNode.type === 'm2o') {
-		for (const parentItem of parentItems) {
-			const itemChild = nestedItems.find((nestedItem) => {
-				return (
-					nestedItem[schema.collections[nestedNode.relation.related_collection!]!.primary] ==
-					parentItem[nestedNode.relation.field]
-				);
-			});
+		const parentsByForeignKey = new Map();
```
Comment (jaads) [inline api/src/database/run-ast/utils/merge-with-parent-items.ts:19]: I think it wouldn't hurt to be explicit regarding the datatypes of the maps, to get type safety and directly see what map will be build. I assume it would be this:
```ts
import type { PrimaryKey } from '@directus/types';

const parentsByForeignKey: Map<PrimaryKey, Item[]> = new Map();
```
(the name of the type is a bit confusing here, but I guess that's how it's done so far).

similarly for the other new map `parentsByPrimaryKey`. 

```ts
const parentsByPrimaryKey: Map<PrimaryKey, Item> = new Map();
```

File: api/src/services/payload.ts (hunk 1 above)
Comment (jclaveau) [reply api/src/services/payload.ts:198]: Actually, due to the mono-thread aspect of JS, the Node's event loop can't do real parallel execution here (in contrast with calling multiple endpoints from a web browser for example).
As a result it's just flooding the event loop Promises callstack producing a slowdown instead of a faster run.

The Primagen has done a very clear video about it: https://youtu.be/dWxcw2R0gZs?t=480

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 3]
```diff
@@ -16,39 +16,81 @@ export function mergeWithParentItems(
...
 			}
 
-			if (!parentItem[nestedNode.fieldKey]) parentItem[nestedNode.fieldKey] = [] as Item[];
+			parentsByPrimaryKey.set(parentPrimaryKey, parentItem);
+		});
 
-			const itemChildren = nestedItems.filter((nestedItem) => {
-				if (nestedItem === null) return false;
-				if (Array.isArray(nestedItem[nestedNode.relation.field])) return true;
+		const toAddToAllParents: typeof nestedItems = [];
```
Comment (jaads) [inline api/src/database/run-ast/utils/merge-with-parent-items.ts:63]:
```suggestion
		const toAddToAllParents: Item[] = [];
```

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 4]
```diff
@@ -16,39 +16,81 @@ export function mergeWithParentItems(
...
-				parentItem[nestedNode.fieldKey] = null;
-				continue;
+		const parentCollectionName = nestedNode.relation.related_collection;
+		const parentPrimaryKeyField = schema.collections[parentCollectionName!]!.primary;
+		const parentRelationField = nestedNode.fieldKey;
+		const nestedParentKeyField = nestedNode.relation.field;
+
+		const parentsByPrimaryKey = new Map();
+
+		parentItems.forEach((parentItem: (typeof parentItems)[number]) => {
```
Comment (jaads) [inline api/src/database/run-ast/utils/merge-with-parent-items.ts:49]:
```suggestion
		parentItems.forEach((parentItem: Item) => {
```

File: api/src/database/run-ast/utils/merge-with-parent-items.ts [hunk 5]
```diff
@@ -16,39 +16,81 @@ export function mergeWithParentItems(
...
-			const itemChild = nestedItems.find((nestedItem) => {
-				return (
-					nestedItem[schema.collections[nestedNode.relation.related_collection!]!.primary] ==
-					parentItem[nestedNode.relation.field]
-				);
-			});
+		const parentsByForeignKey = new Map();
 
-			parentItem[nestedNode.fieldKey] = itemChild || null;
+		parentItems.forEach((parentItem: (typeof parentItems)[number]) => {
```
Comment (jaads) [inline api/src/database/run-ast/utils/merge-with-parent-items.ts:21]:
```suggestion
		parentItems.forEach((parentItem: Item) => {
```

**Review by jaads — COMMENTED** [review]
apart the tiny typing improvements, everything looks look to me too 👍  great idea to use a map there 🎉  This should have boosted the performance the most.  

I did some manual testing - it worked as expected. I'd run the black box tests soon too before merging it

File: api/src/services/payload.ts (hunk 1 above)
Comment (rijkvanzanten) [reply api/src/services/payload.ts:198]: Ah yes processField isn't touching the DB of course 🙂

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Thanks @jclaveau! And welcome to the repo 🙂
