### PR TITLE
Fix redaction of objects with circular structure

### LINKED ISSUE #19833: Authenticate scope in Flow causes error
### Describe the Bug

If a flow is created with a trigger using the scope **authenticate** it will cause the following error:

```
ERROR: Converting circular structure to JSON
--> starting at object with constructor 'Socket'
|     property 'parser' -> object with constructor 'HTTPParser'
--- property 'socket' closes the circle
```

This causes every page in the Directus app to break. The only way to fix it is to remove the flow from the database and restart Directus.

### To Reproduce

In the Directus app, create a flow with a trigger of type **Filter** and scope **authenticate**.

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #19833

### CODE REVIEW

File: api/src/utils/redact-object.ts [hunk 1]
```diff
@@ -111,7 +111,18 @@ export function getReplacer(replacement: Replacement, values?: Values) {
 		? Object.entries(values).filter(([_k, v]) => typeof v === 'string' && v.length > 0)
 		: [];
 
+	const seen = new WeakSet();
+
 	return (_key: string, value: unknown) => {
+		// Skip circular values
```
Comment (licitdev) [inline api/src/utils/redact-object.ts:117]: Wonder if this would be clearer 🤔 

```suggestion
		// Skip circular values that had appeared before
```

File: api/src/utils/redact-object.ts [hunk 2]
```diff
@@ -111,7 +111,18 @@ export function getReplacer(replacement: Replacement, values?: Values) {
...
+		if (typeof value === 'object' && value !== null) {
```
Comment (licitdev) [inline api/src/utils/redact-object.ts:118]: Thought of catching "truthy" values instead of `null` only.
```suggestion
		if (typeof value === 'object' && value) {
```

**Review by licitdev — APPROVED** [review]
Nice fix with WeakSet! 👍 
Added some thoughts below, non-blocking~

File: api/src/utils/redact-object.ts (hunk 2 above)
Comment (azrikahar) [reply api/src/utils/redact-object.ts:118]: Random tangent that popped up in my mind, what if we use `isObject` util function which I assume was the original intention (aside from the extra Array check) of this IF statement?

https://github.com/directus/directus/blob/e78a01013a15af22c37c28b4a040ce12d2b4df30/api/src/utils/redact-object.ts#L99

especially since it's used in this same redactObject function already at line 99, which means doing `if (isObject(value))` instead

Comment (paescuj) [reply api/src/utils/redact-object.ts:118]: We only need to track objects as other values cannot be circular, the null check ensures that by filtering out `Array` and `null` (which are also typeof object).

Comment (paescuj) [reply api/src/utils/redact-object.ts]: > Random tangent that popped up in my mind, what if we use `isObject` util function which I assume was the original intention (aside from the extra Array check) of this IF statement?
> 
> https://github.com/directus/directus/blob/e78a01013a15af22c37c28b4a040ce12d2b4df30/api/src/utils/redact-object.ts#L99
> 
> especially since it's used in this same redactObject function already at line 99, which means doing `if (isObject(value))` instead

Good idea ❤️

File: api/src/utils/redact-object.ts (hunk 1 above)
Comment (paescuj) [reply api/src/utils/redact-object.ts:114]: Hmm "circular" implies that already so I think it should be fine 👍

**Review by azrikahar — APPROVED** [review]
