### PR TITLE
SDK WebSocket auth race condition

### LINKED ISSUE #20636: SDK WebSocket race condition
### Describe the Bug

There have been a few reports in Discord of the SDK `subscribe` function creating race conditions when not explicitly calling `connect` beforehand.

### To Reproduce

```ts
const client = createDirectus<Schema>('https://api.directus.io').with(realtime());

const { subscription, unsubscribe } = await client.subscribe('test', {
	query: { fields: ['*'] },
});

for await (const item of subscription) {
	console.log('subscription', { item });
}

// unsubscribe()
```

Run this snippet a few times (as race conditions can always be tricky)

### Directus Version

10.8.x

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #20636

## Scope

What's changed:

- Fixed race condition when subscribing where the connection is technically already open but the server is not accepting connections yet as it is dealing with authentication. By relying on the internal state instead of the raw `ws.readyState`
- Updated docs to reflect that `.connect()` already was required before you can send any messages `.sendMessage()`
- Added debug logging under a debug flag for better visibility into the websocket state.
- Fixed re-subscription after reconnecting in error situations

## TODO
- update docs about how to enable debugging
- Go over the errors thrown for consistency

### CODE REVIEW

File: sdk/src/realtime/composable.ts [hunk 1]
```diff
@@ -239,7 +248,10 @@ export function realtime(config: WebSocketConfig = {}) {
 				collection: Collection,
 				options = {} as Options,
 			) {
-				if (!socket || socket.readyState !== WebSocketState.OPEN) await this.connect();
+				if (!socket || !isConnected) {
+					throw new Error('Cannot subscribe without an open connection. Make sure you are calling "await client.connect()".');
```
Comment (rijkvanzanten) [inline sdk/src/realtime/composable.ts:252]: Can the `subscribe` call automatically call `await connect()` on the user's behalf? Is a bit better DX than having to manually call connect first.

Comment (br41nslug) [reply sdk/src/realtime/composable.ts:252]: I do agree that will be better DX however with the current approach of calling connect the errors seem to get hidden when something goes wrong during connecting like bad credentials, timeouts, being unable to connect etc. This in turn leads to a lot of question at the moment about why "subscriptions" are not firing which always seems to be connection/authentication errors without errors to the user.

Comment (br41nslug) [reply sdk/src/realtime/composable.ts:252]: I can do another dive into the issue after my other tasks to see if i can get it to properly throw these errors instead of removing the connect feature 🤔

Comment (rijkvanzanten) [reply sdk/src/realtime/composable.ts:252]: Would the subscribe call itself not reject in that case?

So you'd do something like

```ts
try {
  await subscribe('x', callback);
} catch (err) {
  // connection error
}
```

Comment (rijkvanzanten) [reply sdk/src/realtime/composable.ts]: @br41nslug Maybe the return of subscribe is the underlying connection, which can be an event emitter?

```ts
const subscription = await subscribe('x', callback);

subscription.on('connectionError', errorCallback);
```

?

Comment (br41nslug) [reply sdk/src/realtime/composable.ts]: @rijkvanzanten The client itself is already an event emitter where you can listen for low level connection events.

```js
client.onWebsocket('open', () => {})
client.onWebsocket('error', () => {})
client.onWebsocket('close', () => {})
client.onWebsocket('message', () => {})
```

**Review by rijkvanzanten — APPROVED** [review]
