### PR TITLE
Fix JSON values in raw editors and input-code

### LINKED ISSUE #19244: String/json input variables in operations Raw Editor needs to be enclosed by quotation marks
### Describe the Bug

Non numeric field parameters need to be enclosed by quotation marks or the value is set to null. Also numeric parameters don't need to be enclosed but the value does not appear outside of the raw editor.

Not enclosing the parameter worked in previous versions just fine (I updated from 9.21.2). When the parameter was not enclosed in the raw editor Directus added the quotation marks in normal editor. Now, the quotation marks must be set in the raw editor by the user. 

Bildschirmfoto 2023-07-26 um 12 54 57

Could not find any hint in v10.5 that it should work with the newest version.

### To Reproduce

How it does not work but should work:
1. Create Read Data Operation for example.
2. Try to set the raw editor of the query to something like {{$trigger.body}}
3. Save

==> The value is null

How it works:
Enter "{{$trigger.body}}" in the raw editor

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #19469: Flows - "Trigger Flow" auto escapes payload
### Describe the Bug

When passing in a variable into the payload field on the "trigger flow" operation, the quotation marks are automatically escaped which causes the variable to be interpreted as a string. This makes the flow crash because it's expecting JSON but receives a string.

### To Reproduce

Add in the payload variable
save the operation
re open the operation
notice that the string has some additional included escape characters.

https://github.com/directus/directus/assets/21194068/7593673b-2f56-4af3-ac4f-aab4af7ceed6

### Directus Version

10.5.3

### Hosting Strategy

Directus Cloud

### PR DESCRIPTION
**Pull request by azrikahar**
Currently input-code interface has the following logic to stringify JSON when the type is json or the value is object:

https://github.com/directus/directus/blob/26fb314e9734dbf158d09ffe3e560e5b625bd510/app/src/interfaces/input-code/input-code.vue#L105-L107

However it is not accounting for a specific combination of `type is json` _and_ `typeof value is string`, which is why string value such as `{{my_operation}}` is being "doubly escape quoted". Fixes #19469

The similar fix was then applied to system-raw-editor (the one used in Flows and Insights) and form-field-raw-editor. Fixes #19244

Also added a drive-by one-liner fix in form-field-raw-editor line 98 to prevent `JSON.parse` from breaking when trying to parse values such as `{{my_operation}}`.

### CODE REVIEW

File: app/src/interfaces/input-code/input-code.vue [hunk 1]
```diff
@@ -103,7 +104,12 @@ const stringValue = computed(() => {
...
-		return JSON.stringify(props.value, null, 4);
+		const valueToStringify =
+			typeof props.value === 'string' && isValidJSON(String(props.value))
+				? parseJSON(String(props.value))
+				: props.value;
+
+		return JSON.stringify(valueToStringify, null, 4);
 	}
 
 	return props.value as string;
```
Comment (br41nslug) [inline app/src/interfaces/input-code/input-code.vue:115]: Do we want to check for other valid JSON values too? `boolean`, `number` and `null` are also possibilities here in `props.values`

Comment (azrikahar) [reply app/src/interfaces/input-code/input-code.vue]: Good catch! Makes perfect sense to me 👍 seems like `null` is also handled to return an empty string in line 104, so `String(props.value)` will then cover `boolean` and `number`. Updated!

**Review by br41nslug — APPROVED** [review]

File: app/src/interfaces/_system/system-raw-editor/system-raw-editor.vue [hunk 2]
```diff
@@ -133,10 +133,20 @@ watch(
...
+
+function getStringifiedValue(value: string | object | undefined) {
+	if (unref(isObjectLike)) {
+		const valueToStringify = typeof value === 'string' && isValidJSON(String(value)) ? parseJSON(String(value)) : value;
+
+		return JSON.stringify(valueToStringify, null, 4);
+	} else {
+		return String(value ?? '');
+	}
+}
```
Comment (paescuj) [inline app/src/interfaces/_system/system-raw-editor/system-raw-editor.vue:149]: Since we're more or less using the same logic for all three interfaces, I'm wondering if we should place it in a reusable util instead.

```ts
// something like this
function getStringifiedValue(value: string | object | undefined, isObject: boolean) {
	if (isObject) {
		const valueToStringify = typeof value === 'string' && isValidJSON(String(value)) ? parseJSON(String(value)) : value;
		return JSON.stringify(valueToStringify, null, 4);
	} else {
		return String(value ?? '');
	}
}

// usage in system-raw-editor.vue like this
getStringifiedValue(newValue, unref(isObjectLike)

// usage in form-field-raw-editor.vue like this
getStringifiedValue(props.currentValue, type.value === 'object')
```

Would also make the spacing (`4` vs. `\t`) in the `JSON.stringify` calls consistent. Unless I'm missing the reason why this needs to be different 🤔

Comment (azrikahar) [reply app/src/interfaces/_system/system-raw-editor/system-raw-editor.vue]: Makes sense! Updated it to a reusable util as you described 👍

Comment (paescuj) [reply app/src/interfaces/_system/system-raw-editor/system-raw-editor.vue]: Awesome work, even with tests ❤️

**Review by paescuj — APPROVED** [review]
