### PR TITLE
Treat Decimals as Strings

### LINKED ISSUE #24741: Decimal fields bug in precision when exceeding number range
### Describe the Bug

As this issue was missed in https://github.com/directus/directus/pull/24599

When saving values for Decimal fields, the value is handled as a number instead.
As a consequence, significant digits are lost and wrong values saved.

This happens whenever a number can no longer hold all significant digits of the configured decimal. The issue is that the value is transferred as number to the backend (1234.1234) and handled as number before being saved.

When the field is returned from the backend, its send as a string ("1234.1234"), which ensures no digits are lost, and its correctly created as numeric (precision, scale) in the database itself.

### To Reproduce

Create a decimal field with significant digits exceeding the number limit, for example precision: 20, scale: 5.
Save a new value, for example 123456789123456.12345
Note that the saved value is 123456789123456.12000
Same issue occurs whenever more than 17 significant digits are used.

### Directus Version

v11.4.1, v11.5.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgresql

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

This is a continuation of https://github.com/directus/directus/pull/24599.

What's changed:

- Treat Decimals as strings in interfaces / raw values to avoid unexpected behavior when you exceed javascripts safe number.
- This also adds a warning if a numeric interface was previously used and is no longer available. This prevents it from being a breaking change. (This also applies to bigInteger fields)
  warning
- Also, two constants `APP_NUMERIC_TYPES` and `APP_NUMERIC_STRING_TYPES` are introduced to handle the change efficiently. As a bonus, if you hover over the constants, you will get a hint to give you more context why `bigInteger` and `decimal` are treated as string:
  hint

## Potential Risks / Drawbacks

- Lose number functionality, however, you gain precision and ability to actually input decimals that are larger than javascripts safe number limit.

## Review Notes / Questions

- This could affect many places (like with the bigInteger PR)

---

Fixes #24741

### CODE REVIEW

File: app/src/interfaces/slider/index.ts [hunk 1]
```diff
@@ -8,7 +9,8 @@ export default defineInterface({
 	description: '$t:interfaces.slider.description',
 	icon: 'linear_scale',
 	component: InterfaceSlider,
-	types: ['integer', 'decimal', 'float'],
+	// @ts-ignore
```
Comment (robluton) [inline app/src/interfaces/slider/index.ts:12]: would be nice to get rid of this ignore statement. Maybe add 'as const' on the end of the APP_NUMERIC_TYPES constant?

**Comment by robluton** [comment]
For existing decimal fields using the slider interface, console warnings appear. This is because the slider component expects the value prop to be [a number or null](https://github.com/directus/directus/blob/ba7fac402e84ec6239ff56eeb745f94c5126e73b/app/src/interfaces/slider/slider.vue#L4), and the value is now a string.

slider_prop_error

**Review by robluton — APPROVED** [review]
Nice! LGTM 🎸
