### PR TITLE
Fix live preview target URL with search parameters

### LINKED ISSUE #21822: LIVE Preview continually refreshes when accessed through a filtered view
### Describe the Bug

When LIVE Previewing an article (or collection item) in a pop-out window that has been accessed via a filtered view (aka bookmarks), the LIVE Preview continually refreshes the page because it is attempting to append a string to the end of the URL, but the bookmark query string gets in the way.

### To reproduce:
1. Go to a collection that has multiple items
2. Filter the view and create a bookmark
3. Access an item from the bookmark view of the collection
4. click the 👁️ to preview the article
5. click to pop out the preview into it's own window
  - The url of the pop out window should contain the bookmark query string: `http://localhost:8055/admin/content/articles/example-2?bookmark=4/preview`

### Video
https://github.com/directus/directus/assets/395641/ba216a22-7940-4c83-95b5-eeb4dad26498

**NOTE:** This works just fine when previewing an article that is not accessed through a bookmark (filtered view).

Here are the contents of my **Preview URL**
image

Here is the NextJS API file at `pages/api/draft.tsx` that redirects preview requests to my preview template
```
import { getArticle } from "../../../lib/utils"

export default async (req: any, res: any) => {
  // Check the secret and next parameters
  // This secret should only be known to this API route and the CMS
  if (req.query.secret !== process.env.PREVIEW_TOKEN) {
    return res.status(401).json({ message: "Invalid token" })
  }

  if (!req.query.slug) {
    return res.status(401).json({ message: `Missing slug ${req.query.slug}` })
  }

  const article = await getArticle(req.query.slug)

  // If the slug doesn't exist prevent draft mode from being enabled
  if (!article) {
    return res.status(401).json({ message: "Invalid article slug" })
  }

  // Enable Draft Mode by setting the cookie
  res.setDraftMode({ enable: true })

  // Redirect to the path from the fetched article
  res.redirect(`/preview/${article.slug}`)

  return
}
```

### Directus Version

10.10.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

What's changed:

- Instead of appending the `/preview` directly to the current `href` (which fails if the `href` contains search parameters or a hash) we build a new URL and append it to the `pathname` only.

## Potential Risks / Drawbacks

None

## Review Notes / Questions

- Create a collection with Preview URL and a Bookmark for that collection, observe that the `bookmark` search parameter is appended and then try to open the preview of an item in a separate tab. Before the change we entered and endless refresh loop, because instead of the preview the item itself was accessed, immediately trying to open the preview window in a new tab target (which was the open tab) and appending another `/preview` to the URL after the search parameters.

---

Fixes #21822

### CODE REVIEW

File: app/src/modules/content/routes/item.vue [hunk 1]
```diff
@@ -257,7 +257,8 @@ watch(
 			return;
 		}
 
-		const targetUrl = window.location.href + (window.location.href.endsWith('/') ? 'preview' : '/preview');
+		const targetUrl = new URL(window.location.href);
+		targetUrl.pathname += '/preview';
```
Comment (paescuj) [inline app/src/modules/content/routes/item.vue:261]: Not sure if really required, but seeing that this has been in place before and it's technically possible to access the an item via `/admin/content/{collection}/{id}/`, this feels a tad safer

```suggestion
		targetUrl.pathname += targetUrl.pathname.endsWith('/') ? 'preview' : '/preview';
```

**Review by paescuj — APPROVED** [review]
❤️

**Comment by jeremyzilar** [comment]
Thank you 🌲🌲🌲

**Comment by alexvdvalk** [comment]
I'm also seeing issues where the 'version' placeholder is not being merged in when using the popout feature in live preview. I'll wait to see if this fixes that issue too.

**Comment by hanneskuettner** [comment]
Very likely related and fixed by this PR, since this had issues with any query parameters and hashes before.
