### PR TITLE
Check original field name when aliased

### LINKED ISSUE #16203: Filter doesn't work on alias fields if any field permission filter is applied
### Describe the Bug

When i use any collection field permission, for example a field called 'questions' (a many to one field), there is no way for me to filter it through the deep global parameter. I get an error 400 permission denied.
If i enable 'all access' filters on the aliased fields start working again. Item permissions work ok in this manner.

### To Reproduce

1. Make a relational field
2. Set any field permission filter that doesn't target the relational field you want to read
3. Make an alias of that relational field
4. Try to apply any filter on that specific relational field
5. Get an error 400, permission denied.

### Errors Shown

_No response_

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

Mysql

### What browser are you using?

Chrome

### How are you deploying Directus?

Ubuntu

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #16203. When a field is aliased, the original field name should be checked instead.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by br41nslug — COMMENTED** [review]
Still running into an issue with m2o when testing `http://localhost:8055/items/collection_a?alias[tmp]=test&filter[tmp][_eq]=3` (where `test` is a m2o field).
Returns:
```json
{
    "errors": [
        {
            "message": "Invalid filter key \"tmp\" on \"collection_a\"",
            "extensions": {
                "code": "INVALID_QUERY",
                "stack": "Error: Invalid filter key \"tmp\" on \"collection_a\"\n    at validateFilterField (\\api\\src\\utils\\apply-query.ts:427:11)\n    at addWhereClauses (\\api\\src\\utils\\apply-query.ts:381:32)\n"
```

Can confirm this resolves the issue of using an alias for `o2m` with a `deep` filter.

**Review by br41nslug — APPROVED** [review]
The usage in filter directly seems to be another issue. `deep` filters work for o2m/m2o/m2m (but m2o does require accompanying `fields` to work)

**Comment by licitdev** [comment]
> The usage in filter directly seems to be another issue. `deep` filters work for o2m/m2o/m2m (but m2o does require accompanying `fields` to work)

Yes, have noticed that behaviour and have filed issue #16238. 👍

File: api/src/services/authorization.ts [hunk 1]
```diff
@@ -396,7 +397,12 @@ export class AuthorizationService {
 					for (const field of requiredPermissions[collection]) {
 						if (field.startsWith('$FOLLOW')) continue;
 						const fieldName = stripFunction(field);
-						if (!allowedFields.includes(fieldName)) {
+
+						if (collection === rootCollection && alias && alias[fieldName]) {
+							if (!allowedFields.includes(alias[fieldName])) {
+								throw new ForbiddenException();
+							}
+						} else if (!allowedFields.includes(fieldName)) {
```
Comment (rijkvanzanten) [inline api/src/services/authorization.ts:405]: Lets clean this up a hair. Couple thoughts:

- Instead of `alias`, lets call it `aliasMap`, so it's a little more obvious what it is
- The `throw` already prevents the next if block from running, so prefer:

```js
if (a === true) {
  throw x;
}

if (b === true) {
  throw y;
}
```

over

```js
if (a === true) {
  throw x;
} else {
  throw y;
}
```

- Lets combine the double nested if

```js
if (a) {
  if (b) {
    // do x
  }
}
```

to 

```js
if (a && b) {
  // do x
}
```

- lets use optional chaining: `alias && alias[fieldName]` -> `alias?.[fieldName]`

🧹

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/services/authorization.ts (hunk 1 above)
Comment (licitdev) [reply api/src/services/authorization.ts]: > * Instead of `alias`, lets call it `aliasMap`, so it's a little more obvious what it is

Definitely! 👍 

> * The `throw` already prevents the next if block from running

Thanks for the detailed examples of your preferences. It's currently done in this manner as the second block should be skipped if the top block doesn't throw, thus the else block and nested ifs. Your suggested changes should work if the top block continues instead of throwing. 🤔 
I've refactored it to be more similar to eliminate the need for two throw blocks instead.

>  * lets use optional chaining: `alias && alias[fieldName]` -> `alias?.[fieldName]`

Made use of the optional chaining when refactoring. 👍

File: api/src/services/authorization.ts [hunk 2]
```diff
@@ -396,7 +397,9 @@ export class AuthorizationService {
 					for (const field of requiredPermissions[collection]) {
 						if (field.startsWith('$FOLLOW')) continue;
 						const fieldName = stripFunction(field);
-						if (!allowedFields.includes(fieldName)) {
+						const originalFieldName = collection === rootCollection ? aliasMap?.[fieldName] ?? fieldName : fieldName;
```
Comment (rijkvanzanten) [inline api/src/services/authorization.ts:400]: Lets rework this a hair to be a little more legible

```suggestion
let originalFieldName = fieldName;

if (collection === rootCollection && aliasMap?.[fieldName]) {
  originalFieldName = aliasMap[fieldName];
}
```

Comment (rijkvanzanten) [reply api/src/services/authorization.ts:400]: ^ pseudo code

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/services/authorization.ts (hunk 2 above)
Comment (licitdev) [reply api/src/services/authorization.ts]: It's pseudo code that works perfectly! 👍

**Review by rijkvanzanten — APPROVED** [review]
