### PR TITLE
Filter system collections based on the system property

### LINKED ISSUE #21090: Directus App filters for system collections based on name 'directus_*' instead of the 'system' property
### Describe the Bug

Tables can be added via Direct DB, custom extension etc. that are named 'directus_*' and those tables are recognized in the Directus app as system collections.

### To Reproduce

1. Add a table to the DB directly named 'directus_*'
2. You will see this table recognized as a system collection in the app

### Directus Version

v10.8.3

### Hosting Strategy

Directus Cloud

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #21090

## Scope

What's changed:

- Replaced the appropriate `startsWith('directus_')` check with actual comparisons against the tables marked as systeme tables
- Came across 4 instances of the same `getAutomaticJunctionCollectionName` function, deduplicated and moved this to `utils`
- Moved the system-data yaml files from the api to a new `@directus/system-data` package which bundles the yaml's removing the need for yaml dependencies or filesystem interaction at runtime.

## Potential Risks / Drawbacks

- These checks could theoretically come with a performance hit as we're checking against arrays now instead of a simple string comparison.

## Review Notes / Questions

- I would like to lorem ipsum
- I've left the `startsWith('directus_')` in the CollectionService.createOne to still block creation of `directus_` prefixed tables behavior on the API side. Do we want to keep this check or give people the freedom to create `directus_something` tables?

### CODE REVIEW

File: packages/composables/src/use-items.ts [hunk 1]
```diff
@@ -305,3 +305,11 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery):
 		}
 	}
 }
+
+function getEndpoint(collection: string): string {
+	if (collection.startsWith('directus_')) {
```
Comment (rijkvanzanten) [inline packages/composables/src/use-items.ts:310]: This one's still using the prefix

File: sdk/src/schema/core.ts [hunk 2]
```diff
@@ -19,6 +19,29 @@ import type { DirectusUser } from './user.js';
 import type { DirectusVersion } from './version.js';
 import type { DirectusWebhook } from './webhook.js';
 
+export const CoreCollections = [
```
Comment (rijkvanzanten) [inline sdk/src/schema/core.ts:22]: I think we should make this the single source of truth for both app and api use

**Review by rijkvanzanten — DISMISSED** [review]

File: packages/composables/src/use-items.ts (hunk 1 above)
Comment (br41nslug) [reply packages/composables/src/use-items.ts:310]: mentioned this one in the review notes, but should also be fixed by creating a single source of truth in a different package 😄

**Review by jaads — APPROVED** [review]
Looks all good to me! :)

File: packages/system-data/tsconfig.json
Comment (paescuj) [inline packages/system-data/tsconfig.json:1]: Can we extend from `@directus/tsconfig`?

File: packages/system-data/vite.config.js
Comment (paescuj) [inline packages/system-data/vite.config.js:1]: Feels slightly odd to use `vite` here only because of the YAML plugin. Could we look into using `tsup` as we're doing with all other "non-frontend" packages, together with the https://github.com/luxass/esbuild-yaml plugin?

File: packages/system-data/tsconfig.json
Comment (br41nslug) [reply packages/system-data/tsconfig.json:1]: Do we have a tsconfig that matches this configuration to extend? this somewhat custom compared to the others

File: packages/system-data/vite.config.js
Comment (br41nslug) [reply packages/system-data/vite.config.js:1]: I started with `tsup` but somehow google never got to that yaml plugin, they really wanted me to use the vite plugin (always got that in my searches as it used tsup internally 😂)

File: packages/system-data/tsconfig.json
Comment (paescuj) [reply packages/system-data/tsconfig.json:1]: What needs to be custom in particular?
I think we should at least be able to extend from the `base` config: https://github.com/directus/directus/tree/main/packages/tsconfig

Comment (br41nslug) [reply packages/system-data/tsconfig.json:1]: there was some customization for vite to play well with this plugin iirc

File: app/src/modules/settings/routes/data-model/utils/get-junction-collection-name.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+		index++;
+		name = getName(index);
+	}
+
+	return name;
+
+	function getName(index: number) {
+		let name = `${collectionA}_${field}`;
+
+		if (name.startsWith('directus_')) {
```
Comment (paescuj) [inline app/src/modules/settings/routes/data-model/utils/get-junction-collection-name.ts:17]: I think we can also use `isSystemCollection` here:
```suggestion
import { isSystemCollection } from '@directus/system-data';
import { collectionExists } from './collection-exists';

export function getAutomaticJunctionCollectionName(collectionA: string, field: string) {
	let index = 0;
	let name = getName(index);

	while (collectionExists(name)) {
		index++;
		name = getName(index);
	}

	return name;

	function getName(index: number) {
		let name = `${collectionA}_${field}`;

		if (isSystemCollection(name)) {
```

**Review by paescuj — CHANGES_REQUESTED** [review]
Great work, and also nice clean-up 🥳 

I've included some minor change requests, but besides those it all works nicely! 👍 

I've tested against Data Studio as well as API, including Flows, Permissions, OpenAPI / GraphQL schema, ...

File: packages/system-data/src/fields/index.ts [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+	fields.forEach((field, index) => {
+		const systemField: FieldMeta = {
+			system: true,
+			...defaults,
+			...field,
+			collection: table,
+			sort: index + 1,
+		};
+
+		// Dynamically populate auth providers field TODO move back to the API
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply packages/system-data/src/fields/index.ts:69]: Was moved over from the API

File: packages/system-data/package.json [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+		"build": "NODE_ENV=production tsup",
+		"dev": "NODE_ENV=production tsup"
+	},
+	"devDependencies": {
+		"@directus/tsconfig": "workspace:*",
+		"@directus/types": "workspace:*",
+		"esbuild": "0.20.0",
+		"esbuild-yaml": "1.1.1",
+		"tsup": "8.0.1",
+		"typescript": "^5.2.2"
```
Comment (paescuj) [inline packages/system-data/package.json:33]: To align with other packages
```suggestion
		"tsup": "8.0.2",
		"typescript": "5.3.3"
```

File: packages/system-data/package.json [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+	"files": [
+		"dist"
+	],
+	"scripts": {
+		"build": "NODE_ENV=production tsup",
+		"dev": "NODE_ENV=production tsup"
+	},
+	"devDependencies": {
+		"@directus/tsconfig": "workspace:*",
+		"@directus/types": "workspace:*",
```
Comment (paescuj) [inline packages/system-data/package.json:29]: `@directus/types` should be a direct dependency:

```suggestion
	"dependencies": {
		"@directus/types": "workspace:*",
	},
	"devDependencies": {
		"@directus/tsconfig": "workspace:*",
```

File: packages/system-data/tsconfig.json [hunk 7]
```diff
@@ -0,0 +1,9 @@
+{
+	"extends": "@directus/tsconfig/base",
+	"compilerOptions": {
+		"module": "NodeNext",
+		"lib": ["ES2020", "DOM", "DOM.Iterable"],
```
Comment (paescuj) [inline packages/system-data/tsconfig.json:5]: Do we need the DOM?

File: packages/system-data/package.json (hunk 6 above)
Comment (br41nslug) [reply packages/system-data/package.json:29]: Thanks will have to look into resolving this dependency now with tsup so it doesnt become a transient dependency for anything relying on this system-data package.

File: packages/system-data/tsconfig.json (hunk 7 above)
Comment (br41nslug) [reply packages/system-data/tsconfig.json:5]: We'll see once the tsup config is complete

File: packages/system-data/package.json [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+		".": "./dist/index.js",
+		"./package.json": "./package.json"
+	},
+	"main": "dist/index.js",
+	"files": [
+		"dist"
+	],
+	"scripts": {
+		"build": "NODE_ENV=production tsup",
+		"dev": "NODE_ENV=production tsup"
```
Comment (paescuj) [inline packages/system-data/package.json:25]: Does this need to be `NODE_ENV=production` for dev or should we set it to `development`?
```suggestion
		"build": "NODE_ENV=production tsup",
		"dev": "NODE_ENV=development tsup"
```

**Review by paescuj — APPROVED** [review]
Great work @br41nslug 🥇

Retested with the latest changes (particularly the auth provider fields) ✅
