### PR TITLE
Use aliases for relational fields

### LINKED ISSUE #12734: Field value changes when adding multiple fields from a related collection
### Describe the Bug

In the video, we have an O2M relationship. The  "relational" field `filters_doc` can have multiple `related_values` from the `relational` Collection. Add the IDs from relational and things display fine. Add a second field from the `relational` Collection, and the ID Field values convert to a JSON.

https://user-images.githubusercontent.com/62306630/163212796-8e4db3dd-d924-42a9-b87a-62049d30340d.mov

### To Reproduce

I think I addressed it above. Am I doing this submission process right?

### Errors Shown

No

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

Cloud

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #12734

- [x] Requires #12776 to be resolved

Uses solution suggested here: https://github.com/directus/directus/issues/12734#issuecomment-1098191821

## Before

https://user-images.githubusercontent.com/42867097/163396556-8483d816-f0f2-405f-98c3-887c0be65a5b.mp4

## After

https://user-images.githubusercontent.com/42867097/163396572-260446de-d251-4d6b-bb27-c7ebde5fd52a.mp4

### CODE REVIEW

File: packages/shared/src/composables/use-items.ts [hunk 1]
```diff
@@ -137,6 +138,7 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery, f
 				params: {
 					limit: unref(limit),
 					fields: fieldsToFetch,
+					...(alias && { alias: unref(alias) }),
```
Comment (br41nslug) [inline packages/shared/src/composables/use-items.ts:141]: `alias` is extracted from the `query` parameter and is not required according to the `ComputedQuery` type so could be `undefined` im assuming.
```suggestion
...(alias ? { alias: unref(alias) } : {}),
```

Comment (azrikahar) [reply packages/shared/src/composables/use-items.ts:141]: When it's `undefined`, it should short circuit due to the `alias &&` and not attempt to add the empty alias right? or perhaps this is meant as a different scenario from what I had in mind? Just wondering since this syntax had been used in a few places 🤔

Comment (br41nslug) [reply packages/shared/src/composables/use-items.ts:141]: If it's `undefined` or any falsy value the expression will indeed short circuit to `false` but then try to unpack `...false` which would error.
image

Comment (azrikahar) [reply packages/shared/src/composables/use-items.ts:141]: Ahh finally get it! TIL

**Review by br41nslug — APPROVED** [review]
