### PR TITLE
v-table html specs issue #24091

### LINKED ISSUE #24091: v-table html specs issue
### Describe the Bug

When running in development mode, I see a Vie's recommendation about HTML Specifications for v-table that makes sense to me.

`11:04:31 PM [vite] warning: <th> cannot be child of <thead>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.
284|                    </table-header>
285|                    <thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
286|                            <th scope="colgroup" :style="{ gridColumn: fullColSpan }">
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
287|                                    <v-progress-linear v-if="loading" indeterminate />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
288|                            </th>
   |  ^^^^^^^^^
  Plugin: vite:vue
  File: /directus/app/src/components/v-table/v-table.vue`

### To Reproduce

Just run the App in Dev and the error will pass in the screen.

`pnpm --filter app dev`

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

not applicable

### PR DESCRIPTION
**Pull request by robsoncombr**
v-table html specs issue

Resolves #24091

## Scope

**File**
[app/src/components/v-table/v-table.vue](https://github.com/directus/directus/blob/v11.2.2/app/src/components/v-table/v-table.vue)

**Current code**
```
<thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
	<th scope="colgroup" :style="{ gridColumn: fullColSpan }">
		<v-progress-linear v-if="loading" indeterminate />
	</th>
</thead>

```
**Error**

`11:04:31 PM [vite] warning: <th> cannot be child of <thead>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.
284|                    </table-header>
285|                    <thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
286|                            <th scope="colgroup" :style="{ gridColumn: fullColSpan }">
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
287|                                    <v-progress-linear v-if="loading" indeterminate />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
288|                            </th>
   |  ^^^^^^^^^
  Plugin: vite:vue
  File: /directus/app/src/components/v-table/v-table.vue`
  
**Fixed code**
Need to wrap the <th> inside a <tr> element
```
<thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
	<tr>
		<th scope="colgroup" :style="{ gridColumn: fullColSpan }">
			<v-progress-linear v-if="loading" indeterminate />
		</th>
	</tr>
</thead>
```

## Potential Risks / Drawbacks

- none

## Review Notes / Questions

- none

---

Fixes #24091

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hi @robsoncombr! Thanks for your PR, and congrats on the first PR on the repo 🙂 We do require new contributors to sign the project's CLA, so if you wouldn't mind [reviewing the CLA](https://github.com/directus/directus/blob/main/cla.md) and signing it by adding your GitHub username to [the contributors.yml file](https://github.com/robsoncombr/directus/blob/fix_v-table_html_specs/contributors.yml) we can get this merged right away 🙂

File: app/src/components/v-table/v-table.vue [hunk 1]
```diff
@@ -283,9 +283,11 @@ function updateSort(newSort: Sort) {
 				</template>
 			</table-header>
 			<thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
-				<th scope="colgroup" :style="{ gridColumn: fullColSpan }">
-					<v-progress-linear v-if="loading" indeterminate />
-				</th>
+				<tr>
+					<th scope="colgroup" :style="{ gridColumn: fullColSpan }">
```
Comment (rijkvanzanten) [inline app/src/components/v-table/v-table.vue:287]:
```suggestion
				<tr :style="{ gridColumn: fullColSpan }">
					<th scope="colgroup">
```

It's the `loading-indicator` class that has the grid, so the gridColumn should be moved up to the `tr` to make sure the styling still works

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Thanks @robsoncombr ❤️ 🚀 And congrats on the first landed PR 😄
