### PR TITLE
Session token "safety window" when refreshing

### LINKED ISSUE #22360: Race condition on refresh with multiple tabs
### Describe the Bug

Currently the /refresh endpoint is called whenever a tab becomes active. There is an issue where this sometimes gets called more than once from different tabs and causes a logout to occur.

I'm not sure if this can be fixed with a time delay or a retry. 

### To Reproduce

open 2 Directus tabs in the same browser. Make sure both tabs are alongside each other.
Move one tab out and notice that one of the directus projects will be logged out.

https://github.com/directus/directus/assets/21194068/7fe70730-c50d-4c36-b53a-9a86e2d93150

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Implement a "safety window" keeping the old token active for a short amount of time to resolve in-flight requests using the previous token.

As described here https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renewal-timeout

Fixes https://github.com/directus/directus/issues/22360

## Scope

What's changed:

- Session IDs no longer get replaced on refresh but a new session ID is saved while the old one is kept for a short duration of time, the so called "safety timeout" or "grace period".
- On refresh the expired sessions for the current user will be deleted
- Adds a new column to the `directus_sessions` table used to link refreshed sessions to their successor.

## Potential Risks / Drawbacks

- Potential performance impact on the refresh endpoint where deleting the sessions
- Can impact the security if a long grace period is set

## Review Notes / Questions

- I would like to lorem ipsum
- Do we want to call the environment variable `SESSION_REFRESH_GRACE_PERIOD`?
- Is a grace period of 10seconds a good default?

### CODE REVIEW

File: api/src/services/authentication.ts [hunk 1]
```diff
@@ -409,17 +411,55 @@ export class AuthenticationService {
...
 
 		if (record.user_id) {
 			await this.knex('directus_users').update({ last_access: new Date() }).where({ id: record.user_id });
 		}
 
+		// clear expired sessions for the current user
+		await this.knex('directus_sessions')
+			.delete()
+			.where('user', '=', record.user_id)
+			.andWhere('expires', '<', new Date());
```
Comment (br41nslug) [inline api/src/services/authentication.ts:461]: Will this cause issues for large projects?

File: api/src/services/authentication.ts [hunk 2]
```diff
@@ -409,17 +411,55 @@ export class AuthenticationService {
...
-		await this.knex('directus_sessions')
-			.update({
-				token: newRefreshToken,
-				expires: refreshTokenExpiration,
-			})
-			.where({ token: refreshToken });
+		if (options?.session) {
+			if (!record.session_next) {
+				// keep the old session active for a second
+				const SAFETY_TIMEOUT = 1000;
```
Comment (br41nslug) [inline api/src/services/authentication.ts:417]: What is a good timeout for this? 🤔

File: api/src/services/authentication.ts (hunk 1 above)
Comment (paescuj) [reply api/src/services/authentication.ts:461]: Do you mean performance- or timeout-wise?

Comment (br41nslug) [reply api/src/services/authentication.ts:461]: I was thinking performance wise as i recall an issue where the clearing of sessions took a long time on a big instance since we only do that on login. I tried to limit that issue as much as possible by explicitly looking for the current users sessions not all of them.

File: api/src/services/authentication.ts (hunk 2 above)
Comment (paescuj) [reply api/src/services/authentication.ts:417]: From a safety-perspective, I think it should be acceptable to make this a bit higher (perhaps 5-10s?) to account for short delays of requests. IMO still a very small window for attacks.

Comment (br41nslug) [reply api/src/services/authentication.ts:417]: Yeah i agree, but still think it may be valuable top make configurable either way since its hard to tell how long of a timeout may be needed for huge databases/setups

Comment (paescuj) [reply api/src/services/authentication.ts:417]: Yeah, sounds good 👍

File: api/src/services/authentication.ts [hunk 3]
```diff
@@ -428,6 +440,48 @@ export class AuthenticationService {
...
+				.update({
+					expires: sessionExpiration,
+				})
+				.where({ token: newSessionId });
+
+			return;
+		}
+
+		// keep the old session active for a short period of time
+		const SAFETY_TIMEOUT = getMilliseconds(env['SESSION_SAFETY_TIMEOUT'], 5000);
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply api/src/services/authentication.ts]: yes 😄

File: .changeset/five-moons-complain.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+---
+"@directus/api": patch
+"@directus/env": patch
```
Comment (hanneskuettner) [inline .changeset/five-moons-complain.md:3]: Should these be split up into separate change sets?

File: api/src/database/migrations/20240515A-add-session-window.ts [hunk 5]
```diff
@@ -0,0 +1,13 @@
+import type { Knex } from 'knex';
+
+export async function up(knex: Knex): Promise<void> {
+	await knex.schema.alterTable('directus_sessions', (table) => {
+		table.string('next_token').nullable();
```
Comment (hanneskuettner) [inline api/src/database/migrations/20240515A-add-session-window.ts:5]: This should be of length `64`, as our `token` column is of length `64` as well[^1] (and I could not find any migrations touching that, but please double check me on that)

```suggestion
		table.string('next_token', 64).nullable();
```

[^1]: https://github.com/directus/directus/blob/6e7529ac0e7969562d2ab8387dd17dbbe62f6849/api/src/database/seeds/12-sessions.yaml#L4-L8

Comment (br41nslug) [reply api/src/database/migrations/20240515A-add-session-window.ts:5]: Good catch 😄

File: .changeset/five-moons-complain.md (hunk 4 above)
Comment (br41nslug) [reply .changeset/five-moons-complain.md:3]: I dont think thats needed in this case 😄

File: api/src/services/authentication.ts [hunk 6]
```diff
@@ -409,17 +410,28 @@ export class AuthenticationService {
...
+				})
+				.where({ token: refreshToken });
+		}
 
 		if (record.user_id) {
 			await this.knex('directus_users').update({ last_access: new Date() }).where({ id: record.user_id });
 		}
 
+		// clear expired sessions for the current user
+		await this.knex('directus_sessions')
```
Comment (ComfortablyCoding) [inline api/src/services/authentication.ts:430]: In terms of the performance impact of this can we not remove this await? That should ensure this runs outside the request/response context and should not impact response time. We can add a `.catch` to ensure no unhandled rejections

File: api/src/services/authentication.ts [hunk 7]
```diff
@@ -285,6 +285,7 @@ export class AuthenticationService {
 		const record = await this.knex
 			.select({
 				session_expires: 's.expires',
+				session_next: 's.next_token',
```
Comment (licitdev) [inline api/src/services/authentication.ts:288]: Rename for consistency.

```suggestion
				session_next_token: 's.next_token',
```

File: docs/self-hosted/config-options.md [hunk 8]
```diff
@@ -353,6 +353,7 @@ Redis is required when you run Directus load balanced across multiple containers
 | `SESSION_COOKIE_SECURE`             | Whether or not to set the `secure` attribute for the session cookie.                                                                                                                                 | `false`                   |
 | `SESSION_COOKIE_SAME_SITE`          | Value for `sameSite` in the session cookie.                                                                                                                                                          | `lax`                     |
 | `SESSION_COOKIE_NAME`               | Name of the session cookie.                                                                                                                                                                          | `directus_session_token`  |
+| `SESSION_REFRESH_GRACE_PERIOD`      | The duration where a refresh request will allow recently refreshed sessions to be used gracefully preventing race conditions in refresh calls                                                        | `10s`                     |
```
Comment (licitdev) [inline docs/self-hosted/config-options.md:356]:
```suggestion
| `SESSION_REFRESH_GRACE_PERIOD`      | The duration during which a refresh request will permit recently refreshed sessions to be used, thereby preventing race conditions in refresh calls                                            | `10s`                     |
```

File: api/src/services/authentication.ts [hunk 9]
```diff
@@ -428,6 +440,48 @@ export class AuthenticationService {
 		};
 	}
 
+	private async updateStatefulSession(
+		sessionRecord: Record<string, any>,
+		oldSessionId: string,
+		newSessionId: string,
+		sessionExpiration: Date,
+	) {
```
Comment (licitdev) [inline api/src/services/authentication.ts:448]: I think the term `ID` in the session context is misleading as  `token` is the identifier (PK) of a session. 🤔 
If accepted, this suggestion needs to be propagated to comments etc.

```suggestion
	private async updateStatefulSession(
		sessionRecord: Record<string, any>,
		oldSessionToken: string,
		newSessionToken: string,
		sessionExpiration: Date,
	) {
```

**Review by licitdev — COMMENTED** [review]
This fix resolves the issue of being logged out due to an invalid session, but I've noticed that "ghost" sessions were created, likely due to race conditions. The "ghost" sessions can't be cleared until they expire. 🤔 

`SESSION_REFRESH_GRACE_PERIOD` feels like a good name and `10s` looks to be a good default value. 👍 

## Screenshots
#### Fresh login
image

#### 12 Concurrent tabs reloaded once
image

#### 12 Concurrent tabs reloaded a few more times after fully loaded
image

File: api/src/services/authentication.ts (hunk 6 above)
Comment (br41nslug) [reply api/src/services/authentication.ts:430]: We can, however im not sure that is required considering we also await this on the `login` endpoint which cleans up all expired sessions (independent of which user is logging in) so the main delay should happen on login while this query cleans up the short "grace period" sessions created during the session itself only for the current user.

**Review by joselcvarela — CHANGES_REQUESTED** [review]
Just have a suggestion and other than that looks fine to me 👍

Have tested in `main` then moved to this `branch` for local and SSO authentication and in both cases my session was preserved.

Also have tried to open multiple tabs and all of them were logged as expected

File: api/src/services/authentication.ts [hunk 10]
```diff
@@ -429,6 +441,48 @@ export class AuthenticationService {
 		};
 	}
 
+	private async updateStatefulSession(
+		sessionRecord: Record<string, any>,
+		oldSessionToken: string,
+		newSessionToken: string,
+		sessionExpiration: Date,
+	) {
+		if (sessionRecord['session_next_token']) {
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply api/src/services/authentication.ts:450]: newSessionToken will indeed be `sessionRecord['session_next_token']` when it is set but it will also contain a [random new session token](https://github.com/directus/directus/pull/22503/files#diff-03b58901729f938551b47a9357d79ae1d0c62868265a05e8f9980d30b22c0e95R361) if that column is not set in the database. Using `newSessionToken` here would always resolve to `true` as it will always have a value.

[the remark this answers is not in the document]
Comment (licitdev) [reply api/src/services/authentication.ts:450]: I don't think so, `newSessionToken` always exists.

https://github.com/directus/directus/blob/ada0a51ecc5bef5ff2b142af9f7b16bded0918a2/api/src/services/authentication.ts#L361

[the remark this answers is not in the document]
Comment (joselcvarela) [reply api/src/services/authentication.ts:450]: Thank you for the explanation.
It makes sense now 🙏

**Review by joselcvarela — APPROVED** [review]
Looks good to me ✅

**Comment by hanneskuettner** [comment]
I wonder, do we need to account for the race condition, where two or more concurrent refreshes enter the `refresh` method?

Theoretically they both could receive a `null` value for `next_token` in the first DB call https://github.com/directus/directus/blob/783292cff424a5f823a336039493b40ce71bbb34/api/src/services/authentication.ts#L285

Then they both could race to  creating two new session that live for `SESSION_COOKIE_TTL` and updating the old session with a new, random token. This would effectively lead to one active session becoming two, both live for quite long, but one ends up being unused since only the later refresh calls cookie is retained in the client.

I think, this could be avoided by:
- Switching the update and the insert calls in the `updateStatefulSession`, so that we first try to update the existing session
- Adding a additional `whereNull('next_token')` clause to the update query, that would prevent setting the `next_token` again, if already set
- Making an additional DB query in case that race condition happened and the `next_token` was already set, retrieving the actual `next_token` in the invocation that is running slightly later in time
- Have `updateStatefulSession` return the actual `newSessionToken` that is used and move that call before creating signing the JWT

I've pushed my proposed changes to the branch `session-sliding-window-lock-out`

File: api/src/services/authentication.ts [hunk 11]
```diff
@@ -429,6 +438,63 @@ export class AuthenticationService {
...
+
+		if (updatedSession.length === 0) {
+			// Don't create a new session record, we already have a "next_token" reference
+			const { next_token } = await this.knex('directus_sessions')
+				.select('next_token')
+				.where({ token: oldSessionToken })
+				.first();
+
+			return next_token;
+		}
```
Comment (paescuj) [inline api/src/services/authentication.ts:482]: Would be perfect if we could combine that into one query, but I'm afraid there's no generic/easy way to do so cross vendor.

Example for Postgres:
```sql
UPDATE directus_sessions
SET    next_token =
       CASE
              WHEN next_token IS NULL THEN 'newSessionToken'
              ELSE next_token
       END
WHERE  token = 'oldSessionToken'
RETURNING next_token; 
```

Comment (hanneskuettner) [reply api/src/services/authentication.ts:482]: Played around with that as well, didn't arrive at a good solution that's supported across vendors. But we also need to keep in mind that that race condition where we actually do the select query is super slim and as such the amount of duplicates queries should be super small over all.

Comment (paescuj) [reply api/src/services/authentication.ts:482]: Agreed 👍

**Review by paescuj — APPROVED** [review]
