### PR TITLE
Fix falsey payload not showing in flow logs

### LINKED ISSUE #24230: Flow payload does not show up if the value is falsey
### Describe the Bug

Flow return values that are falsey do not show up in the flow logs panel.

**Operation**
CleanShot 2024-12-16 at 17 23 32@2x

**Logs that does not show the operation payload**
CleanShot 2024-12-16 at 17 24 04@2x

This is caused by this check

https://github.com/directus/directus/blob/882c1e0e36658130cf7aee393099012a74bad5a2/app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue#L189

### To Reproduce

- Create an operation that returns `0`, for example

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

What's changed:

- Check for `null` explicitly

## Potential Risks / Drawbacks

- ?

---

Fixes #24230

### CODE REVIEW

File: app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue [hunk 1]
```diff
@@ -186,7 +186,7 @@ function onToggle(open: boolean) {
 							<pre class="json selectable">{{ step.options }}</pre>
 						</v-detail>
 
-						<v-detail v-if="step.data" :label="t('payload')">
+						<v-detail v-if="step.data !== null" :label="t('payload')">
```
Comment (licitdev) [inline app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue:189]: I wonder if it should be `undefined` instead as `null` could be a returned value 🤔 

```suggestion
						<v-detail v-if="step.data !== undefined" :label="t('payload')">
```

Comment (hanneskuettner) [reply app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue:189]: We default to `null` for any undefined value above, see https://github.com/directus/directus/blob/eba1939ab4a15b3a06851a3767a3c3ec6f2e62e0/app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue#L95

Comment (ComfortablyCoding) [reply app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue:189]: Based on [L95](https://github.com/directus/directus/pull/24231/files#diff-353425b538fe82f49352f0b1fd681a2bca344da6355a529736fedc093d41343dR95) it can only ever be null or a value

**Review by licitdev — APPROVED** [review]
`0` ✅ 
image
