### PR TITLE
Fixed WYSIWYG file upload extension to use filename_disk

### LINKED ISSUE #24079: WYSIWYG interface returns .jpg extension for uploaded .jpeg files
### Describe the Bug

**Summary:**
When uploading `.jpeg` files via the default WYSIWYG interface configuration, the image URL is incorrectly saved to the field with a `.jpg` extension. This creates an inconsistency between the image URL stored in the field and the actual file extension in the storage location. 

**Expected Behavior:**
The image URL saved to WYSIWYG fields should match the file extension used in the storage location (i.e., `.jpeg` for `.jpeg` files).

**Impact:**
This bug causes issues for users who parse their HTML and adjust images src attributes to directly access the files on external storage (e.g., AWS S3), as they will encounter mismatches between the file extension in the HTML src attribute and the actual file on the server.

### To Reproduce

1. Click the Add/Edit image on a field with the default WYSIWYG interface configuration
2. Upload a file with the `.jpeg` file extension (not `.jpg`)
3. The 'Image Url' field automatically populates (and saves to the WYSIWYG field) with a `.jpg` file extension
Screenshot 2024-11-22 at 10 58 33 AM
4. Note that the `filename_disk` for the uploaded file in the File Library and the file stored on the server maintain the `.jpeg` file extension

### Directus Version

v11.2.2

### Hosting Strategy

Directus Cloud

### Database

_No response_

### PR DESCRIPTION
**Pull request by that1matt**
## Scope

What's changed:

- useImage pulls filename & file extension from `filename_disk`

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- None

---

Fixes #24079

### CODE REVIEW

File: app/src/interfaces/input-rich-text-html/useImage.ts [hunk 1]
```diff
@@ -118,11 +116,7 @@ export default function useImage(
 	}
 
 	function onImageSelect(image: File) {
-		const fileExtension = image.type
-			? readableMimeType(image.type, true)
-			: readableMimeType(mime.getType(image.filename_download) as string, true);
-
-		const assetUrl = getPublicURL() + 'assets/' + image.id + '.' + fileExtension;
+		const assetUrl = getPublicURL() + 'assets/' + image.filename_disk;
```
Comment (rijkvanzanten) [inline app/src/interfaces/input-rich-text-html/useImage.ts:119]: Even though we're not directly exposing this through the app/api, there's a world where folks have manually updated the filename_disk which means it no longer matches the `<id>.<ext>` format.. I'm wondering if we should play it safe here and make the url `'assets/' + image.id + <extension from filename_disk>`. In the assets endpoint, everything after the UUID is optional and ignored, so that should work for cases where filename_disk was manually overridden as well

Comment (that1matt) [reply app/src/interfaces/input-rich-text-html/useImage.ts]: I made the change to only pull the extension from `filename_disk`. The current change makes the assumption that the `filename_disk` will always have a file extension. If this is a bad assumption, I can extract the old functionality out, and the new functionality into a method that checks if `filename_disk` is undefined, to use the old logic check. Otherwise I can check if the file `type` is `image/jpg` and compare it against `jpg/jpeg` and return the correct value.

File: app/src/interfaces/input-rich-text-html/useImage.ts [hunk 2]
```diff
@@ -118,9 +118,7 @@ export default function useImage(
 	}
 
 	function onImageSelect(image: File) {
-		const fileExtension = image.type
-			? readableMimeType(image.type, true)
-			: readableMimeType(mime.getType(image.filename_download) as string, true);
+		const fileExtension = image.filename_disk.split('.').pop();
```
[the remark this answers is not in the document]
Comment (that1matt) [reply app/src/interfaces/input-rich-text-html/useImage.ts:119]: My bad, I am used to eslint removing unused imports. I got this fixed in the latest commit.

**Review by rijkvanzanten — DISMISSED** [review]
Thanks @that1matt! ❤️

File: app/src/interfaces/input-rich-text-html/useImage.ts (hunk 1 above)
Comment (rijkvanzanten) [reply app/src/interfaces/input-rich-text-html/useImage.ts]: Hmm good point. The filename_disk is generated as UUID + ext by default, but can theoretically be overridden during upload. That in turn means that there's no guarantee that the extension actually exists.

Comment (that1matt) [reply app/src/interfaces/input-rich-text-html/useImage.ts]: Would you like me to make an alteration to have a fallback to pull as it did previously with an additional check for `jpg/jpeg` values?

File: app/src/interfaces/input-rich-text-html/useImage.ts [hunk 3]
```diff
@@ -118,9 +116,7 @@ export default function useImage(
...
```
[the remark this answers is not in the document]
Comment (that1matt) [reply app/src/interfaces/input-rich-text-html/useImage.ts:119]: Yep, I can add a fallback to default to what it was previously, with an additional check for `jpg/jpeg` extensions.

File: app/src/interfaces/input-rich-text-html/useImage.ts (hunk 1 above)
Comment (rijkvanzanten) [reply app/src/interfaces/input-rich-text-html/useImage.ts]: I think we could do a check to see if there's a period in the filename_disk first `.includes('.')` and do the split+pop if true. Then fallback to the previous logic if not 🙂

**Review by rijkvanzanten — APPROVED** [review]
Thanks @that1matt! ❤️
