### PR TITLE
Clean-up error handler & fix message for unknown API errors

### LINKED ISSUE #22420: Error message missing in the popup dialog
### Describe the Bug

An error message should appear in the data studio popup when a flow triggers an error. Nevertheless, it actually shows the error message when I provoke an error with postman.

Data Studio:
image

Postman result:
```
{
    "data": {
        "update_report_strings_item": null
    },
    "errors": [
        {
            "message": "Validation failed: The value 'Hello World' does not match the regex pattern '^[A-HJ-NPR-Z0-9]{7}$'.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "update_report_strings_item"
            ]
        }
    ]
}
```

### To Reproduce

Create a flow, add a 'Run Script' and implement a throw Error statement.

For example:
```
module.exports = async function(data) {
    throw new Error(`Validation failed: The value '${valueToValidate}' does not match the regex pattern '${regexPattern}'.`);
    return {
        data
    };
}
```

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

- Fix broken logic to get error message of unknown errors (e.g. from a Flow) for admin users
  - Brackets were missing, which resulted in the error object itself being used as the message
  - **Example Flow**
     <table><tr><td></tr></td></table>
    <b>Before</b>
     <table><tr><td></tr></td></table>
    <b>After</b>
    <table><tr><td></tr></td></table>
- Clean-up of error handler
  - Wrap in async handler, similar to what we're using in other middleware/handlers - makes it easier to read and allows us to easily catch possible errors in the handler itself (unexpected, but would leak filesystem structure info if uncaught)
  - Add comments to reveal some of the magic happening here 🪄 
  - Reusable fallback error
  - Prevent adding undefined extensions data / stack traces to error data (in dev mode)
  - Don't use `toArray` util to transform errors - would split string errors by commas
  - Better typing
- Shared `InternalServerError`
- Add tests

## Potential Risks / Drawbacks

None

## Review Notes / Questions

None

---

Fixes #22420, partially addresses #22416

### CODE REVIEW

File: api/src/middleware/error-handler.ts [hunk 1]
```diff
@@ -1,105 +1,125 @@
...
+	for (const error of receivedErrors) {
 		if (getNodeEnv() === 'development') {
-			if (isObject(error)) {
-				error['extensions'] = {
-					...(error['extensions'] || {}),
-					stack: error['stack'],
-				};
+			// If available, expose stack trace under error's extensions data
+			if (isObject(error) && error['stack']) {
+				(error['extensions'] ??= {} as any).stack = error['stack'];
```
Comment (hanneskuettner) [inline api/src/middleware/error-handler.ts:38]: Normally I'm a fan of short handed assignments, but maybe this is more readable?

```suggestion
			if (isObject(error) && error['stack'] && (error['extensions'] === undefined || isObject(error['extensions']))) {
				error['extensions'] = {
					...error['extensions'],
					stack: error['stack'],
				}
```

**Review by hanneskuettner — COMMENTED** [review]
One minor nitpick, otherwise it looks super clean

File: api/src/middleware/error-handler.ts [hunk 2]
```diff
@@ -1,105 +1,124 @@
...
+};
 
-	const errors = toArray<unknown>(err);
+const FALLBACK_ERROR = {
+	status: 500,
+	message: 'An unexpected error occurred.',
+	extensions: {
+		code: 'INTERNAL_SERVER_ERROR',
+	},
+};
```
Comment (br41nslug) [inline api/src/middleware/error-handler.ts:24]: Could we move this error definition to the `@directus/errors` package? 😄

Comment (paescuj) [reply api/src/middleware/error-handler.ts:24]: I didn't do so because we don't need a fully fledged `DirectusError` here and `DirectusError` would expect `code` under its root, so we would have to some re-transformation.
But I agree that it would make sense to make it available to clients via `@directus/errors`.
I'll have a look 👍

Comment (br41nslug) [reply api/src/middleware/error-handler.ts:24]: Yeah exactly for extension use was my initial thinking there 😄

Comment (paescuj) [reply api/src/middleware/error-handler.ts]: Done ✅

File: api/src/middleware/error-handler.ts [hunk 3]
```diff
@@ -1,105 +1,118 @@
...
+				status = FALLBACK_ERROR.status;
 			}
 
-			payload.errors.push({
+			errors.push({
 				message: error.message,
 				extensions: {
+					// Expose error code under error's extensions data
 					code: error.code,
 					...(error.extensions ?? {}),
```
Comment (br41nslug) [inline api/src/middleware/error-handler.ts:52]:
```suggestion
				extensions: {
					...(error.extensions ?? {}),
					code: error.code,
```
Inverted the order to ensure the `error.extensions` spreading cannot overwrite the set code.

File: api/src/middleware/error-handler.ts [hunk 4]
```diff
@@ -1,105 +1,118 @@
...
+			accountability: req.accountability ?? null,
+		},
+	);
 
-export default errorHandler;
+	return res.json({ errors: updatedErrors });
+});
+
+function asyncErrorHandler(fn: ErrorRequestHandler) {
+	return (err: any, req: Request, res: Response, next: NextFunction) =>
```
Comment (br41nslug) [inline api/src/middleware/error-handler.ts:105]:
```suggestion
    // Note: keep all 4 parameters here. That's how Express recognizes it's the error handler, even if
    // we don't use next
	return (err: any, req: Request, res: Response, next: NextFunction) =>
```

Lets not forget adding back the original comment here

**Review by br41nslug — COMMENTED** [review]
Looking good, some comments I feel are unnecessary or overkill but they're not hurting anyone so I dont think those matter and would just add noise in the comments 😄

File: api/src/middleware/error-handler.ts (hunk 4 above)
Comment (paescuj) [reply api/src/middleware/error-handler.ts]: Covered via tests now 👍

File: api/src/middleware/error-handler.ts [hunk 5]
```diff
@@ -1,105 +1,118 @@
...
+		Promise.resolve(fn(err, req, res, next)).catch((error) => {
```
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/middleware/error-handler.ts]: Ah good thought! The function has initially been adapted from https://github.com/directus/directus/blob/7e6980dfdf4a09b06455ac63ae9469dcb382a81a/api/src/utils/async-handler.ts#L3-L4 but since we only use  it here in this file we know that we receive an async function, I've now dropped the `Promise.resolve` wrapping.

**Comment by sideshot** [comment]
Can we get this fixed and pushed through?

File: api/src/middleware/error-handler.ts [hunk 6]
```diff
@@ -1,105 +1,123 @@
...
+	);
 
-export default errorHandler;
+	return res.json({ errors: updatedErrors });
+});
+
+function asyncErrorHandler(
+	fn: (...args: Parameters<ErrorRequestHandler>) => Promise<any>,
+): (...args: Parameters<ErrorRequestHandler>) => Promise<ReturnType<ErrorRequestHandler>> {
+	return (err, req, res, next) =>
```
Comment (br41nslug) [inline api/src/middleware/error-handler.ts:107]: I dont necessarily think this abstraction is an improvement over my last review but it also doesnt hurt anyone 🤷 Could we however still add back the original comment that this function requires to have 4 parameters to be marked as global error handler 😄

Comment (paescuj) [reply api/src/middleware/error-handler.ts:107]: What do you mean by abstraction in particular? I just removed the `Promise.resolve` wrapping in d07bed1 since the last review. Any suggestions for improvement?
IMO, the comment is no longer necessary, as it is covered by the new tests and we now (have to) forward all parameters anyway.

**Review by br41nslug — APPROVED** [review]
Not blocking it on adding a comment 😂
