### PR TITLE
Add the ability to configure the error, bug and feature URLs

### LINKED ISSUE #17287: Allow configuring the link to "Report Error"
There's two main places in the app where the user is prompted to report an error: In unexpected error dialogs and in the Settings sidebar. For these two locations, we should allow the system admin to configure what this link does. This allows the admin to have the user notify them through email (or elsewhere) instead of having them be sent over to GitHub (where they might not have an account / aren't familiar).

The configuration should be done in Project Settings. The entered string will be used in the `href` for the report error buttons. This allows `mailto:` and other app links to be used as well. The field should accept a template string that's rendered with micromustache. The variables that should be available in the context of the template are:

- `error`: The `Error` object that caused the error dialog
- `route`: The current vue-router context
- `user`: Current user (from the userStore)
- `role`: Current role (from the roleStore)
- `navigator`: Browser's `navigator` object

This would allow the template to be something like `https://example.com/report?ua={{navigator.userAgent}}&page={{route.fullPath}}&error={{error}}`

### Discussed in https://github.com/directus/directus/discussions/17259

<div type='discussions-op-text'>

<sup>Originally posted by **u12206050** January 21, 2023</sup>
Screenshot 2023-01-21 at 10 53 07

Currently this "Report Error" button opens up an issue on the Directus repo.

Could it rather be configurable such that it opens an issue on the project's repo first, such that it could first be debugged there before involving and burdening the Directus Team with all such (possibly minor) issues?</div>

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Added the ability to configure the URLs for the following links
   - Report an error
   - Report a bug
   - Request a feature
- added a new VCollectionFieldTemplate component that acts the same as the old VFieldTemplate.

## Potential Risks / Drawbacks

- Field Template field breaks
- This is a potential breaking change on the app side as a public component (v-field-template) signature was changed. It seems to be a public component but it is not documented in our [components documentation](https://components.directus.io).

## Review Notes / Questions

- ~Should we add a new section for this in settings? or make them full width? Left them as half to be inline with project URL.~. Addressed below
- Should we be adding the default values for the fields to the DB as actual defaults or keep them in the code? At the moment it is only defaulted in the code.
   - if we do this what should be done for the null case? Hiding the tabs/buttons does not seem ideal.

### UI Sample
Screenshot 2024-03-01 at 1 05 47 PM

---

Fixes #17287

### CODE REVIEW

File: app/src/interfaces/_system/system-display-template/system-display-template.vue [hunk 1]
```diff
@@ -76,20 +78,33 @@ const injectValue = computed(() => {
...
 		<v-field-template
 			v-else
-			:collection="collection"
+			:tree="tree.list"
 			:model-value="value"
 			:disabled="disabled"
-			:inject="injectValue"
+			:load-path-level="tree.pathLoader"
 			@update:model-value="$emit('input', $event)"
 		/>
```
Comment (DanielBiegler) [inline app/src/interfaces/_system/system-display-template/system-display-template.vue:109]: Would be neat if we could include the `placeholder` pro of `v-field-template` so that it looks more consistent with the other fields together. `v-field-template` does have the ability to show placeholders:

image

The others already show the example URL. We'd need to add it to the yaml under options and pass it down.

File: app/src/components/v-collection-field-template.vue [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+			{{ t('interfaces.system-display-template.select_a_collection') }}
+		</v-notice>
+		<v-field-template
+			v-else
+			:tree="treeList"
+			:model-value="value"
+			:disabled="disabled"
+			:load-path-level="loadFieldRelations"
+			@update:model-value="$emit('input', $event)"
+		/>
```
Comment (DanielBiegler) [inline app/src/components/v-collection-field-template.vue:40]: Similar to the other mentioned `placeholder` comment

**Comment by DanielBiegler** [comment]
> Should we add a new section for this in settings? or make them full width? Left them as half to be inline with project URL.

Yeah I agree it feels like an additional "Advanced Settings" or rather "Miscellaneous" group that we could sort it into. @paescuj mentioned the same thing to me. It'd be good to keep the top level settings group rather small and sort these additional fields into their own group IMO. I think we can keep them as half-width, just under their own group that could also hold further links in the future.

File: app/src/interfaces/_system/system-display-template/system-display-template.vue (hunk 1 above)
Comment (ComfortablyCoding) [reply app/src/interfaces/_system/system-display-template/system-display-template.vue:109]: I believe I left it out until the question regarding the default value was addressed. Agreed that it makes sense either way.

File: app/src/modules/settings/components/navigation.vue [hunk 3]
```diff
@@ -63,12 +65,15 @@ const externalItems = computed(() => {
 		{
 			icon: 'bug_report',
 			name: t('report_bug'),
-			href: 'https://github.com/directus/directus/issues/new?template=bug_report.yml',
+			href:
+				settings.value?.project_bug_url ?? 'https://github.com/directus/directus/issues/new?template=bug_report.yml',
```
Comment (paescuj) [inline app/src/modules/settings/components/navigation.vue:69]: Was already like this, but I'd welcome it if we could move these URLs to `app/src/constants.ts` 😃

**Comment by ComfortablyCoding** [comment]
> > Should we add a new section for this in settings? or make them full width? Left them as half to be inline with project URL.
> 
> Yeah I agree it feels like an additional "Advanced Settings" or rather "Miscellaneous" group that we could sort it into. @paescuj mentioned the same thing to me. It'd be good to keep the top level settings group rather small and sort these additional fields into their own group IMO. I think we can keep them as half-width, just under their own group that could also hold further links in the future.

Fair point, I have updated it so the respective links are now in their own "Reporting" section. As there was only 3 and the error URL can be fairly long I have made it the last one and full width.

Screenshot 2024-03-01 at 1 05 47 PM

File: app/src/interfaces/_system/system-display-template/system-display-template.vue (hunk 1 above)
Comment (ComfortablyCoding) [reply app/src/interfaces/_system/system-display-template/system-display-template.vue]: Added via https://github.com/directus/directus/pull/21174/commits/41d308046b3cfb97802bafeb85e7305e104a9228

File: app/src/modules/settings/components/navigation.vue (hunk 3 above)
Comment (ComfortablyCoding) [reply app/src/modules/settings/components/navigation.vue]: Cleanup is always good! Done via https://github.com/directus/directus/pull/21174/commits/a9d2cb3ae2d8fc928509a1d602a9de43f702b864

**Comment by ComfortablyCoding** [comment]
I am not sure why the unit test at `src/lang/translations.test.ts` is failing. It is not due to any change in this PR as it fails on main as well. Should be ok to ignore in the context of this PR.

File: docs/reference/system/settings.md
Comment (paescuj) [inline docs/reference/system/settings.md:1]: Sorry for the nitpicking, but it would be great to have the same order of the fields everywhere (in app it's "feature", "bug", "error")

File: packages/system-data/src/fields/settings.yaml [hunk 4]
```diff
@@ -353,6 +353,134 @@ fields:
       - cast-json
     width: full
 
+  - field: reporting_divider
+    interface: presentation-divider
+    options:
+      icon: link
```
Comment (paescuj) [inline packages/system-data/src/fields/settings.yaml:359]: Can we find a more suitable icon?
I'm thinking, for example, of
- https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=feedback&selected=Material+Icons+Outlined%3Areviews%3A (more neutral, therefore I think also suitable for "feature")
- https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=commun&selected=Material+Icons+Outlined%3Afeedback%3A

File: app/src/interfaces/_system/system-display-template/system-display-template.vue [hunk 5]
```diff
@@ -76,20 +79,34 @@ const injectValue = computed(() => {
...
+const tree = computed(() => {
+	if (props.fields) {
+		return { list: props.fields };
+	}
+
+	if (collection.value === null) {
+		return null;
+	}
+
+	const { treeList, loadFieldRelations } = useFieldTree(collection, injectValue);
```
Comment (paescuj) [inline app/src/interfaces/_system/system-display-template/system-display-template.vue:92]: Can we move the composable out of the computable? Composable should generally be placed on top-level and there's no direct dependency here

File: app/src/interfaces/_system/system-display-template/system-display-template.vue [hunk 6]
```diff
@@ -76,20 +79,34 @@ const injectValue = computed(() => {
...
+	return { list: treeList.value, pathLoader: loadFieldRelations };
+});
 </script>
 
 <template>
 	<div class="system-display-template">
-		<v-notice v-if="collection === null">
-			{{ t('interfaces.system-display-template.select_a_collection') }}
+		<v-notice v-if="tree === null">
+			{{ t('interfaces.system-display-template.select_a_collection_or_tree_fields') }}
```
Comment (paescuj) [inline app/src/interfaces/_system/system-display-template/system-display-template.vue:101]: Is this message relevant to the end user? I think it should still be "Select a Collection" as this is what the user can control

File: app/src/components/v-field-template/v-field-template.vue [hunk 7]
```diff
@@ -36,13 +32,12 @@ const contentEl = ref<HTMLElement | null>(null);
 
 const menuActive = ref(false);
 
-const { collection, inject } = toRefs(props);
-const { treeList, loadFieldRelations } = useFieldTree(collection, inject);
+const { tree, loadPathLevel } = toRefs(props);
```
Comment (paescuj) [inline app/src/components/v-field-template/v-field-template.vue:35]: Not a big deal, but doesn't need to be converted to refs anymore

File: .changeset/tender-timers-develop.md [hunk 8]
```diff
@@ -0,0 +1,9 @@
+---
+'@directus/types': patch
+'docs': patch
+'@directus/api': minor
+'@directus/app': minor
```
Comment (paescuj) [inline .changeset/tender-timers-develop.md:5]: Breaking change for the app because of the changes to `v-field-template.vue`
```suggestion
'@directus/app': major
```

**Review by paescuj — DISMISSED** [review]
Nice work 🎉 Looks good to me in general. Added a few comments, afterwards it's ready for merging IMO.

File: docs/reference/system/settings.md
Comment (DanielBiegler) [reply docs/reference/system/settings.md:1]: Sure, added in https://github.com/directus/directus/pull/21174/commits/b05e9033c9f7a065bf3e29858327e42fa935ceb2

File: app/src/interfaces/_system/system-display-template/system-display-template.vue (hunk 5 above)
Comment (DanielBiegler) [reply app/src/interfaces/_system/system-display-template/system-display-template.vue]: Done :+1:

File: packages/system-data/src/fields/settings.yaml (hunk 4 above)
Comment (DanielBiegler) [reply packages/system-data/src/fields/settings.yaml]: Picked `feedback` icon, I like it.

File: app/src/interfaces/_system/system-display-template/system-display-template.vue (hunk 6 above)
Comment (DanielBiegler) [reply app/src/interfaces/_system/system-display-template/system-display-template.vue]: agreed. done.

Comment (ComfortablyCoding) [reply app/src/interfaces/_system/system-display-template/system-display-template.vue]: Agreed, although I believe that was done due to `useFieldTree` erroring if a collection is not provided.

File: app/src/interfaces/_system/system-display-template/system-display-template.vue (hunk 5 above)
Comment (ComfortablyCoding) [reply app/src/interfaces/_system/system-display-template/system-display-template.vue]: Agreed, although I believe that was done due to `useFieldTree` erroring if a collection is not provided.

**Review by DanielBiegler — APPROVED** [review]
Tested multiple scenarios and it works! 

image

Button correctly renders its templated fields, settings update nicely, etc.

**Review by paescuj — APPROVED** [review]

**Comment by robinsonjohn** [comment]
When are the "bug" and "feature" URL's shown?

**Comment by paescuj** [comment]
> When are the "bug" and "feature" URL's shown?

"Bug" and "Feature" configs take effect under the links presented in the "Settings:



The "Error" config will take effect when the App catches a unexpected error, which will be presented to the user in form of a dialog with a corresponding link:

**Comment by robinsonjohn** [comment]
@paescuj Thank you for that clarification!
