### PR TITLE
Fix related field permissions

### LINKED ISSUE #23197: Related O2M collection permissions not correctly checked
### Describe the Bug

Permissions for a `o2m` field are not properly injected from the related collection.

Originally reported here https://discord.com/channels/725371605378924594/1270371008909676599

### To Reproduce

- Create two collections, `notes` and `pinned` (with some fields, and the at least the standard `user_created` field)
- Create a m2m `pinned` in the `notes` collection to the `pinned` collection
- Create some items in `notes` with the admin account and assign new `pinned` items to the `pinned` field
- Create a new policy with full read permissions for `notes` and the following read permissions for `notes_pinned`

```json
{
    "_and": [
        {
            "pinned_id": {
                "user_created": {
                    "id": {
                        "_eq": "$CURRENT_USER"
                    }
                }
            }
        }
    ]
}
```

- Create a user with the policy
- Query the `notes` collection as follows `/items/notes?alias[counter]=count(pinned)&fields=pinned,counter`

You will see the assigned pinned items and their count, even though they were not created by the user requesting the items 

### Directus Version

v11.0.0-rc.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by hanneskuettner**
Instead of skipping over the full AST node if the field is allowed (in a policy that does not have a filter), only skip the `whenCase` injection, but still process the AST children. Otherwise the permissions of the related collection are not correctly injected into the `cases` of the AST child. But those are necessary for the related query that is run based on the AST.

---

Fixes #23197

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: api/src/permissions/modules/process-ast/lib/inject-cases.ts [hunk 1]
```diff
@@ -48,8 +44,12 @@ function processChildren(
 			throw new Error(`Cannot extract access permissions for field "${fieldKey}" in collection "${collection}"`);
 		}
 
-		// Global and field can't both be undefined as per the error check prior
-		child.whenCase = [...(globalWhenCase ?? []), ...(fieldWhenCase ?? [])];
+		// If there's one or more permissions that allow full access to this field, we can safe some
+		// query perf overhead by ignoring the whole case/when system
```
Comment (paescuj) [inline api/src/permissions/modules/process-ast/lib/inject-cases.ts:48]: I'd probably slightly adjust this comment, for example as follows, as the conditions have now been reversed
```suggestion
		// The case/when system only needs to take place if no full access is given on this field,
		// otherwise we can skip and thus safe some query perf overhead
```

**Review by licitdev — APPROVED** [review]
Works well in my test! 🚀

**Review by paescuj — APPROVED** [review]
