### PR TITLE
Load relational data from api on button-links

### LINKED ISSUE #17837: Buttom Links: in the link using data from referenced objects does not work
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I would like to create a buttom link that uses data from my own collection and data from a many-to-one relationship. in designer mode, both can be selected correctly for the configuration of the buttom link.

Problem: 
In the user view, only the data from the own colltection is pulled correctly. the data from the many-to-one relationship is empty. 

### To Reproduce

create two collections with many to one
add a buttom link which uses data from own collection and the referenced collection

The url ist not generated properly - the data from the refrenced collection is empty

### Hosting Strategy

Directus Cloud

### PR DESCRIPTION
**Pull request by Nitwel**
Before, you where able to select relational fields of an item to insert but we didn't fetch that data from the api and only relied on the data that was already existing. Could be a very old side effect of the relational rework.

Fixes #17837, fixes ENG-824

### CODE REVIEW

**Review by freekrai — APPROVED** [review]

File: app/src/interfaces/presentation-links/presentation-links.vue [hunk 1]
```diff
@@ -28,35 +32,62 @@ type Link = {
...
+
+	return {
+		fields: Array.from(fields),
+	} as Query;
+});
+
+const { item } = useItem(collection, primaryKey, query);
+const { fields } = useCollection(collection);
+
+const RELATIONAL_TYPES = ['file', 'files', 'm2o', 'o2m', 'm2m', 'm2a', 'presentation', 'translations', 'group'];
```
Comment (rijkvanzanten) [inline app/src/interfaces/presentation-links/presentation-links.vue:64]: This should use an existing `const`, or make this a shared `const` if it doesn't exist yet

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
