### PR TITLE
Fix condition to translate directus collections

### LINKED ISSUE #9227: Page not found when trying to edit an item with a "collection" property
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a collection called "products" and another one called "collections". These two collections are related (a product has one collection).

When trying to access a product (click on it to edit the item), the "page not found" error is shown. 

### To Reproduce

Create two Directus collections:

- collections
- products

Create a "collections" item and a product. Try to access the product again.

### Errors Shown

No error is shown in the console nor from the API but I tried to debug it and found that the error is cause by an hard check on the collection attribute:

image

image

I know it's minified code but it looks like this middleware:

https://github.dev/directus/directus/blob/037fbd231af76fb5246c458018c311fdf29b3460/api/src/middleware/collection-exists.ts#L19

I think a simple fix would to replace this line:

```ts
if (!req.params.collection) return next();
```

by this one (or something similar to test the string type):

```ts
if (!req.params.collection || typeof req.params.collection !== 'string') return next();
```

### What version of Directus are you using?

RC 99

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres 11

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally and on Render.com

### PR DESCRIPTION
**Pull request by paescuj**
Only do the `startsWith` check if the `collection` field is a string - otherwise this fails on items having a field called "collection" (for example a relation to a collection called `Collections`, see issue #9227).

Fixes #9227

### CODE REVIEW

File: app/src/composables/use-item/use-item.ts [hunk 1]
```diff
@@ -292,7 +292,7 @@ export function useItem(collection: Ref<string>, primaryKey: Ref<string | number
 	}
 
 	function setItemValueToResponse(response: AxiosResponse) {
-		if (response.data.data.collection?.startsWith('directus_')) {
+		if (typeof response.data.data.collection === 'string' && response.data.data.collection.startsWith('directus_')) {
```
Comment (rijkvanzanten) [inline app/src/composables/use-item/use-item.ts:295]: Right now we're relying on the "collection" field being returned in the data for the item. Shouldn't we instead just use the collection-to-fetch information available in `collection.value` ?

```suggestion
		if (collection.value?.startsWith('directus_')) {
```

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/composables/use-item/use-item.ts (hunk 1 above)
Comment (paescuj) [reply app/src/composables/use-item/use-item.ts:295]: I don't think we can since the value of `collection.value` is `directus_collections` for all collections in data model (even for non-directus collections).

Comment (rijkvanzanten) [reply app/src/composables/use-item/use-item.ts:295]: Ohhhhhhh yeah I forgot this is for directus_collections specifically ^^

In that case, lets make it more explicit and add a check for whether or not we're in directus_collections before trying to read the returned collection 👍🏻 

```suggestion
		if (collection.value === 'directus_collections' && response.data.data.collection?.startsWith('directus_')) {
```

Comment (paescuj) [reply app/src/composables/use-item/use-item.ts]: Makes sense! 👍 Have tested this!

**Review by rijkvanzanten — APPROVED** [review]
