### PR TITLE
Separate caching of dynamic user vars from permissions

### LINKED ISSUE #9933: Permissions cache includes dynamic user variables
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using dynamic user variables in permissions, the fetched dynamic variables are included in the permissions cache, meaning that you have to flush the permissions cache by changing the permissions in order to pull in the latest dynamic user variables. The dynamic variables should be fetched dynamically, and should be cached in the user-data cache instead (so it's purged on content change, rather than permissions change).

### To Reproduce

Use dynamic variables in permissions, change the data that's used in the permissions, note outdated permissions.

### Errors Shown

_No response_

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

17

### What database are you using?

Postgres 13

### What browser are you using?

Safari

### What operating system are you using?

macOS Big Sur

### How are you deploying Directus?

Locally

### PR DESCRIPTION
**Pull request by licitdev**
Closes #9933.

The permissions are now cached based on role in `systemCache`.

The dynamic user variables are cached in `cache` per user when `CACHE_ENABLED` is `true`.

The `cache` is cleared upon create, update, and delete actions on items when `CACHE_AUTO_PURGE` is `true`.

On a side note, the caching may not be efficient if users are using the app when `CACHE_AUTO_PURGE` is `true`. The `cache` is cleared on every page navigation due to an `update` being performed in `/users/me/track/page`. However, that is the intended behaviour in case someone requires to use `$CURRENT_USER.last_page` in permissions.

### Functions extracted
1. `parsePermissions()` to parse and extract required dynamic fields
2. `getFilterContext()` to fetch dynamic fields only when necessary
3. `processPermissions()` to process the filters with the filterContext

### CODE REVIEW

File: api/src/utils/get-permissions.ts [hunk 1]
```diff
@@ -24,7 +24,35 @@ export async function getPermissions(accountability: Accountability, schema: Sch
 		const cachedPermissions = await systemCache.get(cacheKey);
 
 		if (cachedPermissions) {
-			return cachedPermissions;
+			if (cachedPermissions.containDynamicData) {
```
Comment (azrikahar) [inline api/src/utils/get-permissions.ts:27]: Maybe we can do early returns like

```js
if (!cachedPermissions.containDynamicData) {
    return processPermissions(accountability, cachedPermissions.permissions, {});
}
```

and the other if elses when applicable to reduce some nestings here. Just a thought, not really important 😄

**Review by azrikahar — APPROVED** [review]
LGTM!

File: api/src/utils/get-permissions.ts (hunk 1 above)
Comment (licitdev) [reply api/src/utils/get-permissions.ts:27]: Agreed! Will refactor it soon! Thanks for the tip~ 😁

**Review by rijkvanzanten — APPROVED** [review]
