### PR TITLE
Remove UTC conversion from date, time and datetime fields

### LINKED ISSUE #7383: Date interface is displaying 1 day before
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

So this is interesting, every date field is showing 1 day before. So if I select today 12 August 2021 as a date in the system and save it, when I view the data I see 11 August 2021, but if I check the DB, the correct date is saved there. 

https://user-images.githubusercontent.com/9326922/129262257-e359d84e-7297-4fe7-b11d-44534bc43ce0.mp4

### To Reproduce

Create a date field and enter a specific date, save and view the record. Also, check your DB.

### What version of Directus are you using?

RC.90

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution and MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Locally & Windows Server 2019 (Production)

### PR DESCRIPTION
**Pull request by licitdev**
Closes #7383.

The conversion to UTC prior to persisting led to issues when using `date`, `time` and `datetime` fields.

Only `timestamp` fields will contain timezone information.
`date`, `datetime` and `time` fields will not contain timezone information.

Servers should run in UTC timezone. 
Database timezone should be in the UTC.
Inconsistencies that occur when running in different timezones:
MySQL / MariaDB (Read & Write)
MSSQL (Write)

Oracle does not have a `time` field within the database. 
It remains unchanged, where a `datetime` field would be created instead.

This PR fixes the inconsistencies. The data sent and received across different node timezones should now be consistent.

### Main Changes
- [x] Remove UTC conversion from `date`, `time` and `datetime` fields
- [x] Add sequential tests
- [x] Add node timezone tests
- [x] Update date helpers to read/write the values
- [x] Add flags for field type conversion
- [x] Add tests for `date-created` and `date-updated` field flags

### Other Notes
- `timestamp` fields in `MariaDB` has to be `nullable()` when creating field in Knex migrations, else a default create and update will be added.

### CODE REVIEW

File: api/src/services/payload.ts [hunk 1]
```diff
@@ -132,6 +132,19 @@ export class PayloadService {
...
+				if (typeof value === 'string' && value.length > 19) {
+					const newDate = new Date(value);
+					return new Date(newDate.getTime() - newDate.getTimezoneOffset() * 60 * 1000).toISOString().split('Z')[0];
+				}
+			}
+			return value;
+		},
+		async 'oracle-datetime-in-timestamp'({ value }) {
+			return value;
+		},
```
Comment (rijkvanzanten) [inline api/src/services/payload.ts:147]: Lets remove the database specific overrides in favor of a note in the docs explaining that there's no difference between timestamp/datetime in SQLite 👍🏻

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Lets reduce the database specific logic in our codebase, other than that, LGTM!

File: api/src/services/payload.ts (hunk 1 above)
Comment (licitdev) [reply api/src/services/payload.ts]: Done. Thanks!

File: api/src/services/payload.ts [hunk 2]
```diff
@@ -261,6 +261,15 @@ export class PayloadService {
 	processDates(payloads: Partial<Record<string, any>>[], action: Action): Partial<Record<string, any>>[] {
 		const fieldsInCollection = Object.entries(this.schema.collections[this.collection].fields);
 
+		// Update specific database type overrides
+		for (const [_name, field] of fieldsInCollection) {
+			if (field.special.includes('sqlite-timestamp-in-datetime')) {
```
Comment (rijkvanzanten) [inline api/src/services/payload.ts:266]: Lets drop the database specific names from these types. We could just rename those flags from `sqlite-timestamp-in-datetime` to `cast-timestamp` and `cast-datetime` respectively. We should do the same thing for the other casting types (`cast-boolean`, `cast-json` etc)

File: api/src/services/collections.ts [hunk 3]
```diff
@@ -98,6 +98,32 @@ export class CollectionsService {
...
+						if (!field.meta) {
+							field.meta = {
+								special: [flag],
+							} as FieldMeta;
+						} else if (!field.meta.special) {
+							field.meta.special = [flag];
+						} else {
+							field.meta.special.push(flag);
+						}
+					};
```
Comment (rijkvanzanten) [inline api/src/services/collections.ts:111]: Lets move this into a shared util function (it's reused in fields)

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
One more tiny tweak, and we're ready to go on this @licitdev 🙂

File: api/src/services/payload.ts (hunk 2 above)
Comment (licitdev) [reply api/src/services/payload.ts]: @rijkvanzanten Done for `cast-timestamp` and `cast-datetime`.
Changing the existing flags will require an update to the DB itself.
So should the following exhaustive list be updated?
`uuid` => `cast-uuid`
`boolean` => `cast-boolean`
`json` => `cast-json`
`csv` => `cast-csv`

https://github.com/directus/directus/blob/59a72984bfb275204b0bb69368c9e24689fb5a88/api/src/services/payload.ts#L59-L134

File: api/src/services/collections.ts (hunk 3 above)
Comment (licitdev) [reply api/src/services/collections.ts]: Done. Thanks! 🙌🏼

File: api/src/services/payload.ts (hunk 2 above)
Comment (rijkvanzanten) [reply api/src/services/payload.ts]: > So should the following exhaustive list be updated?

Yes, but lets do that in a different PR / cycle 🙂

File: api/src/services/collections.ts [hunk 4]
```diff
@@ -98,6 +99,20 @@ export class CollectionsService {
...
+							if (field.type === 'timestamp') {
+								addFieldFlag(field, 'cast-timestamp');
+							}
+							break;
+						case 'oracle':
+							if (field.type === 'dateTime') {
+								addFieldFlag(field, 'cast-datetime');
+							}
+							break;
+					}
```
Comment (rijkvanzanten) [inline api/src/services/collections.ts:114]: Can we abstract this away some more so we don't have to end up with "if db == 'x'" in more places in the codebase 🤔 

Maybe we can put it in one of those helpers, where it's like 

```js
addFieldFlag(helper.fieldFlagForField(field));
```

that way we don't have to do these explicit checks 🤔

Comment (licitdev) [reply api/src/services/collections.ts]: Great idea. Done. Thank you!

File: api/src/services/payload.ts (hunk 2 above)
Comment (licitdev) [reply api/src/services/payload.ts]: @rijkvanzanten  Oh dear, I've added the following into this PR, should I undo and extract to another PR?

> `uuid` => `cast-uuid`
> `boolean` => `cast-boolean`
> `json` => `cast-json`
> `csv` => `cast-csv`
> `hash` => `cast-hash`

Added the `hash` type into the list too.
`geometry` is left untouched as it is using field types like `geometry.Point` and `geometry.LineString`.

**Comment by abdonrd** [comment]
Has this been discarded from the next version, right?

**Comment by rijkvanzanten** [comment]
@abdonrd I'll do another review today before pushing 9.6, we've already done a couple feedback cycles on this one, so hopefully it's all good to go now 🤞🏻

File: api/src/services/fields.ts [hunk 5]
```diff
@@ -238,6 +247,20 @@ export class FieldsService {
...
+				if (field.type === 'timestamp') {
+					addFieldFlag(field, 'cast-timestamp');
+				}
+				break;
+			case 'oracle':
+				if (field.type === 'dateTime') {
+					addFieldFlag(field, 'cast-datetime');
+				}
+				break;
+		}
```
Comment (rijkvanzanten) [inline api/src/services/fields.ts:262]: Missed a place to use the helpers

File: api/src/services/payload.ts [hunk 6]
```diff
@@ -261,6 +261,15 @@ export class PayloadService {
...
 		const fieldsInCollection = Object.entries(this.schema.collections[this.collection].fields);
 
+		// Update specific database type overrides
+		for (const [_name, field] of fieldsInCollection) {
+			if (field.special.includes('cast-timestamp')) {
+				field.type = 'timestamp';
+			} else if (field.special.includes('cast-datetime')) {
+				field.type = 'dateTime';
+			}
+		}
```
Comment (rijkvanzanten) [inline api/src/services/payload.ts:271]: I'm wondering if this should happen further upstream. I believe there's already a function in get-schema that parses the type:

https://github.com/directus/directus/blob/e2eb2801c5884b5170af93c0cbb715aae11b80d7/api/src/utils/get-schema.ts#L134

so these cast flags should be instead of in the methods:

https://github.com/directus/directus/blob/e2eb2801c5884b5170af93c0cbb715aae11b80d7/api/src/utils/get-local-type.ts#L117-L125

Comment (rijkvanzanten) [inline api/src/services/payload.ts:271]: I'm wondering if this should happen further upstream. I believe there's already a function in get-schema that parses the type:

https://github.com/directus/directus/blob/e2eb2801c5884b5170af93c0cbb715aae11b80d7/api/src/utils/get-schema.ts#L134

so these cast flags should be instead of in the methods:

https://github.com/directus/directus/blob/e2eb2801c5884b5170af93c0cbb715aae11b80d7/api/src/utils/get-local-type.ts#L117-L125

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Reaching nitpicking territory, but 2 more tiny tweaks and it's _really_ done! 😄

File: api/src/services/fields.ts (hunk 5 above)
Comment (licitdev) [reply api/src/services/fields.ts:262]: Yes, missed it. 🙈 Thank you!

File: api/src/services/payload.ts (hunk 6 above)
Comment (licitdev) [reply api/src/services/payload.ts]: Agreed, it's better to be done upstream as the field type will be correct within the schema. It's clearer to be alongside other typecasting field flags too. Thanks @rijkvanzanten! 🙌🏼

Comment (licitdev) [reply api/src/services/payload.ts]: Duplicate comment, resolved~ 🤓

**Review by rijkvanzanten — APPROVED** [review]

**Comment by kk0x03** [comment]
I would like to ask why the server time zone should be UTC
