### PR TITLE
Translate field names in collection dialog

### LINKED ISSUE #18696: Collection folder translation field name is incorrect
### Describe the Bug

image

### To Reproduce

1. Go to Settings -> Data Model
2. Click 'Create Folder'
3. Open the side panel by click 'Create New' Translations
4. the field label of 'Enter a translation' is incorrect

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by br41nslug**
The translation string `"$t:key.to.translation"` was getting formatted before getting translated.

**Before:**
image

**After:**
image

Fixes #18696

### CODE REVIEW

**Review by paescuj — DISMISSED** [review]

File: app/src/interfaces/list/list.vue [hunk 1]
```diff
@@ -168,9 +168,10 @@ const defaults = computed(() => {
 
 const fieldsWithNames = computed(() =>
 	props.fields?.map((field) => {
+		const name = field.name ?? field.field!;
 		return {
 			...field,
-			name: formatTitle(field.name ?? field.field!),
+			name: name.startsWith('$t:') ? name : formatTitle(name),
```
Comment (licitdev) [inline app/src/interfaces/list/list.vue:174]: Should we translate the name prior to `formatTitle()`?

Comment (paescuj) [reply app/src/interfaces/list/list.vue:174]: I don't think so. The `formatTitle()` call is intended for field names only because there you cannot use spaces and so on. On the other hand, translations should already be formatted correctly.
We could however limit the `startsWith('$t:')` check to `field.name` only...

For the context:
Screenshot 2023-05-25 at 09 15 30

**Review by licitdev — CHANGES_REQUESTED** [review]
I think we should fix this issue at `collection-dialog.vue` instead of this implementation.

Set `name: t('language')` and `name: t('field_options.directus_collections.collection_name'),` in:

https://github.com/directus/directus/blob/101ec6649d064164509aa0cfbc52f3fe1c2357ef/app/src/modules/settings/routes/data-model/collections/components/collection-dialog.vue#L31-L54

Here's an implementation that uses `<interface-list>` which translates the strings via this manner.

https://github.com/directus/directus/blob/101ec6649d064164509aa0cfbc52f3fe1c2357ef/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-conditions.vue#L25-L49

**Review by paescuj — APPROVED** [review]

**Review by azrikahar — APPROVED** [review]

**Review by licitdev — APPROVED** [review]
YES~ 🚀
