### PR TITLE
Fix `npm init directus-extension`

### LINKED ISSUE #18183: Unable to run `npm init directus-extension`; Inquirer no-default-import
### Describe the Bug

When executing `$ npm init directus-extension`, the command fails with a `SyntaxError`.

```sh
file:///home/cevans/.npm/_npx/9ea216cce9aeac9a/node_modules/create-directus-extension/lib/index.js:4
import { inquirer } from 'inquirer';
         ^^^^^^^^
SyntaxError: Named export 'inquirer' not found. The requested module 'inquirer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'inquirer';
const { inquirer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.13.0
```

### To Reproduce

1. Install Node.js 18.x
2. Run Command; `$ npm init directus-extension`
3. Observe Error

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #18183

### CODE REVIEW

File: packages/extensions-sdk/src/cli/utils/get-template-path.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
-import path from 'path';
+import { dirname, resolve } from 'node:path';
+import { fileURLToPath } from 'node:url';
 
 export default function getTemplatePath(): string {
-	return path.resolve(__dirname, '..', '..', '..', '..', 'templates');
+	return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'templates');
```
Comment (azrikahar) [inline packages/extensions-sdk/src/cli/utils/get-template-path.ts:5]: This resolves the `ReferenceError: __dirname is not defined` error as `__dirname` doesn't readily exist in ESM compared to CJS. This solution references how it's being resolved in the API in:

https://github.com/directus/directus/blob/c301cfbc82d1ce3ba8dad56800552c4899895b6e/api/src/extensions.ts#L68

File: packages/create-directus-extension/lib/index.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 #!/usr/bin/env node
 'use strict';
 
-import { inquirer } from 'inquirer';
+import inquirer from 'inquirer';
```
Comment (azrikahar) [inline packages/create-directus-extension/lib/index.js:4]: This resolves the primary issue faced by #18183. This refers how it's imported in the API since both are also in ESM (although our current inquirer version is not ESM):

https://github.com/directus/directus/blob/c301cfbc82d1ce3ba8dad56800552c4899895b6e/api/src/cli/commands/schema/apply.ts#L4

**Review by rijkvanzanten — APPROVED** [review]
