### PR TITLE
Remove invalid `item_duplication_fields` paths on field delete 

### LINKED ISSUE #23923: Fields deleted from collection model remain in item_duplication_fields and break "Save as Copy"
### Describe the Bug

If a collection field got checked for duplication and is being deleted from the collection model - it (since ever) remains in `item_duplication_fields` in `directus_collections`.

The new strictness (v11.x.x ?) of the API is blocking requests for non-existing fields and now causes an issue.
It breaks "Save as Copy" as long as deleted fields are left in `item_duplication_fields` and are added to the request.

Error:
```
message: "You don't have permission to access field \"test\" in collection \"test\" or it does not exist. Queried in root."
```

### To Reproduce

- Create a collection
- Create 2 input fields (A & B)
- Select field A for duplication (item duplication fields)
- Delete field A from the collection model
(!) Note that the deleted field does not appear visually in duplication fields anymore
- Check DB or click "edit raw" at item duplication fields and find the deleted field A still exists in the json

Switch to content section and the collection
- Create an item and save it
- Now edit this item and do a change in field B
- Click "Save as Copy" (check request in browsers network tab)

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres 15

### LINKED ISSUE #24496: CollectionsService.deleteOne() doesn't use fieldsService to delete fields
### Describe the Bug

The CollectionsService uses the fieldsService to create the new fields of the collection:
https://github.com/directus/directus/blob/7a903838264e5a0f47baa1f1641400986de70702/api/src/services/collections.ts#L127-L135

However at deleteOne it directly deletes the fields:
https://github.com/directus/directus/blob/7a903838264e5a0f47baa1f1641400986de70702/api/src/services/collections.ts#L614-L620

As a result the `fields.create` filter is called on collection-creation too, while `fields.delete` won't be called on collection.delete.

### To Reproduce

1. Add the following filter and create a collection with some fields. The field-filter will be triggered. 
2. Next delete the collection and the filter won't be triggered.

```js
filter('fields.create', async (payload, meta, context) => {
	console.log('CREATE field');
	return payload;
});

filter('fields.delete', async (payload, meta, context) => {
	console.log('DELETE field');
	return payload;
});
```

### Directus Version

v11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- On field removal or collection deletion we now update all `item_duplicate_fields` for all related collections
- We now emit the `fields.delete` event on `collections.delete`

## Potential Risks / Drawbacks

- Updating an `item_duplication_fields` that was not effected
- Additional processing time on field deletes for large relational structures

## Review Notes / Questions

- None

---

Fixes #23923
Fixes #24496

### CODE REVIEW

File: packages/system-data/src/collections/index.ts [hunk 1]
```diff
@@ -15,5 +15,7 @@ export const systemCollectionNames: string[] = (systemData['data'] as DataCollec
 );
 
 export function isSystemCollection(collection: string): boolean {
+	if (!collection.startsWith('directus_')) return false;
```
Comment (Nitwel) [inline packages/system-data/src/collections/index.ts:18]: Not sure about this check, feels like there is something underlying going wrong that we should look to fix instead.

**Review by Nitwel — CHANGES_REQUESTED** [review]

File: api/src/services/fields.ts [hunk 2]
```diff
@@ -641,6 +642,201 @@ export class FieldsService {
 		}
 	}
 
+	private async collectionMetaUpdates(collection: string, field: string) {
```
[the remark this answers is not in the document]
Comment (Nitwel) [reply api/src/services/fields.ts:645]: Let's do that together today. 🙂

File: packages/system-data/src/collections/index.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply packages/system-data/src/collections/index.ts:18]: Nothing was wrong with the original function, this addition was done to speed up lookup time for non directus collections.

**Review by Nitwel — DISMISSED** [review]
Not sure what is meant by the TODO's but the code turned out nicely and I tested it against the issue and that seems to be properly fixed so this is ready to be merged for me after you finish your TODO's. 😄👍

File: api/src/services/collections.ts [hunk 3]
```diff
@@ -617,7 +620,24 @@ export class CollectionsService {
...
+							filter: {
+								collection: { _eq: collectionKey },
+							},
+						},
+						{
+							bypassEmitAction: (params) =>
+								opts?.bypassEmitAction ? opts.bypassEmitAction(params) : nestedActionEvents.push(params),
+						},
+					);
+
```
Comment (Nitwel) [inline api/src/services/collections.ts:640]: What's the benefit of using the the ItemsService here instead of deleting the proper `directus_fields` directly?

Comment (Nitwel) [reply api/src/services/collections.ts:640]: Ah, I'm guessing this is related to
> We now emit the fields.delete event on collections.delete

right?
In that case this is good to go, if I'm incorrect though, please let me know.

**Review by Nitwel — APPROVED** [review]

File: api/src/services/collections.ts (hunk 3 above)
Comment (ComfortablyCoding) [reply api/src/services/collections.ts:640]: Yes, this is to ensure we emit the `fields.delete` event when the records are removed.

**Comment by ComfortablyCoding** [comment]
Blackbox failures can be disregarded as they are due to https://github.com/directus/directus/pull/24718
