### PR TITLE
Fix websocket subscription filtering

### LINKED ISSUE #19704: Realtime subscription filter/item property not working properly
### Describe the Bug

The `filter` is not working for me either, in the sense that the subscription is receiving events for items out of the scope defined by the filter.

My code:
```
    connection.send(
        JSON.stringify({
            type: 'subscribe',
            collection,
            query: {         
                filter: {
                    id: {
                        _eq: "680aed0b-457d-47b1-b6ed-dcbc63aebd1e"
                    }
                },            
                fields: ['*'] 
            },
            uid: collection
        })
    );
```

Init response:
```
{
    "event": "onmessage",
    "data": {
        "type": "subscription",
        "event": "init",
        "data": [
            {
                "id": "680aed0b-457d-47b1-b6ed-dcbc63aebd1e",
                "user": "4d43e55e-8e62-4959-a953-b1e178952b25",
                "status": "active",
                "date_closed": null,
                "date_created": "2023-09-15T15:47:44.693Z",
                "date_updated": null
            }
        ],
        "uid": "sessions"
    }
}
```

Subsequent message upon activity:
```
{
    "event": "onmessage",
    "data": {
        "type": "subscription",
        "event": "delete",
        "data": [
            "fd92b2ad-9112-4d69-b84f-52717b810643"
        ],
        "uid": "sessions"
    }
}
```

As seen in the above example, the subscription has received an event for an item, for which it's not subscribed!

After suggestion by @br41nslug , i added the `item` property, like so:
```
connection.send(
        JSON.stringify({
            type: 'subscribe',
            collection,
            query: { 
                fields: ['*'] 
            },
            item: <primary key>,
            uid: collection
        })
    );
```

Subsequently, upon creating/updating/deleting any other item in the collection, the subscription receives the event, which it shouldn't.

Additionally, the event payload doesn't contain the triggering item's data. It just includes the data of the subscribing item:
```
{
    "event": "onmessage",
    "data": {
        "type": "subscription",
        "event": "create",
        "data": {
            "id": "30c60aa9-a902-43a0-a17e-f6a34cf1a55b",
            "user": "4d43e55e-8e62-4959-a953-b1e178952b25",
            "status": "active",
            "date_closed": null,
            "date_created": "2023-09-15T16:02:55.130Z",
            "date_updated": null
        },
        "uid": "sessions"
    }
}

{
    "event": "onmessage",
    "data": {
        "type": "subscription",
        "event": "delete",
        "data": {
            "id": "30c60aa9-a902-43a0-a17e-f6a34cf1a55b",
            "user": "4d43e55e-8e62-4959-a953-b1e178952b25",
            "status": "active",
            "date_closed": null,
            "date_created": "2023-09-15T16:02:55.130Z",
            "date_updated": null
        },
        "uid": "sessions"
    }
}
```

### To Reproduce

.

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #19704 

## What changed
- merged the `getSinglePayload` and `getMultiPayload` functions for better consistency in the returned payloads with `filter` and `item`

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by br41nslug** [comment]
Setting this to draft so it doesnt get merged with blackbox errors.

File: api/src/websocket/utils/items.ts [hunk 1]
```diff
@@ -157,13 +141,23 @@ export async function getItemsPayload(
...
+
+	switch (event?.action) {
+		case undefined:
+			return await service.readByQuery(query);
+		case 'create':
+			return await service.readMany([event.key], query);
+		case 'update':
+			return await service.readMany(event.keys, query);
+		case 'delete':
+			return event.keys;
```
Comment (licitdev) [inline api/src/websocket/utils/items.ts:161]: Should we add a default case here to cover for potential addition of event actions?

File: api/src/websocket/utils/items.ts [hunk 2]
```diff
@@ -98,20 +60,31 @@ export async function getMultiPayload(
...
-		return await service.readByQuery();
-	} else if (event.action === 'create') {
-		return await service.readMany([String(event.key)]);
-	} else if (event.action === 'delete') {
-		return event.keys;
-	} else {
-		return await service.readMany(event.keys.map((key: any) => String(key)));
+	if ('item' in subscription) {
+		if (event?.action === 'delete') {
+			// return only the subscribed id in case a bluk delete was done
```
Comment (licitdev) [inline api/src/websocket/utils/items.ts:72]:
```suggestion
			// return only the subscribed id in case a bulk delete was done
```

File: api/src/websocket/utils/items.ts [hunk 3]
```diff
@@ -98,20 +60,32 @@ export async function getMultiPayload(
...
+	}
+
+	switch (event?.action) {
+		case 'create':
+			return await service.readMany([String(event.key)]);
+		case 'update':
+			return await service.readMany(event.keys.map((key: any) => String(key)));
+		case 'delete':
+			return event.keys;
+		case undefined:
```
Comment (paescuj) [inline api/src/websocket/utils/items.ts:86]: Is there a special reason for this as it's already covered by `default`?
```suggestion
```

Same on https://github.com/directus/directus/pull/19743/files#diff-bdf71e4ea86237826b20211bbbb174d2bc99964364bd2b334e5e22b21cb32fb8R161

Comment (br41nslug) [reply api/src/websocket/utils/items.ts:86]: Yes `undefined` is an actual value it can be expected to be and `default:` was just added as fallback later for https://github.com/directus/directus/pull/19743#discussion_r1352101638.

Comment (paescuj) [reply api/src/websocket/utils/items.ts:86]: I see! Not so sure about the `default` then.
Wouldn't it make more sense to handle new event types individually/correctly at the moment when they are added?

TypeScript would warn us if there should be uncovered events:

Comment (br41nslug) [reply api/src/websocket/utils/items.ts:86]: Yep it is still JS in the end so it's not impossible to get other runtime value

Comment (paescuj) [reply api/src/websocket/utils/items.ts:86]: Okay, works for me 😃 You have the better overview here 👍

Comment (br41nslug) [reply api/src/websocket/utils/items.ts:86]: But i do agree with you, if i had to choose I would drop the `defaults` in favor of explicit values

**Review by paescuj — APPROVED** [review]
Works as expected 🥇
