### PR TITLE
Fixes enabling/disabling extensions

### LINKED ISSUE #20478: Disabled extensions stays active
### Describe the Bug

As the title already describes - even after restarting Directus, a disabled extension (doesn't matter of type) stays active:
image
image

### To Reproduce

just do it :-)

https://discord.com/channels/725371605378924594/741317677397704757/1176144948752551956

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #20478 

## Scope

What's changed:

- Implemented enabling/disabling of extensions in a bundle
- Implemented enabling/disabling of app extensions
- Added a banner to reload the app when enabling or disabling app extensions
- Hidden enable/disable logic in development mode
- Added navigation guard

## Review questions
- I was unable to hotreload app extension in the browser so i have chosen to add a warning banner and navigation guard instead, is this enough?
- I was unable to read these enabled settings from the database in the vite config file when running in developer mode so i've opted to default to enabling everything which is the current behavior too

### CODE REVIEW

**Review by paescuj — DISMISSED** [review]
Great work! 🚀 

> I was not able to figure out how to load/unload App extensions live in the browser without refreshing so for the Admin that actually does the disabling/enabling i've added a warning banner that the page should be refreshed. I could do this directly when enabling/disabling a frontend extension but that could be bad DX if you want to disable a bunch of them.

This solution makes perfect sense to me and should also be understandable from user perspective 👍

The enabling/disabling works, but I had to update the "Reload" link, see eb6c287. Previously, I was redirected to the login page in prod build. Could you confirm the new solution works to on your side?

> I was unable to read these enabled settings from the database in the vite config file when running in developer mode so i've opted to default to enabling everything which is the current behavior too

I was afraid of that 😅 Seems fine to have app extensions always enabled in dev mode, but I think we should reflect that in the UI. I was thinking about replacing the "Enabled / Disabled" label with "Enabled (Dev)" with a corresponding tooltip "App Extensions are always enabled in Dev Mode".

**Comment by rijkvanzanten** [comment]
> Seems fine to have app extensions always enabled in dev mode, but I think we should reflect that in the UI. I was thinking about replacing the "Enabled / Disabled" label with "Enabled (Dev)" with a corresponding tooltip "App Extensions are always enabled in Dev Mode".

I'm wondering if there's something we can do to make it behave the same in both prod and dev 🤔

**Comment by br41nslug** [comment]
It behaves the same in both before this PR, being always enabled with the exception of old style backend extensions 😂 The roadblock I ran into for dev mode specifically is that I was unable to get the extensions enabled statusses either from the API (because you need authentication) or directly from the database in the apps `vite.config.js` where the extensions get loaded. In production the API bundles these extensions and has access to anything it needs at that point but in dev mode these are separate processes.

**Comment by paescuj** [comment]
> I'm wondering if there's something we can do to make it behave the same in both prod and dev 🤔

As Tim wrote, not with the current architecture, I'm afraid 🙈 App extensions need to be loaded early during app initialization and we don't have access to the required server state (at this point). We might rely on the API to bundle app extensions in dev (as in prod), but then we would a) need to implement hot reloading via API b) find a way to map shared deps correctly (static asset name?).

File: app/src/modules/settings/routes/extensions/extensions.vue [hunk 1]
```diff
@@ -79,6 +113,17 @@ fetchExtensions();
...
+		<v-dialog v-model="confirmLeave" @esc="confirmLeave = false">
+			<v-card>
+				<v-card-title>{{ t('extension_reload_required') }}</v-card-title>
+				<v-card-text>{{ t('extension_reload_required_copy') }}</v-card-text>
+				<v-card-actions>
+					<v-button @click="leavePage">{{ t('extension_reload_now') }}</v-button>
+					<v-button secondary @click="confirmLeave = false">{{ t('back') }}</v-button>
+				</v-card-actions>
+			</v-card>
+		</v-dialog>
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/extensions.vue:126]: Nice idea to add a navigation guard 🎉 

However, I'm not quite sure whether we really want to force the page reload, seems a bit too "aggressive" for me.
How about offering the option "Proceed without reload" instead of "Back"?

Also the primary action should be moved to the right side:
```suggestion
		<v-dialog v-model="confirmLeave" @esc="confirmLeave = false">
			<v-card>
				<v-card-title>{{ t('extension_reload_required') }}</v-card-title>
				<v-card-text>{{ t('extension_reload_required_copy') }}</v-card-text>
				<v-card-actions>
					<v-button secondary @click="confirmLeave = false">{{ t('back') }}</v-button>
					<v-button @click="leavePage">{{ t('extension_reload_now') }}</v-button>
				</v-card-actions>
			</v-card>
		</v-dialog>
```

File: app/src/modules/settings/routes/extensions/extensions.vue [hunk 2]
```diff
@@ -103,3 +148,4 @@ fetchExtensions();
 	margin-top: 24px;
 }
 </style>
+./utils/current-page-link
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/extensions.vue:151]:
```suggestion
```

File: app/src/modules/settings/routes/extensions/utils/current-page-link.ts
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/utils/current-page-link.ts:1]: Usually, I'm very much in favor of splitting logic into multiple functions (even small ones).
In this case, however, I would actually prefer to use the value directly in `extensions.vue`, so it's easier to see what is actually happening. WDYT?

File: app/src/modules/settings/routes/extensions/utils/use-reload-guard.ts
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/utils/use-reload-guard.ts:1]: Wondering whether it would makes sense to create a generic `use-navigation-guard` composable, which we can reuse here as well as in [`use-edits-guard.ts`](https://github.com/directus/directus/blob/main/app/src/composables/use-edits-guard.ts), seeing that those two are based on the same logic?

File: app/src/modules/settings/routes/extensions/extensions.vue [hunk 3]
```diff
@@ -1,25 +1,40 @@
...
+const regular = computed(() => extensions.value.filter(({ bundle }) => !bundle));
 const extensionsByType = computed(() => groupBy(regular.value, 'schema.type'));
 
+const { confirmLeave, leaveTo, removeGuard } = useReloadGuard(needsReload);
+
+const leavePage = () => {
+	removeGuard();
+	const target = leaveTo.value ?? currentPageLink();
+	router.push(target);
+	// reload the page
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/extensions.vue:34]: Could you expand this comment a tad? I'm afraid the logic here might be a bit difficult to comprehend for non-involved devs.

**Review by paescuj — COMMENTED** [review]
Thanks! ❤️ Can confirm the extension reload works! I've added a few comments.

File: app/src/modules/settings/routes/extensions/components/extension-item.vue [hunk 4]
```diff
@@ -107,3 +110,4 @@ const toggleEnabled = async () => {
 	}
 }
 </style>
+../utils/icons
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/components/extension-item.vue:113]: LOL thnx vscode

File: app/src/modules/settings/routes/extensions/components/extension-item.vue [hunk 5]
```diff
@@ -40,27 +42,28 @@ const toggleEnabled = async () => {
...
+	<v-list-item block :class="{ disabled: devMode ? false : !extension.meta.enabled }">
 		<v-list-item-icon v-tooltip="t(`extension_${type}`)"><v-icon :name="icon" small /></v-list-item-icon>
 		<v-list-item-content class="monospace">{{ extension.name }}</v-list-item-content>
 		<v-chip v-if="extension.schema?.version" class="version" small>{{ extension.schema.version }}</v-chip>
 
 		<template v-if="extension.schema?.type !== 'bundle'">
 			<v-progress-circular v-if="changingEnabledState" indeterminate />
-			<v-chip v-else class="state" :class="{ enabled: extension.meta.enabled }" small>
-				{{ extension.meta.enabled ? t('enabled') : t('disabled') }}
+			<v-chip v-else class="state" :class="{ enabled: devMode ? true : extension.meta.enabled }" small>
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/components/extension-item.vue:58]: Could we add a tooltip hint here à la "App extensions are always enabled in dev mode" or "App extensions cannot be disabled in dev mode" to make it a bit clearer?

**Review by paescuj — COMMENTED** [review]
Sorry, forgot this in my previous review

File: app/src/modules/settings/routes/extensions/components/extension-item.vue [hunk 6]
```diff
@@ -2,12 +2,14 @@
...
 import VProgressCircular from '@/components/v-progress-circular.vue';
-import type { ApiOutput } from '@directus/extensions';
+import type { ApiOutput, ExtensionType } from '@directus/extensions';
 import { computed, ref } from 'vue';
 import { useI18n } from 'vue-i18n';
-import { iconMap } from '../constants/icons';
+import { iconMap } from '../utils/icons';
 import ExtensionItemOptions from './extension-item-options.vue';
 
+const devMode = process.env.NODE_ENV === 'development';
```
[the remark this answers is not in the document]
Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/components/extension-item.vue:11]: Interesting where does `import.meta.env.DEV` get set? I can see it being used but it's not obvious when/where it applies 🤔 I went for `process.env.NODE_ENV === 'development'` because we explicitly set it and use that in places like the vite config

File: app/src/modules/settings/routes/extensions/extensions.vue (hunk 1 above)
Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/extensions.vue:126]: I personally think a reload should be required as the App is effectively in an error state after disabling extensions and in an incomplete state when enabling extensions. By enforcing this with the navigation guard i'm hoping to prevent issues like "I just enabled interface X but cannot select it when creating a field" or people selecting disabled interfaces which will be non-existing for anyone else or after reload.

File: app/src/modules/settings/routes/extensions/components/extension-item.vue (hunk 6 above)
[the remark this answers is not in the document]
Comment (paescuj) [reply app/src/modules/settings/routes/extensions/components/extension-item.vue]: It's a specially exposed variable by Vite, see [import.meta.env](https://vitejs.dev/guide/env-and-mode#env-variables). As far as I understand it, designed exactly for such cases.
Feels a bit safer than relying directly on `process.env` which is theoretically unavailable in browser env.

File: app/src/modules/settings/routes/extensions/utils/use-reload-guard.ts
Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/utils/use-reload-guard.ts:1]: They do share a bit of code (possibly because i copied and edited the edits-guard 😂). However i think it may be a little premature to start abstracting that already, my personal rule of thumb is to try abstracting/refactoring it after building the 3rd similar function/class/composable

Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/utils/use-reload-guard.ts:1]: Having said that i dont think its a bad plan 😂 lemme think on it a second if this is abstractable in a way that would still make sense when adding that 3rd guard in the future

File: app/src/composables/use-navigation-guard.ts [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+	};
+
+	const addListener = () => window.addEventListener('beforeunload', beforeUnload);
+	const removeListener = () => window.removeEventListener('beforeunload', beforeUnload);
+
+	onBeforeMount(addListener);
+	onBeforeUnmount(removeListener);
+
+	return { removeGuard: removeListener };
+}
```
Comment (paescuj) [inline app/src/composables/use-navigation-guard.ts:22]: Let's
- simplify with [`useEventListener`](https://vueuse.org/core/useEventListener/) from VueUse
- no longer set `event.returnValue`, it's [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue)
- not return `removeGuard`, see comment in `extensions.vue`

```suggestion
import { useEventListener } from '@vueuse/core';
import { type Ref } from 'vue';
import { NavigationGuard, onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router';

export function useNavigationGuard(locked: Ref<boolean>, guard: NavigationGuard) {
	onBeforeRouteUpdate(guard);
	onBeforeRouteLeave(guard);

	useEventListener(document, 'beforeunload', (event) => {
		if (locked.value) {
			event.preventDefault();
		}
	});
}
```

File: app/src/composables/use-reload-guard.ts [hunk 8]
```diff
@@ -0,0 +1,22 @@
...
+			confirmLeave.value = true;
+			leaveTo.value = to.fullPath;
+			return false;
+		}
+
+		return true;
+	});
+
+	return { confirmLeave, leaveTo, removeGuard };
+}
```
Comment (paescuj) [inline app/src/composables/use-reload-guard.ts:22]: `removeGuard` is not required, see comment in `extensions.vue`

```suggestion
import { ref, type Ref } from 'vue';
import { useRoute } from 'vue-router';
import { useNavigationGuard } from './use-navigation-guard';

export function useReloadGuard(needsReload: Ref<boolean>) {
	const { path } = useRoute();

	const confirmLeave = ref(false);
	const leaveTo = ref<string | null>(null);

	useNavigationGuard(needsReload, (to) => {
		if (needsReload.value && !to.path.startsWith(path)) {
			confirmLeave.value = true;
			leaveTo.value = to.fullPath;
			return false;
		}

		return true;
	});

	return { confirmLeave, leaveTo };
}
```

File: app/src/modules/settings/routes/extensions/extensions.vue [hunk 9]
```diff
@@ -1,25 +1,41 @@
...
+
+const currentPageLink = () => document.location.href;
+
+const leavePage = () => {
+	removeGuard();
+	// push target location into the route history
+	router.push(leaveTo.value ?? currentPageLink());
+	// hard-reload the page using the latest route
+	router.go(0);
+};
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/extensions.vue:37]: Instead of `removeGuard` we need to set `needsReload` to false, otherwise the guard still blocks the `router.push` call and `router.go` results in reloading the current page.
Note: The event listener should be removed anyway since a) the component is unmounted b) the page is hard-reloaded.

Also we should await `router.push` in this case to ensure `router.go` is called after navigation is completed.

```suggestion
const currentPageLink = document.location.href;

const leavePage = async () => {
	needsReload.value = false;
	// push target location into the route history
	await router.push(leaveTo.value ?? currentPageLink);
	// hard-reload the page using the latest route
	router.go(0);
};
```

File: app/src/modules/settings/routes/extensions/extensions.vue [hunk 10]
```diff
@@ -56,10 +84,17 @@ fetchExtensions();
 			<extensions-info-sidebar-detail />
 		</template>
 
+		<div v-if="needsReload" class="page-container">
+			<v-notice type="warning">
+				{{ t('extension_reload_required_copy') }}&nbsp;
+				<a :href="currentPageLink()" @click="removeGuard">{{ t('extension_reload_now') }}</a>
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/extensions.vue:90]: See comment above regarding `removeGuard`

```suggestion
				<a :href="currentPageLink">{{ t('extension_reload_now') }}</a>
```

File: app/src/modules/settings/routes/extensions/extensions.vue [hunk 11]
```diff
@@ -103,3 +149,4 @@ fetchExtensions();
 	margin-top: 24px;
 }
 </style>
+../../../../composables/use-reload-guard
```
Comment (paescuj) [inline app/src/modules/settings/routes/extensions/extensions.vue:152]: vscode-again

_\~ Best wishes, VS Code_

```suggestion
```

**Review by paescuj — COMMENTED** [review]
Lovin' it, thanks @br41nslug ❤️ 

I've added some final tweaks. I've tested the reload guard as well as edit guard in Chromium, Firefox and Safari with these tweaks. Same for the reload link in the banner.

File: app/src/modules/settings/routes/extensions/extensions.vue (hunk 11 above)
Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/extensions.vue:152]: Hahaha damn you vscode, really need to stop smacking that "update imports" button when moving files

File: app/src/composables/use-reload-guard.ts (hunk 8 above)
Comment (br41nslug) [reply app/src/composables/use-reload-guard.ts:22]: Ah the combination with the vue-use `useEventListener` was the big trick here to get rid of those browser/system dialogs 🤔

File: app/src/modules/settings/routes/extensions/extensions.vue (hunk 9 above)
Comment (br41nslug) [reply app/src/modules/settings/routes/extensions/extensions.vue:37]: I found a way to resolve the url instead so we can simply rely on `document.location.href` for navigating instead of this vue router workaround.

**Review by paescuj — APPROVED** [review]
LGTM
