### PR TITLE
Encoded the url using encodeURIComponent, so that the url gets sanitzed and so, we did not get 404 error.

### LINKED ISSUE #14265: Flows: URL encode url field in Request URL operation.
### Describe the Bug

The the url field in the Webhook / Request URL operation isn't url Encoded / Sanitized before making the request.

When passing payload values as query parameters to the URL field in the Request URL Operation, the url isn't encoded before sending the request.

### To Reproduce

Within a flow create a request operation with a URL field that uses a payload value anywhere.
Screen Shot 2022-07-03 at 16 44 32

After the operation runs without encoding the url field.

### Errors Shown

```{
  "message": "Request failed with status code 404",
  "name": "AxiosError",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "User-Agent": "axios/0.27.2"
    },
    "url": "https://https://www.google.com/search?q=**unencoded value ó # **",
    "method": "get"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 404
}```

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

18

### What database are you using?

Postgres 13

### What browser are you using?

Brave

### How are you deploying Directus?

ubuntu/ self-hosted

### PR DESCRIPTION
**Pull request by zeel-pathak**
## Description
Encoded the url using encodeURIComponent, so that the url gets sanitzed and so, we did not get 404 error.

Fixes #

## Type of Change

- [x] Bugfix

## Requirements Checklist

- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

Closes #14265

### CODE REVIEW

**Comment by benhaynes** [comment]
Thanks for the contribution... and welcome to our dev community!! 🙂

File: api/src/operations/request/index.ts [hunk 1]
```diff
@@ -16,8 +16,8 @@ export default defineOperationApi<Options>({
 			acc[header] = value;
 			return acc;
 		}, {} as Record<string, string>);
-
-		const result = await axios({ url, method, data: body, headers: customHeaders });
+		
+		const result = await axios({ encodeURIComponent(url), method, data: body, headers: customHeaders });
```
Comment (br41nslug) [inline api/src/operations/request/index.ts:20]: It's not possible to use a function like this directly in an object without providing a key. When using a variable doing this will interpolate the variable as key like so `{ test }` is equal to ` { test: test }` however with a function this will result in a syntax error. 
```suggestion
		const result = await axios({ url: encodeURIComponent(url), method, data: body, headers: customHeaders });
```

**Review by br41nslug — CHANGES_REQUESTED** [review]

File: api/src/operations/request/index.ts (hunk 1 above)
Comment (zeel-pathak) [reply api/src/operations/request/index.ts:20]: Ohh thanks @br41nslug , I forgot about this thing about function...Thanks for review, I will add it.

Comment (br41nslug) [reply api/src/operations/request/index.ts]: Awesome, thanks for contributing 😃

**Review by br41nslug — APPROVED** [review]

File: api/src/operations/request/index.ts [hunk 2]
```diff
@@ -16,8 +16,8 @@ export default defineOperationApi<Options>({
 			acc[header] = value;
 			return acc;
 		}, {} as Record<string, string>);
-
-		const result = await axios({ url, method, data: body, headers: customHeaders });
+		
+		const result = await axios({ url: encodeURIComponent(url), method, data: body, headers: customHeaders });
```
Comment (br41nslug) [inline api/src/operations/request/index.ts:20]: Just noticed a second thing just in time, i believe using `encodeURI` here is more appropriate as `encodeURIComponent` will encode the full url from `https://directus.io/` to `https%3A%2F%2Fdirectus.io%2F` where you only want to encode the parameters used in the url. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

**Review by br41nslug — CHANGES_REQUESTED** [review]

File: api/src/operations/request/index.ts (hunk 2 above)
Comment (zeel-pathak) [reply api/src/operations/request/index.ts:20]: Yeah! you got a point, Thanks for letting me know

**Comment by br41nslug** [comment]
Looking good 👍 if you could fix that last linter error i'll merge it.

**Comment by br41nslug** [comment]
Looks like you've committed some windows line endings. While you can fix these one by one as they show up ESLint also has pretty decent integration with IDEs like VSCode to help highlight and auto-fix these problems 😄

**Comment by zeel-pathak** [comment]
@br41nslug , Thanks man, this was my first open-source contribution. I was really nervous, I thought you will be judging me for making such tiny mistakes, but genuinely speaking you are a gem of a person

**Review by br41nslug — APPROVED** [review]

**Comment by rn1ee** [comment]
Thanks for merging this PR into v9.14.2 - but we still have problems, because the encodeURI function leaves some characters untouched in the flow webhook url, the important one is the ampersand (&).

If we have to send content from an WYSIWYG editor as url parameter which contains German umlauts, the editor converts them to the HTML entities like `&uuml;` - so that the webhook url then contains for example `https://www.xxx.xx/?text=m&uuml;nchen&title=my%20example%20for%20directus`, the webhook endpoint will now read only the "m" from the text param and ignores the rest of the string `uuml;nchen`...

Better would be to use the encodeURIComponent function instead of encodeURI which @zeel-pathak included in 5e5c708, because this also encodes the ampersand `https%3A%2F%2Fwww.xxx.xx%2F%3Ftext%3Dm%26uuml%3Bnchen%26title%3Dmy%20example%20for%20directus`.

**Comment by rijkvanzanten** [comment]
> Thanks for merging this PR into v9.14.2 - but we still have problems, because the encodeURI function leaves some characters untouched in the flow webhook url, the important one is the ampersand (&).
> 
> 
> 
> If we have to send content from an WYSIWYG editor as url parameter which contains German umlauts, the editor converts them to the HTML entities like `&uuml;` - so that the webhook url then contains for example `https://www.xxx.xx/?text=m&uuml;nchen&title=my%20example%20for%20directus`, the webhook endpoint will now read only the "m" from the text param and ignores the rest of the string `uuml;nchen`...
> 
> 
> 
> Better would be to use the encodeURIComponent function instead of encodeURI which @zeel-pathak included in 5e5c708, because this also encodes the ampersand `https%3A%2F%2Fwww.xxx.xx%2F%3Ftext%3Dm%26uuml%3Bnchen%26title%3Dmy%20example%20for%20directus`.

Wanna open a PR for that tweak?

**Comment by zeel-pathak** [comment]
hey @rn1ee, earlier I used ```encodeURIComponent```, but it encodes the whole URL, but with the help of @br41nslug, get to know that we only need to encode the parameters as discussed in ```https://github.com/directus/directus/pull/14418#discussion_r920249530```,
So it is better to use ```encodeURI``` as it only encodes the parameters, not the whole URL.

Specifically, I do not know anything about German umlauts, Let me know what you think.

**Comment by zeel-pathak** [comment]
And from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#description, We can see that ```&``` is a reserved character hence it does not gets encoded.

**Comment by br41nslug** [comment]
`encodeURIComponent` can't be used to encode an entire URL because that will result in an invalid url. If we want to use that we'll need to split the url parameter and encode them parameters separately.
