### PR TITLE
Fix unexpected types

### LINKED ISSUE #9576: TypeError: Cannot read properties of undefined (reading 'startsWith')
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello, after upgrading to latest (non RC) version of Directus - **`v9.0.0`** encountered this error: `TypeError: Cannot read properties of undefined (reading 'startsWith')` (see complete error call stack below)

Here are my deps in `package.json`
```json
  "dependencies": {
    "directus": "9.0.0-rc.101",
    "mysql": "^2.18.1"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^21.0.1",
    "@rollup/plugin-node-resolve": "^13.0.6",
    "rollup": "^2.58.3",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-vue": "^6.0.0",
    "vue-template-compiler": "^2.6.14"
  }
```

---

I tried install all dependecies with `pnpm`, `yarn` and `npm` on two Node.js versions: `16.13.0` and `17.0.1` - nothing helped.

Is this a problem on your / my side?

### To Reproduce

1. Install Directus v9.0.0 on Node v.16.13.0 / v.17.0.1
2. Run `npx directus start`

### Errors Shown
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at getLocalType (/node_modules/directus/dist/utils/get-local-type.js:114:18)
    at getDatabaseSchema (/node_modules/directus/dist/utils/get-schema.js:115:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getSchema (/node_modules/directus/dist/utils/get-schema.js:36:22)
    at async registerAuthProviders (/node_modules/directus/dist/auth.js:26:64)
    at async createApp (/node_modules/directus/dist/app.js:92:5)
    at async createServer (/node_modules/directus/dist/server.js:40:38)
    at async Command.startServer (/node_modules/directus/dist/server.js:126:20)
    at async Command.parseAsync (/node_modules/commander/lib/command.js:923:5)
```
### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0 / 17.0.1

### What database are you using?

MySQL 8.0.21

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.4.0-19041-Microsoft (WSL)

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by grefrit**
Fixes #9576

### CODE REVIEW

File: api/src/utils/get-local-type.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ export default function getLocalType(
 		if (special.includes('hash')) return 'hash';
 		if (special.includes('csv')) return 'csv';
 		if (special.includes('uuid')) return 'uuid';
-		if (type.startsWith('geometry')) {
+		if (type?.startsWith('geometry')) {
```
Comment (joselcvarela) [inline api/src/utils/get-local-type.ts:122]: Instead of this, what about iterate over `localTypeMap` and check if `column.data_type` starts with the `key` of `localTypeMap`. This way instead of returning `unknown` for `tinyint unsigned` it would return `integer`.
What are you thoughts @Oreilles @azrikahar?

Comment (rijkvanzanten) [reply api/src/utils/get-local-type.ts:122]: Not sure if that'll work in this particular use case, as I believe this type is the "local type", not the column data type 🤔 I might be mistaken though. @Oreilles ?

Comment (joselcvarela) [reply api/src/utils/get-local-type.ts:122]: Yeah I meant to do that procedure on line 113, so here `type` will be already `integer`.

Comment (Oreilles) [reply api/src/utils/get-local-type.ts:122]: I'd say let's add `tinyint unsigned` to the localTypeMap instead!

Comment (joselcvarela) [reply api/src/utils/get-local-type.ts:122]: But then we will need to add every type variant to `localTypeMap` like `tinyint unsigned`, `tinyint zerofill`, `text collate ...`, etc. https://mariadb.com/kb/en/numeric-data-type-overview/
That's why I suggested to lookup only the first name.
Also I think this is not specific to geometry. The issue urged on that line because `type` was `undefined`.

Comment (Oreilles) [reply api/src/utils/get-local-type.ts:122]: Seems error prone. Exhaustivity should be preferred IMO. As an example: type `time` whould return true if you check `"timestamp".startsWith('time')`

Comment (GrefriT) [reply api/src/utils/get-local-type.ts:122]: I found another bug because of this line
https://github.com/directus/directus/blob/4fc02c7b6b7511346592cac4dbbf5b2b8445ad15/api/src/utils/get-local-type.ts#L113
Here we are splitting by ( and take first part, so types like
https://github.com/directus/directus/blob/4fc02c7b6b7511346592cac4dbbf5b2b8445ad15/api/src/utils/get-local-type.ts#L58
won't work and all tinyint's will be considered as boolean, it's incorrect for a lot of cases

Comment (Oreilles) [reply api/src/utils/get-local-type.ts:122]: Saw this too, I'm on it

Comment (GrefriT) [reply api/src/utils/get-local-type.ts:122]: @Oreilles mysql creates boolean type by default as tinyint(1), not as tinyint or tinyint(0), but in your solutions you map tinyint too. And I don't know, is it possible to use tinyint(0) as boolean?

Comment (Oreilles) [reply api/src/utils/get-local-type.ts:127]: It probably is since that is how they were handled in previous versions.

**Review by oreilles — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]
