### PR TITLE
App: Allow interpolation string as the only value on `input-code` interface

### LINKED ISSUE #21263: Code block in "trigger flow" sends variable with quotes
### Describe the Bug

When creating a flow with a "trigger flow" you can't send `{{$last}}` in the payload. The linter wants you to add "". When doing so the flow return an invalid JSON error. When you go back and check the raw editor it actually sends {{$last}} with quotes.

### To Reproduce

You need to create a flow with a "trigger flow" and make a simple flow that sends data through. 
You need to add the `{{$last}}` to the code payload _(you will have to do quotes here because of the linting)._
Then run it and you will get this error.
```
{
  "name": "SyntaxError",
  "message": "Unexpected token i in JSON at position 4"
}
```
When you go to the raw editor you will see the quotes there and when you see it in your network tab it will show that the escaped quotes are there as well.
image

### video
https://github.com/directus/directus/assets/14160793/bb5ecf92-b9da-46e8-b146-bf6301e30a09

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope
When using Flows, there's cases that we just want to pass the response from previous operation to the next one.
For example, we might want to pass the payload of a Read Date operation to another flow using Trigger Flow operation.
For such cases we should be able to pass the following into the Payload option of Trigger Flow operation:
```
{{ $last }}
```
Although, the Code interface will complain because the Payload option is defined as JSON and this value is not a valid JSON so the linter will show an error.
Since this is a valid action to do (to pass `{{ $last }}`), in this PR we ignore the lint if the value is an interpolation, i.e., if the value starts with `{{` and ends with `}}`. 

What's changed:

- Allow interpolation at root level of Code interface using JSON language

## Potential Risks / Drawbacks

- If the value used is not an interpolation but anything that starts with `{{` and ends with `}}`, there will be no errors

## Review Notes / Questions

- This seems to be a nice first approach to this. Although we should also be able to validate the payload on the API. I have not did it since I didn't found any example on how to validate requests according to the entity.
For example, we could try add some validation into [`OperationsService`](https://github.com/directus/directus/blob/main/api/src/services/operations.ts#L6) but the App send the operation data within a flow which will be handled by [`FlowService`](https://github.com/directus/directus/blob/main/api/src/services/flows.ts#L6) so no validation would be made

## Comparision
|Before|After|
|-|-|
|<video src="https://github.com/directus/directus/assets/14039341/f2af4a27-b0a0-4ea5-82f7-d293aadd105e" ></video>|<video src="https://github.com/directus/directus/assets/14039341/262999ed-c156-428c-a58e-61dd99eab600"></video>|
|In this case you can see that when using `{{$last}}` the Code interface shows an error. Although the Flow works as expected. When I type `"{{ $last }}"` the Flow throws an error.|In this case you can see that using `{{$last}}` **does not** show any error any more and Flow works as expected. Although when typing `"{{ $last }}"` it will still throw an error as  `"` are not removed and Flow will have double quotes conflicting.|
---

Fixes #21263

### CODE REVIEW

File: app/src/interfaces/input-code/input-code.vue [hunk 1]
```diff
@@ -278,6 +287,10 @@ function fillTemplate() {
 		emit('input', props.template);
 	}
 }
+
+function isInterpolation(value: any) {
+	return typeof value === 'string' && value.startsWith('{{') && value.endsWith('}}');
```
Comment (paescuj) [inline app/src/interfaces/input-code/input-code.vue:292]: We should probably make it strict (require value between brackets), for example we could re-use the pattern from https://github.com/directus/directus/blob/5a6071d88bc4b28e4b6899f17fe613e4d15a517a/packages/utils/shared/apply-options-data.ts#L38

**Review by paescuj — COMMENTED** [review]
Since this is only applicable in context of Flows, we should add an option to the interface that allows us to control this behavior.

**Comment by paescuj** [comment]
@joselcvarela Had another idea: How about auto switching to raw editor if a plain interpolation string is detected? Then we wouldn't have to touch the `input-code` interface and it might make it a bit clearer for the user.

**Review by paescuj — APPROVED** [review]
Works as intended 🚀 

(On my previous idea: Would be a bigger changeover as the code interface currently only emits when value is valid... Not worth it at the moment.)
