### PR TITLE
Session Based Authentication

### LINKED ISSUE #21118: Unnecessary fetches using Base64
### Describe the Bug

As seen in the image above, when listing a table with a user shown, it loads the image one after another, pretty slowly, and this is exacerbated when the ping is high (>=250ms).

After a quick look into the code it looks like it is loaded using Base64, over and over. Wouldn't it be considerably faster if fetched directly using the image endpoint? That way, the browser would understand that the same image is being fetched again and would display them all at once.

Cheers!

### To Reproduce

1. Use a high latency connection
2. View a table with "User Created" or similar

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Custom)

### LINKED ISSUE #21159: Add security note for access_token in the query
### Describe the Request

The authentication section in the Directus documentation (https://docs.directus.io/reference/authentication.html) mentions two methods for passing the access token: through a query parameter or an authorization header. It is generally recommended to use the authorization header approach. This helps in minimizing the risk of the access token being inadvertently exposed in logs or accessed by third-party systems. Using headers for token transmission is a best practice for enhancing security.

CleanShot 2024-01-22 at 15 16 01@2x

References:
https://cwe.mitre.org/data/definitions/598.html
https://cwe.mitre.org/data/definitions/200.html
https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#used-vs-accepted-session-id-exchange-mechanisms

### Maintainence Strategy

No maintenance, it's a design best practice, not technology dependent

### PR DESCRIPTION
**Pull request by br41nslug**
## Scope

fixes https://github.com/directus/directus/issues/21118
fixes https://github.com/directus/directus/issues/21159

What's changed:

- Introduced a new authentication mode `"session"` which stores a session token as cookie.
- Adds `SESSION_COOKIE_*` environment variables, same subset as refresh_tokens.
- Implemented shares authentication in the SDK auth composable.
- Implemented the new auth mode in the auth middleware
- Updated SSO (open-id, saml, oath2) to default to the new "session" mode
- Updated the App to use the new authentication and removed obsolete token logic (using a regular `src` for `v-image` and removed the `addTokenToURL` util)
- Updated the SDK types to allow this new method

## TODO

- [x] Find missed docs pages to update

## Potential Risks / Drawbacks

- Authentication changes are always tricky, im sure i've missed an edge-case somewhere.

## Potential Advantages
- No more access_tokens in the URL for assets
- Credential sharing between multiple tabs of the app (or sdk) without one invalidating the refresh token of the other
- API calls done in the same browser as you're logged into the app will now work (but can be overwritten by an explicit Authorization header or access_token query param)

## Review Notes

- For SSO i am currently only able to test google's open-id myself!
- Considered adding CSRF but i dont think this is applicable here since we explicitly only accept `application/json` bodies on the API which cannot be done using regular forms (which is the main attack vector) and ajax calls are limited by cors/csp
- Also considered signing the cookie but since the JWT used as token is already signed and validated i dont't think thats explicitly required here
- I've excluded the WebSocket from using the cookie session as i am not sure I can currently secure that properly against cross site websockets

## Review Questions
- I've excluded the session cookie from the RFC6750 multiple auth methods error else this will break a lot of existing installs that are using the API from the same domain as the App. Do you agree or do we make this a breaking change?
- I've opted to let the SSO providers (openID, SAML, oauth2) default to the new "session" mode so they are compatible with the updates to the app, but of course this is a breaking change for anyone relying on the refresh token with SSO in an external app. For that i've added an env var. Is it right to prioritize making it work with the app here?

### CODE REVIEW

**Review by azrikahar — COMMENTED** [review]
> For SSO i am currently only able to test google's open-id myself!

Did a quick test with GitHub OAuth2 and wasn't able to spot any issues 👍

File: app/src/auth.ts
Comment (azrikahar) [inline app/src/auth.ts:1]: Just noticed an error when manually logging out, we do send `mode: 'session'` in the body during login but seems like we're not sending it when logging out, so the API's `getCurrentMode` is interpreting mode as `cookie`. 

Should we post `mode: 'session'` during logout as well? Should be the line with `await api.post(`/auth/logout`);` if I'm not mistaken.

File: app/src/components/v-image.vue
Comment (paescuj) [inline app/src/components/v-image.vue:1]: Not important, but `inheritAttrs: false` and `v-bind="attrs"` cancel each other out together.

FWIW: Since it's effectively just an alias for `img` now, we might as well remove that component all together, but better to do that in a separate PR 👍

File: api/src/constants.ts
Comment (paescuj) [inline api/src/constants.ts:1]: This has already been used that way for `COOKIE_OPTIONS` before, but I think we should move the cookie options retrievement to an util like `getCookieOptions` where `useEnv()` is called inside that function instead of top-level to fetch the current state (relevant for later on where env can change during runtime).

`REFRESH_COOKIE_OPTIONS`  and `SESSION_COOKIE_OPTIONS` seems slightly misplaced in `constants.ts` anyway, seeing that all the other variables are plain constants (no function calls).

File: app/src/api.ts [hunk 1]
```diff
@@ -1,9 +1,7 @@
-import { logout, LogoutReason, refresh } from '@/auth';
 import { useRequestsStore } from '@/stores/requests';
 import { getRootPath } from '@/utils/get-root-path';
 import axios, { AxiosError, AxiosResponse, InternalAxiosRequestConfig } from 'axios';
-import PQueue, { type Options, type QueueAddOptions } from 'p-queue';
-import { addQueryToPath } from './utils/add-query-to-path';
+import PQueue, { type DefaultAddOptions, type Options } from 'p-queue';
```
Comment (paescuj) [inline app/src/api.ts:4]:
```suggestion
import PQueue, { type Options } from 'p-queue';
```

File: docs/guides/extensions/interfaces-radio-selector-icons.md [hunk 2]
```diff
@@ -157,6 +157,12 @@ select-icon, which provides a searchable dropdown of the icon library.
 
 ## Work With Images
 
+::: tip
+
+[DEPRECATED] Use session cookies instead.
```
Comment (paescuj) [inline docs/guides/extensions/interfaces-radio-selector-icons.md:162]: Could we add a link? I guess to the SDK authentication guide

Comment (paescuj) [inline docs/guides/extensions/interfaces-radio-selector-icons.md:162]:
```suggestion
::: warning DEPRECATED

Use session cookies instead.
```

like here https://docs.directus.io/reference/query.html#metadata

File: docs/guides/extensions/modules-build-landing-page.md [hunk 3]
```diff
@@ -500,6 +500,12 @@ api.get(`/items/pages?fields=title,banner,content&filter[uri][_eq]=${page}`).the
 
 ### Work With Images
 
+::: tip
+
+[DEPRECATED] The query parameter approach used here is deprecated, make use of session cookies instead.
```
Comment (paescuj) [inline docs/guides/extensions/modules-build-landing-page.md:505]:
```suggestion
::: warning DEPRECATED

The query parameter approach used here is deprecated, make use of session cookies instead.
```

like here https://docs.directus.io/reference/query.html#metadata

Comment (paescuj) [inline docs/guides/extensions/modules-build-landing-page.md:505]: Could we add a link? I guess to the SDK authentication guide

File: docs/reference/authentication.md [hunk 4]
```diff
@@ -12,30 +12,46 @@ pageClass: page-reference
...
+time like the Temporary Tokens as you cannot refresh these after they have expired.
+
 **Static Tokens** can be set for each platform user, and never expire. They are less secure, but quite useful for
 server-to-server communication. They are saved as plain-text within `directus_users.token`. Static Tokens are created in
 user settings inside of the Directus Data Studio User Module, or by updating the user's `token` value via API.
 
-Once you have your access token, there are two ways to pass it to the API, via the `access_token` query parameter, or in
-the request's Authorization Header.
+Once you have your access token, there are three ways to pass it to the API, in the request's Authorization Header, or
+as session cookie, or via the `access_token` query parameter.
```
Comment (paescuj) [inline docs/reference/authentication.md:30]:
```suggestion
Once you have your access token, there are three ways to pass it to the API: In the request's Authorization Header, as
session cookie, or via the `access_token` query parameter.
```

File: docs/reference/authentication.md [hunk 5]
```diff
@@ -12,30 +12,46 @@ pageClass: page-reference
...
+Cookie: directus_session_token=<token>
+```
+
+### Query Parameter
+
 ```
+?access_token=<token>
+```
+
+::: Tip
```
Comment (paescuj) [inline docs/reference/authentication.md:50]: Might be worth a
```suggestion
::: warning
```

File: docs/releases/breaking-changes.md [hunk 6]
```diff
@@ -13,6 +13,10 @@ these to a minimum, but rest assured we only make them with good reason.
 
 Starting with Directus 10.0, here is a list of potential breaking changes with remedial action you may need to take.
 
+## Version [NEXT]
```
Comment (paescuj) [inline docs/releases/breaking-changes.md:16]:
```suggestion
## Version 10.10.0
```

File: docs/self-hosted/config-options.md [hunk 7]
```diff
@@ -345,6 +345,11 @@ Redis is required when you run Directus load balanced across multiple containers
...
+| `SESSION_COOKIE_DOMAIN`             | Which domain to use for the session cookie. Useful for development mode.                                                                                                                             | --                        |
+| `SESSION_COOKIE_SECURE`             | Whether or not to use a secure cookie for the session token in cookie mode.                                                                                                                          | `false`                   |
+| `SESSION_COOKIE_SAME_SITE`          | Value for `sameSite` in the session token cookie when in cookie mode.                                                                                                                                | `lax`                     |
+| `SESSION_COOKIE_NAME`               | Name of session token cookie .                                                                                                                                                                       | `directus_session_token`  |
```
Comment (paescuj) [inline docs/self-hosted/config-options.md:352]:
```suggestion
| `SESSION_COOKIE_NAME`               | Name of session token cookie.                                                                                                                                                                        | `directus_session_token`  |
```

File: api/src/constants.ts
Comment (br41nslug) [reply api/src/constants.ts:1]: Sounds good 👍 But lets do that in a separate PR

File: docs/guides/extensions/interfaces-radio-selector-icons.md (hunk 2 above)
Comment (paescuj) [reply docs/guides/extensions/interfaces-radio-selector-icons.md]: Oh right, to the API auth page 👍 ❤️

Comment (br41nslug) [reply docs/guides/extensions/interfaces-radio-selector-icons.md]: Perhaps a link to the break change note is most appropriate 🤔 As whether this is enabled by default or not will depend on the version you're running

Comment (paescuj) [reply docs/guides/extensions/interfaces-radio-selector-icons.md]: Great idea 🚀

**Comment by paescuj** [comment]
> * I've excluded the session cookie from the RFC6750 multiple auth methods error else this will break a lot of existing installs that are using the API from the same domain as the App. Do you agree or do we make this a breaking change?

I agree, I don't see this as a strict requirement. Seems to be a good interim solution 👍 

> * I've opted to let the SSO providers (openID, SAML, oauth2) default to the new "session" mode so they are compatible with the updates to the app, but of course this is a breaking change for anyone relying on the refresh token with SSO in an external app. For that i've added an env var. Is it right to prioritize making it work with the app here?

Yes, I think this is the right way! Makes sense to adjust this at this point in time.

> * I didnt want to add an breaking changes all over the place so for the `AuthenticationService` `login` and `refresh` function signatures but I do think changing the `otp` and `session` properties to a shared config object would be nicer if we agree on that breaking change.

I think it's acceptable to add this to the list of breaking changes - better to do so now, IMO. If I understand correctly, this seems to make it more future proof 👍

File: docs/releases/breaking-changes.md [hunk 8]
```diff
@@ -13,6 +13,81 @@ these to a minimum, but rest assured we only make them with good reason.
...
 
+## Version 10.10.0
+
+### Session Cookie Based Authentication
+
+For improved security and ease of use we have implemented session based authentication and have updated the App to use
+this over the previous token based authentication. This impacts `oauth2`, `open-id` and `saml` SSO installations as they
+too will now also default to the new session based authentication in order to work with the App out-of-the-box.
+
+To keep using the old SSO functionality setting the refresh token instead of session token you can set
```
Comment (paescuj) [inline docs/releases/breaking-changes.md:24]: We need to mention that this would only work for external apps and not when used for the Data Studio

Comment (paescuj) [reply docs/releases/breaking-changes.md:24]: If there should be a need for both methods, I think it might be possible to set-up the same provider two times under a different name 🤔

File: docs/releases/breaking-changes.md [hunk 9]
```diff
@@ -13,6 +13,83 @@ these to a minimum, but rest assured we only make them with good reason.
...
+## Version 10.10.0
+
+### Session Cookie Based Authentication
+
+For improved security and ease of use we have implemented session based authentication and have updated the App to use
+this method over the previous token based authentication. This impacts `oauth2`, `open-id` and `saml` SSO installations
+as they too will now default to the new session based authentication in order to work with the App out-of-the-box.
+
+To keep using the old SSO functionality setting the refresh token instead of session token, you can set
+`AUTH_<PROVIDER>_MODE=cookie`.
```
Comment (paescuj) [inline docs/releases/breaking-changes.md:25]: I think we need to mention that this would only work for external apps and not when used for the Data Studio.

If there should be a need for both methods (Data Studio access & external app with cookie mode), theoretically it should be possible to set-up the same provider two times under a different name. Although, I'm afraid there's currently no option to hide a provider in the Data Studio.

File: .changeset/odd-buses-nail.md [hunk 10]
```diff
@@ -0,0 +1,7 @@
+---
+"@directus/app": major
+"@directus/api": major
+"@directus/sdk": patch
```
Comment (paescuj) [inline .changeset/odd-buses-nail.md:4]:
```suggestion
"@directus/sdk": patch
"@directus/env": patch
```

File: docs/releases/breaking-changes.md [hunk 11]
```diff
@@ -13,6 +13,83 @@ these to a minimum, but rest assured we only make them with good reason.
 
 Starting with Directus 10.0, here is a list of potential breaking changes with remedial action you may need to take.
 
+## Version 10.10.0
+
+### Session Cookie Based Authentication
+
+For improved security and ease of use we have implemented session based authentication and have updated the App to use
```
Comment (paescuj) [inline docs/releases/breaking-changes.md:20]: We should probably also mention the new `SESSION_COOKIE_*` configs

**Review by paescuj — APPROVED** [review]
Besides the two docs comments / change requests -> LGTM 🥳

Tests:
- [x] Auth drivers (with session / cookie mode)
  - [x] Local (obviously)
  - [x] LDAP (test server)
  - [x] OpenID (KeyCloak)
  - [x] OAuth2 (GitHub)
  - [x] SAML (test server from blackbox tests)
- [x] GraphQL auth mutations
- [x] Data & Dashboard exports
- [x] Shares
- [x] Images / Files
  - [x] File Library (File Editor, and co.)
  - [x] Block Editor
  - [x] WYSIWYG (with and without static token)
  - [x] Image Interfaces / Displays
- [x] Refresh (via low TTL)
- [x] Docs checked
