### PR TITLE
fix: clamp target dimensions when withoutEnlargement is true

### LINKED ISSUE #22391: Asset Transformation focal point and withoutEnlargement => sharp bad extract area error
### Describe the Bug

I just found out, that you can't use withoutEnlargement together with a focal point, when passing a width or height that is greater, than the width or height of the original image.

I tested this with multiple images.

The removal of the focal point resolved the issue.

### To Reproduce

Directus Version: 10.10.7

# Example:

AC_027010_02
Image Dimensions: 1024x732
Focal Point set to `512, 366` (when I remove the focal point it starts to work again)

## Working URL:
`http://192.168.0.80:8055/assets/073b87e9-6391-47e9-b671-709138414abd?format=auto&quality=85&fit=cover&width=1024&height=732&withoutEnlargement=true`

## URL's that don't work:
`http://192.168.0.80:8055/assets/073b87e9-6391-47e9-b671-709138414abd?format=auto&quality=85&fit=cover&width=1024&height=733&withoutEnlargement=true`

`http://192.168.0.80:8055/assets/073b87e9-6391-47e9-b671-709138414abd?format=auto&quality=85&fit=cover&width=1025&height=733&withoutEnlargement=true`

## Error in Browser
`{"errors":[{"message":"An unexpected error occurred.","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

## Error in Console
```
cms-directus-1  | [05:24:59.945] ERROR: extract_area: bad extract area
cms-directus-1  |     err: {
cms-directus-1  |       "type": "Error",
cms-directus-1  |       "message": "extract_area: bad extract area",
cms-directus-1  |       "stack":
cms-directus-1  |           Error: extract_area: bad extract area
cms-directus-1  |               at Sharp._read (/directus/node_modules/.pnpm/sharp@0.33.2/node_modules/sharp/lib/output.js:1417:19)
cms-directus-1  |               at Readable.read (node:internal/streams/readable:539:12)
cms-directus-1  |               at createAsyncIterator (node:internal/streams/readable:1163:54)
cms-directus-1  |               at createAsyncIterator.next (<anonymous>)
cms-directus-1  |               at getDataReadable (/directus/node_modules/.pnpm/@aws-sdk+lib-storage@3.525.1_@aws-sdk+client-s3@3.536.0/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:113:20)
cms-directus-1  |               at getDataReadable.next (<anonymous>)
cms-directus-1  |               at getChunkStream (/directus/node_modules/.pnpm/@aws-sdk+lib-storage@3.525.1_@aws-sdk+client-s3@3.536.0/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:88:20)
cms-directus-1  |               at getChunkStream.next (<anonymous>)
cms-directus-1  |               at _Upload.__doConcurrentUpload (/directus/node_modules/.pnpm/@aws-sdk+lib-storage@3.525.1_@aws-sdk+client-s3@3.536.0/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:269:22)
cms-directus-1  |               at _Upload.__doMultipartUpload (/directus/node_modules/.pnpm/@aws-sdk+lib-storage@3.525.1_@aws-sdk+client-s3@3.536.0/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:363:34)
cms-directus-1  |     }
cms-directus-1  | [05:24:59] GET /assets/073b87e9-6391-47e9-b671-709138414abd?format=auto&quality=85&fit=cover&width=1025&height=732&withoutEnlargement=true 500 505ms
```

## .env
```
PUBLIC_URL=http://192.168.0.80:8055
DIRECTUS_URL=http://192.168.0.80:8055

DIRECTUS_ADMIN_TOKEN=<VALID_VALUE>
KEY=<VALID_VALUE>
SECRET=<VALID_VALUE>

DB_CLIENT=pg
DB_CONNECTION_STRING=<VALID_VALUE>
NODE_TLS_REJECT_UNAUTHORIZED=0

CACHE_ENABLED=true
CACHE_TTL=999m
CACHE_AUTO_PURGE=true
CACHE_STORE=memory
CACHE_STATUS_HEADER=true
CACHE_VALUE_MAX_SIZE=2G

ADMIN_EMAIL=<VALID_VALUE>
ADMIN_PASSWORD=<VALID_VALUE>

CORS_ENABLED=true
CORS_ORIGIN=true

STORAGE_LOCATIONS="s3"
STORAGE_S3_DRIVER="s3"
STORAGE_S3_KEY=<VALID_VALUE>
STORAGE_S3_SECRET=<VALID_VALUE>
STORAGE_S3_ENDPOINT=<VALID_VALUE>
STORAGE_S3_BUCKET=<VALID_VALUE>
STORAGE_S3_REGION=<VALID_VALUE>
STORAGE_S3_ROOT=<VALID_VALUE>
```

## Dockerfile
```
FROM directus/directus:10.10.7

USER root
WORKDIR /directus
COPY . .
RUN corepack enable \
  && corepack prepare pnpm@8.1.1 --activate \
  # Currently required, we'll probably address this in the base image in future release
  && chown node:node /directus

ENV HOME=/directus

USER node
RUN pnpm install directus-extension-api-viewer
RUN pnpm install directus-extension-sync
RUN pnpm install directus-extension-admin-panels

# Expose the port
EXPOSE 8055

```

## docker-compose.yml
```
version: '3.8'

services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'doadmin'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus_dev'
    ports:
      - 5432:5432

  # cache:
  #   image: redis:6

  directus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    # volumes:
    # - ./uploads:/directus/uploads
    # If you want to load extensions from the host
    # - ./extensions:/directus/extensions
    depends_on:
      - database
      # - cache

    env_file:
      - ./.env

```

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by wotan-allfather**
When using `withoutEnlargement=true` with a focal point and requesting dimensions larger than the original image, Sharp throws a "bad extract area" error. This is because the extraction region is calculated based on the larger target dimensions, but the resize step cannot enlarge the image beyond its original size.

This fix clamps the target dimensions (width and height) to the original image dimensions when `withoutEnlargement` is enabled, ensuring the extraction region stays within valid bounds.

Closes #22391

## Scope

What's changed:
- Added dimension clamping logic when `withoutEnlargement` is `true`
- Target width is clamped to `Math.min(toWidth, file.width)`
- Target height is clamped to `Math.min(toHeight, file.height)`
- Added comprehensive tests for the fix

## Potential Risks / Drawbacks

- This changes the effective dimensions when `withoutEnlargement=true` and requested dimensions exceed the original. The previous behavior was to error; now it silently clamps. This is consistent with Sharp's behavior for non-focal-point resizes.

## Tested Scenarios

- [x] Both dimensions larger than original → clamped to original dimensions
- [x] Only width larger than original → width clamped, height unchanged
- [x] Both dimensions smaller than original → no change (existing behavior)
- All 16 transformation tests pass

## Review Notes / Questions

- The solution follows the approach suggested by @MauriceArikoglu in the issue thread
- The clamping is applied early in the transformation flow, before focal point calculations

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

### CODE REVIEW

File: api/src/utils/transformations.ts [hunk 1]
```diff
@@ -16,8 +16,26 @@ export function resolvePreset({ transformationParams, acceptFormat }: Transforma
...
+		let toHeight = transformationParams.height ? Number(transformationParams.height) : undefined;
+
+		/*
+		 * When withoutEnlargement is true, clamp target dimensions to original dimensions.
+		 * This prevents "bad extract area" errors when using focal points with requested
+		 * dimensions larger than the original image. Without this, the extraction region
+		 * would be calculated based on the larger target dimensions, but the resize step
+		 * can't enlarge the image, resulting in an attempt to extract from non-existent area.
+		 * See: https://github.com/directus/directus/issues/22391
+		 */
```
Comment (Nitwel) [inline api/src/utils/transformations.ts:24]:
```suggestion
		/*
		 * When withoutEnlargement is true, clamp target dimensions to original dimensions to prevent "bad extract area" errors when using focal points.
		 */
```

**Review by Nitwel — APPROVED** [review]
LGTM, would simplify the comment here a bit to be less verbose.
The only question left is if not erroring here is a wanted behavior.
@AlexGaillard what do you think?

**Comment by AlexGaillard** [comment]
>The only question left is if not erroring here is a wanted behavior.

Whilst this is technically just protecting against user error as the discussion on the issue says, I think it's ok based on the idea that a client might request height and width without user input.

File: .changeset/fix-withoutenlargement-focal-point.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@directus/api": patch
+---
+
+Fixed asset transformation error when using `withoutEnlargement` with focal point and dimensions larger than the original image. The target dimensions are now clamped to the original image dimensions when `withoutEnlargement` is enabled, preventing the "bad extract area" error from Sharp.
```
Comment (AlexGaillard) [inline .changeset/fix-withoutenlargement-focal-point.md]:
```suggestion
Fixed asset transformation error when using `withoutEnlargement` with focal point and dimensions larger than the original image. Target dimensions are now clamped to the original image dimensions.
```

File: api/src/utils/transformations.test.ts [hunk 3]
```diff
@@ -251,6 +251,109 @@ describe('resolvePreset', () => {
 		]);
 	});
 
+	test('Add resize transformation: withoutEnlargement clamps dimensions larger than original #22391', () => {
+		// Test case from issue #22391:
+		// Image is 1920x1080, but we request 2000x1200 with withoutEnlargement=true and a focal point
+		// Without the fix, this would cause "bad extract area" error in Sharp
+		// because the extraction region is calculated based on target dimensions (2000x1200)
+		// but the resize step can't enlarge beyond the original (1920x1080)
```
Comment (AlexGaillard) [inline api/src/utils/transformations.test.ts]:
```suggestion
	test('Resize transformation with withoutEnlargement clamps dimensions larger than original', () => {
```
We have git blame so we don't need all this extra context 👍

File: api/src/utils/transformations.test.ts [hunk 4]
```diff
@@ -251,6 +251,109 @@ describe('resolvePreset', () => {
...
+		};
+
+		const output = resolvePreset(
+			{ transformationParams },
+			{ ...inputFile, focal_point_x: inputFile.width / 2, focal_point_y: inputFile.height / 2 },
+		);
+
+		// Dimensions should be clamped to original (1920x1080)
+		// Since we're requesting 1920x1080 with a centered focal point on a 1920x1080 image,
+		// the intermediate dimensions will be 1920x1080, and the extract will be the full image
```
Comment (AlexGaillard) [inline api/src/utils/transformations.test.ts]:
```suggestion
```

File: api/src/utils/transformations.test.ts [hunk 5]
```diff
@@ -251,6 +251,109 @@ describe('resolvePreset', () => {
...
+					fit: 'cover',
+					withoutEnlargement: true,
+				},
+			],
+			['extract', { left: 0, top: 0, width: 1920, height: 1080 }],
+		]);
+	});
+
+	test('Add resize transformation: withoutEnlargement clamps only width when height is smaller #22391', () => {
+		// Width is larger, height is smaller - only width should be clamped
```
Comment (AlexGaillard) [inline api/src/utils/transformations.test.ts]:
```suggestion
	test('Resize transformation with withoutEnlargement clamps only width when height is smaller', () => {
```

File: api/src/utils/transformations.test.ts [hunk 6]
```diff
@@ -251,6 +251,109 @@ describe('resolvePreset', () => {
...
+		const output = resolvePreset(
+			{ transformationParams },
+			{ ...inputFile, focal_point_x: inputFile.width / 2, focal_point_y: inputFile.height / 2 },
+		);
+
+		// Width should be clamped to 1920, height stays at 500
+		// With 1920x500 target and centered focal point on 1920x1080 image:
+		// hRatio = 1080/500 = 2.16, wRatio = 1920/1920 = 1
+		// wRatio < hRatio, so factor = 1, width = 1920, height = 1080/1 = 1080
+		// Extract region: left = 0, top = (1080/2 - 500/2) = 290
```
Comment (AlexGaillard) [inline api/src/utils/transformations.test.ts]:
```suggestion
		// With 1920x500 target and centered focal point on 1920x1080 image
```

File: api/src/utils/transformations.test.ts [hunk 7]
```diff
@@ -251,6 +251,109 @@ describe('resolvePreset', () => {
...
+					fit: 'cover',
+					withoutEnlargement: true,
+				},
+			],
+			['extract', { left: 0, top: 290, width: 1920, height: 500 }],
+		]);
+	});
+
+	test('Add resize transformation: withoutEnlargement with smaller dimensions unchanged', () => {
+		// Both dimensions are smaller than original - should work normally
```
Comment (AlexGaillard) [inline api/src/utils/transformations.test.ts]:
```suggestion
	test('Resize transformation with withoutEnlargement with smaller dimensions is unchanged', () => {
```

File: api/src/utils/transformations.test.ts [hunk 8]
```diff
@@ -251,6 +251,109 @@ describe('resolvePreset', () => {
...
+
+		const output = resolvePreset(
+			{ transformationParams },
+			{ ...inputFile, focal_point_x: inputFile.width / 2, focal_point_y: inputFile.height / 2 },
+		);
+
+		// 1920x1080 -> 800x600
+		// hRatio = 1080/600 = 1.8, wRatio = 1920/800 = 2.4
+		// hRatio < wRatio, so factor = 1.8, height = 600, width = Math.round(1920/1.8) = 1067
+		// Extract region: newXCenter = 960/1.8 = 533.33, left = Math.round(533.33 - 400) = 133, top = 0
```
Comment (AlexGaillard) [inline api/src/utils/transformations.test.ts]:
```suggestion
```

**Review by AlexGaillard — DISMISSED** [review]
We can remove a lot of this extra context I think 👍

**Review by AlexGaillard — APPROVED** [review]
:cool::beans: TY @wotan-allfather
