### PR TITLE
Fix system filters

### LINKED ISSUE #25282: App: Filter shows null when is empty
### Describe the Bug

On Directus App, when choosing a field of type Text or String, the default value appears to be `null` instead of being empty.

### To Reproduce

https://github.com/user-attachments/assets/fba66848-aff9-45a1-8179-c17c45dde74f

### Directus Version

11.8.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres

### LINKED ISSUE #25290: App: Boolean value is not possible to change on quick filter
### Describe the Bug

On the App, boolean values are not being possible to be filtered as value does not change.

### To Reproduce

https://github.com/user-attachments/assets/e23a0583-b0b3-4e85-860f-37e5b288c8f1

### Directus Version

11.8.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres

### PR DESCRIPTION
**Pull request by br41nslug**
## Scope

What's changed:

- removed the string casting which was introduced in #25245 resulting in the `undefined` value getting cast to empty string `""` which in turn was cast to `null`

## Potential Risks / Drawbacks

- Could potentially affect other filter or the original fix

## Review Notes / Questions

- The original PR introduced this `value="String(value)"` casting for filters other than `_in/_nin`, I think this was an unintentional change but not sure what the actual reason behind it was.
- Should I leave in the comment about the type casting eslint issue?

---

Fixes #25290
Fixes #25282

### CODE REVIEW

File: app/src/interfaces/_system/system-filter/input-group.vue [hunk 1]
```diff
@@ -10,6 +10,10 @@ import InputComponent from './input-component.vue';
 import { fieldToFilter, getComparator, getField } from './utils';
 import { useCollection } from '@directus/composables';
 
+// Workaround because you cannot cast directly to union types inside
+// the template block without running into esling/prettier issues
```
Comment (AlexGaillard) [inline app/src/interfaces/_system/system-filter/input-group.vue]:
```suggestion
// the template block without running into eslint/prettier issues
```
typo 😄

Comment (br41nslug) [reply app/src/interfaces/_system/system-filter/input-group.vue]: haha nice catch

**Review by AlexGaillard — APPROVED** [review]
TYVM @br41nslug LGTM and @formfcw poked his head in to approve as well 👍
