### PR TITLE
Fix WYSIWYG field not being cleared after "Save and Create New"

### LINKED ISSUE #7730: Save and add new doesn't clear WYSIWYG
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

WYSIWYG fields are not cleared when "Save and add new" is used.

### To Reproduce

1. "Save and add new" on a collection that has a WYSIWYG
2. See WYSIWYG is not cleared

### What version of Directus are you using?

INTERNAL

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #7730

## Investigation

https://user-images.githubusercontent.com/42867097/131691368-4961c357-0025-4553-9ed9-28fc767e6e93.mp4

In the above video, we can see that "Title" and "Content" are both set as `null` in the beginning. After entering values to the fields, particularly "Content" the WYSIWYG field, we can observe the value does indeed turn into the HTML string on the current fields value. After clicking "Save and Create New", both fields are set as `null` again, even the "Content" field as shown in the end. 

This proves that the current code does indeed nulls/clears the WYSIWYG field, so this should be an issue with tinymce-vue itself, which is used over here:

https://github.com/directus/directus/blob/39c617c8639a44b9b97a87f85fb36769ceef6b79/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L3-L11

When we inspect the watcher of this 3rd party component, we can find the following code:

```js
  watch(modelValue, (val: string, prevVal: string) => {
    if (editor && typeof val === 'string' && val !== prevVal && val !== editor.getContent({ format: props.outputFormat })) {
      editor.setContent(val);
    }
  });
 ```
 
 Link to above code: https://github.com/tinymce/tinymce-vue/blob/540b4bf78c16bbe5335a5f1cc9c16f0b381e9117/src/main/ts/Utils.ts#L99-L103
 
 We can now see the issue is with `typeof val === 'string'`. Since we are resetting it as `null`, the if statement fails, thus not setting the content as "null" or empty.
 
 ## Solution
 
 This is why I added a check in internalValue to return an empty string if the interface is `input-rich-text-html`. Here's what it looks like after the fix:
 
https://user-images.githubusercontent.com/42867097/131694410-c0ac0b88-51dd-4164-86ae-1444a7afdc71.mp4

Do let me know if there's a better way to add this check if the if statement there seems hacky.

### CODE REVIEW

File: app/src/components/v-form/form-field.vue [hunk 1]
```diff
@@ -133,6 +133,7 @@ export default defineComponent({
 		const internalValue = computed(() => {
 			if (props.modelValue !== undefined) return props.modelValue;
 			if (props.initialValue !== undefined) return props.initialValue;
+			if (props.field.meta?.interface === 'input-rich-text-html') return '';
```
Comment (rijkvanzanten) [inline app/src/components/v-form/form-field.vue:136]: We can't rely on hardcoding any exceptions based on the specific interface. Seeing that interfaces are also extension types, this name could be anything at any time. I think we'll have to look for the fix on the TinyMCE side itself!

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Comment by rijkvanzanten** [comment]
By the way, just wanted to say keep it up with the amazing PRs. You wouldn't believe how helpful it is to have this detailed investigation/solution documentation 😍

File: app/src/components/v-form/form-field.vue (hunk 1 above)
Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: That does makes sense. Do you have a particular suggestion/proposal to TinyMCE vue? The immediate thought in my mind is turning `typeof val === 'string'` into  `typeof val === 'string' || val === null`, but it might not work since `setContent()` expects a string. Reference: https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent

or doing something like turning this

```js
if (editor && typeof val === 'string' && val !== prevVal && val !== editor.getContent({ format: props.outputFormat })) {
      editor.setContent(val);
}
```

into

```js
if (val === null) {
      editor.setContent('');
} else if (editor && typeof val === 'string' && val !== prevVal && val !== editor.getContent({ format: props.outputFormat })) {
      editor.setContent(val);
}
```

_hope I didn't make anyone's eyes bleed with my code above_ 😅

**Comment by azrikahar** [comment]
> By the way, just wanted to say keep it up with the amazing PRs. You wouldn't believe how helpful it is to have this detailed investigation/solution documentation 😍

Thank you very much for the kind words! The idea mostly is reviewing PRs can be pretty time-consuming with the context switches from other issues/features at hand, so I try to make PRs more of a "being able to understand context just from this PR without having to jump back & forth to the code/issue" kind of thing. Really glad it is proves  to be helpful 👍

**Comment by rijkvanzanten** [comment]
> The idea mostly is reviewing PRs can be pretty time-consuming with the context switches from other issues/features at hand, so I try to make PRs more of a "being able to understand context just from this PR without having to jump back & forth to the code/issue" kind of thing. Really glad it is proves to be helpful

You're absolutely 100% right about this 💯 I wish everyone would do that 🙂

File: app/src/components/v-form/form-field.vue (hunk 1 above)
Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: Your last example makes sense to me! When `val` is explicit `null`, we'll have to empty out the editor by inserting an empty string. 

That being said, we'll have to make sure that that doesn't then stage an empty string back up to the parent, causing an infinite loop.

Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: Just tested it by editing the code in node_modules ( not sure if there's a better way D: ) and it works flawlessly. Though with an additional `editor` in the if statement, becoming `if (editor && val === null)` just to be safe as the original code, seems to make sense. Will create the PR over at TinyMCE Vue 👍

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: Nice! I was actually under the impression that your code example above was part of Directus, not TinyMCE :o

Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: oh haha. Honestly I still tried to see is it possible to add the fix within Directus, but I think we'll then need to add a watcher to the value, check did it turn to null (which is after the watcher in tinymce finish firing), then set it to an empty string ourselves.

That'll be unfavorable right? or am I inadvertently overcomplicating things here? 🤔

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: Did you confirm the same problem exists within tinymce standalone? I wouldn't want to bother them with a PR that's specifically addressing an issue that only shows up within Directus 🙂

Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: hmm currently the tinymce-vue's watcher does have the typeof string check, hence it doesn't clear it's content if we set it as null. Definitely share the same sentiment of trying not to bother them with a PR if possible as well haha. 

Alright just to confirm the current expectation, if we were able to make this fix occur within `input-rich-text-html.vue`, that is acceptable right? Previously since I added the fix in in `form-field.vue`, hence that is an "unstable" fix (which I wholeheartedly agree)?

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: Oh absolutely, if it's within the interface that has the problem (in this case input-rich-text-html), then that's totally fine. As a matter of fact, that interface itself already does a lot of type checking and refreshing logic to make TinyMCE behave as it should, so it could very well be that this problem is actually caused by us missing a particular check somewhere 🙂

Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: ah got it. Once again I got confused with your previous comment:

> I think we'll have to look for the fix on the TinyMCE side itself!

and my first thought was the package itself, whereas you actually meant TinyMCE as in the interface... Oh my, sorry for the confusion again. 😂 Now I definitely agree that the check should be in the interface. Thank you for clarifying!

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: Ohhhhh I see! Yeah haha I can see how that's confusing 👉🏻👈🏻 I meant that more as the "Side where _we_ use TinyMCE" 😁

Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: So looks like the issue can be fixed here:

https://github.com/directus/directus/blob/a6e88183e99847c96c956add94a148965b9e50be/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L290-L297

where instead of `return props.value` (which is null, thus not triggering tinymce watcher), doing `return ''` works.

however I would still need to defer to you on whether `return ''` is enough or should we do `return props.value || ''` which also works. Just depends on whether falsy values will creep past the if statement above it 🤔

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: How about we update it to:

```js
 		const internalValue = computed({ 
 			get() { 
 				if (!props.value) return '';  
 				return replaceTokens(props.value, getToken()); 
 			}, 
```

Comment (azrikahar) [reply app/src/components/v-form/form-field.vue:136]: oh true that's much better. It works perfectly! thank you very much for the prompt feedback

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]: Thanks (once again!) for all your help 🙂

Comment (rijkvanzanten) [reply app/src/components/v-form/form-field.vue:136]:
```suggestion
```

**Review by rijkvanzanten — APPROVED** [review]

File: app/src/components/v-form/form-field.vue (hunk 1 above)
Comment (azrikahar) [reply app/src/components/v-form/form-field.vue]: shoot forgot to remove this change 🤦‍♂️ thanks haha
