### PR TITLE
Fix keys being optional on writes

### LINKED ISSUE #10451: Graphql mutation "create_fields_item" can't create any field because we must provide an Id for it
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello,
i would like to create fields with graphql. However, i must provide an id.

Same issue when creating fields with a collection **create_collections_item**
https://docs.directus.io/reference/system/collections/#create-a-collection

Relatives issues #5859  #5723  #5931 #5875
thx

### To Reproduce

```graphql
mutation {
  create_fields_item(
    data: {
      collection: "subscription"
      field: "date"
      type: "string"
      meta: {
        readonly: false
        hidden: false
        translations: [
          { language: "en-US", translation: "Date" }
        ]
        special: []
        interface: "input"
        collection: "subscription"
        field: "date"
      }
      schema: { name: "date" }
    }
    collection: "subscription"
  ) {
    field
  }
}

```

### Errors Shown

```json
{
    "errors": [
        {
            "message": "GraphQL validation error.",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_EXCEPTION",
                "graphqlErrors": [
                    {
                        "message": "Field \"directus_fields_meta_input.id\" of required type \"Int!\" was not provided.",
                        "locations": [
                            {
                                "line": 7,
                                "column": 13
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

v15.14.0

### What database are you using?

sqlite

### What browser are you using?

chrome,brave

### What operating system are you using?

linux

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

Generate different types for writes in GQL fields/collections

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- None

---

Fixes #10451

### CODE REVIEW

File: api/src/services/graphql/resolvers/system-admin.ts [hunk 1]
```diff
@@ -6,197 +6,207 @@ import { ExtensionsService } from '../../extensions.js';
...
-							toInputObjectType(Field.clone('create_directus_collections_fields'), { postfix: '_input' }).NonNull,
-						],
-					}).NonNull,
-				},
-				resolve: async (_, args) => {
-					const collectionsService = new CollectionsService({
-						accountability: gql.accountability,
-						schema: gql.schema,
-					});
+	if (gql.accountability?.admin === false) {
```
Comment (licitdev) [inline api/src/services/graphql/resolvers/system-admin.ts:19]: Account for the optional chaining which could return `undefined`

```suggestion
	if (!gql.accountability?.admin) {
```

File: api/src/services/graphql/resolvers/system.ts [hunk 2]
```diff
@@ -222,57 +213,9 @@ export function injectSystemResolvers(
...
-		name: 'directus_extensions',
-	});
-
-	const composers: BaseTypeComposers = {
-		Collection,
-		Field,
-		Relation,
-		Extension,
-	};
+	const Collection = getCollectionType(schemaComposer, schema, 'read');
```
Comment (ComfortablyCoding) [inline api/src/services/graphql/resolvers/system.ts:216]: Now that we do not pass these objects into `resolveSystemAdmin` we should be able to move them into the read access check. This will provide a small perf improvement when access is denied

Comment (ComfortablyCoding) [reply api/src/services/graphql/resolvers/system.ts]: Refactored via f64620818be658325a73a56c8ba6efdd4246932d

**Review by ComfortablyCoding — COMMENTED** [review]
LGTM 🚀, leaving off approval until my changes can be checked and secondary review is added

**Review by br41nslug — APPROVED** [review]
Bit of a pain to go through the diffs after the refactor but good changes 🎉
