### PR TITLE
RTL: Fix context menu positioning

### LINKED ISSUE #25649: RTL: Field menu options alignment is wrong
Image

### PR DESCRIPTION
**Pull request by AlexGaillard**
## Scope

What's changed:

- Context menu is now right aligned for RTL

Screenshot 2025-08-14 at 4 22 36 PM

## Potential Risks / Drawbacks

- None I can think of

## Tested Scenarios

- Tested both LTR and RTL
- Tested on small screen

## Review Notes / Questions

- There is a bit of a mix of logic going on here. on `form-field` I used the isRTL computed to place the `v-menu` at `bottom-end` instead of `bottom-start` so it's right aligned, is this confusing given that it should technically be `bottom-start` in relation to RTL world? 🙃If so then the style change will need to be made in `v-menu` rather than `form-field`
- The modifiers for popperjs are hella confusing, is there a better way to handle the styles than the override I went with? 

## Checklist

- [ ] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25649 
 <div id='description'>
    <a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This PR fixes context menu positioning issues in RTL layouts by refactoring form-field and v-menu components with RTL support. A new checkPlacement function was implemented for correct menu placement, and conditional logic ensures consistent UI experience across LTR and RTL interfaces. Test files were updated with createTestingPinia for improved RTL testing.

</div>

### CODE REVIEW

File: app/src/components/v-form/form-field.vue [hunk 1]
```diff
@@ -167,7 +172,7 @@ function useComputedValues() {
 		class="field"
 		:class="[field.meta?.width || 'full', { invalid: validationError }]"
 	>
-		<v-menu v-if="!isLabelHidden" placement="bottom-start" show-arrow arrow-placement="start">
+		<v-menu v-if="!isLabelHidden" :placement="isRTL ? 'bottom-end' : 'bottom-start'" show-arrow arrow-placement="start">
```
Comment (formfcw) [inline app/src/components/v-form/form-field.vue]: Let’s keep the placement value at `bottom-start` here, since `start` means `left` in LTR and `right` in RTL. Instead, let’s make the change in the `v-menu` component — see the other comment.

File: app/src/components/v-menu.vue [hunk 2]
```diff
@@ -395,13 +400,21 @@ function usePopper(
 								case 'bottom-start':
```
Comment (formfcw) [inline app/src/components/v-menu.vue:412]: Let’s make the change in the `bottom-start` block and remove the `bottom-end` block. This way it will also work for the `top-start` placement.

Example (not tested):
```ts
case 'top-start':
case 'bottom-start':
	x = props.arrowPadding;
	if (isRTL.value) x *= -1;
	break;
```

**Review by formfcw — CHANGES_REQUESTED** [review]
Thank you for the update @AlexGaillard :heart:

Looks good, just one minor thing and please include a changeset.

File: app/src/components/v-menu.vue (hunk 2 above)
Comment (AlexGaillard) [reply app/src/components/v-menu.vue:412]: No matter what, I'm pretty sure we'll have to be passing in `bottom-end` to the popper, so I don't think this will work

File: .changeset/real-kings-learn.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/app': patch
+---
+
+Add RTL support for popper context menu
```
Comment (formfcw) [inline .changeset/real-kings-learn.md]: Let’s use past tense for consistency.

```suggestion
Added RTL support for popper context menu
```

File: app/src/components/v-menu.vue [hunk 4]
```diff
@@ -281,11 +286,19 @@ function usePopper(
 		stop();
 	});
 
+	function checkPlacement() {
+		if (isRTL.value && options.value.placement.includes('start')) {
+			return options.value.placement.replace(/start/g, 'end');
+		}
+
+		return options.value.placement;
+	}
```
[the remark this answers is not in the document]
Comment (formfcw) [reply app/src/components/v-menu.vue]: I agree here

File: app/src/components/v-menu.vue [hunk 5]
```diff
@@ -281,11 +286,19 @@ function usePopper(
...
+
 	watch(
 		options,
 		() => {
 			popperInstance.value?.setOptions({
-				placement: options.value.attached ? 'bottom-start' : options.value.placement,
+				placement: options.value.attached ? 'bottom-start' : (checkPlacement() as Placement),
```
Comment (formfcw) [inline app/src/components/v-menu.vue]: Let’s include the `options.value.attached ? 'bottom-start'` condition in the `checkPlacement` function, since we should also reverse `bottom-start` to `bottom-end` when in RTL mode (when `options.value.attached` is `true`). In addition, it might make sense to rename `checkPlacement` to `getPlacement`.

File: app/src/components/v-menu.vue (hunk 2 above)
Comment (formfcw) [reply app/src/components/v-menu.vue:412]: Yes, that makes sense with your new approach.

File: app/src/components/v-menu.vue [hunk 6]
```diff
@@ -301,7 +314,7 @@ function usePopper(
 	function start() {
 		return new Promise((resolve) => {
 			popperInstance.value = createPopper(reference.value!, popper.value!, {
-				placement: options.value.attached ? 'bottom-start' : options.value.placement,
+				placement: options.value.attached ? 'bottom-start' : (checkPlacement() as Placement),
```
Comment (formfcw) [inline app/src/components/v-menu.vue]: see https://github.com/directus/directus/pull/25697#discussion_r2282103787

File: app/src/components/v-menu.vue [hunk 7]
```diff
@@ -395,13 +408,21 @@ function usePopper(
 								case 'bottom-start':
 									x = props.arrowPadding;
 									break;
+								case 'bottom-end':
```
Comment (formfcw) [inline app/src/components/v-menu.vue:416]: Let’s also apply this to `top-end`.

```suggestion
								case 'top-end':
								case 'bottom-end':
```

However, let’s make sure to test all these cases in LTR and RTL.

**Review by formfcw — CHANGES_REQUESTED** [review]
Thanks for the changes. It seems tricky with popperjs.
I will test all the variations later.

File: app/src/components/v-menu.vue (hunk 7 above)
Comment (AlexGaillard) [reply app/src/components/v-menu.vue:416]: Added tests

**Review by formfcw — APPROVED** [review]
Thank you for the changes. Great work! :heart:

LGTM :rocket:
