### PR TITLE
Fix translating m2a filters on GQL only when applicable

### LINKED ISSUE #22502: `parseFilter` incorrectly converts entry names starting with `item__` to `item:`
### Describe the Bug

The `parseFilter` utility function always converts filter entry names that start with `item__` and are objects to `item:`:

https://github.com/directus/directus/blob/333ec524ee92496183fd6602850aeb933c54e9d6/packages/utils/shared/parse-filter.ts#L119-L120

This could potentially lead to problems when the user actually has a field named `item__<something>` and wants to filter that field. This conversion was initially introduced in https://github.com/directus/directus/pull/15162 as fix to not being able to filter M2A relations in GraphQL.

This functionality needs to be retained, but either pulled out of `parseFilter` or only optionally apply, if we know that the filters are coming from GraphQL (and are actually within a M2A? Cause otherwise the same problem persists in GraphQL. Or that is then just an inherent restriction of GraphQL, similar to reserved keywords or collections starting with underscore).

Additionally, this simple replacement breaks if the user uses a different field name, other than `item` in their M2A relation setup.

### To Reproduce

N/A

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- only rename a2o relation `field__collection` when it matches against the relational schema.

E.g.
```json
{
  "id": { "_eq": 1 },
  "blocks": {
    "item__text": { // will be renamed to `item:text`
      "id": { "_eq": 1 },
       "content": { "_eq": "Hello World" },
    },
  },
}
```

## Potential Risks / Drawbacks

- Could possibly follow collections not correctly and miss a case

## Review Notes / Questions

- Now this is only scoped to GQL so the failure scope is a lot smaller

---

Fixes #22502 
Closes SER-125

### CODE REVIEW

**Comment by ComfortablyCoding** [comment]
Moved to draft due to conflicts

File: api/src/services/graphql/utils/replace-m2a.ts [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+		const m2o_relation = schema.relations.find(
+			(relation) => relation.collection === collection && relation.field === key,
+		);
+
+		const a2o_relation = schema.relations.find(
+			(relation) =>
+				relation.collection === collection &&
+				key.startsWith(relation.field + '__') &&
+				relation.meta?.one_allowed_collections?.some((collection) => collection === key.split('__')[1]),
+		);
```
Comment (ComfortablyCoding) [inline api/src/services/graphql/utils/replace-m2a.ts:20]: Could we utilize `getRelationInfo` here and extract the `relationType` 🤔

File: api/src/services/graphql/schema/parse-query.ts [hunk 2]
```diff
@@ -127,9 +129,19 @@ export async function getQuery(
 
 	query.alias = parseAliases(selections);
 	query.fields = await parseFields(selections);
+
 	if (query.filter) query.filter = replaceFuncs(query.filter);
+
 	query.deep = replaceFuncs(query.deep as any) as any;
 
+	if (collection && schema) {
```
Comment (ComfortablyCoding) [inline api/src/services/graphql/schema/parse-query.ts:137]:
```suggestion
	if (collection) {
```

File: api/src/services/graphql/utils/replace-m2a.ts [hunk 3]
```diff
@@ -0,0 +1,81 @@
+import type { Filter, NestedDeepQuery, SchemaOverview } from '@directus/types';
```
Comment (ComfortablyCoding) [inline api/src/services/graphql/utils/replace-m2a.ts:1]: Should we rename this file to `filter-replace-m2a` so it is more accurate?

File: api/src/services/graphql/utils/replace-m2a.ts [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+			const m2o_relation = schema.relations.find(
+				(relation) => relation.collection === collection && relation.field === key,
+			);
+
+			const a2o_relation = schema.relations.find(
+				(relation) =>
+					relation.collection === collection &&
+					key.startsWith(relation.field + '__') &&
+					relation.meta?.one_allowed_collections?.some((collection) => collection === key.split('__')[1]),
+			);
```
Comment (ComfortablyCoding) [inline api/src/services/graphql/utils/replace-m2a.ts:64]: Same as https://github.com/directus/directus/pull/24830/files#r2056361437

File: api/src/services/graphql/utils/replace-m2a.ts [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+
+	return filter;
+}
+
+export function filterReplaceM2ADeep(
+	deep_arg: NestedDeepQuery | null | undefined,
+	collection: string,
+	schema: SchemaOverview,
+) {
+	if (!deep_arg) return deep_arg;
```
Comment (ComfortablyCoding) [inline api/src/services/graphql/utils/replace-m2a.ts:45]: For the sake of consistency should we update `filterReplaceM2A` to do the same as `filterReplaceM2ADeep` and return for `null`/`undefined` filter? Currently we require `filter` for `filterReplaceM2A` but not `deep` for `filterReplaceM2ADeep`

File: api/src/services/graphql/utils/replace-m2a.ts (hunk 1 above)
Comment (Nitwel) [reply api/src/services/graphql/utils/replace-m2a.ts]: Didn't went with getRelationInfo but very close to it so it's a bit cleaner now.

**Review by licitdev — COMMENTED** [review]
We are getting an error when filtering on the m2a level. The existing blackbox tests should be passing, or else this would be a breaking change.

```js
{
  errors: [
    {
      message: `You don't have permission to access fields "item__test_items_m2a_circles_uuid", "name" in collection "test_items_m2a_shapes_children_uuid" or they do not exist. Queried in "children".`,
      extensions: {
        code: 'FORBIDDEN',
        reason: `You don't have permission to access fields "item__test_items_m2a_circles_uuid", "name" in collection "test_items_m2a_shapes_children_uuid" or they do not exist. Queried in "children".`
      },
      locations: [ { line: 1, column: 9 } ],
      path: [ 'test_items_m2a_shapes_uuid' ]
    }
  ]
}
```

https://github.com/directus/directus/blob/fbc7febe11c634331c4c251f70291215dae0d532/tests/blackbox/tests/db/routes/items/m2a.test.ts#L465-L481

**Comment by Nitwel** [comment]
Problem being that I tested everything locally and it was just working fine, i.e. filtering m2a's was working just fine.

**Comment by ComfortablyCoding** [comment]
### Tests
- [x] Expect m2a filter to work
- [x] Expect m2a filter nested in an _and to work
- [x] Expect m2a filter nested in an _or to work
- [x] Expect m2a nested filter to work
- [x] Expect m2a with deep filter to work

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
