### PR TITLE
SDK Fix realtime infinite auth loop

### LINKED ISSUE #19583: @directus/sdk - Realtime auth token sent to server many times per second
### Describe the Improvement

When inspecting an open socket, it seems to send the access token many times per second, and I think this might be the issue:

```js

if (message['type'] === 'auth' && hasAuth(currentClient)) {
  const access_token = await currentClient.getToken();
  
  if (access_token) {
	  ws.send(auth({ access_token }));
	  continue;
  }
}

```

When the server sends back an auth ok, it triggers the socket to send the access token - is this required?

Would this work instead?

```js

if (message['type'] === 'auth' && message['status'] !== 'ok' && hasAuth(currentClient)) {
  const access_token = await currentClient.getToken();
  
  if (access_token) {
	  ws.send(auth({ access_token }));
	  continue;
  }
}

```

It just makes it hard to debug in the network tab

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #19583

- Fixed the SDK responding to the authentication confirmation message with new authentication causing an infinite loop between client and server
- Fixed leaking memory on event listeners by making sure each event handler gets removed before re-adding a new one

### CODE REVIEW

File: sdk/src/realtime/composable.ts [hunk 1]
```diff
@@ -111,7 +111,12 @@ export function realtime(config: WebSocketConfig = {}) {
 				if (!message) continue;
 
 				if ('type' in message) {
-					if (message['type'] === 'auth' && hasAuth(currentClient)) {
+					if (
+						message['type'] === 'auth' &&
+						'status' in message &&
+						message['status'] === 'error' &&
+						hasAuth(currentClient)
```
Comment (paescuj) [inline sdk/src/realtime/composable.ts:118]: Should we make it even more specific by checking the error code too?
In an own client implementation I used the following condition:
```js
data.type === 'auth' &&
data.status === 'error' &&
data.error.code === 'TOKEN_EXPIRED'
```

**Review by rijkvanzanten — APPROVED** [review]
