### PR TITLE
Fix use-items loading state when an existing request gets canceled

### LINKED ISSUE #16883: After upgrade to 9.22.1 app content shows empty table occasionally
### Describe the Bug

https://user-images.githubusercontent.com/5406765/209098901-d9b02887-7c57-4111-a57e-955f98280ed9.mov

### To Reproduce

1. Upgrade to 9.22.1
2. Start Directus locally
3. Login as admin, go to `/admin/content/`
4. Switch between different collections, the problem occurs.

### Errors Shown

No

### What version of Directus are you using?

v9.22.1

### What version of Node.js are you using?

v18.12.1

### What database are you using?

SQLite

### What browser are you using?

Google Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Closes #16883

Within the use-items composable, whenever a request starts, it'll attempt to cancel an existing request that has yet to be completed:

https://github.com/directus/directus/blob/602f5db4f73101fda2292de3487635b2ae046b49/packages/shared/src/composables/use-items.ts#L122

However even if an **existing** request gets canceled, it will still enter it's `finally` block here and clear the loadingTimeout that is already set by the **current** request:

https://github.com/directus/directus/blob/602f5db4f73101fda2292de3487635b2ae046b49/packages/shared/src/composables/use-items.ts#L194-L205

but this causes the **current** request to not being able to set loading to true, so it's causing an odd "No Items" state when this happens, as seen below.

https://user-images.githubusercontent.com/42867097/209074826-369be24c-a14f-4a71-afa2-a57a21e18db4.mp4

### Example timeline of how this problem occurs

(`finally` below refers to the `finally` block of try/catch/finally)

1. Request A starts
2. Request A assigns loadingTimeout
3. Request A loadingTimeout finishes and set loading to true
4. Request B starts
5. Request B cancels request A
6. Request B assigns loadingTimeout
7. Request A is canceled, so it goes to Request A `finally` to clear loadingTimeout, but it shouldn't because this ends up clearing Request B's loadingTimeout, so now loading is still never set to true at all
8. Since Request B was never able to set loading to true, and it is still in pending fetching the items (`items.length` is zero), the "No Items" table body in `<v-table>` is (mistakenly) shown:

    https://github.com/directus/directus/blob/602f5db4f73101fda2292de3487635b2ae046b49/app/src/components/v-table/v-table.vue#L42-L46

9. Request B completes, and it goes to Request B `finally` to clear loadingTimeout (but it's already cleared due to Request A)

### After PR

https://user-images.githubusercontent.com/42867097/209074879-7cfa7750-69f4-44af-a5fa-739b7472b516.mp4

### Additional changes

I've also opted to rename `currentRequest` to `existingRequest`, as it feels like it's slightly more accurate to describe it is attempting to cancel a request that is already (and still) running, and not the "current" request. Another reason is partially it might be a bit confusing if `isCurrentRequestCanceled = false` is followed up directly by `currentRequest?.cancel()`.
 
## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: packages/shared/src/composables/use-items.ts [hunk 1]
```diff
@@ -60,11 +60,16 @@ export function useItems(collection: Ref<string | null>, query: ComputedQuery, f
...
+		filter: null,
+	};
 	let loadingTimeout: NodeJS.Timeout | null = null;
 
 	const fetchItems = throttle(getItems, 500);
 
+	// can this be removed to prevent double fetches?
 	if (fetchOnInit) {
 		fetchItems();
 	}
```
Comment (azrikahar) [inline packages/shared/src/composables/use-items.ts:75]: @rijkvanzanten is there a particular edge case where this is still required, or perhaps it's no longer applicable?

It seems like it was first added in https://github.com/directus/directus/pull/2893/files#diff-0d53067b4a1ccc2bb89ebeb8bfc7bbda1c7f94922e75668b223feaa0c64741b5 for calendar layout, to specifically opt-out calendar layout from fetching on init, with the watcher's `immediate` option based on `fetchOnInit`'s value.

However in the advanced filters PR https://github.com/directus/directus/pull/8570/files#diff-9898b066ab280a7cd156ae0d26bea7373f99c17d512e2a20d9899fe8c57ed907, the watcher is now always set to `immediate: true`, so `fetchOnInit` turned out to be making an additional redundant request. Though the request cancelation kicks in to cancel it anyways.

Comment (rijkvanzanten) [reply packages/shared/src/composables/use-items.ts:75]: Great question. Everything seems to work just fine when removing it

Comment (rijkvanzanten) [reply packages/shared/src/composables/use-items.ts:75]: >  Though the request cancelation kicks in to cancel it anyways.

Which is OK for the app, but still causes the API to use valuable resources!

**Review by rijkvanzanten — APPROVED** [review]
