### PR TITLE
Fix redirection race condition after SSO login

### LINKED ISSUE #19421: last_page is ignored if user logs in via OAuth
### Describe the Bug

If a user logs in using username and password, the user is always presented with the last page he/she viewed last time. For another user who logs in via OAuth authentication (i.e. Google or Keycloak), the user always landed on the content page. Due to content page special `last-accessed-collection` flag stored in `localStorage`, it creates the impression that last_page redirection works.

### To Reproduce

1. Setup 2 users, one - `user1` - with default login provider using username and password, the other - `user2` - with another provider like Google or Keycloak. Both users are app admins to avoid any permission issue.
2. Login as `user1`, then navigate to `File Library` screen before logging out
3. Login again as `user1`, it should render `File Library` screen after logging in
4. Login as `user2`, then navigate to `File Library` screen before logging out
5. Login again as `user2`, it renders `Content` screen instead of `File Library` as expected

Tracking down the issue to [continue-as.vue](https://github.com/directus/directus/blob/772bc2ac375c13517ed5997793aefbc0ec56f4e5/app/src/routes/login/components/continue-as.vue#L67), `hydrateAndLogin()` is being invoked twice. The first time with the correct `lastPage.value`, while it is null in the second call.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by licitdev**
## Scope

What's changed:

- Fixed redirection race condition after SSO login

## Potential Risks / Drawbacks

- 

## Review Notes / Questions

- 

---

Fixes #19421

### CODE REVIEW

File: app/src/routes/login/components/continue-as.vue [hunk 1]
```diff
@@ -49,6 +49,7 @@ async function fetchUser() {
 
 async function hydrateAndLogin() {
 	await hydrate();
+	await userPromise;
```
Comment (Nitwel) [inline app/src/routes/login/components/continue-as.vue:52]: Why are not calling the fetchUser() function here directly?

Comment (licitdev) [reply app/src/routes/login/components/continue-as.vue:52]: It's a race condition as the function had already ran. We should not run again as it's unnecessary.

**Review by Nitwel — APPROVED** [review]

**Review by AlexGaillard — APPROVED** [review]
LGTM2
