### PR TITLE
Reduce the refresh of access token while still fresh

### LINKED ISSUE #8449: Window switching between access token refresh causes error 403
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Each time the browser window becomes active, an access token refresh is triggered.
When any new request is sent to the server right before the response for the access token refresh is received, it will result in a 403 if the server side has refreshed the access token.

https://user-images.githubusercontent.com/26413686/135439273-97c1f57b-d55b-44b2-9381-04a28833fcd8.mov

### To Reproduce

Switch to the app window and double click on a link that gets data from server.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by licitdev**
Fixes #8449. Reduces the need to do a refresh when the access token is still fresh (10 seconds before expiry).
A refresh will only be done when it is within 10 seconds from expiry or after it has expired.

@rijkvanzanten I am wondering if it's a good idea to add a delay to the request's queue if a refresh request is running.
https://github.com/directus/directus/blob/cb7b6a91084d0c71e886a8d0481280ad066a6e63/app/src/stores/requests.ts 
Thinking of tweaking `startRequest()` to hold further requests... 

Edit: Tested and the same issue occurs when there's a coincidental access token refresh.
But the odds are significantly smaller after this PR.

### CODE REVIEW

**Comment by azrikahar** [comment]
this might/should relate to #8337 🤔

>  I am wondering if it's a good idea to add a delay to the request's queue if a refresh request is running.
Thinking of tweaking startRequest() to hold further requests...

FWIW, had the exact same thought before I went with the debounce approach tbh 😂 Does feel like that is the better approach... but we'll need to tweak/modify the current `p-queue` setting used to queue the requests. Looked into it before, there is the option to set a [priority](https://github.com/sindresorhus/p-queue#priority) (so we can ensure refresh token runs first), but not about  how the "hold further requests" part mesh with it.

**Comment by licitdev** [comment]
> FWIW, had the exact same thought before I went with the debounce approach tbh 😂 Does feel like that is the better approach... 

Saw that debounce but that is to prevent multiple refreshes if window is switched multiple times within a second.

Two issues currently after the debounce fix.
1. Every time window is in focus, an access token refresh is triggered. In my opinion, that is excessive given that each JWT has a short enough expiry of 15 mins by default compared to refresh token of 7 days. (Should be resolved with the first commit)
2. Should a refresh request be triggered, if any other server requests is sent, it may cause a 403 depending on latency. (Currently looking into a fix...) 

> we'll need to tweak/modify the current `p-queue` setting used to queue the requests. Looked into it before, there is the option to set a [priority](https://github.com/sindresorhus/p-queue#priority) (so we can ensure refresh token runs first), but not about how the "hold further requests" part mesh with it.

Thank you @azrikahar for the insight, I think it may have to be used in conjunction with pause. 
Priority will allow the access token refresh to jump the queue, but other lower priority functions to run.

**Comment by licitdev** [comment]
@azrikahar Done. I have removed the debounce as the 1 second delay.
It causes an issue if token is expired and user triggers a server action within that second (eg: POST to `/users/me/track/page`).
Please let me know if this PR works for you. 

For testing, the return statement on line 75 can be commented to allow for access token refresh to trigger each time window is in focus.

https://github.com/directus/directus/blob/c32bd0564e9539343272417ee0271fce82e7644d/app/src/auth.ts#L74-L76

File: app/src/auth.ts [hunk 1]
```diff
@@ -76,9 +76,6 @@ export async function refresh({ navigate }: LogoutOptions = { navigate: true }):
 	}
 
 	try {
-		// Delete the token header if it still exists
-		delete api.defaults.headers.Authorization;
-
 		const response = await api.post('/auth/refresh');
```
Comment (rijkvanzanten) [inline app/src/auth.ts:79]: The reason it was there is because you can't request a /refresh with an access token (as it would still validate that access token). We should update this call to explicitly nullify the authorization header for this particular call:

```suggestion
		const response = await api.post('/auth/refresh', { headers: { 'Authorization': undefined }});
```

Comment (licitdev) [reply app/src/auth.ts]: Thank you! @rijkvanzanten

File: app/src/auth.ts [hunk 2]
```diff
@@ -95,9 +103,11 @@ export async function refresh({ navigate }: LogoutOptions = { navigate: true }):
 
 		appStore.accessTokenExpiry = Date.now() + response.data.data.expires;
 		appStore.authenticated = true;
+		isRefreshing = false;
 
 		return accessToken;
 	} catch (error: any) {
+		isRefreshing = false;
```
[the remark this answers is not in the document]
Comment (licitdev) [reply app/src/auth.ts:110]: Got it, thank you! 🤓

**Review by rijkvanzanten — APPROVED** [review]
