### PR TITLE
Fix File Limit Erroring Logic and DB Merge Logic

### LINKED ISSUE #20216: Uploading a file with size above FILES_MAX_UPLOAD_SIZE leaves a half uploaded file
### Describe the Bug

I set the FILES_MAX_UPLOAD_SIZE value to '10mb', when I try to upload a 20mb image, it uploads the image first (progress bar completes, it takes a while) and then gives me back an error saying the uploaded size is too much.

Screenshot 2023-10-27 at 10 02 27

It then leaves a file which did not succeed, but is in my library.

### To Reproduce

- Set the FILES_MAX_UPLOAD_SIZE='10mb'
- Go to your library and upload a file larger then that
- See how it leaves a failed upload behind, and see how it takes until the image is uploaded to throw the error

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #20331: `Replace File` wipes fields
### Describe the Bug

https://github.com/directus/directus/assets/22613842/b754b64d-7db8-45fb-81c2-97fcc64a28e1

Inside the App’s File Library, using the `Replace File` button under the thumbnail wipes Title, Description and Tags data. Most of the time, we are using `Replace File` to upload an updated version of a certain file/image, this forces us to fish the old information from the Revisions panel.

Is this expected behaviour? In that case I would suggest to add an `Update File` button to retain those infos.

### To Reproduce

Add Title, Description and Tags information to a file/image and use the `Replace File` function

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Edit 1:** Title was originally set automatically by Directus (based on filename), I manually wrote Description and added Tags. In the video I’m re-uploading the same file, however Directus isn’t picking up the Title on FileReplace.

### PR DESCRIPTION
**Pull request by connorwinston**
## Scope

What's changed:

- File Upload Error Handling
  - Replacing a file now uploads it as a temporary file, then once successful promotes it
  - Limit errors now throw in the File Service not the Controller
- File Metadata Merge Logic

## Potential Risks / Drawbacks

- Title, Description, and Metadata will no longer overwrite data

## Review Notes / Questions

- Please SPECIFICALLY test with a file upload size limit

---

Fixes #20331 and Fixes #20216

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@ComfortablyCoding Whaddayathink of these changes? 👀

File: packages/types/src/files.ts [hunk 1]
```diff
@@ -21,3 +23,7 @@ export type File = {
 	tags: string | null;
 	metadata: Record<string, any> | null;
 };
+
+export type FileStream = {
```
Comment (rijkvanzanten) [inline packages/types/src/files.ts:27]: Does busboy not export this by default? Odd!

File: api/src/services/files.ts [hunk 2]
```diff
@@ -107,12 +165,31 @@ export class FilesService extends ItemsService {
 			const stream = await storage.location(data.storage).read(payload.filename_disk);
 			const { height, width, description, title, tags, metadata } = await this.getMetadata(stream);
 
-			payload.height ??= height ?? null;
-			payload.width ??= width ?? null;
-			payload.description ??= description ?? null;
-			payload.title ??= title ?? null;
-			payload.tags ??= tags ?? null;
-			payload.metadata ??= metadata ?? null;
+			if (!payload.height && height) {
```
Comment (rijkvanzanten) [inline api/src/services/files.ts:168]: These should overwrite no matter what right?

File: api/src/services/files.ts [hunk 3]
```diff
@@ -65,39 +71,91 @@ export class FilesService extends ItemsService {
...
+			}
 		} catch (err: any) {
 			logger.warn(`Couldn't save file ${payload.filename_disk}`);
 			logger.warn(err);
 
-			await this.deleteOne(primaryKey);
+			await cleanUp();
 
-			throw new ServiceUnavailableError({ service: 'files', reason: `Couldn't save file ${payload.filename_disk}` });
+			if(err instanceof ContentTooLargeError) {
```
Comment (rijkvanzanten) [inline api/src/services/files.ts:138]:
```suggestion
			if (err instanceof ContentTooLargeError) {
```

File: api/src/services/files.ts [hunk 4]
```diff
@@ -65,39 +71,91 @@ export class FilesService extends ItemsService {
...
+			// If this is a replacement, we'll write the file to a temp location first to ensure we don't overwrite the existing file if something goes wrong
+			if (isReplacement === true) {
+				await disk.write(tempFilenameDisk, stream, payload.type);
+			} else {
+				// If this is a new file upload, we'll write the file to the final location
+				await disk.write(payload.filename_disk, stream, payload.type);
+			}
+
+			// Check if the file was truncated (if the stream ended early) and throw limit error if it was
+			// @ts-expect-error
```
Comment (rijkvanzanten) [inline api/src/services/files.ts:127]: Lets type this in a way that doesn't disable TS

File: api/src/services/files.ts [hunk 5]
```diff
@@ -65,39 +71,91 @@ export class FilesService extends ItemsService {
...
 
+		// Used to clean up if something goes wrong
+		const cleanUp = async () => {
+			// If this is a new file upload that failed, we need to delete the DB record
+			if (isReplacement === false) {
+				await this.deleteOne(primaryKey!);
+			}
+
+			try {
+				if(isReplacement === true ){
```
Comment (rijkvanzanten) [inline api/src/services/files.ts:103]:
```suggestion
				if (isReplacement === true ){
```

File: api/src/services/files.ts (hunk 2 above)
Comment (ConnorSimply) [reply api/src/services/files.ts:168]: This overwrites the height if the user does not supply the height in the upload, and there is a new height. If the user supplies their own height we ignore, and if there is no new height detected then it won't set the field to null.

Are you saying that it _should_ set the field to null?

File: packages/types/src/files.ts (hunk 1 above)
Comment (ConnorSimply) [reply packages/types/src/files.ts:27]: NO! Drove me crazy. This is not exported from busboy or the busboy types from what I can find.

File: api/src/services/files.ts (hunk 4 above)
Comment (ConnorSimply) [reply api/src/services/files.ts:127]: I tried so many different ways but I don't know what was going on but I could not get it to type this right. Could use a look at this :)

Comment (ComfortablyCoding) [reply api/src/services/files.ts:127]: Some options I see that would resolve the error are:
1. Fix the function type (and any other dependant functions) to be FileStream only
2. Type assert the statement here (e.g. `(stream as FileStream).truncated`) as at this point we know it should have this property.
3. Add it as a property on all Readable Types
```ts
// e.g.
declare module 'stream' {
    interface Readable {
        truncated: boolean
    }
}
```

I would say 1 and 2 are our best options with 3 as a last resort as it will place that property on all Readable types.

File: api/src/services/files.ts [hunk 6]
```diff
@@ -65,39 +71,91 @@ export class FilesService extends ItemsService {
...
+			// delete the previously saved file and thumbnails to ensure they're generated fresh
+			for await (const filepath of disk.list(String(primaryKey))) {
+				await disk.delete(filepath);
+			}
+
+			// Upgrade the temp file to the final filename
+			await disk.copy(tempFilenameDisk, payload.filename_disk);
+
+			// Delete the temp file
+			await disk.delete(tempFilenameDisk);
```
Comment (ComfortablyCoding) [inline api/src/services/files.ts:158]: Instead of a copy and delete should we do a move here? Seems more efficient.

File: packages/types/src/files.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply packages/types/src/files.ts:27]: busboy seems to expect it to be of type `Readable` but this does not have a truncate property. Looks like the types are outdated.

**Review by ComfortablyCoding — COMMENTED** [review]
A few points of feedback but overall LGTM! Seems to be a nice improvement.

File: packages/types/src/files.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply packages/types/src/files.ts:27]: busboy seems to expect it to be of type `Readable` but this does not have a truncate property. Looks like the types are outdated.

File: api/src/services/files.ts (hunk 4 above)
Comment (ComfortablyCoding) [reply api/src/services/files.ts:127]: Some options I see that would resolve the error are:
1. Fix the function type (and any other dependant functions) to be FileStream only
2. Type assert the statement here (e.g. `(stream as FileStream).truncated`) as at this point we know it should have this property.
3. Add it as a property on all Readable Types
```ts
// e.g.
declare module 'stream' {
    interface Readable {
        truncated: boolean
    }
}
```

I would say 1 and 2 are our best options with 3 as a last resort as it will place that property on all Readable types.

Comment (ConnorSimply) [reply api/src/services/files.ts:127]: 1. The type will not always be FileStream, not all file uploads go through BusBoy...importing via URL is just a normal Stream. Only streams through BusBoy have the truncated property added.
2. Stream will not always have that property, will this work?
3. BusBoy streams are not the only streams in the api, would this pollute other streams that don't have it?

File: api/src/services/files.ts (hunk 6 above)
Comment (ConnorSimply) [reply api/src/services/files.ts]: Most of the move functions use copy and then delete, but it may be more efficient for some drivers. I made the change.

File: api/src/services/files.ts (hunk 4 above)
Comment (ComfortablyCoding) [reply api/src/services/files.ts:126]: Seems type narrowing might be a better path. This works for me with no error
```ts
if ('truncated' in stream && stream.truncated === true) {
  // code
}
```

**Comment by AlexGaillard** [comment]
FWIW I tested this out and it LGTM, though I'll defer the final review to those who were more involved in the conversation.

**Review by rijkvanzanten — APPROVED** [review]
