### PR TITLE
Fix a bug where the ID of newly added M2M/M2A items was lost after editing a junction field

### LINKED ISSUE #24568: Loss of Relational IDs When Editing Entries with Raw Groups
### Describe the Bug

# Bug Description

## General Description

When editing an item in a many-to-many (M2M) table or list entry of **CollectionA**, and there is a field present in a raw group of the junction collection between **CollectionA** and **CollectionB**, the reference ID to **CollectionA** gets lost.

## Impact

While the entry can typically still be saved, this issue leads to multiple problems:

- **User Experience Problems:** Users are confused by unexpected behavior.
- **Data Duplication:** The ability to add duplicate items from **CollectionB**.
- **Conditional Check Failures:** Issues arise when the missing reference ID impacts condition-based logic.

### Detailed Issues

- **Data Display Issue:** After editing, all data of **CollectionB** is no longer displayed in the table or list.
- **Further Editing Issues:**
  - All data from **CollectionB** is absent when attempting to edit again.
  - Fields that are required cannot be saved or edited due to appearing empty.
- **Duplication Risk:** Users can add the same item from **CollectionB** again due to the absence of **CollectionA_ID** affecting client-side unique checks.

## Temporal Fix

Move fields outside of the Raw Group (note: this may affect some bookmarks).

## Related
It seems this is possibly related to the following issue. Sounded different enough to open a new issue tho.
- https://github.com/directus/directus/issues/18676

### To Reproduce

# Steps to Reproduce

Image

Setting the interface layout to Table highlights the issue best. Add the fields `grade` and `subject_name` to understand the UIX issue.

1. Create a subject entry, e.g., `Math`, in **CollectionA**.
2. Create a student entry, e.g., `Alex`, in **CollectionB**.
3. In the Grades-Table, click on `Add Existing` and select the subject.

After these steps, the subject should appear without a grade:

Image

### Data Display Issue:

1. Click the recently added entry to edit it.
2. Enter a grade and save.
3. The `Subject Name` now appears empty. (The reference to the Student ID is lost, surprisingly not the Subject ID.)

### Duplication:

1. Click `Add Existing`.
2. The ability to add the already edited subject again demonstrates the duplication issue.
3. Cancel to avoid adding duplicates.

### Further Editing Issues:

1. After entering a grade and editing again, `Subject Name` is empty.
2. If `Subject Name` was a required field, you could not edit the grade since it appears empty.

Overall, this issue persists only when fields are in a raw group. Moving the `grade` field outside of the Raw Group, without deletion, resolves this issue.

### Directus Version

v11.4.1 (latest)

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres:16.4

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- Added a condition to allow each existing field to be part of the modelValue, when `$type` is `created`

## Potential Risks / Drawbacks

- This applies to any edits made to a group's fields. There may be cases where this could cause an issue.

## Review Notes / Questions

—

---

Fixes #24568

### CODE REVIEW

File: app/src/components/v-form/v-form.vue [hunk 1]
```diff
@@ -259,7 +259,7 @@ function apply(updates: { [field: string]: any }) {
 		: Object.keys(updates).filter((key) => {
 				const field = fieldsMap.value[key];
 				if (!field) return false;
-				return field.schema?.is_primary_key || !isDisabled(field);
+				return updates.$type === 'created' || field.schema?.is_primary_key || !isDisabled(field);
 		  });
```
Comment (AlexGaillard) [inline app/src/components/v-form/v-form.vue:263]:
```suggestion
				return (updates.$type === 'created' && field.meta?.readonly) || field.schema?.is_primary_key || !isDisabled(field);
```

Seeing as the cause of this update being left out is the fact that the `field.meta.readonly === true`, should we maybe add that as an extra layer of assertion? Or is that maybe too specific of a case?

Comment (formfcw) [reply app/src/components/v-form/v-form.vue:263]: I don't see how this relates to the readonly state. What do you mean by that?

Comment (formfcw) [reply app/src/components/v-form/v-form.vue:263]: Thank you for your suggestion :heart: Makes sense 🚀

**Review by AlexGaillard — APPROVED** [review]
:cool::beans:
