### PR TITLE
Fix persistent nested validation errors

### LINKED ISSUE #24392: Prevent persistent nested validation errors
### Describe the Improvement

- Create a `posts` collection with a translation (interface) field.
- Add a field to the translation collection and make it required
- Create another collection with a M2A or M2M field and add a relationship to `posts` (and other collections if m2a)
- Add some items to `posts`
- In the other collection, add a `posts` item and add a translation, but make sure the field you created is empty.
- Click save, so it throws a validation error
- Then close the drawer and create a new post (or other collection item).
- When you click the save button, you get the previous validation error (BUG)

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- This is a regression of https://github.com/directus/directus/pull/24220, which is not yet released.

## Potential Risks / Drawbacks

none

## Review Notes / Questions

none

---

Fixes #24392

### CODE REVIEW

File: app/src/views/private/components/drawer-item.vue [hunk 1]
```diff
@@ -333,7 +333,8 @@ function useRelation() {
 }
 
 function useActions() {
-	const { nestedValidationErrors } = useNestedValidation();
+	const { nestedValidationErrors, resetNestedValidationErrors } = useNestedValidation();
+	watch(internalActive, resetNestedValidationErrors);
```
Comment (paescuj) [inline app/src/views/private/components/drawer-item.vue:337]: Nitpicking, but I guess we only need to call it once either on close / open:

```suggestion
	const { nestedValidationErrors, resetNestedValidationErrors } = useNestedValidation();

	watch(internalActive, (active) => {
		if (!active) resetNestedValidationErrors();
	});
```

**Review by paescuj — APPROVED** [review]

File: app/src/views/private/components/drawer-item.vue (hunk 1 above)
Comment (formfcw) [reply app/src/views/private/components/drawer-item.vue]: nitpicking but fair ❤️
