### PR TITLE
Fix duplicate values bug for is-one-of filter

### LINKED ISSUE #24968: Validation of a field for `is One Of` type duplicates it's values on each key stroke.
### Describe the Bug

Please check attached video
https://github.com/user-attachments/assets/fa0d95a0-961f-432f-b617-a5e4453ae7a4

### To Reproduce

Please check attached video
https://github.com/user-attachments/assets/fa0d95a0-961f-432f-b617-a5e4453ae7a4

### Directus Version

v11.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres 14

### PR DESCRIPTION
**Pull request by osmandvc**
## Scope

What's changed:

- Fixes the duplicate values bug upon entering values seperated by comma in the "Is One Of" filter

## Review Notes / Questions

To summarize why the bug happened: The key issue is that the old flatMap in the computed value property correctly processes the comma at the data level, but the UI doesn't remove the comma from the visual input and doesnt focus the next input for a new item. This creates a mismatch between what the user sees and what the system processes. The bug did not occur upon pasting in comma seperated values because the string gets emmited as a whole, resulting in the desired behavior. 

With this fix, the comma is removed from the visual input as soon as it's typed, and a new input field is created and focused (only for "Is-one-of" and "Is-not-one-of" filters and where the `commaAllowed` prop is set to `true`)

---

Fixes #24968

### CODE REVIEW

File: app/src/interfaces/_system/system-filter/input-group.vue [hunk 1]
```diff
@@ -115,6 +113,41 @@ function setValueAt(index: number, newVal: any) {
...
+	if (parts.length === 1) {
+		const firstPart = parts[0]?.trim() || '';
+		const newArray = Array.isArray(value.value) ? clone(value.value) : [];
+		newArray[index] = firstPart;
+		const insertPosition = index + 1;
+		newArray.splice(insertPosition, 0, '');
+		value.value = newArray;
+
+		nextTick(() => {
+			const inputElements = document.querySelectorAll('.list .value input');
```
Comment (robluton) [inline app/src/interfaces/_system/system-filter/input-group.vue:129]: prefer not to depend on class names for this if possible

Comment (robluton) [reply app/src/interfaces/_system/system-filter/input-group.vue:129]: I think you can handle most of this by  preventing the comma input in an onKeyDown handler inside[ input-component.vue](https://github.com/directus/directus/blob/95732f741f8d320bf5761891c718b44400b1f5c2/app/src/interfaces/_system/system-filter/input-component.vue#L139) and then passing the focus to the nextSibling. What do you think about that approach?

Comment (osmandvc) [reply app/src/interfaces/_system/system-filter/input-group.vue:129]: Yeah I initially tried that approach and its way cleaner imo, I will look into it again tomorrow

**Comment by osmandvc** [comment]
Thanks for your guidance @robluton, I realized that I overcomplicated stuff a bit and did some redundant steps after catching the comma. The refactored code is way more readable and makes more sense :D To summarize what changed:

- As you mentioned, the comma gets catched by `onKeyDown` for every input-field which then triggers a focus to the next input-field. 
- For pasting comma-seperated values, the `onPaste` handler was used. The emitted clipboard-value just gets split by comma in the parent and gets attached to the end of the current list of input items.
- Using refs for focusing input fields instead of querying classnames, as requested

An addtional UX improvement could be allowing to delete items by hitting backspace on empty inputs, I can implement that also if you wish so.

You can see a short demo attached, happy to hear your feedback!


https://github.com/user-attachments/assets/1ff6cab9-bb98-473d-b0f6-04f562deaca8

File: app/src/interfaces/_system/system-filter/input-component.vue [hunk 2]
```diff
@@ -100,13 +102,35 @@ function onEffect(value: typeof props.value) {
...
-function onInput(value: string | null) {
+function onInput(value: string | number | Record<string, unknown> | boolean | null) {
 	isInputValid.value = isValueValid(value);
 
-	if (isInputValid.value) {
-		emit('input', value === '' ? null : value);
+	if (isInputValid.value) emit('input', value === '' ? null : value);
+}
+
+function onKeyDown(event: KeyboardEvent) {
```
Comment (robluton) [inline app/src/interfaces/_system/system-filter/input-component.vue:111]: I'm wondering if we can do something like this. This prevents the commas from making it into the input and sets the focus to the next one. I don't think the other events and processing are needed with this in place, but curious about your thoughts?

```ts
function onKeyDown($event: KeyboardEvent) {
	if ($event.key === ',' && props.commaAllowed) {
		const parent = ($event.target as HTMLInputElement).parentElement;
		const nextInput = parent?.nextElementSibling?.querySelector('input');

		if (nextInput) {
			nextInput.focus();
		}

		$event.preventDefault();
		return;
	}
}
```

Comment (osmandvc) [reply app/src/interfaces/_system/system-filter/input-component.vue:111]: Its a very valid approach, but I am not really a fan of mixing up too much specific "comma seperated input-group logic" into the input-component itself, that's why I am letting the parent decide the actual logic (input-group). I also think DOM-traversal would be valid for this but using refs would be more robust against possible modifications in the future imo. Coupling a child element with DOM nodes of other child elements also seems a bit "out of scope" for me. What are your thoughts on this?

Comment (robluton) [reply app/src/interfaces/_system/system-filter/input-component.vue:111]: That works for me. I can appreciate the focus on data flow rather than a more concise alternative. Going to approve this one. Thanks for the PR! 🎸

**Review by robluton — APPROVED** [review]
LGTM
