### PR TITLE
Fix merge behavior during validation for nested drawer forms

### LINKED ISSUE #25919: Cannot save nested M2M relation edit when junction table has newly added required field
### Describe the Bug

When editing a related item through a many-to-many relationship interface, Directus throws a validation error ( "Value cannot be 'null'") if the related item's junction table contains a newly added required M2M field, even when that field is being populated during the save operation.
The issue occurs specifically when:

1. Collection B has an existing M2M relationship to Collection A (with existing data)
2. A new required M2M relationship is added from Collection B to Collection C
3. Attempting to edit a Collection B item through Collection A's interface and setting the new required B→C relationship fails with a null validation error
4. Editing the same Collection B item directly (not through Collection A) works perfectly fine

This suggests a validation timing issue where Directus validates the required field before the new relationship value is committed when editing through nested relations.

### To Reproduce

1. Create Collection A, B, and C
2. Create a M2M relationship between Collection A and Collection B
3. Add several rows to Collection B and create relationships to Collection A
4. Add a new M2M relationship from Collection B to Collection C and mark it as required
5. Add rows to Collection C
6. Navigate to a Collection A item that has existing relationships to Collection B
7. Click to edit one of the related Collection B items through the Collection A interface
8. In the nested edit panel, populate the new required B→C relationship field
9. Click Save

### Directus Version

v11.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mssql

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- Fixed an issue where saving nested many-to-many relationships triggered a validation error due to incorrect merging behavior
- Moved the redundant logic from the useItem() and useVersions() composables into a new mergeItemData utility, and also applied it to the overlay-item component

## Potential Risks / Drawbacks

—

## Tested Scenarios

- Reproduction steps

## Review Notes / Questions

—

## Checklist

- [x] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25919

### CODE REVIEW

File: app/src/composables/use-item/index.ts [hunk 1]
```diff
@@ -5,24 +5,25 @@ import { i18n } from '@/lang';
 import { useFieldsStore } from '@/stores/fields';
 import { useRelationsStore } from '@/stores/relations';
 import { APIError } from '@/types/error';
+import { applyConditions } from '@/utils/apply-conditions';
```
Comment (robluton) [inline app/src/composables/use-item/index.ts:8]: Just a note. In the future we should avoid making changes unrelated to the task so the diff only shows what needs to be reviewed. If we want to order the imports differently, we might consider adding a format rule and running it over the codebase as its own PR.

File: app/src/utils/merge-item-data.test.ts [hunk 2]
```diff
@@ -0,0 +1,85 @@
+import { describe, it, expect } from 'vitest';
+import { mergeItemData } from './merge-item-data';
+
+describe('mergeItemData', () => {
+	it('should use existing if edits is undefined', () => {
```
Comment (robluton) [inline app/src/utils/merge-item-data.test.ts]: The test states edits is undefined, but is using an empty object instead.

File: app/src/utils/merge-item-data.test.ts [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+		const defaults = { x: 'default' };
+		const existing = { x: 'existing' };
+		const edits = {};
+		const result = mergeItemData(defaults, existing, edits);
+		expect(result.x).toMatchInlineSnapshot(`"existing"`);
+	});
+
+	it('should use default if both existing and edits are undefined', () => {
```
Comment (robluton) [inline app/src/utils/merge-item-data.test.ts]: These are both assigned empty objects - not undefined.

**Comment by robluton** [comment]
@formfcw looks good! 🎸
Just a couple of minor comments.

**Review by robluton — APPROVED** [review]
LGTM! 🎸

**Review by AlexGaillard — APPROVED** [review]
