### PR TITLE
Fix filter hook altered payload not passed to action hook on `create`

### LINKED ISSUE #19473: Action hook disregards output value of filter hook
### Describe the Bug

[Watch](https://sos-de-fra-1.exo.io/directus/Bildschirmaufnahme%202023-08-19%20um%2009.44.25.mov)

### To Reproduce

Setup two flows:
1) Trigger is a filter hook on update/create
- Return the value of the last operation
- Transform payload and return (does not matter how)
2) Trigger is an action hook on update/create

Create or update the collection. The filter modifies the payload correctly but the action input is still the original payload.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- The final payload (i.e. after filter hook and preset changes) is now passed down to the action hook

## Potential Risks / Drawbacks

- This will break all existing users who depend on the original payload being provided in the action hook

## Review Notes / Questions

- A changeset of`major` seemed appropriate due to the payload changes
- This change seems to already be present for all other relevant hooks and did not look intentional

---

Fixes #19473
Related Doc PR: https://github.com/directus/docs/pull/247

### CODE REVIEW

File: api/src/services/items.ts [hunk 1]
```diff
@@ -140,58 +140,56 @@ export class ItemsService<Item extends AnyItem = AnyItem, Collection extends str
...
+						payload,
 						{
-							accountability: this.accountability,
-							action: 'create',
 							collection: this.collection,
-							payload: payloadAfterHooks,
 						},
 						{
-							knex: trx,
+							database: this.knex,
```
Comment (br41nslug) [inline api/src/services/items.ts:156]: Should this event callback not stay within in the transaction so extensions get the knex transaction and can potentially cancel/rollback.

Comment (ComfortablyCoding) [reply api/src/services/items.ts:156]: hmmm, as discussed it should and will move it back. The original thinking was to provide access to `payloadWithPresets` without needing an alternate variable assigned inside the transaction

Comment (ComfortablyCoding) [reply api/src/services/items.ts]: This should be resolved via 866fabc7a886df1a1fd2d4ba30c60c567117835d

**Review by br41nslug — APPROVED** [review]
LGTM and lets make sure we add a breaking change note in the docs too

**Comment by ComfortablyCoding** [comment]
> LGTM and lets make sure we add a breaking change note in the docs too

Opened https://github.com/directus/docs/pull/247 to add the breaking changes note
