### PR TITLE
Fix relational fields for Download Page as CSV & relevant displays' handler improvements

### LINKED ISSUE #13791: App Export Download this Page as CSV M2M Issues
### Describe the Bug

The Download Page as CSV is supposed to export the table exactly as it appears in the table layout view:

For example, on v9.12.1, I have collections for Permits and Organizations. Permits has a many-to-many relationship field called orgs. I choose the following table layout for the Permits collection:

(the last three columns are Orgs: Title - English, Orgs: Subtitle - English, and Directus Roles: Name):
image

this is the CSV I get from Download this Page as CSV:
image

### To Reproduce

- Created a collection: permit
    - Included default fields for status and create/update by/date
    - Create input field: title_english
    - Create dropdown field: language
    - Create m2m field: orgs --> related table organizations
- Collection: organizations
    - Add input fields: title_english, subtitle_english, title_french, subtitle_french

Add the following permit records:

Status | Title English | Language
-- | -- | --
Draft | Import Declaration | bilingual
Published | Federal Incorporation (... | bilingual
Draft | Explosive Importation ... | bilingual

Add the following organizations records:

Subtitle English | Subtitle French | Title English | Title French
-- | -- | -- | --
  |   | Corporations Canada | Fr Corporations Canada
Explosives Regulatory Division | Fr Explosives Regulatory Division | Natural Resources Canada | Fr Natural Resources Canada

- Export using "Download Page as CSV"
    - Tested without any relational fields and works correctly
    - Adding related organizations.title_english makes permits.title_english disappear
    - Relational data to the m2m fields doesn't export
    - Relational data to O2M fields like user_created.first_name exports correctly

## Observations:
- Duplicate field names seem to cause aggregation problems
- M2M relations are not exporting at all -- depth issue maybe?
- Noticed when testing on a dropdown field -- if the Display "Text" entry is blank, then no data will be exported :)
    - Ensure this is noted to the documentation OR put conditional to export the "Value" if the "Text" is empty

### Errors Shown

N/A

### What version of Directus are you using?

9.12.1 & 9.11.1

### What version of Node.js are you using?

Current & Community Cloud

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally & Community Cloud

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #13791

### Issues, Investigation and Solution used

- > - Adding related organizations.title_english makes permits.title_english disappear
  > - Relational data to the m2m fields doesn't export

   There's 2 primary bugs causing this:

     - The value retrieval was not accounting for the recently added aliasing (so relational fields are aliased/hashed rather than the original relational table name)

        (`key` can be aliased)
     https://github.com/directus/directus/blob/efa64dc4aa7f631d9eb6ee942bc5302667b35ea2/app/src/utils/save-as-csv.ts#L27
   
     - Here we are using `parsedItem[name]` ("name" being field name) to generate the csv columns. However, `Title English` and relational `orgs -> organization ID -> Title English` both resolves into `Title English`, hence whichever comes later will override the previous value and make the column/field seemingly disappear.

       https://github.com/directus/directus/blob/efa64dc4aa7f631d9eb6ee942bc5302667b35ea2/app/src/utils/save-as-csv.ts#L35-L45
   
   The relevant solution were applied to `save-as-csv.ts` only.

- > - checkbox tree field just dumps the raw value, rather than using the Display that is shown in the table layout.
  > - Display for Checkbox Tree is configured to mirror the configured Choices (Labels display)

   For checkbox tree (json or csv), the `value` in the handler is an array, hence the "finding of choice" will always not match as it's comparing to an array. 
   
   Added an additional check and map over the array with `getConfiguredChoice`.

- > - Noticed when testing on a dropdown field -- if the Display "Text" entry is blank, then no data will be exported 

   This was added in the above solution as well, specifically `return text && text !== '' ? text : val;` to fallback to value.

- > - wysywyg field exports the raw HTML which is not how it's displayed in the Table Layout
  > - Display for Wysiwyg is set as "Formatted Value"
  
   formatted value display additionally does replacing of HTML tags and decoding:
   
   https://github.com/directus/directus/blob/efa64dc4aa7f631d9eb6ee942bc5302667b35ea2/app/src/displays/formatted-value/formatted-value.vue#L154-L158
   
   Added the same logic to formatted-value display's handler.
   
## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: app/src/displays/formatted-value/index.ts [hunk 1]
```diff
@@ -13,7 +14,16 @@ export default defineDisplay({
 	handler: (value, options) => {
 		const prefix = options.prefix ?? '';
 		const suffix = options.suffix ?? '';
-		const formattedValue = options.format ? formatTitle(value) : value;
+
+		let sanitizedValue = String(value);
+
+		// Strip out all HTML tags
+		sanitizedValue = value.replace(/(<([^>]+)>)/gi, '');
```
Comment (br41nslug) [inline app/src/displays/formatted-value/index.ts:21]: This regex seems very broad to me 🤔 are there situations where this could filter out legitimate content?

File: app/src/displays/labels/index.ts [hunk 2]
```diff
@@ -10,16 +10,24 @@ export default defineDisplay({
...
 
-		return value;
+		function getConfiguredChoice(val: string) {
+			const configuredChoice =
+				options?.choices?.find((choice: { value: string }) => choice.value === val) ??
+				interfaceOptions?.choices?.find((choice: { value: string }) => choice.value === val);
+
+			if (configuredChoice) {
+				const { text } = translate(configuredChoice);
+				return text && text !== '' ? text : val;
```
Comment (br41nslug) [inline app/src/displays/labels/index.ts:26]:
```suggestion
				return text ? text : val;
```
Because `!"" === true` you don't need to check both if text is "truthy" and not empty as the empty string will never pass the first expression. 
I considered suggesting ```return text || val``` but i think the full ternary operator is more readable.

File: app/src/displays/formatted-value/index.ts (hunk 1 above)
Comment (azrikahar) [reply app/src/displays/formatted-value/index.ts:21]: Good question! I was lifting it from the existing displayValue of formatted-value so I'm not aware of whether it currently has false-positives as well 🤔

https://github.com/directus/directus/blob/efa64dc4aa7f631d9eb6ee942bc5302667b35ea2/app/src/displays/formatted-value/formatted-value.vue#L154-L158

Maybe we can use the `sanitize-html` package to be more thorough? Seems like we're already using it over in the API:

https://github.com/directus/directus/blob/efa64dc4aa7f631d9eb6ee942bc5302667b35ea2/api/src/utils/md.ts#L2

so perhaps we can add it to the App for this "strip HTML" purpose? 🤔 and set `allowedTags` to an empty array so that it'll actually strip all tags as [described by the package author here](https://stackoverflow.com/a/31639380).

Comment (br41nslug) [reply app/src/displays/formatted-value/index.ts:21]: Maybe too much of an edge case this one, but as this sanitization is used for WYSIWYG html where if someone uses the `<` character in text it will match that and remove all text after that in the element
image
```js
import sanitizeHTML from 'sanitize-html'; 
```
sounds like a good solution to me :) with all weird quirks of html/xml you really don't want to be matching that using regex

Comment (azrikahar) [reply app/src/displays/formatted-value/index.ts]: Just noticed that `sanitize-html` doesn't bundle for browsers, so ended up using `dompurify` since it's already being used App side in the md utils anyway:

https://github.com/directus/directus/blob/52d1080c11de2e24432bf56ea03049533dc4503f/app/src/utils/md.ts#L2

uses `ALLOWED_TAGS: []` option similar to `allowedTags` in sanitize-html.

File: app/src/displays/labels/index.ts (hunk 2 above)
Comment (rijkvanzanten) [reply app/src/displays/labels/index.ts]: > I considered suggesting return text || val but i think the full ternary operator is more readable.

`||` or `??` @br41nslug 😉

**Review by br41nslug — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by bcartier** [comment]
This is working really well. Thank you for pushing this through for the v9.13.0 release.  

One minor thing I noticed was that for M2M-related fields, they appear in the CSV as:

**["Field Value"],["Another Field Value"]**

...as opposed to the Table Layout display of:

**Field Value, Another Field Value**

Is this intended/required? Ideally, I think it should be the same formatting as the Table Layout if at all possible.

**Comment by rijkvanzanten** [comment]
@bcartier Is that M2M using the Labels display? I think we can tweak the string handler of that to render out a `.join(', ')` instead of the JSON stringified result 🙂
