### PR TITLE
Fix field presets for relational fields are not working

### LINKED ISSUE #16127: Field Presets for M2M fields are not used
### Describe the Bug

When using Field Presets in a create item permission, those presets are not used for M2M fields.

I have looked into the code and I think the issue is in the file [/api/src/services/items.ts on line 166](https://github.com/directus/directus/blob/228a5ca15f981f01c7072b641d53e1edf562629a/api/src/services/items.ts#L166). Here, the original `payload` is used instead of `payloadWithPresets`. Therefore, the presets are missing and are not evaluated.

### To Reproduce

1. Create two collections authors and books
2. Add a M2M field "books" on authors with books as related collection
3. Create a new book for testing (id is 1)
4. On the public role (for simplicity, bug happens with any role), set the create permission for the authors collection to Use Custom and use the following Field Presets:
`{
    "books": [
        {
            "books_id": 1
        }
    ]
}`
5. Set the create permission of the Public role for the junction table authors_books to All Access
6. Use the API with the Public role to create an item (empty, i.e. {}) in authors

The preset for the books field will not be used, i.e. the field is empty and no entry in the junction table is generated.

### Errors Shown

_No response_

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres 13 (postgis/postgis:13-master)

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by timspi**
## Description

The API was not using field presets and filter hook data for relational fields. This was because the call to the payload service was using the original payload instead of the updated one.

To address the problems in the app mentioned by @azrikahar, I added a conditional warning that is shown when a field preset is configured with the simple array method for a field that uses a relational interface.

Field preset with error

Field preset without error

Fixes #16127 

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by abdonrd** [comment]
Thanks for working on this! We also have this problem.

File: app/src/modules/settings/routes/roles/permissions-detail/components/presets.vue [hunk 1]
```diff
@@ -47,7 +58,32 @@ export default defineComponent({
 			},
 		});
 
-		return { t, presets };
+		/**
+		 * Interfaces that use the useRelationMultiple composable.
+		 */
+		const relationalInterfaces = ['list-m2a', 'list-m2m', 'list-o2m', 'list-o2m-tree-view', 'files'];
```
Comment (rijkvanzanten) [inline app/src/modules/settings/routes/roles/permissions-detail/components/presets.vue:64]: We can't hardcode interfaces by name, as interfaces are an extension type. The only way to resolve that is by looking up the details of each registered interface to extract a list of relational interfaces

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: app/src/lang/translations/en-US.yaml [hunk 2]
```diff
@@ -187,6 +187,7 @@ permissions_for_role: 'Items the {role} Role can {action}.'
 fields_for_role: 'Fields the {role} Role can {action}.'
 validation_for_role: 'Field {action} rules the {role} Role must obey.'
 presets_for_role: 'Field value defaults for the {role} Role.'
+presets_field_warning: 'The app interface for relational field {field} only supports the detailed syntax.'
```
Comment (rijkvanzanten) [inline app/src/lang/translations/en-US.yaml:190]:
```suggestion
presets_field_warning: 'Relational presets for field "{field}" should be configured with the "detailed" syntax.'
```

Should make it a tad more obvious that "detailed" is a word we call it so it's easier to search for it in the docs or ask a question about it

**Review by rijkvanzanten — DISMISSED** [review]

File: app/src/modules/settings/routes/roles/permissions-detail/components/presets.vue [hunk 3]
```diff
@@ -47,7 +55,31 @@ export default defineComponent({
 			},
 		});
 
-		return { t, presets };
+		const relationsStore = useRelationsStore();
+		const relations = relationsStore.getRelationsForCollection(props.permission.collection);
+		const relationFields = relations.map((relation) => relation.field);
```
Comment (rijkvanzanten) [inline app/src/modules/settings/routes/roles/permissions-detail/components/presets.vue:60]: Does this correctly filter out just the `o2m` relationships, or does this affect all relational fields?

Comment (timspi) [reply app/src/modules/settings/routes/roles/permissions-detail/components/presets.vue]: Sorry, I did not do proper testing yesterday evening. I have changed it now and I think now it behaves correctly. I tested for m2m, o2m and m2o with different configurations. I also updated the comment to explain the motivation behind the warning more clearly. Maybe the warning text itself could be extended to be more precise, e.g.:
Relational [...] syntax. Otherwise, if a relational app interface is used, it will not show the preset correctly.

The warning is shown for all relations where the meta.one_field is set now. For the o2m relation, the warning is also shown as the interface does not support the array syntax either. For m2o, there is no warning as the relation is filtered out. But even if not, the warning would only be shown when a non-empty array is entered which does not make sense for a m2o field. Validation for the whole preset could be added, but I think there are more urgent topics at the moment.

**Review by paescuj — APPROVED** [review]
LGTM ❤️

File: app/src/lang/translations/de-DE.yaml [hunk 4]
```diff
@@ -181,6 +181,7 @@ permissions_for_role: 'Elemente, die {role} Rolle {action} kann.'
 fields_for_role: 'Felder die von der {role} Rolle {action} werden können.'
 validation_for_role: 'Feld {action} Regeln, welche die {role} Rolle befolgen muss.'
 presets_for_role: 'Standardwert für die {role} Rolle.'
+presets_field_warning: 'Der App-Editor für Feld {field} unterstützt nur die detaillierte Syntax.'
```
Comment (azrikahar) [inline app/src/lang/translations/de-DE.yaml:184]:
```suggestion
```

From a guess from the `App-Editor` here (as I'm not familiar with the language), I believe it's now outdated due to https://github.com/directus/directus/pull/16560/commits/3911a17610dbdc9bd5e804e1d67d4cf5763ceace 

That being said, opting to remove this in favor of follow up translations by users via Crowdin as the preferred workflow 👍

**Review by azrikahar — CHANGES_REQUESTED** [review]

**Review by azrikahar — APPROVED** [review]
LGTM 👍 Thanks again for looking into this!
