### PR TITLE
Generate joi merge

### LINKED ISSUE #13119: Save options not shown
### Describe the Bug

Hi, I noticed that on saving an item the save option "save e create new" and "Save as a copy" are no more shown if the user is not an administrator.

### To Reproduce

- Login with non admin user
- Create a new item in a collection 
- Click in the dots save options icon

### Errors Shown

_No response_

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

12

### What database are you using?

10.5.12 MariaDB

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally on ubuntu 20.04.03 LTS

### LINKED ISSUE #13595: The generate-joi functionality is duplicated in app and the shared package
### Describe the Bug

We have [generate-joi/index.ts](https://github.com/directus/directus/blob/main/app/src/utils/generate-joi/index.ts) in the app with a comment that the function should be shared. We also have [generate-joi.ts(https://github.com/directus/directus/blob/main/packages/shared/src/utils/generate-joi.ts) in the shared package. They both (to me) seem to do the same thing but slightly differently. 

Should we just have the one shared function? This way we don't have to add new operators and tests in two places?

The differences are:
 - The app version has an `allowUnknown` prop that defaults to `true`. Shared doesn't have it at all. Personally, I think having the boolean available but not defaulting to `true` outside the app makes sense?

- Shared doesn't run Object.values() for every match. It uses `compareValue` which is a little clearer.

- Shared has stricter typing and a comment that it doesn't currently accept _and _or. But I can't see why the one in the app would? I assume it has something to do with [this](https://github.com/directus/directus/blob/f9a3413586773aa7ff51fdcc701ba460bb994968/packages/shared/src/utils/generate-joi.ts#L102-L106)

[This](https://github.com/directus/directus/blob/main/app/src/utils/is-allowed.ts) seems to be the only place in the app that uses generateJoi according to the search function in VSC. It's being passed a permissions object that can technically be a LogicalFilter containing _and/_or. Not sure the best way to handle this since neither location of generateJoi seems to be recursive in a way that handles the operators.

The benefit of merging them is that operators, updates, and optimizations don't need to be added in both places.

### To Reproduce

Link 1: [generate-joi/index.ts](https://github.com/directus/directus/blob/main/app/src/utils/generate-joi/index.ts) in Link 2: [generate-joi.ts(https://github.com/directus/directus/blob/main/packages/shared/src/utils/generate-joi.ts)

### Errors Shown

Folder structure change. No errors.

### What version of Directus are you using?

[7e1e735](https://github.com/directus/directus/commit/7e1e7354b9472608cb8ffc48554c8eaf5c21925e)

### What version of Node.js are you using?

16.3.1

### What database are you using?

Postgres

### What browser are you using?

Chromium

### How are you deploying Directus?

running locally

### LINKED ISSUE #13855: Flows: Condition Operation returning not allowed error
### Describe the Bug

Flows created with Condition Operations seems to be returning permission error when performing filters with the available variables ($trigger, $last, ...)

### To Reproduce

1. Create Flow with the setup Event Hook -> Action (Non-Blocking) -> Scope (items.create) -> Select Collection to trigger
2. Create Condition Operation using the variable $trigger on the filter:

Flow-Bug-1

3. Trigger flow by creating item on the previous Collection
4. Check the log created on the Condition Operator step

### Errors Shown

Flow-Bug-2

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally with Docker

### PR DESCRIPTION
**Pull request by jamescammarano**
## Description

We have [generate-joi/index.ts](https://github.com/directus/directus/blob/main/app/src/utils/generate-joi/index.ts) in the app with a comment that the function should be shared. We also have [generate-joi.ts](https://github.com/directus/directus/blob/main/packages/shared/src/utils/generate-joi.ts) in the shared package. They both (to me) seem to do the same thing but slightly differently. 

The benefit of merging them is that operators, updates, and optimizations don't need to be added in both places.

I also updated the `app/jest.config.js` to properly resolve `@/` imports.

NOTE: Neither implementation seems to support _and or _or

Fixes #13595
Fixes #13855 
Fixes #13119 

## Type of Change

- [ ] Bugfix
- [ ] New Feature
- [x] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

File: packages/shared/src/utils/generate-joi.ts [hunk 1]
```diff
@@ -58,6 +58,7 @@ export const Joi: typeof BaseJoi = BaseJoi.extend({
 });
 
 export type JoiOptions = {
+	allowUnknown?: boolean;
```
Comment (rijkvanzanten) [inline packages/shared/src/utils/generate-joi.ts:61]: allowUnknown should have a default below as well

Comment (rijkvanzanten) [inline packages/shared/src/utils/generate-joi.ts:61]: allowUnknown should have a default below as well

File: packages/shared/src/utils/generate-joi.ts [hunk 2]
```diff
@@ -113,23 +115,31 @@ export function generateJoi(filter: FieldFilter, options?: JoiOptions): AnySchem
...
+			if (compareValue === null || compareValue === undefined || typeof compareValue !== 'string') {
 				schema[key] = Joi.any().equal(true);
 			} else {
 				schema[key] = getStringSchema().contains(compareValue);
 			}
 		}
 
 		if (operator === '_ncontains') {
-			if (compareValue === null || compareValue === undefined) {
+			if (compareValue === null || compareValue === undefined || typeof compareValue !== 'string') {
```
Comment (rijkvanzanten) [inline packages/shared/src/utils/generate-joi.ts:134]: I don't think this compareValue check should happen here 🤔 feels weird to silently fail the validation if the wrong type was presented. If anything, it should probably crash with an InvalidPayloadException when an illegal value is presented

File: packages/shared/src/utils/generate-joi.ts [hunk 3]
```diff
@@ -215,7 +233,9 @@ export function generateJoi(filter: FieldFilter, options?: JoiOptions): AnySchem
 		}
 
 		if (operator === '_between') {
-			if (compareValue.every((value: any) => Number.isSafeInteger(Number(value instanceof Date ? NaN : value)))) {
+			if (
+				(compareValue as any).every((value: any) => Number.isSafeInteger(Number(value instanceof Date ? NaN : value)))
```
Comment (rijkvanzanten) [inline packages/shared/src/utils/generate-joi.ts:237]: `isSafeInteger` doesn't work on floats, so we should update this to check against `Number.MAX_SAFE_INTEGER`:

CleanShot 2022-06-08 at 15 13 41@2x

File: packages/shared/src/utils/generate-joi.ts [hunk 4]
```diff
@@ -244,13 +266,17 @@ export function generateJoi(filter: FieldFilter, options?: JoiOptions): AnySchem
...
-				schema[key] = getStringSchema().regex(new RegExp(wrapped ? compareValue.slice(1, -1) : compareValue));
+				schema[key] = getStringSchema().regex(new RegExp(wrapped ? (compareValue as any).slice(1, -1) : compareValue));
 			}
 		}
 	}
 
 	schema[key] = schema[key] ?? Joi.any();
 
+	if (options.allowUnknown) {
+		return Joi.object(schema).unknown();
```
Comment (rijkvanzanten) [inline packages/shared/src/utils/generate-joi.ts:277]: The return of this function on 284 is already adding `.unknown()`, making this option useless (the result is the same whether or not `allowUnknown` is true or false. We should make sure where that allowUnknown was used before, and ensure that the new behavior is consistent and not causing any new errors.

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Comment by rijkvanzanten** [comment]
@licitdev could you do a review to make sure the behavior is consistent across the original uses of the util? I'm mostly worried about the difference in `allowUnknown` causing new issues 🤔

**Comment by licitdev** [comment]
@rijkvanzanten Yes, The `allowUnknown()` aspect was one of the differences between the app & api util. This is not a trivial merge but a necessary one. 👍🏻 

I'm worried about regressions, particularly because it's used in parsing filters in permissions. Will need some time to investigate deeper.

**Comment by rijkvanzanten** [comment]
> I'm worried about regressions, particularly because it's used in parsing filters in permissions. Will need some time to investigate deeper.

Very much same. Lets take our time on this one, and maybe add a couple more e2e tests using validation permissions while we're add it

**Comment by jaycammarano** [comment]
Just to contribute to the `allowUnknown()` conversation. Wouldn't having it not default to true solve that concern? I added it to the one place in the app that used it. Is there a scenario I'm not considering?

File: packages/shared/src/utils/generate-joi.ts (hunk 4 above)
Comment (licitdev) [reply packages/shared/src/utils/generate-joi.ts]: `allowUnknown` is currently always `true` for both the app & api. 
It was used in 
https://github.com/directus/directus/blob/d8ae3b9a8d3708e0c198d2d05555cfc116b72cf4/app/src/modules/collections/routes/detail/detail.vue#L414-L416

The option remains so that we could reuse to check for exact matches without unknown fields.

**Review by licitdev — COMMENTED** [review]
Updated to fix https://github.com/directus/directus/issues/13855

**Comment by jaycammarano** [comment]
What kind of tests does this need to be merged? I can whip some up today.

File: packages/shared/src/utils/generate-joi.ts (hunk 4 above)
Comment (licitdev) [reply packages/shared/src/utils/generate-joi.ts]: @jaycammarano I've defaulted `allowUnknown` to be true as I haven't seen it being set to false anywhere. Please assist to verify if that's correct. 👀

Comment (licitdev) [reply packages/shared/src/utils/generate-joi.ts]: Removed unused `allowUnknown` option.

**Comment by licitdev** [comment]
This PR also fixes #13119 from the updated `app/src/utils/is-allowed.ts`.

File: packages/shared/src/utils/generate-joi.ts [hunk 5]
```diff
@@ -92,9 +93,7 @@ export function generateJoi(filter: FieldFilter, options?: JoiOptions): AnySchem
 	}
 
 	if (Object.keys(value)[0]?.startsWith('_') === false) {
-		schema[key] = Joi.object({
-			[key]: generateJoi(value as FieldFilter, options),
-		});
+		schema[key] = generateJoi(value as FieldFilter, options);
```
Comment (imiskolee) [inline packages/shared/src/utils/generate-joi.ts:96]: same fix with: https://github.com/directus/directus/pull/14311

**Review by rijkvanzanten — APPROVED** [review]
