### PR TITLE
fix: adjust icon size on the drawer header (#26370)

### LINKED ISSUE #26370: Elements appearing too large in the drawer header
### Describe the Bug

Image thumbnail and download button appear too large.

Image

Regression caused by https://github.com/directus/directus/pull/26259

### To Reproduce

Setup a collection with a file or an image interface, select an image and click "edit item" to open the drawer.

### Directus Version

v11.14.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

### PR DESCRIPTION
**Pull request by kekekuli**
## Scope

What's changed:

- add the missing styles, same as before normal code behavior. ( The old `header-bar.vue` file behave normal, steal code from it)

## Potential Risks / Drawbacks

- Lorem ipsum dolor sit amet
- Consectetur adipiscing elit

## Tested Scenarios

- Lorem ipsum dolor sit amet
- Consectetur adipiscing elit

## Review Notes / Questions

- I would like to lorem ipsum
- Special attention should be paid to dolor sit amet

## Checklist

- [ ] Added or updated tests
- [x] Documentation PR created [here](https://github.com/directus/docs) or not required
- [x] OpenAPI package PR created [here](https://github.com/directus/openapi) or not required

---

Fixes #26370

### CODE REVIEW

File: app/src/interfaces/file/file.vue [hunk 1]
```diff
@@ -316,6 +316,7 @@ function useURLImport() {
 				<VButton
 					secondary
 					rounded
+					small
```
Comment (rijkvanzanten) [inline app/src/interfaces/file/file.vue]: Lets standardize this to use the `PrivateViewHeaderBarActionButton`. Looks like I missed the `DrawerItem` uses in https://github.com/directus/directus/pull/26375 :) I'll push up a commit here~

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Thanks @kekekuli! 🫶
