### PR TITLE
Fix unauthorized field exposure in asset responses

### LINKED ISSUE #24057: Filename for assets is exposed even when access policy denies access to "filename_download" field
### Describe the Bug

When an access policy (i.e. the `Public` policy) denies access to the `filename_download` field inside the `directus_files` collection, the `Content-Disposition` still includes the filename, even though it shouldn't be exposed when the currently used access policy denies read access to that field. Instead, Directus could fall back to the asset's ID as filename in this case.

### To Reproduce

1. Make sure to upload an asset and note down its ID
2. Go to `Settings` &rarr; `Access Policies` &rarr; `Public` &rarr; `Permissions` &rarr; `directus_files` (add it via `Add Collection` if necessary) &rarr; `Read` &rarr; `Use custom` &rarr; `Field Permissions` &rarr; Uncheck `filename_download` (expand fields list if necessary)
3. Save all changes
4. Log out of Directus or open a private browser window
5. Go to `https://<your directus instance>/assets/<the id you noted in step 1.>` and observe the filename (either via the browser tab title, the network tab in DevTools or by downloading the file)

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 13

### PR DESCRIPTION
**Pull request by gaetansenn**
## Scope

What's changed:

- `AssetsService` now respects field-level permissions when serving assets
- Introduced `returnAllowedRootFields` option in validateItemAccess to retrieve accessible fields in a single database query
- Fields restricted by user permissions (e.g., filename_download, modified_on) are filtered from the response and HTTP headers

## Potential Risks / Drawbacks

- None - essential fields are preserved, and the implementation is backward compatible

## Tested Scenarios

- Field filtering for non-admin users with field-level restrictions
- Admin users retain full access to all fields
- Item-level permission rules combined with field-level permissions
- System public assets bypass filtering correctly

## Checklist

- [X] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #24057

### CODE REVIEW

**Review by ComfortablyCoding — COMMENTED** [review]
Unfortunately the current approach leads to a few issues:

* It introduces a breaking change by requiring explicit permission for fields that are essential
* There's no clear guidance on which fields are minimally required
* It forces users to grant access to fields they wouldn’t typically allow

Ideally we have a way to query as an admin but return the data as the if the user queried

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 1]
```diff
@@ -34,31 +40,36 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
 	// Inject the filter after the permissions have been processed, as to not require access to the primary key
-	ast.query.filter = {
+	processResult.ast.query.filter = {
 		[primaryKeyField]: {
 			_in: options.primaryKeys,
 		},
 	};
 
-	const items = await fetchPermittedAstRootFields(ast, {
+	const items = await fetchPermittedAstRootFields(processResult.ast, {
```
Comment (br41nslug) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]:
```suggestion
	const items: Record<string, unknown>[] = await fetchPermittedAstRootFields(processResult.ast, {
```

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 2]
```diff
@@ -34,31 +40,36 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
-	if (items && items.length === options.primaryKeys.length) {
-		const { fields } = options;
+	let hasAccess = false;
 
-		if (fields) {
-			return items.every((item: any) => fields.every((field) => toBoolean(item[field])));
-		}
+	if (items && items.length === options.primaryKeys.length) {
+		hasAccess = options.fields
+			? items.every((item: any) => options.fields!.every((field) => toBoolean(item[field])))
```
Comment (br41nslug) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]:
```suggestion
			? items.every((item) => options.fields!.every((field) => toBoolean(item[field])))
```

File: api/src/services/assets.ts [hunk 3]
```diff
@@ -96,9 +96,11 @@ export class AssetsService {
 				},
 				{ knex: this.knex, schema: this.schema },
 			);
-		}
 
-		const file = (await this.filesService.readOne(id, { limit: 1 })) as File;
+			filesService = new FilesService({ accountability: this.accountability, knex: this.knex, schema: this.schema });
+		} else filesService = new FilesService({ knex: this.knex, schema: this.schema });
```
Comment (br41nslug) [inline api/src/services/assets.ts]:
```suggestion
		} else {
		    filesService = new FilesService({ knex: this.knex, schema: this.schema });
		}
```

File: api/src/permissions/modules/process-ast/process-ast.ts [hunk 4]
```diff
@@ -16,7 +16,10 @@ export interface ProcessAstOptions {
 	accountability: Accountability | null;
 }
 
-export async function processAst(options: ProcessAstOptions, context: Context) {
+export async function processAst(
+	options: ProcessAstOptions,
+	context: Context,
+): Promise<{ ast: AST; permissions?: any }> {
```
Comment (br41nslug) [inline api/src/permissions/modules/process-ast/process-ast.ts]:
```suggestion
): Promise<{ ast: AST; permissions?: Awaited<ReturnType<typeof fetchPermissions>> }> {
```
Not sure if this awaited type is the way to go but at least it gets rid of another `any` making the codebase a little more type-safe. Alternatively we could define and re-use the permission type returned from `fetchPermissions`

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 5]
```diff
@@ -34,31 +40,36 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+			: true;
+	}
 
-		return true;
+	if (options.returnFieldPermissions) {
+		return {
+			hasAccess,
+			authorizedFields: processResult.permissions.find((p: any) => p.collection === options.collection)?.fields ?? [],
```
Comment (br41nslug) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]:
```suggestion
			authorizedFields: processResult.permissions?.find((p) => p.collection === options.collection)?.fields ?? [],
```

**Review by br41nslug — COMMENTED** [review]
Got some type nitpicks for you 😬 hopefully those get rid of some reliance on the `any` type.

Will have to look at this again with some fresh eyes to properly wrap my head around the fix here 😵

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 1 above)
Comment (ComfortablyCoding) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Stale

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 2 above)
Comment (ComfortablyCoding) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Stale

File: api/src/services/assets.ts (hunk 3 above)
Comment (ComfortablyCoding) [reply api/src/services/assets.ts]: Stale

File: api/src/permissions/modules/process-ast/process-ast.ts (hunk 4 above)
Comment (ComfortablyCoding) [reply api/src/permissions/modules/process-ast/process-ast.ts]: Stale

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 5 above)
Comment (ComfortablyCoding) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Stale

File: api/src/controllers/assets.ts
Comment (ComfortablyCoding) [inline api/src/controllers/assets.ts:1]: Let's account for `modified_on` missing as well, it is not an bypassed field and may be missing

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 6]
```diff
@@ -43,22 +58,60 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
 		},
 	};
 
+	// Inject the children collection fields after the permissions have been processed, as to not require access to all collection fields
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]:
```suggestion
	// Inject the root fields after the permissions have been processed, as to not require access to all collection fields
```

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 7]
```diff
@@ -43,22 +58,60 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+		ast.children = Object.keys(context.schema.collections[options.collection]!.fields).map((field) => ({
+			type: 'field',
+			name: field,
+			fieldKey: field,
+			whenCase: [],
+			alias: false,
+		}));
+
+		const fieldMap: FieldMap = fieldMapFromAst(ast, context.schema);
+		const collections = collectionsInFieldMap(fieldMap);
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: As this is not used anywhere let's inline it if the types allow
```suggestion
		const collections = collectionsInFieldMap(fieldMapFromAst(ast, context.schema));
```

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 8]
```diff
@@ -43,22 +58,60 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+
+		const policies = await fetchPolicies(options.accountability, context);
+
+		const permissions = await fetchPermissions(
+			{ action: options.action, policies, collections, accountability: options.accountability },
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: As this can only ever be a single collection is the processing for collections necessary?
```suggestion
			{ action: options.action, policies, collections: options.collection, accountability: options.accountability },
```

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 9]
```diff
@@ -43,22 +58,60 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
 		},
 	};
 
+	// Inject the children collection fields after the permissions have been processed, as to not require access to all collection fields
+	if (options.returnAllowedRootFields) {
+		ast.children = Object.keys(context.schema.collections[options.collection]!.fields).map((field) => ({
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: As this is after the ast has been processed we should deduplicate the `fields` passed in to ensure no duplicate where conditions are injected. This is assuming `injectCases` does not deduplicate already.

File: api/src/controllers/assets.ts
Comment (gaetansenn) [reply api/src/controllers/assets.ts:1]: You want  set the date as new if the `modified_on` field is not provided? Why not simply not return the value instead of returning a wrong value?

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 10]
```diff
@@ -43,22 +58,60 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+	}
 
-		if (fields) {
-			return items.every((item: any) => fields.every((field) => toBoolean(item[field])));
-		}
+	// If returnAllowedRootFields, extract the fields that have value = 1
+	if (options.returnAllowedRootFields && items.length > 0) {
+		const allowedRootFields = Object.keys(items[0]).filter((field) => {
+			return items[0][field] === 1;
+		});
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: This will only return the allowed fields based on the first item, as it can be different per item we should go with a map based on id or similar.

File: api/src/services/assets.ts [hunk 11]
```diff
@@ -50,6 +50,25 @@ export class AssetsService {
 		this.filesService = new FilesService({ ...options, accountability: null });
 	}
 
+	private sanitizeFields(file: File, allowedFields: string[] | undefined): Partial<File> {
+		if (!allowedFields || allowedFields.includes('*')) {
+			return file;
+		}
+
+		const essentialFields: (keyof File)[] = ['type'];
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: As these bypass permissions let's name this something more appropriate, e.g.
```suggestion
		const bypassFields: (keyof File)[] = ['type'];
```

Comment (ComfortablyCoding) [reply api/src/services/assets.ts]: `filesize` should be included in this list as well, it is something that can be determined from the downloaded file either way

File: api/src/services/assets.ts [hunk 12]
```diff
@@ -50,6 +50,25 @@ export class AssetsService {
...
+		const fieldsToKeep = new Set<string>([...essentialFields, ...allowedFields]);
+
+		const filteredFile: Partial<File> = {};
+
+		for (const field of fieldsToKeep) {
+			if (field in file) {
+				(filteredFile as Record<string, unknown>)[field] = file[field as keyof File];
+			}
+		}
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: Let's improve the typings here if possible

File: api/src/services/assets.ts [hunk 13]
```diff
@@ -86,16 +105,32 @@ export class AssetsService {
...
-					accountability: this.accountability,
-					action: 'read',
-					collection: 'directus_files',
-					primaryKeys: [id],
-				},
-				{ knex: this.knex, schema: this.schema },
-			);
+			if (this.accountability.admin) {
+				allowedFields = ['*'];
+			} else {
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: This needs to be adjusted as `this.accountability === null` is also admin. That will never be the case here due to the check above.

As `sanitizeFields` accepts undefined for allowedFields perhaps only assigning if they are not adming would be more appropriate
```suggestion
      let allowedFields;
			if (req.accountability?.admin !== true) {
```

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 9 above)
Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: For the deduplication, if I handle the case where both fields and returnAllowedRootFields are passed, I can't use injectCases directly since it replaces all cases. I'd need to use getCases to inject cases only for the new fields (with offset-adjusted indices) to preserve the work done by processAst.
That said, this case is pretty rare. Do we really need to handle it?

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 8 above)
Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Oh yes you are right good point

File: api/src/services/assets.ts (hunk 12 above)
Comment (gaetansenn) [reply api/src/services/assets.ts]: I already improved it from as any to proper casts. 
The limitation is that `allowedFields` comes from `validateItemAccess` which returns string[] (it's generic, works with any collection).
To go further we'd need either:
- A runtime type guard (unnecessary overhead)
- Make `validateItemAccess` generic with <T> (adds complexity for little benefit)
I think the current typing is a reasonable trade-off. 
The cast is localized and explicit. 

Thoughts?

File: api/src/services/assets.ts (hunk 13 above)
Comment (gaetansenn) [reply api/src/services/assets.ts]: Hum okay I see yes let's just revert the logic

File: api/src/controllers/assets.ts
Comment (ComfortablyCoding) [reply api/src/controllers/assets.ts:1]: I meant we should handle the case where `modified_on` is not provided/allowed. It seems we already handle it as `Date.parse` will return NaN for undefined.

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 9 above)
Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: `injectCases` use uniq() for dedupe

File: api/src/controllers/assets.ts
Comment (gaetansenn) [reply api/src/controllers/assets.ts:1]: Yes it's already the case it's going to be undefined

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 9 above)
Comment (ComfortablyCoding) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: > For the deduplication, if I handle the case where both fields and returnAllowedRootFields are passed, I can't use injectCases directly since it replaces all cases. I'd need to use getCases to inject cases only for the new fields (with offset-adjusted indices) to preserve the work done by processAst.

If it replaces all cases would that not mean it should already be deduplicating the where cases? 

> That said, this case is pretty rare. Do we really need to handle it?

If needed, yes we should.

File: api/src/services/assets.ts (hunk 12 above)
Comment (ComfortablyCoding) [reply api/src/services/assets.ts]: We can cast the allowedFields before passing them in, if we then type the allowed fields as keys would that help?

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 9 above)
Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Sorry removed that comment, We can leave like that as injectCases deduplicating the where cases

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 14]
```diff
@@ -43,22 +55,61 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+	// If returnAllowedRootFields, build a map of allowed fields per item
+	if (options.returnAllowedRootFields && items.length > 0) {
+		const allowedRootFieldsMap: Record<string, string[]> = {};
+
+		for (const item of items) {
+			const id = String(item[primaryKeyField]);
 
-		if (fields) {
-			return items.every((item: any) => fields.every((field) => toBoolean(item[field])));
+			allowedRootFieldsMap[id] = Object.keys(item).filter((field) => field !== primaryKeyField && item[field] === 1);
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: While obvious due to being at this point in the code I do not see a reason to remove the primaryKeyField from the list? This would potentially result in us removing the primary key field later in our sanitizieField function in the asset service.

File: .changeset/fresh-doodles-eat.md [hunk 15]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
+---
+
+Fixed unauthorized field exposure in asset responses
```
Comment (ComfortablyCoding) [inline .changeset/fresh-doodles-eat.md]:
```suggestion
Fixed `getAsset` returning all file fields instead of only those allowed by the users permissions
```

File: .changeset/fresh-doodles-eat.md [hunk 16]
```diff
@@ -0,0 +1,5 @@
+---
+'@directus/api': patch
```
Comment (ComfortablyCoding) [inline .changeset/fresh-doodles-eat.md]:
```suggestion
'@directus/api': major
```

File: api/src/services/assets.ts (hunk 12 above)
Comment (gaetansenn) [reply api/src/services/assets.ts]: allowedFields can also contain '*'

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 17]
```diff
@@ -43,22 +55,61 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+	if (options.fields) {
+		accessAllowed = items.every((item: any) => options.fields!.every((field) => toBoolean(item[field])));
+	}
+
+	// If returnAllowedRootFields, build a map of allowed fields per item
+	if (options.returnAllowedRootFields && items.length > 0) {
+		const allowedRootFieldsMap: Record<string, string[]> = {};
+
+		for (const item of items) {
+			const id = String(item[primaryKeyField]);
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Wouldn’t this end up being a 0 or 1 rather than the actual value? I don’t think we can reliably determine which record corresponds to which item/field permissions. We may need to remove the map and handle it the same way we process fields: if a field has a value of 1 for all items, then it can be considered allowed for all items and should be marked as such.

File: api/src/services/assets.ts [hunk 18]
```diff
@@ -86,16 +105,28 @@ export class AssetsService {
 		 */
 		if (!isValidUuid(id)) throw new ForbiddenError();
 
-		if (systemPublicKeys.includes(id) === false && this.accountability) {
-			await validateAccess(
+		let allowedFields: string[] | undefined;
+
+		if (!systemPublicKeys.includes(id) && this.accountability && !this.accountability.admin) {
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: Let's simplify this.
```suggestion
		if (!systemPublicKeys.includes(id) && this.accountability?.admin !== true) {
```

**Review by ComfortablyCoding — DISMISSED** [review]

File: api/src/services/assets.ts (hunk 18 above)
Comment (gaetansenn) [reply api/src/services/assets.ts]: Okay, but then I need to cast to a non-null assertion. But yes, we can do it that way.

Comment (ComfortablyCoding) [reply api/src/services/assets.ts]: That's unfortunate, let's leave it but be consistent with other locations

```suggestion
		if (!systemPublicKeys.includes(id) && this.accountability && this.accountability.admin !== true) {
```

File: api/src/services/assets.ts [hunk 19]
```diff
@@ -50,6 +50,25 @@ export class AssetsService {
 		this.filesService = new FilesService({ ...options, accountability: null });
 	}
 
+	private sanitizeFields(file: File, allowedFields: string[] | undefined): Partial<File> {
+		if (!allowedFields || allowedFields.includes('*')) {
+			return file;
+		}
+
+		const bypassFields: (keyof File)[] = ['type', 'filesize', 'storage', 'filename_disk'];
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: Was `storage` and `filename_disk` added intentionally? These should not be bypassed fields as they cannot introspected from the file.

Comment (gaetansenn) [reply api/src/services/assets.ts]: Oh yeah sorry was a mistake from the tests

**Review by ComfortablyCoding — DISMISSED** [review]
Removing permission to read `filename_disk` results in an internal 500 error when attempting to download
```
ERROR: Cannot extract access permissions for field "filename_disk" in collection "directus_files"
    err: {
      "type": "Error",
      "message": "Cannot extract access permissions for field \"filename_disk\" in collection \"directus_files\"",
      "stack":
          Error: Cannot extract access permissions for field "filename_disk" in collection "directus_files"
              at processChildren (/directus/api/src/permissions/modules/process-ast/lib/inject-cases.ts:42:10)
              at injectCases (/directus/api/src/permissions/modules/process-ast/lib/inject-cases.ts:14:14)
              at validateItemAccess (/directus/api/src/permissions/modules/validate-access/lib/validate-item-access.ts:75:3)
              at async AssetsService.getAsset (/directus/api/src/services/assets.ts:112:49)
              at async <anonymous> (/directus/api/src/controllers/assets.ts:204:34)
      "extensions": {
        "stack":
            Error: Cannot extract access permissions for field "filename_disk" in collection "directus_files"
                at processChildren (/directus/api/src/permissions/modules/process-ast/lib/inject-cases.ts:42:10)
                at injectCases (/directus/api/src/permissions/modules/process-ast/lib/inject-cases.ts:14:14)
                at validateItemAccess (/directus/api/src/permissions/modules/validate-access/lib/validate-item-access.ts:75:3)
                at async AssetsService.getAsset (/directus/api/src/services/assets.ts:112:49)
                at async <anonymous> (/directus/api/src/controllers/assets.ts:204:34)
      }
    }
```


https://github.com/user-attachments/assets/1e6491d6-fd73-411b-92f4-b664e8f01793

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 20]
```diff
@@ -43,22 +55,63 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+			context,
+		);
+
+		const schemaFields = Object.keys(context.schema.collections[options.collection]!.fields);
+		const hasWildcard = permissions.some((p) => p.fields?.includes('*'));
+
+		const allowedFields = hasWildcard ? new Set(schemaFields) : new Set(permissions.flatMap((p) => p.fields ?? []));
+
+		// Create children only for fields that exist in schema and are allowed by permissions
+		ast.children = Array.from(allowedFields)
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: In the interest of reducing code duplication let's replace this with `fetchAllowedFields`
```suggestion
		const allowedFields = await fetchAllowedFields(
			{ action: options.action, collections: [options.collection], accountability: options.accountability },
			context,
		);

		const schemaFields = Object.keys(context.schema.collections[options.collection]!.fields);
		const hasWildcard = allowedFields.some((field) => field === '*');

		const permissionedFields = hasWildcard ? schemaFields : fetchAllowedFields;

		// Create children only for fields that exist in schema and are allowed by permissions
		ast.children = Array.from(permissionedFields)
```

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts [hunk 21]
```diff
@@ -43,22 +55,63 @@ export async function validateItemAccess(options: ValidateItemAccessOptions, con
...
+			.filter((field) => context.schema.collections[options.collection]!.fields[field])
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: This filter should not be necessary after [the `fetchAllowedFields` update](https://github.com/directus/directus/pull/25905/files#r2611795629) as [it ensures fields exist on the schema](https://github.com/directus/directus/blob/main/api/src/permissions/modules/fetch-allowed-fields/fetch-allowed-fields.ts#L39)
```suggestion
```

File: api/src/services/assets.ts [hunk 22]
```diff
@@ -203,16 +222,28 @@ export class AssetsService {
 		 */
 		if (!isValidUuid(id)) throw new ForbiddenError();
 
-		if (systemPublicKeys.includes(id) === false && this.accountability) {
-			await validateAccess(
+		let allowedFields: string[] | undefined;
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: Let's default this to `*` instead of undefined to reduce cases that need to be checked
```suggestion
		let allowedFields: string[] = ['*']
```

File: api/src/permissions/modules/validate-access/lib/validate-item-access.test.ts [hunk 23]
```diff
@@ -158,5 +165,266 @@ test('Returns false if the number of returned items matches the number of reques
...
+			c.field('field-b').string();
+			c.field('field-c').string();
+			c.field('field-d').string();
+		})
+		.build();
+
+	const acc = {} as unknown as Accountability;
+
+	vi.mocked(fetchPolicies).mockResolvedValue([]);
+	vi.mocked(fetchPermissions).mockResolvedValue([{ fields: ['*'] } as Permission]);
```
Comment (ComfortablyCoding) [inline api/src/permissions/modules/validate-access/lib/validate-item-access.test.ts]: We should either keep the fetchPermissions response inline with the `fetchPermittedAstRootFields` response or use a default mock. The current implies full access while `fetchPermittedAstRootFields` indicates otherwise.

For example this should be a conflicting permission to result in null, e.g.
```
[
  {
    fields: ["field-a", "field-b", "field-d"],
    permissions: {
      _and: [
        {
          id: {
            _eq: 1,
          },
        },
      ],
    },
  },
  {
    fields: ["field-c"],
    permissions: {
      _and: [
        {
          id: {
            _eq: 2,
          },
        },
      ],
    },
  },
] as Permission[];
```

File: api/src/services/assets.test.ts
Comment (ComfortablyCoding) [inline api/src/services/assets.test.ts:1]: We should ideally be using our [test-utils](https://github.com/directus/directus/tree/main/api/src/test-utils) where possible

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 20 above)
Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Good catch ! 
Used `fetchAllowedFields` as suggested. 
Note: I still kept `fetchPolicies/fetchPermissions` for injectCases() below since it needs the full permissions object, but since they're cached there's no performance impact

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 21 above)
Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Removed the filter good point :)

File: api/src/permissions/modules/validate-access/lib/validate-item-access.ts (hunk 20 above)
Comment (ComfortablyCoding) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: > Note: I still kept fetchPolicies/fetchPermissions for injectCases() below since it needs the full permissions object, but since they're cached there's no performance impact

That is unfortunate :(

Comment (ComfortablyCoding) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Ideally they would be optionally passed in, otherwise defaulted to fetching from cache. Something we can look into in a different PR if needed.

Comment (gaetansenn) [reply api/src/permissions/modules/validate-access/lib/validate-item-access.ts]: Makes sense, happy to look into that in a follow-up PR :)

File: api/src/services/assets.ts [hunk 24]
```diff
@@ -203,16 +222,28 @@ export class AssetsService {
...
 				{ knex: this.knex, schema: this.schema },
 			);
+
+			if (!accessAllowed) {
+				throw new ForbiddenError({
+					reason: `You don't have permission to perform "read" for collection "directus_files" or it does not exist.`,
+				});
+			}
+
+			allowedFields = allowedRootFields ?? ['*'];
```
Comment (ComfortablyCoding) [inline api/src/services/assets.ts]: Ideally we adjust the type so `allowedRootFields` is defined when `returnAllowedRootFields` is true as it will always be at least an empty array.

Comment (gaetansenn) [reply api/src/services/assets.ts]: Yes, that’s a good idea !Let’s update it

File: api/src/services/assets.test.ts
Comment (gaetansenn) [reply api/src/services/assets.test.ts:1]: Regarding test-utils usage in `assets.test.ts` the file already uses the available test-utils.
The remaining manual mocks don't have corresponding test-utils available

That said, I noticed that `fetchPermissions` and `fetchPolicies` are mocked manually in 12 different test files across the codebase. These would be good candidates for new `test-utils`. 
We can add mockFetchPermissions() and mockFetchPolicies() utilities in a separate PR to reduce duplication across those files?

Comment (ComfortablyCoding) [reply api/src/services/assets.test.ts:1]: It uses it in some places (e.g. mockDatabase) but not others (e.g. mockSchema), lets stay consistent. In regards to mocking fetchPermissions/fetchPolicies, if it is something trivial that can be done lets go for it.

Comment (gaetansenn) [reply api/src/services/assets.test.ts:1]: The existing `mockSchema()` in test-utils is for mocking the @directus/schema module (createInspector), not for creating a `SchemaOverview` object.
We could create a `createEmptySchema()` utility, but looking at the codebase, test files use inconsistent structures
If we add the createEmptySchema utils, this would require touching 14 files and deciding on the correct structure.

For `fetchPermissions/fetchPolicies` test-utils, creating them is trivial, but applying them would touch 15 files across the codebase.
I'd prefer to keep this PR focused and handle the test-utils cleanup in a separate PR no ?

Comment (ComfortablyCoding) [reply api/src/services/assets.test.ts:1]: > The existing mockSchema() in test-utils is for mocking the @directus/schema module (createInspector), not for creating a SchemaOverview object.
> We could create a createEmptySchema() utility, but looking at the codebase, test files use inconsistent structures
> If we add the createEmptySchema utils, this would require touching 14 files and deciding on the correct structure.


Good point and agreed. Let's leave that for now.

> For fetchPermissions/fetchPolicies test-utils, creating them is trivial, but applying them would touch 15 files across the codebase.
> I'd prefer to keep this PR focused and handle the test-utils cleanup in a separate PR no ?

We can add it as a new util and apply it for these new tests. Ensuring other files are inline can be left to other PRs that touch those files.

Comment (ComfortablyCoding) [reply api/src/services/assets.test.ts:1]: Let's leave this for now, not a blocker.

**Review by ComfortablyCoding — APPROVED** [review]

**Review by AlexGaillard — APPROVED** [review]
