### PR TITLE
SSO fixes and improvements

### LINKED ISSUE #10233: OIDC: refresh grant improperly handles new refresh_token
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using an OIDC provider that provides a new refresh_token on a refresh grant flow, the old refresh_token is invalidated. Directus should be able to handle this by storing the new refresh_token in place of the existing refresh_token. 

See discussion #10148 for further details. 

### To Reproduce

Use an OIDC provider that provides a new refresh_token and new access_token on a refresh grant.
See discussion #10148 for further details. 

### Errors Shown

Directus simply says the refresh_token is invalid. Server side logs:

```
Dec 01 01:07:51 simplesamlphp DEBUG [21cd28ea1b] Token Request: {"grant_type":"authorization_code","code":"<snip>","redirect_uri":"http:\/\/mydomain.com\/directus\/auth\/login\/sso\/callback","code_verifier":"<snip>"}
Dec 01 01:07:51 simplesamlphp DEBUG [21cd28ea1b] Token Response: {"id_token":"<snip>","token_type":"Bearer","expires_in":3600,"access_token":"<snip>","refresh_token":"<refreshtoken1>"}
Dec 01 01:07:51 simplesamlphp DEBUG [61a0e80b4b] Token Request: {"grant_type":"refresh_token","refresh_token":"<refreshtoken1>"}
Dec 01 01:07:51 simplesamlphp DEBUG [61a0e80b4b] Token Response: {"id_token":"<new id token>","token_type":"Bearer","expires_in":3600,"access_token":"<new access token>","refresh_token":"<refreshtoken2>"}
Dec 01 01:07:52 simplesamlphp DEBUG [105214b31c] Token Request: {"grant_type":"refresh_token","refresh_token":"<refreshtoken1>"}
Dec 01 01:07:52 simplesamlphp ERROR [105214b31c] SimpleSAML\Module\oidc\Server\Exceptions\OidcServerException: The refresh token is invalid.
```

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

Whatever comes with the Docker container

### What database are you using?

MariaDB 10.4

### What browser are you using?

Chrome

### What operating system are you using?

RHEL 7

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by aidenfoxx**
Sorry for bundling things together. I can split them out if required.

- Fixes #10233 (update `refresh_token` if one is provided in the `refresh()` call)
- Added ability to set custom authorization URL parameters
- Added ability to specify `issuerUrl` in OAuth2 flow (required when using OpenID)
- Added handling for if `refresh_token` is invalidated
  1. During login we trigger a refresh to verify the `refresh_token` validity
  2. On `InvalidTokenException` trigger the SSO authorization page with a `prompt=consent` to request a new `refresh_token`
  3. Fail if token continues to be invalid

### CODE REVIEW

File: api/src/auth/drivers/openid.ts [hunk 1]
```diff
@@ -62,17 +67,21 @@ export class OpenIDAuthDriver extends LocalAuthDriver {
 		return generators.codeVerifier();
 	}
 
-	async generateAuthUrl(codeVerifier: string): Promise<string> {
+	async generateAuthUrl(codeVerifier: string, prompt = false): Promise<string> {
```
Comment (aidenfoxx) [inline api/src/auth/drivers/openid.ts:70]:
```suggestion
	async generateAuthUrl(codeVerifier: string, prompt: boolean = false): Promise<string> {
```

File: api/src/auth/drivers/oauth2.ts [hunk 2]
```diff
@@ -53,16 +59,20 @@ export class OAuth2AuthDriver extends LocalAuthDriver {
 		return generators.codeVerifier();
 	}
 
-	generateAuthUrl(codeVerifier: string): string {
+	generateAuthUrl(codeVerifier: string, prompt = false): string {
```
Comment (aidenfoxx) [inline api/src/auth/drivers/oauth2.ts:62]:
```suggestion
	generateAuthUrl(codeVerifier: string, prompt: boolean = false): string {
```

File: api/src/auth/drivers/oauth2.ts [hunk 3]
```diff
@@ -53,16 +59,20 @@ export class OAuth2AuthDriver extends LocalAuthDriver {
 		return generators.codeVerifier();
 	}
 
-	generateAuthUrl(codeVerifier: string): string {
+	generateAuthUrl(codeVerifier: string, prompt: boolean = false): string {
```
Comment (aidenfoxx) [inline api/src/auth/drivers/oauth2.ts:62]:
```suggestion
	generateAuthUrl(codeVerifier: string, prompt = false): string {
```

File: api/src/auth/drivers/openid.ts [hunk 4]
```diff
@@ -62,17 +67,21 @@ export class OpenIDAuthDriver extends LocalAuthDriver {
 		return generators.codeVerifier();
 	}
 
-	async generateAuthUrl(codeVerifier: string): Promise<string> {
+	async generateAuthUrl(codeVerifier: string, prompt: boolean = false): Promise<string> {
```
Comment (aidenfoxx) [inline api/src/auth/drivers/openid.ts:70]:
```suggestion
	async generateAuthUrl(codeVerifier: string, prompt = false): Promise<string> {
```

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
LGTM!
