### PR TITLE
Fix styling issues with the related-values display

### LINKED ISSUE #21853: Styling issues when rendering the related-values display in the render-template component
### Describe the Bug

The `<related-values>` display is not properly aligned and on mouse-over, the appearing gray background that appears overlaps its siblings and is cut off by the `<render-template>`.

### To Reproduce

issue

### Directus Version

v.10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #22160: Select box text is cut off when Directus Minimal theme is selected
### Describe the Bug

Directus Minimal - cut off text:

Directus Minimal - cut off

Directus Default theme - everything ok:

Directus Default theme - everything ok

### To Reproduce

Create collection, add O2M relation field to other collection. Make relation.

Change theme through Directus / Appearance from Directus Default to Directus Minimal.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by formfcw**
## Scope

What's changed:

- changed vertical padding of `v-list-items.block` (+ `.dense`) to provide more space for the render-template
  - this prevents the render-template from cutting off the mouseover-background of the `related-values` display
  - this also affects thumbnails as they get larger
- fix alignment and overlapping of `related-values` display within the `render-template`
- made `height` and `padding` of v-list-item.block (+ `.dense`) more dynamic

Before:
issue

After:
fix

## Potential Risks / Drawbacks

- Could cause visual bugs on other parts of the app, even though I've tested many use cases
  - default and dense listing
  - m2m, m2a listings
  - table layout
  - title in the drawer

## Review Notes / Questions

- Feel free to change things

---

Fixes #21853
Potentially fixes #22160

### CODE REVIEW

File: app/src/displays/related-values/related-values.vue [hunk 1]
```diff
@@ -108,16 +108,19 @@ function getLinkForItem(item: any) {
 </template>
 
 <style lang="scss" scoped>
+$toggle-px: 6px;
+$toggle-py: 4px;
```
Comment (paescuj) [inline app/src/displays/related-values/related-values.vue:112]: I don't think we're using SCSS variables in other components.
For the sake of consistency, let's use native CSS `var`.

File: app/src/displays/related-values/related-values.vue [hunk 2]
```diff
@@ -130,17 +133,28 @@ function getLinkForItem(item: any) {
...
-.subdued {
+.render-template {
+	> .v-menu {
+		display: inline;
+
+		.toggle {
+			margin: $toggle-py $toggle-px;
+		}
+	}
+}
```
Comment (paescuj) [inline app/src/displays/related-values/related-values.vue:153]: Is this related to the same `toggle` element as above?
If so, let's merge & nest the styles for more clarity.

File: app/src/components/v-list-item.vue [hunk 3]
```diff
@@ -258,7 +258,10 @@ function onClick(event: PointerEvent) {
 	&.block {
 		--v-icon-color: var(--v-icon-color, var(--theme--foreground-subdued));
 
-		padding: var(--v-list-item-padding, var(--theme--form--field--input--padding));
+		padding: var(
+			--v-list-item-padding,
+			calc(var(--theme--form--field--input--height) * 0.13333) var(--theme--form--field--input--padding)
```
[the remark this answers is not in the document]
Comment (formfcw) [reply app/src/components/v-list-item.vue]: The idea with `0.13333` was to provide a relative value that works for both the normal and the dense heights. But I agree with you that it makes it hard to read.

**Review by rijkvanzanten — APPROVED** [review]
