### PR TITLE
Update TinyMCE to fix issue with readonly mode

### LINKED ISSUE #19278: WYSIWYG editor becomes incorrectly disabled
### Describe the Bug

A field using the WYSIWYG interface becomes disabled when the interface has been used in another page.

I have a collection with a WYSIWYG field.

When I interact with an item in this collection for the first time after a full page refresh, the field works fine and I can edit my content and save the item.

However, when I try again with another item or the same, the field is disabled and the value can't be edited (except with the "dit raw value" button)

### To Reproduce

1. Create a collection
2. Add a field in standard mode, chosing the "WYSIWIG" option with default settings
3. Create an item of this collection : the wysiwyg field works fine
4. Edit the created item : the field is disabled
5. refresh the page : the field is enabled.
6. Modify the field and save the item
7. Edit the same item : the field is disabled

### Directus Version

v10.5.1

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #19278

When reloading the page, the initial value for `disabled` is usually true usually because data being in `loading` state.
It seems there was a bug in TinyMCE that the initial edit mode could not be changed afterwards.
Couldn't find anything in the changelog, though.

### CODE REVIEW

File: app/src/interfaces/input-rich-text-html/input-rich-text-html.vue [hunk 1]
```diff
@@ -246,7 +246,6 @@ const props = withDefaults(
 		],
 		font: 'sans-serif',
 		customFormats: () => [],
-		disabled: true,
```
Comment (paescuj) [inline app/src/interfaces/input-rich-text-html/input-rich-text-html.vue:249]: Unrelated to this issue, but I don't think we should explicitly set the `disabled` value in the interface.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by u12206050** [comment]
Ive updated to 10.5.2 after seeing this issue, but after updating it still seems to be an issue. It works when I reload the page but when I navigate to another item then it is in readonly mode again.
