### PR TITLE
Prevent MySQL collation errors

### LINKED ISSUE #9897: Error when i change template of M2O
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a relation M2O and when i try to change display template it returns error
Video explain better

https://user-images.githubusercontent.com/63153191/142278988-30528e49-9aaf-4af3-9357-8416b3c51a33.mov

### To Reproduce

Create a M2O relationship and change the template.
This error doesn't appear everytime, i have the same relation in other content types with, and they don't give errors.

### Errors Shown

[INTERNAL_SERVER_ERROR] alter table `Spazi_page` modify `SEO` int null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'SEO': used in a foreign key constraint 'spazi_page_seo_foreign'
content_copy

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

### LINKED ISSUE #11242: Making relation field readonly failes
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Making relation field readonly immediately after creation failes

### To Reproduce

1. Create a new data model
2. Add a relational field (Many-to-one)
3. After this edit it and set it to readonly

### Errors Shown

```
{
  "errors": [
    {
      "message": "alter table `wayforpay_payments` modify `order` int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'order' and referenced column 'id' in foreign key constraint 'wayforpay_payments_order_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by oreilles**
MySQL uses a total of [8 different system variables](https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html) to determine how to handle strings.

- `character_set_client`
- `character_set_results`
- `character_set_connection`( &&`collation_connection` )
- `character_set_database`( &&`collation_database` )
- `character_set_server` ( &&`collation_server` )

When receiving a query, all strings are interpreted as `character_set_client`, translated to `character_set_connection`, then all results are sent back to the client after translation from `character_set_database` (or whatever the table's character set is) to `character_set_results`.

`character_set_connection` is important for two different reason: it will use that specific character set to compare two literal string sent by the client, e.g. `select 'Hello' = 'Hëllo'` - and, more importantly, all table and columns created from that connection will be created with that character set (and collation).

The problem many people are facing, is that they are managing their database with tables and columns that matches their database default, and are then using Directus, which uses `node-mysql`, which uses `UTF8` for the connection regardless of the database default.

What we want is the IO to be performed in UTF8, and the database operations to be performed with the database default character set and collation. And there's a command that does exactly that:
```sql
SET CHARACTER SET 'UTF8MB4'.
-- translates to:
SET character_set_client = 'UTF8MB4';
SET character_set_results = 'UTF8MB4';
SET collation_connection = @@collation_database;
```

This change is going to be painful for a lot of people. Because it used to be recommended that people set their `DB_CHARSET` environment variable for MySQL, and that people who have been deploying directus using `npm init directus-project` or `npx directus bootstrap` didn't have an environment file yet, close to 100% of MySQL users currently have all of their Directus system tables ( as well as all the table they created with the app ) in `utf8_general_ci`.

This change means that until they fix *all* those tables *and columns* collation to match their database default, every relation creation will fail. For that reason, I think we should fix the bug allowing the relational field to be created even if the relation creation fails. (https://github.com/directus/directus/issues/10564) before merging this PR, or the amount of related bug report will skyrocket.

Fixes https://github.com/directus/directus/issues/9897
Fixes https://github.com/directus/directus/issues/11242

### CODE REVIEW

**Review by rijkvanzanten — COMMENTED** [review]
@Oreilles Could you provide a brief set of instructions on how to ensure that the Directus tables use the correct charset? Would be even nicer if we could provide some SQL to run 🙂

File: api/src/database/index.ts [hunk 1]
```diff
@@ -243,3 +247,21 @@ export async function validateDatabaseExtensions(): Promise<void> {
...
+			.select(`collation_name as collation`)
+			.where({ table_name: 'directus_users', column_name: 'id' })
+			.first();
+		const databaseResult = await database.select(database.raw(`@@collation_database as collation`)).first();
+		if (directusResult?.collation === databaseResult.collation) {
+			logger.warn(
+				`Directus tables collation (${directusResult.collation}) don't match your database default collation (${databaseResult.collation}).`
+			);
+		}
+		await database.raw("SET CHARACTER SET 'UTF8MB4'");
```
Comment (rijkvanzanten) [inline api/src/database/index.ts:264]: Is this going to be a problem? UTF8MB4 seems like a good default, but also feels like something that might be a tad too opinionated 🤔

File: api/src/database/index.ts [hunk 2]
```diff
@@ -19,6 +19,13 @@ export default function getDatabase(): Knex {
 		return database;
 	}
 
+	if (env.DB_CLIENT === 'mysql') {
+		if (env.DB_CHARSET) {
+			logger.warn(`DB_CHARSET has been deprecated and now has no effect.`);
+			env.DB_CHARSET = null;
+		}
+	}
```
Comment (rijkvanzanten) [inline api/src/database/index.ts:27]:
```suggestion
```

I think we can still allow DB_CHARSET for power users, as long as we throw appropriate warnings about misusage in the validateDatabaseCharset step below

File: api/src/database/index.ts (hunk 1 above)
Comment (rijkvanzanten) [inline api/src/database/index.ts:264]: This may or may not be needed. On my end, the `mysql` package correctly defaults to the database collection for DDL operations.

File: api/src/database/index.ts [hunk 3]
```diff
@@ -243,3 +247,21 @@ export async function validateDatabaseExtensions(): Promise<void> {
...
 	}
 }
+
+async function validateDatabaseCharset(database?: Knex): Promise<void> {
+	database = database ?? getDatabase();
+	if (getDatabaseClient(database) === 'mysql') {
+		const directusResult = await database('information_schema.columns')
+			.select(`collation_name as collation`)
+			.where({ table_name: 'directus_users', column_name: 'id' })
+			.first();
```
Comment (rijkvanzanten) [inline api/src/database/index.ts:257]: Lets check against all the Directus system columns, instead of just `directus_users.id`

File: api/src/database/index.ts [hunk 4]
```diff
@@ -243,3 +247,21 @@ export async function validateDatabaseExtensions(): Promise<void> {
...
+		const databaseResult = await database.select(database.raw(`@@collation_database as collation`)).first();
+		if (directusResult?.collation === databaseResult.collation) {
+			logger.warn(
+				`Directus tables collation (${directusResult.collation}) don't match your database default collation (${databaseResult.collation}).`
+			);
+		}
```
Comment (rijkvanzanten) [inline api/src/database/index.ts:263]: Lets check against `DB_CHARSET ?? databaseDefaultCollation`. When the user has a custom DB_CHARSET, the system tables should have that as well (I think)

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
On my end, mysql seems to correctly default to the current database charset/collation. If that's consistently the case, we should be able to clean this up a bit, and mostly lean on warnings to prevent user mistakes 🤔

**Review by rijkvanzanten — APPROVED** [review]
