### PR TITLE
Fix generated columns being required. 

### LINKED ISSUE #9196: directus tries to update computed field when using translation interface
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

when trying to update a translation (through the translation interface in the "main" collection) that contains a computed field, directus tries to save the value of the computed field to the database

### To Reproduce

- create collection `foo`
- add `translations` field to `foo` _(as of v99 I need to manually setup the translation, cause of a [known issue](https://github.com/directus/directus/issues/9069); but that doesn't influence this issue; I'm using the default names for the setup)_
- add standard field `bar` to `foo_translations` of type `string`
- create an entry of `foo` with a value of your choosing for `bar` (1 language is enough)
image

- add computed field `baz` to `foo_translations` through sql (`ALTER TABLE foo_translations ADD baz AS('imcomputed!')`)
- click on the field in the data model to configure it through directus (don't need to change anything)
- try to edit the entry of `foo` you inserted changing the value of `bar`
image

- the entry cannot be edited and an error is shown:

### Errors Shown

image

```json
{
  "message": "update [foo_translations] set [foo_id] = @p0, [languages_id] = @p1, [bar] = @p2, [baz] = @p3 where [id] in (@p4);select @@rowcount - The column \"baz\" cannot be modified because it is either a computed column or is the result of a UNION operator.",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

### What version of Directus are you using?

v9.0.0-rc.99

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

### PR DESCRIPTION
**Pull request by oreilles**
Changes:
* Add `generated` prop to `FieldOverview`
* Add `is_generated` prop to `SchemaOverview[<table>]['columns'][<column>]`
* Never add generated columns to the list of required fields in `AuthorizationService.validatePayload`

Also prevent schema changes on generated columns by disabling non-editable fields `unique` and `nullable` and hiding non applicable fields `default_value` and `required` (subject to modification).

Should fix https://github.com/directus/directus/issues/9189
Should fix https://github.com/directus/directus/issues/9196

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

File: packages/schema/src/dialects/mssql.ts [hunk 1]
```diff
@@ -15,8 +15,10 @@ export default class MSSQL extends KnexMSSQL implements SchemaInspector {
 				c.IS_NULLABLE as is_nullable,
 				c.DATA_TYPE as data_type,
 				c.CHARACTER_MAXIMUM_LENGTH as max_length,
+       			cc.is_computed as is_generated,
```
Comment (rijkvanzanten) [inline packages/schema/src/dialects/mssql.ts:18]: cc doesn't exist here

Comment (Oreilles) [reply packages/schema/src/dialects/mssql.ts:18]: Oh. This has to be removed, it was from another solution I tried.
