### PR TITLE
Modular authentication

### LINKED ISSUE #6927: Reset Password Form giving "Invalid Payload"
### Describe the Bug

Reset password flow on RC-85 appears broken. After clicking the link and filling out the new password, the form gives a validation error "Invalid Payload"

Inspecting the network the real error is:
 `{"errors":[{"message":"\"token\" field is required.","extensions":{"code":"INVALID_PAYLOAD"}}]}`
 
 But looking at the payload it appears the token is being passed in the body.
 
 ```
 {"password":"password","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlcmVrQGxhbWJkYWN1cnJ5LmRldiIsInNjb3BlIjoicGFzc3dvcmQtcmVzZXQiLCJpYXQiOjE2MjY5NjQ2MDIsImV4cCI6MTYyNzA1MTAwMn0.2lsiTBvy46Tswc9YHPNq1zfvUwimOWqIwO0Bb7l-06Y"}
 ```
 
Screenshots:

Screen Shot 2021-07-22 at 9 37 03 AM
Screen Shot 2021-07-22 at 9 37 43 AM
Screen Shot 2021-07-22 at 9 38 00 AM

### To Reproduce

Using Directus 9.0.0-rc-85, go through the reset password flow, attempt to update your password and receive the error indicated above.

### What version of Directus are you using?

9.0.0-rc-85

### What version of Node.js are you using?

Whatever is in the Directus docker image

### What database are you using?

Mariadb latest

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### LINKED ISSUE #6948: POST /users throws 500 instead of 400 with invalid payload
### Describe the Bug

API response
````json
{
    "errors": [
        {
            "message": "An unexpected error occurred.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
````

console
````
TypeError: Cannot read property 'toLowerCase' of undefined
    at UsersService.createOne (/node_modules/directus/dist/services/users.js:86:34)
    at /node_modules/directus/dist/controllers/users.js:27:35
    at scoped (/node_modules/directus/dist/utils/async-handler.js:5:60)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
````

### To Reproduce

- install of Directus using `npx create-directus-project`
- `POST http://localhost:8055/users` request without any authentication (e.g. via Postman)

### What version of Directus are you using?

v9.0.0-rc.85

### What version of Node.js are you using?

v12.22.3

### What database are you using?

Postgres

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

### LINKED ISSUE #8163: Accept user invitation doesn't trigger users update hooks
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Accepting user invitation is mutating the user. It updates its password and its status.
It should trigger the corresponding users update hooks (before/after).

### To Reproduce

Invite a user and accept the invitation.
No users update hooks are trigerred.

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v14.16.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by aidenfoxx**
Broke authentication out into a modular implementation to allow better integration with alternative auth methods. Also fixed a number of bugs, including #6927.

The updated flow uses "auth providers" which are uniquely configured authentication services similar to how the storage implementation works. For example, a Directus instance could have 2 LDAP auth providers which both implement the LDAP service, but are configured to point to different servers. Each provider would have their own login pages (which are linked with the existing SSO links).

Screenshot 2021-07-24 at 15 08 46

With this initial implementation all auth providers use a standard login page which accepts an "Identifier" and "Password".

Screenshot 2021-07-24 at 15 09 23

The implementation of new providers uses a standard interface defined [here](https://github.com/directus/directus/pull/6942/files#diff-342f586c30b6e82af3f65afc6e7164e76ac8870ae3719b6cea712ed050b35a34), which should allow for somewhat flexible integrations while also working with the Directus core.

Fixes #6927, fixes #6948
closes #8163 and #8229

### CODE REVIEW

File: app/src/modules/users/routes/item.vue [hunk 1]
```diff
@@ -102,7 +102,7 @@
 			<div v-if="isNew === false" class="user-box">
 				<div class="avatar">
 					<v-skeleton-loader v-if="loading || previewLoading" />
-					<img v-else-if="avatarSrc" :src="avatarSrc" :alt="item.email" />
+					<img v-else-if="avatarSrc" :src="avatarSrc" :alt="Avatar" />
```
Comment (aidenfoxx) [inline app/src/modules/users/routes/item.vue:105]: Should probably be localized

Comment (rijkvanzanten) [reply app/src/modules/users/routes/item.vue:105]: Also, this will crash as it tries to read `Avatar` as a variable. 

```suggestion
					<img v-else-if="avatarSrc" :src="avatarSrc" alt="Avatar" />
```

or 

```suggestion
					<img v-else-if="avatarSrc" :src="avatarSrc" :alt="t('avatar')" />
```

File: app/src/routes/login/components/sso-links.vue [hunk 2]
```diff
@@ -1,9 +1,18 @@
 <template>
 	<div class="sso-links">
-		<template v-if="providers && providers.length > 0">
+		<template v-if="authProviders?.length > 0 || oauthProviders?.length > 0">
```
Comment (aidenfoxx) [inline app/src/routes/login/components/sso-links.vue:3]:
```suggestion
		<template v-if="authProviders?.length || oauthProviders?.length">
```

File: api/src/services/users.ts [hunk 3]
```diff
@@ -25,49 +22,55 @@ export class UsersService extends ItemsService {
...
+				field: 'email',
+				invalid: duplicates[0],
+			});
+		}
 
-			const results = await query;
+		const query = this.knex
+			.select('email')
+			.from('directus_users')
+			.whereRaw(`LOWER(??) IN (${emails.map(() => '?')})`, ['email', ...emails]);
```
Comment (aidenfoxx) [inline api/src/services/users.ts:52]: Re-add the "toLowerCase" in this function.

File: api/src/services/users.ts [hunk 4]
```diff
@@ -278,22 +293,28 @@ export class UsersService extends ItemsService {
...
 
-		if (!user || user.status !== 'invited') {
+		if (user?.status !== 'invited') {
 			throw new InvalidPayloadException(`Email address ${email} hasn't been invited.`);
 		}
 
-		const passwordHashed = await argon2.hash(password);
-
-		await this.knex('directus_users').update({ password: passwordHashed, status: 'active' }).where({ id: user.id });
+		const service = new UsersService({
```
Comment (aidenfoxx) [inline api/src/services/users.ts:300]: This should use the `UserService.updateOne` to ensure the password meets security requirement.

File: api/src/services/users.ts [hunk 5]
```diff
@@ -95,114 +98,109 @@ export class UsersService extends ItemsService {
...
-	async updateByQuery(query: Query, data: Partial<Item>, opts?: MutationOptions): Promise<PrimaryKey[]> {
-		const email = data.email?.toLowerCase();
-
-		if (email) {
-			await this.checkUniqueEmails([email]);
-		}
-
-		if (data.password) {
-			await this.checkPasswordPolicy([data.password]);
+		if (data.provider !== undefined) {
```
Comment (aidenfoxx) [inline api/src/services/users.ts:171]: We prevent changing the provider after a user is created to prevent future headaches with misconfigured users.

File: api/src/services/authentication.ts [hunk 6]
```diff
@@ -52,17 +50,28 @@ export class AuthenticationService {
...
+				'role',
+				'tfa_secret',
+				'provider',
+				'identifier',
+				'auth_data'
+			)
 			.from('directus_users')
-			.whereRaw('LOWER(??) = ?', ['email', email.toLowerCase()])
+			.where('id', await provider.userID(identifier))
+			.andWhere('provider', providerName)
```
Comment (aidenfoxx) [inline api/src/services/authentication.ts:74]: This should check ignore case.

File: app/src/routes/login/components/sso-links.vue [hunk 7]
```diff
@@ -21,25 +30,28 @@ export default defineComponent({
...
 
 		async function fetchProviders() {
 			loading.value = true;
 
 			try {
-				const response = await api.get('/auth/oauth/');
+				const [authResponse, oauthResponse] = await Promise.all([api.get('/auth/'), api.get('/auth/oauth/')]);
+
+				authProviders.value = authResponse.data.data?.map((providerName: string) => ({
+					name: providerName,
```
Comment (aidenfoxx) [inline app/src/routes/login/components/sso-links.vue:48]: It would be nice if this (and oauth) had underscores parsed out and title formatting.

File: api/src/services/authentication.ts [hunk 8]
```diff
@@ -243,47 +261,56 @@ export class AuthenticationService {
...
+		const user = await this.knex
+			.select<User>(
+				'id',
+				'first_name',
+				'last_name',
+				'email',
+				'password',
+				'status',
+				'role',
+				'tfa_secret',
```
Comment (aidenfoxx) [inline api/src/services/authentication.ts:300]:
```suggestion
```

Doesn't need to be sent to provider.

File: api/src/services/authentication.ts [hunk 9]
```diff
@@ -1,27 +1,25 @@
...
-import { ActivityService } from '../services/activity';
+import { ActivityService } from './activity';
+import { TFAService } from './tfa';
 import { AbstractServiceOptions, Accountability, Action, SchemaOverview, Session } from '../types';
 import { SettingsService } from './settings';
 import { merge } from 'lodash';
 
 type AuthenticateOptions = {
-	email: string;
+	identifier: string;
```
Comment (aidenfoxx) [inline api/src/services/authentication.ts:20]: I just realized this is a breaking change. I think we should map `email = identifier` before firing the `auth` hook and mark the email field as depreciated in the docs, warning users that email may not always represent an email value.

Thoughts @rijkvanzanten?

**Comment by aidenfoxx** [comment]
@rijkvanzanten Any news on this? I've got people at work bugging me about LDAP support

**Comment by xesjkeee** [comment]
Hey @aidenfoxx
I found your PR from Rijk, he said that you are going to integrating LDAP auth to directus.

So, we were discussing with him the new feature at https://github.com/directus/directus/discussions/5205

How do you think, is it really to implement that functional about I spoked in the discussion in this PR? If you wish I can help you to do it

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Heya!

After a long review, I think I've concluded we shouldn't go ahead with the modular approach to the auth providers. I totally get what you were going for, and like we've discussed many times, I do see the potential in allowing for auth classes to be modular pieces that could theoretically be added in as custom extensions in the future. However, at this point in time, I believe that the auth providers are too different and integrated into the system to be easily modularized (even though you got very close to the storage adapter syntax and approach).

As of right now, I believe there's simply too much custom logic that's required to be injected in various part of the app/api for the different auth providers (like oAuth2, but also looking forwards at things like native support for auth0 or keycloak), which means that trying to fit them into a semi-standard base class will cause more tech overhead than worth the benefits of having the flow in a shared auth endpoint. As a matter of fact, I actually think it's a little easier to communicate and reason about the different auth flows if they have dedicated endpoints (like is currently the case for auth vs oauth), even though LDAP and "standard" auth are very similar in terms of IO.

That being said, there's a couple things included in this PR that we should absolutely take on and move in before/while adding in LDAP natively:

* The `provider` field on users, and more importantly the check that only allows you to login with the auth flow you originally signed up with
* The `identifier` (though lets call it _external_ identifier) fields to keep track of LDAP/oAuth provider IDs
* The cleanup in the services (splitting up the MFA stuff into it's own service)
* Checking with the auth provider while refreshing the token, to ensure changes on "the other end" are properly handled on auth token refresh
* The cleanup in the items service (update/delete by query both relying on a get-keys-by-query)
* The new base endpoint in /auth to return the available auth providers, instead of relying on the oauth endpoint to get those configured providers
* The username based auth (as compared to the default email). I think we can make the same functionality possible within the regular auth service by allowing the "identifier" column to be configurable, and have it default to `email`

Other than these already made changes, I think we should discuss adding on the following changes to this PR, or potentially a new PR based off of the existing changes:
* Renaming `/auth/login` to `/auth/local/login` to match the `/auth/<scope>` format so we can more easily communicate the different available flows (eg /auth/local/login, /auth/oauth/, /auth/ldap/login, /auth/auth0/etc)
* Adding a way to disable the local auth altogether, to require use of SSO
* Adding configuration to allow public registration on first login through oAuth/LDAP based on an email-allowlist (w/ a accept-all wildcard)* 
\* This one is probably out of scope for this particular discussion, however important considering I believe your LDAP ideas included auto-registration for users on first login.
* Rename the auth environment variables to be formatted `AUTH_<provider>`, so it'll become `AUTH_LOCAL_IDENTIFIER_FIELD="email"` and `AUTH_OAUTH_PROVIDERS="facebook"` etc

Massive thanks for all your hard work on this, and apologies for the flip-flopping on technical direction! I too was very excited about the notion that these auth flows could easily be plugged in, but as it stands, I think the maintenance overhead due to the hacks required to get the more finicky flows (looking at you oauth/keycloak) working outweighs the benefit of a shared modular system at this time. I'm positive we can lift all the useful tweaks and fixes, and still get the flexibility we're looking for with LDAP, while maintaining a codebase that's easy to maintain.

Lemme know if you'd be down to lift those changes, or if you'd like me to. Either way, I'm super excited to get this LDAP show on the road ✨

**Comment by aidenfoxx** [comment]
@rijkvanzanten Not gonna lie, it does kill me inside that I ditched my old LDAP integration at your behest to create this modular approach. But I'll try not to hold it against you. 😜

> The username based auth (as compared to the default email). I think we can make the same functionality possible within the regular auth service by allowing the "identifier" column to be configurable, and have it default to email

In this case I would prefer renaming to `alternate_identifier` instead of `external_identifier`.

> I believe that the auth providers are too different and integrated into the system to be easily modularized

I'm not sure I fully agree. As we discussed, the modular auth providers are really just hooks on the authentication service. They're kinda kinda dumb in that sense. Assuming all flows lead to authentication service, then the actual modular stuff should kinda just work?

If I'm not misreading you, your biggest concern is the frontend aspect of the integration? How do we get the `identifier` and `secret` to the authentication service (and by virtue the auth provider)? This was something we were aware of, and it is hard to see a complete solution that works with a modular approach.

### Soooooo...

That being the case, is the fix (for now at least) to remove the generic login logic and replace it with bespoke endpoints `/auth/local/login` `/auth/ldap/login` etc?

**Comment by aidenfoxx** [comment]
So I've made the changes mentioned above, but honestly I'm not a fan of the routing. The new API ends up kinda of ugly with the whole `/auth/:driver/:provider/login` format. I kept the `/auth/login` endpoint for backwards compatibility.

I'm also not sure if we should add special naming for auth functions in the graphql API also to mirror the REST changes.

**Comment by rijkvanzanten** [comment]
> Not gonna lie, it does kill me inside that I ditched my old LDAP integration at your behest to create this modular approach. But I'll try not to hold it against you. 😜

Totally get it! And you're more than welcome to hold that against me 🙃 

> If I'm not misreading you, your biggest concern is the frontend aspect of the integration?

That was originally the first point of concern, but on closer look and more thorough thinking through, there's a couple more points where each auth provider has subtle differences. For example:
* oauth uses custom endpoints with a session for it's flow
* hooks would have different payloads (and potentially different/extra hooks altogether) per auth provider
* some auth providers would have to have support for custom tokens/cookies that aren't directus' JWT
* some auth providers might tap into sessions where others don't
* some auth providers might have to rely on custom endpoints/hooks to manipulate the user based on events happening in external services

Long story short, the exact usage and implementation details between the different auth providers will have subtle-to-drastic differences between each flow, so in terms of maintainability and explainability, it would be easier to manage them as standalone flows in both code and documentation/integration 🤔  That way, we have a more simple "This is LDAP from beginning to end" instead of a "This is where LDAP matches the standard stuff, and this is where it is slightly different" and a "This is how you login using LDAP" instead of a "This is how you login, be aware that if you use oAuth the endpoint response will be slightly different"

> The new API ends up kinda of ugly with the whole /auth/:driver/:provider/login format. I kept the /auth/login endpoint for backwards compatibility.

Yeah I agree. Was just wondering if it would make sense to consider the "standard" auth its own scoped flow, or if that should be just the default way, and have the others as scoped additions. In terms of actual usage in the wild, I think it's safe to assume that local auth will be used most of the time, with oauth/ldap integration added on for more integrated usage 👍🏻

**Comment by benhaynes** [comment]
Clearly, I'm out of my depth on this, but would it be possible to have all these current/complex auth methods be **non-modular**, and included in the core codebase... but still offer an "escape hatch" with a modular auth provider extension that gives some possibility for customization?

There has been a lot of requests for custom auth flows, and just wondering how we can avoid locking this (completely) to the core codebase. Just thinking out loud...

**Comment by aidenfoxx** [comment]
I personally still stand by the modular approach. I believe it would have been flexible enough for 80% of use cases, with the remaining 20% fixable with extensions or changes to the interface:

> oauth uses custom endpoints with a session for it's flow

Auth drivers can register their own endpoints on construct. The LDAP provider registers a similar listener on initialization, for example

> hooks would have different payloads (and potentially different/extra hooks altogether) per auth provider

The interface can support data more than just an identifier/secret combo

> some auth providers would have to have support for custom tokens/cookies that aren't directus' JWT

Not sure why this wouldn't be supported by the auth interface? 🤔 

> some auth providers might tap into sessions where others don't

We added an extra field in the database that can be used for auth sessions `auth_data`

> some auth providers might have to rely on custom endpoints/hooks to manipulate the user based on events happening in external services

Refer to the first point

Obviously this could be sunk cost fallacy speaking, but I don't see the problems that a fixed interface brings as being worse than the spaghetti code and duplication that comes from implementing individual auth providers tightly into the core. And if the interface isn't working in some way, then we make a V2, or a V3... or strip it out completely!

But that's just my take, and I trust Rijks opinion if he believes that's the way we should go.

File: api/src/controllers/auth.ts [hunk 10]
```diff
@@ -317,8 +342,20 @@ router.get(
 				// Do nothing
 			});
 
+			const database = getDatabase();
+			const user = await database.select('provider').from('directus_users').where('email', email).first();
+
+			if (!user) {
+				throw new InvalidCredentialsException('Email does not match existing user');
```
Comment (aidenfoxx) [inline api/src/controllers/auth.ts:349]: Don't need this section. AuthProvider will throw same exception

**Comment by rijkvanzanten** [comment]
(reminder: auth service authenticate method now takes "identifier" instead of "email")

File: api/src/services/users.ts (hunk 4 above)
Comment (aidenfoxx) [reply api/src/services/users.ts:339]: @rijkvanzanten This is the part that relates to #8163. We create a new instance of `UserService` to avoid any accountability protections that would prevent an unauthorized users updating the user record.

TODO: I should probably add a code comment explaining that.

File: api/src/services/authentication.ts [hunk 11]
```diff
@@ -184,11 +195,10 @@ export class AuthenticationService {
 		 * Sign token with combination of server secret + user password hash
 		 * That way, old tokens are immediately invalidated whenever the user changes their password
 		 */
-		const accessToken = jwt.sign(payload, env.SECRET as string, {
+		const accessToken = jwt.sign({ id: user.id }, env.SECRET as string, {
```
Comment (aidenfoxx) [inline api/src/services/authentication.ts:198]: Regression of new hook payload.

**Comment by aidenfoxx** [comment]
I've re-re-reviewed the code, made some minor quality tweaks and fixed 1 regression. Tested all the flows I believe I touched and things seem to still be working as expected.

File: api/src/services/graphql.ts [hunk 12]
```diff
@@ -1739,10 +1740,11 @@ export class GraphQLService {
 				args: {
 					email: GraphQLNonNull(GraphQLString),
 					password: GraphQLNonNull(GraphQLString),
+					provider: GraphQLString,
 					mode: AuthMode,
 					otp: GraphQLString,
 				},
-				resolve: async (_, args, { req, res }) => {
+				resolve: async (_, { ...args }, { req, res }) => {
```
Comment (aidenfoxx) [inline api/src/services/graphql.ts:1747]:
```suggestion
				resolve: async (_, args, { req, res }) => {
```

File: api/src/exceptions/invalid-config.ts [hunk 13]
```diff
@@ -0,0 +1,7 @@
+import { BaseException } from '@directus/shared/exceptions';
+
+export class InvalidConfigException extends BaseException {
+	constructor(message = 'Invalid config', provider?: string) {
```
Comment (rijkvanzanten) [inline api/src/exceptions/invalid-config.ts:4]: Lets not lock this to a "provider" string flag, but instead just pass on the a full object of extensions (seeng "Invalid Config" could be used for anything)

File: api/src/exceptions/invalid-config.ts [hunk 14]
```diff
@@ -0,0 +1,7 @@
...
+		super(message, 500, 'INVALID_CONFIG', { provider });
```
Comment (rijkvanzanten) [inline api/src/exceptions/invalid-config.ts:5]: We should use 503 instead of 500

File: api/src/types/auth.ts [hunk 15]
```diff
@@ -0,0 +1,22 @@
+export interface User {
```
Comment (rijkvanzanten) [inline api/src/types/auth.ts:1]: This should probably be under `@directus/shared` in a user.ts file rather than auth

File: api/src/controllers/auth.ts [hunk 16]
```diff
@@ -213,6 +220,22 @@ router.post(
...
+	'/',
+	asyncHandler(async (req, res, next) => {
+		const providers = toArray(env.AUTH_PROVIDERS);
+		const providerData = providers
+			.filter((provider) => provider && env[`AUTH_${provider.toUpperCase()}_DRIVER`])
+			.map((provider) => ({
+				name: provider,
+				driver: env[`AUTH_${provider.toUpperCase()}_DRIVER`],
+			}));
+		res.locals.payload = { data: env.AUTH_PROVIDERS ? providerData : null };
```
Comment (rijkvanzanten) [inline api/src/controllers/auth.ts:233]: We should include whether or not the default auth is enabled

File: api/src/auth/providers/local.ts [hunk 17]
```diff
@@ -0,0 +1,33 @@
...
+export default class LocalAuth extends Auth {
+	/**
+	 * Get user id by email
+	 */
+	async userID(identifier: string): Promise<string> {
+		const user = await this.knex
+			.select('id')
+			.from('directus_users')
+			.whereRaw('LOWER(??) = ?', ['email', identifier.toLowerCase()])
+			.orWhereRaw('LOWER(??) = ?', ['alternate_identifier', identifier.toLowerCase()])
```
Comment (rijkvanzanten) [inline api/src/auth/providers/local.ts:15]: Lets keep local auth email only for the time being

File: api/src/auth.ts [hunk 18]
```diff
@@ -0,0 +1,75 @@
...
+};
+
+const getAuthDriver = (driver: string): AuthConstructor | undefined => {
+	switch (driver) {
+		case 'local':
+			return LocalAuth;
+	}
+};
+
+const auth = new AuthManager(getDatabase(), getAuthConfig());
```
Comment (rijkvanzanten) [inline api/src/auth.ts:71]: Lets try getting rid of an authmanager class in favor of a single exported "getAuthProvider" function that we can use (the same as getDatabase and getCache). That way, we can more safely control the single-instance nature of "auth manager" (seeing it's illegal to have more than 1 instance of this class, with the stateful nature of ldap in mind)

File: api/src/controllers/auth.ts [hunk 19]
```diff
@@ -17,63 +22,65 @@ import logger from '../logger';
 const router = Router();
 
 const loginSchema = Joi.object({
-	email: Joi.string().email().required(),
+	email: Joi.string().required(),
 	password: Joi.string().required(),
 	mode: Joi.string().valid('cookie', 'json'),
 	otp: Joi.string(),
 }).unknown();
```
Comment (rijkvanzanten) [inline api/src/controllers/auth.ts:29]: Any ideas on where / how to store these provider-specific body definitions properly?

**Comment by rijkvanzanten** [comment]
Just so we're on the same page, does the following sound right?:

We're aiming for the following configuration style:

```
AUTH_PROVIDERS // List of configured auth providers
AUTH_<PROVIDER>_DRIVER // what auth driver to use*
```

For example:

```
AUTH_PROVIDERS="github"
AUTH_GITHUB_DRIVER="oauth2"
AUTH_GITHUB_KEY="abc" // oauth2 specific 
AUTH_GITHUB_SECRET="def" // oauth2 specific
```

Every auth provider will have a (slightly) different login payload. For example: "local" will use [id-field]/password, "ldap" will use userCN/password, oauth2 will use a redirect, etc. Therefore, each driver gets a "custom" (eg driver-based) login endpoint w/ payload under `/auth/login/:provider`.

After login is complete, the refresh and logout endpoints are the same for every endpoint. This is because refreshing / logging out is handled in Directus itself, and isn't a different flow for the end user. This means that we'll effectively have:

```
/auth                   // retrieve configured auth providers
/auth/login             // login using the default (hardcoded) "local" auth
/auth/login/:provider   // Login using the configured auth provider
/auth/refresh           // Refresh the current auth session
/auth/logout            // Stop the current auth session
```

The `/auth/login` endpoint without a given provider will use the hardcoded default auth provider. This is the regular email/password flow we currently have. This is effectively the "default" provider, and is accessed in `/auth/login`. It would be nice to be able to completely disable this auth flow with a dedicated `AUTH_DISABLE_DEFAULT` (name tbd) flag, though that's not in scope for this particular change.

\* For starters, this will be one of `local`, `oauth2`. We'll design this with support for `ldap`, `saml`, and `cas` in mind

**Comment by rijkvanzanten** [comment]
@aidenfoxx Give me some time to write a PR on top of your PR here, then you can review my changes, and we're done 💪🏻

File: api/src/database/migrations/20210903A-add-auth-provider.ts [hunk 20]
```diff
@@ -0,0 +1,21 @@
+import { Knex } from 'knex';
+
+export async function up(knex: Knex): Promise<void> {
+	await knex.schema.alterTable('directus_users', (table) => {
+		table.string('provider', 128).notNullable().defaultTo('default');
+		table.string('alternate_identifier', 512).unique();
```
[the remark this answers is not in the document]
Comment (aidenfoxx) [reply api/src/database/migrations/20210903A-add-auth-provider.ts:6]: I'd have said email is the identifier at present, at least for auth. I chose `alternate_identifier` because we wanted support usernames for local, but since that's changed we can use `external_identifier`.

File: api/src/types/auth.ts (hunk 15 above)
Comment (aidenfoxx) [reply api/src/types/auth.ts:1]: I would disagree, for the moment. It's only used internally, so there is never a need for it outside of the core

File: api/src/controllers/auth.ts (hunk 16 above)
Comment (aidenfoxx) [reply api/src/controllers/auth.ts:233]: Not sure I understand? We need default enabled to continue to support the existing oauth flow. After we move to the new oauth, however, we can disable default

Comment (rijkvanzanten) [reply api/src/controllers/auth.ts]: This must've made sense to me at some point..

File: api/src/database/system-data/fields/users.yaml [hunk 21]
```diff
@@ -150,3 +150,17 @@ fields:
     display: datetime
     display_options:
       relative: true
+
+  - field: provider
```
Comment (rijkvanzanten) [inline api/src/database/system-data/fields/users.yaml:154]: We should make these readonly by default at all times. The local driver is the default, and the other providers will be set during signup through the external provider

File: api/src/services/authentication.ts [hunk 22]
```diff
@@ -131,16 +142,12 @@ export class AuthenticationService {
...
-			if (!user.password) {
-				emitStatus('fail');
-				await stall(STALL_TIME, timeStart);
-				throw new InvalidCredentialsException();
-			}
-
-			if ((await argon2.verify(user.password, password)) === false) {
+			try {
+				await provider.verify({ ...user }, password);
+			} catch (e) {
```
Comment (rijkvanzanten) [inline api/src/services/authentication.ts:147]: This is the only bit I'm not sure about yet. The password check is pretty proprietary to one or to drivers.

To me, it looks like this _authenticate_ method has 3 "parts", 2 of which are shared between all drivers:

1) Before-login attempt. Tracks a rate limiter point, and checks if the user record exists and is active
2) Proprietary check from the driver. In the case of the local driver, it verifies the password
3) Start the session, and return the tokens

I'm wondering if we should split up this authenticate method into 2 methods: `validateLoginAttempt` and `login`.  These would map to no 1 and 3 respectively. That would mean that it's up to the driver implementation to decide whether any other validation is required, like checking a hash string for password validity 🤔

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
I'm super happy with this @aidenfoxx! I think we managed to find just the right balance between flexibility in the drivers vs maintainability in the codebase (finally lol).

Seeing this is not a breaking change, I'm down to merge this as-is. That being said, I'd love to hear your thoughts on the "authenticate" method of the "AuthService" to see if we can clean that up just a tad more.

I'll move all the changes from the app into a new PR, as I'd like to spend some more time with @benhaynes on that to figure out exactly how we want to tackle multiple login forms and different routes etc 👍🏻

File: api/src/auth/auth.ts [hunk 23]
```diff
@@ -44,7 +44,7 @@ export default abstract class Auth {
 	 * @param user User information
 	 * @throws InvalidCredentialsException
 	 */
-	refresh(_user: User): void {
+	async refresh(_user: User): Promise<void> {
```
Comment (aidenfoxx) [inline api/src/auth/auth.ts]: I prefer not enforcing async. If the inheriting class doesn't need the method to be to be async it shouldn't have to define it. Mostly for understandably. If I saw a function implementing async without using an await, I would assume someone forgot their await.

File: api/src/services/authentication.ts (hunk 22 above)
Comment (aidenfoxx) [reply api/src/services/authentication.ts:147]: Hm... I really couldn't say. I think we'll learn pretty quickly once we start adding new auth flows how the authenticate function could be improved, but right now it's hard for me to visualize the different scenarios.

I can, however, see the value in adding a `validateLoginAttempt` function to the auth intereface to compliment the `validate` function, since validating a password and validating a login aren't always the same thing.

File: api/src/auth/drivers/local.ts [hunk 24]
```diff
@@ -0,0 +1,108 @@
...
+import { AuthDriver } from '../auth';
+import { User } from '../../types';
+import { InvalidCredentialsException, InvalidPayloadException } from '../../exceptions';
+import { AuthenticationService } from '../../services';
+import { Router } from 'express';
+import Joi from 'joi';
+import asyncHandler from '../../utils/async-handler';
+import env from '../../env';
+import ms from 'ms';
+import { Knex } from 'knex';
```
Comment (aidenfoxx) [inline api/src/auth/drivers/local.ts:11]:
```suggestion
```

File: api/src/controllers/auth.ts [hunk 25]
```diff
@@ -24,23 +24,21 @@ const router = Router();
 
 const authProviders = getAuthProviders();
 
-if (authProviders) {
-	for (const authProvider of authProviders) {
-		let authProviderRouter: Router | null = null;
+authProviders.forEach((authProvider) => {
```
Comment (rijkvanzanten) [inline api/src/controllers/auth.ts:27]: We rely on `for...of` all over the place in this codebase, so let's keep that consistent .

(the main reason is that it makes it easy to switch between async and non-async functions inside the loop. You can't "await" in a forEach callback, but you can in a for...of invocation)

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@aidenfoxx Your turn for the final ✅ ☺️

File: api/src/controllers/auth.ts (hunk 25 above)
Comment (aidenfoxx) [reply api/src/controllers/auth.ts]: Boo! I hate that attitude. I think you should use whatever tool is best for the job, and I see  `forEach` as the more utilitarian function with `for` being reserved for special cases. But it's no biggie, and I'll keep it in mind.

File: api/src/auth/auth.ts [hunk 26]
```diff
@@ -11,13 +11,13 @@ export abstract class AuthDriver {
...
-	 * Get user id by unique identifier
+	 * Get user id for a given provider payload
 	 *
-	 * @param identifier Unique user identifier
+	 * @param payload Any data that the user might've provided
 	 * @throws InvalidCredentialsException
 	 * @return User id of the identifier
 	 */
-	abstract userID(identifier: string): Promise<string>;
+	abstract getUserID(identifier: string | number, payload: Record<string, any>): Promise<string>;
```
Comment (aidenfoxx) [inline api/src/auth/auth.ts:20]: Why not kill `identifier` and only have `payload`?

Comment (rijkvanzanten) [reply api/src/auth/auth.ts:20]: Figured `identifier` is a known standard in that part of the auth flow, while the payload could be any user provided thing, that makes identifier slightly more reliable

File: api/src/auth/auth.ts [hunk 27]
```diff
@@ -29,54 +29,36 @@ export abstract class AuthDriver {
...
 	/**
-	 * Handle user session termination
+	 * Handle user session refresh
 	 *
 	 * @param user User information
 	 * @param session Session data
 	 * @throws InvalidCredentialsException
 	 */
-	logout(_user: User, _session: Session): void {
+	async refresh(_user: User, _session: Session): Promise<void> {
```
Comment (aidenfoxx) [inline api/src/auth/auth.ts:50]: We no longer need the full `Session` object. Just the `data` from the session field.

File: api/src/auth/auth.ts [hunk 28]
```diff
@@ -29,54 +29,36 @@ export abstract class AuthDriver {
...
 	 *
-	 * @param user User information
-	 * @param session Session data
+	 * @param _user User information
+	 * @param _payload Any data that the user might've provided
 	 * @throws InvalidCredentialsException
 	 */
-	refresh(_user: User, _session: Session): void {
-		/* Optional */
+	async login(_user: User, _payload: Record<string, any>): Promise<Record<string, any> | null> {
```
Comment (aidenfoxx) [inline api/src/auth/auth.ts:38]: It would be nice to make `Record<string, any> | null` it's own type `SessionData`.

File: api/src/auth/auth.ts (hunk 26 above)
Comment (aidenfoxx) [reply api/src/auth/auth.ts:20]: Hm... I dunno. I kinda like the idea of going full payload. Currently I use the `code` from the oauth response as the identifier, but it's kinda a misnomer

Comment (rijkvanzanten) [reply api/src/auth/auth.ts:20]: Works for me!

File: api/src/controllers/auth.ts [hunk 29]
```diff
@@ -317,8 +293,11 @@ router.get(
 				// Do nothing
 			});
 
+			// The default auth provider should allow auth by email. If that ever
+			// changes, this will need to be addressed
 			authResponse = await authenticationService.authenticate({
```
Comment (aidenfoxx) [inline api/src/controllers/auth.ts:298]:
```suggestion
			authResponse = await authenticationService.login({
```

File: api/src/auth/drivers/local.ts [hunk 30]
```diff
@@ -0,0 +1,111 @@
...
+	 * Verify user password
+	 */
+	async verify(user: User, password?: string): Promise<void> {
+		if (!user.password || !(await argon2.verify(user.password, password as string))) {
+			throw new InvalidCredentialsException();
+		}
+	}
+
+	async login(user: User, payload: Record<string, any>): Promise<null> {
+		await this.verify(user, payload.password);
```
Comment (aidenfoxx) [inline api/src/auth/drivers/local.ts:45]:
```suggestion
		if (payload.password) {
			await this.verify(user, payload.password);
		}
```

File: api/src/services/authentication.ts [hunk 31]
```diff
@@ -130,18 +130,14 @@ export class AuthenticationService {
...
-			}
+		let sessionData: SessionData = null;
 
-			if ((await argon2.verify(user.password, password)) === false) {
-				emitStatus('fail');
-				await stall(STALL_TIME, timeStart);
-				throw new InvalidCredentialsException();
-			}
+		try {
+			sessionData = await provider.login(user, cloneDeep(payload));
```
Comment (aidenfoxx) [inline api/src/services/authentication.ts:136]:
```suggestion
			sessionData = await provider.login(clone(user), cloneDeep(payload));
```

File: api/src/auth/drivers/local.ts [hunk 32]
```diff
@@ -72,12 +74,15 @@ export function createLocalAuthRouter(): Router {
...
+
+			if (error) {
+				throw new InvalidPayloadException(error.message);
+			}
 
 			const mode = req.body.mode || 'json';
 
 			const { accessToken, refreshToken, expires } = await authenticationService.login(
-				'local',
+				undefined, // Will default to DEFAULT_AUTH_PROVIDER
```
Comment (rijkvanzanten) [inline api/src/auth/drivers/local.ts:85]: Instead of defaulting to the default auth driver, this should be passing in the provider name of the current provider. That's currently not accessible in this createLocalAuthRouter() function. We should add a `providerName` parameter to the create-routes function in order for us to be able to pass it along to the authenticationsService

Comment (aidenfoxx) [reply api/src/auth/drivers/local.ts:85]: Do we really have to? I assumed you hardcoded 'local' for a reason (to limit the login until the new frontend had been finalized). Previously it would use `req.params.provider` which worked fine since if it was undefined it would default to `DEFAULT_AUTH_PROVIDER`.

Either way, it had to be changed from 'local' since that isn't the default provider, which broke the login flow.

File: api/src/services/graphql.ts [hunk 33]
```diff
@@ -1752,11 +1754,7 @@ export class GraphQLService {
 						accountability: accountability,
 						schema: this.schema,
 					});
-					const result = await authenticationService.authenticate({
-						...args,
-						ip: req?.ip,
-						userAgent: req?.get('user-agent'),
-					});
+					const result = await authenticationService.login('local', args, args?.otp);
```
Comment (aidenfoxx) [inline api/src/services/graphql.ts:1757]:
```suggestion
					const result = await authenticationService.login(provider, args, args?.otp);
```

File: api/src/services/graphql.ts [hunk 34]
```diff
@@ -1739,6 +1740,7 @@ export class GraphQLService {
 				args: {
 					email: GraphQLNonNull(GraphQLString),
 					password: GraphQLNonNull(GraphQLString),
+					provider: GraphQLString,
```
Comment (aidenfoxx) [inline api/src/services/graphql.ts:1743]:
```suggestion
```

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Removed the notice label, as this PR doesn't include any breaking changes
