### PR TITLE
Cache bust image when generating previews

### LINKED ISSUE #22556: Cloudinary Storage: Old image returned after replacing/editing
### Describe the Bug

With Cloudinary storage, the old image is still displayed after replacing or editing an image via the File Library.

As pointed out by @joselcvarela in https://github.com/directus/directus/pull/22551#issuecomment-2127691145, this comes from the fact that the files aren't invalidated.

### To Reproduce

- Setup Cloudinary Storage [^1]
- Upload an image to the File Library
- Replace/Edit that image

https://github.com/directus/directus/assets/5363448/9040096b-855e-4549-b77f-f9d7cfcb0601

(After editing, the image isn't loading anymore inside the image editor, not sure if that is a consequence of the issue)

[^1]: https://docs.directus.io/self-hosted/config-options.html#cloudinary-cloudinary

### Directus Version

10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

N/A

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

Allow for cachebusting when reading images from cloudinary to use the latest image for preview generation.

## Potential Risks / Drawbacks

None

## Review Notes / Questions
None
---

Fixes #22556

### CODE REVIEW

File: api/src/services/assets.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export class AssetsService {
 				});
 			}
 
-			const readStream = await storage.location(file.storage).read(file.filename_disk, range);
+			const readStream = await storage.location(file.storage).read(file.filename_disk, { range, bustCache: true });
```
Comment (rijkvanzanten) [inline api/src/services/assets.ts:171]: It feels a little tricky to pass `bustCache` here, as we know that most drivers ignore it 🤔 Seeing this is only required for Cloudinary, maybe we add it in just there?

Comment (rijkvanzanten) [reply api/src/services/assets.ts:171]: Alternatively, maybe we can pass the `last_updated` field value from `directus_files` as an optional parameter and use that as a cache buster just in cloudinary? 🤔

File: packages/storage-driver-cloudinary/src/index.ts [hunk 2]
```diff
@@ -79,6 +79,10 @@ export class DriverCloudinary implements Driver {
 		return String(new Date().getTime());
 	}
 
+	private getLatestVersion() {
+		return `v${this.getTimestamp()}`;
```
Comment (rijkvanzanten) [inline packages/storage-driver-cloudinary/src/index.ts:83]: Would be nice if this is a known last updated timestamp rather than _now_ to make it a bit more efficient)

File: packages/storage-driver-cloudinary/src/index.ts [hunk 3]
```diff
@@ -119,10 +123,12 @@ export class DriverCloudinary implements Driver {
...
 	}
 
-	async read(filepath: string, range?: Range) {
+	async read(filepath: string, options?: ReadOptions) {
+		const { range, bustCache } = options ?? {};
+
 		const resourceType = this.getResourceType(filepath);
 		const fullPath = this.fullPath(filepath);
-		const signature = this.getParameterSignature(fullPath);
+		const signature = bustCache === true ? this.getLatestVersion() : this.getParameterSignature(fullPath);
```
Comment (rijkvanzanten) [inline packages/storage-driver-cloudinary/src/index.ts:131]: How often do we read without busting the cache here? While less efficient, it might be an option to always cache bust in cloudinary as it's unreliable otherwise, and leave the other drivers as is

**Review by rijkvanzanten — DISMISSED** [review]

**Comment by rijkvanzanten** [comment]
@paescuj I'd like to get to a point where Directus doesn't modify the filename on disk at all, but instead retains the original filename from the upload. That'll require way more refactoring of course, but I'd rather not introduce any new work now that limits us more in getting that to work later 🙂

**Comment by paescuj** [comment]
> @paescuj I'd like to get to a point where Directus doesn't modify the filename on disk at all, but instead retains the original filename from the upload. That'll require way more refactoring of course, but I'd rather not introduce any new work now that limits us more in getting that to work later 🙂

Not sure if I understand correctly, but wouldn't that technically be the same as the suggested idea, but using the original filename instead of a random UUID?

Btw. if we replace a JPEG file with a PNG, the filename on disk should be updated anyway (e.g. `0191eac7-6f03-7a0a-9f9e-7b5370ecb887.jpg → 0191eac7-6f03-7a0a-9f9e-7b5370ecb887.png`). As far as I know, certain storage backends require the correct file extension.

**Comment by rijkvanzanten** [comment]
> Not sure if I understand correctly, but wouldn't that technically be the same as the suggested idea, but using the original filename instead of a random UUID?

Yeah but if you replace the file with a file of the same name, we'd still have an issue 🤔 Alternatively, we could prefix / suffix the filename with unique identifier, kinda like how many URLs work nowadays: `/<mini-id>-<original-filename>.<ext>`

**Comment by Nitwel** [comment]
Sorry, forgot to add a detailed explanation on why I went with this approach which should have reduced confusion. Let me try to answer most questions:

1. Always busting Cloudinary cache: I don't think that's a good approach as now any image request to Cloudinary would skip the CDN increasing latency for all requests and also disabling a feature most people would expect be enabled out of the box.
2. Using `last_updated`: Because that timestamp is created when updating the table row, technically it should be before the new version is available to Cloudinary. Cloudinary responds with the proper timestamp after uploading the updated image but we have no way of storing that anywhere from within the storage-driver. When relying on `last_updated`, there is no guarantee that Cloudinary will respond with the updated image.
3. Using mini-ids on filenames: This is another solution I would be fond of, this way we implement our own versioning for files which makes Cache invalidation independent of the file host. Though I'm not sure if the effort is worth it just for this Cloudinary issue.
4. Using `invalidate` param: For clarification in case this option comes up in the future, we can't rely on the `invalidate` param as it takes multiple seconds to actually invalidate the cache and by that, thumbnails are often generated again using the outdated version of the file.

In general, the Cloudinary api is a headache to work with as sometimes things work like they are documented, and other times not at all which made debugging this a nightmare. 😅 

I tried to find the most reasonable solution, taking into account that this issue is only in Cloudinary, I was hesitant too to change the params for read in all other drivers, but right now I think it is the best solution other than adding a mini-id to files, which would increase complexity by a bit.

File: .changeset/cold-cheetahs-double.md [hunk 4]
```diff
@@ -0,0 +1,12 @@
+---
+'@directus/storage-driver-cloudinary': patch
```
Comment (br41nslug) [inline .changeset/cold-cheetahs-double.md:2]: Just a note: I was thinking this could be a breaking change due to the read function signature changing but i dont think we've ever exposed these drivers to extensions/devs

File: packages/storage-driver-cloudinary/src/index.ts [hunk 5]
```diff
@@ -119,10 +119,12 @@ export class DriverCloudinary implements Driver {
...
 	}
 
-	async read(filepath: string, range?: Range) {
+	async read(filepath: string, options?: ReadOptions) {
+		const { range, version } = options ?? {};
+
 		const resourceType = this.getResourceType(filepath);
 		const fullPath = this.fullPath(filepath);
-		const signature = this.getParameterSignature(fullPath);
+		const signature = version !== undefined ? `v${version}` : this.getParameterSignature(fullPath);
```
Comment (br41nslug) [inline packages/storage-driver-cloudinary/src/index.ts:127]: Should we add a comment here about the "version" being used to bust the cache? Potentially linking back to https://cloudinary.com/documentation/advanced_url_delivery_options#asset_versions

**Review by br41nslug — APPROVED** [review]
I like this versioned approach but it wasnt directly clear to me that that was actually doing the cache busting until going through the cloudinary docs 🤔

**Comment by Nitwel** [comment]
Before, I named it `bustCache` but I had a chat with Rijk and we settled on `version` for that. But I could add a comment to clarify that we use it here for cache busting. 👍
