### PR TITLE
Fix processing dates on aggregation

### LINKED ISSUE #25060: Timezone issue with aggregate[max] in Directus API
### Describe the Bug

Hi everyone, I’ve run into a timezone inconsistency with aggregate[max] in Directus.

Evironement :
- lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy

- timedatectl
Local time: Thu 2025-04-10 19:47:33 CEST
Universal time: Thu 2025-04-10 17:47:33 UTC
RTC time: Thu 2025-04-10 17:47:33
Time zone: Europe/Paris (CEST, +0200)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no

- database : mysql --version
mysql  Ver 8.0.41-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
global_time_zone +00:00
session_time_zone +00:00

Issue description
- I'm storing timestamps in UTC (TIMESTAMP(6) in MySQL)
- My MySQL server is explicitly set to +00:00 (confirmed with @@session.time_zone)
- When querying a specific record via /items/collection?filter[Id][_eq]=..., the timestamp is returned correctly in UTC (e.g., 2025-04-06T16:37:14.129Z)
- However, when using an aggregate query like /items/collection?aggregate[max]=timestamp&groupBy[]=location_id, the same provider_updateTime value shows as 2025-04-06T14:37:14.129Z — exactly 2 hours earlier
This looks like Directus applies a timezone conversion during the aggregate response, even though the value is already UTC.

Has anyone experienced this issue or found a workaround? Is this a known bug with how aggregate queries handle timezones?

How to Fix ?

I'v added a Environment="TZ=UTC" in my service and all datetimes ar now the same (directly and with agregate)

Thanks!

### To Reproduce

Set GMT+2 TimeZone on the Server
Run directus as a service

sudo nano /etc/systemd/system/directus.service
`[Unit]
Description=Directus API
After=network.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/visiexpert/visiexpert-directus
Environment=PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/home/ubuntu/.nvm/versions/node/v22.14.0/bin/npx directus start
Restart=always

[Install]
WantedBy=default.target`

Start the service
`sudo systemctl start directus`

Set up a collection with timestamp field - timestam(6) in my case

Request a collection item via GET 
`http://localhost:8055/items/providers_reviews?filter[provider_reviewId][_eq]=AbFvOqk1qmPf-rLNi_k6qbwU6zth1aeuYP6n_GbVO7knxf5p6elRFOH0P6-_Eopdm3id64F6wchB`

See my result as exemple
`{
  "data": [
    {
      "provider_updateTime": "2025-04-06T16:37:14.129Z"
    }
  ]
}`

Request a collection item via GET with a agregate max
`http://localhost:8055/items/visiexpert_providers_reviews?aggregate[max]=provider_updateTime&groupBy[]=location_id&fields[]=location_id&fields[]=location.provider_location_id&deep[location][_fields][]=provider_location_id`
See the +2 hour on timestamp data
`{
  "data": [
    {
      "location_id": 597,
      "max": {
        "provider_updateTime": "2025-04-06T18:37:14.129Z"
      }
    }
  ]
}`

### Directus Version

v11.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql  Ver 8.0.41

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- Now processing dates also on aggregation

## Potential Risks / Drawbacks

none

## Review Notes / Questions

- while the original issue does not mention this, this also fixes this bug #22804 for aggregation

---

Fixes #25060

### CODE REVIEW

File: api/src/database/run-ast/run-ast.ts [hunk 1]
```diff
@@ -89,7 +89,18 @@ export async function runAst(
 
 		// Run the items through the special transforms
 		const payloadService = new PayloadService(collection, { knex, schema });
-		let items: null | Item | Item[] = await payloadService.processValues('read', rawItems, query.alias ?? {});
+
+		// Include aggegation e.g. "count->id" in alias map
+		const aggregateMapped = Object.fromEntries(
```
Comment (ComfortablyCoding) [inline api/src/database/run-ast/run-ast.ts:94]: As discussed it may be worthwhile to pass down the aggregates to `processValues` and process the information there accordingly (e.g. in `processDates`). This will ensure all "processValues` has all our processing logic.

P.S. We can also update the `processAggregates` to utilize this new property to ensure no conflicts with any alias names that contain `->`

Comment (Nitwel) [reply api/src/database/run-ast/run-ast.ts]: Did a clean up, let me know if you have more suggestions!

**Review by ComfortablyCoding — COMMENTED** [review]
#### Tests
- [x] `date`,`datetime` & `timestamp` fields are properly converted
- [x] aggregate data is properly expanded from `->` syntax to object

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
