### PR TITLE
Fix app permissions presets with nested dynamic variables

### LINKED ISSUE #14315: Permission Field Preset for M2O field with Dynamic Variable
### Describe the Bug

I'm not able to use *Dynamic Variable* as a default M2O field value with *Custom Role > Collection > Read > Field Preset*

Related Issue: #13806 and PR: #13830 (not resolved for M2O field types)

### To Reproduce

1. Create new Data Model: *Organisations*
1. Create new Data Model: *News* with field *organisation*, Many to One Relationship, Related Collection: Organisations
1. Create new field for `directus_users`: *organisation*, Many to One Relationship, Related Collection: Organisations
1. Create new Role: Manager with App Access: Enabled, Admin Access: Disabled
1. Set *Create* Permissions for News to *Use Custom*
1. Set Field Presets to
   ```json
   {
       "organisation": "$CURRENT_USER.organisation"
   }
   ```
1. Create new User with *Manger* role and log in
1. Go to Content > News > Create Item
1. The Organisation field is not filled in with value of `$CURRENT_USER.organisation`

### Errors Shown

none

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #14315

Currently when the app parses presets in permissions, the `$CURRENT_ROLE` and `$CURRENT_USER` dynamic variables are constructed based on the `currentUser` in the user store:

https://github.com/directus/directus/blob/62b4a2413ca310b1bad23c64fe37e8feac710c1e/app/src/utils/parse-preset.ts#L6-L20

However when `currentUser` is populated, it is based on predefined fields:

https://github.com/directus/directus/blob/62b4a2413ca310b1bad23c64fe37e8feac710c1e/app/src/stores/user.ts#L37-L51

so the app parsing of dynamic variables in presets will not be able to find nested dynamic variables such as `$CURRENT_USER.custom_user_field` as `custom_user_field` was never fetched.

The API does not have this issue as it dynamically fetches the nested dynamic variables with Users and Roles services' `readOne` as seen here:

https://github.com/directus/directus/blob/62b4a2413ca310b1bad23c64fe37e8feac710c1e/api/src/utils/get-permissions.ts#L167-L186

### Before

https://user-images.githubusercontent.com/42867097/203940600-71a2b6a8-689a-4721-b1f0-a41b041531c0.mp4

### After

https://user-images.githubusercontent.com/42867097/203940221-3fd9bdcc-6e59-4fb9-b335-e74ef40100de.mp4

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

File: app/src/stores/permissions.ts [hunk 1]
```diff
@@ -33,6 +40,25 @@ export const usePermissionsStore = defineStore({
...
+				for (const rawPermissions of rawPermissionsWithPresets) {
+					deepMap(rawPermissions.presets, (value) => {
+						if (typeof value !== 'string') return;
+
+						if (value.startsWith('$CURRENT_USER.')) {
+							fields.push(value.replace('$CURRENT_USER.', ''));
+						} else if (value.startsWith('$CURRENT_ROLE.')) {
+							fields.push(value.replace('$CURRENT_ROLE.', 'role.'));
+						}
+					});
```
Comment (azrikahar) [inline app/src/stores/permissions.ts:57]: general logic referred from the API side here:

https://github.com/directus/directus/blob/62b4a2413ca310b1bad23c64fe37e8feac710c1e/api/src/utils/get-permissions.ts#L143-L159

**Review by licitdev — APPROVED** [review]
LGTM. The merging into `currentUser` is clean and neat. 👍 
This reminded me of https://github.com/directus/directus/pull/9572 which adds a separate cache to store the filter context.

**Review by br41nslug — APPROVED** [review]
LGTM
