### PR TITLE
Gaetan/cms 1115 schema cache timing issue with auth hooks during container

### LINKED ISSUE #25500: Schema Cache Timing Issue with Auth Hooks During Container Startup
## Summary

Auth providers in Directus are instantiated with a static schema snapshot during server startup, causing authentication hooks that modify user payloads to fail when custom fields are added to the schema after auth provider registration. This creates a timing issue where schema changes are not reflected in the `UsersService` instances used by auth drivers.

## Environment

- **Directus Version**: 11.9.3
- **Setup**: Docker container with custom schema applied via schema-sync extension
- **Auth Provider**: OpenID/OAuth2

## Problem Description

During container startup, the following sequence occurs:

1. **Auth providers are registered** with static schema: [`registerAuthProviders()`](https://github.com/directus/directus/blob/main/api/src/auth.ts#L35) calls `await getSchema()` once
2. **Schema-sync extension runs** during `app.before` hook and imports custom schema
3. **Auth requests execute** but auth drivers still use the original schema from step 1

This causes auth filter hooks (like `auth.create`) to fail when setting custom fields on the user payload, even when the schema is refreshed within the hook.

### Schema Registration Timing

In [`/api/src/auth.ts`](https://github.com/directus/directus/blob/main/api/src/auth.ts#L35):
```typescript
export async function registerAuthProviders(): Promise<void> {
  // ...
  const options = { knex: getDatabase(), schema: await getSchema() }; // ← Static schema snapshot
  // ...
}
```

### Auth Driver Construction

In auth drivers like [`/api/src/auth/drivers/openid.ts`](https://github.com/directus/directus/blob/main/api/src/auth/drivers/openid.ts#L62):
```typescript
constructor(options: AuthDriverOptions, config: Record<string, any>) {
  // ...
  this.usersService = new UsersService({ knex: this.knex, schema: this.schema }); // ← Uses static schema
  // ...
}
```

### UsersService Schema Binding

In [`/api/src/services/users.ts`](https://github.com/directus/directus/blob/main/api/src/services/users.ts):
```typescript
export class UsersService extends ItemsService {
  constructor(options: AbstractServiceOptions) {
    super('directus_users', options);
    this.schema = options.schema; // ← Schema bound at construction time
  }
}
```

## Impact

This issue prevents:
- **Dynamic user field association** during authentication
- **Custom field population** in auth hooks 
- **Schema extensions** that need to be available immediately after container startup
- **Proper integration** with schema management tools like directus-schema-sync

## Expected Behavior

Auth hooks should be able to set custom fields on user payloads when those fields exist in the current schema, regardless of when the schema was updated during the startup process.

## Current Workarounds

- Use action hooks (`users.create`) to update users after creation (breaks atomicity)
- Restart container after schema import (manual intervention required)
- Store temporary data in `auth_data` field (not ideal for relational data)

### Option 1: Lazy Schema Loading
```typescript
// In auth drivers, get fresh schema when needed
get currentSchema() {
  return getSchema({ bypassCache: true });
}
```

### Option 2: Schema Update Notification
```typescript
// Allow auth drivers to update their schema when schema changes
updateSchema(newSchema: SchemaOverview) {
  this.schema = newSchema;
  this.usersService = new UsersService({ knex: this.knex, schema: newSchema });
}
```

### Option 3: Defer Auth Provider Registration
Register auth providers after all `app.before` hooks have completed to ensure schema is fully loaded.

## Related Code References

- **Auth Provider Registration**: [`/api/src/auth.ts:35`](https://github.com/directus/directus/blob/main/api/src/auth.ts#L35)
- **OpenID Auth Driver**: [`/api/src/auth/drivers/openid.ts:62`](https://github.com/directus/directus/blob/main/api/src/auth/drivers/openid.ts#L62)
- **Schema Caching**: [`/api/src/utils/get-schema.ts`](https://github.com/directus/directus/blob/main/api/src/utils/get-schema.ts)
- **Users Service**: [`/api/src/services/users.ts`](https://github.com/directus/directus/blob/main/api/src/services/users.ts)

## Additional Context

This issue is particularly problematic for production deployments using infrastructure-as-code approaches where schema changes are applied automatically during container startup. The current architecture requires manual intervention or complex workarounds to achieve proper schema synchronization with auth providers.

## Reproduction Steps
1. Set up Directus with custom schema containing additional user fields
2. Create an auth filter hook (`auth.create`) that sets custom fields on the user payload
3. Start container from scratch (not restart)
4. Authenticate with external provider
5. Observe that custom fields are not set in the database, despite hook execution

### Directus Version

v11.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres:15-alpine

### PR DESCRIPTION
**Pull request by gaetansenn**
## Scope

What's changed:

- Auth drivers now fetch schema per request via `getSchema()` instead of caching at startup
- Removed `schema` from `AuthDriverOptions` interface - only `knex` is required
- Optimized to fetch schema once per auth operation and reuse for both hooks and services
- Added `getCurrentSchema()` protected method to `AuthDriver` base class
- Updated all auth drivers (OAuth2, OpenID, LDAP, SAML) to use the new pattern

## Potential Risks / Drawbacks

- Minimal performance overhead: additional `getSchema()` calls per auth request (mitigated by global schema cache)
- Auth drivers now have different lifecycle than initially designed (singleton instances with per-request schema)

## Tested Scenarios

- Tested with `schema-sync` extension that updates schema during `app.before` hook
- Auth hooks (`auth.create`, `auth.update`) can now successfully set custom user fields added after server startup
- GitHub OAuth configuration tested

## Review Notes / Questions

- **Performance:** `getSchema()` is globally cached - frozen object reference (~1ns) or cloneDeep (~1-5ms) depending on `CACHE_SCHEMA_FREEZE_ENABLED`
- **Architecture:** This aligns auth drivers with controller pattern (both fetch schema per request)

## Checklist

- [ ] Added or updated tests
- [ ] Documentation PR created [here](https://github.com/directus/docs) or not required

---

Fixes #25500

### CODE REVIEW

File: api/src/auth/auth.ts [hunk 1]
```diff
@@ -1,14 +1,25 @@
...
+	protected async getCurrentSchema(): Promise<SchemaOverview> {
+		return await getSchema();
+	}
+
+	protected async getUsersService(schema?: SchemaOverview): Promise<UsersService> {
+		return new UsersService({
+			knex: this.knex,
+			schema: schema ?? (await this.getCurrentSchema()),
+		});
 	}
```
Comment (br41nslug) [inline api/src/auth/auth.ts]: It feels a little bit like overkill to wrap the globally available `getSchema` function into a method of this class without extra logic 🤔 
```suggestion
	protected async getUsersService(schema?: SchemaOverview): Promise<UsersService> {
		return new UsersService({
			knex: this.knex,
			schema: schema ?? (await getSchema()),
		});
	}
```

File: api/src/auth/drivers/ldap.ts [hunk 2]
```diff
@@ -304,15 +301,18 @@ export class LDAPAuthDriver extends AuthDriver {
 				};
 			}
 
+			const schema = await this.getCurrentSchema();
```
Comment (br41nslug) [inline api/src/auth/drivers/ldap.ts]: Same for the other usages but wont make a comment for each one 😄 
```suggestion
			const schema = await getSchema();
```

File: api/src/auth/auth.ts (hunk 1 above)
Comment (gaetansenn) [reply api/src/auth/auth.ts]: Totally agree with you

File: api/src/auth/drivers/ldap.ts (hunk 2 above)
Comment (br41nslug) [reply api/src/auth/drivers/ldap.ts]: Dont forget to tackle the other usages of `this.getCurrentSchema();` in the PR 😉

Comment (gaetansenn) [reply api/src/auth/drivers/ldap.ts]: ah yeah right :)

File: api/src/auth/drivers/saml.ts [hunk 3]
```diff
@@ -88,15 +86,18 @@ export class SAMLAuthDriver extends LocalAuthDriver {
 
 		// Run hook so the end user has the chance to augment the
 		// user that is about to be created
+		const schema = await getSchema();
```
Comment (br41nslug) [inline api/src/auth/drivers/saml.ts]: A very tiny thing but lets make sure these comments stay with the line they refer to 😄 
```suggestion
		const schema = await getSchema();
		
		// Run hook so the end user has the chance to augment the
		// user that is about to be created
```

File: api/src/auth/drivers/openid.ts [hunk 4]
```diff
@@ -392,7 +396,9 @@ export class OpenIDAuthDriver extends LocalAuthDriver {
 
 				// Update user refreshToken if provided
 				if (tokenSet.refresh_token) {
-					await this.usersService.updateOne(user.id, {
+					const usersService = await this.getUsersService();
```
Comment (br41nslug) [inline api/src/auth/drivers/openid.ts]:
```suggestion
					const usersService = this.getUsersService(schema);
```

File: api/src/auth/auth.ts [hunk 5]
```diff
@@ -1,14 +1,21 @@
...
 	constructor(options: AuthDriverOptions, _config: Record<string, any>) {
 		this.knex = options.knex;
-		this.schema = options.schema;
+	}
+
+	protected async getUsersService(schema?: SchemaOverview): Promise<UsersService> {
+		return new UsersService({
+			knex: this.knex,
+			schema: schema ?? (await getSchema()),
+		});
```
Comment (br41nslug) [inline api/src/auth/auth.ts]: I dont think we need this function to be `async`, all usages (Except 1 that has schema available) get the schema passed in. This way we do not have to `await` this function everywhere for a fallback that isnt used 😄 
```suggestion
	protected getUsersService(schema: SchemaOverview): UsersService {
		return new UsersService({
			knex: this.knex,
			schema,
		});
```

**Review by br41nslug — COMMENTED** [review]
I've got some last tiny nitpicks but beyond that the code is looking good 🎉

File: api/src/auth/drivers/saml.ts (hunk 3 above)
Comment (gaetansenn) [reply api/src/auth/drivers/saml.ts]: Ah yeah you are right sorry for that mistake 😅

Comment (br41nslug) [reply api/src/auth/drivers/saml.ts]: Haha it's easy to miss 😃

File: api/src/auth/auth.ts (hunk 5 above)
Comment (gaetansenn) [reply api/src/auth/auth.ts]: Nice suggestion :)

File: api/src/auth/drivers/openid.ts (hunk 4 above)
Comment (br41nslug) [reply api/src/auth/drivers/openid.ts]: Ah i see the github collapsed view got me and `schema` wasnt already available. nice solve

**Review by br41nslug — APPROVED** [review]

**Comment by rvveber** [comment]
🚀
