### PR TITLE
Fix save enabled in drawer when no changes made

### LINKED ISSUE #20802: M2O/inline editing: Clicking Edit button then Save always assumes changes are being made
### Describe the Bug

I'm not actually clear if this is a bug or a component to make the feature work, but I think it should be considered a bug. We discovered it because the behavior triggers an update on the relevant item, which is a problem because the related item "update" was blocked by a filter flow blocking the main form.

The desired behavior is that if the modification only results in an update to the id it is not a modification as all, therefore the "save" should be ignored and treated as a cancel.

### To Reproduce

1. Load an item into an M2O field. Raw value for the field will be the id, eg 123
2. Click the Edit pop up button
3. Make no changes
4. Press Save instead of Cancel
5. The raw value changes to { "id" : 123 }
6. Save will attempt an update on the related item with no information to update, but still be restricted by any conditions of the update

### Directus Version

10.8.2

### Hosting Strategy

Directus Cloud

### PR DESCRIPTION
**Pull request by robluton**
## Scope

What's changed:

**Fix issue where save was enabled before any changes made**
- drawer-collection - local state for selection added
- drawer-item do not enable save button unless edits made

## Potential Risks / Drawbacks

- these components are important and should be tested thoroughly

## Review Notes / Questions
I tested by doing the following:
Created a new collection with both o2m and m2o fields.
Create existing items for both related collections.
From the main collection, open an existing m2o item
- Verified save was disabled
- Changed selection
- Verified save was enabled

From the main collection, opened an existing o2m item
- Verified save was disabled
- Modified a form field
- Verified save was enabled

---

Fixes #20802

## Summary by CodeRabbit

* **Bug Fixes**
  * The save button for many-to-one and one-to-many relationship drawer items is now disabled by default unless changes have been made, preventing accidental saves when no edits occur.
  * The save button in drawer overlays is now only enabled when there are unsaved edits, improving clarity and preventing unnecessary save actions.

### CODE REVIEW

File: app/src/views/private/components/overlay-item.vue [hunk 1]
```diff
@@ -542,7 +542,13 @@ function popoverClickOutsideMiddleware(e: Event) {
 		<template #actions>
 			<slot name="actions" />
 
-			<v-button v-tooltip.bottom="getTooltip('save', t('save'))" icon rounded :disabled="!isSavable" @click="save">
+			<v-button
+				v-tooltip.bottom="getTooltip('save', t('save'))"
+				icon
+				rounded
+				:disabled="!isSavable || !hasEdits"
```
Comment (formfcw) [inline app/src/views/private/components/overlay-item.vue]: Let’s move the `hasEdits` condition to the `isSavable` computed, so we can take advantage of this improvement when using shortcuts and also when using other `overlay` types.

File: app/src/views/private/components/drawer-collection.vue [hunk 2]
```diff
@@ -170,7 +189,7 @@ function useActions() {
 			<template #actions>
 				<search-input v-model="search" v-model:filter="presetFilter" :collection="collection" />
 
-				<v-button v-tooltip.bottom="t('save')" icon rounded @click="save">
+				<v-button v-tooltip.bottom="t('save')" icon rounded :disabled="!hasSelectionChanged" @click="save">
```
Comment (formfcw) [inline app/src/views/private/components/drawer-collection.vue:187]: Let’s also move the condition (`hasSelectionChanged`) to the `save()` function to prevent saving with shortcuts (`meta+enter`).

File: app/src/views/private/components/drawer-collection.vue [hunk 3]
```diff
@@ -58,6 +59,24 @@ const layoutSelection = computed<any>({
...
+			initialSelection.value = Array.isArray(internalSelection.value)
+				? [...internalSelection.value]
+				: internalSelection.value;
+		}
+	},
+);
+
+const hasSelectionChanged = computed(() => {
+	return !isEqual(internalSelection.value, initialSelection.value);
+});
```
Comment (formfcw) [inline app/src/views/private/components/drawer-collection.vue]: Let’s move these lines into the existing `useSelection` inline composable below. The contents of your watcher could be moved into the watcher on line 112. Then, the computed could be returned by `useSelection`.

**Review by formfcw — CHANGES_REQUESTED** [review]
Great improvement @robluton :rocket:

Just a few things …

**Review by formfcw — APPROVED** [review]
Thank you @robluton 🎸 

LGTM 🎉
