### PR TITLE
Fix pass options to transport

### LINKED ISSUE #9712: Directus SDK - Transport options ignored
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

According to the documentation, we can pass any headers and params upon initializing the Directus SDK
image

Doing so however has no effect. 

I've checked the code and it seems that those parameters are ignored - https://github.com/directus/directus/blob/main/packages/sdk/src/base/directus.ts#L100

In this piece of code, it seems that the final request only respects the config object, which is the local request data, but it does not include `this._options.transport.*`

### To Reproduce

```
new Directus(url, {
  transport: {
     params: {
       param1: "value1"
     }
  }
})
```

### Errors Shown

_No response_

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16

### What database are you using?

postgres

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by joselcvarela**
Fixes #9712

### CODE REVIEW

File: packages/sdk/src/base/directus.ts [hunk 1]
```diff
@@ -105,6 +105,7 @@ export class Directus<T extends TypeMap> implements IDirectus<T> {
 						},
 					};
 				},
+				...this._options?.transport,
```
Comment (joselcvarela) [inline packages/sdk/src/base/directus.ts:108]: I moved this from line 91 so users could override options.
