### PR TITLE
fix(api): use payload updated with filter event for O2M processing

### LINKED ISSUE #20746: Filter() Hook should be able to modify nested entities
### Describe the Bug

I want to modify on  a filter() hook the payload that's being used to update nested entities. 
For example, imagine a School has a one2Many with Students. From the School detail I can modify the student e.g. name, and I'll receive in the filter() hook a payload like this: 
   `{ id: 1, students: {create:[], delete: [], update: [{id:1, name:"foo bar"}]}`
Now, in the hook I would like to modify it as follows:  
  `{ id: 1, students: {create:[], delete: [], update: [{id:1, name:"foo",surname:"bar"}]}`
and return it. I've tried to do so, but the modification does not have effect: in the Student filter() hook I still get the original, not modified value.

### To Reproduce

Create an o2m relation, modify the payload, and see it doesn't actually update the nested relation entity

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by mahendraHegde**
## Scope

What's changed:

- use filter event modified o2m entities in processO2M while updating entities
- use the eventModified payload in `action` event

## Potential Risks / Drawbacks

NA

## Review Notes / Questions

added below

---

Fixes #20746

### CODE REVIEW

File: api/src/services/items.ts [hunk 1]
```diff
@@ -774,7 +774,7 @@ export class ItemsService<Item extends AnyItem = AnyItem> implements AbstractSer
 						? ['items.update', `${this.collection}.items.update`]
 						: `${this.eventScope}.update`,
 				meta: {
-					payload,
+					payload: payloadAfterHooks,
```
Comment (mahendraHegde) [inline api/src/services/items.ts:777]: does it make sense to use `payloadWithPresets` here?

Comment (paescuj) [reply api/src/services/items.ts]: Yeah, updated to `payloadWithPresets` so the emitted action event payload matches the actual updated value 👍

**Review by paescuj — APPROVED** [review]
Thank you @mahendraHegde!
