### PR TITLE
Expose schema endpoints

### LINKED ISSUE #11481: Expose snapshot/apply endpoints in the API
This allows you to use the schema migration logic from both the CLI and the API. This endpoint will be admin-only.

We should implement the following:

```
/server/schema/snapshot
/server/schema/apply
/server/schema/diff
```

where `diff` will return an array of changes the API will apply on upload of a the snapshot to the apply endpoint.

### LINKED ISSUE #14687: Schema apply attempts to delete collection(s) when re-applying the same snapshot from a different database vendor
### Describe the Bug

First investigation: https://github.com/directus/directus/issues/13383#issuecomment-1191238970
Second investigation: https://github.com/directus/directus/issues/14677#issuecomment-1196331207

When we have a schema snapshot from a SQLite for example, applying on a Postgres database works on the first time. However when we re-apply it again without changing anything, it will mark collections for deletion, when it should say "No changes to apply." instead.

This is not specific to SQLite -> Postgres, but happens between any database vendors as their collections' "schema" is different (refer the first investigation result).

### To Reproduce

1. Apply the following minimal SQLite snapshot on a fresh Postgres database:

    ```yaml
    version: 1
    directus: 9.14.5
    collections:
      - collection: a
        meta:
          accountability: all
          archive_app_filter: true
          archive_field: null
          archive_value: null
          collapse: open
          collection: a
          color: null
          display_template: null
          group: null
          hidden: false
          icon: null
          item_duplication_fields: null
          note: null
          singleton: false
          sort: null
          sort_field: null
          translations: null
          unarchive_value: null
        schema:
          name: a
          sql: CREATE TABLE `a` (`id` integer not null primary key autoincrement)
    fields:
      - collection: a
        field: id
        meta:
          collection: a
          conditions: null
          display: null
          display_options: null
          field: id
          group: null
          hidden: true
          interface: input
          note: null
          options: null
          readonly: true
          required: false
          sort: null
          special: null
          translations: null
          validation: null
          validation_message: null
          width: full
        schema:
          data_type: integer
          default_value: null
          foreign_key_column: null
          foreign_key_table: null
          generation_expression: null
          has_auto_increment: true
          is_generated: false
          is_nullable: false
          is_primary_key: true
          is_unique: false
          max_length: null
          name: id
          numeric_precision: null
          numeric_scale: null
          table: a
        type: integer
    relations: []
    ```

2. It should apply it successfully, as shown here:

   WindowsTerminal_CrYJqgkJ6a

3. However when we re-apply the exact same schema again, it's trying to delete collections (which should not happen):

   WindowsTerminal_iGHUM4HN7Q

When we inspect the `snapshotDiff.collections` in apply-snapshot, we'll see:

```json
[
    {
        "collection": "a",
        "diff": [
            {
                "kind": "D",
                "path": [
                    "schema",
                    "comment"
                ],
                "lhs": null
            },
            {
                "kind": "D",
                "path": [
                    "schema",
                    "schema"
                ],
                "lhs": "public"
            },
            {
                "kind": "N",
                "path": [
                    "schema",
                    "sql"
                ],
                "rhs": "CREATE TABLE `a` (`id` integer not null primary key autoincrement)"
            }
        ]
    }
]
```

### Errors Shown

```
14:33:54 🚨 Cannot read properties of null (reading 'meta')
TypeError: Cannot read properties of null (reading 'meta')
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-snapshot.ts:136:84
    at Array.filter (<anonymous>)
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-snapshot.ts:135:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What version of Directus are you using?

9.14.5 main branch (https://github.com/directus/directus/commit/263ee74408a52fe6d302a004e38dd16d6e6e4055)

### What version of Node.js are you using?

16.15.1

### What database are you using?

PostgreSQL 13.5

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Closes #11481, fixes #14687
Fixes ENG-221, ENG-270
- [x] Expose new `/schema/snapshot`, `/schema/apply`, `/schema/diff` API endpoints
- [x] Add export as YAML
- [x] Update specs
- [x] https://github.com/directus/directus/pull/14713/commits/e906f68710c647b97cfc85d7a93c7c5fd048fdae should be removed when https://github.com/knex/knex-schema-inspector/pull/129 is released in an updated package.
- [x] Verify #14687 is fixed
- [x] Update `knex-schema-inspector` to fix CrDB auto-increment detection https://github.com/knex/knex-schema-inspector/pull/135 
- [x] Revert changes to `.github/workflows/blackbox-main.yml`

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [x] Documentation was added/updated -> directus/docs#62

### CODE REVIEW

File: api/src/services/schema.ts [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+	constructor(options: AbstractServiceOptions) {
+		this.knex = options.knex || getDatabase();
+		this.accountability = options.accountability || null;
+		this.schema = options.schema;
+	}
+
+	async snapshot(): Promise<Snapshot> {
+		if (this.accountability?.admin !== true) throw new ForbiddenException();
+
+		await flushCaches();
```
[the remark this answers is not in the document]
Comment (rijkvanzanten) [reply api/src/services/schema.ts:25]: Yeah good one. There's a bigger change we have to do in caches and Redis use in general, so I think we should do a bigger change across all of that in a separate sprint 👍🏻

**Comment by rijkvanzanten** [comment]
@licitdev Could you help with the blackbox tests for these new endpoints? 🙂

File: api/src/controllers/server.ts [hunk 2]
```diff
@@ -81,4 +88,113 @@ router.get(
 	respond
 );
 
+router.get(
+	'/schema/snapshot',
+	asyncHandler(async (req, res, next) => {
+		const service = new SchemaService({ accountability: req.accountability, schema: req.schema });
```
Comment (licitdev) [inline api/src/controllers/server.ts:94]: We should not pass `schema` in so as to fetch a fresh schema that bypasses cache.

```suggestion
		const service = new SchemaService({ accountability: req.accountability });
```

File: api/src/controllers/server.ts [hunk 3]
```diff
@@ -81,4 +88,113 @@ router.get(
...
+	});
+
+	req.pipe(busboy);
+};
+
+router.post(
+	'/schema/apply',
+	asyncHandler(schemaMultipartHandler),
+	asyncHandler(async (req, res, next) => {
+		const service = new SchemaService({ accountability: req.accountability, schema: req.schema });
```
Comment (licitdev) [inline api/src/controllers/server.ts:170]:
```suggestion
		const service = new SchemaService({ accountability: req.accountability });
```

File: api/src/controllers/server.ts [hunk 4]
```diff
@@ -81,4 +88,113 @@ router.get(
...
+		return next();
+	}),
+	respond
+);
+
+router.post(
+	'/schema/diff',
+	asyncHandler(schemaMultipartHandler),
+	asyncHandler(async (req, res, next) => {
+		const service = new SchemaService({ accountability: req.accountability, schema: req.schema });
```
Comment (licitdev) [inline api/src/controllers/server.ts:185]:
```suggestion
		const service = new SchemaService({ accountability: req.accountability });
```

File: api/src/services/schema.ts [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+
+		const currentSnapshot = await getSnapshot({ database: this.knex, schema: this.schema });
```
Comment (licitdev) [inline api/src/services/schema.ts:27]: There is no need to `flushCache()` as we're fetching a fresh schema that bypasses cache.

```suggestion
		if (this.accountability?.admin !== true) throw new ForbiddenException();

		const currentSnapshot = await getSnapshot({ database: this.knex, schema: this.schema });
```

File: api/src/services/schema.ts [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+
+		return currentSnapshot;
+	}
+
+	async apply(snapshot: Snapshot): Promise<void> {
+		if (this.accountability?.admin !== true) throw new ForbiddenException();
+
+		await flushCaches();
+
+		const currentSnapshot = await getSnapshot({ database: this.knex, schema: this.schema });
```
Comment (licitdev) [inline api/src/services/schema.ts:37]:
```suggestion
		if (this.accountability?.admin !== true) throw new ForbiddenException();

		const currentSnapshot = await getSnapshot({ database: this.knex, schema: this.schema });
```

File: api/src/services/schema.ts [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+			throw new InvalidPayloadException('Failed to apply snapshot');
+		}
+	}
+
+	async diff(snapshot: Snapshot): Promise<SnapshotDiff | null> {
+		if (this.accountability?.admin !== true) throw new ForbiddenException();
+
+		await flushCaches();
+
+		const currentSnapshot = await getSnapshot({ database: this.knex, schema: this.schema });
```
Comment (licitdev) [inline api/src/services/schema.ts:60]:
```suggestion
		if (this.accountability?.admin !== true) throw new ForbiddenException();

		const currentSnapshot = await getSnapshot({ database: this.knex, schema: this.schema });
```

**Review by licitdev — CHANGES_REQUESTED** [review]
The schema that's currently passed in has been fetched in the `req.schema` middleware and it might be outdated as the cache is flushed after. In addition, I think we should reduce the flushing of cache.

Please refer to the following changes in addition to those that I have suggested.

The `getSchema()` can be updated to accept a `bypassCache` flag.
 https://github.com/directus/directus/blob/5895ced76c1d98055ed3112c2ef521f407342808/api/src/utils/get-schema.ts#L17-L20

The following snapshot utils should then be updated to call `getSchema({ database, bypassCache: true })`.

https://github.com/directus/directus/blob/5895ced76c1d98055ed3112c2ef521f407342808/api/src/utils/get-snapshot.ts#L12

https://github.com/directus/directus/blob/5895ced76c1d98055ed3112c2ef521f407342808/api/src/utils/apply-snapshot.ts#L24

Lastly, the flushing of cache from CLI should be removed as well.

https://github.com/directus/directus/blob/5895ced76c1d98055ed3112c2ef521f407342808/api/src/cli/commands/schema/snapshot.ts#L14

https://github.com/directus/directus/blob/5895ced76c1d98055ed3112c2ef521f407342808/api/src/cli/commands/schema/apply.ts#L22

**Comment by licitdev** [comment]
https://github.com/directus/directus/pull/14713/commits/e906f68710c647b97cfc85d7a93c7c5fd048fdae should be removed when https://github.com/knex/knex-schema-inspector/pull/129 is merged.

File: api/src/services/schema.ts [hunk 8]
```diff
@@ -0,0 +1,288 @@
...
+import { ForbiddenException, InvalidPayloadException } from '../exceptions';
+import { AbstractServiceOptions, Snapshot, SnapshotDiff, SnapshotWithHash } from '../types';
+import { applyDiff } from '../utils/apply-diff';
+import { getSnapshot, getVersionedHash } from '../utils/get-snapshot';
+import { getSnapshotDiff } from '../utils/get-snapshot-diff';
+
+const snapshotJoiSchema = Joi.object({
+	version: Joi.number().required(),
+	directus: Joi.string().required(),
+	vendor: Joi.string().valid('mysql', 'postgres', 'cockroachdb', 'sqlite', 'oracle', 'mssql', 'redshift').optional(),
```
Comment (ConnorSimply) [inline api/src/services/schema.ts:17]: Should this Joi validation pull the list of vendors from the Database type definition instead? Pardon me if I am way off the mark, I am still getting acquainted with everything!

Comment (licitdev) [reply api/src/services/schema.ts]: Yes we should! I've just added type validation to the vendor list. Thanks! 👍

**Comment by ConnorSimply** [comment]
This all looks good to me, however, just a UX/DX thing I am curious about. Currently it returns the schema or diff inside the the returned JSON data property `{ "data": {SCHEMA}}`, it would be nice if it just returned the schema/diff at the root level so that you could in theory download the file and upload it without having to get the children data. @rijkvanzanten @licitdev

**Review by connorwinston — APPROVED** [review]
This all looks good to me, however, just a UX/DX thing I am curious about. Currently it returns the schema or diff inside the the returned JSON data property `{ "data": {SCHEMA}}`, it would be nice if it just returned the schema/diff at the root level so that you could in theory download the file and upload it without having to get the children data. @rijkvanzanten @licitdev

**Comment by licitdev** [comment]
@ConnorSimply Nice train of thought! 👍 The `export` query parameter is supported and it allows for a direct download in the selected file format. This info had been added in https://github.com/directus/docs/pull/62. Here's a docs preview link for easy reference https://deploy-preview-62--directus-docs.netlify.app/reference/system/server.html#retrieve-schema-snapshot.

Additionally, a UI within the data studio will be added in the future which should improve the UX of these schema endpoints.

**Comment by ConnorSimply** [comment]
> @ConnorSimply Nice train of thought! 👍 The `export` query parameter is supported and it allows for a direct download in the selected file format. This info had been added in [directus/docs#62](https://github.com/directus/docs/pull/62). Here's a docs preview link for easy reference https://deploy-preview-62--directus-docs.netlify.app/reference/system/server.html#retrieve-schema-snapshot.
> 
> Additionally, a UI within the data studio will be added in the future which should improve the UX of these schema endpoints.

Yeah, I saw the export query param on `snapshot` in the docs but not on `diff` so I wasn't for sure if it was available for that endpoint. I think the docs should make a clear point that it is recommended to use the export param on both endpoints because I can already imagine the discussions coming in about why you cant just upload the snapshot endpoint result to diff/apply.

**Comment by rijkvanzanten** [comment]
I get what you're saying @ConnorSimply, but in this case I think consistency wins over the added DX for this one endpoint. Every endpoint in the API returns the data payload under `data`, so we should do that here as well. That being said, I'm down to open the floor for discussion to drop that `data` top level scope completely API-wide for a next major release 🙂

**Comment by azrikahar** [comment]
> Currently it returns the schema or diff inside the the returned JSON data property `{ "data": {SCHEMA}}`, it would be nice if it just returned the schema/diff at the root level

It was originally returning it at the root level when it was first being developed! However currently the export query does assume it to always be in `res.locals.payload.data` rather than root level `res.locals.payload`, so export won't work if we don't nest it inside `.data`:

https://github.com/directus/directus/blob/dbfedb56fe2efe44187abfd31165faaa79ae7780/api/src/middleware/respond.ts#L63-L79

and since it would be a much bigger (and breaking) API wide change as Rijk mentioned, it was opted not  to be done in this PR 👍

File: api/src/cli/utils/drivers.ts [hunk 9]
```diff
@@ -1,4 +1,6 @@
-export const drivers = {
+import { Driver } from '../../types';
+
+export const drivers: Record<Driver, string> = {
```
Comment (paescuj) [inline api/src/cli/utils/drivers.ts:3]: Sorry, a bit unrelated but WDYT about usuing a `Map` here instead?

```ts
const driversMap: Map<string, Driver> = new Map([
	['PostgreSQL / Redshift', 'pg'],
	['CockroachDB (Beta)', 'cockroachdb'],
	['MySQL / MariaDB / Aurora', 'mysql'],
	['SQLite', 'sqlite3'],
	['Microsoft SQL Server', 'mssql'],
	['Oracle Database', 'oracledb'],
]);

// For "api/src/cli/commands/init/index.ts"
export const drivers = Array.from(drivers.keys());
```

This way the `getDriverForClient` function could be as simple as:
```ts
return driversMap.get(client) || null
```

---

This import here

https://github.com/directus/directus/blob/5ac28ab28b085063f2dc96eccfa5d979867691f2/api/src/cli/utils/create-env/index.ts#L7 should probably changed to the following anyway:
```ts
import { Driver } from '../../../types';
```

Comment (rijkvanzanten) [reply api/src/cli/utils/drivers.ts:3]: Theoretically yes, but those `drivers` are also imported and used in other files, so I don't want to force that refactor through as part of this PR 👍🏻

File: api/src/services/schema.ts [hunk 10]
```diff
@@ -0,0 +1,290 @@
...
+	}).required(),
+});
+
+export class SchemaService {
+	knex: Knex;
+	accountability: Accountability | null;
+
+	constructor(options: Omit<AbstractServiceOptions, 'schema'>) {
+		this.knex = options.knex || getDatabase();
+		this.accountability = options.accountability || null;
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:102]: Lets use `??` for defaults like this to avoid accidental falsey accidents

File: api/src/services/schema.ts [hunk 11]
```diff
@@ -0,0 +1,290 @@
...
+					if (!existingCollection) {
+						throw new InvalidPayloadException(
+							`Provided diff is trying to delete collection "${collection}" but it does not exist. Please regenerate a new diff and try again.`
+						);
+					}
+				} else {
+					const matchingCollection = snapshotWithHash.collections.find((c) => c.hash === diffCollection.hash);
+					if (!matchingCollection) {
+						throw new InvalidPayloadException(
+							`Provided diff to update collection "${collection}" does not match the current instance's collection, indicating it has changed after this diff was generated. Please regenerate a new diff and try again.`
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:149]: > Please regenerate a new diff [...]

This should be _Please generate a new diff_ or _Please regenerate the diff_

File: api/src/services/schema.ts [hunk 12]
```diff
@@ -0,0 +1,290 @@
...
+				}
+			}
+			for (const diffField of payload.diff.fields) {
+				const field = `${diffField.collection}.${diffField.field}`;
+
+				if (diffField.diff[0]?.kind === 'N') {
+					const existingField = snapshotWithHash.fields.find(
+						(f) => f.collection === diffField.collection && f.field === diffField.field
+					);
+					if (existingField) {
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:161]: Tiny tiny nitpick, but I personally prefer putting an empty line between blocks like these. Makes the whole thing just a tad more readable

File: api/src/services/schema.ts [hunk 13]
```diff
@@ -0,0 +1,290 @@
...
+						throw new InvalidPayloadException(
+							`Provided diff is trying to create field "${field}" but it already exists. Please regenerate a new diff and try again.`
+						);
+					}
+				} else if (diffField.diff[0]?.kind === 'D') {
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:166]: I'm wondering if we should put the string values here in an enum so it's a little easier to read, like:

```
if (kind === Kind.DELETE)
```

File: api/src/services/schema.ts [hunk 14]
```diff
@@ -0,0 +1,290 @@
...
+
+		const { error } = applyJoiSchema.validate(payload);
+		if (error) throw new InvalidPayloadException(error.message);
+
+		const currentSnapshot = await this.snapshot();
+
+		const snapshotWithHash = this.getHashedSnapshot(currentSnapshot);
+
+		if (payload.hash !== snapshotWithHash.hash) {
+			for (const diffCollection of payload.diff.collections) {
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:124]: Maybe we should move this bit to a new method `validateDiff` so it's easier to test in separation

File: api/src/services/schema.ts [hunk 15]
```diff
@@ -0,0 +1,290 @@
...
+			);
+		}
+
+		if (
+			payload.diff.collections.length === 0 &&
+			payload.diff.fields.length === 0 &&
+			payload.diff.relations.length === 0
+		) {
+			return;
+		}
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:227]: Should this check be first, so we can skip the validation step if there's no diff to be applied?

File: api/src/services/schema.ts [hunk 16]
```diff
@@ -0,0 +1,290 @@
...
+
+		return diff;
+	}
+
+	getHashedSnapshot(snapshot: Snapshot): SnapshotWithHash {
+		const snapshotHash = getVersionedHash(snapshot);
+
+		return {
+			hash: snapshotHash,
+			...snapshot,
```
Comment (rijkvanzanten) [inline api/src/services/schema.ts:277]:
```suggestion
			...snapshot,
			hash: snapshotHash,
```

File: api/src/types/snapshot.ts [hunk 17]
```diff
@@ -13,20 +15,30 @@ export type Snapshot = {
 export type SnapshotField = Field & { meta: Omit<FieldMeta, 'id'> };
 export type SnapshotRelation = Relation & { meta: Omit<RelationMeta, 'id'> };
 
+export type SnapshotWithHash = Omit<Snapshot, 'collections' | 'fields' | 'relations'> & {
```
Comment (rijkvanzanten) [inline api/src/types/snapshot.ts:18]: Do we need the omit here if it's overridden by the second object? I thought the `&` worked as an "assign" instead of a "merge"

File: api/src/types/snapshot.ts [hunk 18]
```diff
@@ -13,20 +15,30 @@ export type Snapshot = {
...
+	hash: string;
+	collections: (Collection & { hash: string })[];
+	fields: (SnapshotField & { hash: string })[];
+	relations: (SnapshotRelation & { hash: string })[];
+};
+
 export type SnapshotDiff = {
 	collections: {
 		collection: string;
+		hash?: string;
```
Comment (rijkvanzanten) [inline api/src/types/snapshot.ts:28]: Should we make `hash` required everywhere? Looks like it's used quite often 🤔

File: api/src/utils/apply-diff.ts [hunk 19]
```diff
@@ -0,0 +1,305 @@
...
+import { cloneDeep, merge, set } from 'lodash';
+import logger from '../logger';
+import emitter from '../emitter';
+
+type CollectionDelta = {
+	collection: string;
+	diff: Diff<Collection | undefined>[];
+};
+
+export async function applyDiff(
```
Comment (rijkvanzanten) [inline api/src/utils/apply-diff.ts:17]: This could do with a unit test if at all possible 👀

File: api/src/utils/apply-diff.ts [hunk 20]
```diff
@@ -0,0 +1,305 @@
...
+				({ diff }) => (diff[0] as DiffDeleted<Collection>).lhs?.meta?.group === currentLevelCollection
+			) as CollectionDelta[];
+
+		const createCollections = async (collections: CollectionDelta[]) => {
+			for (const { collection, diff } of collections) {
+				if (diff?.[0].kind === 'N' && diff[0].rhs) {
+					// We'll nest the to-be-created fields in the same collection creation, to prevent
+					// creating a collection without a primary key
+					const fields = snapshotDiff.fields
+						.filter((fieldDiff) => fieldDiff.collection === collection)
```
Comment (rijkvanzanten) [inline api/src/utils/apply-diff.ts:50]: I knew this stuff looked familiar 😄 https://github.com/directus/directus/commit/ce104b6a9ccf7b9b1cccf820dbc3f5bbeafe1e94

File: api/src/utils/get-snapshot.ts [hunk 21]
```diff
@@ -61,3 +65,7 @@ function sortDeep(raw: any): any {
 
 	return raw;
 }
+
+export function getVersionedHash(item: Record<string, any>): string {
+	return getSimpleHash(`${JSON.stringify(item)}_${version}`);
```
Comment (rijkvanzanten) [inline api/src/utils/get-snapshot.ts:70]: Alternatively you could use `object-hash` (already a dependency of the API)

File: api/src/utils/get-string-from-stream.ts [hunk 22]
```diff
@@ -0,0 +1,18 @@
+import { Readable } from 'node:stream';
+import { InvalidPayloadException } from '../exceptions';
+
+export function getStringFromStream(stream: Readable) {
```
Comment (rijkvanzanten) [inline api/src/utils/get-string-from-stream.ts:4]: Needs unit test

Comment (rijkvanzanten) [reply api/src/utils/get-string-from-stream.ts:4]: Also lets put this in `@directus/utils` (the new utils package)

File: api/src/utils/sanitize-schema.ts [hunk 23]
```diff
@@ -0,0 +1,76 @@
...
+ * Omit certain database vendor specific collection properties that should not be compared when performing diff
+ *
+ * @param collection collection to sanitize
+ * @returns sanitized collection
+ *
+ * @see {@link https://github.com/knex/knex-schema-inspector/blob/master/lib/types/table.ts}
+ */
+
+export function sanitizeCollection(collection: Collection | undefined) {
+	const omittedPaths = [
```
Comment (rijkvanzanten) [inline api/src/utils/sanitize-schema.ts:15]: Instead of omitting paths, should we rely on an allow-list of keys that we know we use / rely on and use `pick`?

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

File: api/src/controllers/server.ts [hunk 24]
```diff
@@ -81,4 +89,104 @@ router.get(
...
+			return next();
+		} catch (error: any) {
+			busboy.emit('error', error);
+		}
+	});
+
+	busboy.on('error', (error: Error) => next(error));
+
+	busboy.on('close', () => {
+		if (fileCount === 0) return next(new InvalidPayloadException(`No file were included in the body`));
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/controllers/server.ts:168]: IIRC this `were` was primarily meant to fix the `where` typo over in files controller:

https://github.com/directus/directus/blob/dc135f776d3ba453e7764fc5471585bcba0ddc18/api/src/controllers/files.ts#L113

but totally did not notice it's outdated after changing `files` to `file` over here 😄

(also updated the typo in files controller after resolving this)

File: api/src/services/schema.ts (hunk 11 above)
Comment (azrikahar) [reply api/src/services/schema.ts:149]: Changed it to `Please generate a new diff` 👍

File: api/src/services/schema.ts (hunk 10 above)
Comment (azrikahar) [reply api/src/services/schema.ts:102]: Updated!

These lines are technically referred from other existing services, so I assume we should update them as well? Perhaps another PR?

File: tests-blackbox/routes/server/schema.test.ts [hunk 25]
```diff
@@ -0,0 +1,560 @@
...
+		describe('denies non-admin users', () => {
+			it.each(vendors)('%s', async (vendor) => {
+				// Action
+				const response = await request(getUrl(vendor))
+					.post('/server/schema/diff')
+					.send({
+						version: 1,
+						directus: currentDirectusVersion,
+						// TODO: align vendor names
+						vendor: 'postgres',
```
Comment (paescuj) [inline tests-blackbox/routes/server/schema.test.ts:146]: (commenting here only to point out the TODO)

File: api/src/services/schema.ts (hunk 16 above)
Comment (azrikahar) [reply api/src/services/schema.ts:289]: I believe the intent (at the time) was to simply follow the "hash at the front" logic for the collections/fields/relations:

https://github.com/directus/directus/blob/776c84c2634b03010ed6e4663876b98f583d92d9/api/src/services/schema.ts#L295-L300

but in hindsight I do think there isn't an actual purpose in keeping it in front at this point!

File: api/src/services/schema.ts (hunk 10 above)
Comment (paescuj) [reply api/src/services/schema.ts]: > These lines are technically referred from other existing services, so I assume we should update them as well? Perhaps another PR?

That's right! Yes, let's do it in another PR this one is already big 😄🎉

File: api/src/controllers/server.ts [hunk 26]
```diff
@@ -81,4 +89,104 @@ router.get(
 	respond
 );
 
+router.get(
+	'/schema/snapshot',
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/controllers/server.ts:93]: These are actually simply following the `/server/schema/<operation>` path mentioned in the original issue #11481 😄 but in hindsight I should've questioned it before committing. Definitely agree that `/schema` endpoints makes perfect sense!

[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/controllers/server.ts:93]: > These are actually simply following the `/server/schema/<operation>` path mentioned in the original issue #11481 😄 but in hindsight I should've questioned it before committing. Definitely agree that `/schema` endpoints makes perfect sense!

Ah right 👍 Yup, let's change that 😃🚀

File: api/src/utils/get-snapshot.ts [hunk 27]
```diff
@@ -67,5 +67,5 @@ function sortDeep(raw: any): any {
 }
 
 export function getVersionedHash(item: Record<string, any>): string {
-	return getSimpleHash(`${JSON.stringify(item)}_${version}`);
+	return `${hash(item)}_${version}`;
```
Comment (paescuj) [inline api/src/utils/get-snapshot.ts:70]: Could we somehow include the version in the hash?

File: api/src/utils/sanitize-schema.ts (hunk 23 above)
Comment (azrikahar) [reply api/src/utils/sanitize-schema.ts:15]: I think omitting path was first chosen because for Field, the omitting is "simpler" than allowing 😄 but allow-list does seem safer in case there's ever new keys added in knex-schema-inspector side I suppose. Will switch to allow-list 👍

File: api/src/services/schema.ts (hunk 13 above)
Comment (azrikahar) [reply api/src/services/schema.ts:171]: That's a great idea 👍

File: api/src/types/snapshot.ts (hunk 17 above)
Comment (azrikahar) [reply api/src/types/snapshot.ts]: This is definitely not my strong suit, but it seems like removing the `Omit` makes typescript unhappy to build it. Any idea why? 🤔 

I believe I might've actually resorted to `Omit` specifically to resolve this at the time, but unfortunately now I honestly don't remember _why_, really sorry for that 😅

File: api/src/database/helpers/schema/dialects/cockroachdb.ts [hunk 28]
```diff
@@ -11,6 +12,17 @@ export class SchemaHelperCockroachDb extends SchemaHelper {
 		await this.changeToTypeByCopy(table, column, type, options);
 	}
 
+	processField(field: Field): void {
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts:15]: @licitdev do you recall the reasoning for https://github.com/directus/directus/commit/816c998291ecb1fceb7b7f867f94290896a3435f? I assume it's because knex-schema-inspector doesn't "recognize" this for CockroachDB and set the `has_auto_increment` flag, but also wondering if you have a better comment so wanted to tap you in here 😁

[the remark this answers is not in the document]
Comment (licitdev) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts:15]: Yeah it has been awhile, I recall it being along the lines of not correctly detecting `auto_increment` as the default value from the a string along the lines of `nextval(some_sequence_here)`.

File: api/src/services/schema.ts [hunk 29]
```diff
@@ -0,0 +1,290 @@
...
+import { ALIAS_TYPES } from '../constants';
+import getDatabase, { getDatabaseClient } from '../database';
+import { ForbiddenException, InvalidPayloadException } from '../exceptions';
+import { AbstractServiceOptions, DatabaseClients, Snapshot, SnapshotDiff, SnapshotWithHash } from '../types';
+import { applyDiff } from '../utils/apply-diff';
+import { getSnapshot, getVersionedHash } from '../utils/get-snapshot';
+import { getSnapshotDiff } from '../utils/get-snapshot-diff';
+
+const snapshotJoiSchema = Joi.object({
+	version: Joi.number().required(),
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/services/schema.ts:15]: Sounds good to me! 👍

File: api/src/types/snapshot.ts (hunk 17 above)
Comment (azrikahar) [reply api/src/types/snapshot.ts:18]: Oh yeah that makes it much clearer now. I think that was indeed the original reasoning 👍

File: api/src/types/snapshot.ts [hunk 30]
```diff
@@ -1,10 +1,12 @@
 import { Collection } from './collection';
 import { Relation, RelationMeta, Field, FieldMeta } from '@directus/shared/types';
 import { Diff } from 'deep-diff';
+import { DatabaseClient } from './database';
 
 export type Snapshot = {
 	version: number;
 	directus: string;
+	vendor?: DatabaseClient;
```
[the remark this answers is not in the document]
Comment (azrikahar) [reply api/src/types/snapshot.ts:9]: Yeah, particularly because we also allow omitting the `vendor` flag via `force` query param, so old snapshots can still be used if it's their only option.

File: api/src/utils/get-snapshot.ts (hunk 27 above)
Comment (azrikahar) [reply api/src/utils/get-snapshot.ts:70]: It was definitely an oversight! It should probably be `hash({ ...item, version })` instead 🤔

File: api/src/types/snapshot.ts (hunk 30 above)
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/types/snapshot.ts:9]: Great, thanks! 😃 Makes sense 👍

File: api/src/controllers/server.ts (hunk 26 above)
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/controllers/server.ts]: Done! 👍

File: tests-blackbox/routes/server/schema.test.ts (hunk 25 above)
Comment (azrikahar) [reply tests-blackbox/routes/server/schema.test.ts]: @licitdev I assume the aligning here means between the blackbox test's vendor list:

https://github.com/directus/directus/blob/d2b5881a1211fdce9091495756f3ff2e1f571ba6/tests-blackbox/common/get-dbs-to-test.ts#L1-L11

against the current list in the API:

https://github.com/directus/directus/blob/d2b5881a1211fdce9091495756f3ff2e1f571ba6/api/src/types/database.ts#L3

because we added validation based on the API's list:

https://github.com/directus/directus/blob/d2b5881a1211fdce9091495756f3ff2e1f571ba6/api/src/services/schema.ts#L18-L20

so `postgres10`, `mysql5` and `sqlite3` would indeed be caught by the valdation (I do recall we had the sqlite vs sqlite3 discussion on discord). Any thoughts on how do we want to address this TODO?

Based on the current values, I did thought about maybe we can simply strip the numbers (eg. `postgres10` would become `postgres`) to satisfy the blackbox test, such as:

```diff
					.send({
						version: 1,
						directus: currentDirectusVersion,
-						// TODO: align vendor names
-						vendor: 'postgres',
+						vendor: vendor.replace(/[0-9]/g, ''),
						collections: [],
						fields: [],
						relations: [],
					})
```

but not sure if that is too naive/hacky of a solution 😄

Comment (licitdev) [reply tests-blackbox/routes/server/schema.test.ts]: @azrikahar Your solution should work well for now, until there's custom vendors / drivers. 💯  
cc @jaads

File: api/src/utils/get-snapshot.ts (hunk 27 above)
Comment (paescuj) [reply api/src/utils/get-snapshot.ts]: > update: went with hash({ item, version }) for simplicity sake 👍

Exactly how I imagined it 👍 Thanks! ❤️

File: api/src/utils/apply-diff.ts (hunk 19 above)
Comment (azrikahar) [reply api/src/utils/apply-diff.ts:18]: I believe it is still technically tested by `apply-snapshot.test.ts` since we're extracting `applySnapshot`'s inner logic into `applyDiff`, albeit indirectly now. Should we move it into `apply-diff.test.ts` instead?  🤔 though I'm not sure if `applySnapshot` still requires testing after we do so (I assume that's perfectly fine?).

File: .gitignore [hunk 31]
```diff
@@ -19,8 +19,8 @@ dist
 .e2e-containers.json
 coverage
 TODO
-schema.yaml
-schema.json
+/schema.yaml
+/schema.json
```
Comment (paescuj) [inline .gitignore:23]: Limited to `/` in order to be able to create the file `packages/specs/src/components/schema.yaml`.

@rijkvanzanten Do you remember why this has been added? (https://github.com/directus/directus/pull/8349/commits/fc1c87ac02d2622931defbf4b51cc5ce74042f44) Are those expected in another directory?

File: api/src/types/snapshot.ts (hunk 18 above)
Comment (paescuj) [reply api/src/types/snapshot.ts]: Got superfluous with https://github.com/directus/directus/pull/14713/commits/e70fe8e9547588f41e8d98db2d5d03d4191a1033.

File: .gitignore (hunk 31 above)
Comment (rijkvanzanten) [reply .gitignore:23]: It was just so I wouldn't accidentally commit my local schema snapshot debugging attempts 😁

Comment (paescuj) [reply .gitignore:23]: I see, thanks 😁 Should we leave it like this or maybe expand it to `/api/schema.yaml`?

File: api/src/services/schema.ts [hunk 32]
```diff
@@ -0,0 +1,290 @@
...
+			Joi.object({
+				hash: Joi.string().when('diff.0.kind', { is: 'N', then: Joi.optional(), otherwise: Joi.any() }),
+				collection: Joi.string(),
+				field: Joi.string(),
+				diff: Joi.array().items(deepDiffSchema),
+			})
+		),
+		relations: Joi.array().items(
+			Joi.object({
+				hash: Joi.string().when('diff.0.kind', { is: 'N', then: Joi.optional(), otherwise: Joi.any() }),
```
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/services/schema.ts]: Addressed in aec94e0 ✅

File: .gitignore (hunk 31 above)
Comment (rijkvanzanten) [reply .gitignore:23]: The `/` prefix should be fine :

File: api/src/database/helpers/schema/dialects/cockroachdb.ts (hunk 28 above)
[the remark this answers is not in the document]
Comment (licitdev) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts]: Pushed https://github.com/knex/knex-schema-inspector/pull/135. Added a task to update the `knex-schema-inspector` dependency.
Resolving this conversation for now.

[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts]: Awesome, thanks @licitdev! 🚀

File: api/src/services/schema.ts (hunk 14 above)
Comment (paescuj) [reply api/src/services/schema.ts]: Done in [7217049](https://github.com/directus/directus/pull/14713/commits/72170492785f0d061aa11173bf1ccd45cd02fcb3). @rijkvanzanten Is this what you had in mind?

File: api/src/database/helpers/schema/dialects/cockroachdb.ts (hunk 28 above)
[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts]: @licitdev Just to be sure: This means https://github.com/knex/knex-schema-inspector/pull/135 needs to be merged & released before merging this pull request?

[the remark this answers is not in the document]
Comment (licitdev) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts]: Yes, that is required.

[the remark this answers is not in the document]
Comment (paescuj) [reply api/src/database/helpers/schema/dialects/cockroachdb.ts]: Okay, thanks for your confirmation! Sorry, just saw that you've even added this to the PR's description 🙈

File: api/src/services/schema.ts (hunk 14 above)
Comment (azrikahar) [reply api/src/services/schema.ts]: @paescuj Thanks for making the changes! Thoughts on making `validateDiff` a void function like `validateSnapshot`? Just curious whether we should make them behave a tad more consistent (since both are validating stuff in schema service's methods)

File: api/src/utils/validate-snapshot.ts [hunk 33]
```diff
@@ -0,0 +1,80 @@
...
+});
+
+/**
+ * Validates the snapshot against the current instance.
+ **/
+export function validateSnapshot(snapshot: Snapshot, force = false) {
+	const { error } = snapshotJoiSchema.validate(snapshot);
+	if (error) throw new InvalidPayloadException(error.message);
+
+	if (!force) {
```
Comment (azrikahar) [inline api/src/utils/validate-snapshot.ts:59]: Thoughts on replacing this with `if (force) return;` instead?

File: api/src/utils/validate-diff.ts [hunk 34]
```diff
@@ -0,0 +1,150 @@
...
+
+	if (
+		applyDiff.diff.collections.length === 0 &&
+		applyDiff.diff.fields.length === 0 &&
+		applyDiff.diff.relations.length === 0
+	) {
+		return false;
+	}
+
+	if (applyDiff.hash !== currentSnapshotWithHash.hash) {
```
Comment (azrikahar) [inline api/src/utils/validate-diff.ts:66]: Similar to validateSnapshot, how do we feel with doing `if (applyDiff.hash === currentSnapshotWithHash.hash) return false;` instead? (or `if (applyDiff.hash === currentSnapshotWithHash.hash) return;` depending on our discussion in https://github.com/directus/directus/pull/14713#discussion_r1090691487)

File: api/src/services/schema.ts (hunk 14 above)
Comment (paescuj) [reply api/src/services/schema.ts]: Thanks for your feedback, @azrikahar! Absolutely, we should 😃 I'm going to update it according to your suggestions 👍

File: api/src/services/schema.test.ts [hunk 35]
```diff
@@ -0,0 +1,331 @@
...
+
+afterEach(() => {
+	tracker.reset();
+	vi.clearAllMocks();
+});
+
+describe('Services / Schema', () => {
+	describe('snapshot', () => {
+		it('should throw ForbiddenException for non-admin user', async () => {
+			const testSnapshot = {
```
Comment (paescuj) [inline api/src/services/schema.test.ts:42]: Can we dedup all those test data (in this case with line 59)? Same with `snapshotDiffWithHash`, ...

Comment (azrikahar) [reply api/src/services/schema.test.ts:42]: I did thought about it, but there was some discussion on making tests more "contained" within themselves (even if it results in dupes) 🤔 That being said, it's probably less important here so I'll proceed to dedupe them 👍

Comment (paescuj) [reply api/src/services/schema.test.ts:42]: Okay, I see! Whatever feels right for you 👍😃

Comment (azrikahar) [reply api/src/services/schema.test.ts]: Done! 🙌

Comment (paescuj) [reply api/src/services/schema.test.ts]: Nice 🙌  Thanks!

File: api/src/controllers/schema.ts [hunk 36]
```diff
@@ -0,0 +1,120 @@
...
+		const service = new SchemaService({ accountability: req.accountability });
+		await service.apply(req.body);
+		return next();
+	}),
+	respond
+);
+
+const schemaMultipartHandler: RequestHandler = (req, res, next) => {
+	if (req.is('application/json')) {
+		if (Object.keys(req.body).length === 0) throw new InvalidPayloadException(`No data were included in the body`);
```
Comment (rijkvanzanten) [inline api/src/controllers/schema.ts:38]:
```suggestion
		if (Object.keys(req.body).length === 0) throw new InvalidPayloadException(`No data was included in the body`);
```

File: api/src/controllers/schema.ts [hunk 37]
```diff
@@ -0,0 +1,120 @@
...
+	if (!req.is('multipart/form-data')) throw new UnsupportedMediaTypeException(`Unsupported Content-Type header`);
+
+	const headers = req.headers['content-type']
+		? req.headers
+		: {
+				...req.headers,
+				'content-type': 'application/octet-stream',
+		  };
+
+	const busboy = Busboy({ headers });
```
Comment (rijkvanzanten) [inline api/src/controllers/schema.ts:52]: Lets add `limits: { fileSize }` here with a env var for max schema size to process. Related to ENG-491

Comment (rijkvanzanten) [reply api/src/controllers/schema.ts:52]: Alternatively we could hardcode it to a safe upper limit (like 5MB), but this feels like something that should be configurable through env

Comment (rijkvanzanten) [reply api/src/controllers/schema.ts:52]: Actually lets combine this with ENG-491 and just make it a single config option for both 👍🏻

**Comment by rijkvanzanten** [comment]
Looks great, feels great, works great, great job everybody 👏🏻

**Review by rijkvanzanten — APPROVED** [review]

File: api/src/services/schema.ts (hunk 14 above)
Comment (rijkvanzanten) [reply api/src/services/schema.ts]: LGTM as is 👍🏻

**Comment by rijkvanzanten** [comment]
@licitdev You're the last to approve! 

CleanShot 2023-01-31 at 12 30 48@2x

**Review by licitdev — APPROVED** [review]

**Comment by RobinTHOREL** [comment]
hey guys, this feature look like awesome and really exepected. can we find docs somewhere? 👀
