### PR TITLE
Fix reversing of _null, _nnull, _empty and _nempty

### LINKED ISSUE #3448: filters _nnull, _null, _empty, _nempty require boolean value, but don't use it
API requires that we provide boolean for this filter, but it just ignores provided value. Users might think that value can reverse operation. But id does not do anything

https://github.com/directus/directus/blob/5024493f6938586a13b675ae0fde7a5824be0bca/api/src/utils/apply-query.ts#L197

### PR DESCRIPTION
**Pull request by acautin**
When the value given is false, at the moment both `IS NULL` and `IS NOT NULL` are added to the query which means there are never results.

Fixes #3448

### CODE REVIEW

File: api/src/utils/apply-query.ts [hunk 1]
```diff
@@ -576,21 +574,22 @@ export function applyFilter(
 			// See https://github.com/knex/knex/issues/4518 @TODO remove as any once knex is updated
 
 			// These operators don't rely on a value, and can thus be used without one (eg `?filter[field][_null]`)
-			if (operator === '_null' || (operator === '_nnull' && compareValue === false)) {
+
```
Comment (paescuj) [inline api/src/utils/apply-query.ts:577]:
```suggestion
```

**Review by paescuj — APPROVED** [review]
Thanks @acautin!

**Review by rijkvanzanten — APPROVED** [review]
