### PR TITLE
fix styling for specific map buttons

### LINKED ISSUE #20001: Map buttons are styled as white on white
### Describe the Bug

The Buttons for the map input are styled incorrectly

Light:
image

Dark:
image

the issue is in class `mapbox-gl-draw_ctrl-draw-btn`
```css
.mapbox-gl-draw_ctrl-draw-btn {
    border-color: #000000e6;
    color: #ffffff80;
    width: 30px;
    height: 30px
}
```
Removing `color: #ffffff80;` fixes the issue.
as does adding this
```css
.mapbox-gl-draw_ctrl-draw-btn {
    color: unset;
}
```

Light: 
image

Dark:
image

I'm unable to locate exactly where this style is coming. 

### To Reproduce

Open a map interface, switch between dark & light mode

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Boegie19**
## Scope

What's changed:

- Fixed styling being white on white for specific map buttons

## Review Notes / Questions

---

Fixes #20001

### CODE REVIEW

File: app/src/interfaces/map/map.vue [hunk 1]
```diff
@@ -548,3 +548,9 @@ function handleKeyDown(event: any) {
 	opacity: 0;
 }
 </style>
+
+<style lang="scss">
+.mapbox-gl-draw_ctrl-draw-btn {
+	color: unset;
+}
+</style>
```
Comment (paescuj) [inline app/src/interfaces/map/map.vue:556]: I think this should be integrated into the already existing https://github.com/directus/directus/blob/main/app/src/styles/lib/_mapbox.scss

**Review by paescuj — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
