### PR TITLE
fix: adds missing Query and x-metadata to /components/schemas

### LINKED ISSUE #16523: OAS missing x-metadata and Query schemas
### Describe the Bug

After fix https://github.com/directus/directus/pull/16485 `x-metadata` and `Query` wer supposed to be located at `/components/schemas/` but they are missing. This leads to an invalid spec.

image

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 12, Warning count: 0
Errors: 
        -attribute paths.'/revisions'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/permissions'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/users'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/folders'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/activity'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/files'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/operations'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/presets'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/flows'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/items/blogs'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/roles'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.#/components/schemas/Query is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

### To Reproduce

Copy spec from `/server/specs/oas` generated by directus 9.21.0 into any OAS validator

### Errors Shown

_No response_

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

v16.18.1

### What database are you using?

Postgres 15.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by NickUfer**
## Description

Fixes #16523

Related to #16485 

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [X] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

Spec now includes Query and x-metadata. Swagger editor does not throw errors anymore. Version is 9.21.0 because I just copied the compiled JS file into the podman container as I don't want to fiddle with an extra setup

image

### CODE REVIEW

**Comment by cf-ts** [comment]
Hello there, I just corrected the yaml files of the base api in my PR and did not change any code of the dynamic spec file generator. I did not see that within the new location (components.schemas) "Query" and "x-metadata" won't be copied into the final file, sorry for that! (see: https://github.com/directus/directus/pull/16485)

My Problem with this solution here is that it is quite static... So if now the base api would change in a way where a new model is introduced which again is not part of collection but used at some paths, it must be added here hard coded again. So I'm wondering if it would be better to dynamically add all models to the schema section which don't have a "x-collection" record!? I can't really tell because Im new to directus... My approach would be something like this: (see: https://github.com/cf-ts/directus/tree/fix-bug-in-oas-gen)

specifications.ts line 324
`		components.schemas = {};
		// copy schemas without a collection
		if (openapi.components && openapi.components.schemas) {
			for (const schemaName in openapi.components.schemas) {
				const schema: any = openapi.components!.schemas![schemaName];
				if (!schema['x-collection']) {
					components.schemas[schemaName] = schema;
				}
			}
		}`

**Comment by NickUfer** [comment]
Okay, I just tried your solution and it introduces some side effects, it adds too much and adds undefined descriptions, however that happens https://github.com/NickUfer/directus/actions/runs/3515780729/jobs/5891478462

So I would stick for now with the static solution until a maintainer decides what to do. And if another schema is added it would be required to add it to the test in this commit anyways, so you have to touch it either way

**Comment by NickUfer** [comment]
Over night I got another idea how its maybe a mix of your and my solution. We define which schemas we want in a string array and search and add them to components.schemas. This way it is only required to add a string rather than copy pasting the same code again

**Comment by NickUfer** [comment]
https://github.com/directus/directus/blob/1dc7ce4dc0240296248c5d5167782be8d257e29b/api/src/services/specifications.ts#L324-L335

**Comment by cf-ts** [comment]
I think this one is a good idea... 👍
Maybe the maintainers would like to define that List as a const or as a default config setting somewhere and then this can be changed really easy and even a user could override it needed...
I hope it will get merged soon, then the OAS client generation would finally work again! :) 🥇 (I think the automated client generation is a key feature if you use TypeScript, otherwise we would have to write and  maintain  the typings manually...)

File: api/src/services/specifications.ts [hunk 1]
```diff
@@ -323,6 +323,16 @@ class OASSpecsService implements SpecificationSubService {
 
 		components.schemas = {};
 
+		// Always includes the schemas with these names
+		const includeSchemas = ['Query', 'x-metadata'];
```
Comment (br41nslug) [inline api/src/services/specifications.ts:327]: I think moving this to `/api/constants.ts` would be a more appropriate place.

**Review by br41nslug — CHANGES_REQUESTED** [review]
Looking good and solves the errors thrown by swagger 😄

File: api/src/services/specifications.ts (hunk 1 above)
Comment (NickUfer) [reply api/src/services/specifications.ts]: @br41nslug moved to constants.ts :+1:

Comment (br41nslug) [reply api/src/services/specifications.ts]: Awesome! 🚀 It might be getting a little nitpicky but im thinking perhaps `OAS_REQUIRED_SCHEMAS` is little more descriptive 🤔

Comment (NickUfer) [reply api/src/services/specifications.ts]: No problem, changed 👍🏼

**Review by br41nslug — APPROVED** [review]

**Comment by NickUfer** [comment]
@rijkvanzanten or whoever merges in the end, can this be merged already please? I don't want to resolve conflicts because something else was changed

**Comment by br41nslug** [comment]
> I don't want to resolve conflicts because something else was changed

Always make sure maintainers have edit right on the PR branch so we can resolve these conflicts when they come up.
