### PR TITLE
Fix Initial Loading of EditorJS Interface

### LINKED ISSUE #24797: App: Block editor lose value after saving without any changes
### Describe the Bug

On version 11.5.1, the Block Editor interface has a bug which clears the value of the field without changing any field.
Since this cause a change on "[edits](https://github.com/directus/directus/blob/main/app/src/modules/content/routes/item.vue#L67)" of the item, saving the item cause the value on this field to be lost.
This happens either with any other field changed or not.

This seems to be a regression introduced on version 11.5.0 in this PR: https://github.com/directus/directus/pull/24617
On version 11.4.1 this is not reproducible.

I have noticed that this only happens when navigating to the item from another page.
If we open the item directly or if we refresh the page, all seems to work as expected.

### To Reproduce

- Create a collection
- Create a Block Editor field
- Create an item on that collection and put some data on Block Editor field
- Save and go back to collection
- Open the item again and see the Raw Value of Block Editor field is empty and Save Button is enabled
- Hitting save right away or changing any other field and the hitting save, will cause the value on the field to be lost

https://github.com/user-attachments/assets/99289f52-b136-486f-a1ba-f7d4c0af75c1

### Directus Version

v11.5.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres

### PR DESCRIPTION
**Pull request by connorwinston**
When interfaces are mounted, they initially render before receiving any value. The EditorJS interface updates the model value in two ways:

1. Through a batched emit with a 400ms timeout, triggered by the `onChange` event.
2. Through an immediate watcher (`BlockChanged`) that triggers instantly on every block change.

Previously, the immediate watcher (`BlockChanged`) was firing prematurely, emitting updates before EditorJS received the initial field value. This PR resolves the issue by temporarily disabling the immediate watcher until EditorJS has either received its initial value or until the batched emit fires for the first time. This ensures correct behavior even when the initial field value is null.

## Scope

Whats changed?
- Introduces a reactive boolean (`editorjsIsInitialized`) to track whether EditorJS has accepted its initial value.
- Disables the `BlockChanged` watcher from emitting updates until initialization is complete.
- Sets `editorjsIsInitialized` to `true` upon receiving the first non-null initial value or when the batched emit (`onChange`) event fires for the first time.

## Potential Risks / Drawbacks
- When editing a field initially set to null, there will be up to a `400ms` delay before the first emitted value updates the field. This delay only affects the initial input into a null field; subsequent edits or edits to fields already containing a value remain unaffected.

## Review Notes / Questions
- Verify behavior when creating a new item that uses EditorJS Interface.
- Test editing items with both null and pre-set values in EditorJS interface fields to ensure expected behavior.

---

Fixes #24797

### CODE REVIEW

File: app/src/interfaces/input-block-editor/input-block-editor.vue [hunk 1]
```diff
@@ -95,7 +96,9 @@ onMounted(async () => {
 	}
 
 	editorjsRef.value.on(BlockChanged, () => {
-		emitValue(editorjsRef.value!);
+		if (editorjsIsInitialized.value == true) {
```
Comment (robluton) [inline app/src/interfaces/input-block-editor/input-block-editor.vue:99]: any reason not to use type and equality comparison here? `editorjsIsInitialized.value === true`

**Review by robluton — APPROVED** [review]
LGTM
