### PR TITLE
Notify other instances when extension is updated

### LINKED ISSUE #21902: Updating extension is not propagated through instances
### Describe the Bug

When having multiple instances of Directus, for example using `PM2_INSTANCES: 4`, it's possible to see that when updating extension in one instance, this change is not being done on the other instances.

### To Reproduce

- Have an endpoint extension defined in your `EXTENSIONS_PATH`. The endpoint can be `/test` for example and returns 200.
- Start Docker image and set `PM2_INSTANCES` to value greater than 2. I chose 4 so it's faster to test
- Disable extension from Extensions module
- Do multiple requests to the extension endpoint and you will see that sometime gives 200 and other times gives 404.
When hitting the instance were extension was disabled is giving 404 while others are returning 200 because extension is still enabled 

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope
When enabling/disabling extensions, it's only being applied to current instance. If there's multiple instances of Directus running (for example, by default 2 instances are running via PM2 when using Docker image), other instances are not aware of this change.

In this PR we fixed this by publish a message for all other instances listen and reload their extensions.

What's changed:

- Send message to other instances to reload their extensions when one is updated in one instance

## Potential Risks / Drawbacks

- None as I am aware of

## Review Notes / Questions

- None 🤔

---

Fixes #21902

### CODE REVIEW

**Comment by joselcvarela** [comment]
In order to test this I have done:
1. Go to `api` folder
2. Run `PORT=8056 pnpm run cli start`
3. Run `PORT=8057 pnpm run cli start`
4. Run `pnpm run dev`
5. Create a `nginx.conf` with the following content:
```
upstream loadbalance{
  server host.docker.internal:8055;
  server host.docker.internal:8056;
  server host.docker.internal:8057;
}

server{
  listen 80;
  server_name localhost;
  location / {
      proxy_pass http://loadbalance;
  }
}
```
6. Create a `docker-compose.yaml` with the following content:
```
version: '3.1'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
```
7. Run `docker compose up nginx`
8. Access `localhost` and run tests mentioned in the link issue #21902

File: api/src/services/extensions.ts [hunk 1]
```diff
@@ -176,7 +176,9 @@ export class ExtensionsService {
 			return extension;
 		});
 
-		this.extensionsManager.reload();
+		this.extensionsManager.reload().then(() => {
+			this.extensionsManager.notifyOthers();
+		});
```
Comment (paescuj) [inline api/src/services/extensions.ts:181]: This is getting a bit messy IMO 🙊 Can't we just move the publish call into the `reload` method?

Comment (joselcvarela) [reply api/src/services/extensions.ts]: I was doing that so we had more control, but I understand your point 👍

Comment (joselcvarela) [reply api/src/services/extensions.ts:181]: After some tests, if we put the publish call into `reload` method, all instances will be reloading forever. That's because one send to the others and the others send to others, so we cannot put that publish inside `reload`

**Review by licitdev — COMMENTED** [review]
The addition makes sense to me. 👍 Just a thought, notifyReloadRequired or broadcastReloadNotification might provide clearer indication of the purpose of the notification.

On a side note, a changeset should be added.

**Comment by joselcvarela** [comment]
Thank you @licitdev 🙏

File: .changeset/curvy-horses-invite.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@directus/api": patch
+---
+
+Fix update extension when having multiple instances running
```
Comment (paescuj) [inline .changeset/curvy-horses-invite.md:5]:
```suggestion
Fixed state of extensions after enabling/disabling in multiple instances setups
```

File: api/src/services/extensions.ts (hunk 1 above)
Comment (paescuj) [reply api/src/services/extensions.ts]: Well, we would have to break further reloads via an option in the https://github.com/directus/directus/blob/768e9088044ca7be0d79475bbfe695919fd1155a/api/src/extensions/manager.ts#L218 call, but the current solution with the more explicit naming works too 👍

**Review by paescuj — APPROVED** [review]
