### PR TITLE
Reuse S3 client and increase maxSockets

### LINKED ISSUE #18734: S3 Storage at scale starts failing
### Describe the Bug

When using Directus within AWS, and if we don't pass any credentials and let AWS SDK figure those out, these credentials will be fetched from Metadata service. This is done on `new S3Client`.
Because we are creating new client for each request, this means that for each request the AWS credentials are requested.

This works fine if we don't request too much assets but it becomes problematic when requesting multiple ones in parallel like viewing 500 items in App File Library.

Initializing a single client and do all requests with this client, also does not seem to be the right solutions since there's an issue with AWS SDK which starts to slowdown as long as we make more and more requests:
https://github.com/aws/aws-sdk-js-v3/issues/3560

The solution might be to pass a custom agent to AWS SDK and adapt the connections, as suggested in a comment within that issue report:
https://github.com/aws/aws-sdk-js-v3/issues/3560#issuecomment-1484140333

### To Reproduce

- Within AWS, run Directus in a container without any credentials configured.
- Upload more than 500 images
- Go to File Library and choose view 500 items per page

Some images will not appear due to this issue.

### Directus Version

Cloud

### Hosting Strategy

Directus Cloud

### PR DESCRIPTION
**Pull request by licitdev**
Fixes #18734 by reusing the same S3 client but increasing `maxSockets` to `500`.

The default `maxSockets` was `50` and that caused the S3 client to stop responding when additional sockets were required.

Maintained the default `keepAlive`, and added defaults for `connectionTimeout` and `socketTimeout`.

Ref: https://github.com/aws/aws-sdk-js-v3/blob/8ffd6b2e3e488f9827a98c970cd6901e2a3fbe93/packages/node-http-handler/src/node-http-handler.ts#L63-L70

### CODE REVIEW

File: packages/storage-driver-s3/src/index.ts [hunk 1]
```diff
@@ -44,7 +47,24 @@ export class DriverS3 implements Driver {
 	}
 
 	private getClient() {
-		const s3ClientConfig: S3ClientConfig = {};
+		/*
+		 * AWS' client default socket reusing can cause performance issues when using it very
+		 * often in rapid succession, hitting the maxSockets limit of 50.
+		 * We'll customize the requestHandler to get around this.
```
Comment (paescuj) [inline packages/storage-driver-s3/src/index.ts:53]:
```suggestion
		 * The requestHandler is customized to get around this.
```

File: .changeset/beige-olives-beam.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+"@directus/storage-driver-s3": patch
+"@directus/storage": patch
+"tests-blackbox": patch
+---
+
+Reused S3 client and increased maxSockets
```
Comment (paescuj) [inline .changeset/beige-olives-beam.md:7]: "Reused..." sounds as if it is actually no longer the case.
I would probably put it something like this:
```suggestion
Addressed S3 storage scaling issues by using a customized request handler
```

**Review by paescuj — APPROVED** [review]

File: .changeset/beige-olives-beam.md (hunk 2 above)
Comment (licitdev) [reply .changeset/beige-olives-beam.md:7]: Sounds good, thanks! 👍

**Review by rijkvanzanten — APPROVED** [review]
