### PR TITLE
Don't hide but set as readonly

### LINKED ISSUE #14832: Missing relationship field in side drawer.
### Describe the Bug

I'll explain as an example:

Two collections: Orders and OrderLines.
And order has one2many order lines.

When viewing a specific order line and clicking on its' order, the drawer opens up to display all the fields. However I am unable to view what other order lines are on that order.

### To Reproduce

As mentioned above.

### Errors Shown

_No response_

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

### PR DESCRIPTION
**Pull request by u12206050**
## Description

"unhides" relationship field and sets to readonly

Fixes #14832 

## Type of Change

- [x] Bugfix?
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

### CODE REVIEW

File: app/src/views/private/components/drawer-item.vue [hunk 1]
```diff
@@ -177,8 +177,11 @@ export default defineComponent({
 
 		const fields = computed(() => {
 			if (props.circularField) {
-				return fieldsWithPermissions.value.filter((field: Field) => {
-					return field.field !== props.circularField;
+				return fieldsWithPermissions.value.map((field: Field) => {
+					if (field.field === props.circularField) {
+						field.meta!.readonly = true;
```
Comment (rijkvanzanten) [inline app/src/views/private/components/drawer-item.vue:182]: I think there's a tiny change `meta` is `null` (when it's a database-only field with no directus_fields record). Lets use `set` from lodash to prevent an error when `meta` doesn't exist.

```suggestion
						set(field, 'meta.readonly', true);
```

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]
