### PR TITLE
Import config.js file as ESM

### LINKED ISSUE #19555: ESM error when using a config.js file
### Describe the Bug

If you have a `config.js` file and are on the latest version of 9.x, you'll be unable to deploy a Docker image.
This may be fixed in 10, but many of use are stuck on 9 without an enterprise license.

It seems like it's trying to `require` when it imports the config here: https://github.com/directus/directus/blob/0deadb9062cd4d360cb61d1a4a09de6c0988267f/api/src/env.ts#L15

And then it blows up here: https://github.com/directus/directus/blob/0deadb9062cd4d360cb61d1a4a09de6c0988267f/api/src/env.ts#L403

Screenshot 2023-08-29 at 1 34 35 PM

### To Reproduce

1. Docker file using latest 9.x: `FROM directus/directus:9.26.0`.
2. Docker file referencing a config file with `COPY ./config.js .`
3. Have a fairly simple ESM `config.json`:
```
import fs from 'fs';
import path from 'path';

export default function (env) {
    // Get the JSON file name from the environment
    const jsonFileName = '/vault/secrets/secrets.json';

    // Read the JSON file and parse its contents
    const jsonData = fs.readFileSync(path.resolve(jsonFileName));
    const json = JSON.parse(jsonData);

    for (let prop in json) {
        env[prop] = json[prop];
    }

    // Log the environment variables that were set
    return env;
};
```

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
Closes #19555

### CODE REVIEW

File: api/src/env.ts [hunk 1]
```diff
@@ -380,37 +381,36 @@ export const getEnv = () => env;
...
 
-function processConfiguration() {
+async function processConfiguration() {
 	const configPath = path.resolve(process.env['CONFIG_PATH'] || defaults['CONFIG_PATH']);
 
 	if (fs.existsSync(configPath) === false) return {};
 
 	const fileExt = path.extname(configPath).toLowerCase();
 
 	if (fileExt === '.js') {
```
Comment (br41nslug) [inline api/src/env.ts:403]:
```suggestion
	if (['.js', '.cjs', '.mjs'].includes(fileExt)) {
```

let's allow for the CJS fallback same as for extensions.

**Review by br41nslug — APPROVED** [review]

File: api/src/env.ts [hunk 2]
```diff
@@ -380,37 +382,37 @@ export const getEnv = () => env;
...
 	const configPath = path.resolve(process.env['CONFIG_PATH'] || defaults['CONFIG_PATH']);
 
 	if (fs.existsSync(configPath) === false) return {};
 
 	const fileExt = path.extname(configPath).toLowerCase();
 
-	if (fileExt === '.js') {
-		const module = require(configPath);
-		const exported = module.default || module;
+	if (['.js', '.cjs', '.mjs'].includes(fileExt)) {
```
Comment (azrikahar) [inline api/src/env.ts:404]: Very side tangent here, but should we use this extensions constant over here?

https://github.com/directus/directus/blob/0c56c46fdf8dfd0a40ae04b3ec6270c42edf1077/packages/constants/src/files.ts#L1

this is a rather random question, shouldn't really block this PR at all as it works as is 👍

**Review by azrikahar — APPROVED** [review]

File: api/src/env.ts (hunk 2 above)
Comment (paescuj) [reply api/src/env.ts]: Nice 🚀❤️

File: api/src/env.ts [hunk 3]
```diff
@@ -4,16 +4,22 @@
...
 import path from 'path';
+import getModuleDefault from './utils/get-module-default.js';
 import { requireYAML } from './utils/require-yaml.js';
 import { toBoolean } from './utils/to-boolean.js';
 
 const require = createRequire(import.meta.url);
 
+// casting as string[] so we can use .includes() properly
+const configFileExtensions = JAVASCRIPT_FILE_EXTS as unknown as string[];
+
```
Comment (paescuj) [inline api/src/env.ts:22]:
```suggestion
```

File: api/src/env.ts [hunk 4]
```diff
@@ -380,37 +386,37 @@ export const getEnv = () => env;
...
 
 	if (fs.existsSync(configPath) === false) return {};
 
-	const fileExt = path.extname(configPath).toLowerCase();
+	const fileExt = path.extname(configPath).toLowerCase().substring(1);
 
-	if (fileExt === '.js') {
-		const module = require(configPath);
-		const exported = module.default || module;
+	if (configFileExtensions.includes(fileExt)) {
```
Comment (paescuj) [inline api/src/env.ts:408]:
```suggestion
	if ((JAVASCRIPT_FILE_EXTS as readonly string[]).includes(fileExt)) {
```

**Review by paescuj — COMMENTED** [review]
I'd do the type assertion for `JAVASCRIPT_FILE_EXTS` inline since it's only used there and use `readonly` instead of `unknown` to satisfy the assertion.

File: api/src/env.ts (hunk 4 above)
Comment (br41nslug) [reply api/src/env.ts:408]: I had it inlined at first but that makes it a lot less readable and does not leave us the option to explain why we did this weird trick. If we're going inline i think i'd rather type cast the extension like 
```suggestion
	if (JAVASCRIPT_FILE_EXTS.includes(fileExt as any)) {
```

Comment (paescuj) [reply api/src/env.ts:408]: Why `any`? `as readonly string[]` satisfies TS so we don't loose type safety and it's pretty self-explanatory, IMO.

Comment (br41nslug) [reply api/src/env.ts:408]: > Why any?

Because its the TS workaround that sticks closest to the approach you'd take if it wasnt a `readonly array` namely just `ARRAY.includes(value)`. Just because it has an `any` in there doesnt mean it loses type safety in any meaningful way in this case.

I strongly disagree about it being "self-explanatory" but it also doesnt really matter how we cast it the effect is the same, pick one 😄

Comment (paescuj) [reply api/src/env.ts:408]: - IMO, `any` should always be the last resort, it's also considered bad practice by `typescript-eslint`, see [`no-explicit-any`](https://typescript-eslint.io/rules/no-explicit-any) - we've disabled this rule for now (with the hope that we can clean this up someday):
  https://github.com/directus/directus/blob/0c56c46fdf8dfd0a40ae04b3ec6270c42edf1077/.eslintrc.js#L50-L51
- You lose type safety because you wouldn't notice anymore if `fileExt` changes, e.g. from `string` to `object`
- `as readonly string[]` only works because it's compatible with the type of `JAVASCRIPT_FILE_EXTS` so we don't lose type safety with this. Try to change it to e.g. `readonly number[]`, TS would complain.
- `(JAVASCRIPT_FILE_EXTS as readonly string[]).includes(fileExt)` feels self-explanatory to me because it shows:
  - `JAVASCRIPT_FILE_EXTS` it's most likely a constant
  - that is compatible with `readonly string[]` so we see it's really a read only const with string compatible content
  - it can be compared to `fileExt` so fileExt is a string

File: api/src/env.ts [hunk 5]
```diff
@@ -362,7 +365,7 @@ const typeMap: Record<string, string> = {
 let env: Record<string, any> = {
 	...defaults,
 	...process.env,
-	...processConfiguration(),
+	...(await processConfiguration()),
```
Comment (u12206050) [inline api/src/env.ts:368]: This one await will impact all other files that import this to also become asynchronous.
This already hinders us from bundling Directus into a single executable. Recommend to encase this in an exported function instead.
