### PR TITLE
Fix return error for GraphQL mutations

### LINKED ISSUE #7651: Error thrown in custom before hook not propagating to graphql output
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Originating from discussion #7622.

A custom hook for `items.create.before` is registered. An error might be thrown inside the hook.

Assume running mutation `create_articles_item` with a payload that triggers an error inside the hook. The response body of the mutation is just:
```
{ data: { create_articles_item: null } }
```

It contains no other fields, in particular not `errors`.

### To Reproduce

Register a hook, for example (adapted from [docs](https://docs.directus.io/guides/api-hooks/#before)):

```javascript
module.exports = function registerHook({ exceptions }) {
	const { InvalidPayloadException } = exceptions;

	return {
		'items.create.before': async function (input) {
			throw new InvalidPayloadException("error inside custom hook");
		},
	};
};
```

Execute a graphql mutation which triggers the hook (i.e. which creates an item).

### What version of Directus are you using?

v9.0.0-rc.91

### What version of Node.js are you using?

v12.22.4

### What database are you using?

sqlite3 v3.36.0

### What browser are you using?

Firefox, Chromium

### What operating system are you using?

arch linux

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by joselcvarela**
Fixes #7651 
Fixes #7622

### CODE REVIEW

File: api/src/services/graphql.ts [hunk 1]
```diff
@@ -971,7 +971,7 @@ export class GraphQLService {
 				}
 			}
 		} catch (err: any) {
-			this.formatError(err);
+			return this.formatError(err);
```
Comment (rijkvanzanten) [inline api/src/services/graphql.ts:974]: 🤦🏻

**Review by rijkvanzanten — APPROVED** [review]
